### ISSUE TITLE
jackstraw error in fake.x

### ISSUE THREAD

**Issue by maximilianh** [satijalab/seurat#10]
I'm getting this when running jackStraw(nbt,num.replicate = 200,do.print = TRUE) :

Error in fake.x[rand.genes, r1.use:r2.use] : subscript out of bounds
Calls: jackStraw -> jackStraw -> sapply -> lapply -> FUN -> jackRandom

My complete script:

library(methods)
suppressWarnings(suppressMessages(library(Seurat)))
nbt.data=read.table("temp.tab",sep="     ",header=TRUE,row.names=1)
nbt.data=log(nbt.data+1)
nbt=new("seurat",raw.data=nbt.data)
nbt=setup(nbt,project="NBT",min.cells = 3,names.field = 2,names.delim = "_",min.genes = 500,is.expr=1,)
nbt=mean.var.plot(nbt,y.cutoff = 2,x.low.cutoff = 2,fxn.x = expMean,fxn.y = logVarDivMean)
nbt=pca(nbt,do.print=FALSE)
nbt=jackStraw(nbt,num.replicate = 200,do.print = TRUE) 

the input file temp.tab is here:
http://hgwdev.soe.ucsc.edu/~max/seurat/temp.tab

Any ideas what could be causing this?

**Comment by KatieONell** [comment]
I got the same error because I left num.pc as 30 but only had 10 PCs to work with. After I fixed that, though, I got the error "Error in fake.pcVals[, x] : incorrect number of dimensions". I tried copying the function directly into my code instead of calling jackStraw(object), but now I'm getting "Error in match.fun(FUN) : object 'empP' not found."

**Comment by andrewwbutler** [comment]
@KatieONell you're right about the number of PCs causing the initial issue. I've put in some error checking to make sure that doesn't happen anymore.  empP is an internal package function which is why it isn't being found when you copy out the function.

**Comment by KatieONell** [comment]
Thanks! Any advice on how to deal with this one: 
"Error in fake.pcVals[, x] : incorrect number of dimensions" ?

**Comment by andrewwbutler** [comment]
Hmm. Could you post an example that causes this error?

**Comment by KatieONell** [comment]
Here's the seurat object:
[Seurat_object.zip](https://github.com/satijalab/seurat/files/328525/Seurat_object.zip)
and this line of code leads to the error: jackStraw(nbt2, num.pc=5, prop.freq=.015)

**Comment by andrewwbutler** [comment]
Ok, so it turns out that if you have a very small number of genes (34 in your case) and prop.use is set too low, the random sampling procedure ends up sampling nothing. This propagates through and eventually causes the error that you were getting. I've put in additional checks for that and it will now default to choosing 3 genes for every random sampling in the event of low gene numbers. Reinstalling from github should resolve the issue.

**Comment by KatieONell** [comment]
It's working now, thank you!

**Comment by KatieONell** [comment]
This is a minor issue, but in the error checking for num.pc, the conditional currently is:
if (num.pc >= ncol(object@pca.rot)) -> change the number of pcs; but it should be
if (num.pc > ncol(object@pca.rot)) [just greater than, not greater than or equal to; it's been changing mine when I set num.pc to ncol(object@pca.rot)]

**Comment by andrewwbutler** [comment]
Good point. It's not actually changing anything in your case but there's no reason for that warning message when they're equal. I went ahead and made the change.
