### ISSUE TITLE
Error with ALRA assay data

### ISSUE THREAD

**Issue by mpmorley** [satijalab/seurat#1016]
I'm able to RunALRA but FindVariableFeatures on that object with alra assay returns an error. 

```R
pbmc_small_alra <- RunALRA(object = pbmc_small)
pbmc_small_alra <- FindVariableFeatures(pbmc_small_alra)
Error in as(object = object, Class = "dgCMatrix") : 
  no method or default for coercing “dsyMatrix” to “dgCMatrix”
```

**Comment by linqiaozhi** [comment]
After running ALRA, the Seurat object has an assay called `alra` that contains the imputed data. However, this assay does not have a `count` slot, which is what the FindVariableFeatures's method `vst`  (now default in Seurat 3.0) expects. This method for choosing variable features uses the count data, and since it is not in the `alra` assay, it fails. 

One possible solution is to just set the "count" slot in the "alra" assay to be the "count" slot in the "RNA" assay. However, then the user would think that they are choosing the variable genes using the imputed data, but in reality they are not--they are using the original count data. So, that is not ideal.

It's not clear to us if the VST method would actually work on the scaled data (or, the imputed scaled data). In the past, we have used the "mean.var.plot" method for finding variable genes (default in Seurat 2.0), which does not operate on the count data, and hence can be used on the imputed data. Indeed, if the user just sets the `selection.method` to `mean.var.plot`, then it runs as is (@mpmorley, this should fix your problem). 

Perhaps the best option is to give the user a warning if FindVariableGenes is called when using an "alra" assay. For example, "The VST selection method uses count data and does not use the ALRA imputed data; please use mean.var.plot instead, if you would like to find the variable genes based on the imputed data."

**Comment by satijalab** [comment]
I agree that the counts slot for an imputation assay should be the same as the original data

**Comment by stefanonard85** [comment]
Hello all, 

I am using ALRA, actually works fine but  the count slot is empty this is why when I run SCT transform it uses the count slot on the SCT, therefore I get always the same results... is there a solution to this?
