### ISSUE TITLE
FindAllMarkers() results are not saved into the object

### ISSUE THREAD

**Issue by maximilianh** [satijalab/seurat#1019]
I believe that most of the Seurat functions add their results to the object. This is very handy, as one can save the object and send it to someone else. In many ways, the Seurat object itself has become a file format. Also, as a result, it can be easily converted to Cellranger, Bioconductor or Scanpy objects.

However, the FindAllMarkers() function is different, it does not save the result. There is not even an option to save the result. This may be to save space, but it could save at least the top n genes.

I wonder if it could be a good idea to add an option one day that adds the FindAllMarkers() and FindMarkers() result to the Seurat object.

**Comment by maximilianh** [comment]
One reason that this was a not a major issue originally may be that the runtime with the lower number of cells was not a big deal. These days with 10X datasets, calculating markers can take quite a while, so it may be good to keep the result.

**Comment by timoast** [comment]
One reason we return the marker dataframe rather than saving it within the Seurat object is that currently there are no functions in Seurat that need to access the list of markers. If, in the future, we were to add functionality that required a list of markers (like gene set enrichment analysis), it would then make sense to place the marker output within the object.

I agree that it often is a good idea to save the list of markers, but there are other ways of doing that that don't require the markers to be stored within the object (write it to a text file, for example).

You are of course free to save anything you like in the `misc` slot, eg:

```r
object@misc$markers <- FindAllMarkers(object)
```

**Comment by maximilianh** [comment]
OK. So third parties who want to do gene set enrichment analysis on Seurat objects can't really do that right now. That's OK, I just wanted to make sure. 

Good, I'll suggest to my users to save the markers in the slot "@misc$markers" @mxposed @pcm32

**Comment by maximilianh** [comment]
Writing the markers to a text file means that they live outside of the Seurat object. This means that I should not recommend to users to treat the Seurat object as the main way of saving and exporting the data. I rather would have to recommend ... I don't know... scanpy's h5ad format? I don't really know what to recommend. 

If they keep everything in text files, these are slow to load and it's very hard to recreate the Seurat object from them.
