### ISSUE TITLE
FindTransferAnchors: Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE)

### ISSUE THREAD

**Issue by JonThom** [satijalab/seurat#1078]
I am trying to use `FindTransferAnchors` between an integrated query dataset and a reference dataset, as in the Seurat 3.0 pancreas vignette.

Both objects have been through NormalizeData, FindVariableFeatures, ScaleData and RunPCA.

The function fails with 

`Performing PCA on the provided reference using 2000 features as input.
Projecting PCA
Finding neighborhoods
Finding mutual nearest neighborhoods
        Found 3854 anchors
Filtering Anchors
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE): invalid character indexing`

A colleague encountered the same problem independently using different datasets. 
We were able to get `FindTransferAnchors` to work by setting `project.query = T`

**Comment by andrewwbutler** [comment]
Hi,

Are the 2000 features you're using present/scaled in both datasets?

**Comment by rlittman16** [comment]
Hi,

I had the same issue, is there a way to quickly check if all of the features are present in both of the datasets?

They should be as the chosen features are overlapping DEGs between the two data sets.

**Comment by brianpenghe** [comment]
You can use the intersect:
intersect(unlist(object@raw.data@Dimnames[1]),YourFeatures)

**Comment by timoast** [comment]
Hi, I'm going to close this issue now as we haven't heard back from you @JonThom, but if you see the same error with the latest version of Seurat from the develop branch, please reopen the issue or create a new issue

**Comment by widsquid** [comment]
Hello I am having fun with new features thanks! Unfortunately I am stuck now. I am seeing the same error at this stage following the PBMC scATAC-seq Vignette with my own datasets.

transfer.anchors <- FindTransferAnchors(reference = pbmc.rna, query = pbmc.atac, features = VariableFeatures(object = pbmc.rna), reference.assay = "RNA", query.assay = "ACTIVITY", reduction = "cca")

...
Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE): invalid character indexing

I tried the project.query = TRUE and still returned the same error. not sure if the 2000 features I am using are present/scaled in both datasets as I thought they were generated by functions in the pipeline. Any advice on how to find the Features/check for this or otherwise proceed would be much appreciated.
thanks
