### ISSUE TITLE
v3.0 Problem removing Legend and Axes in FeaturePlot

### ISSUE THREAD

**Issue by SFF-singecell-user** [satijalab/seurat#1080]
Hello,
I am trying to remove the legends and axes from the FeaturePlot using v3.0
This is what I tried: 
>plot <- FeaturePlot(object = seuratobject, features = gene.list1) + NoLegend() + NoAxes()
> print(plot)

But it still return a plot that includes legends and axes.
Thanks in advance for any help.

**Comment by timoast** [comment]
When you plot >1 feature, FeaturePlot combines the plots using `cowplot::plot_grid`. After the plots have been combined you can't change things like the legend and axes. Instead you can use the `combine=FALSE` argument, so that the plots are not combined, then change each individual plot, then combine the altered plots. Here is an example with the pbmc dataset:

```r
library(Seurat)

p <- FeaturePlot(pbmc_small, head(VariableFeatures(pbmc_small)), combine = FALSE)

for(i in 1:length(p)) {
  p[[i]] <- p[[i]] + NoLegend() + NoAxes()
}

cowplot::plot_grid(plotlist = p)
```
<img width="660" alt="screen shot 2019-01-22 at 1 01 45 pm" src="https://user-images.githubusercontent.com/4591688/51555572-e714fd80-1e45-11e9-8886-561ad5c71040.png">

**Comment by diazdc** [comment]
Would it be possible to bring back the no.axes and no.legend arguments to FeaturePlot() and DimPlot()? Both seem like a much more elegant way to solve this problem.

**Comment by timoast** [comment]
Yes, we now use [patchwork](https://patchwork.data-imaginist.com/index.html) for combining plots which allows easier modification of the individual panels using the `&` operator
