### ISSUE TITLE
RunPCA rev.pca

### ISSUE THREAD

**Issue by harinipras** [satijalab/seurat#1087]
Hi Seurat Team,

I looked at the RunPCA documentation and it said use rev.pca = TRUE if my data is gene(rows) x cells(columns). But that's how most datasets are arranged including the demonstrated dataset pbmc, but I've not seen the option used anywhere else. Can you help me out with this?

**Comment by rcalandrelli** [comment]
There is the issue #648 about this where I have just left a comment. The first question was exactly the same, Seurat team confirmed what's in the documentation, but it is not clear why they do not set rev.pca=TRUE in the tutorial, since the matrix PBMC that is used it is gene by cell. Hopefully they will clear this up!

**Comment by satijalab** [comment]
Sorry this is unclear. Yes, rev.pca should be set to FALSE. The documentation refers to the data that is passed into the irlba function itself (which is the transpose of the scale.data slot).
