### ISSUE TITLE
DoHeatmap() in Seurat v3.0: subscript out of bounds

### ISSUE THREAD

**Issue by mkm79** [satijalab/seurat#1088]
Hello,

I have run the pipeline as described in the Guided Clustering Tutorial for Seurat v3, and am having the following issue when I try to make a heatmap.

When I run 
`DoHeatmap(object = ds, features = top10$gene)`

I get this error:
```
Error in GetAssayData(object = object, slot = slot)[default.vars, cells,  : 
  subscript out of bounds
```
Could you please advise on what might be causing this and suggest how to fix it? Thank you.

**Comment by tmccra2** [comment]
I am also having the same problem and got the same error

**Comment by andrewwbutler** [comment]
Hi,

This is likely happening because you are trying to plot features that haven't been scaled (`DoHeatmap` by default plots from the `scale.data` slot). I've just pushed a commit that better 
checks for this and issues a warning for those that aren't available. 

To fix, try rescaling your data, making sure to include all the features you want to plot in this heatmap.

**Comment by tmccra2** [comment]
Fixed it! Thanks a bunch!
