### ISSUE TITLE
UMAP for clustering?

### ISSUE THREAD

**Issue by vagnec** [satijalab/seurat#1099]
Hi,

I used Seurat on a small-medium dataset (300 cells). I'm more convinced by the clustering based on UMAP than the one based on PCA (from a biological point of views, it makes more sense). However, I have a doubt: is it "correct" to use UMAP coordinates as an input for SNN-clustering, or it is wrong ?

Thank you for your answer

**Comment by TomKellyGenetics** [comment]
You can pass umap components to `FindClusters` provided that you've run `RunUMAP` first.

```R
FindClusters(object = pbmc_small, reduction.type = "umap")
```

**Comment by vagnec** [comment]
Thank you TomKellyGenetics. But I was wondering if there is a rational to use PCA instead of UMAP?

**Comment by TomKellyGenetics** [comment]
You can set `reduction.type` to `"pca"` or `"tsne"` as well. When I run clustering, you should also consider which distance metric to use (`metric` parameter in `RunUMAP` or `RunTSNE`). Both tSNE and UMAP are run by default on the pre-computed principal components rather than the entire dataset (mainly for computational efficiency). It is up to you to decide which to use based on your application. I would run `FindClusters` on the same dimension reduction that you will use to plot the data so the clusters match the co-ordinate space you will use to plot.
