### ISSUE TITLE
Equivalent TransferIdent() function in Seurat v3?

### ISSUE THREAD

**Issue by veravevo** [satijalab/seurat#1108]
Hi there,
I'm trying to update my scripts from v2.3.4 to Seurat v3, and I have been looking for an equivalent of the TransferIdent()-function to transfer metadata between Seurat objects. What would be the equivalent to this function in Seurat v3?

Thank you so much! 
Cheers, Vera

**Comment by timoast** [comment]
Hi, you can achieve this in version 3 by doing:

```r
object2 <- AddMetaData(object = object2, metadata = object1$data.to.transfer, col.name = 'new.metadata')
```

Assuming same cell names in `object1` and `object2`

**Comment by RachelLukowicz** [comment]
Hi, just had a follow up question here - Is there anyway to have a function similar to keep.existing within TransferIdent in V3? I want to pull the metadata cluster idents column from object 1 into object 2. All cells from object 1 are present in object 2, but object 2 has some cells that are not present in object 1. I can't run the above function because the metadata columns are not the same length. Thanks!
