### ISSUE TITLE
Error in CreateSeuratObject - unused aguments

### ISSUE THREAD

**Issue by prmunn** [satijalab/seurat#1134]
Attempting to go through the first tutorial (Seurat - Guided Clustering Tutorial) - I'm able to run the first couple of commands:

```r
library(Seurat)
library(dplyr)
pbmc.data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19/")
```

But when I run 

``` r
pbmc <- CreateSeuratObject(raw.data = pbmc.data, min.cells = 3, min.genes = 200, project = "10X_PBMC") command I get:

Error in CreateSeuratObject(raw.data = pbmc.data, min.cells = 3, min.genes = 200,  : 
  unused arguments (raw.data = pbmc.data, min.genes = 200)
```
Please help

**Comment by andrewwbutler** [comment]
Hi,

Have you installed the pre-release v3 Seurat?  You can check with
```r
packageVersion(pkg = "Seurat")
```
If this returns 3.0.0.9000, then you're using v3. To proceed with that version, please see the tutorial [here](https://satijalab.org/seurat/pbmc3k_tutorial_v3.html). In this case, `raw.data` has been renamed to `counts` and `min.genes` to `min.features`. 

Otherwise, you'll need to reinstall v2 via CRAN:
```r
install.packages("Seurat")
```

**Comment by prmunn** [comment]
Yes, I'm using the V3 release. Just tried the CreateSeuratObject command in the new tutorial and it appears to be working. Thank you for getting back to me so quickly.
