### ISSUE TITLE
Seurat3 FindVariableFeatures/VariableFeaturePlot output looks incorrect

### ISSUE THREAD

**Issue by aapetti** [satijalab/seurat#1147]
Hello!

I ran FindVariableFeatures in Seurat 3 using two different methods, "mean.var.plot" and the newer "vst." I then plotted the output using VariableFeaturePlot. The result looked reasonable for the "mean.var.plot" results, but very strange for the "vst" results (and generated a warning: "Transformation introduced infinite values in continuous x-axis"). The vst plot is attached. Perhaps I need to change the axes from the default? Any advice you can provide would be greatly appreciated!

Many thanks in advance,
Allegra
[Cycling.variableGenes.190215.pdf](https://github.com/satijalab/seurat/files/2870128/Cycling.variableGenes.190215.pdf)

**Comment by ChristophH** [comment]
The plot looks fine. For the 'vst' method, dispersion has a different meaning - it's the variance after a regularized variance stabilizing transformation. First, for every gene an expected variance is determined based on the overall mean-variance relationship in the data. Second, given the expected variance, the observed counts are standardized.

The warning suggests that there were genes with mean <= 0 that caused problems because the x-axis is on log10 scale. I don't know why that would be the case, but you can check the raw values afterwards with the HVFInfo function.

**Comment by aapetti** [comment]
Thank you very much for your reply!
