### ISSUE TITLE
FindMarkers on Integrated Data: Seurat v3

### ISSUE THREAD

**Issue by silpasuthram** [satijalab/seurat#1168]
Genes that have zero expression in RNA assay can get slightly positive/negative values in the integrated data (see plots below). This affects the calculation of pct.1 and pct.2 . It inflated pct of the query dataset and can affect differential expression results.  Is there a fix for it? Also, can the thresh.min be made a user defined property?  Currently it is set to 0.

![image](https://user-images.githubusercontent.com/12534106/53186313-919f4e00-35b5-11e9-923c-c9a628eca1b2.png)
![image](https://user-images.githubusercontent.com/12534106/53186324-9b28b600-35b5-11e9-9d3a-4541de91ed26.png)

**Comment by satijalab** [comment]
When comparing data across conditions (for example, ctrl v. drug), you should not run FindMarkers on the integrated data, but on the original dataset (assay = "RNA"). This is because the integration will aim to remove differences across samples so that shared populations align together. 

This is why we treat sample comparison as a two-step process. First, we integrate datasets together to consistently identify common cell populations across datasets. Second, we perform DE on the original (unintegrated) data, to find gene expression differences for each population.

**Comment by silpasuthram** [comment]
Thanks.

**Comment by joekodama** [comment]
How do I compare the same clusters in the two different conditions in a integrated dataset?
