### ISSUE TITLE
3D PCA and 3D tSNE plot

### ISSUE THREAD

**Issue by shikhagupta68** [satijalab/seurat#1178]
Hi,

I was wondering if there is a way I can visualize my data in the form of 3D PCA and 3D tSNE plots?

For 3D tSNE, I tried using RunTSNE function with dim.embed =3 but it doesn't seem to be working.

Please let me know if Seurat has other functions which can be used for this purpose.

Thank you
Shikha Gupta

**Comment by andrewwbutler** [comment]
Hi,

There are no native Seurat functions to produce 3D plots but you can always pull out the data and feed it into your favorite 3D plotting framework. The relevant function in Seurat v3 is:

```R
Embeddings(object = object[["pca"]])
```

or in Seurat v2:

```R
GetCellEmbeddings(object = object, reduction.type = "pca")
```

**Comment by shikhagupta68** [comment]
Thanks so much

**Comment by Dragonmasterx87** [comment]
@shikhagupta68 I know this is old but find [the solution here](https://github.com/Dragonmasterx87/3D-Plotting-in-Seurat-3.0.0)

Cheers!

**Comment by shikhagupta68** [comment]
Thanks very much!

**Comment by Dragonmasterx87** [comment]
@andrewwbutler mate, you guys should implement this: [3D Plotting of Seurat Objects using Seurat 3.1.1](https://github.com/Dragonmasterx87/Interactive-3D-Plotting-in-Seurat-3.0.0)

I'm sure you guys can make it nicer, but it works a lot of people are using it.

Also is it cool if I list you as a co-author? Since you gave me the idea to use plotly :) You guys please feel free to implement it as a part of seurat.
