### ISSUE TITLE
AnnData conversion errors

### ISSUE THREAD

**Issue by gokceneraslan** [satijalab/seurat#1182]
Hi,

When I try to convert an old Seurat object to anndata using 

```r
Convert(from = sobj, to = "anndata", filename = 'x.h5ad'))
```

I get errors about missing `dr` and `meta.data` slots. It'd be nice to check the version of the Seurat object and suggest user to use the `UpdateSeuratObject` function. (or it might run automatically, too, if it's safe to use for all cases.)

After converting my file, another error I got is the missing `hvg.info` slot. I don't know if this is because of the conversion or it might be that there is just no hvg.info in the object (I'm not very familiar with Seurat object structure and version changes). So, I had to run `FindVariableGenes` to populate that slot as a workaround.

**Comment by mojaveazure** [comment]
Hi Gökçen,

We are in the process of updating our Seruat &harr; Anndata converters for Seurat v3. Please see #1021 for updates on this.

**Comment by gokceneraslan** [comment]
Hi, thank you. I don't think this is a duplicate bug but it's up to you.

**Comment by mojaveazure** [comment]
Hi Gökçen,

The new Seurat &rarr; Anndata converter will be written as an S3 method targeting Seurat v3 objects. Since Seurat v3 objects (R class `Seurat`) are an entirely new class declaration, there won't be any way R to dispatch the function on a Seurat v2 object (R class `seurat`), rendering this need for the function to call `UpdateSeuratObject` moot. The user will have to run `UpdateSeuratObject` on their own to even be allowed to run the function, as R won't automatically allow running the converter on a Seurat v2 object.

I marked as this issue as a duplicate since this is a bug with the Seurat &rarr; Anndata converter, of which there are several. We are actively working on this, but aren't there yet. The Anndata &rarr; Seurat converter, however, is functional and will read in an h5ad file as a Seurat v3 object.
