### ISSUE TITLE
How can I add the unique cell name in FindIntegrationAnchors ?

### ISSUE THREAD

**Issue by Aja23i6** [satijalab/seurat#1187]
Hi, 
I'm merging two datasets in seurat 3.0 with FindIntegrationAnchors.
Now I have the Warning message,
Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

As in the seurat v2, there is the option "add.cell.id" in RunCCA command.
RunCCA(WT, KO, genes.use = genes.use, num.cc = 100, add.cell.id1="wt", add.cell.id2="KO" )

Do you have similar option in FindIntegrationAnchors?

Best

**Comment by timoast** [comment]
Hi, there is a function called `RenameCells` in Seurat v3 that can be used to rename cells. However, this is done for you automatically in `FindIntegrationAnchors` if you have duplicate cell names in the groups (notice you get a warning rather than an error). If you would prefer to specify cell names yourself, you can run `RenameCells` on the objects before running `FindIntegrationAnchors`

**Comment by Aja23i6** [comment]
Thank you. It means I can change the name by `RenameCells`.  But `FindIntegrationAnchors `automatically add the name, so I have this warning message.

Thanks again!
