### ISSUE TITLE
merge release/future into release/3.0

### ISSUE THREAD

**Issue by namita1025** [satijalab/seurat#1203]
Is there any plan to add the parallelization of release/future into the main release/3.0 branch? I have been using release/future but worry that new features will only be added to the release/3.0 branch.

**Comment by mojaveazure** [comment]
`release/future` was merged into `release/3.0` in November of 2018 (latest commit for `release/future` is 4595fad, which is present in `release/3.0`). Also, when looking at merging `release/future` into `release/3.0`, we see that everything in `release/future` is present in `release/3.0`

![screen shot 2019-03-06 at 3 35 38 pm](https://user-images.githubusercontent.com/11035068/53911931-cb486e00-4025-11e9-95a8-de4c6c520b78.png)

We apologize for the confusion, and will remove the `release/future` branch since it's no longer needed.
