### ISSUE TITLE
Plotting log2(CPM+1) or similar Expression Levels visualization.

### ISSUE THREAD

**Issue by ogarmar3** [satijalab/seurat#1211]
Hello,

I'm trying to compare expression levels of some genes between two conditions, but the scaling and dropouts make the differences difficult to visualize (see plot1.png). I'd like to show something like the Counts Per Million in Example.png
Is there a way to plot log2(CPM+1) with VlnPlot, or another expression levels visualization that looks similar to the attached boxplot?

Thank you!

Marcos Otero
![plot1 png](https://user-images.githubusercontent.com/40645584/53981257-077fdb00-40c7-11e9-8901-f84eb94eb968.png)
![example](https://user-images.githubusercontent.com/40645584/53981302-18305100-40c7-11e9-9721-f0396946c6a4.png)

**Comment by timoast** [comment]
Log-normalization with the `NormalizeData` function will compute log(1 + counts per `scale_factor`). `scale_factor` by default is set to 10000.

In Seurat v3 you can change the data used by `VlnPlot` by setting the `slot` argument, which by default is set to `data` to plot the normalized data.

If there is differential expression between these genes, you might want to plot the expression per cluster rather than for all cells. You can do this by setting the cell identities before plotting.
