### ISSUE TITLE
Choosing CCA Dims for FindIntegrationAnchors

### ISSUE THREAD

**Issue by Thessentials** [satijalab/seurat#1248]
In Seurat v3, what options are available for visualizing the CC vectors derived from the CCA when using the ```FindIntegrationAnchors``` function?

For example, in Seurat v2 it was possible to use the ```MetageneBicorPlot``` function to visualize the shared correlation strength in order to select a meaningful number of CC dimensions to use for the integration / alignment step.

**Comment by satijalab** [comment]
Thanks for your question. As we describe in the manuscript, each integration analysis does require a 'dimensionality' (i.e. number of PCs, or CCs) that are used in identifying anchors, and performing integration.

The short answer is that we recommend using whatever dimensionality you would use in a standard clustering analysis (i.e. from PCA, for example by exploring an elbow plot, or a statistical resampling analysis).

In Seurat v3, we've also noticed that results are quite robust to fine-tuning of this parameter (try exploring modifying the number of dimensions in our vignettes online). We do not perform fine-tuning for any of the analyses in the manuscript.

**Comment by rjb67** [comment]
I am reading this response and I am still not exactly sure how I am supposed to visualize the number of CCs to use after running `FindIntegrationAnchors`. I looked at the AnchorSet object and nothing there gave me an idea of how to do something similar to `MetageneBicorPlot` if I want to use CCs. Or should I use PCA after calculating the CCs? That doesn't make sense though based on Seurat v2.

Would it be possible to see some example code of how I could do this?

**Comment by lshepard2154** [comment]
I would like to second this request for further explanation please. 

I think are more clear explanation of this would be helpful to the community. Before Seurat 3, the choice of the CCA was quite clear using functions such as `MetageneBicorPlot` which is not available here... From the suggestion, it seems like we should run the additional steps to perform PCA but my understanding is that this can only be done for each seurat object individually, rather than in a combined object such as this line from the old vignette (https://satijalab.org/seurat/v2.4/immune_alignment.html):

```
p3 <- MetageneBicorPlot(immune.combined, grouping.var = "stim", dims.eval = 1:30, 
    display.progress = FALSE)

```

Is there really no way to acquire a similar output from the above with the integrated method?

Thank you!

**Comment by satijalab** [comment]
We do not provide a visualization function, and explain our rationale at the beginning of the supplement of Stuart*, Butler* et al, biorXiv 2018. In Seurat3, there is a substantially reduced dependence on this precise parameter value. For example, in the integration vignette for the pancreas on the website, you can explore how the results change by setting this parameter over a wide range.

**Comment by Fernandobec** [comment]
I understand your recommendation on using whichever dimensionality would be used for the samples to be integrated, however in my case my distinct samples are timepoints of a development timecourse and for some of them I use ndims 1:10 because they are very homogeneous samples whereas at later timepoints i go to 1:30-1:40. Do you have some advice on how to choose the ndims parameter for integration in such a case? Thanks!
