### ISSUE TITLE
Seurat v3.0 Error running AverageExpression

### ISSUE THREAD

**Issue by bapoorva** [satijalab/seurat#1252]
I am using Seurat v3.0 and I'm having issues with the function that computes average expression of genes in each identity class. I've never had this problem with version 2 and I'm not sure what it means or how to fix it.
```
avgexp=AverageExpression(object = scrna)
Finished averaging RNA for cluster 0
Finished averaging RNA for cluster 1
Finished averaging RNA for cluster 2
Finished averaging RNA for cluster 3
Finished averaging RNA for cluster 4
Finished averaging RNA for cluster 5
Finished averaging RNA for cluster 6
Finished averaging RNA for cluster 7
Finished averaging RNA for cluster 8
Finished averaging RNA for cluster 9
Finished averaging RNA for cluster 10
Finished averaging RNA for cluster 11
Finished averaging RNA for cluster 12
Finished averaging RNA for cluster 13
Finished averaging RNA for cluster 14
Finished averaging RNA for cluster 15
Finished averaging RNA for cluster 16
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided
```

**Comment by andrewwbutler** [comment]
Hi,

Is it possible to share the object (or downsampled version) that reproduces the error?

**Comment by pguilha** [comment]
I'm having the exact same issue:
Finished averaging SCT for cluster 0
Finished averaging SCT for cluster 1
Finished averaging SCT for cluster 2
Finished averaging SCT for cluster 3
Finished averaging SCT for cluster 4
Finished averaging SCT for cluster 5
Finished averaging SCT for cluster 6
Finished averaging SCT for cluster 7
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided

**Comment by EdePater** [comment]
Dear reader,
I have exactly the same problem. I have generated a Seurat library from both a WT and a KO single cell experiment. I have defined several clusters. Now I want to know within one cluster if there is differential gene expression between WT and KO. To get to this cluster I have generated a new Seurat object with just this one population, but if I run Average expression I get cell not found. I can send you additional information. Please specify what you would need.
With kind regards
Emma de Pater

**Comment by andrewwbutler** [comment]
The Seurat object (or downsampled version) that reproduces the error would be the most helpful for quickly debugging this.

**Comment by EdePater** [comment]
Thank you for looking into this.
I've attached a downsampled version of the seurat object that gives me trouble, Ive included the Rscript with which I have solved the issue now. This is not in the most elegant method, but it worked for now. I think I have made a mistake in defining the subset.
With kind regards
Emma
________________________________
Van: Andrew Butler [notifications@github.com]
Verzonden: donderdag 4 april 2019 15:35
Aan: satijalab/seurat
CC: E.M. De Pater; Manual
Onderwerp: Re: [satijalab/seurat] Seurat v3.0 Error running AverageExpression (#1252)


The Seurat object (or downsampled version) that reproduces the error would be the most helpful for quickly debugging this.

**Comment by ddiez** [comment]
I was having the same problem with `BuildClusterTree()` and think I found the reason.

I am using the v3 C57BL6 mouse PBMC VDJ+RNA-seq demo dataset from 10x (https://support.10xgenomics.com/single-cell-vdj/datasets). I create an process a Seurat object with:

```
x <- Read10X_h5(here("rna/vdj_v1_mm_c57bl6_pbmc_5gex_filtered_feature_bc_matrix.h5"))
x <- CreateSeuratObject(x, "10xPBMC", min.cells = 10, min.features = 10)
x <- NormalizeData(x, verbose = FALSE)
x <- FindVariableFeatures(x, verbose = FALSE)
x <- ScaleData(x, verbose = FALSE)
```

Then compute dimensionality reduction:

```
x <- RunPCA(x, dims = 1:30, verbose = FALSE)
x <- RunTSNE(x, dims = 1:30, perplexity = 30, num_threads = 16, verbose = FALSE)
```

Then calculate clusters using:

```
x <- FindNeighbors(x, verbose = FALSE)
x <- FindClusters(x, algorithm = 3, resolution = 0.6, verbose = FALSE)
```

Which returns an object with a new column named `RNA_snn_res.0.6` containing the new identities:

```
Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
```

There is also a column named `seurat_clusters`:

```
> head(x@meta.data)
                   orig.ident nCount_RNA nFeature_RNA RNA_snn_res.0.6 seurat_clusters
AAACCTGAGAGCTATA-1    10xPBMC      18659         3238               2               2
AAACCTGAGCATCATC-1    10xPBMC       2318          971               0               0
AAACCTGAGCTTTGGT-1    10xPBMC       2594         1039               0               0
AAACCTGAGGGCATGT-1    10xPBMC       3789          960              13              13
AAACCTGAGTGACTCT-1    10xPBMC       3211         1435               6               6
AAACCTGCATGGTTGT-1    10xPBMC      12344         2670               3               3
```

with the following levels:

```
Levels: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 10xPBMC
```

That is, there is a level that corresponds to the project name. The `active.ident` slot contains the same information as in `seurat_clusters`. Then, when running `BuildClusterTree()` this function calls `CellsByIdentities()` which fails because there are no cells assigned to the "10xPBMC" level.

```
> table(x@active.ident)

      0       1       2       3       4       5       6       7       8       9      10      11      12      13      14      15      16      17      18 10xPBMC 
   1485    1048    1039     962     769     614     473     442     277     261     203     198     183     166     105     102      72      55      44       0 
```

After setting the active identity with:

```
x <- SetIdent(x, value = "RNA_snn_res.0.6")
```

The `active.ident` slot now contains the correct levels (i.e. no level named "10xPCMB") and `BuildClusterTree()` finishes without problem.

**Comment by EdePater** [comment]
I have a Seurat object from two different datasets. So in my case I have some orig.ident with "WT" and some with "hom" which I want to preserve. The function cannot recognize them because they are of class "character" and not of class "factor". If I can set the orig.ident as class "factor" then I should be set.

**Comment by andrewwbutler** [comment]
Ok, turns out the issue was in the object setup when initially setting the identities. If you reinstall the latest `release/3.0` and rerun your scripts from the beginning (need to redo `CreateSeuratObject`), the issue should be fixed.

**Comment by ddiez** [comment]
Thank you Andrew. I installed the version of Seurat for this commit with `remotes::install_github("satijalab/seurat", ref="0e070c1878f5301421bd0dae0c6cde32c29da1f1")` and can confirm it fixes the problem reported in this issue. Note that there seems to be other problems introduced by more recent commits (e.g. failure with RunTSNE). I may wait a bit to see if the problem is not fixed before posting a more specific issue.

**Comment by annpa1231** [comment]
Hi,
I am trying to use Signac and I get these error messages seen below

Error in setnames(ans, col.names) : 
  Can't assign 5 names to a 1 column data.table
In addition: Warning message:
In fread(file = fragment.path, col.names = c("chr", "start", "end",  :
  Stopped early on line 2. Expected 1 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<>>


Error in `[[.Seurat`(x, i, drop = TRUE) : 
  Cannot find 'total' in this Seurat object

Would you be able to help me figure it out?
Thank you

**Comment by annpa1231** [comment]
This is what I have tried

> FilterFragments(fragment.path = fragment.path, cells = colnames(IPFnml_fast), output.path = fragment_file_filtered)
Retaining 6042 cells
Reading fragments
Error in setnames(ans, col.names) : 
  Can't assign 5 names to a 1 column data.table
In addition: Warning message:
In fread(file = fragment.path, col.names = c("chr", "start", "end",  :
  Stopped early on line 2. Expected 1 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<>>
> # Computing QC metrics
> IPFnml_fast <- NucleosomeSignal(object = IPFnml_fast)
Extracting reads in requested region
Computing ratio of mononucleosomal to nucleosome-free fragments
> IPFnml_fast$pct_reads_in_peaks <- IPFnml_fast$peak_region_fragments / pbmc$total * 100
Warning message:
In IPFnml_fast$peak_region_fragments/pbmc$total :
  longer object length is not a multiple of shorter object length
> IPFnml_fast$pct_reads_in_peaks <- IPFnml_fast$peak_region_fragments / IPFnml_fast$total * 100
Error in `[[.Seurat`(x, i, drop = TRUE) : 
  Cannot find 'total' in this Seurat object


Thanks again
