### ISSUE TITLE
Memory Exhaust IntegrateData

### ISSUE THREAD

**Issue by tmccra2** [satijalab/seurat#1254]
Hello! Thank you again for your wonderful program and all your help/prompt replies.

Right now I'm trying to integrate 3 very large datasets following this: https://satijalab.org/seurat/pancreas_integration_label_transfer.html

I see that in the tutorial it says "We then pass these anchors to the IntegrateData function, which returns a Seurat object. The returned object will contain a new Assay, which holds an integrated (or ‘batch-corrected’) expression matrix for all cells, enabling them to be jointly analyzed."

When I run this: `sc10x2 <- IntegrateData(anchorset=sc10x2,dims=1:50)`
I get this: 
> Merging dataset 2 into 1
> Extracting anchors for merged samples
> Finding integration vectors
> Finding integration vector weights
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Integrating data
> Merging dataset 3 into 1 2
> Extracting anchors for merged samples
> Finding integration vectors
> Error: vector memory exhausted (limit reached?)
> Error during wrapup: vector memory exhausted (limit reached?)

My integrated dataset does not say "Large Seurat" object, it says "Large AnchorSet" which is why I think I have an issue when I perform the next step: `DefaultAssay(object = sc10x2) <- "integrated"` 
I get this back: 
> Error in UseMethod(generic = "DefaultAssay<-", object = object) : 
>   no applicable method for 'DefaultAssay<-' applied to an object of class "AnchorSet" 

Any tips? I'm not sure how to proceed. Thanks!

**Comment by andrewwbutler** [comment]
It looks like the `IntegrateData` function failed with the memory limit error, therefore `sc10x2` won't contain the integrated datasets but will still be the `AnchorSet` object returned from `FindIntegrationAnchors`. What is the scale of your 3 datasets and how much memory do you have available?

**Comment by zbgaber** [comment]
Hello, 
I aso had this prblem.  I'm writing just in case other people also have this problem and just in case it is useful your your improving Seurat.

I had the same error with the IntegrateData function.  It was when trying to integrate six datasets with a combined cell number of 9371 cells.  I also had the features.to.integrate argument set to integrate all the genes in my dataset (around 11,000) which probably also increased the problem.  I was also using RStudio at the time.

I was also I'm using a MacBook with a total memory of 16Gb.  I have no idea how much of that was in use when the problem was having but currently my laptop seems to have about 10Gb in use at the moment which I suspect is typical - I probably have too many things open.

Anyways, I was able to work around the problem using suggestions in this thread - they give many options, I used the suggestion for people using RStudio.  It should at least point people in the directions they should be looking, although I'm not a computer scientist so everyone should use caution when tweaking things on their computer.  Take notes so you can undo them!

[https://stackoverflow.com/questions/51248293/error-vector-memory-exhausted-limit-reached-r-3-5-0-macos/52612848](url)

**Comment by YunZheHuang** [comment]
I have the same issue after using SCTransform, I have around 30000 cells. I didn't encounter this error when I use the log normalization, this error appears after I used SCTransform.

**Comment by lucygarner** [comment]
The link above wasn't working for me for some reason:
https://stackoverflow.com/questions/51248293/error-vector-memory-exhausted-limit-reached-r-3-5-0-macos/52612848
