### ISSUE TITLE
Changing axis thickness in DotPlot

### ISSUE THREAD

**Issue by Dragonmasterx87** [satijalab/seurat#1269]
In a code such as that given below:
dataobject.plot <- c("gene1", "gene2"....."geneN")
DotPlot(object = dataobject.plot = feature.plot, plot.legend = TRUE, cols.use = c("yellow", "red"), dot.scale = 8)

How can I change the xaxis and yaxis thickness I cant get par(axis(1, lwd = 2)) to work how can I amend the parameters by which dotPlot is plotting the axis thickness?

Cheers.

**Comment by mojaveazure** [comment]
Hi Fahd,

`DotPlot` uses ggplot2 to generate the plot rather than base R graphics, you have to use [ggplot2-style theming](https://stackoverflow.com/questions/36474643/graphical-parameters-in-ggplot2-how-to-change-axis-tick-thickness) to modify axis thickness.

Please note, in Seurat v2, you have to pass `do.return = TRUE` to modify the plot. Seurat v3 does not have this caveat.
