### ISSUE TITLE
convert to anndata fails with `ValueError`

### ISSUE THREAD

**Issue by bobermayer** [satijalab/seurat#1270]
Hi,

thanks a lot for providing conversion functions, this is awesome!

when converting the `immune.combined` object from the CCA vignette to `anndata`, it fails with 
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Variables annot. `var` must have number of columns of `X` (14053), but has 0 rows. 
```
this can be avoided by running 
```
immune.combined <- FindVariableGenes(immune.combined,do.plot=FALSE)
```
before conversion, but should this be necessary?

**Comment by a-munoz-rojas** [comment]
I was also running into the same issue - thanks for posting the quick fix. Several people also noted it here: #677 

Looking at your fix, it seems that when you run FindVariableGenes it annotates each gene with the mean, dispersion, etc, which can then be exported to .var in the anndata file. If you don't run FindVariableGenes, the variables (genes) are not annotated with any information, which prompts the error since there is nothing to put into .var in the anndata file. This bug should hopefully be fixed as there are cases when you won't have gene information and you would still want to export it.

**Comment by mojaveazure** [comment]
Hi Benedikt,

We no longer actively develop Seurat v2.X releases. The latest version of Seurat, Seurat v3, doesn't support direct Seurat &rarr; AnnData conversion. However, we do support writing out to a loom file, which you can then read into Scanpy.
