### ISSUE TITLE
Jupyter Notebook no progress bar or logs

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#1279]
I've been running Seurat on Jupyter Notebook. For large datasets, it was very hard to know whether Seurat is running or it's killed on the notebook. There are no log messages indicating the current status. Is it possible to make the package more compatible with Jupyter Notebook?

Thanks

**Comment by mojaveazure** [comment]
Seurat message logs and progress bars are implemented using `message`, `txtProgressBar`, and `pb*apply` with everything going through standard error, as discussed in #45, #226, and #638 to make it easier to use Seurat in Rmarkdown. From (not very exhaustive) Googling, it seems as though Jupyter won't show standard error as it comes, but rather holds it until the end (see [here](https://meta-serv.com/article/progressbar) where they redirect a Python progress bar from stderr to stdout).

Having Seurat switch between standard error and standard out would add a large amount of complexity and overhead to the code, and we simply don't have the bandwith for either development or maintenence of such functionality. As such, we're going to prioritize Rmarkdown support over Jupyter support since most of our users (and us ourselves) use Rmarkdown instead of Jupyter.

While Rmarkdown was previously just for documents (like our vignettes) and presentations, it now [offers a "notebook"](https://bookdown.org/yihui/rmarkdown/notebook.html) similar to Jupyter notebooks. If you're looking for a Jupyter-like environment for Seurat, we would highly recommend RStudio (or RStudio Server if you're working remotely) with Rmarkdown documents and notebooks. You can even use other languages, such as [Python](https://bookdown.org/yihui/rmarkdown/language-engines.html#python), in Rmarkdown as well as send data between R and Python, if you're using tools written in both languages.
