### ISSUE TITLE
AverageExpression missing "RNA" assay 

### ISSUE THREAD

**Issue by whdmstjr0702** [satijalab/seurat#1329]
Hello,

I am using Seurt v3.0 and trying to use AverageExpression function on my integrated Seurat Object.

![integrated_Seurat](https://user-images.githubusercontent.com/46611286/55653748-1684a680-57b5-11e9-9925-58c3857b9302.png)

I type in the code:
`Average <- AverageExpression(object = integrated, return.seurat = TRUE)`

The code run successfully, but my "Average" seurat object but does not contain RNA assay.

![Average_Seurat](https://user-images.githubusercontent.com/46611286/55653791-374cfc00-57b5-11e9-861f-722c3b1a37ba.png)

Can anyone help with this?

Thank you.

Ed

**Comment by mojaveazure** [comment]
Hi Ed,

If you have `AverageExpression` return a Seurat object, it makes a new object from the matrix otherwise returned by `AverageExpression`. Since this matrix has clusters as columns instead of cells, it cannot have the original expression matrix in the same Seurat object as these have differing numbers of columns (fewer clusters than cells). All assays in a Seurat object must have the same number of columns, so we can't have the average expression matrix in the same Seurat object as the standard RNA and integrated assays.

**Comment by mojaveazure** [comment]
Whoops, misunderstood what was being asked. There's a mismatch between the documentation and the code, so it's not actually defaulting to all assays.

**Comment by mojaveazure** [comment]
Hi Ed,

This should be fixed as of 71a3879; `AverageExpression` uses all assays by default rather than just the default assay. Also, the `assay` parameter has been changed to `assays` to reflect that it can take multiple assays.

Sorry again for the misunderstanding earlier.
