### ISSUE TITLE
Can not remove batch effect by ScaleData !

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1351]
Hi all :
    I have 6 tissue samples that perform 10X RNA-seq. I merge them first and then want to see the cell types in these samples. In order to correct batch effect , I use ScaleData and include sample batch information to regress out. My code is as below : 

```R
scObject <- ScaleData(object = scObject, vars.to.regress = c("nUMI", "percent.mito", "sampleID"), genes.use = scObject@var.genes, model.use = "negbinom")

scObject <- RunPCA(object = scObject, pc.genes = scObject@var.genes)

scObject <- FindClusters(object = scObject, reduction.type = "pca", dims.use = 1:20, 
    resolution = 0.4, save.SNN = TRUE, force.recalc=TRUE)

scObject <- RunTSNE(object = scObject, dims.use = 1:20, do.fast = TRUE)

TSNEPlot(object = scObject, do.label=TRUE, pt.size = 1.5)
```

The whole tSNE results you can find here : https://github.com/SeadonXing/Questions-For-Seurat/blob/master/tSNE.PNG
And I plot the expression of CD3D and CD8A for identify T cells and CD8+ T cells : https://github.com/SeadonXing/Questions-For-Seurat/blob/master/T-cells.PNG
https://github.com/SeadonXing/Questions-For-Seurat/blob/master/CD8%2B%20T%20cells.PNG
It can be clearly see that there are strong batch that cells are group by sample not by cell types, especially for CD8+ T cells. In the T cells cluster, the subclusters are all group by sample not by subtype T cells.
My question is how to handle for this situation ? Why there are strogn batch even after I regress the batch effect ? Are there any other methods to correct this or to explore why ? 
My ideal results is that cells are cluster by cell types and even in each of the cell types, cells can still group by sub celltypes and cells for each samples are spread random and everywhere in each cluster.
Hope you reply
Best

**Comment by andrewwbutler** [comment]
Hi,

We don't generally recommend using `ScaleData` to regress out batch effects. I would suggest running our integration procedure in v3 (see [vignette here](https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html)).

**Comment by SeadonXing** [comment]
Yes I knwo that you creat powerful tools to intergrate dataset from differetn plateform ( drop-seq and smart-seq) and condition. But for my samples , its just biology replicates(samples in same condition and plateform) and I just need to combined them together to do analysis. I think its no need to run CCA intergrate analysis. What`s more, all the before analysis have been done by Seurat 2.3.4, I think its may not appropriate to update to v3 now.
Can you give me more advices for this situation ?

Sincere Thanks

**Comment by Dragonmasterx87** [comment]
Hi,

@SeadonXing First of all, I am not a Seurat Developer and am learning myself.

Just some thoughts:

Even samples run from n=3 biological samples on the same platform will result in 'biologically similar' cells clustering away from one another, due to subtle effects of biological variability in gene expression. All PCA tools find 'dissimilarity' so they will find dissimilarity even if you are comparing two elephants (analogy), of course, the elephants will cluster away from a mouse, but if you cluster based just on the elephant's CCAs and PCAs (subsetting), you will see huge variability. 

That's why the Seurat team developed a supervised technique of mapping cells having similar identities into similar clusters (UMAP/Integrated-Anchor based clustering). Which has its pro's and cons, but if you want to force cells into a particular bin, then you will have to use Seruat 3 which @andrewwbutler has outlined already. 

I also have run a large part of the analysis in 2.3.4, and I don't want to perform UMAP (as yet) but eventually, I will have to shift from S2 > S3. In my opinion, since you want to perform a supervised analysis, it's better to start now. However, if you want to increase the tightness of your clusters, decrease the number of variable genes (make it more stringent go from ~2000 to ~500) and you clusters will map onto one another better, OR will at least be connected AND far apart in 2D space.

Just some thoughts, as I said i'm learning myself, the devs can correct me if I'm wrong.

Cheers!

**Comment by SeadonXing** [comment]
Dear @andrewwbutler  and @Dragonmasterx87  :
    Anyway, thank you for reply and advices.  I just want to fingure out that why sometimes I use ScaleData include batch can remove batch effect perfect but why in this example above it perform so bad ? I dont think its a totally random things.
    And I still confused with one things that in my opinion the integration procedure in v3 is similiar to RunCCA in v2 and is used when you want to combined across different plateforms and conditions just like the tutorials show. Pancrease data cross drop-seq cel-seq and smart-seq, stimulated and control PBMC , both of them I think suitable  for  integration procedure method. But for my situation , there are only biology replicates , I think I can just combine them by  simple ways like "cbind" in R. Dose this samples in same plateform and condition should still have to use the  integration procedure ? Or which situation should I use "cbind" or " integration procedure".

Best

**Comment by satijalab** [comment]
We do not recommend using ScaleData for removing batch effects, for reasons discussed in https://www.nature.com/articles/nbt.4096. If you have multiple experiments where cells are clustering together across experiments based on their biological identity (instead of by replicate), there is no need to run the integration workflow
