### ISSUE TITLE
NormalizeData function with normalization.method == "genesCLR"

### ISSUE THREAD

**Issue by jeitziner** [satijalab/seurat#1377]
Why did you add +1 in the formula "length(x+1)" ? It is the same as length(x), except if you meant length(x)+1. Thanks for your answer!

**Comment by satijalab** [comment]
@ChristophH can you respond?

**Comment by ChristophH** [comment]
The `x+1` is a mistake (which has no consequences) and it is supposed to be just `length(x)`

The entire line that you are referring to is
`log1p((x)/(exp(sum(log1p((x)[x > 0]), na.rm=TRUE) / length(x+1))))`

Please note that in the [CITE-seq publication](https://www.nature.com/articles/nmeth.4380) we use CLR normalization per cell (the vector `x` holds the ADT counts for a single cell) and the CLR-normalized counts are
`log(x / (exp(sum(log(x[x > 0]), na.rm=TRUE) / length(x))))`

The differences in these two implementations are due to different strategies in handling zeros.

**Comment by jeitziner** [comment]
Thanks for your answer! 
In the article you mentioned they calculated for the CLR(x) actually the CLR(x+1) (they mention: "x is the vector of ADT counts (including one pseudocount for each component)"), which would translate to log1p(x / (exp(sum(log1p(x), na.rm=TRUE) / length(x)))).  After some computation, I saw that there are no consequences in either using your formulae or the one from the mentioned paper!
