### ISSUE TITLE
subset funcition in V3

### ISSUE THREAD

**Issue by ysu2015** [satijalab/seurat#1385]
Big Congs for V3 on CRAN!!

I am very happy to use Seurat on my analysis. I have several points not very clear on the function "subset" on V3. 
1) After using "subset" to subset parts of the data (p2) from original object (p1), p2 not longer to keep all the raw counts of p1 (but V2 did) , right?
2) p2 keep all the levels of p1@meta.data$col.name, even the value is 0 ? what application will be to keep this information? Seeing that table(Idents(p1))=table(Idents(p2))

Thanks.

Y

**Comment by andrewwbutler** [comment]
Hi,

1. Yes, that's correct. `subset` in v3 will subset all matrix slots including the counts matrix. If you want to keep the original counts matrix around, I would recommend saving it as a separate object/file. 
2. This is likely because the `col.name` in question is a factor and subsetting a factor in R will maintain the levels even if there are no members of that level present. You can use the `droplevels` function to get rid of these unused factor levels either on that metadata column:

```R
p1$col.name <- droplevels(x = p1$colname)
```

or on the Seurat object itself if it's the "idents" that you want to drop the factor levels from:

```R
p1 <- droplevels(x = p1)
```

**Comment by ysu2015** [comment]
Thanks for quick reply. That is very clear. 

Y
