### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by mitul-patel** [satijalab/seurat#139]
Hello,

I am trying to plot PCA, tSNE and featureplots using ggplot. I am using pbmc object. But I am not able to generate plots...and got error: Error: ggplot2 doesn't know how to deal with data of class seurat

Could you tell me how can I plot those using ggplot?

Many thanks.

**Comment by leonfodoulian** [comment]
Hello,

You can find the appropriate data sets in the Seurat object, extract them as a `data.frame()` and plot them using ggplot2. Most of the codes used by Seurat to generate graphics can be found in [plotting_internal.R](https://github.com/satijalab/seurat/blob/master/R/plotting_internal.R), and can be easily adapted to the data frames.

Best,
Leon

**Comment by mitul-patel** [comment]
Many thanks Leon. I have another question regrading the interactivity. I like to render the PCAplot into shiny app. But I am getting following error: no applicable method for 'ggplotly' applied to an object of class "list". The command I used: ggplotly(PCAPlot(object = pbmc, dim.1 = 1, dim.2 = 2, do.hover=TRUE)). I have also tried this command: PCAPlot(object = pbmc, dim.1 = 1, dim.2 = 2, do.hover=TRUE). But none of them worked in shiny using renderPlotly.

Any ideas how can I render this interactive plot into shiny?

Many thanks.

**Comment by leonfodoulian** [comment]
Seurat v2.0.0 supports interactive plotting. You can find the details under **Interactive plotting features** [in this vignette](http://satijalab.org/seurat/visualization_vignette.html). Briefly, you have to set in the `PCAPlot` function `do.hover = T` and define the data details you'd like to visualize by passing them as a vector to the `data.hover` argument. You'll find an example in the vignette.

Otherwise, you can also apply that on ggplot2 objects, again by extracting the appropriate data from Seurat as `data.frame()` and running `ggplotly(ggplot(...))`.

**Comment by mitul-patel** [comment]
Thanks again Leon.... I have looked the Seurat V2.0.0 and its great. I wanted to include plots into my existing shiny app. I have extracted dataset by "pbmc.df<-data.frame(as.matrix(pbmc@data))". But I dont know how to plot in ggplot2. will it be same as the PCAplot?

I have also set option do.return=TRUE but it returns plot. Does it return ggplot2 object or plot?

Many thanks.

**Comment by leonfodoulian** [comment]
I'm sorry if I wasn't clear. I guess the following code should be helpful:

```
require(ggplot2)

# Create data frame of clusters computed by Seurat
df.cluster <- data.frame(Cell = names(object@ident), Cluster = object@ident)

# Create data frame of PCs compute by Seurat
df.pc <- data.frame(object@dr$pca@cell.embeddings)
# Add Cell column
df.pc$Cell = rownames(df.pc)
# Merge PC data frame to Cluster data frame
df.pc <- merge(df.pc, df.cluster, by = "Cell")
# Plot PC1 and PC2 using ggplot2,
# colors of points correspond to Cluster IDs
ggplot(data = df.pc, aes(PC1, PC2)) + geom_point(aes(color = Cluster))

# Create data frame of tSNE compute by Seurat
df.tsne <- data.frame(object@dr$tsne@cell.embeddings)
# Add Cell column
df.tsne$Cell = rownames(df.tsne)
# Merge tSNE data frame to Cluster data frame
df.tsne <- merge(df.tsne, df.cluster, by = "Cell")
# Plot tSNE1 and tSNE2 using ggplot2,
# colors of points correspond to Cluster IDs
ggplot(data = df.tsne, aes(tSNE_1, tSNE_2)) + geom_point(aes(color = Cluster))
```

Best,
Leon

**Comment by mitul-patel** [comment]
Great.... Many thanks Leon. This is exactly what I wanted to do. Just last thing.... it would be great to have same data frame for Feature Plot and Cell plot computes...

I really appreciate your help and advice.

Many thanks again.

**Comment by leonfodoulian** [comment]
I'm going to include a very simplified code for plotting the`FeaturePlot(reduction.use = "tsne", ...)` for one gene (Actb in this case). You can implement it for PC plots, and for any gene of interest. 

```
# Define gene of interest
gene <- "Actb"
# Create expression data frame for gene in long format
df <- data.frame(Expression = object@data[gene,], Gene = gene)
# Add Cell column
df$Cell = rownames(df)
# Merge expression data frame to tSNE data frame
df <- merge(df, df.tsne, by = "Cell")
# Plot gene expression using ggplot2,
# Colors of points correspond to gene expression levels
ggplot(df, aes(tSNE_1, tSNE_2)) + 
  geom_point(aes(color = Expression)) + 
  scale_color_gradientn(colors = rev(rainbow(5)))
```

For `CellPlot` graphs, instead of extracting the data for a gene, extract the columns corresponding to the cells of interest, and directly plot them in ggplot2. You can also play around the codes to automatize this process for as many genes or cell pairs of interest, or even render it automatic in a shiny app. 

Best,
Leon

**Comment by mitul-patel** [comment]
Many thanks Leon.... Excellent stuff. Solved all queries...

Regards,
Mitul
