### ISSUE TITLE
draw.line equivalent in DoHeatmap seurat3

### ISSUE THREAD

**Issue by rmenafra** [satijalab/seurat#1429]
Hi everybody, 
In Seurat v3 the Do.Heatmap function doesn't separate anymore with vertical white lines the clusters (in Seurat2 was draw.lines = TRUE option).
Any idea on how to re-create the same? I couldn't find an easy solution in the ggplot2 documentation.
Thanks in advance

**Comment by satijalab** [comment]
Thanks - yes we also miss having this feature in our own analyses, and are in the process of adding back in - should be on GitHub in the near future.

**Comment by mojaveazure** [comment]
Hi,

This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by TATABOX99** [comment]
Hello, I am currently using the DoHeatmap function in Seurat version 5.0, and I don't understand why the draw.line command generates gray lines instead of white ones. Is this some kind of error, or is there an issue with my code?
<img width="719" alt="屏幕截图 2023-12-10 165831" src="https://github.com/satijalab/seurat/assets/153422737/e5f253fb-c627-43bf-897a-69b63b2d4509">
