### ISSUE TITLE
Altering colours for DimHeatmap

### ISSUE THREAD

**Issue by kasumaz** [satijalab/seurat#1440]
Dear Seurat/Andrew Butler, 

I was wondering if for example in the vignette: DimHeatmap(object = pbmc, dims = 1, cells = 500, balanced = TRUE), the colours of the heatmap can be altered?
From purple and yellow to other colours. In case there is a command that can be inserted that makes this adjustment based on standard colours. Would be much easier than try to photoshopping it. I use the new V3. 
Many thanks. 
Kaz

**Comment by mojaveazure** [comment]
Hi Kaz,

If you set `fast = FALSE`, `DimHeatmap` will use ggplot2 instead of `image` to generate the heatmap. Then, you can use standard ggplot2 functions to modify colors (eg. `scale_fill_gradient`).

Please note that ggplot2 is much slower than `image`, especially for plots with many features and/or cells.

**Comment by kasumaz** [comment]
Once more thanks a lot!

**Comment by methornton** [comment]
Hello!  I am unable to change the color on a DimHeatmap that is 15 dimensions using fast=FALSE and scale_fill_gradientn.  Is there another solution?

**Comment by paulklemm** [comment]
> If you set `fast = FALSE`, `DimHeatmap` will use ggplot2 instead of `image` to generate the heatmap. Then, you can use standard ggplot2 functions to modify colors (eg. `scale_fill_gradient`).

For me, this doesn't work. With the following code, it still uses the magenta - black - yellow default color scale.

```r
Seurat::DimHeatmap(
  seurat_data,
  dims = 1:15,
  cells = 500,
  balanced = TRUE,
  fast = FALSE
) +
  ggplot2::scale_fill_gradientn(colors = c("steelblue1", "white", "tomato"))
```

With `Seurat::DoHeatmap` it works fine. Maybe it's a problem because of the plot list here? https://github.com/satijalab/seurat/blob/49a1be0427f2f26a531eb468ba93eeb18d8a2edb/R/visualization.R#L139-L153

**Comment by plijnzaad** [comment]
Just a note: @paulklemm 's code only operates on the panel. (I guess you can fix this by using `combine=FALSE` and add the gradients expclitity to each of the `list` members)
