### ISSUE TITLE
Unexpected linear correlation between genes

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#1470]
Hello,

When analyzing my data, I noticed that there is a  positive linear correlation between certain genes (please see below for code and the generated graph). The strong linearity observed here makes it difficult to explain the differences by a biological phenomenon. Rather than this linear appearance (marked by arrows), I expected to see a "cloud" of dots that are more dispersed (akin to Gapdh vs Rpl32 graph below). This linear relationship between genes can be worrisome since the expression of an interesting gene might be potentially confounded by another gene which is not that interesting.

```
# Previously analyzed Seurat object that holds information on dimension reduction and clusters
combined <- readRDS(~/combined.rds")

# High abundance housekeeping genes
FeatureScatter(combined, "Gapdh", "Rpl32")

# T cell marker genes
FeatureScatter(combined, "Cd3e", "Cd8a")

# Other markers of interest.
FeatureScatter(combined, "Nampt", "Vav1")

```

![image](https://user-images.githubusercontent.com/38366155/56942290-17b8a300-6ad7-11e9-8dfa-b960c496ac08.png)

I also plotted the raw values to see the range of read counts across these genes. The positive correlation issue was more pronounced in gene-pairs with low raw counts (see images below)

```

FeatureScatter(combined, "Gapdh", "Rpl32", slot="counts")
FeatureScatter(combined, "Nampt", "Vav1", slot="counts")
FeatureScatter(combined, "Cd3e", "Cd8a", slot="counts")

```
![image](https://user-images.githubusercontent.com/38366155/56942203-9c56f180-6ad6-11e9-8da7-7629ecfb1927.png)

I'd appreciate your insights to explain this phenomenon. 

Inexpressible thanks to all who are involved in making and maintaining this awesome package.

Best,
Atakan

**Comment by andrewwbutler** [comment]
Hi,

You're correct, this can show up for gene pairs with low raw counts. Essentially, this is a result of normalizing **per cell** for genes with low counts. For example, say I have many cells with 1 count for both Val1 and Nampt but a different total number of counts. When you apply the log normalization transformation, this normalizes per cell so within any given cell, you will observe the same normalized value for Val1 and Nampt. However, this exact value will vary between cells depending on the total number of counts observed. This is what causes the lines you're seeing on the normalized `FeatureScatter` plots. Once you get above seeing just a few counts for genes, it becomes far less likely that you're going to get a lot of cells with the same count value for any pair of genes and that's why you don't see the "lines" showing up in your plots for genes with higher raw counts.

**Comment by atakanekiz** [comment]
Makes sense. I was thinking it would be unlikely to have the same low gene count (e.g. 1 for both) and also the same total number of counts across many cells resulting in a discernible linear correlation. But empirical data proves it otherwise. Thanks!
