### ISSUE TITLE
Integration/CCA vignette- problem identifying differentially expressed genes stim vs control

### ISSUE THREAD

**Issue by SFF-singecell-user** [satijalab/seurat#1482]
Hello, I am using Seurat v3 and following the ctrl vs stim vigenette. I am unfortunately runing into a problem identifying differentially expressed genes within a cell type, stim vs control.

This is my code (starting with labelling the clusters) and the error. I am not sure what I am doing wrong and would appreciate any help/advice.
Many thanks
------
immune.combined <- subset(x= immune.combined, idents = c("0", "1", "2", "3", "4", "5", "7", "8", "9", "11", "12", "13"))

immune.combined <- RenameIdents(object = immune.combined, "0" = "CD4 T", "1" = "CD8 T", 
                                "2" = "CD4 T", "3" = "CD8 T", "4" = "CD4 T", "5" = "CD4 T", "7" = "Myeloid", 
                                "8" = "FCER1A+ myeloid", "9" = "B cells", "11" = "mixed", "12" = "CD14+ CD16+ monocytes", "13" = "Dendritic cells")

Idents(object = immune.combined) <- factor(x = Idents(object = immune.combined), levels = c("CD4 T", "CD8 T", "Myeloid", "FCER1A+ myeloid", "Dendritic cells","mixed", "B cells", "CD14+ CD16+ monocytes"))

myeloid.cells <- subset(x = immune.combined, idents = "Myeloid")
Idents(object = myeloid.cells) <- "stim"
avg.myeloid.cells <- log1p(x = AverageExpression(object = myeloid.cells, verbose = FALSE)$RNA)
avg.myeloid.cells$gene <- rownames(x = avg.myeloid.cells)

immune.combined$celltype.stim <- paste(Idents(object = immune.combined),sep = "_", immune.combined$stim)
immune.combined$celltype <- Idents(object = immune.combined)
Idents(object = immune.combined) <- "celltype.stim"
myeloid.stim.response <- FindMarkers(object = immune.combined, ident.1 = "Myeloid_STIM", ident.2 = "Myeloid_CTRL", verbose = FALSE)

Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: Myeloid_STIM

**Comment by mojaveazure** [comment]
Have you checked to see what the values of `immune.combined$celltype.stim` are?

**Comment by SFF-singecell-user** [comment]
Hi Paul, Thanks so much- simple but good suggestion and it helped me figure out the problem.
Appreciate all of your lab’s help with everything

**Comment by Kabooma7** [comment]
Hello, I am having the same issue. Could please elaborate on how "immune.combined$celltype.stim" and "head(x = Idents(object = immune.combined))" helped solve the problem?

Thanks in advance

**Comment by jackhedberg** [comment]
Hello, I am having the same error come up, except that I'm using the FoldChange() function rather than FindMarkers(). My idents are appropriate and I confirmed they are showing up correctly as per mojaveazure's suggestion above. Yet I still get this error when I try to run FoldChange() on my Seurat object: 

Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: Virus

Any suggestions are appreciated.

**Comment by ytyangxiao** [comment]
> 

```
  immune.combined$celltype.stim <- paste(Idents(immune.combined), immune.combined$stim, sep = "_")

  immune.combined$celltype <- Idents(immune.combined)

  Idents(immune.combined) <- "celltype.stim"
```

 The third command changed the Idents. Then you need to return it by using the command,

  ## reset Idents
  Idents(immune.combined) <- "celltype"

**Comment by laumanzanares** [comment]
Hello, I am having the same problem but haven't been able to fix it.

T0_R.markers <- FindMarkers(immune.combined.sct, assay = "SCT", ident.1 = "naive", ident.2 = "NR",
+                                      verbose = FALSE, recorrect_umi = FALSE)
Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: naive

When I try 
> head(x=Idents(object = immune.combined.sct)
Pa_AAACCCACAACACAAA-1 Pa_AAACCCACAAGTCCCG-1 Pa_AAACCCACAATGTCTG-1 Pa_AAACCCACACATTCGA-1 Pa_AAACCCACAGTAGTTC-1 
 23_naive_naive_naive   0_naive_naive_naive   0_naive_naive_naive   3_naive_naive_naive   4_naive_naive_naive 
Pa_AAACCCACAGTCTTCC-1 
  3_naive_naive_naive 
55 Levels: 23_naive_naive_naive 0_naive_naive_naive 3_naive_naive_naive 4_naive_naive_naive ... 26_NR_NR_NR

There is obviously something I did wrong since the name of treatment appears three times. Sorry if its a simple question but I am not an expert and I would really appreciate someone's help.
