### ISSUE TITLE
error in object@commands

### ISSUE THREAD

**Issue by zhumengyan** [satijalab/seurat#1490]
Thanks for your great tools for scientific community.
I have two questions:
1. I find error in object@commands$FindVariableFeatures.RNA, 
  mean.function : Error in cat(names(params[p]), ":", params[[p]], "\n") : 
  argument 3 (type 'closure') cannot be handled by 'cat'

2. If I want to run function "FindClusters" several times using different parameters. How can I know which parameters are used currently.

I am using Seurat 3.0 in centos. data is from 10X.

**Comment by andrewwbutler** [comment]
Hi,

1. This is because it's trying to print a function (e.g. the `mean.function` and `dispersion.function` parameters) and it seems that `cat` doesn't like that. If you're interested in retrieving any of the values from `FindVariableFeatures`, you should still be able to pull them out with the `Command` function.
2. `FindClusters` currently only stores the results of the latest call. However, if the parameter that you want to vary is `resolution`, you can provide a vector of values to `resolution` rather than making separate calls.

**Comment by zhumengyan** [comment]
Thanks for quick reply!
I have another question. When I want to get Umap plot with combination of different resolution and dim . if I provide a vector of values to resolution to "FindClusters", and then I use "RunUMAP", Which resolution is used , or resolution is meaningless to function RunUMAP?

**Comment by mojaveazure** [comment]
Hi @zhumengyan,

`RunUMAP` does not take into account the resolution used for clustering. As seen in our [documentation for `RunUMAP`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.0/topics/RunUMAP), you can run UMAP on either an expression matrix of certain features, a nearest neighbor graph from `FindNeighbors`, or the embeddings matrix of another dimensional reduction.
