### ISSUE TITLE
Cell Cycle effect can`t be removed

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1500]
Hi Seurat team :
    This question related to https://github.com/satijalab/seurat/issues/1305. At that time, I use Seurat version 2.3.4. Now I change to Seurat version 3.0. After integrated data, I want to regress the effect of cell cycle. Now I have three questions that 
(1) To calculate cell cycle score, which assays should be used ? "RNA" or "Integrated". 
(2) When run ScaleData, I know I should use the "integrated" assays, but the "integrated" assays dont have the slot of "counts". So I can not use "poisson" or "negbinom" model in this step ?
 You also have methioned that poisson', and 'negbinom perform better if have enough cells.
(3) I try use "integrated" and "RNA" to calcualte cell cycle score separelty, and ScaleData use "linear" by default. But I can still found a cluster full of T cells, B cells, Monocytes ....... and they are all express cell cycle genes. So the linear modle cant regress out the cell cycle in my samples. Any advices for this situation ?

Many thanks
Best

**Comment by satijalab** [comment]
We can advise the following:

1. When running IntegrateData, make sure that you integrate all features, and not just the variable genes - i.e. set `features.to.integrate` to be equal to all genes in the object. This ensures that the integrated assay will keep values for cell cycle genes.
2. After running IntegrateData, calculate cell cycle scores on the integrated assay.
3. When running `ScaleData` after integration, use the cell cycle scores as `vars.to.regress`, under a linear model.

That will remove cell cycle effects from your data. If you continue to see a cluster of cells that expresses CC genes, then I expect that this cluster is also defined by additional features (in addition to the cell cycle), which is why it remains distinct.

**Comment by kunal368** [comment]
Hi Seurat team:

As per the recommendations above I am using following code to make sure that I integrate all features when running IntegrateData

```
####Integration of cell datasets
all_genes <- as.vector(unique(c(rownames(E8.5@assays$RNA),rownames(E9.5@assays$RNA))))

reference.list <- list(E8.5, E9.5)
integration_anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)
integrated.obj <- IntegrateData(anchorset = integration_anchors, dims = 1:30, features.to.integrate = all_genes) #Integrating using anchors
```
I am getting following error on running IntegrateData: 
**Integrating data
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing**

I am not sure how to resolve this. Does something needs to be done in FindIntegrationAnchors function?
