### ISSUE TITLE
find marker gene when using SCTranform normalization method

### ISSUE THREAD

**Issue by wupeng2** [satijalab/seurat#1501]
hello,
thans for your excellent jobs. 
but i still fell confused about find marker gene for cluster for single sample after read your vignette.
there are two way to find marker.
option 1:cluster and find marker use SCTransform data 
fresh.second <- SCTransform(object = fresh.second, vars.to.regress = "percent.mt", verbose = FALSE,return.only.var.genes = FALSE)
fresh.second <- RunPCA(object = fresh.second, features = VariableFeatures(object = fresh.second))
pca<-1:30
fresh.second <- RunUMAP(fresh.second, dims = pca)
fresh.second <- RunTSNE(fresh.second, dims = pca)

fresh.second <- FindNeighbors(fresh.second, dims = pca)
fresh.second <- FindClusters(fresh.second, resolution = 0.5)
fresh.second.markers <- FindAllMarkers(fresh.second, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

option2:cluster by SCTransform data  and find marker use “RNA” data 
fresh.second <- SCTransform(object = fresh.second, vars.to.regress = "percent.mt", verbose = FALSE,return.only.var.genes = FALSE)
fresh.second <- RunPCA(object = fresh.second, features = VariableFeatures(object = fresh.second))
pca<-1:30
fresh.second <- RunUMAP(fresh.second, dims = pca)
fresh.second <- RunTSNE(fresh.second, dims = pca)
fresh.second <- FindNeighbors(fresh.second, dims = pca)
fresh.second <- FindClusters(fresh.second, resolution = 0.5)
DefaultAssay(object = fresh.second) <- "RNA"
fresh.second <- NormalizeData(object =fresh.second, normalization.method = "LogNormalize", scale.factor = 10000)
all.genes <- rownames(x = pbmc)
fresh.second  <- ScaleData(object = fresh.second, features = all.genes)
fresh.second .markers <- FindAllMarkers(fresh.second , only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
which one do you recommend?
thanks 
best wishes!

**Comment by satijalab** [comment]
Apologies for the confusion, neither option is incorrect, and we've been considering this over time. We recommend option 1, but option 2 is not incorrect.

Note that the absolute best way to do this is to run DE on the pearson residuals themselves, which are stored in object[["SCT"]]]@scale.data. We don't support this yet in Seurat, but will soon. Still, the results between all three approaches should be extremely similar

**Comment by guoyanzhao** [comment]
Dear Seurat Team,
Thank you for this wonderful tool. It has been very useful in analyzing our data.

I did some comparison of DEG detection using SCTransform, RNA and integrated assays and various methods. Surprisingly the results varied a lot depending on the assay used and the input data. I would like to hear your thoughs on the analysis and results.

To summarize I have two sets of data: 

Dataset 1: cell2 have twice the number of nUMIs as that of cell1 due to treatment (they are the same cell because they are clustered together in the same cluster).
Dataset 2: cell1 and cell2 have similar nUMIs (they are the same type of cells as data set 1 because they are clustered together in the same cluster at low resolution).

Since you recommended “the absolute best way to do this is to run DE on the pearson residuals themselves, which are stored in object[["SCT"]]]@scale.data.” I used “return.only.var.genes = FALSE” to obtain pearson residuals as suggested: 

C1_subset <- SCTransform(C1_subset, return.only.var.genes = FALSE, vars.to.regress = c("percent.mito", "nCount_RNA"), verbose = FALSE) 

Then I used  the following command to use Pearson residuals for DEG detection for wilcox, bimod, t test and changed the “test.use” to the corresponding test.

FindMarkers(object = C1_subset, ident.1 = cell1, ident.2 = cell2, assay = "SCT", slot = "scale.data", only.pos = FALSE, min.pct = 0.25, test.use = "wilcox", logfc.threshold = 0.25)

For DESeq2 and negbinom method I removed “slot = "scale.data",” from the command. 

For each of the assay (SCTransform, RNA and integrated) I performed DEG detection using wilcox, bimod, 	t test, DESeq2 and negbinom. Here is what I observed (the table below summarized the results.):

1)	For cells sequenced at similar depth no matter which normalization method or DEG detection method was used the results were all similar. 
2)	For cells with very different sequencing depth different methods gave very different results depending on the assay and DEG detection method used for the analysis. When using “integrated” assay different methods gave more consistent results (only wilcox, bimod, t test was able to run on the integrated data). 
3)	The level of gene expression change seems more biologically reasonable when using “RNA” or “integrated” assay (range of avg_logFC 0.54 to -0.82 and 0.94 to -0.94) than when using “SCT” assay (range of avg_diff  -2023.84  to  616.06). 

data set 1 (cell2 have twice the number of nUMIs as that   of cell1): number of DEGs detected
normalization | wilcox | bimod | t test | DESeq2 | negbinom
SCT                 | 1488 | 6118 | 30 | 1130 | 1563
RNA                | 161 | 404 | 132 | 3311 | 4852
integrated       | 328 | 402 | 390 | NA | NA
For wilcox, 29 DEGs from SCT and RNA overlap. 26 DEGs from SCT and integrated overlap. 

Data set 2 (cell1 and cell2 have similar nUMIs): number of DEGs detected
normalization | wilcox | bimod | t test | DESeq2 | negbinom
SCT                 | 64 | 133 | 74 | 64 | 38
RNA                | 27 | 29 | 28 | 64 | 40
integrated       | 35 | 39 | 37 | NA | NA

Below tables show overlap of DEG between Wilcox method and all other methods:
data set 1:
normalization | wilcox | Overlap with bimod DEG | Overlap with t test DEG | Overlap with DESeq2 DEG | Overlap with negbinom DEG
SCT                 | 1488 | 1445 | 25 | 31 | 104
RNA                | 161 | 161 | 131 | 46 | 161
integrated       | 328 | 326 | 325 | NA | NA

data set 2:
normalization | wilcox | Overlap with bimod DEG | Overlap with t test DEG | Overlap with DESeq2 DEG | Overlap with negbinom DEG
SCT                 | 64 | 46 | 60 | 56 | 35
RNA                | 27 | 27 |   | 26 | 26
integrated       | 35 | 35 | 35 | NA | NA

My question is:
1)	Whether my command for doing SCTransform is correct?
2)	Whether my command to use Pearson residuals for DEG detection is correct?
3)	Several people suggested of using “integrated” assay why this is not correct? From my test using “integrated” assay detected the same DEGs as using SCT and RNA assays when two cell populations have similar nUMIs. The number of DEGs and the range of fold change seemed more biological reasonable. Also when using “integrated” assay the results from different DEG detection method are more consistent with each other. This is true for both data sets.

I would like to hear your thoughts on my analysis result. Or am I missing anything important in the analysis? Sorry for this long post. I sincerely appreciate your time and help!

**Comment by JingleW** [comment]
> hello,
> thans for your excellent jobs.
> but i still fell confused about find marker gene for cluster for single sample after read your vignette.
> there are two way to find marker.
> option 1:cluster and find marker use SCTransform data
> fresh.second <- SCTransform(object = fresh.second, vars.to.regress = "percent.mt", verbose = FALSE,return.only.var.genes = FALSE)
> fresh.second <- RunPCA(object = fresh.second, features = VariableFeatures(object = fresh.second))
> pca<-1:30
> fresh.second <- RunUMAP(fresh.second, dims = pca)
> fresh.second <- RunTSNE(fresh.second, dims = pca)
> 
> fresh.second <- FindNeighbors(fresh.second, dims = pca)
> fresh.second <- FindClusters(fresh.second, resolution = 0.5)
> fresh.second.markers <- FindAllMarkers(fresh.second, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
> 
> option2:cluster by SCTransform data and find marker use “RNA” data
> fresh.second <- SCTransform(object = fresh.second, vars.to.regress = "percent.mt", verbose = FALSE,return.only.var.genes = FALSE)
> fresh.second <- RunPCA(object = fresh.second, features = VariableFeatures(object = fresh.second))
> pca<-1:30
> fresh.second <- RunUMAP(fresh.second, dims = pca)
> fresh.second <- RunTSNE(fresh.second, dims = pca)
> fresh.second <- FindNeighbors(fresh.second, dims = pca)
> fresh.second <- FindClusters(fresh.second, resolution = 0.5)
> DefaultAssay(object = fresh.second) <- "RNA"
> fresh.second <- NormalizeData(object =fresh.second, normalization.method = "LogNormalize", scale.factor = 10000)
> all.genes <- rownames(x = pbmc)
> fresh.second <- ScaleData(object = fresh.second, features = all.genes)
> fresh.second .markers <- FindAllMarkers(fresh.second , only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
> which one do you recommend?
> thanks
> best wishes!

Hi, as shown above, "percent.mt" was regressed out during SCTransformation. Do I need regress out "percent.mt" during the process of "ScaleData" if I followed Option 2 to perform DE analysis with  "RNA" Assay? Thanks.

**Comment by Lucyyang1991** [comment]
> Apologies for the confusion, neither option is incorrect, and we've been considering this over time. We recommend option 1, but option 2 is not incorrect.
> 
> Note that the absolute best way to do this is to run DE on the pearson residuals themselves, which are stored in object[["SCT"]]]@scale.data. We don't support this yet in Seurat, but will soon. Still, the results between all three approaches should be extremely similar

So, after three years, did the Seurat support run DE on the pearson residuals themselves, which are stored in object[["SCT"]]]@scale.data?

**Comment by mauritsunkel** [comment]
Their new DE solution after SCT pipeline: https://satijalab.org/seurat/articles/sctransform_v2_vignette.html
