### ISSUE TITLE
I have problem with calculating jackstraw

### ISSUE THREAD

**Issue by kks101790** [satijalab/seurat#1505]
I have problem with calculating jackstraw. Although I've using the Seurat since version 2, I didn't have any problem calculating jackstraw. Below is the process I've been done.

        Seurat_obj <- CreateSeuratObject(RawMat, project="VC")
        Seurat_obj <- NormalizeData(Seurat_obj, normalization.method = "LogNormalize")
        Seurat_obj <- FindVariableFeatures(Seurat_obj, selection.method = "vst", nfeatures = 2000)
        all.genes <- rownames(x = Seurat_obj)
        Seurat_obj <- ScaleData(Seurat_obj, features = all.genes)
        Seurat_obj <- RunPCA(Seurat_obj, features = VariableFeatures(object = Seurat_obj), npcs=min(dim(Seurat_obj))-1)
        Seurat_obj <- JackStraw(Seurat_obj, num.replicate = 100, dims = min(dim(Seurat_obj))-1)

When calculating Jackstraw function I receive error message like below.

Error in `[[.Seurat`(object, paste0("RunPCA.", assay)) :
  Cannot find 'RunPCA.RNA' in this Seurat object

Can you tell me what's wrong with this process?

Thank you.

**Comment by satijalab** [comment]
Your error indicates that somehow Seurat3 may not be correctly installed. can you check to make sure that you can run:

`pbmc_small <- JackStraw(pbmc_small)` (note that you may receive some warnings about singular values since its a small toy dataset, bu thats fine)

If you cannot run this then please restart R and reinstall Seurat3 using the instructions here: https://satijalab.org/seurat/install.html

Also, you should not be setting dims to be such a  large number (the minimum of the total number of cells ,or the total number of genes). Since PCA is trying to find a low-dimensional representation, this parameter is typically set <100.
