### ISSUE TITLE
"No cells found" when using subset

### ISSUE THREAD

**Issue by zhumengyan** [satijalab/seurat#1511]
Hi,
I used different resolution parameters in `FindClusters`, and default resolution is 2. 
However, when I want to use `subset` on other resolution, I come across an error:
"Error: No cells found". But if I use default parameter "2", no error occured.

I don't know if it is a bug or I should switch resolution parameter in other ways. 
Thanks

Code: 
`
RD001.obj2 <- FindClusters(object = RD001.obj2, resolution = seq(0.5, 2.0, 0.1)) 
RD001.obj2@active.ident <- RD001.obj2@meta.data$RNA_snn_res.0.6 
RD001.obj2@meta.data$seurat_clusters <- RD001.obj2@meta.data$RNA_snn_res.0.6 

RD001.obj2 <- RunUMAP(object = RD001.obj2, dims = 1:20) 
RD001.tumor <- subset(x = RD001.obj2, subset=Phase == "G1")
`

**Comment by timoast** [comment]
Here you’re trying to subset on an identity called “Phase” but there’s nothing in the code you have provided showing how that identity was created. I suggest you look at some of the tutorials on the Satija lab website, especially our vignette on Seurat object interaction: https://satijalab.org/seurat/v3.0/interaction_vignette.html

**Comment by rjb67** [comment]
I am having the same issue as well. I am trying to convert a SingleCellExperiment object into a Seurat object and I did so using as.Seurat(). However, after doing this, several metadata features were missing like nCount_RNA, nFeature_RNA, and orig.ident. I got those manually.

When I tried to subset the data, I got the same error of no cells being found which confused me because I can see the counts and data matrices having expression information.

I added cell names to the active.ident portion of the object as levels. It no longer gives the "no cells found" error, but now it runs for a long time and hits the vector memory limit. My guess is that it is either somehow doing endless recursion or something weird.

**Comment by andrewwbutler** [comment]
Hmm, if you can provide some code and data for a reproducible example of that behavior I can look into it.

**Comment by lianov** [comment]
Just looking into the `as.Seurat` function myself, and when you run (with data as shown in https://satijalab.org/seurat/v3.1/conversion_vignette.html):

```
manno <- readRDS(file = "./manno_human.rds")
class(manno)
manno
manno.seurat <- as.Seurat(manno)
colnames(manno.seurat@meta.data)
```

The result of `colnames(manno.seurat@meta.data)` is the original metadata, but no nCount_RNA, nFeature_RNA ... as @rjb67  mentions.

**Comment by hekselman** [comment]
Was this issue addressed? I couldn't find a convenient way to calculate nFeature_RNA and nCount_RNA manually. If you could share a code for this, that will be very helpful! ^_^
Thanks in advance, Idan.

**Comment by andrewwbutler** [comment]
Hi,

Currently, the function we use to compute these is not exported (we will consider exporting) but it is quite straightforward.

```R
nCount <- colSums(x = object[[assay]], slot = "counts"), 
nFeature <- colSums(x = GetAssayData(object = object[[assay]], slot = "counts") > 0))
```
