### ISSUE TITLE
SetAssayData error

### ISSUE THREAD

**Issue by zzgw** [satijalab/seurat#1524]
I tested Get/SetAssayData
all I would like to do is to change one gene name
```
# Set an Assay slot directly
count.data <- GetAssayData(object = pbmc_small[["RNA"]], slot = "counts")
count.data <- as.matrix(x = count.data + 1)
rownames(count.data)[1] = "MS4A1-test"
new.assay <- SetAssayData(object = pbmc_small[["RNA"]], slot = "counts", new.data = count.data)
```
the error message is:
Warning: Adding features not currently present in the object
Error: Attempting to add a different number of cells and/or features

this error maybe similar to issue #1357

**Comment by mojaveazure** [comment]
Hi,

`SetAssayData` will not allow this to happen as the incoming `counts` and `data` slots must have exactly the same feature (row) and cell (column) names. Any cells or features that have different names are removed. While the `scale.data` slot can have fewer features than the assay currently has, the `counts` and `data` slots cannot, hence the error. We have these requirements for object stability, as we were running into too many issues allowing the `data` and `counts` slots to be flexible.

Since feature names are not easily changeable in Seurat, I would recommend either creating a new Seurat object with the modified counts matrix or adding it as a new assay (see our [multimodal analysis vignette](https://satijalab.org/seurat/v3.0/multimodal_vignette.html) for more details about working with multiple assays). We are exploring ways of allowing users to easily change cell and feature names, but have nothing to report at this moment in time.
