### ISSUE TITLE
SubsetData argument "subset.names" vs "subset.name" does not throw a compatibility error

### ISSUE THREAD

**Issue by alexvnesta** [satijalab/seurat#154]
Updated code from Seurat 1.4 to Seurat 2.0. Left old SubsetData function alone. Did not end up actually modifying file unless I changed to subset name not names. No error was thrown.

**Comment by mojaveazure** [comment]
This isn't a bug, it's how R works. SubsetData supports the `...` parameter, allowing arguments that aren't defined by the function to be passed. We use this to send extra parameters to FetchData when `subset.name` is not `NULL`. By default, `subset.name` *is* `NULL`, so the `...` is never used and simply swallowed by R. In your case, the `...` contains `subset.names` while `subset.name` is `NULL`, so the `...`, and by extension `subset.names`, is never used.
```R
  if (! is.null(x = subset.name)) {
    data.use <- FetchData(object, subset.name, ...) # Here is the `...`
    if (length(x = data.use) == 0) {
      return(object)
    }
```

SubsetData is functioning exactly as it should and the documentation and prompt show `subset.name` instead of `subset.names`. Documentation on the `...` can be found in [section 2.1.9 of the R Language Definition](https://cran.r-project.org/doc/manuals/R-lang.html#Dot_002ddot_002ddot).
