### ISSUE TITLE
DotPlot split.by Average Expression in Legend?

### ISSUE THREAD

**Issue by kragrawa** [satijalab/seurat#1541]
Hi I was wondering if there was any way to add the average expression legend on dotplots that have been split by treatment in the new version? Thanks!

This is the split.by dotplot in the new version:
![image](https://user-images.githubusercontent.com/26942963/57797387-30dc6900-76ff-11e9-9604-5dfb415e1913.png)

This is the old version, with the bars labeling average expression in the legend:
![image](https://user-images.githubusercontent.com/26942963/57797680-cbd54300-76ff-11e9-8184-4b8edf4ab169.png)

**Comment by andrewwbutler** [comment]
It doesn't look like there is currently a way to easily add these legends in v3. We will look into adding this back.

**Comment by dorothyzh** [comment]
May I know if the color key for average expression in dot plot is solved in the package or not? I am trying the dotplot, but still cannot show the legend by default.

**Comment by satijalab** [comment]
Answered in #2487

**Comment by alog-trinity** [comment]
It looks like there is a sort of bug in their new version 4.0.2 of Seurat:

the title 'Average Expression" will disappear even one uses their code example:

data("pbmc_small")
cd_genes <- c("CD247", "CD3E", "CD9")
DotPlot(object = pbmc_small, features = cd_genes)
pbmc_small[['groups']] <- sample(x = c('g1', 'g2'), size = ncol(x = pbmc_small), replace = TRUE)
DotPlot(object = pbmc_small, features = cd_genes, split.by = 'groups')

Please see below for details.

cols = c("blue", "red")
split.by = 'condition'
> split.colors <- !is.null(x = split.by) && !any(cols %in%rownames(x = brewer.pal.info))
> split.colors
[1] TRUE

As a result, the condition
 failed:
if (!split.colors) {
        plot <- plot + guides(color = guide_colorbar(title = "Average Expression"))
    }

because
  !split.colors
[1] FALSE  

(see DotPlot code)

**Comment by vd4mmind** [comment]
Thanks for pointing this out.
