### ISSUE TITLE
Whats the difference between "SubsetData" and "subset" function in Seurat v3

### ISSUE THREAD

**Issue by SeadonXing** [satijalab/seurat#1564]
Hi Seurat team :
    My question is whats the difference between "SubsetData" and "subset" function.  For examples I want to extract Endothelial from complex cells data. I think these two command are actually the same : 
```
scObject <- subset(x = scObject.all, idents = c("Endothelial"), invert = FALSE);
scObject <- SubsetData(scObject.all, ident.use= c("Endothelial"))
```
So can you give some exmpels , which situation should I use which function.

Best

**Comment by rjb67** [comment]
Not a member of the team, but "subset" is the new format for "SubsetData" in Seurat v3. They should theoretically do the same thing, but because of the updates to the object format, it would probably be best to use "subset" to avoid any unintentional errors.

**Comment by mojaveazure** [comment]
`SubsetData` is a relic from the Seurat v2.X days; it's been updated to work on the `Seurat` v3 object, but was done in a rather crude way. `SubsetData` will be marked as defunct in a future release of Seurat.

`subset` was built with the `Seurat` v3 object in mind, and will be pushed as the preferred way to subset a `Seurat` object. Not only does it work better, but it also follow's the standard R object syntax and structure, making the `Seurat` object more R-native.

Please note, as we're adhering to the standard R object syntax and structure, `subset` cannot be used programmatically. As I mentioned in https://github.com/satijalab/seurat/issues/1053#issuecomment-454512002, there is a work-around using `FetchData` for programatic subsetting. While we see the value in a programmatic `subset`, we also are striving to make the `Seurat` object as R-like as possible so that our users, especially users new to both R and Seurat, don't have to learn two different methods for interacting with both R objects and `Seurat` objects.
