### ISSUE TITLE
Commands slot not updated in UpdateSeuratObject()

### ISSUE THREAD

**Issue by maggietsui** [satijalab/seurat#1576]
Hi,

Is it possible to update UpdateSeuratObject() so that it transfers everything from the v2 object calc.params slot to the v3 object commands slot? Thanks!

**Comment by mojaveazure** [comment]
Hi Maggie,

We chose to not include the v2 `calc.params` slot in `UpdateSeuratObject` since it would be far too complicated to reconstruct the v2 functions in v3. Not only would we need a map of v2 to v3 function names, we'd also need a map of v2 parameters to v3 parameters. We are open to a PR that would be able to accurately update the v2 `calc.params` to a v3 `Command` object, but this is not something we have the bandwidth for.

If you want to save the v2 `calc.params`, you can use [`Misc<-`](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/Misc) to store the v2 list in the v3 object's miscellaneous data storage.
