### ISSUE TITLE
PercentageFeatureSet(dischs15mins, pattern = "^MT-". All cells have the same value of percent.mt.

### ISSUE THREAD

**Issue by sygongcode** [satijalab/seurat#1583]
Hi, all 
I have some questions about calculating mitochondrial QC metrics with the PercentageFeatureSet function. My sample is Drosophila. When I was doing the QC uses the function PercentageFeatureSet, I got a Warning message:
In SingleExIPlot(type = type, data = data[, x, drop = FALSE], idents = idents,  :
  All cells have the same value as percent.mt.
I don't know why. Do I need to list all the MT genes of Drosophila? And then make some codes?
Can someone help me, thank you.

**Comment by JPingLin** [comment]
Hi, 
I have the same issue before, then I realize that my reference to align my reads with do not include mitochondria sequences. If you work on different species (like not common mouse or human), likely your gene names are not listed the same way as mouse and human do. Because mitochondria gene in mouse and human all started with MT-xx (ex MT-RNR2, MT-ATP6, MT-CO1...) that's why the code pattern ="^MT-" to grab gene names start with it will work. You probably should check your reference FASTA and GTF files to see if a. mitochondria sequences are included, and b. what is the name of the mitochondria genes. So you can change the code pattern ="xxx" to find it. Or in my case, I add the sequence manually to my .fa file and name my mitochondria genes MT-xx in the .gtf file so I don't have to change the code. 

Good luck.

**Comment by sygongcode** [comment]
> Hi,
> I have the same issue before, then I realize that my reference to align my reads with do not include mitochondria sequences. If you work on different species (like not common mouse or human), likely your gene names are not listed the same way as mouse and human do. Because mitochondria gene in mouse and human all started with MT-xx (ex MT-RNR2, MT-ATP6, MT-CO1...) that's why the code pattern ="^MT-" to grab gene names start with it will work. You probably should check your reference FASTA and GTF files to see if a. mitochondria sequences are included, and b. what is the name of the mitochondria genes. So you can change the code pattern ="xxx" to find it. Or in my case, I add the sequence manually to my .fa file and name my mitochondria genes MT-xx in the .gtf file so I don't have to change the code.
> 
> Good luck.

Hi,
Thank you very much for your suggestions. I will try it.
Best wishes
