### ISSUE TITLE
Requesting help with SumarizedExperiment

### ISSUE THREAD

**Issue by BSharmi** [satijalab/seurat#1585]
Hi,

I am Trying to run Seurat version 3.0.1 on 10X 1 million cells on mouse E18.5 brain data. I followed the instructions on https://satijalab.org/seurat/v3.0/conversion_vignette.html on getting Seurat object from SingleCellExperiment object. I installed scater and loomR. I am getting an error while creating the Seurat object.

    library(restfulSE)
    library(Seurat)
    library(scRNAseq)

    my10x = se1.3M()
    my10x_sc = as.SingleCellExperiment(my10x)

The last line gives an error- 
Error in UseMethod(generic = "as.SingleCellExperiment", object = x) : 
  no applicable method for 'as.SingleCellExperiment' applied to an object of class "c('SummarizedExperiment', 'Vector', 'Annotated')"
    
So I tried this and it worked - 
   
     my10x_sc = SingleCellExperiment(my10x)

Then I create a Seurat object after adding assaynames - 
    
    assayNames(my10x_sc)[1]<- "counts"
    my10x.seurat <- as.Seurat(my10x_sc, counts = "counts")

But since there is no 'logcounts' assay I get the error - 
Error: No data in provided assay - logcounts

I searched for the error and found a few posts (https://github.com/satijalab/seurat/issues/859, https://github.com/satijalab/seurat/issues/837) but they do not start with an object of class 'SummarizedExperiment'. 

Is there a tutorial that talks about creating a Seurat object from 'SummarizedExperiment'? I would greatly appreciate thehelp.

Thank you very much

**Comment by mojaveazure** [comment]
Hi Sharmi,

`as.SingleCellExperiment` doesn't have a method to convert `SummarizedExperiment` objects to `SingleCellExperiment` objects. If you look at the [documentation](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/as.SingleCellExperiment), you'll see there's only one method defined for `as.SingleCellExperiment`, and that's for `Seurat` objects. You can also see this in R by using the `methods` function:

```R
> methods(generic.function = 'as.SingleCellExperiment')
[1] as.SingleCellExperiment.Seurat*
see '?methods' for accessing help and source code
```

To convert a `SummarizedExperiment` to a `SingleCellExperiment`, you'll need to use Bioconductor's code (I assume they already have functions to do this conversion, since the `SingleCellExperiment` class is based on the `SummarizedExperiment` object). Conversion from a `SingleCellExperiment` object to a `Seurat` object can be done with `as.Seurat`

As for the error regarding not finding `logcounts`, if you read the [documentation](https://www.rdocumentation.org/packages/Seurat/versions/3.0.1/topics/as.Seurat), you'll see that you can pass `NULL` to the `data` parameter of `as.Seurat` to avoid looking for a normalized data slot in the `SingleCellExperiment` object

**Comment by BSharmi** [comment]
Thank you very much for the pointers.
