### ISSUE TITLE
FindClusters returning error

### ISSUE THREAD

**Issue by whitleyo** [satijalab/seurat#161]
Hello,

Using Seurat on R3.4 on Windows, I've tried going through the 2700 PBMCs tutorial. When I try running the Find Clusters function, I obtain this error.

> pbmc <- FindClusters(object = pbmc, reduction.type = "pca", dims.use = 1:10, 
+                      resolution = 0.6, print.output = 0, save.SNN = TRUE)
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: running command 'java -jar "C:/Users/newot/Documents/R/win-library/3.4/Seurat/java/ModularityOptimizer.jar" "C:/Users/newot/Documents/R/win-library/3.4/edge_34905.txt" "C:/Users/newot/Documents/R/win-library/3.4/output34905.txt" 1 0.6 1 100 10 0 0' had status 127 
2: In file(file, "rt") :
  cannot open file 'C:/Users/newot/Documents/R/win-library/3.4/output34905.txt': No such file or directory

It seems that the file output34905.txt does not in fact exist. I'm looking into the source code for the FIndCluster function, but if someone is able to identify a potential issue here, that would be great. Thanks for your help.

**Comment by satijalab** [comment]
1. Have you tried setting the temp.file.location to a different directory?
2. See issue #104 , reinstalling the package (or reinstalling from CRAN) may help

**Comment by jpoles1** [comment]
I have tried both of the above solutions and I am still getting the same error : 
`cannot open file 'C:/Users/$USER/tmp/output_21088.txt': No such file or directory`
The edge file gets written there, but the output does not.

**Comment by alcooj** [comment]
I also had the same problem. It turned out the solution was to install Java; the computer I was working on didn't have it. I glossed over this requirement since I did the Seurat installation from CRAN. I couldn't seem to locate the page where I saw it, but the suggestion to install the dev version helped me out: http://satijalab.org/seurat/devinstall.html
Maybe the Seurat team should also have the Java requirement reflected on the "Install from CRAN" page, specially for first-time installations.
