### ISSUE TITLE
Merging reclustered clusters

### ISSUE THREAD

**Issue by pagarwal14** [satijalab/seurat#1621]
Hi,
I am using Seurat 2 for analyzing a 10X data set and got a set of clusters that seemed to reasonably explain the experiment and underlying biology.  But there are 2 clusters that I needed to combine and recluster which gave me 4 sub-clusters and these seem to better separate out the cell types within the two original clusters. Now I need to merge these 4 sub-clusters from the 2 original clusters with the rest of the clusters.  I cannot figure out how to do this, since the 2 original clusters now have their own cluster assignment.
Just to make sure the problem is clear, the following might help.
Original clusters = 0,1,2,3,4,5,6,7,8
Clusters 2 and 4 were combined and reclustered to give 4 clusters A,B,C and D.
Now I would like the clusters to be 0,1,3,5,6,7,8,A,B,C, and D as part of the original object.
Is there a way to achieve this in Seurat?
Thanks,
- Pankaj

**Comment by andrewwbutler** [comment]
Hi Pankaj,

Ultimately, all you really need is a column in meta.data that has the combined vector of new cluster ids. If you have two separate Seurat objects (one for all the original clusters except 2 and 4 and one for just 2 and 4 after reclustering), you can create a new meta.data column in both objects with the same name and then simply merging the objects should be sufficient. Otherwise, you could create this named vector yourself (or 1 column data.frame) and use `AddMetaData` to add it to the Seurat object.

**Comment by Yale73** [comment]
Hi Andrew,@andrewwbutler 

I have two separate Seurat objects, but after I added a new meta.data column and merge them, there is no dimensional reduction ("tsne", "umap", "pca") to run the Dimplot. Even I added the cluster information, I can not add the cell.embeddings. How to fix it?

Thanks,
Yale

**Comment by andrewwbutler** [comment]
Hi Yale,

After merging you will need to regenerate the dimensional reduction on the merged object.

**Comment by Yale73** [comment]
@andrewwbutler Hi Andrew,

I rerun the dimensional reduction, but the original clusters were messy because of new variable features for PCA (the following plot). But if I didn't run the FindVaribleFeatures(), I can not run the dimensional reduction. If I chose the markers I am interested in, they will not be unsupervised. Is there a way to keep original clusters clearly separated?

![image](https://user-images.githubusercontent.com/50378244/116155982-bfa1e080-a69f-11eb-9d6b-cda2769141b9.png)

Thanks,
Yale

**Comment by andrewwbutler** [comment]
Hi Yale,

Can you elaborate on what exactly you did up until this point? If you clustered each dataset separately, there's no guarantee that the cluster numbers from each dataset will correspond to equivalent cell types/states so it's not unexpected that this kind of plot would look messy (if I understand what you're showing correctly).

**Comment by RajneeshSrivastava** [comment]
> Hi Andrew,@andrewwbutler
> 
> I have two separate Seurat objects, but after I added a new meta.data column and merge them, there is no dimensional reduction ("tsne", "umap", "pca") to run the Dimplot. Even I added the cluster information, I can not add the cell.embeddings. How to fix it?
> 
> Thanks, Yale

Hi Seurat team,
To address similar issue posted earlier by @Yale73 , I used the function **merge.dr** while merging two (or list of) seurat objects (see below) while retaining the dimensional reductions. But I think, this is only applicable for same #clusters/ subtypes retained let's say while sub-setting the original object.
```
SeuO1=subset(SO,subset=group=="A")
SeuO2=subset(SO,subset=group=="B")
#do subsampling with subset_objects and merge
SeuOs <- merge(SeuO1, y = SeuO2, merge.data = TRUE, add.cell.ids = c("A", "B"), merge.dr=c("pca","tsne","umap"))
```
Just wanted to cross check with Seurat team/ @andrewwbutler if this approach is correct?

-Rajneesh

**Comment by dimitrisokolowskei** [comment]
Hi,

I would also want to know if the approach proposed by @RajneeshSrivastava is correct. Thanks!
