### ISSUE TITLE
Doheatmap order won't change with active.ident

### ISSUE THREAD

**Issue by JPingLin** [satijalab/seurat#1632]
Hi, 
I am using Seurat v3. My doheatmap for some reason locked at 0 1 10 11 ... 2 3 4 5... order. I have changed levels as instructure as #1589, and the order did change, but heatmap results is still the same at 0 1 10 11 13 14 2 3 4 5 6 7 8 9 order. What should I do differently? Thanks! 

levels(X@active.ident)
>  [1] "0"  "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14"
X@active.ident <- factor(x = X@active.ident, levels = c(0,1,5,6,2,3,4,7,8,9,10,11,12,13,14))
levels(X@active.ident)
>  [1] "0"  "1"  "5"  "6"  "2"  "3"  "4"  "7"  "8"  "9"  "10" "11" "12" "13" "14"
DoHeatmap(object = X, features = topn.list$gene, size=2, hjust=0, angle = 0, slot = "scale.data", draw.lines = TRUE, group.by= "ident") + scale_fill_viridis() + theme(text = element_text(size = 3)) + NoLegend() 

![Screen Shot 2019-06-04 at 12 08 15 PM](https://user-images.githubusercontent.com/50379176/58895747-ad40e700-86c2-11e9-91e0-b75806a57f79.png)

sessionInfo()
>Show in New WindowClear OutputExpand/Collapse Output
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sessioninfo_1.1.1      refGenome_1.7.7        RSQLite_2.1.1         
 [4] doBy_4.6-2             clustree_0.4.0         ggraph_1.0.2          
 [7] RColorBrewer_1.1-2     reticulate_1.12.0-9001 magick_2.0            
[10] scales_1.0.0           viridis_0.5.1          viridisLite_0.3.0     
[13] dplyr_0.8.1            cowplot_0.9.4          ggplot2_3.1.1         
[16] Seurat_3.0.1.9010     

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

Just pushed a fix for this on the develop branch. Can you give it a try and see if it resolves the issue?

**Comment by JPingLin** [comment]
It is working now, thank you for the prompt response!!

**Comment by hfberg** [comment]
Hi! I have the same issue, And I've tried some of the workarounds in #1589 but they don't work. I also don't want to use the developer version since i'm not developing. Could you please update the seurat package to include the fix? :):):)

**Comment by mojaveazure** [comment]
@hfberg

The `develop` branch not only is what's used for developers to build off of, but also serves as a preview of the next version of Seurat. If you want the latest bug fixes, you'll need to use the `develop` branch.

Updating the package requires a new CRAN submission, which has its own time constraints. These don't include just packaging and submission, but also checks, tests, binary building, and propagation to CRAN mirrors. Moreover, CRAN has time limits between submissions, so we can't just push updates through CRAN whenever we want. Instead, we have to wait for a large and important enough collections of fixes and improvements before making a new submission. 

Because of these restrictions on updating Seurat through CRAN, we do iterative patching on the `develop` branch to ensure our users always have bug fixes available to them. Until a new update is on CRAN, you can use the `develop` branch for the latest set of fixes and improvements to Seurat.

**Comment by cemalley** [comment]
I installed the development branch and still have this issue. Order is not changed by refactoring nor renaming the idents with a prefix in the order I want. Have to move to a manual ComplexHeatmap instead.
