### ISSUE TITLE
UMAP : conda environment r-reticulate not found

### ISSUE THREAD

**Issue by raphaelmng** [satijalab/seurat#1642]
Hello,

I am a bit new in bioinformatics and wanted to follow the workflow of Satija Lab for scRNAseq analysis but I have a problem with umap. When I try to download thanks to `reticulate::py_install(packages ='umap-learn')` it gives me the error : 
Error in conda_python(envname = envname, conda = conda) : 
  conda environment r-reticulate not found

I don't know what to do to fix that. Can someone help me please? I am on R studio.

**Comment by mojaveazure** [comment]
What happens if you use standard CPython that either came with your computer or from [Python directly](https://www.python.org/)? [We've noticed issues with reticulate and Anaconda not playing nicely together](https://github.com/satijalab/seurat/issues?utf8=%E2%9C%93&q=is%3Aissue+conda+), and would strongly suggest not using it.

**Comment by raphaelmng** [comment]
I don't know the python language and the workflow is written for R, so I don't understand, what do I have to do? Can I apply the workflow on Python?

**Comment by KatjaRM** [comment]
Hi Raphael,
This is what worked for me:

`py_install('umap-learn', method = 'virtualenv')`

If you don't have virtualenv installed, install it via your terminal: 

`pip install virtualenv`

Hope this helps!

Best,

Katja
