### ISSUE TITLE
RunTSNE error: "Remove duplicates before running TSNE." 

### ISSUE THREAD

**Issue by DNB86** [satijalab/seurat#167]
Hi, 
I am using a large data sets (140K). I had this error "Remove duplicates before running TSNE" when running RunTSNE(). This error is due to Rtsne, I know that Rtsne package has a "check_duplicates" argument that can be set to "FALSE".  
1- I was wondering if you can suggest a way to solve this "duplicate_checking" issue when using Seurat. 
2- Just to be sure that I understood what is a duplicate in this case : It is a cell with the same values after pca reduction ? if it is the case I don't see why it is worth it to remove it.
Thanks a lot for your help.

**Comment by andrewwbutler** [comment]
1. You can pass Rtsne function parameters (e.g. check_duplicates = FALSE) to RunTSNE and they will be passed through. Since tSNE is generally just used for visualization, a small number of duplicates is unlikely to be problematic but I would check to see how many you have. A large number of duplicates might indicate an issue with the upstream analysis. 
2. Yes, if you are calling RunTSNE with the default settings, duplicates will be cells with the same PCA scores for the specified dimensions.

**Comment by DNB86** [comment]
check_duplicates = FALSE worked this time. I tried before posting this message it was not working, may be because I was not loading Rtsne package...
Thank you for your precious help.
