### ISSUE TITLE
TSNEPlot in a loop with Seurat V3

### ISSUE THREAD

**Issue by CMC-LI** [satijalab/seurat#1681]
Hi Seurat Team, 

I like Seurat V3's new functions, but ran into an issue while making PDF files of TSNEplots in a for-loop. 

In Seurat V2, I used to be able to do the following to get five different PDF files, each containing a TSNEPlot of the seurat object at the specified resolution: 

   ResolutionList = c("res.0.2", "res.0.4", "res.0.6", "res.0.8", "res.1")

   for (Resolution in ResolutionList){
       seurat <- SetAllIdent(seurat, id = Resolution)
       pdf(paste(Resolution, "_tSNE.pdf", sep=""), width=7, height=7)
       TSNEPlot(object = seurat, do.label = TRUE)
       dev.off()
   }

In Seurat V3, I substituted the old commands with new commands, but only got 5 blank PDF files without anything in it.  

   ResolutionList = c("SCT_snn_res.0.2", "SCT_snn_res.0.4", "SCT_snn_res.0.6", "SCT_snn_res.0.8", "SCT_snn_res.1")

   for (Resolution in ResolutionList){
       Idents(object = seurat) <- Resolution
       pdf(paste(Resolution, "_tSNE.pdf", sep=""), width=7, height=7)
       TSNEPlot(object = seurat, reduction = "tsne", label=TRUE)
       dev.off()
}

If I only generate a single PDF without a for-loop, the new commands worked fine. It was only a problem when I made it into a for-loop. 

I wonder how I can get this to work? Thanks a lot!

**Comment by jspaezp** [comment]
Hey @CMC-LI ... not part of the Seurat team but I hope this is helpful.

In the new version of the functions, the functions don't explicitly print the plot, instead, they return a ggplot object. Therefore you want to explicitly print the object from `TSNEplot` within your loop (something like `print(TSNEplot(...))`).

I would also advise you to use `DimPlot` instead of calling the plot for the dimensional reduction directly since I have found it to work a lot more consistently within `.Rmd` documents.

The following example worked fine for me

```r
require(Seurat)

seurat <- Seurat::pbmc_small
seurat <- FindClusters(seurat, resolution = seq(from = 0.1, to = 1, by = 0.1))
ResolutionList <- grep("_snn_res", colnames(seurat@meta.data), value = TRUE)

for (Resolution in ResolutionList){
    pdf(paste0(Resolution, "_tSNE.pdf"), width=7, height=7)
    g <- DimPlot(object = seurat, do.label = TRUE, reduction = "tsne", group.by = Resolution)
    print(g)
    dev.off()
}
```

Kindest wishes,
Sebastian

**Comment by CMC-LI** [comment]
Thank you Sebastian!
