### ISSUE TITLE
error: could not find function "Setup"

### ISSUE THREAD

**Issue by lilycanfly** [satijalab/seurat#172]
When I follow up the guided tutorial --2,700 PBMCs of Seurat
![pastedgraphic-1](https://user-images.githubusercontent.com/32545217/31230896-612f14a6-a9b3-11e7-9144-c3cc980f7f6c.png)

**Comment by mschilli87** [comment]
If you run `sessionInfo()`, which version of Seurat do you see?

 I'm guessing you are using Seurat >=2.0 which changed the functions for amny of the steps compared to <2.0 versions.
The latest tutorial covers how to analyze data with the current Seurat version.

Instead of `new` & `Setup`, for example, you now have a `CreateSeuratObject` function.

**Comment by lilycanfly** [comment]
Thank you so much. I will check it.
