### ISSUE TITLE
Fewer features in integrated assay

### ISSUE THREAD

**Issue by Zepeng-Mu** [satijalab/seurat#1749]
Hi,

I noticed that in my integrated assay, there are only 1339 features, whereas in RNA assay there are around 18000 features. So I think the 1339 features are only those used to integrate two samples, which makes sense.

However, does this mean that I cannot use the integrated assay to do other types of analysis just as RNA assays? Also, the integrated assay does not contain "counts" slot. So it seems that it is not designed for usage in other analysis? 

Many thanks!

**Comment by timoast** [comment]
You can define the set of features to be integrated using the `features.to.integrate` argument in `IntegrateData`. By default, this is set to the variable features which is why you’re seeing 1339 features. We do not correct the counts slot, so this would be the same as in the original assay. For efficiency, we do not store the same data again in the integrated assay
