### ISSUE TITLE
Error in grid.call

### ISSUE THREAD

**Issue by balthasar0810** [satijalab/seurat#1756]
Dear all,

I am experiencing the issue when calling TSNEPlot(my_seurat_object, params):
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found

Everything worked fine yesterday, didn't do any updates. What happened? I also recalculated the TSNE.

Thx, best, Chris

**Comment by mojaveazure** [comment]
Hi Chris,

This seems to be an error with R, and possibly your computer. A quick Google search found two related StackOverflow questions, [here](https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon) and [here](https://stackoverflow.com/questions/34220883/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon). Since this is not a Seurat issue, we're unable to provide more support than this.

**Comment by balthasar0810** [comment]
Ok. Thanks. Sorry for the bother. Chris

Envoyé de mon iPhone

Le 27 juin 2019 à 17:26, Paul Hoffman <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Chris,

This seems to be an error with R, and possibly your computer. A quick Google search found two related StackOverflow questions, here<https://stackoverflow.com/questions/10581440/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon> and here<https://stackoverflow.com/questions/34220883/error-in-grid-calll-textbounds-as-graphicsannotxlabel-xx-xy-polygon>. Since this is not a Seurat issue, we're unable to provide more support than this.
