### ISSUE TITLE
Featureplot blend in Seurat v3

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#1758]
Hi,

I am using the blend option in Featureplot with two genes. However, I don't need the individual gene expression plots. Is there a way to plot just the blended plot?

Thanks!!

**Comment by mojaveazure** [comment]
Blended feature plots are actually four plots combined into one. The first two are the expression plots for the features independently, the third plot is the co-expression plot, and the last plot is the key. If you want these separate, you can pass `combine = FALSE` to have `FeaturePlot` return a list of plots rather than the combined plot

```R
plots <- FeaturePlot(pbmc_small, features = c('MS4A1', 'LYZ'), combine = FALSE)
plots[[3]] + NoLegend()  # Get just the co-expression plot, built-in legend is meaningless for this plot
plots[[4]] # Get just the key
CombinePlots(plots[3:4], legend = 'none') # Stitch the co-expression and key plots together
```
