### ISSUE TITLE
SCTransform centering and scalig

### ISSUE THREAD

**Issue by atermanini** [satijalab/seurat#1777]
Hi,

with Seurat v2, I was using ScaleData function to regress and scaling data before calling RunPCA. In particular, ScaleData by default use: do.scale = TRUE, do.center = TRUE.

With Seurat v3 I am now using SCTransform, and by default is: do.scale = FALSE, do.center = TRUE. So why in the online tutorial is called RunPCA on non-scaled data? https://satijalab.org/seurat/v3.0/sctransform_vignette.html

Is it better to call:

pbmc <- SCTransform(pbmc, vars.to.regress = "percent.mt", do.center = TRUE, do.scale = TRUE, verbose = FALSE)

pbmc <- RunPCA(pbmc, verbose = FALSE)

Thanks very much,
Alberto

**Comment by satijalab** [comment]
When using SCTransform, we do not run ScaleData prior to PCA. We suggest using the default options.  The reasons are described in more detail here : https://www.biorxiv.org/content/10.1101/576827v2

**Comment by eiden309** [comment]
Hi @satijalab,

I have a question similar to what @atermanini has raised and went to read through the [paper](https://www.biorxiv.org/content/10.1101/576827v2) you have listed above. My understanding is that Pearson residuals obtained from `SCTransform` are better than logNormalized data because Pearson residuals are significantly less correlated with cellular sequencing depth.

However, I am slightly confused because when I was looking at your documentation via `?SCTransform` and it is written that:

> Results are saved in a new assay (named SCT by default) with counts being (corrected) counts, data being log1p(counts), scale.data being pearson residuals

As such, if the argument `do.scale = FALSE` is used for SCTransform, then scale.data would be empty in the SCT assay generate. When we run the `RunPCA` function, are the Pearson residuals not used or does `RunPCA` extract information from the misc slot in SCT assay to generate the PCs? Thank you in advance for the clarification.
