### ISSUE TITLE
padding Seurat object with zeroes to help IntegrateData using all features

### ISSUE THREAD

**Issue by stkachev** [satijalab/seurat#1808]
Hi,

I am trying to integrate 9 existing Seurat object into one and I want to use all features (as a union among all datasets). The reason being there are some markers that are very specific for particular cell types that are not present in all of the datasets. When I try to do this FindIntegrationAnchors step runs fine but then later in IntegrateData I get an error which I think was previously reported: 

Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing

One possible way around this is to pad missing features with zeros and that I think will make sure that all features are "present" in all datasets and it will probably avoid the above error. How can I do that with an existing Seurat object?

**Comment by zh0003ai** [comment]
I have similar issues regarding distinct cell clusters existing in only certain data sets but not all, i.e. cells exclusive to diseases or control group, or at a certain time point. 
When I tried adding zero features to the count matrix, the genes I added were removed after the SCTransfrom step. After SCTransform, I believe it's not valid to add zeros in the scale.data slot anymore, since the corrected expression values are residuals centered around 0, and include negative values. 
Adding zeros in the count matrix would work for the log normalization method, but I want to take the advantage of SCTransfrom. Is there a reasonable workaround to solve this issue?
Thanks a lot!

**Comment by satijalab** [comment]
You can merge the Seurat objects (using the merge function described here) https://satijalab.org/seurat/v3.0/merge_vignette.html, and it will pad with 0s as you request.

2. SCTransform attempts to distinguish biological from technical variation in gene expression, so cannot be run on a gene where all values are 0
