### ISSUE TITLE
number of features used in data integration

### ISSUE THREAD

**Issue by qiuyuguo** [satijalab/seurat#1840]
Dear Seurat team,

As I tried to run data integration with different number of features, I realized that I got somewhat different dimensional reduction result, such as following:

integration with 2000 features
![image](https://user-images.githubusercontent.com/11847281/61382531-cf9d5700-a861-11e9-87d0-fbdeb6ed1d06.png)
integration with > 5000 features
![image](https://user-images.githubusercontent.com/11847281/61382398-9238c980-a861-11e9-95de-2e2359e74b2a.png)

Visually, the one done with 2000 features looks more consistent across samples. Can I argue that the integration done with more features reflects more accurately the true relationships between the samples? What would be your interpretation?

Thanks!
Alex

**Comment by satijalab** [comment]
Indeed, the number of features used does affect the output of all single-cell analyses (including clustering, integration, pseudotime, etc.). Unfortunately we can't advise on the exact value to choose, but agree that the sensitivity of some analyses to this parameter can be frustrating.

Our best suggestion is to use the SCTransform workflow, which weights genes in downstream analysis based on their biological variation. As a result, adding more genes into the analysis makes less of a difference, because they have lower weights. As a result, we find that the results exhibit less sensitivity based on the number of features included.
