### ISSUE TITLE
Seurat v2.3.4 versus latest v3.1

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#1842]
Hi,

If we are deep into a project using Seurat v2.3.4, how compelling is the need to migrate to v3.1?  Are there any concrete ideas as to how the clustering, DE, etc. will get affected?  I use the old normalization in 2.3.4 and other methods therein, and it would be quite a task to move to v3.1 now for the intended publication.  So, I'm grappling with this question, and any advice based on anybody's experience on this regard would be immensely useful!  I expect many others would be in the same situation, where they are close to submitting a manuscript using months of analyses done on v2.3.4 when the cool v3.1 got released.  Please advice.  Thanks.

**Comment by timoast** [comment]
Hi, if you are deep into a project using v2 and have satisfactory results without using any of the new features present in v3 (eg, our improved integration methods), then there might not be a big advantage in repeating everything using v3. You can always update your Seurat objects to v3 using `UpdateSeuratObject` without re-running past analyses in order to use the current version with its improved features.
