### ISSUE TITLE
ScaleData and RunCCA/AlignSubspace

### ISSUE THREAD

**Issue by igordot** [satijalab/seurat#187]
Based on the documentation, both `ScaleData` and `RunCCA`/`AlignSubspace` can be used to correct for batch effects. Obviously, the two procedures are very different algorithms/workflows. Is it just that one is for continuous and the other is for categorical variables?

If that is the case, what is the appropriate approach when you have two groups (so either one is technically possible)?

**Comment by satijalab** [comment]
ScaleData represents an attempt at removing batch effects through linear regression. In the manuscript, we discuss the limitations of standard batch effect correction strategies (regression-based or otherwise) for single cell RNA-seq data, and we developed our integration strategy as an alternative workflow for this challenge.
