### ISSUE TITLE
reference.objects missing

### ISSUE THREAD

**Issue by Biiiiimer** [satijalab/seurat#1885]
Hi, I am using the seurat development version. In the new IntegrateData function, there is a call for reference.objects, however since I did not use a reference in FindIntegrationAnchors, this is missing in my Anchorset object, leading to an error and forcing me to use the old IntegrateData function (from master).

Furthermore, I also have an analysis question. I am integrating multiple datasets of which two are more similar to each other than to the rest. When finding anchors, these two datasets have a lot of anchors between them, but not with the others leading to a bad integration. When specifically integrating the merger of those two datasets with the merger of the other datasets, the issue persists since only a small number of anchors are found. Increasing k.filter, k.anchor and k.score leads to more anchors, but still integration is faulty. I am using SCT transform for normalization. What would be the best approach to integrate these datasets?

**Comment by timoast** [comment]
Hi, if you created an anchorset using an older version of Seurat, without the reference-based integration option, you will need to either use the older IntegrateData function or re-run FindIntegrationAnchors to update the anchorset. This is because we added a slot to the anchorset class to enable the reference-based integration, and the newer version of the IntegrateData function expects that slot to be there. 

We have run integrations between many datasets with varying similarity to each other (eg https://satijalab.org/seurat/v3.0/integration.html) and haven't seen this problem. Is it possible that there are cell states unique to some of the datasets, which could be the reason they don't align in the integration? If you think that these really should align and the batch effects are just very strong, you can try _reducing_ `k.anchor` to be more stringent when finding anchors. You might also try changing the number of dimensions used and setting `weight.reduction="pca"` in IntegrateData.
