### ISSUE TITLE
Export Metadata to ExportToCellbrowser

### ISSUE THREAD

**Issue by baracus37** [satijalab/seurat#1922]
Hi,

I was now able to export my Seurat object to Cellbrowser using `ExportToCellbrowser` Function. Now I would like to add additional Metadata. For example I would to export the object@meta.data$sample. I am aware that the documentation says:

>...    specifies the metadata fields to export. To supply field with human readable name, pass name    as field="name" parameter.

But I do not know how to pass this argument to ExportToCellbrowser. Can someone help?

**Comment by timoast** [comment]
Hi, you can export specific columns of the metadata by providing additional arguments to the ExportToCellBrowser function. For example, to export the column "RNA_snn_res.0.8", do:

```r
ExportToCellbrowser(object = pbmc_small, dir = "cellbrowser", RNA_snn_res.0.8="RNA_snn_res.0.8")
```

**Comment by baracus37** [comment]
Thanks for your help. When i try to do this, I get the following error message from cbBuild:

> ERROR:root:Config statement 'clusterField' contains an invalid field name, 'celltype_clusters_cor'. Valid meta field names are: sample, Cell

I get the same error message when trying to run cbBuild on the cellbrowser.conf directly. I am not sure if this is a ExportToCellbrowser issue or a cbBuild issue.

**Comment by AprilJack** [comment]
This error is caused by Seurat not overwriting previous files. If you delete all files in the output directory and re-run ExportToCellbrowser is the first step to solving this problem. 

If you wish to output more metadata slots you then have to name ALL the slots you'd like to output. Even those that were automatically output before. You also need to point ExportToCellbrowser() to the slot containing the cluster data now. See my example below for an example. In my Seurat object my clusters are stored in the slot named "seurat_clusters". 

Seurat::ExportToCellbrowser(object =pbmc,
                            dir = "cellbrowser/out/",
                            dataset.name = "scRNA",
                            cb.dir = "cellbrowser/out/",
                            port=8789,
                            reductions =c("tsne","umap","pca"),
                            orig.ident="Sample",
                            percent.mt="Percent.Mitochondrial",
                            nCount_RNA="nCount_RNA",
                            nFeature_RNA="nFeature_RNA",
                            seurat_clusters="Clusters",
                            cluster.field= "Clusters")
