### ISSUE TITLE
Duplicate gene name in cell cycle list

### ISSUE THREAD

**Issue by yewero** [satijalab/seurat#194]
The gene `HJURP` was duplicated in the cell cycle list.
The list was in:
http://satijalab.org/seurat/cell_cycle_vignette.html

> You can download the files needed to run this vignette here.

regev_lab_cell_cycle_genes.txt
https://www.dropbox.com/s/3dby3bjsaf5arrw/cell_cycle_vignette_files.zip?dl=1

**Comment by satijalab** [comment]
Thanks very much for the catch. We will fix and replace (if @mojaveazure hasn't already)

**Comment by mojaveazure** [comment]
@yewero The cell cycle gene list has been updated on Dropbox. When you read in the list, the G2M genes are now `cc.genes[44:97]` instead of `cc.genes[44:98]`. As an alternative, the cell cycle gene list is available in Seurat as the `cc.genes` data set. Access to it is gained using the `data` function, and you can view more information on it through its help page.

```R
> library(Seurat)
Loading required package: ggplot2
Loading required package: cowplot

Attaching package: ‘cowplot’

The following object is masked from ‘package:ggplot2’:

    ggsave

Loading required package: Matrix
> data(cc.genes)
> str(cc.genes)
List of 2
 $ s.genes  : chr [1:43] "MCM5" "PCNA" "TYMS" "FEN1" ...
 $ g2m.genes: chr [1:54] "HMGB2" "CDK1" "NUSAP1" "UBE2C" ...
> ?cc.genes
```
