### ISSUE TITLE
Percentage of mitochondrial gene of normalized counts

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#1952]
Hi everyone,
Following the SEURAT tutorial, PercentageFeatureSet calculate the percentage of counts, how i can calculate the percentage after normalization? 
Thank you

**Comment by andrewwbutler** [comment]
Hi,

`PercentageFeatureSet`, as the name implies, is just calculating a percentage. You can take the normalized matrix and compute a percentage by summing the normalized values for the features of interest divided by the total normalized values for the cell (multiplied by 100). You can check out the code for `PercentageFeatureSet` here.
https://github.com/satijalab/seurat/blob/245d72b5f7c3ae75b185f2ae2d3a5b4c67c61e9a/R/utilities.R#L917-L936

Essentially, you would just need to change the slot from "counts" to "data" and use a sum in the denominator instead of relying on the pre-computed nCount value.

**Comment by GBeattie** [comment]
Not sure if anyone got this working, but I've tried myself and come across an error.

Here is my modified function:

```
PercentageFeatureSetNorm <- function( 
  object, 
  pattern = NULL, 
  features = NULL, 
  col.name = NULL, 
  assay = NULL 
) { 
  assay <- assay %||% DefaultAssay(object = object) 
  if (!is.null(x = features) && !is.null(x = pattern)) { 
    warning("Both pattern and features provided. Pattern is being ignored.") 
  } 
  features <- features %||% grep(pattern = pattern, x = rownames(x = object[[assay]]), value = TRUE) 
  obj <- deparse(substitute(object))
  percent.featureset <- colSums(x = GetAssayData(object = object, slot = "data")[features, , drop = FALSE])/ 
    colSums(as.matrix(GetAssayData(object, slot = "data"))) * 100 
  if (!is.null(x = col.name)) { 
    object <- AddMetaData(object = object, metadata = percent.featureset, col.name = col.name) 
    return(object) 
  } 
  return(percent.featureset) 
} 
```

I get the following error:

```
Error in assay %||% DefaultAssay(object = object) : 
  could not find function "%||%"
```

I've searched around but a can't find a usage of the "%||%" operator, any clues would be appreciated!

**Comment by andrewwbutler** [comment]
Hi,

This is a developer convenience function we define internally here: 
https://github.com/satijalab/seurat/blob/fe93b05745e55ec2f66e3f0b4c4196aad9f4d5a7/R/utilities.R#L1511-L1527
