### ISSUE TITLE
Seurat v3.0 RunPCA - Error in data.use[features, ] : no 'dimnames' attribute for array

### ISSUE THREAD

**Issue by Dzhan4** [satijalab/seurat#1958]
It looks like this error has popped up before in other functions, but for me I'm getting it when trying RunPCA. This has been referenced by #1368, and #1337.

My code briefly:

hz.seq <- Read10X("../data/homozygous/mm10/")
hz1 <- CreateSeuratObject(counts=hz.seq, min.cells = 3, min.features = 200)
hz1[["stim"]] <- "hz"

wt.seq <- Read10X("../data/wildtype/mm10/")
wt1 <- CreateSeuratObject(counts=wt.seq, min.cells = 3, min.features = 200)
wt1[["stim"]] <- "wt"

hz1[["percent.mt"]] <- PercentageFeatureSet(hz1, pattern = "^mt-")
wt1[["percent.mt"]] <- PercentageFeatureSet(wt1, pattern = "^mt-")

hz1 <- subset(hz1, subset = nFeature_RNA > 200 & percent.mt < 5)
wt1 <- subset(wt1, subset = nFeature_RNA > 200 & percent.mt < 5)

hz1 <- NormalizeData(hz1)
wt1 <- NormalizeData(wt1)

hz1 <- FindVariableFeatures(hz1, selection.method = "vst", nfeatures = 2000)
wt1 <- FindVariableFeatures(wt1, selection.method = "vst", nfeatures = 2000)

anchors <- FindIntegrationAnchors(object.list = list(hz1, wt1), dims = 1:20)
combined <- IntegrateData(anchorset = anchors, dims = 1:20)

combined <- RunPCA(combined, npcs = 30, verbose = FALSE)

Is there something obvious I'm missing here?

**Comment by cswoboda** [comment]
Not a complete fix, but if you label the cell types for each individual Seurat Object like they do in the tutorial for multiple dataset integration, it will carry in the meta data, so you can integrate the data, and have the clusters appear unintegrated by grouping by cell type. For example:

DimPlot(pancreas.integrated, reduction = "umap", group.by = "celltype", label = TRUE, 
    repel = TRUE) + NoLegend()

Again not a fix for the issue, but if you want to continue with data analysis I believe this should work for you! Sorry I can't be more of a help outside that.

**Comment by Dzhan4** [comment]
Thanks for the response! I apologize if this is a rudimentary question since I think I might not fully comprehend the workflow for integrating data: should I be identifying celltypes for each batch individually with PCA first, assigning celltypes etc, before integrating them together? 

I just ask because in the old Seurat v2, the RunCCA allowed for combined clustering with two or more raw datasets without knowing the celltypes ahead of time.

**Comment by cswoboda** [comment]
Theoretically you should be able to run PCA on integrated data after integration. However, I get the same error trying to run a PCA when integrating more than one data set, and have noticed the PCA is relatively unneeded because the umap reduction from each other data set end up making the UMAP of the integrated look fine. So, if you want to treat each as an individual cluster, if you have the celltypes in the metadata you can just group by them and you should be okay. So to answer your question, identify cell types for each individual batch, store in meta data (should be automatic), and then call them when making the Dimplot of the integrated data. This is what I've been doing while I'm waiting to figure out why I cant PCA the data with more than one integration. Hope that helps!

**Comment by Dzhan4** [comment]
Turns out it was something silly - I didn't scale the integrated Seurat object prior to running PCA. 

This route, I do not identify celltypes in the individual batches, I perform the same pipeline as the code I wrote before where I do not interrogate the individual batches and simply find anchors to integrate, then scale after integration.
