### ISSUE TITLE
Dim plot; cols.highlight unique color for cell.highlight vector?

### ISSUE THREAD

**Issue by jbridge873** [satijalab/seurat#1997]
Hi Guys,
I would like to have my cells.highlight vector Dimplot to have unique colors.  Tried creating a vector of colors to use in cols.highlight but the plot has them all the same color.  Any help?
Code below; 
```R
$clonelist <- mostabundant$barcode
$clonelist
$my_color_palette <- hue_pal()(length(clonelist))
$my_color_palette

$e =(DimPlot(tcr_testing, cells.highlight = clonelist, cols.highlight= my_color_palette, split.by = "orig.ident", group.by = "mouseid", ncol=2))
$e + labs(title = 'Most abdundant clone n=6') + NoLegend()
```

**Comment by mojaveazure** [comment]
As stated in the [documentation for `DimPlot`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.0/topics/DimPlot):

> cells.highlight    A list of character or numeric vectors of cells to highlight. If only one group of cells desired, can simply pass a vector instead of a list. If set, colors selected cells to the color(s) in `cols.highlight` and other cells black (white if dark.theme = TRUE); will also resize to the size(s) passed to `sizes.highlight`

The `cells.highlight` parameter expects a list, not a vector, of vectors of cells. Each entry in the list gets highlighted the same color. If `clonelist` is a vector of cells, and each cell gets its own color, you can convert it to the proper format with `as.list(x = clonelist)`. Otherwise, passing a vector will treat everything as one group (also stated in the docs).
