### ISSUE TITLE
Negative Length Vector Error

### ISSUE THREAD

**Issue by dylanmr** [satijalab/seurat#203]
I am attempting to align two 10X single cell datasets each with about 50,000 cells. The pipeline works fine until the point of alignment. Following the command: `RunCCA(object = ctrl, object2 = test, genes.use = hvg.union)` I receive the following error: 

```R         
Error in FastMatMult(m1 = t(x = mat1), m2 = mat2) : 
length vectors are not allowed
```

Do you have any recommendations on dealing with this issue?

**Comment by mschilli87** [comment]
@dylanmr: If you managed to solve the problem, would you mind sharing the solution for people runnign into this issue in the future?

**Comment by dylanmr** [comment]
@mschilli87 My apologies. I did not mean to remove the issue. Thank you for responding!

**Comment by satijalab** [comment]
We have seen this error occasionally as well, on certain OS installations. It appears to be due to the system running out of memory (often when dealing with sparse matrices). In this case, it appears the matrices entered are too large to be multiplied by the system. 

I am closing the issue as its not directly related to Seurat. In the near future, we will release additional improvements that we hope will assist users working with large datasets - both for performance and memory concerns.
