### ISSUE TITLE
How to improve the result of tSNE and UMAP?

### ISSUE THREAD

**Issue by swlx08** [satijalab/seurat#2053]
Hi,

I am using Seurat 3.0 to integrate my 8 samples (2 KO, 3 WT, 3 KI) via standard workflow.

At the beginning I set the nfeatures = 3000 and  dims = 1:30:
`WT3 <- FindVariableFeatures(WT3, selection.method = "vst", nfeatures = 3000)`
`reference.list <- list(KI1, KI2, KI3, KO1, KO2, WT1, WT2, WT3)`
`ERNP.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:30)`
`ERNP.integrated <- IntegrateData(anchorset = ERNP.anchors, dims = 1:30)`
`DefaultAssay(ERNP.integrated) <- "integrated"`
`ERNP.integrated <- ScaleData(ERNP.integrated, verbose = FALSE)`
`ERNP.integrated <- RunPCA(ERNP.integrated, npcs = 30)`
`ERNP.integrated <- RunTSNE(object = ERNP.integrated, dims.use = 1:30, do.fast = TRUE)`
`ERNP.integrated <- FindNeighbors(ERNP.integrated, reduction = "pca", dims = 1:30)`
`ERNP.integrated <- FindClusters(ERNP.integrated, resolution = 0.4)`

The results of tSNE and UMAP seemed ill-defined and unclear:
![图片](https://user-images.githubusercontent.com/36035647/64117797-b5dfb100-cdc8-11e9-9ad6-d757b7b2bdf8.png)

![图片](https://user-images.githubusercontent.com/36035647/64117817-bed08280-cdc8-11e9-8928-029cebf7034b.png)

Then I tried to set dims = 1:50 and the result didn't improve:
![图片](https://user-images.githubusercontent.com/36035647/64117922-fb9c7980-cdc8-11e9-874e-4fe5692ddbd1.png)

Nor dims = 1:20:
![图片](https://user-images.githubusercontent.com/36035647/64117930-01925a80-cdc9-11e9-9ac2-29f97e497a6d.png)

I also tried to set nfeatures = 5000 and didn't observe any improvement:
`WT3 <- FindVariableFeatures(WT3, selection.method = "vst", nfeatures = 5000)`

Finally, I tried Seurat 2.3.4 (via RunMultiCCA), and it seemed to outperform Seurat 3.0:
![图片](https://user-images.githubusercontent.com/36035647/64118227-c6dcf200-cdc9-11e9-8093-e6a8f8ab28a3.png)

So could you please tell me how improve the result of tSNE and UMAP when using Seurat 3.0? Thanks a million in advance.

Stanley

**Comment by samuel-marsh** [comment]
Hi Stanley,

Not a member of the Dev team but will try and provide some helpful info and would suggest posting in other bioinformatics forums if you are looking for more info as this isn't really Seurat question but more a general single cell question.

The number of clusters and how "defined" the clusters are is going to be result of multiple factors in your code:
--# of variable features selected
--PCs selected
--resolution

You need to adjust these to each individual dataset and there isn't really a standard that is applicable to all datasets.  For variable genes selecting too many or two few to use in the downstream clustering will effect the results depending on how many genes in your dataset are actually highly variable.  i.e. raising your variable genes to 5000 if only say 2000 of the genes in your dataset are highly variable won't likely add significant value.

PC selection is also key in similar fashion.  You need to examine PCs (see ElbowPlot and Jackstraw sections of vignettes for some additional info).  You should also examine PC heatmaps and the genes in each PC as they relate to your dataset.  Again for example if the variance in the dataset is primarily contained in PCs 1:20 then expanding the number of PCs included downstream will likely not have significant impact.  

Resolution can dramatically effect your clustering.  While the overall shape of your tSNE or UMAP will not change the number of clusterings will be altered.  This is something you need to dynamically adjust and examine as it relates to your dataset.  To high a resolution and you end up with ill defined clusters which lack unique markers.  To low and you end up with clusters that are too large and you may miss meaningful info.

Finally, regarding V2 "outperforming" V3 again that is matter of interpretation.  You may find that the clustering results (again accounting for all the parameters above) you think is "better" with V2 than V3 and that is ok.  But I would suggest you deeply read the Butler et al., 2018 and Stuart et al., 2019 so that you understand the difference between the two methods in the results that will be output one way or the other.

Hope this is helpful.

Best,
Sam

**Comment by swlx08** [comment]
> 
> 
> Hi Stanley,
> 
> Not a member of the Dev team but will try and provide some helpful info and would suggest posting in other bioinformatics forums if you are looking for more info as this isn't really Seurat question but more a general single cell question.
> 
> The number of clusters and how "defined" the clusters are is going to be result of multiple factors in your code:
> --# of variable features selected
> --PCs selected
> --resolution
> 
> You need to adjust these to each individual dataset and there isn't really a standard that is applicable to all datasets. For variable genes selecting too many or two few to use in the downstream clustering will effect the results depending on how many genes in your dataset are actually highly variable. i.e. raising your variable genes to 5000 if only say 2000 of the genes in your dataset are highly variable won't likely add significant value.
> 
> PC selection is also key in similar fashion. You need to examine PCs (see ElbowPlot and Jackstraw sections of vignettes for some additional info). You should also examine PC heatmaps and the genes in each PC as they relate to your dataset. Again for example if the variance in the dataset is primarily contained in PCs 1:20 then expanding the number of PCs included downstream will likely not have significant impact.
> 
> Resolution can dramatically effect your clustering. While the overall shape of your tSNE or UMAP will not change the number of clusterings will be altered. This is something you need to dynamically adjust and examine as it relates to your dataset. To high a resolution and you end up with ill defined clusters which lack unique markers. To low and you end up with clusters that are too large and you may miss meaningful info.
> 
> Finally, regarding V2 "outperforming" V3 again that is matter of interpretation. You may find that the clustering results (again accounting for all the parameters above) you think is "better" with V2 than V3 and that is ok. But I would suggest you deeply read the Butler et al., 2018 and Stuart et al., 2019 so that you understand the difference between the two methods in the results that will be output one way or the other.
> 
> Hope this is helpful.
> 
> Best,
> Sam

Dear Sam,

Thank you very much for your answer. It is very helpful.

**Comment by naixiangxiaozi** [comment]
> Hi Stanley,
> 
> Not a member of the Dev team but will try and provide some helpful info and would suggest posting in other bioinformatics forums if you are looking for more info as this isn't really Seurat question but more a general single cell question.
> 
> The number of clusters and how "defined" the clusters are is going to be result of multiple factors in your code:
> --# of variable features selected
> --PCs selected
> --resolution
> 
> You need to adjust these to each individual dataset and there isn't really a standard that is applicable to all datasets. For variable genes selecting too many or two few to use in the downstream clustering will effect the results depending on how many genes in your dataset are actually highly variable. i.e. raising your variable genes to 5000 if only say 2000 of the genes in your dataset are highly variable won't likely add significant value.
> 
> PC selection is also key in similar fashion. You need to examine PCs (see ElbowPlot and Jackstraw sections of vignettes for some additional info). You should also examine PC heatmaps and the genes in each PC as they relate to your dataset. Again for example if the variance in the dataset is primarily contained in PCs 1:20 then expanding the number of PCs included downstream will likely not have significant impact.
> 
> Resolution can dramatically effect your clustering. While the overall shape of your tSNE or UMAP will not change the number of clusterings will be altered. This is something you need to dynamically adjust and examine as it relates to your dataset. To high a resolution and you end up with ill defined clusters which lack unique markers. To low and you end up with clusters that are too large and you may miss meaningful info.
> 
> Finally, regarding V2 "outperforming" V3 again that is matter of interpretation. You may find that the clustering results (again accounting for all the parameters above) you think is "better" with V2 than V3 and that is ok. But I would suggest you deeply read the Butler et al., 2018 and Stuart et al., 2019 so that you understand the difference between the two methods in the results that will be output one way or the other.
> 
> Hope this is helpful.
> 
> Best,
> Sam

Hi Sam,
when you mentioned before, I have saw that we should select the PC that related to our dataset. Yes, and after I do this I want to use the PC-4 and PC-5 but have no idea how to change it in the dimplot. I have tried to read the dimplot function and found out that I can use dims=c(4,5), but got the error"Error in Embeddings(object = object[[reduction]])[cells, dims]: subscript out of bounds Calls: DimPlot Execution halted" do you have idea of that?
