### ISSUE TITLE
Identifying Common Cell Types Between Experimental Conditions w/ Multiple Replicates

### ISSUE THREAD

**Issue by stephenchea** [satijalab/seurat#2059]
I have two experimental conditions (wildtype & mutant) with 6 biological replicates per experimental condition. I am wondering what workflow would be best for correcting batch effects and identifying common cell types between the two experimental conditions. 

1. Should I integrate all the replicates from both experimental conditions together and then cluster? 
2. Should I integrate the replicates from each experimental condition separately and then integrate again across the two conditions? 
3. Should I integrate the replicates from each experimental condition separately, and then perform label transfer using the integrated wildtype as the reference?

**Comment by andrewwbutler** [comment]
Hi,

Options 1 and 2 would likely give very similar results, though you could explore both and see. Neither would be a "wrong" approach. The main downside with option 3 is that you could potentially lose some power to detect rare populations as you effectively only have half the data when clustering the wildtype in order to get the labels you would transfer.

**Comment by veravevo** [comment]
Thank you @andrewwbutler for the answer. I am in the exact same situation. I always thought that multiple integration steps are not recommended and would result in loss of power in the analysis. 
So with my datasets, integrating all samples toghether (2 conditions, 3 biological replicates each), resulted in very bad clustering. Merging the replicates and then intgrating the conditions resulted in clustering of the replicates. 
Only first integrating the replicates, and then integrate again across conditions worked for me. 
Thank you!

**Comment by xx789** [comment]
Hi, @veravevo . I am doing exact same things as you described. I can integrate 3 biological replicates for each of the two conditions, and get two integrated Seurat objects, let's say int1 and int2. However, how do I start the integration pipeline again for using int1 and int2 as input? Because when I integrate 3 biological replicates for each of the two conditions, I started from the raw 10x matrics of each replicate. I am confused about how to start from int1 and int2. Can you share your step-by-step codes? Thanks!
