### ISSUE TITLE
RunUMAP from Seurat 3.10 still requires Python even if using uwot

### ISSUE THREAD

**Issue by rspreafico** [satijalab/seurat#2082]
Even if `uwot` is installed and should be used in place of the Python package `umap-learn`, Seurat 3.1 `runUMAP` seems to still require Python. If Python is correctly configured, then `runUMAP` goes thru using `uwot`. If Python/`reticulate`/`renv` are not configured, then `runUMAP` throws an error. So there is a hanging dependency somewhere. Quickly looking at code of `runUMAP.default` method, I think there is a Python seed call before checking whether `umap-learn` or `uwot` is selected. Not sure whether this is the issue as I skimmed thru the code in literally 10 secs, just a pointer. Thanks

**Comment by mojaveazure** [comment]
Hi,

Can you test the `fix/python-umap` branch to see if that fixes the issue? We all use macOS/Linux, which has Python installed at the OS level, so we are unable to use a machine that has R installed, but not Python.

To install the `fix/python-umap` branch, run the following:
```R
if (!requireNamespace('remotes', quietly = TRUE) {
  install.packages('remotes')
}
remotes::install_github("satijalab/seurat", ref = 'fix/python-umap')
```

**Comment by rspreafico-vir** [comment]
I'll try to test it one of these days. Meanwhile, one way to test it on your end is to have a fully encapsulated R environment using [renv](https://github.com/rstudio/renv) - the R counterpart of Python's `virtualenv` and the successor of `packrat`. Using `renv` is the way I originally spot the issue, as Python was hidden from the encapsulated environment.

**Comment by gosuzombie** [comment]
The new branch fixes the error of attempting to default to python umap rather than uwot. Now I can't seem to pass arguments to uwot, namely n_threads and fast_sgd

**Comment by mojaveazure** [comment]
Hi Fupan,

We've [never allowed passing extra parameters](https://github.com/satijalab/seurat/blob/master/R/dimensional_reduction.R#L1216-L1233) to `uwot::umap`; I've pushed a change adding a `uwot.sgd` parameter, which will be passed to `fast_sgd`

As for `n_threads`, this is currently set using `future::nbrOfWorkers`; as such, to set the number of threads to use, you need to create a plan using `future::plan`

While this may not make sense technically (`uwot::umap` doesn't use future), all other parallelized functions in Seurat are configured using future. In order to maintain consistency with the rest of Seurat, we're going to keep setting `n_threads` based on `future::nbrOfWorkers`
