### ISSUE TITLE
From anndata objects h5ad to seurat preprocessed flag.

### ISSUE THREAD

**Issue by Xparx** [satijalab/seurat#2091]
Hi,

I'm trying to pass around my data to my lab who some use R and seurat.
I previously commented here: https://github.com/satijalab/seurat/issues/1427.
One thing that seems to be an issue is that my data stay sparse after preprocessing.
(Log + 1) transforming and median/mean normalizing cells do not change zero values.

1. Would it be possible to add a flag when loading a h5ad file to explicitly say it has been preprocessed and contain additional data?

2. Additionally would it be possible to add a flag for loading specific layers from the anndata object as the main X data?

Best regards

**Comment by mojaveazure** [comment]
Hi Andreas,

Sorry for the delay in the response.

1. It would be possible, but would add to the complexity of `ReadH5AD`, which is already difficult enough to maintain. If you're data has been processed, I would recommend filling the `adata.raw` slot with the raw data to force the matrix in `adata.X` to be put in `data` instead of `counts`. We are working on a fix to detangle dimensional reduction information and nearest neighbor graphs requiring scaled data to be present.

2. There is a `layers` parameter in [`ReadH5AD`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/ReadH5AD) in the latest version of Seurat

**Comment by Xparx** [comment]
Ok. I'll look in to the layers parameter. Sounds like it's what I'm looking for.

Thanks for your answer!
