### ISSUE TITLE
Analyzing SC data based only on genes of interest

### ISSUE THREAD

**Issue by cpalmtree** [satijalab/seurat#2092]
I have a very large data set of single cells but for a certain analysis I am only interested in analyzing a set of 18 genes (a very tiny number). So I want to cluster my data set only taking these genes into account. 

From reading through the vignette there seem to be several ways forward, I'm just not sure which is most appropriate. It seems like I can run PCA selecting my genes as "features" which I have tried but I'm met with a warning: "You're computing too large a percentage of total singular values, use a standard svd instead.did not converge--results might be invalid!; try increasing work or maxit."

Alternatively, it looks like I can run PCA normally based on highly variable genes and then run "FindNeighbors" on my particular genes or "runUMAP" only on my particular genes.

Is any method more legitimate?

**Comment by andrewwbutler** [comment]
If you are going to use PCA for dimensional reduction and your feature set is 18 genes, you will need to set the `npcs` parameter to something less than 18. You could also run a full PCA instead of the approximate solution (set with the `approx` parameter), which should get rid of the warning you mention. 

For your alternative method, yes you can run `FindNeighbors` on a gene list but it will do the neighbor finding in gene expression space, not PCA space (so the "normal" PCA you refer to won't be used for anything downstream). This is probably what you want to do here as 18 features is already a fairly small feature set and I'm not sure you'll get too much out of reducing that further with PCA, though you can always try both and compare.
