### ISSUE TITLE
Error in Tutorials

### ISSUE THREAD

**Issue by emerygoossens** [satijalab/seurat#21]
Hello, 

I am just working through the tutorial titled: Seurat_ClusteringTutorial_Part1.html

A few lines into it, I received this message that I can't seem to resolve:

> nbt=MeanVarPlot(nbt,y.cutoff = 2,x.low.cutoff = 2,fxn.x = expMean,fxn.y = logVarDivMean)
[1] "Calculating gene dispersion"
  |===============================================================================| 100%
Error in text.default(data.x[pass.cutoff], data.norm.y[pass.cutoff], pass.cutoff,  : 
  zero-length 'labels' specified

**Comment by satijalab** [comment]
Hi,

This is due to the your cutoffs being set such that no genes pass the filters. Try setting y.cutoff and x.low.cutoff to lower values.

Also the tutorial you are working through has been replaced. We have released a newer version of Seurat and an updated tutorial. You can find it [here](http://satijalab.org/seurat/pbmc-tutorial.html)

- Andrew
