### ISSUE TITLE
nCount and nFeature calculation before and after SCTransform

### ISSUE THREAD

**Issue by allie-burns** [satijalab/seurat#2101]
Hello,

I want to clarify how nCount and nFeature are calculated both before and after normalization.  It seems that before any normalization is done (nCount_RNA and nFeature_RNA), nCount is the number of UMI counts taken across all cells from the RNA@data matrix and nFeatures counts any gene with at least 1 UMI count.  Is that correct or is it based on a different cutoff?

I'm a bit more unsure about how these are calculated after using SCTransform to normalize (nCount_SCT and nFeature_SCT).  Is it the same cutoff or is there a different method of calculation?  I'm trying to figure out why in some cases I get fewer nFeatures after the normalization and in other cases I get more nFeatures and knowing the cutoff (or the method used for calculation) would help me figure out where the changes are coming from.

Thank you!

**Comment by satijalab** [comment]
That is correct. The nCount_SCT and nFeature_SCT are calculated after normalization -  I would not pay much attention to these values (we calculate them by default, but they do not have physical meaning, as they reflect the number of features detected after normalizing for differences in the number of features detected).

**Comment by jmp448** [comment]
Would it be reasonable to do a FeatureScatter between nCount_SCT and nFeature_SCT to ensure that there is no (or minimal) correlation between the two? Because part of the purpose of the SCTransform is to eliminate this correlation, correct?

**Comment by MardahlM** [comment]
Hi,

My comment relates to this question, so I hope it is OK I write a question here. 
I am re-analysing a publicly available single-cell RNA-seq dataset with two samples (plus minus treatment) and have downloaded preprocessed data from the geodataset as two .csv files. The authors state these files contain matrices that have been QC and logNormalized - and scaled.

After creating a Seurat object for both datasets, I checked the nFeatures_RNA and nCount_RNA for either dataset and got around twice as many nFeatures as nCounts_RNA. I can't explain this. To me UMIs are the nCount_RNA and I can't find anything on the internet proving otherwise. If nCount_RNA is UMIs, and there are only half the UMIs as genes detected, how can that many genes been detected? I believe that you can't have two RNA molecules from different genes detected by the same UMI. In other questions online, I have seen the definition of cell complexity log10(nFeature_RNA/nCount_RNA) is >0.8. Maybe it is my mathematical understanding that is failing me. Have I a case of more features popping up after normalization? 

I attach a plot of the nCount_RNA against nFeatures_RNA (for the public matrix provided as a preprocessed matrix) and hope someone with a kind heart can explain how nFeature_RNA can be 2x that of nCount_RNA for a given cell. If it helps these cells should be endothelial cells from a tumor. 

![Screenshot 2021-10-16 at 22 02 34](https://user-images.githubusercontent.com/11302012/137688858-18587683-5ae4-4653-9e69-8c6e0c7ac210.png)
s.
