### ISSUE TITLE
How to determine appropriate significance cutoffs for gene expression values, and what expression data is used to visualize data in Seurat?

### ISSUE THREAD

**Issue by AlasdairCUPEI** [satijalab/seurat#2123]
Hi all,
I am still somewhat new to Seurat and single-cell data and I would just like some clarification on a couple of things.  

First of all, I would like to know what kind of expression data is being used to generate visualization tools in Seurat, such as FeaturePlots (FPs) and Violin Plots (VPs).  Throughout a typical analysis, after the QC regressions, the data is normalized and scaled, and PCA and clustering is run as normal.  I would just like to confirm if the normalized and scaled expression levels are carried forward to the FPs/VPs or if the expression values found in the raw data are used instead.  For example, when creating a "ViolinPlot", the y-axis simply states "Expression Level", which is somewhat ambiguous - is it the raw expression level, or the values that have been log-normalized (using Seurat's "LogNormalize") and then scaled?  Based on the scale created for the FPs and VPs, I'm assuming it's directly using the raw data (since scaled data should be primarily between -1 and 1), but are they exactly the raw data values or are there any modifications at all to them?

Finally, and more importantly, I was wondering what an appropriate cut-off would be to determine the significant expression level for a gene of interest.  I would like to make a subset of data that contains only the cells that express a particular gene above a certain significant threshold so that I can re-cluster and examine only those cells.  Let's say this gene is widely expressed across many clusters, and only a few cells in each cluster express that gene, so I can't simply pull out one of the existing clusters for analysis.  I know that I will have to extract those cells using the code that was provided by the developers of Seurat in their interaction tutorial:

# Can I create a Seurat object based on expression of a feature or value in object metadata?
subset(pbmc, subset = MS4A1 > 1)

I know that in this case, since it is pulling from the metadata, that it is using the raw expression values.  I'm just wondering about the threshold they are using; they used an expression level of 1.0 to identify all MS4A1+ cells in their dataset to make their new object.  I'm guessing this is not a standardized cutoff, and it seems somewhat arbitrary (even though I know that using that value, I would still extract almost all of the positive cells for most genes).  Assuming that I can't simply use the cutoff of 1.0 (as above), what would be the correct way to determine or calculate what value I should be using for my data?

Thank you very much!

**Comment by diazdc** [comment]
I'm not part of the development team, but I can try to help you out. 

You can see the default expression values used for each plot in the "slot" parameter by using the help function in R. For example, if you type `?FeaturePlot` in your console you can see that by default `slot = "data"`, which uses log-normalized values.

> Finally, and more importantly, I was wondering what an appropriate cut-off would be to determine the significant expression level for a gene of interest.

This question is very context dependent. If you mean _statistical significance_ (which is usually implied in an analytical context), that's only determined _after_ you've run a statistical test between two populations of cells. If you're simply looking for a reasonable cutoff value to subset your cells, you'll need see how that gene is distributed first and then decide for yourself what the appropriate value will be, because what's considered to be low expression for one gene may be high for another. You can accomplish this by using R's built in summary function (or make a density plot for more resolution). Here's an example for a couple of genes:
 
    summary(FetchData(object = seurat_obj, vars = "atoh1a"))
    
    atoh1a       
    Min.   :0.0000
    1st Qu.:0.0000
    Median :0.0000
    Mean   :0.3182
    3rd Qu.:0.0000
    Max.   :4.2873 

    summary(FetchData(object = seurat_obj, vars = "cldnb"))
    
    cldnb
    Min.   :0.000  
    1st Qu.:2.340  
    Median :3.035  
    Mean   :2.806  
    3rd Qu.:3.671  
    Max.   :6.155

note: expression values are pull from the "data" slot

**Comment by AlasdairCUPEI** [comment]
Thank you very much for your reply, it was super helpful!  In terms of the significant expression level question, I had meant the reasonable cutoff to subset the cells, and your examples and explanation were great.

**Comment by LaydenLab** [comment]
A RidgePlot can show you the distribution of a variable across your data, which can give you an idea of what cutoff to use for the threshold for each particular gene.

RidgePlot(object = seurat_obj, features = 'MS4A1')
