### ISSUE TITLE
Plot NA first in DimPlot

### ISSUE THREAD

**Issue by GBeattie** [satijalab/seurat#2129]
Hey!

So I've added to the metadata in my object (metadata name = expanded) and created a DimPlot grouping by "expanded", the issue being that the NA values obscure the data. I can remove the NAs, but would like them to be visible to show unlabelled regions, I've tried manually ordering the plot data like: 

`order(expanded_plot$data$expanded, na.last = F)` 

But that seems to be converting NA into a number.

Below is the code for the DimPlot, and a screenshot of it as it stands, thanks in advance for any assistance!

`expanded_plot <- DimPlot(wt.combined, group.by = "expanded", split.by = "orig.ident", pt.size = 1, na.value = element_blank(), do.return = TRUE)`

![image](https://user-images.githubusercontent.com/11555832/65414178-12902380-ddeb-11e9-8d55-7ded9749c5f1.png)

**Comment by yuhanH** [comment]
In your case, you could set the color for NA dots.
You set the `na.value` to change NA value color. But it only works when you use the custom scale.
If you want to extract the default color, you can use the script below:
```
unique(ggplot_build(  expanded_plot  )$data[[1]][,1])
```
The first should be "grey50" . The rest colors are the colors in your current DimPlot

**Comment by CSBioAzim** [comment]
From where these NAs come?

**Comment by zoequandt** [comment]
I have a similar question- I can recolor the NAs this way but I would like them to be behind the other variables instead of in front. Here is my example code and resulting plot:

DimPlot(simple.query, group.by = "Shared_or_Expanded", order = c("Not Expanded nor Shared", "Expanded and Shared", "Shared", "Expanded"), sizes.highlight = 6, cols=TCR, pt.size=1, reduction = "ref.umap", na.value="grey") + ggtitle('Expanded and Shared by Barcode') + NoAxes()

![image](https://github.com/satijalab/seurat/assets/58529939/153ea3b8-cc91-4122-b6ba-1ec3ca0b699a)

**Comment by MajorasMeow** [comment]
It has been some years but if anyone stumbles on this:

The default DimPlot plots cells based on factor levels, meaning the last level is plotted on Top. 
The resolution is to set the metadata column as factors in the order that NA is not plotted on Top.
