### ISSUE TITLE
Scale of data after CLR transformation

### ISSUE THREAD

**Issue by jyang635** [satijalab/seurat#2159]
Dear authors,

In this [documentation](https://satijalab.org/seurat/v3.0/multimodal_vignette.html), I noticed that after doing CLR transformation on ADT data.  The range of the data starts from 0 in the RidgePlot. However, the CLR transformed data should contain negtive values in my understanding. I am wondering if there is any extra scaling operation after CLR transformation. If so, could you please explain how you calculate the **expression level** of ADT data?

Thanks!

**Comment by andrewwbutler** [comment]
Hi,

The relevant code for performing the CLR transformation can be found here:

https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/preprocessing.R#L1768-L1769

This function uses `log1p` which is why you aren't seeing any negative values (essentially adding a pseudocount for each component).
