### ISSUE TITLE
Cell cycle scoring and regression  in "Reciprocal PCA (Integration and Label Transfer tutorials)"

### ISSUE THREAD

**Issue by JayalalKJ** [satijalab/seurat#2177]
The scripts below are from Seurat _ Integration and Label Transfer tutorials  [https://satijalab.org/seurat/v3.1/integration.html].

In this where can I add the **cell cycle regression analysis scripts** ?
 

bm280k.data <- Read10X_h5("../data/ica_bone_marrow_h5.h5")
bm280k <- CreateSeuratObject(counts = bm280k.data, min.cells = 100, min.features = 500)
bm280k.list <- SplitObject(bm280k, split.by = "orig.ident")
bm280k.list <- future_lapply(X = bm280k.list, FUN = function(x) {
    x <- NormalizeData(x, verbose = FALSE)
    x <- FindVariableFeatures(x, verbose = FALSE)
})
features <- SelectIntegrationFeatures(object.list = bm280k.list)
bm280k.list <- future_lapply(X = bm280k.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})
anchors <- FindIntegrationAnchors(object.list = bm280k.list, reference = c(1, 2), reduction = "rpca", 
    dims = 1:50)
bm280k.integrated <- IntegrateData(anchorset = anchors, dims = 1:50)
bm280k.integrated <- ScaleData(bm280k.integrated, verbose = FALSE)
bm280k.integrated <- RunPCA(bm280k.integrated, verbose = FALSE)
bm280k.integrated <- RunUMAP(bm280k.integrated, dims = 1:50)
DimPlot(bm280k.integrated, group.by = "orig.ident")

**Comment by timoast** [comment]
You would do cell cycle regression in the `ScaleData` step on each object, before integration

**Comment by JayalalKJ** [comment]
> You would do cell cycle regression in the `ScaleData` step on each object, before integration
Hi Timoast 
Thanks for the tip. But When do cell cycle regression before integration, I am getting following error ! 
Error in UseMethod(generic = "DefaultAssay", object = object) : 
  no applicable method for 'DefaultAssay' applied to an object of class "list
?

**Comment by JayalalKJ** [comment]
> You would do cell cycle regression in the `ScaleData` step on each object, before integration

But, I have to merge my 19 different objects. Does it works after the merging ?

**Comment by rcrueda** [comment]
In line with this thread, I am trying to perform integration with RPCA at the same time as cell cycle regression but I am not sure in which scaling steps cell cycle regression should happen. 

My code is as follows:

### Split the dataset into a list of seurat objects based on sample origin
seurat.list <- SplitObject(seurat, split.by = "orig.ident")

### normalize and identify variable features for each dataset independently
seurat.list <- lapply(X = seurat.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 3000)
  x <- CellCycleScoring(x, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
})

### select features that are repeatedly variable across datasets for integration and run PCA on each dataset using these features
features <- SelectIntegrationFeatures(object.list = seurat.list, nfeatures = 2000)
seurat.list <- lapply(X = seurat.list, FUN = function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE, **vars.to.regress = c("S.Score", "G2M.Score")**)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

###integration
immune.anchors <- FindIntegrationAnchors(object.list = seurat.list, anchor.features = features, reduction = "rpca")
immune.combined <- IntegrateData(anchorset = immune.anchors) 

DefaultAssay(immune.combined) <- "integrated"

# Run the standard workflow for visualization and clustering
immune.combined <- ScaleData(immune.combined, verbose = FALSE , **vars.to.regress = c("S.Score", "G2M.Score")**)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)

immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:20) 
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:20)  
immune.combined <- FindClusters(immune.combined, resolution = 0.5)

DefaultAssay(immune.combined) <- "RNA"

seurat <- immune.combined 
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat, features = rownames(seurat))

I have 3 different scaling steps. Is it correct to use CC gene regression before integration and before cell clustering and not in the RNA compartment? 

Would it otherwise be fine to do cc regression only after integration and before cell clustering? 

Thanks!
