### ISSUE TITLE
Color key for Average expression in Dot Plot

### ISSUE THREAD

**Issue by MridusmitaSaikia** [satijalab/seurat#2181]
Hello,

I am using the DotPlot to analyze the expression of target genes in my two Drop-seq datasets (control versus treatment). It bothers me that the DotPlot does not have the color key for the Average Expression, like the feature plots. I was wondering if there was a way to add that.

Thanks in advance!
~ Mridu

**Comment by samuel-marsh** [comment]
Hi Mridu,

Not a member of the Dev team but hopefully can help.  Are you using Seurat V2?  In V2 you need to add the argument `plot.legend = TRUE` in your DotPlot call in order for the legend and scale bar to be plotted in the output.  In V3 they are plotted by default.

Best,
Sam

**Comment by MridusmitaSaikia** [comment]
Hi Sam,

Thanks for the note. I am actually using the Seurat V3. I use the split.by argument to plot my control vs treated data. The scale bar for average expression does not show up in my plot. Can I try your suggestion (adding the argument plot.legend = TRUE) in the V3?

**Comment by samuel-marsh** [comment]
Hi Mridu,

Unfortunately, this looks like it goes beyond my ability to help and will need input from @satijalab folks.  The `plot.legend = TRUE` is not an argument in the V3 DotPlot call so that will not work.  Looking at the code for DotPlot() it appears that this removal of the legend is part of the code when using `split.by` (See below).  Sorry I can't be more help, was hoping it was simple V2 issue.

Best,
Sam

See:
https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/visualization.R#L1995-L2003

**Comment by AndyR2** [comment]
see #1541

**Comment by satijalab** [comment]
answered in #2487

**Comment by lumos21** [comment]
Yes, I do find with Seurat3 it's disabled to use color key if using split.by,  because there will be two or more colors. So the only way to have the color key is to comment out split.y, and the color key can be added like this.

DotPlot(immune.combined, features = rev(markers.to.plot), cols = c("blue"), dot.scale = 8 
     #, split.by = "stim"
     ) + RotatedAxis()  +
  scale_colour_gradient(low = "white", high = "blue") +
  guides(color = guide_colorbar(title = 'Average Expression'))

![plot_dotplot_test](https://user-images.githubusercontent.com/24864595/85795627-75ea1180-b6ed-11ea-8d8c-957b51ea6cbe.png)

If I don't comment out split.by, it will give errors. 

> answered in #2487
