### ISSUE TITLE
Can't read Alevin quantification using ReadAlevin

### ISSUE THREAD

**Issue by apcamargo** [satijalab/seurat#2197]
I quantified my samples using Alevin version 0.14.1 using the following command:

`salmon alevin -p 48 --tgMap transcript_to_gene.tsv -i ../Transcriptome/index -l ISR --chromium -1 Reads/SAMPLE_1.fastq.gz -2 Reads/SAMPLE_2.fastq.gz -o Quantification/SAMPLE`

When I try to open the quantification matrix in Seurat using the `ReadAlevin` function, I get the following error:

```
Error in out.matrix[, n] <- readBin(con = con, what = double(), endian = "little", : number of items to replace is not a multiple of replacement length
Traceback:

1. ReadAlevin("Quantification/SAMPLE")
```

**Comment by k3yavi** [comment]
Hi @apcamargo ,

Thanks for raising the issue. With `0.14.1` alevin developers (I am also part of the group) have significantly optimized the cell-v-gene matrix output format, you can check the comparisons with other formats [here](https://github.com/COMBINE-lab/EDS/blob/master/README.md) and we are still working on making the PR to update the parser into Seurat repo. In the meantime, you can check the tutorial [here](https://combine-lab.github.io/alevin-tutorial/2018/alevin-seurat/) on how to use Seurat with your alevin generated quants. To keep track of this issue, I have raised https://github.com/COMBINE-lab/salmon/issues/436 in the salmon repo as well.

@ Seurat team, my apologies for answering the question without a review and please feel free to close the issue here if you feel it's an external dependency issue.

**Comment by satijalab** [comment]
Closing as this is being addressed in the salmon repo
