### ISSUE TITLE
Problem with using "roc" in FindMarkers

### ISSUE THREAD

**Issue by FloWuenne** [satijalab/seurat#220]
Hi everyone,

when using the FindMarkers function with the "roc" test to check for markers between two clusters, I get the following error thrown no matter what dataset I run this on:
```

markers <- FindMarkers(obj, ident.1=celltype1, ident.2=celltype2,
                           only.pos=TRUE,
                           test.use="roc")

Error in `$<-.data.frame`(`*tmp*`, p_val_adj, value = integer(0)) : 
  replacement has 0 rows, data has 1996
```

I am suspecting that this is some package dependency issue that R doesn't explicity state but I couldn't figure out how to solve this yet. 

Thanks for the help,
Best,

Florian

**Comment by leonfodoulian** [comment]
Hi Florian,

What version of Seurat are you using? I ran your code on my datasets and didn't get this error at all. I am not sure to what extent it's due to package dependencies. Rather, it seems to be related to the `p_val_adj` column. Indeed, there is no p value computed by a ROC test (`NAs` are returned in this case). Can you install the latest CRAN version or the development version of Seurat and try running the code again?

Best,
Leon

**Comment by FloWuenne** [comment]
Hi Leon,

Indeed it was a version error and roc worked fine on our cluster where I had installed the most up-to-date Seurat version from CRAN.

Sorry for that,
you can close the issue as resolved! 

Best,

Florian

**Comment by leonfodoulian** [comment]
Hello Florian,

I don't have authorisation to close your issue. Could you do that please?

Best,
Leon
