### ISSUE TITLE
Rank cells by similarity in DoHeatmap()

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#2222]
I choose some genes of interest to plot in `DoHeatmap(scData, features = Gene_for_Heatmap) + NoLegend()`. However, the heatmap was grouped by clusters. 
![Rplot](https://user-images.githubusercontent.com/49429496/67090311-60c2f780-f1dc-11e9-8412-1cbc29f0692f.png)

I want to make **cells ranked by their similariy**, like this figure provided by [seurat tutorial](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html). But that was plotted using the marker genes of the cluster. It would be much more better if I could have order list (ex. ranked cell name list). Could anyone help me?
![image](https://user-images.githubusercontent.com/49429496/67090359-7df7c600-f1dc-11e9-9980-58dc01245a11.png)

**Comment by timoast** [comment]
Hi, in the tutorial the cells are not actually ordered by similarity, but grouped by cluster and the genes ordered by the clusters that they are expressed in. I think the easiest thing would be for you to do the same and order your gene list by the cluster that the genes are expressed in, so that they match the order that the clusters are plotted in (ie, the cluster factor levels).

If you do want to order the cells instead, the `DoHeatmap` function has a `cells` argument that will allow you to do this.

**Comment by grimwoo** [comment]
@Timoast Thanks, could you please tell me how to do that in details? though I've read the description, it's difficult to write the code.

**Comment by timoast** [comment]
Hi @grimwoo, you could run `AverageExpression` to get the average expression level of each gene in each cluster, then sort the genes by their expression in the different clusters. Unfortunately due to the volume of questions asked here we don't have the bandwidth to provide specific code

**Comment by grimwoo** [comment]
@timoast I do know how to do the the heatmap provided by Seurat tutorial. But could you at least give me an example of what kind of code to write with `DoHeatmap(cell = ????)`? Hence I could try it myself.

**Comment by grimwoo** [comment]
maybe `cell = `  logic ? or character?  or list? or ident?

**Comment by timoast** [comment]
Hi @grimwoo, the `cells` parameter expects a vector of cell names. You can read the documentation for `DoHeatmap` for more information
