### ISSUE TITLE
FindAllMarkers fails on scale.data slot from "integrated" assay

### ISSUE THREAD

**Issue by rmenafra** [satijalab/seurat#2272]
Hi Seurat team,
I have performed integration using the SCTtransform workflow (as in your vignette).
When I try to identify cluster markers using the "integrated" assay and the "scale.data" slot FindAllMarkers fails with:
Warning: No DE genes identified
Warning: The following tests were not performed: 
Warning: When testing PA_4 versus all:
	no 'dimnames[[.]]': cannot use character indexing
Warning: When testing PZ_4 versus all:
	no 'dimnames[[.]]': cannot use character indexing
Warning: When testing CZ_4 versus all:
	no 'dimnames[[.]]': cannot use character indexing
Warning: When testing CA_4 versus all:
	no 'dimnames[[.]]': cannot use character indexing 

If I would select the  "data" slot from the integrated assay or the "scale.data" slot from the SCT assay  I have no problem running the FindAllMarkers (or FindMarkers), but I thought after integration it was better to use the "scale.data" slot from the "integration" assay. 
I know this question has probably been asked already multiple times in different ways but the result of differential gene expression changes in each of the above mentioned combinations.
I'm looking forward to your reply.
Best,
Roberta

**Comment by timoast** [comment]
We don't recommend DE on the integrated data and I suspect this is the cause of the problem. There are several closed issues about this, I recommend using either the "SCT" or "RNA" assay

**Comment by raveancic** [comment]
Dear @satijalab and @timoast is there a reason why you do not recommend to use DE on the integrated data? The issue here is that if I have data from two different chemistries that have been integrated and I want to see which genes are differentially expressed in one cluster vs others (cluster made with integrated dataset) why should I go back to the SCT/RNA dataset?
I really do not see the point here. 
Thank you very much for this. 
Alessandro
