### ISSUE TITLE
Cannot subset Seurat object

### ISSUE THREAD

**Issue by tkapello** [satijalab/seurat#2292]
Hi,

   I want to subset a Seurat object to contain only the cells which carry more than 1500 genes. I run

`tissue_358hi<- SubsetData(tissue_358, cells = as.character(row.names(tissue_358@meta.data[tissue_358@meta.data$nFeature_RNA > 1500,])))`

and I get the following error:

```
Error in checkSlotAssignment(object, name, value) : 
  assignment of an object of class “numeric” is not valid for slot ‘counts’ in an object of class “Assay”; is(value, "AnyMatrix") is not TRUE

```
This is a bit strange because this code worked fine in other Seurat objects. Does anyone have any good suggestion about why this is happening?

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the Dev team but hopefully this is helpful.  Are you using Seurat V3?  In V3 and newer you can subset differently.  See Satija lab vignettes [https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html](https://satijalab.org/seurat/v3.1/pbmc3k_tutorial.html)
i.e.
`pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)`

So if you run `tissue_358hi <- subset(tissue_358hi, subset = nFeature_RNA > 200)`
Does that solve the issue?

Best,
Sam

**Comment by tkapello** [comment]
Hi Sam,

   thanks for the reply. I use Seurat V.3 indeed, but I used _SubsetData()_ because I noticed that _subset()_ did not remove all the cells I asked for. When I visualised in VlnPlots, there were still a few cells containing fewer genes which I found awkward. _SubsetData()_ did the trick, but gave me this issue.

**Comment by samuel-marsh** [comment]
Hi,

If you view the object@metadata after using the `subset` way and sort the nFeature_RNA column can you confirm the values are less than your desired subset?  I can't replicate the issue with my own datasets.

VlnPlot on it's own can be deceiving unless you modify the y axis because the intercept of the x and y axis is not 0 (see below).  Example using an object of mine with:
`subset(object, subset = nFeature_RNA > 1000)`

![VlnPlot_no_mod](https://user-images.githubusercontent.com/38284410/68316818-179def00-0088-11ea-8a49-d8296ba382ee.jpeg)
![VlnPlot_MOD](https://user-images.githubusercontent.com/38284410/68316839-21275700-0088-11ea-8287-74e6620dc9a2.jpeg)


If still an issue then might be out of my expertise.  Sorry.
Best,
Sam

**Comment by tkapello** [comment]
You are right about the axes. I checked and this was not the issue. Thanks though for the contribution

**Comment by samuel-marsh** [comment]
No problem.  Hope someone else or member of Dev team can help with your issue.  Strange that subset() isn't filtering correctly.

Best,
Sam

**Comment by timoast** [comment]
@tkapello can you provide a reproducible example where `subset` doesn't remove cells that it should, using the `pbmc_small` dataset or one of the datasets in [SeuratData](https://github.com/satijalab/seurat-data)? Could you also provide the output of `sessionInfo()`?

**Comment by tkapello** [comment]
I tried with pbmc_small, but the issue is not reproducible. What I noticed with my dataset is that the cells are removed with _SubsetData()_, but somehow a few with low gene counts re-appear after normalisation and selection of variable features. Not sure if anyone else has seen such a thing.

**Comment by tkapello** [comment]
I finally solved the issue. It was caused by _subset()_. For some reason, I had to run the command twice to properly remove the unwanted cells. Maybe the Dev team would want to check this if somebody else also finds the same error.
