### ISSUE TITLE
Differentially expressed genes in each cluster by group

### ISSUE THREAD

**Issue by ghoshal** [satijalab/seurat#231]
Hi,

I have an aligned dataset between normal and treated samples. I want to find differentially expressed gene between normal and treated in one group of cells (cluster). Is there a way to do it?
Can a grouping variable be used for FindAllMarkers?

Thanks,

Bibaswan

**Comment by leonfodoulian** [comment]
Hello again,

What is the column corresponding to the identity of these cells in the `object@meta.data` slot? You can set the identity of your cells using that column, and then compute differential expression analysis based on the status of the cells, independent of the clusters. Otherwise, if your cells are mixed within a cluster, you can create a column corresponding to the interaction of the cluster ID of the cells and the health status, set the identity of your cells to the resulting column and compute `FindAllMarkers()`.

```
# Create a column corresponding to the interaction of the cluster ID and the health status of cells
object@meta.data$id.hs <- interaction(object@meta.data$res.0.8, object@meta.data$orig.ident, sep = ".")

# Switch the identity of your cells to 'id.hs'
object <- SetAllIdent(object = object, id = "id.hs")

# Compute differential expression analysis
markers <- FindAllMarkers(object = object)
```

Best,
Leon

**Comment by ghoshal** [comment]
Thanks Leon. So just to clarify, the object@meta.data has two classes separated by orig.ident and protocol. If I run FindALLMarkers on this object then it would give me a list of differentially expressed genes by the orig.ident so that the +logFC will determine higher expression in one group vs another and vice versa.

**Comment by leonfodoulian** [comment]
Exactly. Unless you create a third column in your `object@meta.data` where you combine cell ID (computed by `FindClusters`) and treatment status, and set the identity of your cells to that column (as I demonstrated above). In this case, it would probably make more sense to compute `FindMarkers()` (instead of `FindAllMarkers()`) for each cell type, between treated and non treated cells.

**Comment by ghoshal** [comment]
Perfect. Thanks a lot.
