### ISSUE TITLE
Loading Seurat error in monocle 2

### ISSUE THREAD

**Issue by LIUMENG004** [satijalab/seurat#2329]
I am trying to import Seurat3 data into monocle2. Here is the code：

**#Load Seurat object
seurat_object <- readRDS('tenx_seurat_rawdata.rds')

#Extract data, phenotype data, and feature data from the SeuratObject
data <- as(as.matrix(seurat_object@assays$RNA@raw.data), 'sparseMatrix')

pd <- new('AnnotatedDataFrame', data = seurat_object@meta.data)

fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)**

But it told me: **Error in as.matrix(seurat_object@assays$RNA@raw.data) :
  trying to get slot "raw.data" from an object of a basic class ("NULL") with no slots**
How to sovle the problem

**Comment by saeedfc** [comment]
This is more of a question to Monocle developers I guess.
From what I understand, 
Monocle 2 cannot take Seurat 3 objects.
You will have to create a seurat v2 object to use the import function in Monocle2. 
Otherwise, you can manually construct the CDS (CellDataSet) object in Monocle2 by extracting the counts matrix and meta_data from seurat_object. But it has always been tricky because of some inconsistencies of the CDS object being manually filled.

```
matrix <- GetAssayData(seurat_object, assay= "RNA", slot = "counts")
meta.data <- seurat_object@meta.data
```

Easiest way will be to use Seurat v2 to construct v2 object and then use it for monocle 2.
You can find more answers in the github issues of the past in both monocle2 and seurat github pages

**Comment by timoast** [comment]
@saeedfc is right, it looks like you are trying to access slots in the v2 object structure. The `raw.data` slot is now replaced by `counts` in v3. If you use `GetAssayData` instead you should be able to construct a CDS object

**Comment by LIUMENG004** [comment]
> This is more of a question to Monocle developers I guess.
> From what I understand,
> Monocle 2 cannot take Seurat 3 objects.
> You will have to create a seurat v2 object to use the import function in Monocle2.
> Otherwise, you can manually construct the CDS (CellDataSet) object in Monocle2 by extracting the counts matrix and meta_data from seurat_object. But it has always been tricky because of some inconsistencies of the CDS object being manually filled.
> 
> ```
> matrix <- GetAssayData(seurat_object, assay= "RNA", slot = "counts")
> meta.data <- seurat_object@meta.data
> ```
> 
> Easiest way will be to use Seurat v2 to construct v2 object and then use it for monocle 2.
> You can find more answers in the github issues of the past in both monocle2 and seurat github pages

Thanks for your reply. After i get the matrix and meta.data with your code:
**> matrix <- GetAssayData(seurat_object, assay= "RNA", slot = "counts")
> meta.data <- seurat_object@meta.data**
 
How to create a CDS with the above object? My data set is around 100k cells.
