### ISSUE TITLE
Differential expression across condition for all clusters

### ISSUE THREAD

**Issue by Brie33** [satijalab/seurat#2367]
Hello,
I'm currently working with a 10x dataset that contains 2 conditions and several clusters. I would like to run a differential gene expression analysis (using MAST) for condition A vs condition B for every cluster in my object.
Using FindMarker I can easily obtain the differentially expressed genes A vs B for one cluster, but I don't see any implemented way to run it for all clusters. I was looking for a way to run FindMarker using "condition" as active.ident and the cluster identity as second subgrouping (for example like "add.ident" in AverageExpression). 

I tried 
`FindMarkers(object, ident.1 = "A", ident.2 = "B", test.use = "MAST", group.by = "cell.types")`
but I probably don't fully understand how "group.by" is supposed to be used. Having set the idents to condition, group by does not allow me to pull from the metadata the second layer of identities.

If this possibility is not implemented already, is it possible to iterate the function across all clusters?
Thanks in advance

**Comment by tulikakakati** [comment]
check out 
See this vignette for more information: https://satijalab.org/seurat/v3.1/immune_alignment.html

**Comment by Brie33** [comment]
> 
> 
> check out
> See this vignette for more information: https://satijalab.org/seurat/v3.1/immune_alignment.html

Thank you for your reply. I indeed based my question on that vignette. As you can see, since they create new idents containing condition_cluster, they can later on run the differential expression analysis only one cluster at the time, but not all clusters together as I was suggesting.

**Comment by knoedlerj** [comment]
I had the same issue and solved it with a FOR loop. Not the most elegant but easier than copying and pasting for every cluster. 

output <- "/path/to/filename"
mySeurat$celltype.condition <- paste(Idents(mySeurat), mySeurat$condition, sep="_")
mySeurat$celltype <- Idents(mySeurat)
Idents(mySeurat) <- "celltype.condition"
for (i in 0:38){ #or however many clusters you have
try({
ident1 <- paste0(i,"_condition1")
ident2 <- paste0(i,"_condition2")
condition.diffgenes <- FindMarkers(mySeurat, ident.1 = ident1, ident.2=ident2, min.pct=0.25, logfc.threshold=0.25)
write.csv(condition.diffgenes, file=paste0(output,i,"_.csv"))
})
}

**Comment by Brie33** [comment]
> 
> 
> I had the same issue and solved it with a FOR loop. Not the most elegant but easier than copying and pasting for every cluster.
> 
> output <- "/path/to/filename"
> mySeurat$celltype.condition <- paste(Idents(mySeurat), mySeurat$condition, sep="_")
> mySeurat$celltype <- Idents(mySeurat)
> Idents(mySeurat) <- "celltype.condition"
> for (i in 0:38){ #or however many clusters you have
> try({
> ident1 <- paste0(i,"_condition1")
> ident2 <- paste0(i,"_condition2") condition.diffgenes <- FindMarkers(mySeurat, ident.1 = ident1, ident.2=ident2, min.pct=0.25, logfc.threshold=0.25) write.csv(condition.diffgenes, file=paste0(output,i,"_.csv"))
> })
> }

Thank you very much for the help. I was afraid there was no other way than relying on a for loop. I will try your suggestion. My only concern is that using a for loop the statistics does not take into consideration that I am reiterating the analysis across many clusters, and I am not sure if it should.

**Comment by timoast** [comment]
The best way to do this is using a loop as @knoedlerj suggested. We currently don't have a build-in way to do that in Seurat

**Comment by pabloatria18** [comment]
@knoedlerj can you please help me?
I am kind of new to this.

I have two conditions, and 12 clusters per condition.
My code should be:
for (i in 0:24){ #or however many clusters you have **(24, since I have 12 in each condition)**
try({
ident1 <- paste0(i,"_condition1") **This part I am not sure how to fill **
ident2 <- paste0(i,"condition2")

Thank you

**Comment by jrknoedler** [comment]
Hey! To answer your question:

The first part of the code is lifted from the Satija lab vignette. So let's say your grouping variable is 'drug' and your conditions are 'control' and 'treated' . Replace 'condtion'  in the first part to rename your cell identities. Then replace 'condition1' with 'control' and 'condition2' with 'treated' in the loop. 
In this part:

for (i in 0:24){ #or however many clusters you have (24, since I have 12 in each condition)

You should actually have (i in 0:11) if your clusters are still named with Seurat defaults. You have 12 clusters and you're looping through each to compare the two libraries. 

Hope that helps!

Best,
Joe

**Comment by pabloatria18** [comment]
Thank you @jrknoedler 
IT did help!
I still have a problem though
My code looks like this:

output <- "DEGAll.csv"
bmsc.integrated$celltype.condition <- paste(Idents(bmsc.integrated), bmsc.integrated$group, sep="_")
bmsc.integrated$celltype <- Idents(bmsc.integrated)
Idents(bmsc.integrated) <- "celltype.condition"
for (i in 0:11){ # or however many clusters you have
  try({
    ident1 <- paste0(i,"_Control")
    ident2 <- paste0(i,"_Loaded")
    
    condition.diffgenes <- FindMarkers(bmsc.integrated, ident.1 = ident1, ident.2= ident2, min.pct=0.25, logfc.threshold=0.25)
    write.csv(condition.diffgenes, file=paste0(output,i,".csv"))
  })
}

But I get 11 csv files and are all different between each other.
Any recommendations?

I appreciate your help

**Comment by jrknoedler** [comment]
Ah - each csv should be the differentially expressed genes for each cluster (which is what I assumed you were looking for).

**Comment by pabloatria18** [comment]
> Ah - each csv should be the differentially expressed genes for each cluster (which is what I assumed you were looking for).

Oh no
I want to compare the whole dataset across conditions, not individually by clusters.
And also I would like to group for example 3 clusters that seem to be related and compare them across both conditions.
Any ideas on how to do that? 

Thank you very much for your time and help

**Comment by jrknoedler** [comment]
The best way to do that would be to use "SetIdent" to rename every cluster in the integrated dataset so they have the same name; then you can use the code to rename them by condition and run "Findmarkers". Same goes for comparing the three related clusters - rename them "Excitatory" or whatever (I'm a neuro guy) and then run the code as before. 

However, I would think about your experimental design when interpreting your results. How many replicate libraries do you have per condition? If you only have one, bear in mind that while this analysis will almost certainly give you results with a low adjusted p value, strictly speaking this is pseudoreplication - you may have thousands of  cells, but since they originate from the same library preparation they aren't independent observations. You could use these results to, say, confirm known or suspected gene perturbations, or see if there are genes that show very large fold changes and follow up on them with an independent validation, but I think carefully about what how you interpret it. If you do have multiple replicates per condition you're probably better off collapsing the counts and doing pseudobulk analysis.

**Comment by me37uday** [comment]
Thanks for your answer @jrknoedler !

However, I am getting the following error : 

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rowSums': invalid or not-yet-implemented 'Matrix' subsetting
```

Does anything else need to be updated in the code from the time it was posted? Any help would be much appreciated!

Thanks,
Uday

**Comment by jrknoedler** [comment]
Hi Uday,

Hey! I ran into something like this myself recently - I think some R update changed a few things. I remember solving it by manually loading "Matrix". However, it looks like the problem might be that whatever version of Seurat you're running isn't calling DESeq2 correctly so I'm not sure how to resolve it (when I run DESeq2 on single-cell data I extract the count table from the Seurat object and set up the dds object myself).
