### ISSUE TITLE
For object@ident in Seurat v2.3.4, what's the corresponding slot in Seurat V3.1.0?

### ISSUE THREAD

**Issue by singletrips** [satijalab/seurat#2395]
For object@ident in Seurat v2.3.4, what's the corresponding slot in Seurat V3.1.0? Should it be object@active.ident?

**Comment by mojaveazure** [comment]
Please see the [`Idents`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.1/topics/Idents) function for accessing cell identity classes.

For Seurat v3, we've built accessors/setters for various slots, including the cell identities. As such, we discourage accessing slots directly and instead encourage the use of these accessors/setters. Using the accessors/setters we provide will make your code more stable; we don't intend to replace or alter these functions so that they can persist throughout future versions of Seurat. The object structure, however, may change as data types change.

To learn more about interacting with `Seurat` objects and to get a v2/v3 data access translaion, please see our [command cheatsheet](https://satijalab.org/seurat/essential_commands.html).
