### ISSUE TITLE
Quantitative Analysis - Differences between two conditions

### ISSUE THREAD

**Issue by rmicheroli** [satijalab/seurat#2406]
Hello everybody

I have scRNAseq Data with three different conditions. Using the SEURAT standard workflow i have now 10 clusters. Now, i would like to know, if one cluster is "more" present in one condition compared to the others. The goal is to say, that a specific cell type is typical for a certain condition (as it is more prevalent).

Is there a way to perform such an analysis?

Thanks!

**Comment by timoast** [comment]
You can assess the composition of different clusters by using the `table` function in R. For example:

```r
table(obj$batch, obj$cluster)
```

The proportion of cells from different conditions present in each cluster may be due to a variety of technical as well as biological reasons, so use caution when interpreting these proportional differences.

**Comment by s849** [comment]
Is there a way to calculate the statistical significance of these cell proportions across two conditions per cluster??
