### ISSUE TITLE
How to change the order of genes in DimHeatmap() plot in Seurat V3?

### ISSUE THREAD

**Issue by singletrips** [satijalab/seurat#2424]
The first figure is my plot using DimHeatmap() in Seurat V3:
![5992426BFA9148B506C5AD007F0DA11C](https://user-images.githubusercontent.com/31929730/70815787-26b94080-1d9c-11ea-86a1-82225da37e4c.png)
The second figure is my plot using PCHeatmap() in Seurat V2:
![27A053D0223331331D96FDE7B0AE52E6](https://user-images.githubusercontent.com/31929730/70815807-320c6c00-1d9c-11ea-8579-d2b202995d80.png)

However, the genes are in reversed order, how to reorder the genes on the plot?

**Comment by MajoroMask** [comment]
Since `DimHeatmap(fast = FALSE)` returns a `ggplot` object, you can extract the axis y information from it then change the order by adding a `scale_y_discrete()` layer to it. 

For example:
```
p1 <- DimHeatmap(pbmc_small, nfeatures = 20, fast = FALSE)
```

![image](https://user-images.githubusercontent.com/19700954/70901792-6bf89f00-2036-11ea-9489-42b27a0118d3.png)

```
p1_b <- ggplot_build(p1)
p1_b$layout$panel_scales_y[[1]]$range$range
#>  [1] "SDPR"          "PF4"           "PPBP"          "TUBB1"         "CA2"           "TREML1"       
#>  [7] "MYL9"          "PGRMC1"        "RUFY1"         "PARVB"         "VDAC3"         "IGLL5"        
#>[13] "AKR1C3"        "CD1C"          "RP11-290F20.3" "GNLY"          "S100A8"        "S100A9"       
#>[19] "HLA-DQA1"      "HLA-DPB1"   
```

Use this to relevel axis y:

```
p1 + scale_y_discrete(limits =  rev(p1_b$layout$panel_scales_y[[1]]$range$range))
```

![image](https://user-images.githubusercontent.com/19700954/70902076-f9d48a00-2036-11ea-8660-c0a747c5c3b1.png)

Hope this can help you.

**Comment by singletrips** [comment]
Thanks, it worked!
