### ISSUE TITLE
Cancer cells heterogeneity was lost after integration using SCTransform method

### ISSUE THREAD

**Issue by Chenmengpin** [satijalab/seurat#2461]
Hi,

Thank you for developing this wonderful package. I'm quite new in bioinformatics field, and ran into some trouble when integrating multiple samples. 
I have 4 samples which contain both cancer cells and non-cancer cells(like immunes cells), and simply merge all the samples gave me a bad result, so I'm trying to integrate them using SCTransform in order to remove batch effects. Following is the code I'm using:

B1 <- SCTransform(B1, vars.to.regress = "percent.mt",verbose = FALSE)
B2 <- SCTransform(B2, vars.to.regress = "percent.mt",verbose = FALSE)
B3 <- SCTransform(B3, vars.to.regress = "percent.mt",verbose = FALSE)
B4 <- SCTransform(B4, vars.to.regress = "percent.mt",verbose = FALSE)
All.features <- SelectIntegrationFeatures(object.list = list(B1,B2,B3,B4))
All.list <- PrepSCTIntegration(object.list = list(B1,B2,B3,B4), verbose = FALSE)
All.anchors <- FindIntegrationAnchors(object.list = All.list, normalization.method = "SCT",
                                      anchor.features = All.features)
All.integration <- IntegrateData(anchorset = All.anchors, 
                                 normalization.method = "SCT")
All.integration <- RunPCA(All.integration, verbose = TRUE)
All.integration <- RunTSNE(All.integration, dims = 1:30, do.fast = TRUE)
All.integration <- RunUMAP(All.integration, dims = 1:30)
All.integration <- FindNeighbors(All.integration, dims = 1:30)
All.integration <- FindClusters(All.integration)
DimPlot(All.integration, reduction = "umap",label = TRUE)

The UMAP plot shows that all the sample are mixed very well in each cluster which means the batch effects definitely been removed. However, in consideration of tumor heterogeneity, those cancer cell clusters should be sample-specific as serveral single-cell sequencing papers suggested. So I'm thinking whether it's because the SCTransform is too strong to erase the intransic biological characteristics when removing the batch effects. 
I'm wondering is there a way to preserve the tumor heterogeneity at the same time remove batch effects. Any suggestion would be very appreciated!

Thanks.

**Comment by lyc-1995** [comment]
Hello,
Not one of the developers, but I also think that the SCTransform is too aggressive when we do integration. You may try using the `panc8` datasets from `SeuratData` to reproduce the Label Transfer tutorial [https://satijalab.org/seurat/v3.1/integration.html](url) with SCTransform method, then you can find that the predicted labels show less accurate compared to Standard Workflow.
My experience is that we'd better use Standard Workflow instead of SCTransform while doing integration. Here is an example which may help: [https://github.com/yandgong307/human_macrophage_project/blob/master/data%20integration%20of%20cs11%20and%20cs15%20in%20YS.R](url)

**Comment by Chenmengpin** [comment]
> Hello,
> Not one of the developers, but I also think that the SCTransform is too aggressive when we do integration. You may try using the `panc8` datasets from `SeuratData` to reproduce the Label Transfer tutorial [https://satijalab.org/seurat/v3.1/integration.html](url) with SCTransform method, then you can find that the predicted labels show less accurate compared to Standard Workflow.
> My experience is that we'd better use Standard Workflow instead of SCTransform while doing integration. Here is an example which may help: [https://github.com/yandgong307/human_macrophage_project/blob/master/data%20integration%20of%20cs11%20and%20cs15%20in%20YS.R](url)

Thanks a lot for your suggestion, I'll give it a try.

**Comment by satijalab** [comment]
In your experiment, you have processed each sample as a different batch. As a result, there is no way to remove batch-effects while preserving sample differences, since batch has been conflated with sample. No computational method can overcome this. Instead, you will need to redesign your experiment so that multiple samples are mixed together in the same batch, perhaps using sample multiplexing techniques (like demuxlet, or Cell Hashing)
