### ISSUE TITLE
WhichCell cut out half of the datset

### ISSUE THREAD

**Issue by gaelcge** [satijalab/seurat#247]
Hi

I just realized that WhichCells cut half my dataset in two (precisely) when I subset it based on the "CTL", "KO" in the dataset column from object@meta.data...even if max.cells.per.ident = Inf

```R
WhichCells(object, ident = NULL, ident.remove = NULL, cells.use = NULL, subset.name = "Dataset", accept.low = -Inf, accept.high = Inf, accept.value = c("CTL", "KO"), max.cells.per.ident = Inf, random.seed = 1)
```

Cheers

Gael

**Comment by njkimnj** [comment]
Hey mate, you can try that

cells <- rownames(subset(object@meta.data, Dataset %in% c('CTL','KO')))

**Comment by andrewwbutler** [comment]
Hi Gael,

It looks like 'accept.value' expects just a single value and not a vector of values and that's why it's excluding some of your data. We should probably extend it to be more flexible but one solution for now would be to use `SetAllIdent` on the `meta.data` column of interest and then pass your selection vector to the `ident` parameter in `WhichCells`.
