### ISSUE TITLE
Jupyter kernel crashes for all versions after 3.0.2

### ISSUE THREAD

**Issue by sjfleming** [satijalab/seurat#2482]
When using Seurat in a Jupyter notebook running a python3 kernel, as in the following cell magic:

```python
%%R

library(Seurat)
```

the entire Jupyter kernel crashes.  This is reproducible.  See
https://stackoverflow.com/questions/58611486/r-kernel-crashes-while-loading-r-package-using-rpy2

Following the advice above, if I use Seurat 3.0.2, everything works fine.

**Comment by mojaveazure** [comment]
Hi Stephen,

As mentioned in the StackOverflow article, this happens when an R package calls reticulate (R's version of rpy2). We rely on reticulate for core functionality, so we will not be compatible with Jupyter for the forseeable future.

If you're looking for a notebook experience that works with both R and Python, checkout [RMarkdown Notebooks](https://bookdown.org/yihui/rmarkdown/notebook.html). You get all the formatting power of RMarkdown (what we use to write our vignettes), inline output and figures like Jupyter, [the ability to easily pass objects between R and Python](https://rstudio.github.io/reticulate/articles/rstudio_ide.html), and all the niceties that comes with working in RStudio.

**Comment by sjfleming** [comment]
Thanks so much for you answer, I appreciate it!
