### ISSUE TITLE
Featureplot: columns of graphs despite using split.by parameter?

### ISSUE THREAD

**Issue by hemadelon** [satijalab/seurat#2495]
Hi everyone!

I read in the documentation that when using the split.by parameter in FeaturePlot you cannot also use ncol to set the number of columns.
However, the variable I'm using the split my graphs by consists of 10 entries. That means it now generates a very wide table of featureplots that I cannot see, because they are so close together.

Is there any other way to still divide the generated featureplots in columns? 
I attempted it by doing ggarrange, but that didn't work.

Hope someone can help me out!

**Comment by ahoffrichter** [comment]
I'm having the same problem.  I tried using: 

`p <- FeaturePlot(object, features = geneX, split.by = "sample", combine = F)
plot_grid(plotlist = p, ncol=4)`

it works, but it's not very pretty.

**Comment by mojaveazure** [comment]
As noted in the [documentation](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/FeaturePlot) for `FeaturePlot`, the `ncol` parameter is ignored when using `split.by`

We do this since `split.by` is not just a splitting term, but also used to replicate the behavior of `FeatureHeatmap` from the Seurat v2.X; to get around this, you can set `combine = FALSE` to return a list of plots and use either Anne's solution of using `plot_grid` from cowplot, Seurat's [`CombinePlots`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.2/topics/CombinePlots), or another way of stitching the plots together.
