### ISSUE TITLE
scale.data in "RNA" assay after SCTransform-integration workflow

### ISSUE THREAD

**Issue by saeedfc** [satijalab/seurat#2503]
Hi,

I am using SCTransform > Integration workflow. In this (https://github.com/satijalab/seurat/issues/2303#issue-519978917) issue discussion from November 2019, it was said that the scale.data won't be empty in the latest develop branch. I am using Seurat 3.1.2 (later version- December 2019). I have scale.data empty in 'RNA' assay but not empty in 'integration' assay (Still not for all features). But for gene expression visualization such as Heatmap I should actually use RNA assay, right (that require scaled data as well)? Can I just use ScaleData function with RNA assay here for these purposes?

Or can I use return.only.var.genes = FALSE for SCtransform and use the scale.data slot from SCT assay for heatmap?
Thanks and kind regards,
Saeed
https://github.com/satijalab/seurat/issues/2303#issue-519978917

**Comment by yuhanH** [comment]
Hi,
After running SCTransform > Integration workflow, the scale.data in SCT assay is not empty. 
scale.data is still empty in the RNA assay, and you can just run the NormalizeData and ScaleData in the RNA assay for gene expression visualization.
Also, you can return residuals for all genes in the SCTransform for heatmap.

**Comment by ymahmoud** [comment]
> 
> 
> Hi,
> After running SCTransform > Integration workflow, the scale.data in SCT assay is not empty.
> scale.data is still empty in the RNA assay, and you can just run the NormalizeData and ScaleData in the RNA assay for gene expression visualization.
> Also, you can return residuals for all genes in the SCTransform for heatmap.

Hi,
If I want to use the SCT scaled data for the heatmap, I should run SCTransform again after integration, right? Because I tried using the SCT scaled.data slot (that come from the SCTransform normalization and scaling of each dataset before integration) and the heatmap showed clear differences between cells from the distinct datasets within each cluster.
In that case, if I run NormalizeData and ScaleData (to use RNA assay) or SCTransform (to use SCT assay) after integration, should I regress out for the same variables that I use initially (both datasets have these same variables)? Would it be convenient to add the dataset as a variable to regress out during scaling?

Thank you very much for your help and for this wonderful package!
