### ISSUE TITLE
Problem with plots in Seurat v 3.1.2

### ISSUE THREAD

**Issue by idalarsson** [satijalab/seurat#2508]
Hi,

I'm using Seurat on a daily basis and came across an Error today that I haven't gotten before and don't know how to solve. When I'm trying to plot, e.g. using DimPlot() or VariableFeaturePlot(), I get the following error:
Error in .Call("decode_c", as_character(colour), alpha, as.integer(to),  : 
  Incorrect number of arguments (5), expecting 4 for 'decode_c
I've tried simple things like restarting R, re-installing Seurat etc but nothing seems to work. Have you seen this error before and know how to solve it? 

Thanks!
Ida

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but maybe can help.  Could you please post full code that you are running  for `DimPlot()` that gives the error?

Thanks,
Sam

**Comment by idalarsson** [comment]
Thanks! This is the code and as I mentioned above, the error occur both at DimPlot() and VariableFeaturePlot()

`###Script for loading, performing some QC and downstream analysis of scRNA###
library(Seurat)
library(dplyr)
library(gridExtra)
library(biomaRt)
library(RColorBrewer)
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DESeq2")
BiocManager::install("MAST")
library(DeSeq2)

Dalmo<-CreateSeuratObject(counts = data, min.cells = 3,min.features =500,project = 'Non_treatment',meta.data = combinedMatrix[,33426:33427])

#Quality control checks and opt. filtering
Dalmo[["percent.mt"]] <- PercentageFeatureSet(Dalmo, pattern = "^MT.")
VlnPlot(Dalmo, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
plot1 <- FeatureScatter(Dalmo, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(Dalmo, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
Dalmo <- subset(Dalmo, subset = percent.mt < 30)

#Normalization
Dalmo <- NormalizeData(Dalmo)
Dalmo <- FindVariableFeatures(Dalmo,do.plot=TRUE,display.progress = F)

Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(Dalmo), 10)

plot variable features with and without labels
plot1 <- VariableFeaturePlot(Dalmo)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1, plot2))

all.genes <- rownames(Dalmo)
Dalmo <- ScaleData(Dalmo,features=all.genes)

Perform dimensionality reduction by PCA and UMAP embedding
Dalmo <- RunPCA(Dalmo, verbose = FALSE)
Dalmo <- RunTSNE(Dalmo)
Dalmo <- RunUMAP(Dalmo, dims = 1:30, verbose = FALSE) #umap needs to be installed

Dalmo <- FindNeighbors(Dalmo, dims = 1:30, verbose = FALSE)
Dalmo <- FindClusters(Dalmo, verbose = TRUE)

DimPlot(Dalmo,reduction = "umap", group.by = 'days')`

**Comment by samuel-marsh** [comment]
Do you get similar error if you try running identical code (minus the exp specific meta data) using pbmc vignette data?

Otherwise my best first guess based on your code is something to do with the format of information in metadata slots.

**Comment by ValentinCL** [comment]
I have the same probleme with the function ggbetweenstats...... Do you have a soluce ?

**Comment by idalarsson** [comment]
@samuel-marsh thank you for the input! 

I tried with the pbmc data but I get the same error, so it doesn't seem to an issue with my data (which it shouldn't be because I've been able to run this exact script millions of times but now this error has started to appear, probably after some update?).

**Comment by samuel-marsh** [comment]
Hi @idalarsson 

Can you provide the output of `sessionInfo()`?  When I run the code you provide (again minus the meta.data info) on the pbmc dataset I have no errors with VariableFeaturePlot or DimPlot.  I would also suggest trying to update to the latest github release if you are not already on it and seeing if that solves the issue.

Best,
Sam

**Comment by idalarsson** [comment]
Yes, here is the output:
`> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                   
[5] LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_3.1.2

loaded via a namespace (and not attached):
  [1] TH.data_1.0-10      Rtsne_0.15          colorspace_1.4-1    ggridges_0.5.2      rstudioapi_0.10     farver_2.0.2        leiden_0.3.1       
  [8] listenv_0.8.0       npsurv_0.4-0        ggrepel_0.8.1       mvtnorm_1.0-11      codetools_0.2-16    splines_3.6.2       R.methodsS3_1.7.1  
 [15] mnormt_1.5-5        lsei_1.2-0          TFisher_0.2.0       zeallot_0.1.0       jsonlite_1.6        ica_1.0-2           cluster_2.1.0      
 [22] png_0.1-7           R.oo_1.23.0         uwot_0.1.5          sctransform_0.2.1   BiocManager_1.30.10 compiler_3.6.2      httr_1.4.1         
 [29] backports_1.1.5     assertthat_0.2.1    Matrix_1.2-18       lazyeval_0.2.2      htmltools_0.4.0     tools_3.6.2         rsvd_1.0.2         
 [36] igraph_1.2.4.2      gtable_0.3.0        glue_1.3.1          RANN_2.6.1          reshape2_1.4.3      dplyr_0.8.3         rappdirs_0.3.1     
 [43] Rcpp_1.0.3          Biobase_2.44.0      vctrs_0.2.1         multtest_2.40.0     gdata_2.18.0        ape_5.3             nlme_3.1-142       
 [50] gbRd_0.4-11         lmtest_0.9-37       stringr_1.4.0       globals_0.12.5      lifecycle_0.1.0     irlba_2.3.3         gtools_3.8.1       
 [57] future_1.15.1       MASS_7.3-51.5       zoo_1.8-6           scales_1.1.0        parallel_3.6.2      sandwich_2.5-1      RColorBrewer_1.1-2 
 [64] reticulate_1.14     pbapply_1.4-2       gridExtra_2.3       ggplot2_3.2.1       stringi_1.4.3       mutoss_0.1-12       plotrix_3.7-7      
 [71] caTools_1.17.1.3    BiocGenerics_0.30.0 bibtex_0.4.2.2      Rdpack_0.11-1       SDMTools_1.1-221.2  rlang_0.4.2         pkgconfig_2.0.3    
 [78] bitops_1.0-6        lattice_0.20-38     ROCR_1.0-7          purrr_0.3.3         labeling_0.3        htmlwidgets_1.5.1   cowplot_1.0.0      
 [85] tidyselect_0.2.5    RcppAnnoy_0.0.14    plyr_1.8.5          magrittr_1.5        R6_2.4.1            gplots_3.0.1.2      multcomp_1.4-12    
 [92] pillar_1.4.3        sn_1.5-4            fitdistrplus_1.0-14 survival_3.1-8      tibble_2.1.3        future.apply_1.4.0  tsne_0.1-3         
 [99] crayon_1.3.4        KernSmooth_2.23-16  plotly_4.9.1        grid_3.6.2          data.table_1.12.8   metap_1.2           digest_0.6.23      
[106] tidyr_1.0.0         numDeriv_2016.8-1.1 R.utils_2.9.2       RcppParallel_4.4.4  stats4_3.6.2        munsell_0.5.0       viridisLite_0.3.0  `

**Comment by ValentinCL** [comment]
And the mine in order to complete (maybe we have the same problem...)


R version 3.6.2 (2019-12-12) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 17763)  Matrix products: default  locale: [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                   LC_TIME=French_France.1252      attached base packages:  [1] grid      stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] RCy3_2.6.3          ggtree_2.0.1        DECIPHER_2.14.0     RSQLite_2.2.0       dada2_1.14.0        Rcpp_1.0.3          impute_1.60.0       genefilter_1.68.0   rlist_0.4.6.1       [10] epitools_0.5-10     labdsv_2.0-1        mgcv_1.8-31         UpSetR_1.4.0        VennDiagram_1.6.20  futile.logger_1.4.3 ggraph_2.0.0        httr_1.4.1          RJSONIO_1.3-1.4     [19] brainGraph_2.7.3    CINNA_1.1.53        treemap_2.4-2       kableExtra_1.1.0    scales_1.1.0        ips_0.0.11          intergraph_2.0-2    ggnetwork_0.5.1     igraph_1.2.4.2      [28] ade4_1.7-13         structSSI_1.1.1     PMA_1.2             reshape2_1.4.3      sys_3.3             rmarkdown_2.0       devtools_2.2.1      usethis_1.5.1       phangorn_2.5.5      [37] ape_5.3             googlesheets_0.3.0  googledrive_1.0.0   gridExtra_2.3       R.utils_2.9.2       R.oo_1.23.0         R.methodsS3_1.7.1   nlme_3.1-143        ggrepel_0.8.1       [46] here_0.1            sjPlot_2.8.1        formattable_0.2.0.1 rfishbase_3.0.4     plyr_1.8.5          vegan_2.5-6         lattice_0.20-38     permute_0.9-5       entropart_1.6-3     [55] randomForest_4.6-14 e1071_1.7-3         pls_2.7-2           miniUI_0.1.1.1      forcats_0.4.0       stringr_1.4.0       dplyr_0.8.3         purrr_0.3.3         readr_1.3.1         [64] tidyr_1.0.0         tibble_2.1.3        tidyverse_1.3.0     microbiome_1.8.0    ggplot2_3.2.1       shiny_1.4.0         knitr_1.27          phyloseq_1.30.0     Biostrings_2.54.0   [73] XVector_0.26.0      IRanges_2.20.2      S4Vectors_0.24.2    BiocGenerics_0.32.0  loaded via a namespace (and not attached):   [1] statnet.common_4.3.0        Hmisc_4.3-0                 Rsamtools_2.2.1             class_7.3-15                ps_1.3.0                    foreach_1.4.7                 [7] rprojroot_1.3-2             crayon_1.3.4                centiserve_1.0.0            MASS_7.3-51.5               backports_1.1.5             reprex_0.3.0                 [13] rlang_0.4.2                 readxl_1.3.1                performance_0.4.2           nloptr_1.2.1                callr_3.4.0                 BiocParallel_1.20.1          [19] rjson_0.2.20                bit64_0.9-7                 glue_1.3.1                  pheatmap_1.0.12             processx_3.4.1              oro.nifti_0.9.1              [25] AnnotationDbi_1.48.0        haven_2.2.0                 tidyselect_0.2.5            SummarizedExperiment_1.16.1 XML_3.98-1.20               zoo_1.8-7                    [31] sjmisc_2.8.3                GenomicAlignments_1.22.1    chron_2.3-54                xtable_1.8-4                magrittr_1.5                evaluate_0.14                [37] cli_2.0.1                   zlibbioc_1.32.0             hwriter_1.3.2               rstudioapi_0.10             rpart_4.1-15                fastmatch_1.1-0              [43] sjlabelled_1.1.2            lambda.r_1.2.4              treeio_1.10.0               RcppEigen_0.3.3.7.0         xfun_0.12                   parameters_0.4.1             [49] pkgbuild_1.0.6              multtest_2.42.0             cluster_2.1.0               tidygraph_1.1.2             biomformat_1.14.0           FactoMineR_2.1               [55] expm_0.999-4                RNifti_1.0.1                dendextend_1.13.2           png_0.1-7                   reshape_0.8.8               zeallot_0.1.0                [61] withr_2.1.2                 bitops_1.0-6                ggforce_0.3.1               cellranger_1.1.0            coda_0.19-3                 pillar_1.4.3                 [67] RcppParallel_4.4.4          multcomp_1.4-12             fs_1.3.1                    scatterplot3d_0.3-41        vctrs_0.2.1                 ellipsis_0.3.0               [73] generics_0.0.2              gh_1.0.1                    tools_3.6.2                 foreign_0.8-74              munsell_0.5.0               tweenr_1.0.1                 [79] DelayedArray_0.12.2         emmeans_1.4.3.01            qdapTools_1.3.3             fastmap_1.0.1               compiler_3.6.2              pkgload_1.0.2                [85] abind_1.4-5                 httpuv_1.5.2                sessioninfo_1.1.1           GenomeInfoDbData_1.2.2      later_1.0.0                 jsonlite_1.6                 [91] GGally_1.4.0                graph_1.64.0                tidytree_0.3.1              estimability_1.3            lazyeval_0.2.2              promises_1.1.0               [97] latticeExtra_0.6-29         effectsize_0.0.1            sna_2.5                     checkmate_1.9.4             sandwich_2.5-1              webshot_0.5.2               [103] Rtsne_0.15                  Biobase_2.46.0              survival_3.1-8              htmltools_0.4.0             memoise_1.1.0               graphlayouts_0.5.0          [109] quadprog_1.5-8              viridisLite_0.3.0           digest_0.6.23               assertthat_0.2.1            mime_0.8                    leaps_3.1                   [115] futile.options_1.0.1        bayestestR_0.5.0            remotes_2.1.0               data.table_1.12.8           blob_1.2.0                  labeling_0.3                [121] splines_3.6.2               Formula_1.2-3               Rhdf5lib_1.8.0              RCurl_1.95-4.13             broom_0.5.3                 hms_0.5.3                   [127] modelr_0.1.5                rhdf5_2.30.1                colorspace_1.4-1            base64enc_0.1-3             BiocManager_1.30.10         mnormt_1.5-5                [133] GenomicRanges_1.38.0        nnet_7.3-12                 mvtnorm_1.0-12              fansi_0.4.1                 R6_2.4.1                    factoextra_1.0.6            [139] lifecycle_0.1.0             acepack_1.4.1               formatR_1.7                 ShortRead_1.44.1            minqa_1.2.4                 testthat_2.3.1              [145] Matrix_1.2-18               desc_1.2.0                  TH.data_1.0-10              RColorBrewer_1.1-2          iterators_1.0.12            htmlwidgets_1.5.1           [151] polyclip_1.10-0             network_1.16.0              rvest_0.3.5                 flashClust_1.01-2           insight_0.8.0               htmlTable_1.13.3            [157] matrixStats_0.55.0          codetools_0.2-16            lubridate_1.7.4             prettyunits_1.1.0           psych_1.9.12.31             dbplyr_1.4.2                [163] gridBase_0.4-7              GenomeInfoDb_1.22.0         gtable_0.3.0                DBI_1.1.0                   stringi_1.4.4               farver_2.0.3                [169] annotate_1.64.0             viridis_0.5.1               xml2_1.2.2                  rvcheck_0.1.7               boot_1.3-24                 ggeffects_0.14.0            [175] lme4_1.1-21                 bit_1.1-15.1                sjstats_0.17.7              jpeg_0.1-8.1                pkgconfig_2.0.3             corrplot_0.84
--
 
> | >
>

**Comment by samuel-marsh** [comment]
Hi @idalarsson,

This may be beyond me at this point since I can't replicate the error with your code and pbmc dataset and I don't have windows machine currently to test on.  Hopefully member of the Dev team can help out.  @timoast @andrewwbutler any suggestions?

Thanks and sorry I can't be of more help!
Sam

**Comment by ValentinCL** [comment]
Apparently the problem comes from ggplot....

**Comment by timoast** [comment]
This does look like an issue with ggplot2 rather than Seurat, and likely platform-specific. Please raise an issue with a reproducible example with the ggplot2 team.

**Comment by Rcoder-007** [comment]
AS mentioned  by @timoast , this is a ggplot2 issue. I tried by changing R from 64 bit to 32 bit and it worked for me. I would suggest to try using 32bit version.
