### ISSUE TITLE
The return of "The following X features requested have not been scaled"

### ISSUE THREAD

**Issue by dagarfield** [satijalab/seurat#2515]
Pardon, but suffering from issue 1222
https://github.com/satijalab/seurat/issues/1222
(see comment)

In short, something odd is happening along the CellCycle removal pathways. Thanks!

**Comment by satijalab** [comment]
This is usually because the features listed were not included in the ScaleData call. This is potentially because they were not detected in the dataset as variable genes, or were not detected in the dataset at all. 

To avoid this, run ScaleData on the list of cc.genes instead of variable features. However, any genes that were not detected in any cells cannot be scaled, hence the warning message.
