### ISSUE TITLE
Adding contour to a feature plot

### ISSUE THREAD

**Issue by cjuagf** [satijalab/seurat#2520]
Hello Seurat team,

Thanks for developing Seurat! I would like to add a contour to a feature plot in Seurat such as below:
<img width="700" alt="Screen Shot 2020-01-20 at 4 15 01 PM" src="https://user-images.githubusercontent.com/47041278/72765179-0bfa9880-3ba0-11ea-8b9a-dc1ed3a19094.png">

This can be done using robustsinglecell, but when I tried it using my Seurat object I was not able to generate this. Do you have any suggestions/ideas as to how to generate this contour plot in Seurat?

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Since Seurat returns ggplot objects you can modify as you would any plot in ggplot.  I believe `geom_density_2d` is what you are looking for.  See here for more info:
[https://ggplot2.tidyverse.org/reference/geom_density_2d.html](https://ggplot2.tidyverse.org/reference/geom_density_2d.html)

Best,
Sam

**Comment by cjuagf** [comment]
Thank you!

**Comment by ecdabe-BISC** [comment]
So could anyone expand upon this a bit? I've tried many versions of "expanding on a plot as you would any plot in ggplot". I've tried many ways of doing + geom_density_2d() but its calling for aes x & y variables and it still doesn't work if I provide them because they are coming from a Seurat object.

**Comment by ecdabe-BISC** [comment]
I worked it out! This is for my main UMAP cluster diagram, but I feel like there's probably a more straight forward way to do this that would allow me to maintain the same color aesthetics or overlay onto my original dimplot image instead of making a separate image? 
data <- Embeddings(object = Object[["umap"]])[(colnames(Object)), c(1, 2)]
data <- as.data.frame(data)
data$cluster <- Object@active.ident
ggplot(data)+geom_point(aes(x=UMAP_1, y=UMAP_2),color=data$cluster, show.legend = TRUE)+geom_density2d(aes(x=UMAP_1, y=UMAP_2))+theme_classic()+scale_x_continuous(limits=c(min(data$UMAP_1) - .10*diff(range(data$UMAP_1)),max(data$UMAP_1) + .10*diff(range(data$UMAP_1))))+scale_y_continuous(limits=c(min(data$UMAP_2) - .10*diff(range(data$UMAP_2)),max(data$UMAP_2) + .10*diff(range(data$UMAP_2))))
![image](https://user-images.githubusercontent.com/53497718/85245201-dab71a80-b414-11ea-9756-9a77e6719f1a.png)
![image](https://user-images.githubusercontent.com/53497718/85245209-e30f5580-b414-11ea-8f10-3e5f52a9bc07.png)

**Comment by aditisk** [comment]
Hi @ecdabe-BISC, thanks for the example code. I was able to generate a plot with my data but I needed some help in interpretation. What are the contours presenting ? Is it looking at the number of cells in each area to quantify the "density" of each cluster ? Thanks in advance for your help.
