### ISSUE TITLE
RunPCA error in Guided Clustering tutorial

### ISSUE THREAD

**Issue by alliweske** [satijalab/seurat#2526]
When I run this:
scdata <- RunPCA(scdata, features = VariableFeatures(object = scdata))
I get this error:
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

I've tried looking at previous posts with the same error message, but altering the number of PCs or dims hasn't worked. How to I fix this?

**Comment by andrewwbutler** [comment]
You get this error when running through the pbmc3k guided clustering tutorial? Or are you just running those commands on your own dataset? Could you post the code you ran up until this point. Also, could you check what the dimensions of the following are?

```R
dim(GetAssayData(scdata, slot = "scale.data"))
length(VariableFeatures(object = scdata))
```

**Comment by alliweske** [comment]
> You get this error when running through the pbmc3k guided clustering tutorial? Or are you just running those commands on your own dataset? Could you post the code you ran up until this point. Also, could you check what the dimensions of the following are?
> 
> ```r
> dim(GetAssayData(scdata, slot = "scale.data"))
> length(VariableFeatures(object = scdata))
> ```

I am trying to do the tutorial commands on my own dataset starting with:
scdata<-CreateSeuratObject(GENE_RAW_COUNTS)
and the rest of the commands the same as the tutorial. I assume the problem is that I need to alter the commands to fit my dataset, but any tips or suggestions on how to do that would be appreciated! Here's the outputs for dimension and length:
 dim(GetAssayData(scdata, slot = "scale.data"))
[1] 17737     3
> length(VariableFeatures(object = scdata))
[1] 2000

**Comment by andrewwbutler** [comment]
Based on the dimensions of the scale.data slot in `scdata`, it looks like you only have 3 cells in your `scdata` object? This suggests something else went wrong upstream of `RunPCA`.

**Comment by mariannebest** [comment]
Hi both! I have been trying to use Seurat for bulk-seq dataset as it was confirmed in another couple of threads by Satija lab that this can work. However, when I am up to the point of RunPCA I also have the same error message as posted by @alliweske 

Following your advice @andrewwbutler , I have 15 bulk samples (each have 100 cells sequenced together)... is the RunPCA not working because 15 is too low? Can I somehow reduced the amount of samples needed to run it?

> dim(GetAssayData(seurat, slot = "scale.data"))
[1] 18953    15
> length(VariableFeatures(object = seurat))
[1] 2000

Thank you for your help!
Marianne
