### ISSUE TITLE
Results compared between Harmony and Seurat

### ISSUE THREAD

**Issue by w2niva** [satijalab/seurat#2533]
Hi All,
I have a 10X single-cell dataset consisting of four treatments and two replicates (8 samples). There are batch effects between my samples. I have used Seurat and Harmony both to correct the batch effects. While the cluster identity and markers identified using FindConservedMarkers are consistent across Harmony and Seurat; differential gene expression between treatments is very different. Although there are overlapping genes between the two runs. I have the following questions:
1. has anyone compared the two methods and seen difference in DGE?
2. Is there a way to choose which batch correction is better?
I would appreciate any thoughts on the two methods.

**Comment by satijalab** [comment]
In general, my opinion is that the number of DGE is not a good metric to assess correction. If you do the integration poorly (for example, if you match B cells in one sample with T cells in another), there will be very high DGE, but that is due to computational error.

In our Seurat wrappers (https://satijalab.org/seurat/vignettes.html) page we demonstrate how to run a set of awesome batch correction techniques on a few different samples. You can see how the results compare.
