### ISSUE TITLE
Clarification on default integration algorithim

### ISSUE THREAD

**Issue by Connorr0** [satijalab/seurat#2534]
I was reading [Batch effects in single-cell RNA-sequencing data are corrected by matching mutual nearest neighbors](https://www.nature.com/articles/nbt.4091) and noticed that the batch correction vector seems to point to the average of the mutual nearest neighbors. Since the labs I work for often use your package when doing integration I was wondering if you could clear some things up:

1) Gaussian smoothing is applied, but I could not tell if it was on the pairwise vectors for one cell (which do not seem to have a differing spatial component) or between batch corrected vectors for cells?

2) Other than Gaussian smoothing I am not seeing an opportunity to "weaken" the pull from one dataset to another, as said before it appears that the new gene expression vector for the cells will become something that highly resembles the average of it's nearest neighbors in the other dataset. Is this the case?

**Comment by satijalab** [comment]
1. We average correction vectors of cells that are similar to the target cell (the latter)

2. Remember that it is the batch correction vector that is averaged, not the expression of the cells in the other dataset.

Having said that, If the batch effect vectors are consistent across similar cells (i.e. cells that are similar to each other in one dataset form anchors to cells that are similar to each other in another), then there will be effective correction (i.e. a strong pull). That is because there is good evidence to support alignment.

If the anchors are not consistent, then disparate batch effect vectors will be averaged together, which will weaken the pull. This is what happens when there is a population that is present in one dataset, but not present in another.

**Comment by Connorr0** [comment]
Cool, I have a follow-up question (sorry for asking after closing). I have recently noticed that reviewers will ask for batch effect corrected data. Heatmaps and UMAPs that show batch specific expression are often turned back, while I think this is good I am currently seeing a problem with this which I think is overlooked, namely MMN batch effect correction on data with multiple confounding factors. 

I know many people who believe that because MMN is a batch effect correction algorithm it will leave their timepoint or treatment specific variation alone. Specifically I see people use this approach when combining two datasets with two or more confounding factors (batch + treatment, batch + time). In this case the assumptions about the orthogonality of the important biological variation to the batch vector does not seem to hold. (Since a drug is now pushing a change between the two samples for example.) Also it seems inappropriate to apply one correction to samples with multiple confounding variables in general.

In the case where you have two known factors effecting gene expression do you still recommend MMN integration when looking for differences between two treatments? I feel like I saw something about this on your webpage as the vignettes for Seurat 3 were updated, but I have been having trouble finding it recently.
