### ISSUE TITLE
Supervised clustering on a subset of integrated object (best practices?)

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#2539]
Hello Seurat team!

I have seen some other similar issues about this (such as #326, #127, #1883), but I am not sure how relevant those answers are in my case.

I integrated 12 different 10x scRNAseq runs using `rpca` approach and created a `combined` object in the first pass analysis. I'd like to subset all the T cell clusters into a separate object and then perform re-clustering using a user-defined list of genes. My goal is using certain genes (based on biological knowledge) and try to see if they can differentiate T cell subsets in a meaningful way. 

I got something to work but I'm not sure if it is the best way of doing what I'm trying to do. Please see my code below and let me know if you see anything wrong.

```
dim(combined)
# > 17306 52643

DefaultAssay(combined)
# > "RNA"

tcell <- subset(combined, idents="T cell")

dim(tcell)
# > 17306 24859 

# Genes to use for clustering and dimensionality reduction
genes <- c( "Havcr2",  "Tigit",   "Lag3" ,   "Pdcd1" ,  "Ctla4",   "Prdm1" ,  "Fasl"  ,  "Ifng" ,  
 "Tnf",     "Cxcr5",   "Ccr7" ,   "Bcl6",    "Tcf7" ,   "Irf8"  ,  "Cx3cr1" , "Lef1" ,  
 "Klrg1",   "Myc" ,    "Slamf7" , "Ifitm1",  "Ifitm2" , "Isg20",   "Il12rb1" ,"Zeb1" ,  
 "Tbx21" ,  "Prf1" ,   "Gzmb" ,   "Gzma",    "Gzmk" ,   "Sell" ,   "Il7r",    "Mki67" )

tcell <- FindVariableFeatures(tcell)

tcell <- ScaleData(tcell)

dims <- 5

tcell <- RunPCA(tcell, 
                features = genes,
                approx=F, npcs = dims)

#> The following 16 features requested have not been scaled (running reduction without them): 
Tigit, Lag3, Pdcd1, Prdm1, Fasl, Cxcr5, Bcl6, Slamf7, Il12rb1, Zeb1, Foxo3, Id2, Cd3e, Cd3g, Cd8a, Tbx21

tcell <- RunTSNE(tcell, 
                 check_duplicates=F, 
                 features = genes, dims = 1:dims)

tcell <- RunUMAP(tcell, features = genes, umap.method="uwot")

tcell <- FindNeighbors(tcell,
                       features = genes)

tcell <- FindClusters(tcell, resolution = 0.5)

```

My specific questions are below. Although I realize that some answers may depend on the experimental context, I'm trying to develop a general sense of how I can perform this analysis in the best way possible. I apologize in advance if some of these questions are too basic.

**1-** Am I correct in using `RNA` as the DefaultAssay for subsetting the `tcell` object and downstream applications?

**2-** If my goal is to drive clustering/dim reduction with a list of genes, do I still need to calculate variable genes?

**3-** Do I need to perform `ScaleData` step again if I want to change parameters in PCA/tSNE/UMAP steps (I wouldn't think so, but I remember reading a post about this previously)?

**4-** How many dimensions should one calculate when using a list of genes like I'm trying to do here? Is there a rough number for a short vs large list of user-defined genes?

**5-** Why am I getting the warning about genes not being scaled and left out of PCA calculation?

**6-** Which steps are the appropriate places to pass the user-defined gene list? Here I used in all three of the PCA-tSNE-UMAP steps. If I understand it correctly, passing a custom feature list to `RunTSNE` and `RunUMAP` will change the overall "look" of the clusters, while passing it to `FindNeighbors` will change how the clusters will be determined. So, one can use two different sets of genes (ie variable genes vs user-provided shortlist) to change topography and the composition of the output. Is this right?

**7-** Does calculating more than one dim reductions (i.e. both tSNE and UMAP) impact the clustering step?

Alternatively, would you recommend using all variable genes in the subsetted object to perform dim reduction?

I greatly appreciate everything you do for this awesome software solution!

Best,
Atakan

**Comment by andrewwbutler** [comment]
Hi Atakan,

1. For `subset`, it doesn't matter what  the `DefaultAssay` is as this function will subset all assays to only contain the cells specified. For downstream analysis, if you've performed an integration workflow, I would use the `integrated` assay. Also relevant here, you should be sure that the `features.to.integrate` parameter in `IntegrateData` includes the features you want to use downstream, otherwise this function will only store values for the feature set used in the anchor finding step. 

2. No, if you want to use a supervised list of genes, you don't need to calculate variable genes. 

3. Yes, you should perform `ScaleData` again since you've taken a subset of cells. You should also pass your supervised list here to the `features` parameter so that those features are scaled. 

4. You could check out the `ElbowPlot` to get a rough estimate of this. Since you are already working with a reduced feature set though, you could also experiment with using the features directly as input to clustering/viz. 

5. You are getting warnings because those genes haven't been scaled. See point 3. (Genes could also be left out if they have no variance but that seems unlikely here).

6. Here, you want to refer back to point 4. If you've decided to use PCA, then you should use those chosen PCs as input for `RunTSNE`/`RunUMAP`/`FindNeighbors`. If you want to try using the features directly, this is where you would pass that feature list to those functions (running PCA wouldn't be necessary in that situation). 

7. If you are going to cluster in a reduced dimension space, this is specified by the `reduction` parameter in `FindNeighbors`. Computing more `DimReducs` doesn't affect anything. The default here is `reduction = "pca"` so computing either or both tSNE and UMAP would have no impact on the clustering results and are typically used primarily for visualization.
