### ISSUE TITLE
seurat color palette

### ISSUE THREAD

**Issue by andrea-de-micheli** [satijalab/seurat#257]
Hello,

Is there a way to retrieve the colors that TSNEPlot for each group? I would like to use the same exact colors for labeling my cells in another context.

Thank you!
Andrea

**Comment by leonfodoulian** [comment]
Hello Andrea,

If the plotted colours are the default colours of `ggplot2`, you can get these colours using the  `hue_pal()` function of the `scales` packages in R. This comes in handy if you have a very large number of clusters. Otherwise, you can define your custom colours using `scales_colour_manual()`. Below is a combination of both options:

```
# Load the "scales" package
require(scales)

# Create vector with levels of object@ident
identities <- levels(object@ident)

# Create vector of default ggplot2 colors
my_color_palette <- hue_pal()(length(identities))

# Plot the tSNE plot with the default ggplot2 colors
TSNEPlot(object = object, do.return = T) + 
  scale_color_manual(values = my_color_palette)
```

The colour codes can be found in `my_color_palette`.

Hope this helps!

Best,
Leon

**Comment by mojaveazure** [comment]
Hi Andrea,

You can use ggplot2's [`ggplot_build`](https://www.rdocumentation.org/packages/ggplot2/versions/2.2.1/topics/ggplot_build) function to deconstruct a tSNE plot into the data used to make said plot.

```R
> p <- Seurat::TSNEPlot(object, do.return = TRUE)
> pbuild <- ggplot2::ggplot_build(p)
> pdata <- pbuild$data[[1]]
```

The colors used, in hexadecimal, are in the `colour` column of `pdata`, the groups in the `group` column.
