### ISSUE TITLE
Question about find highly variable genes

### ISSUE THREAD

**Issue by LuoJulia** [satijalab/seurat#2599]
I had some questions about what data the FindVariableGenes and ScaleData functions pull from.

For my analysis, I first do standard preprocessing and integrate the different samples of bulk data and cluster on that. Then, I subset out the cells of interest and do analyses on this subset of cells.
On this subset, I reintegrate and afterwards, find new variable genes, scale, PCA, cluster, etc. I noticed that there is no difference in the scale.data slot under the integrated assay whether or not I run the FindVariableGenes function on the integrated assay. 
When I run the FindVariableGenes on the object with the active.assay being "integrated", the "var.features" slot under the integrated assay does change, however the rownames of the object do not (nor do the Dimnames under the data slot of the integrated assay slot).
It seems to me that ScaleData is pulling the list of genes from Dimnames[[1]] instead of the var.features slot. Is there a reason for this/is my understanding correct? Also, in that case, in the RunPCA function, where is it pulling the numbers from if I set my active.assay to "integrated" ? 

Would appreciate any help, I'm very new and confused!

**Comment by andrewwbutler** [comment]
Hi, 

I think perhaps the confusion is coming from the behavior of the `IntegrateData` function. By default, this function only returns the features specified by `features.to.integrate` (the rational here is to save on memory because the integrated data matrix is no longer sparse and for large datasets, this can become cumbersome). Likely what is happening here is that you didn't set `features.to.integrate` and so by default it, uses the same features that were used to determine the anchors (typically 2k) and so the data matrix that is returned has 2k features. You then run `FindVariableFeatures` on this data and by default, ask for 2k variable features, so it just picks all of the available features. Without seeing your code, this is probably why the scale.data slot is the same under both scenarios. You can also explicitly set which features to scale in `ScaleData` if you want to test things out for yourself. 

Hope that clears things up. If not, feel free to reopen.

**Comment by DCarbonez** [comment]
Hi,

I'd like to build further on this issue.

I have 3 datasets. Each of them was analysed separately. Afterwards I integrated them like this: 
`samples.anchors <- FindIntegrationAnchors(object.list = list_of_samples, dims= 1:30, anchors.features = 3000

all.features <- Reduce(f=intersect, x=lapply(list_of_samples, rownames))

integrated_seurat_object <- IntegrateData(anchorset = samples.anchors, dims = 1:30, features.to_integrate = all.features`

When i check the variable features on the integrated seurat object (`integrated_seurat_object@assays$integrated@var.features`), there are 3,000 variable features, exactly the same as the anchors chosen. Although there are 15,287 features in the dataset.

Subsequently, I ran FindVariableFeatures on the integrated seurat object

`integrated_seurat_object_HVF <- FindVariableFeatures(integrated_seurat_object, selection.method="vst", nfeatures=3000)`

`sum(integrated_seurat_object_HVG@assays$integrated@var.features %in% integrated_seurat_object@assays$integrated@var.features)`

This resulted in 442. Which means that only 442 of the 3000 anchor features were also used as Highly Variable Features.

I was wondering: 
1) Why are the anchor features stored in the var.features in the integrated seurat object, as they are not the most highly variable features after all?
2) Is it necessary to recalculate the VariableFeatures after integration, as it seems the anchors are not representative for the Highly Variable Features after all?

Thanks in advance

**Comment by mariannebest** [comment]
@LuoJulia Hello Julia, I hope you don't mind me asking but I am quite new to this and am trying to do what you say above and integrate my 6 samples of bulk seq data and cluster on that through Seurat. Do you have a protocol or any information you could give me? 

As read in a different thread by the Satija lab I need to normalise and do the DE in DESEq2 before reading into Seurat. Which I have but I am unsure how to read all this info into the CreateSeuratObject - I've only found how to read in a count matrix which of course doesn't contain any of the vst, PCA components that I'll need for the clustering! 

Thank you so much, any information would be much appreciated!

Marianne
