### ISSUE TITLE
Seurat installation failed on iMac 10.15.3

### ISSUE THREAD

**Issue by yeroslaviz** [satijalab/seurat#2609]
Hi, 

I'm trying to install Seurat on my iMac, but it fails with the folloeing error:

```
* installing *source* package ‘Seurat’ ...
** package ‘Seurat’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/usr/local/clang4/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppProgress/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c ModularityOptimizer.cpp -o ModularityOptimizer.o
clang-4.0: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from ModularityOptimizer.cpp:23:
In file included from ./ModularityOptimizer.h:3:
In file included from /usr/local/clang4/bin/../include/c++/v1/chrono:303:
/usr/local/clang4/bin/../include/c++/v1/ctime:48:10: fatal error: 'time.h' file not found
#include <time.h>
         ^~~~~~~~
1 error generated.
make: *** [ModularityOptimizer.o] Error 1
ERROR: compilation failed for package ‘Seurat’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Seurat’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Seurat’

The downloaded source packages are in
	‘/private/var/folders/sd/4b5246kd3x9_rjzd2zpxg8sr0000gn/T/RtmpV6zFlc/downloaded_packages’
Warning message:
In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status
```

trying to download the devel version directly from github (`devtools::install_github("satijalab/seurat")`) gave the same error

I have already installed the command line tools for xcode, as I thought this might be the problem.

any ideas?

thanks

----
> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night

**Comment by andrewwbutler** [comment]
Hi,

Do you need the `develop` version? If not, I would try installing from CRAN with `install.packages("Seurat")`. The mac binaries are now available there and should circumvent this compilation issue.

**Comment by akhst7** [comment]
I have the similar issue.  I'd like to use the dev version of Seurat is 3.1.3 whereas the Cran version is 3.1.0.  It looks like you have a manually installed old clang, not Apple provided (`/usr/local/clang4/`)  ?  The latest clang is 9.0.1 which you can install by Brew.  But I don't think upgrading clang will simply solve the issue here.  Whenever you see `/usr/local/clang4/bin/../include/c++/v1`, it typically means the complier can't find headers in /user/include. This is because there is no /usr/include in 10.15.  I still have not figured out what points the compiler to `/usr/include ` instead of `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include `.  It maybe  that the Makevars created by Seurat's install script, overriding my own Makevars which posits to  `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include `.  Let me know if you figure this out.

**Comment by akhst7** [comment]
The issue appears to be `CXX_STD = CXX11` in Makevars of Seurat-Masters.  If you remove it, Seurat compiles under 10.15.13 but without a **TBB malloc library.**   I wish a Seurat team could figure the way around this.
