### ISSUE TITLE
Prune.SNN=0 and large npcs required for otherwise obvious cluster to be found

### ISSUE THREAD

**Issue by heathergeiger** [satijalab/seurat#2613]
I am currently running Seurat v3.1 on a published dataset from 10X (https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.2/5k_neuron_v3_nextgem). We are testing the effects of downsampling reads, so I am working with a gene x cell matrix that comes from downsampling these reads down to 32% (~25k average reads per cell).

Anyway, my ultimate input after removing very lowly expressed genes and poor quality cells is a 15490 gene x 5866 cell matrix.

Here is my code that I ran initially on the Seurat object.

    seurat.obj <- NormalizeData(seurat.obj)

    seurat.obj <- FindVariableFeatures(seurat.obj,
        selection.method = "mean.var.plot")

    seurat.obj <- ScaleData(seurat.obj,
        features = VariableFeatures(seurat.obj))

    seurat_seed=1392

    seurat.obj <- RunPCA(seurat.obj,
        features = VariableFeatures(seurat.obj),
        seed.use=seurat_seed)

    PCs_to_use = 1:15

    seurat.obj <- FindNeighbors(seurat.obj,
        reduction="pca",
        dims = PCs_to_use)

     seurat.obj <- FindClusters(seurat.obj,
        resolution=0.6,
        random.seed=seurat_seed)

     seurat.obj <- RunUMAP(seurat.obj,
        reduction="pca",
        dims = PCs_to_use,
        seed.use=seurat_seed)`

Attached please find the resulting UMAP plot 
[5k_neuron_v3_nextgem_32pct_downsample_UMAP_vs_diff_clustering_options.pdf](https://github.com/satijalab/seurat/files/4193428/5k_neuron_v3_nextgem_32pct_downsample_UMAP_vs_diff_clustering_options.pdf), with the cluster of interest highlighted. Not only do we know from the non-downsampled data that cluster 11 should be broken into two, but it seems quite obvious from the separation on the UMAP as well.

I tried playing around with the number of PCs and the resolution parameter, but was ultimately only able to resolve this cluster into two by not only increasing npcs to 50, but settings prune.SNN to 0.

Attached please find PCA values for first 50 PCs for all cells so you can reproduce these plots:
 
[5k_neuron_v3_nextgem_32pct_downsample_PC_values.csv.gz](https://github.com/satijalab/seurat/files/4193432/5k_neuron_v3_nextgem_32pct_downsample_PC_values.csv.gz).

Anyway, I thought this behavior was a bit strange, and was wondering if you had any ideas on why this might be happening. Seems like too much pruning was happening even with the default parameter which is quite low.

**Comment by andrewwbutler** [comment]
Hi,

It seem like under these clustering parameters, perhaps there is a little more pruning of edges between cells that comprise cluster 13 and this weakens the signal separating them out.  If you wanted to investigate the pruning result in more detail, you could look at the two SNN graphs produced under your two different parameter settings and compare the edges (and their weights) between/within cells comprising these two clusters. The graphs are stored as matrices and can be accessed with the `[[` operator (e.g. `seurat.obj[["RNA_snn"]]`). 

That being said, reducing the pruning is one way to combat that but I also noticed that setting the resolution to `0.7` instead of `0.6` under your first parameter settings (PCS 1-15, default pruning) also resolved these two clusters. Typically, I tend to adjust the resolution parameter first when trying to investigate clustering results but as you demonstrate here, there are a number of other parameters that can influence things. Unfortunately, there's not going to be one default setting that works optimally for all datasets + biological questions.
