### ISSUE TITLE
combine in DimPlot not working.

### ISSUE THREAD

**Issue by ccshao** [satijalab/seurat#2645]
Hello Seurat team, 

No matter `combine = TRUE` or `FALSE`, only a single plot is returned in DimPlot. I am using the Seurat 3.1.1. Did I misunderstand the `combine` parameter?

The pbmc object is produced following the tutorial. 

```
DimPlot(pbmc, reduction = "umap", combine = FALSE)
[[1]]

DimPlot(pbmc, reduction = "umap", combine = FALSE, split.by = "orig.ident")
[[1]]

DimPlot(pbmc, reduction = "umap", combine = FALSE, group.by = "orig.ident")
[[1]]

DimPlot(pbmc, reduction = "umap", combine = FALSE, group.by = "seurat_clusters")
[[1]]
```

Thanks for looking into it.

**Comment by kaizen89** [comment]
I think only the ggplot object is combined when `combine=T`. 
From documentation
```
combine	
Combine plots into a single gg object; note that if TRUE; themeing will not work when plotting multiple features
```

**Comment by mojaveazure** [comment]
With each of your examples, you should be getting a list of ggplot objects since `combine = FALSE`; we only return a combined plot if `combine = TRUE` and there are multiple plots to combine. For example, if you run `DimPlot` with no splits or extra groups, then only one plotting representation will be needed so a single ggplot, not a combined ggplot, object will be returned.

**Comment by Xrmkm** [comment]
When I set `combine = FALSE` I still get a patchworked, combined ggplot (in a list with a length of 1)! This was never an issue with the Seurat code, so I wonder what I could be overlooking.
