### ISSUE TITLE
DotPlot Visualization 

### ISSUE THREAD

**Issue by sandbox-rgb** [satijalab/seurat#2656]
Hi, 

I really like using the Dotplot for visualization in Seurat and had some questions about how it works, and what it may be capable of. 

1. When dot plot shows percent expression for genes by size of the dot, how is percent expression calculated? Does percent expression indicate the percent expression of the gene for the cluster of genes we choose to plot on the dot plot (cells expressing genes/total cells in cluster)? What if we plot more than one cluster in one dot plot? Or if we plot one cluster subjected to different conditions all  on one dot plot (e.g. by using split by)? 

2. Is there a way to make dot plot perform hierarchical clustering like in a heatmap, such that one can pull out groups of DEGs  that cluster together for example with Cutree? I really like that dot plot  shows precent expression, which heatmap doesn’t do, and think it would be really cool if it could also do hierarchical clustering.

3. Is there a way to display  the  normalized expression value  of the gene (prior to scaling)  as a number on top of the dot of  the dot plot while  still showing the  dot color based on scaled value? 

Thanks!

**Comment by satijalab** [comment]
1. The DotPlot shows the percentage of cells within that cluster (or if split.by is set, both within a given cluster and a given condition) that express the gene. If you plot more than one cluster, different dot sizes reflect the fact that different clusters contain different percentages of cells that express the gene.

2/3-  these would indeed be interesting features, but are not something that we support (primarily because they would overcomplicate the visualization)

**Comment by Simon-Leonard** [comment]
Hi sandbox-rgb,
Just to tell you that we are working on a dot plot visualization tool with a high modularity and possibility to combine with dendrograms.
Here is the bioRxiv preprint : https://biorxiv.org/cgi/content/short/2020.04.03.023655v1
Bests

**Comment by sandbox-rgb** [comment]
Hi Simon-Leonard,

Thank you for the  preprint! I look forward to trying the new dot plot visualization tool. 

Best
