### ISSUE TITLE
RunMultiCCA() question

### ISSUE THREAD

**Issue by cimbusch** [satijalab/seurat#270]
Hello,

great the RunMultiCCA() is now available!

When running RunCCA() is was setting add.cell.id1 and add.cell.id2 to avoid duplicate cell names. With RunMultiCCA() this option does not make so much sense anymore, but there should be still an option to create unique cell identifiers? Where can I inject a prefix to the cell ids, maybe directly when creating the the Seurat object: CreateSeuratObject() ?

Cheers,
  Charles

**Comment by andrewwbutler** [comment]
We'll provide an example workflow for multiple alignment on the website in the very near future. One way to handle this though would be to prepend your unique identifiers to the cell names of the initial input matrix you pass to `CreateSeuratObject`.

**Comment by cimbusch** [comment]
Ok, I see. Yeah, just appending it to the initial input matrix is working. Thanks.

**Comment by cimbusch** [comment]
Looking forward to an example workflow, the downstream part seems to be a bit different:

> data.union <- RunMultiCCA(samples_list, genes.use = hvg.union)
[1] "Computing CC 1"
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1] "Scaling data matrix"
  |=====================================================================================================================================================| 100%
> 
> # visualize results of CCA
> # plot CC1 versus CC2 and look at a violin plot
> p1 <- DimPlot(data.union, reduction.use = "cca", group.by = "sample", pt.size = 0.5, do.return = T)
Error in `[.data.frame`(data.plot, cells.use, dim.codes) : 
  undefined columns selected
> DimHeatmap(data.union, reduction.type = "cca", cells.use = 500, dim.use = 1:9, do.balanced = T)
Error in DimTopGenes(object = object, dim.use = ndim, reduction.type = reduction.type,  : 
  Gene loadings for cca with use.full=FALSE have not been computed

**Comment by ghoshal** [comment]
Hi, 

I am having issues with RunMultiCCA as well. 

hvg.D04 <- rownames(x = head(x = D04@hvg.info, n = 5000))
hvg.D05 <- rownames(x = head(x = D05@hvg.info, n = 5000))
hvg.D06 <- rownames(x = head(x = D06@hvg.info, n = 5000))
hvg.union <- Reduce(union, list(hvg.D04, hvg.D05, hvg.D06))

# lastly, we set the 'protocol' in each dataset for easy identification
# later it will be transferred to the merged object in RunCCA
D04@meta.data[, "class"] <- "Pooled_A"
D05@meta.data[, "class"] <- "Pooled_B"
D06@meta.data[, "class"] <- "Pooled_C"


pooled_list <- list(D04, D05, D06)

pooled <- RunMultiCCA(object.list = pooled_list, genes.use = D04@var.genes, niter = 50, standardize = T, num.ccs = 3)

Error in data.use[genes.use, ] : subscript out of bounds
Called from: apply(X = data.use[genes.use, ], MARGIN = 1, FUN = var)

Thanks,

Bibaswan

**Comment by leonfodoulian** [comment]
Hi Bibaswan,

I don't know if you are informed that a new tutorial related to `RunMultiCCA()` is now available, but you might want to check it out before proceeding in your analysis. You can download the corresponding _R_ file by clicking [here](https://www.dropbox.com/s/aji4ielg8gc70vj/multiple_pancreas_workflow.R?dl=1). More information about the datasets that were used can be found in the [main tutorial page of Seurat](http://satijalab.org/seurat/get_started.html).

Hope this helps for now.

Best,
Leon

**Comment by ghoshal** [comment]
Thanks Leon. Got the code.

**Comment by lb15** [comment]
Hi!

Is there a way to add cell IDs to a current Seurat object rather than during the creation? I'm using objects updated from seurat v1, and they have been subclustered to contain only a subset of cells I'm interested in. Therefore, I'd prefer to not go back to recreating the entire object from the original matrix and redoing the subclustering, etc. I've tried manually adding cell IDs in @meta.data, scale.data, raw.data, and .data, but I still get errors related to invalid row.name length during the MergeSeurat call within RunMultiCCA. Just checking if there has been any addition to address adding the cell.ids during the RunMultiCCA call. Thanks!

Sincerely,
Lauren

**Comment by h1hui** [comment]
But how do you append cell identifiers to the initial matrix?

**Comment by yingxixu** [comment]
Hi Leon,
This is my code below:


# Determine genes to use for CCA, must be highly variable in at least 2 datasets
ob.list <- list(day0, day9, day21)
genes.use <- c()
for (i in 1:length(ob.list)) {genes.use <- c(genes.use, head(rownames(ob.list[[i]]@hvg.info), 1000))}
genes.use <- names(which(table(genes.use) > 1)) for (i in 1:length(ob.list)) {genes.use <- genes.use[genes.use %in% rownames(ob.list[[i]]@scale.data)]}


# Run multi-set CCA
T.integrated <- RunMultiCCA(ob.list, genes.use = genes.use, num.ccs = 15, add.cell.id1 = "X", add.cell.id2 = "Y")



 Thanks for your reply, and looking forward to your help.


Yingxi
 
------------------ Original ------------------

**Comment by leonfodoulian** [comment]
Hi Yingxi,

I can't see any option for `add.cell.id1` and `add.cell.id2` in `Seurat::RunMultiCCA()`. Those are options that are specific for `Seurat::MergeSeurat()`. You might want to add a prefix to your cell IDs before creating the Seurat objects. You can simply refer to issue #400 for an answer to your question.

Best,
Leon

**Comment by yingxixu** [comment]
Hi Leon,
 I have solved this problom followed issue#400, thank you so much!
Have a good day~
Yingxi
 
 
------------------ Original ------------------

**Comment by ptrcalmeida** [comment]
@Bibaswan
While using 'RunMultiCCA' I ran into an error similar to has been described in an earlier post. Can you help me?

g.1 <- head(rownames(normal1@hvg.info), 1000)
g.2 <- head(rownames(normal2@hvg.info), 1000)
g.3 <- head(rownames(tumor1@hvg.info), 1000)
g.4 <- head(rownames(tumor2@hvg.info), 1000)
hvg.union <- Reduce(union, list(g.1, g.2, g.3, g.4))

ob.list <-list(tumor1, tumor2, normal1, normal2)
lung.integrated <-RunMultiCCA(object.list=ob.list, genes.use=hvg.union, num.ccs = 15)
**Error in data.use[genes.use, ] : subscript out of bounds**

**Comment by rjtower** [comment]
I have 2 questions regarding the RunMultiCCA trying to combine 4 scRNA-seq runs.

i) First, I create a list of variable genes for each data set, then combined into a unique list. But I get script out of bounds when I run the RunMultiCCA. I found that this is because, while some genes are highly variable within 2-3 runs, that gene is not expressed in one of the runs. Can I sort my "genes.use" list by only expressed genes for each of my 4 data sets?

ii) If I manually remove non-expressed genes from my genelist, the CCA list runs fine. But when I try to check the analysis with eg. DimPlot(object = object, reduction.use = "cca", group.by = "group", pt.size = 0.5, do.return = TRUE), I get the following error:

Error in reduction.type %in% names(object@dr) : 
  trying to get slot "dr" from an object of a basic class ("list") with no slots

This was not a problem when I was doing pairwise CCA comparisons.
