### ISSUE TITLE
Question on FindIntegrationAnchor()

### ISSUE THREAD

**Issue by Crystalizeee** [satijalab/seurat#2701]
Hi.

https://satijalab.org/seurat/v3.0/integration.html

So according to the seurat integration tutorial, it is advised that the objects without `SCTransform()` run `FindIntegrationAnchor()` right after standard preprocessing (log-normalization & Identify variable features), whereas those with `SCTransform()` suggested to run `SelectIntegrationFeatures()` and `PrepSCTIntegration()` before running `SCTransform()` with normalization method = SCT.

Would you please explain why?

And what if you run the `FindIntegrationAnchor()` on the `SCTransform()`-ed objects without running the suggested functions?

Why would it be a statistically/biologically bad idea to do so?

Thanks!

**Comment by 321356766** [comment]
I would love to know the answer to this too. By accident, I have run the standard integration pipeline [FindIntegrationAnchors() and IntegrateData()] on SCTransform-ed data (objects with assay set to "SCT") and have found that integration is good and the resulting clustering appears to capture the biological differences between the cells well.

I have compared the same data set as above using the standard integration workflow (objects with assay set to "RNA") and the full SCTransform pipeline [SelectIntegrationFeatures(), PrepSCTIntegration(), FindIntegrationAnchors(), IntegrateData()] and find the outputs using the above hybrid workflow attractive. Am I missing anything? What does PrepSCTIntegration do exactly?

Thanks.

**Comment by Crystalizeee** [comment]
> I would love to know the answer to this too. By accident, I have run the standard integration pipeline [FindIntegrationAnchors() and IntegrateData()] on SCTransform-ed data (objects with assay set to "SCT") and have found that integration is good and the resulting clustering appears to capture the biological differences between the cells well.
> 
> I have compared the same data set as above using the standard integration workflow (objects with assay set to "RNA") and the full SCTransform pipeline [SelectIntegrationFeatures(), PrepSCTIntegration(), FindIntegrationAnchors(), IntegrateData()] and find the outputs using the above hybrid workflow attractive. Am I missing anything? What does PrepSCTIntegration do exactly?
> 
> Thanks.

I actually also got interesting results like this by accident. But I am worried this can false positive and not sure whether to follow up wet lab on this.

**Comment by andrewwbutler** [comment]
Hi, 

`PrepSCTIntegration` does the following things:
   
-  If `anchor.features` is a numeric value, calls `SelectIntegrationFeatures` to determine the features to use in the downstream integration procedure.

  - Ensures that the sctransform residuals for the features specified to anchor.features are present in each object in the list. This is necessary because the default behavior of `SCTransform` is to only store the residuals for the features determined to be variable. Residuals are recomputed for missing features using the stored model parameters via the `GetResidual` function.

  - Subsets the `scale.data` slot to only contain the residuals for anchor.features for efficiency in downstream processing.

We are in the process of updating many of the man pages to hopefully be more descriptive (this is from the new version that should roll out in the near future).  In short, yes, it's recommended to run these before integrating sctransform normalized objects.
