### ISSUE TITLE
question about FindMarkers

### ISSUE THREAD

**Issue by ahmedabbas81** [satijalab/seurat#2708]
Hello,

Is there anything wrong in the following command?

`young_markers <- FindMarkers(male.integrated, ident.1 = c("young"),ident.2 = c("old"),group.by = 'tech',min.pct = 0,test.use = "MAST",logfc.threshold = 0.0)
`
It is giving me wrong calculations for avgLogFc and pct1 and pct2. I calculated them myself and got different results. My calculations are exactly similar to FindMarkers calculations in other cases in which I group by "celltype". That's why I trust my function for calculating logFC. I doubt if there is something wrong in the above command I wrote.

Thanks

**Comment by satijalab** [comment]
The command is correct, i'd encourage you to make sure that you are testing using the RNA assay  (instead of the integrated assay, which may be set by default). I'd also suggesting making sure that 'tech' is indeed the right variable to group by, (young and old don't seem like different technologies).

If that does not solve the problem, please reopen with a more detailed description of the type of discrepancies you are seeing.
