### ISSUE TITLE
Unexpected behaviour of sampleUMI

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#2734]
```
object <- subset(object, subset=nCount_RNA>= 1000)
sampled <- SampleUMI(object@assays$RNA@counts, max.umi = 1000, upsample = F);dimnames(sampled) <- dimnames(object)
min(Matrix::colSums(sampled))
> 919
```
I expected that the number of UMI would be 1000 for every cell but it does not seem to be the case.
Is this expected?
Also the dimnames are not preserved if not set manually, and I think that the in the function there might be a little error, when setting ` dimnames(new_data) <- dimnames(data)`. If `upsampling=F` the cell names will be different in the 2 objects as cells with less than `max.umi` will be removed. Can someone please verify this?

**Comment by satijalab** [comment]
You are correct - SampleUMI does not guarantee that each cell will have exactly 1000 UMI, but it will perform random downsampling with this goal (since there is randomness in the procedure, we can't get exactly 1,000 UMI each time)

Thats a good catch with upsampling=F requiring a renaming. We will fix (@andrewwbutler)

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting. There is a small bug but not exactly what is being described here. `SampleUMI` will always return a matrix that is the same dimensions as the one in the input, regardless of `upsampling` or `max.umi` parameter settings. The bug is that the dimnames are only being carried over if you provide a vector to `max.umi` (specifying for each cell, what the `max.umi` should be), not when it's only a single value. 

This is easy to add back after running as you tried to do here. However, `dims(sampled)` is not guaranteed to be the same as  `dims(object@assays$RNA@counts)`. `dims(sampled)` returns the dimensions of the `@data` slot of the `DefaultAssay(object)`, not the dims of the RNA assay counts slot. One example where they would differ would be when there is filtering that has happened as you mentioned that would make the counts and data slots have different dimensions (another would be if RNA is not the default assay). The following code should work to do what you wanted:

```R
object <- subset(object, subset=nCount_RNA>= 1000)
orig.counts <- GetAssayData(object[['RNA']], slot = "counts")
sampled <- SampleUMI(orig.counts, max.umi = 1000, upsample = F)
dimnames(sampled) <- dimnames(orig.counts)
```

Will post back here when we've restored the names for this case (allowing you to remove the last line).

**Comment by andrewwbutler** [comment]
Updated on the latest  `develop` branch. Installing that version should resolve the issue but feel free to reopen if not.

**Comment by kaizen89** [comment]
Thanks @andrewwbutler, however now I am not sure what is the function of `upsample`. What happens to the cells with much less than `max.umi`? Could you please clarify this? Also, I am not able to see any example where the object `counts` and `data` would have different dimensions. Can you pleae give an example? Thanks

**Comment by andrewwbutler** [comment]
The `upsample` parameter will randomly add counts to non-zero count genes in cells with fewer than `max.umi` such that there will be approximately `max.umi` counts in every cell. 

Under most common workflows, `counts` and `data` will likely have the same dimensions but it is not something that we explicitly require in the object structure. You could for example want to keep a copy of the entire raw data matrix in `counts` but only work off of a filtered set of genes in `data`.
