### ISSUE TITLE
SCTransform meta.features output

### ISSUE THREAD

**Issue by hmbaghdassarian** [satijalab/seurat#2751]
Hi all, 

Is there a description of the meta.features output in the SCT assay from SCTransform() anywhere? Specifically, what each of sct.gmean, sct.variance, sct.residual_mean, and sct.residual_variance are?

I am hoping to quantify variance or coefficient of variation for my genes and I'm wondering whether these would be appropriate metrics to do so. Given the description in the [SCTransform vignette](https://satijalab.org/seurat/v3.1/sctransform_vignette.html) under "Where are normalized values stored for sctransform?" and my understanding of the paper, I expected them to be related to the counts matrices in the SCT assay, particularly the scale.data slot. But I am unable to find a relationship between the counts matrices and the values provided in meta.features.  For example, having set `variable.features.n` equal to the number of features in the `seurat_object@assays$RNA@counts` slot when running SCTransform() so as not to filter out any genes, I'm finding that `rowMeans(seurat_object@assays$SCT@scale.data)` is not the same (nor does it have the same rank-order) as either sct.gmean or sct.residual_mean. I also get the same for looking at `rowVars` in comparison to sct.variance and sct.residual_variance. 

Thanks! 

P.S.: I have really enjoyed using Seurat and appreciate the extensive documentation and effort you all have put to answer everyone's questions :)

**Comment by timoast** [comment]
@ChristophH are you able to answer this?

**Comment by satijalab** [comment]
I think the best response is to view the code for the sctransform package, so you can see exactly how all these variables are calculated.  

This is the repo here:
https://github.com/ChristophH/sctransform

You will predominantly be interested in the vst function,  which describes most of the variables you are discussing here.

Last thing-  after vst is run, we do center the Pearson residuals in Seurat (so that they can be used as input to PCA), which is why the values in the scale.data slot are slightly shifted.

**Comment by yuhanH** [comment]
Hi, 
the value stored in the meta.features is used for SCTransform internal model, and sct.gmean, sct.variance, are calculated from RNA assay. 
sct.residual_mean and sct.residual_variance are calculated before `ScaleData`
To quantify the variance of your genes, you can calculate variance from SCT scale.data which is residual value.

**Comment by freddie090** [comment]
Hi - sorry, I'm still a bit confused re the `ScaleData` slot. 

From looking at a lot of the papers that discuss the different ways to perform a VST (e.g. https://www.biorxiv.org/content/10.1101/2021.07.07.451498v1.full.pdf) I can see that I can recreate the plots that show 'mean expression per gene' on the x axis and, 'pearson residual variance' on the y axis by using the residuals found per-gene in the `seurat_SCT@assays$SCT@SCTModel.list$model1@feature.attributes` slot. 

However, if I manually calculate the variance per-gene from the `ScaleData` slot from the SCT assay, this returns different values... what is the difference in the Pearson Residual variances found in the `feature.attributes` slot and those located in the `ScaleData` slot?

(I am interested because I would like to calculate the Pearson Residual variances per gene for my entire experiment, and then re-calculate them when sub-setting cells from different samples).

Thanks for any help
