### ISSUE TITLE
Problem with UMAP visualization

### ISSUE THREAD

**Issue by LNeuro** [satijalab/seurat#2784]
Dear all - 

I am processing a single-nucleus RNA-seq dataset of about 70,000 cells and I'm struggling with the UMAP not seeming to accurately reflect the clustering.  Different cell types are clustered for the most part, but there is a substantial number of cells/data points that are either too far out in space or even, in some cases, associated with seemingly completely different clusters (see attached). I've messed around with the resolution (res), dimensions (dim), and the min.dist but I still have this issue to a lesser or greater extent. Any thoughts on why a cell that is called one cell type would  appear to cluster with another cell type on a UMAP?

![Beta2_UMAP_Opto_umap6](https://user-images.githubusercontent.com/62312672/77823285-55032780-70d0-11ea-9688-42c4df5bd09d.jpg)
cluster with another cell type on a UMAP?

**Comment by KinSimon96** [comment]
It can come from different problems:

1) Low depth-sequencing: some markers could not be detected, so same cells can have lot of heterogeneity.

2) Doublets: 2 cells came in one drop, so the sequencing detected both RNA from first and second cell. Packages exist such as DoubletFinder to fix this problem.

3) Contamination: cellular lyses may cause free RNA travelling into the liquid, which induces general marker(s) contamination for lot of your cells. Packages such as SoupX are very helpful for this. (I've decontaminated 5 tumoral datasets yesterday with this package)

4) You can remove poor quality cells with this function:
`UP <- subset(UP, subset = nCount_RNA > 750 & nCount_RNA < 30000)`

Below 1000 RNA counts, it can be considered as poor quality cells. Above 30 000 (in my case, for yours, watch your own violin plot), it can be considered as doublets so it has to be removed.

You can also try tSNE instead of Umap, or the Monocle3 package to see if you have better results.

**Comment by LNeuro** [comment]
Dear Kin, 

Thank you!  I have already removed doublets using Doublet Finder and I've filtered out low quality cells.  I do, however, realize that our sequencing depth isn't great here and these are nuclei, not cells.  I will try out Monocle3. Thanks again for the advice. Lucas
