### ISSUE TITLE
Gene Expression Filtering After Using Sctransform

### ISSUE THREAD

**Issue by iSinedeus** [satijalab/seurat#2802]
Hello,

I am trying to subset some of my cells based on their gene expression. I have an integrated dataset of 10 samples that was processed through the sctransform workflow and I have subset some of the clusters. I would now like to subset this further by gene expression within these clusters. I am trying to use the following code:

Idents(s10_CD68, WhichCells(s10_CD68, slot = "counts", expression = CD3E <= 0 & CD79A <= 0 & CD3D <= 0 & MS4A1 <= 0 & CD3G <= 0)) <- 'cd68_clean'

But I receive this error message:
Warning: Found the following features in more than one assay, excluding the default. We will not include these in the final dataframe

I have tried using: slot = "data.frame" to replace counts and it appears to work but when I reprocess this data I still see a few cells expressing these markers on my vlnplots although I believe there should be essentially none of these cells. I believe this difference is due to the difference in scaling of the data but I don't know if there is a way to correct for this? I ultimately want to remove cells with non-zero expression of these genes but it appears that the "zero" is defined differently based on how the data is scaled. I appreciate any help advice anyone has to offer.

Thank you

**Comment by andrewwbutler** [comment]
Hi,

This issue is arising most likely because some of the features in your expression above are not found in the `integrated` assay which is set as the default assay after running integration. This can happen when these features aren't in the `features.to.integrate` parameter (which defaults to `anchor.features`). You can either rerun `IntegrateData` and make sure that those features are included in `feature.to.integrate` or change you're filtering expression to pull from a different assay (e.g. `SCT`) explicitly by appending the `Assay` key to the front of the feature name (e.g. `"sct_CD3E"`). If you want to filter explicitly for no detected counts, you could also just switch the default assay to "RNA" before running the line above.
