### ISSUE TITLE
Gene expression scatterplots show strange straight line with Integrated data

### ISSUE THREAD

**Issue by Lesdormis** [satijalab/seurat#2805]
Hi Seurat Developers,

I used the SCTransform workflow to integrate my 4 sample datasets. 
And after integration, I was checking the expression value by using the integrated@data.
But I saw a very strange straight line like a cutoff in the scatter plot. 
Could you kindly why is that? And how it comes?
![image](https://user-images.githubusercontent.com/30546732/78254015-46978000-74c3-11ea-9d59-6169dae05413.png)
![image](https://user-images.githubusercontent.com/30546732/78254022-4c8d6100-74c3-11ea-9265-d9d2c2c847e8.png)

Thanks in advance!

**Comment by timoast** [comment]
Hi, I believe the line of values you see here is due to the fact that residuals are clipped at a certain value in SCTransform (default = [sqrt(n/30)](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R#L1197)). You can change the clipping threshold using the `clip.range` parameter in SCTransform.

The reason you have some points that go above this range is because you're plotting the integrated data, so some cells in the dataset have had a correction vector applied that moves the value above the clipping threshold.
