### ISSUE TITLE
RNA splicing isoform

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#2813]
Hi, I wanna research the RNA isoforms. And I've classified the cell types in my 10x scRNA seq data.
When I search the software/package for RNA isoform, I found that none of them (Expedition, brie,  AltAnalyze, SingleSplice, and etc.) mentioned the method combining their output file and Seurat.
Hence, does anyone know how to analyze RNA isoforms in Seurat?

**Comment by satijalab** [comment]
We don't have any examples on our website of how to do this yet, but please stay tuned. In the mean time, the Kallisto/BUSTools workflow supports isoform level quantification (https://bustools.github.io/BUS_notebooks_R/10xv3.html) and can be loaded into Seurat

**Comment by grimwoo** [comment]
@satijalab Thanks a lot!

**Comment by lambdamoses** [comment]
I wrote that notebook. @satijalab The 10x v3 kallisto|bustools notebook you referred to is not meant for isoform level analysis. For 3' based data, like 10x, you need to use the TCC matrix rather than the gene count matrix as in that notebook. The equivalence class in the TCC matrix can preserve some isoform information. We have assigned a student to write a new tutorial for TCC matrices.

**Comment by nbahlis** [comment]
Hi Lambdamoses, is the tutorial using TCC matrices available , thank you

**Comment by lambdamoses** [comment]
Sorry, not yet.

**Comment by gadepallivs** [comment]
@lambdamoses Hello, is your tutorial for isoform analysis available, how do we generate the TCC matrix ? Is there an acceptable pipeline that we can use 10x 3 ' data ?
