### ISSUE TITLE
merging Seurat objects after SCT

### ISSUE THREAD

**Issue by anoronh4** [satijalab/seurat#2814]
I am trying to merge data objects after normalization. I previously ran SCTransform on all my samples in the same way. However, I noticed in my first run that i forgot to run `merge` with `merge.data=T`. So I fixed an reran...however there was absolutely no change to my UMAP. 

Does `merge` work with SCTransform normalized data? and if it does, what am I missing? Should I run `FindVariableFeatures`,`RunPCA`,`FindClusters` and `RunUmap` all with `assay="SCT"`?

update: parameter `assay="SCT"` did not help (probably because my default assay is already "SCT"). so my question is still about whether `merge` still works with `SCTransform`

**Comment by yuhanH** [comment]
Hi,
`merge.data=T` is a default setting, so usually you don't need to set it. 
After you merge SCT normalized objects, the VariableFeatures of the  merge object is not set. However, you should not run `FindVariableFeatures`, because it is designed for the LogNormal data.
The features in the merged SCT scale.data are the variable features. You can set those genes as the Variable features, and `RunPCA` for the downstream analysis. 
If it doesn't solve your question, I will reopen this issue.

**Comment by vlcm2019** [comment]
Hi, 
How do i set the variable features to scale.data feature after merging SCT normalized objects? 
Thanks.

**Comment by yuhanH** [comment]
HI, 
You can set the genes in the scale.data to the variable genes by `VariableFeatures()`.
For example.
```
`VariableFeatures(object[["SCT"]]) <- rownames(object[["SCT"]]@scale.data)`.
```

**Comment by vlcm2019** [comment]
Hi Yuhan,

Thank you for your help.

**Comment by xjs1996** [comment]
Hi Yuhan,
I have same questions:  In the merge step which were after SCTransform, Peason residuals will be recalculated or not?  The gene number in scale.data of SCT assay is less than the union of hvgs of data paticipated in merge step, so how you choose these genes to keep? If it is ok not to do scale of merged data before PCA?

Best regards,

XJS

**Comment by BenjaminDEMAILLE** [comment]
Hi ! 

After merging does the variable feature in the scale data slot are the intersect or the union of the variable feature of the different sample ? 

thanks
