### ISSUE TITLE
Potential issue with scaling data and PCA

### ISSUE THREAD

**Issue by orrzor** [satijalab/seurat#282]
Hi Seurat team!

I have a potential concern with `ScaleData()` and how the resulting `object@scale.data` works with `RunPCA()`. I noticed after running `ScaleData()`, that the mean gene expression for each gene across all cells is sometimes not 0. I would expect it to be 0 after the mean-centering transformation. I realized this occurs because of the `scale.max` parameter in `ScaleData()`, and when I increased this parameter up from 10, the mean gene expression was now 0.

My concern is that the gene expressions in `object@scale.data` are not necessarily all mean-centered by default, depending on how `scale.max` is set. The PCA needs the expression data to be mean centered. I looked at the `RunPCA()` code and it looks like `RunPCA()` and `PrepDR()` use the `object@scale.data` as is. Furthermore, the default behavior of `irlba()` is to not center the data. Am I missing something here, or may the gene expression data going into the PCA actually not always be centered? Thanks for clarifications!!

**Comment by leonfodoulian** [comment]
Hi,

Were you using UMI or (non-UMI) count data when running your tests?

Best,
Leon

**Comment by orrzor** [comment]
Hi Leon,

Thanks for getting back to me. I was using UMI data (10x), and after scaling, some of the gene expression values got set to max.scale (10 in this case). I then noticed that the mean expression for those genes was often not 0, but still pretty close ( < 1 typically). I think it's a small problem, but maybe worth indicating in the function documentation that the genes may not be actually centered after running `ScaleData()`. Thanks, Orr

**Comment by leonfodoulian** [comment]
Hi Orr,

Typically, `scale.max` is set to 10 by default, except if you are using a non-linear model to regress out your latent variables. In this case, `scale.max` is automatically set to 50. When I first started using the function, I tended to explicitly specify all arguments _as is_ when running the function (a way for me to tweak the code and get familiarised with the function), and observed a similar behaviour to what you just described. And this was lost when I had run the function without specifying `scale.max` when `use.umi` was set to `TRUE`. Going back to the source code, I realized that this was due to the fact that the default value of `scale.max` in this case was set to 50, and not to 10. For more information, please check [lines 503 to 506 in preprocessing.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/preprocessing.R#L503-L506). I am therefore wondering whether you did something similar to what I did, that is specified `scale.max = 10` and set `use.umi = TRUE`.

Best,
Leon

**Comment by satijalab** [comment]
This is a fair question, we perform scaling before clipping the values at scale.max. Therefore, it is possible that the data means will have (extremely) slight deviations from 0. My hesitancy for changing this (and rescaling after clipping) is that if we do, then the value of scale.max will affect all scaled expression levels, not just the ones that are clipped - this could cause more significant artifacts going forward. If you identify cases where our current approach gives suboptimal biological results, let us know, and we will reconsider.
