### ISSUE TITLE
Cannot set do.scale=F in RunCCA call (for automatic call to MergeSeurat)

### ISSUE THREAD

**Issue by sriesenfeld** [satijalab/seurat#284]
I want to be able to call RunCCA without having the automatic call to MergeSeurat try to re-normalize the data or run ScaleData on the merged object. The reason I don't want ScaleData to get automatically called is that it runs on all the genes, which makes the object huge (since the matrix is not sparse anymore), and it also takes a while. Since only variable genes are used for a lot of the analysis, it doesn't make sense to me to store a scaled matrix of all the genes. 

However, when I try to set do.scale=F in the arguments for my call run RunCCA, which the documentation says get passed to MergeSeurat ("Extra parameters (passed onto MergeSeurat in case with two objects passed"), I get an error:

## Example call:
ilc <- RunCCA(object = ob.l[["v1"]], object2 = ob.l[["v2"]], genes.use = hvg.union, do.normalize=F, do.scale=F, do.center=F, add.cell.id1="_v1", add.cell.id2="_v2")

## Returns:
Running CCA
Merging objects
Error in MergeSeurat(object1 = object, object2 = object2, do.scale = FALSE,  : 
  formal argument "do.scale" matched by multiple actual arguments

My guess is that do.scale is being set explicitly to True when RunCCA calls MergeSeurat, which would then conflict with the argument that gets passed as an extra parameter, but I haven't confirmed this.

**Comment by leonfodoulian** [comment]
Hi,

Looking at the source code of `RunCCA()`, `do.scale` is set to `FALSE` in `MergeSeurat()`. For more information, please check [lines 633 to 639 in dimensional_reduction.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/dimensional_reduction.R#L633-L639). The error you're getting is due to the fact that you are specifying `do.scale = FALSE`, and this is being passed to the `MergeSeurat()` function, which already has this argument set. So the argument is being matched multiple times, hence the error. Setting `rescale.groups = FALSE` will prevent the function from re-scaling the objects. This argument is set to `FALSE` by default, so you've got nothing to worry about. For more information on what this argument does, and how it is handled by the function, please refer to [lines 584 to 606 in dimensional_reduction.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/dimensional_reduction.R#L584-L606).

Hope this helps!

Best,
Leon

**Comment by satijalab** [comment]
Hi Sam. We actually run a ScaleData command right after MergeSeurat. We could modify to make this optional, and could be useful especially for larger datasets. Please feel free to modify and submit a pull request :)
