### ISSUE TITLE
Error: package or namespace load failed for ‘Seurat’ in .doLoadActions(where, attach):

### ISSUE THREAD

**Issue by urielrosen** [satijalab/seurat#2853]
Hi,

we use on rstudio with R 3.6.0  , can you please suggest what to do to solve this ?

library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package RcppAnnoy: loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "AnnoyAngular": cannot allocate vector of size 350131.9 Gb

thanks.

**Comment by moschmi** [comment]
same here! With R 3.6.3

**Comment by mojaveazure** [comment]
Are you on macOS? It seems as though macOS has issues with versions of RcppAnnoy when installed from source instead of from the binary. If you are on macOS (or Windows, since this issue could appear there as well), can you ensure that you are installing from the binary instead of from source? https://github.com/satijalab/seurat/issues/2275#issuecomment-613194096

**Comment by moschmi** [comment]
I am on Windows 10. Otherwise Seurat works fine. Looks like the package AnnoyAngular doesn't work on version 3.

**Comment by urielrosen** [comment]
Hi,

I reinstalled seurat which solved the issue.

**Comment by mojaveazure** [comment]
@moschmi I'm unable to reproduce this on Windows 10; I would recommend reinstalling Seurat, AnnoyAngular, AnnoyAngular's dependencies, and if worst comes to worst, R and Rtools
![image](https://user-images.githubusercontent.com/11035068/80140097-52bfac00-855c-11ea-897a-411aa03e6bb9.png)

**Comment by Jonyls** [comment]
@urielrosen How do you solve the problem  on Win10？

**Comment by MichaelPeibo** [comment]
same problem here.

**Comment by ZeitgeberH** [comment]
Same problem. I am on Windows 10.
install.packages("Rcpp")  solved the issue.

**Comment by mauritsunkel** [comment]
In the end, I had to attach the (Seurat) package through `library(Seurat)` in my package function in order to make it work. (Maybe attaching AnnoyAngular would similarly work)

I also tried:
- Reinstalling: Rcpp, RcppAnnoy, Seurat
- Adding '@importFrom RcppAnnoy AnnoyAngular' the specific function in my package.
- Adding '@import RcppAnnoy' the specific function in my package.
- Adding '@import Seurat' for the specific function in my package. 
- Adding '@require RcppAnnoy' for the specific function in my package.  
- Adding '@require Seurat' for the specific function in my package. 
- Combinations of the above

**Comment by AmirKhsrv** [comment]
> Hi,
> 
> we use on rstudio with R 3.6.0 , can you please suggest what to do to solve this ?
> 
> library(Seurat) Error: package or namespace load failed for ‘Seurat’ in .doLoadActions(where, attach): error in load action .**A**.1 for package RcppAnnoy: loadModule(module = "AnnoyAngular", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "AnnoyAngular": cannot allocate vector of size 350131.9 Gb
> 
> thanks.

Just load the monocle package (package(monocle)). this worked for me

**Comment by gsx-ucas** [comment]
Same problem. 
`install.packages(c("RcppAnnoy", "RcppHNSW"))` solved the issue.

**Comment by yjgh19z** [comment]
> Same problem. I am on Windows 10. install.packages("Rcpp") solved the issue.

I encountered the same problem after replaced the old hard drive with a new one and moved all the files from the old to the new one,  install.packages("Rcpp") solved the issue.
