### ISSUE TITLE
Gene/Feature Metadata?

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#2855]
Hello,

In the seurat object, genes/features are simply the rownames on the matrix.  Cells are colnames, and there is a slot that specifically holds a dataframe for sample metadata.  The genes can also have attributes that have value in storing.  For example, explicitly tracking gene symbol, EnsemblId, etc. Is there a canonical way to track this ancillary gene data using the seurat object?  

Simply tracking the data alone in a specific slot would have utility. If there was an official feature-metadata dataframe, that could lead into some useful features, like allowing separate gene name/label on the features for plotting (the user-friendly label on many genes isnt appropriate as the rowname on a matrix).  Much like how one can specify sample metadata fields for group/split, it would be useful if one could specify the feature metadata field for labeling on the plotting functions.

**Comment by mojaveazure** [comment]
Feature-level metadata is associated with each individual assay. To access feature-level metadata, simply use the double bracket `[[` subset operator on the `Assay` objects, similar to access cell-level metadata on the `Seurat` object. You can set feature-level metadata using the double bracket `[[<-` assignment operator or `AddMetaData` on an `Assay` object

```R
# Access cell-level meta-data
head(pbmc_small[[]])

# Access feature-level meta-data
head(pbmc_small[["RNA"]][[]])
```

Remember, when using `AddMetaData` on an `Assay` to add feature-level metadata, an `Assay` object is returned. Be sure to not overwrite your `Seurat` object. For more details, please see the documentation of [`AddMetaData`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/AddMetaData)

We do not yet have the ability to label plots based on feature-level metadata. However, since most plotting functions return ggplot objects by default, you can simply modify them using ggplot2 functions as you see fit.

**Comment by hartmannmark** [comment]
For a beginner, can anybody provide an example how to concretely do this, e.g. for a heatmap and a featureplot?

`DoHeatmap(object, features = c("ENSG00000197540", "ENSG00000115523", "ENSG00000105374"))`

`FeaturePlot(object, features = c("ENSG00000197540", "ENSG00000115523", "ENSG00000105374"))`

If I add e.g. 
```
+ theme_void() + 
  theme(legend.position = 'none') +
  ggtitle("symbol") +
  theme(plot.title = element_text(color="darkred", hjust = 0.5, size=36, face="bold"))
```
only the last UMAP of the multi-feature plot is modified.

How can I exchange the IDs in the heatmap?

**Comment by timoast** [comment]
@hartmannmark please see the patchwork package for information on how to modify all plots: https://github.com/thomasp85/patchwork

**Comment by sparsepix** [comment]
While gene-level metadata can be written manually, the handling by Seurat is very inconvenient. 
- It is lost every time you perform an operation such as integration. 
- It makes a lot of sense to keep row names to ensemble IDs as the R data frame doesn't allow duplicate row names and there will be some ambiguity with the output of many aligners that score more than just protein-coding genes. Like that, however, any plots regarding features can't be accessed by symbol conveniently. 
Is there a general reason for the absence of strong gene-level metadata support like in AnnData that I just haven't thought of?
