### ISSUE TITLE
Using parallelization for FindSpatiallyVariableFeatures

### ISSUE THREAD

**Issue by stephenwilliams22** [satijalab/seurat#2856]
I'm running `FindSpatiallyVariableFeatures` on a dataset that is taking a very long time to process. I killed the process after 1.5hrs.
```
spatial_182963 <- FindSpatiallyVariableFeatures(spatial_182963, assay = "SCT", 
                                                features = VariableFeatures(spatial_182963)[1:1000], 
                                                selection.method = "markvariogram")
```

I noticed in the source code that there is a mention of `nbrOfWorkers` in the `RunMarkVario` function def.
https://github.com/satijalab/seurat/blob/spatial/R/spatial.R#L1410

I next ran the same code as above but with 

```
library(future)
plan("multiprocess", workers = 7)
plan()
```
and the process only took about 13 min. 

Because this doesn't seem to be documented I was wondering if you have tested this scenario and if so if there were any concerns with parallelization in this function.

**Comment by andrewwbutler** [comment]
Hi Stephen,

Yeah, parallelization makes sense here because you're computing these statistics for each gene independently so there shouldn't be any differences in the results, just runtime as you noted. If you are noticing differences though, please let us know and I can look into it. 

You can also give the `moransi` option a try for `selection.method` which we use in the slideseq tab on the spatial vignette for a more efficient option when you have lots of cells/spots.

**Comment by stephenwilliams22** [comment]
HI Andrew,
This all makes sense. Thanks for the info!
