### ISSUE TITLE
DoHeatMap

### ISSUE THREAD

**Issue by bioryguy** [satijalab/seurat#287]
I'm having two problems with the DoHeatMap function but maybe they're caused by the same issue. I'd like to create a heat map of my dataset (cells) using a list of genes of interest. I've defined the list and executed the function like this:
```R
heat <- c("Gene1", "Gene2", "Gene3")
doHeatMap(cells,genes.use = heat,slim.col.label = TRUE,remove.key = TRUE)
```

My first problem is that this code produces the error:
> Warning message:
> 'doHeatMap' is deprecated.
> Use 'DoHeatmap ' instead.
> 

However when I execute this code with DoHeatMap I receive the error:
> Error in DoHeatMap(cells, genes.use = heat, slim.col.label = TRUE, remove.key = TRUE) : 
>   could not find function "DoHeatMap"

The second problem is that running the code as written above produces a heatmap, but without several of my genes of interest as defined in the list. I've checked to make sure that those missing genes are in my dataset, they are and I can produce FeaturePlots for them. I've updated all of my packages to the most recent. I'm not sure what to try from here.

Much appreciated,
Ryan

**Comment by bioryguy** [comment]
Also, I was using one version old of both R and RStudio. However, updating both did not fix the issue.

**Comment by leonfodoulian** [comment]
Hi Ryan,

I can maybe help you with your second issue. `DoHeatmap()` plots scaled gene expression levels, which is the default setting of the function with `use.scaled = TRUE`. My guess is that those genes that get omitted from the plot are absent from your `object@scale.data`. One way to check this is by running the following:

```R
# Get vector of genes present in object@scale.data
heat[heat %in% rownames(object@scale.data)]

# Get vector of genes absent from object@scale.data
heat[!(heat %in% rownames(object@scale.data))]
```

If you have computed `ScaleData()` on your `object@var.genes`, you might want to include those other genes as well in order to be able to plot them. Otherwise, you can plot non scaled data, by setting `use.scaled = FALSE`, but this dramatically changes the aspect of the plot, and renders gene expression differences between the clusters difficult to grasp. 

Best,
Leon

**Comment by satijalab** [comment]
Please check the capitalization in the DoHeatmap call

**Comment by bioryguy** [comment]
Sorry I didn't get back to this sooner, I've been in a location without internet access for the last several days.

Leon,
You are absolutely correct, those genes were not in my `object@scale.data`. I noticed that they also were not in my var.genes by modifying your commands above to:
`#get vector of genes present in object@var.genes
heat[heat %in% rownames(object@var.genes)]`
When I used the `ScaleData` command earlier in my analysis I used the `genes.use = object@var.genes` argument so those genes were not included in object@scale.data.
So I was able to create the figure as intended with all genes included, and as far as I can tell there's nothing wrong with this approach, by creating a new Seurat object and leaving the `genes.use` argument at default `object@data`. Then I created the heat map off of that new object.
`dta <- ScaleData(object = object, vars.to.regress = c("orig.ident", "nUMI"), model.use = "negbinom")
doHeatMap(dta, genes.use = heat, slim.col.label = TRUE, remove.key = FALSE)'

Thanks for the help!

satijalab,
I suppose it's not terribly important because I was able to get my desired figure. However correcting the capitalization did not fix the problem here, as I stated in my original post. Using the current command still produces the same error message.

> Error in DoHeatMap(cells, genes.use = heat, slim.col.label = TRUE, remove.key = TRUE) :
could not find function "DoHeatMap"

I'm not sure if that's important enough for you to reopen this issue or not but thank you for your consideration either way.

**Comment by leonfodoulian** [comment]
Also, using the latest function name allows you to use the up-to-date function, instead of the deprecated one. This is advantageous in cases where new features are implemented or bugs are fixed.

Best,
Leon

**Comment by bioryguy** [comment]
Ah, excellent! Thank you both so much for all the help Leon and Rajul.

**Comment by hekselman** [comment]
I have the same problem, but the thing is, I can't show the same gene more than once.
One would say that it's not needed, but because of this, I need to decide which cluster gets which gene.

For instance, I have 7 clusters, 2 of which upregulate the same marker, and I want to show that this gene is related to both clusters, when I show the top highly expressed genes.
What should I do, if I want to show the same gene more than once?
