### ISSUE TITLE
Integrating data and embed new data onto existing low-dimensional embedding

### ISSUE THREAD

**Issue by danhtruong** [satijalab/seurat#2886]
Hello.

Has there been any work been done on embedding the query cells onto the existing reference map? At some point, you would have a standard reference map/atlas that can be used for comparison without changing the original structure of the embedding. I have been trying to figure out a way to project the new data onto the reference using known methods but have had no luck.

Are there seurat functions that I missed that can do this?

**Comment by KinSimon96** [comment]
I'm not expert but i don't think this is relevant, because your clusters are built from highly variable features present in your cells. Adding new data provides new cell information, so will obviously change the original structure. 
Maybe it is still possible, but it would include a space constraint to your new cells, which would induce a lake of relevance. 

Don't hesitate to correct me if i'm wrong!

**Comment by satijalab** [comment]
Thanks very much for your question, we don't support this at the moment but please stay tuned!
