### ISSUE TITLE
sctransform after dataintegration

### ISSUE THREAD

**Issue by ctoen** [satijalab/seurat#2899]
Dear Seurat team,

Thank you for developing a great and well documented tool for sc analysis! 

I've been struggling with an issue that has been discussed in several post discussed already and I'm sorry for bringing it up again but I would really appreciate your help on how I can continue with SCTransformed data after data integration. 

So I am using SCTransform to separately normalize several Cel-seq2 datasets,
and than I am following the tutorial about PrepSCTIntegration. PCA, UMAP / tSNE and clustering were calculated by setting the new "integrated" assay as default assay. 

As SCTransformation looked better than lognormalization for the individual datasets, I would like to continue with SCTransformed data after integration as well. My question is:

1. Is this allowed and statistically ok at all?
2. If yes, I would expect I would have to run SCTransform on the raw counts again but then as a whole instead of for every experiment separately. Is this correct? What do you recommend?  Should I run SCTransform again or can I use the data from the [["SCT"]] assay that were calculated for each experiment separately?
3. And if I have SCTransformed data that I can continue with after DataIntegration, which dataslot should I use for DE gene calling? The [["data"]] with corrected counts or the [["scale.data"]] with pearson residuals (I read in closed issue #1767 that for the SCTransform workflow _the absolute best way to do this is to run DE on the pearson residuals themselves, which are stored in object[["SCT"]]]@scale.data_).
4. And which slot can I use for heatmaps and featurePlots? If  DE gene calling and heatmap plotting are performed on the [["SCT"]]]@scale.data, what does logFC and what doe the units in the heatmap represent?

Again sorry for bringing this up again, I hope you can help me out here. 

Best wishes,
Christa

**Comment by satijalab** [comment]
1. You can use the corrected Pearson residuals (stored in the scale.data slot of the integrated assay) for joint analysis, like PCA and clustering

2/3: For DE gene calling, you can use the original SCT assay (or even the original RNA assay). You should never use integrated/corrected values when performing DE.

We typically use the data slot instead of scale.data. Its a complicated issue, and I know that in #1767 I suggested the potential use of running DE directly on the Pearson residuals. There are advantages statistically to this in principle, but there are also caveats (for example, Pearson residuals run on very different technologies may not be directly comparable). If you do run DE on the scale.data slot (for any assay), the logFC values are not meaningful.

4. We typically use the scale.data slot for heat maps and the data slot for Feature/Violin plots.

We recognize these issues are quite complex and difficult to work through , and are in the process of writing an FAQ to help advise.
