### ISSUE TITLE
FindMarkers not working with list of features

### ISSUE THREAD

**Issue by ph329** [satijalab/seurat#2900]
Hi,

I'm trying to use FindMarkers to look for differential expression of a list of genes between clusters. I'm inputting the gene list as a character vector as the "features" variable, but FindMarkers is returning a list of all genes differentially expressed between the two clusters, not my genes of interest. Looks like it might be a bug? Or is there a different way I should be formatting the "features" gene list?

Thanks!

**Comment by timoast** [comment]
Can you include the code you're running?

**Comment by ph329** [comment]
Sure, it's pretty basic:

`features <- c("rp2", "tbx1", "EGFP")
features.markers <- FindMarkers(seurat_obj,
                                ident.1 = "cluster_ident",
                                features = features,
                                test.use = "DESeq2")`

The output is the same whether the features variable is set or not.

**Comment by timoast** [comment]
DESeq2 requires all genes to estimate the dispersion parameter, so running DESeq2 with a subset of genes is disabled in FindMarkers (https://github.com/satijalab/seurat/blob/master/R/differential_expression.R#L482-L487). If you choose a different test you'll be able to run with a smaller set of features. Keep in mind that DESeq2 was designed for bulk RNA-seq data rather than single-cell RNA-seq data.
