### ISSUE TITLE
DotPlot cannot function...

### ISSUE THREAD

**Issue by AndoYutaro** [satijalab/seurat#2904]
Hi,
 I am trying to use Dot plot on my dataset and it seems that I can not get any figures. here is my code:

> Idents(seuset) <- factor(Idents(seuset), levels = T)
> markers.to.plot <- c("Ptprc", "Cd3e", "Cd4", "Cd8a", "Foxp3", "Pdcd1", "Il17a", "Ighm")
> DotPlot(seuset, features = rev(markers.to.plot), cols = c("lightgrey", "red"), dot.scale = 1, split.by = "Sample") + RotatedAxis()

However, I got the error message that “Error in FUN(X[[i]], …): Subscript is out of bounds” 
Why is it ?
Please tell me the way to solve it.

**Comment by AndrewSkelton** [comment]
Are those genes in your Seurat Object's features? What does the following return?

`markers.to.plot %in% rownames(seuset)`

**Comment by AndoYutaro** [comment]
Thank you so much for your reply.
I tried it and the result was:

> markers.to.plot %in% rownames(seuset)
[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

Is it right?

**Comment by AndoYutaro** [comment]
@AndrewSkelton 
Thank you so much for your reply.
I tried it and the result was:

`markers.to.plot %in% rownames(seuset)
[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE'

Is it right?

**Comment by AndoYutaro** [comment]
> 

> 

> ``

**Comment by AndoYutaro** [comment]
@AndrewSkelton 
I'm sorry. I accidentally closed the comments.
Could you tell me from here ?

**Comment by mojaveazure** [comment]
Why are you running `Idents(seuset) <- factor(Idents(seuset), levels = T)`? The identities should already be a factor; messing with them and changing the factor levels will cause bugs. This in particular will remove all your cell identities unless they're all `T` (even then, because you're setting a logical as the level, R may still remove everything since levels should be characters, not logicals). Try fixing your cell identities (if you ran `FindClusters`, they are stored in cell-level metadata under `seruat_clusters`); that should fix the issue you're having.

**Comment by AndoYutaro** [comment]
@mojaveazure 
Thank you so much for finding my error.
I understood what was wrong.
I could solve the problem and got the figure.
I'm grateful for your instruction.
