### ISSUE TITLE
Integration, SCT, and Expression Slot Clarification

### ISSUE THREAD

**Issue by AndrewSkelton** [satijalab/seurat#2906]
Hi, 

This is hopefully a simple explanation, I'm having trouble understanding conceptually what I _should_ do, post integration. 

On the different Integration vignettes it seems to be a bit of a mixed message between the standard RNA assay slot and SCT. So I'll try and summarise in some questions.

- Post Integration using `SCT`, what are the recommended steps?
  - Should the `DefaultAssay` parameter be set to `SCT` and `NormalizeData ` Ran?
  - or
  - Should the `DefaultAssay` parameter be set to `RNA` and `NormalizeData ` Ran?
- Post Integration using `SCT` which slot is best to use / most representative for an expression figure such as `FeaturePlot`?

Thanks for any clarification! 

Andrew

**Comment by AndrewSkelton** [comment]
After some deeper reading on Closed Issues, I think that #1421 articulated my questions the best. It seems that it's partially answered by referring to point 4 of the [FAQ](https://satijalab.org/seurat/faq), but I'm still unclear about how the `scaled.data` slot is used from `SCT` in Integration. Additionally this line of questioning has obviously been asked before as seen in the [SCTransform repo](https://github.com/ChristophH/sctransform/issues/4).

If the recommendation is to set the default assay to `SCT` or `RNA` post integration and run `NormalizeData`, for clustering / differential expression at the moment, should I expect the DE to be biased by any typically regressed variables (such as %MT)?

If the answer is yes, then is there any reason to regress out these variables in the first place, if no down stream function make use of them, or have I missed something there? Would the subsequent integration process make use of the `scaled.data` slot?

Would the advice be to feed these variables (such as %MT) into the `latent.vars` parameter in the `FindAllMarkers` function? - if they're expected to cause a significant impact?

Thanks for any clarification that can be made! :)

**Comment by mduan31** [comment]
In the FAQ 4, they said "DE and integration are not currently supported with sctransform but will be soon", but apparently we already seen there is a SCTransform version of integration [https://satijalab.org/seurat/v3.1/integration.html], so I'm not sure if DE is working for SCT assay at the moment. 

I can understand why we should not use integrated data to detect DEs because there are dependencies between genes. However, I don't understand why we can't use data from SCT assay to detect DEs, because SCTransform is an alternative normalization method, which is reported more efficiently removing variation due to sequencing depth and retains biological heterogeneity compared to general log2(1+CPM) [https://www.biorxiv.org/content/10.1101/576827v2]. If we can use RNA assay to detect DEs, why we can't use SCT assay to detect DEs?

Thanks!
Michelle

**Comment by satijalab** [comment]
Thanks, we get this question a lot and I understand its confusing.

First, after SCT integration, for dimensional reduction - please use the scale.data slot

The harder question is for DE. As we showed in the manuscript, SCTransform is well-suited for identifying DE genes in the presence of substantial technical noise. It does this because it learns a tailored model of technical noise for each dataset.

The challenge is that these models can be different from one dataset to another. The model SCTransform learns in one dataset may not be directly applicable to the model learned in another. Out of caution, we therefore do not suggest performing DE on the SCT assay when comparing different datasets.

Hope that helps

**Comment by RuixiangLiu01** [comment]
> Thanks, we get this question a lot and I understand its confusing.
> 
> First, after SCT integration, for dimensional reduction - please use the scale.data slot
> 
> The harder question is for DE. As we showed in the manuscript, SCTransform is well-suited for identifying DE genes in the presence of substantial technical noise. It does this because it learns a tailored model of technical noise for each dataset.
> 
> The challenge is that these models can be different from one dataset to another. The model SCTransform learns in one dataset may not be directly applicable to the model learned in another. Out of caution, we therefore do not suggest performing DE on the SCT assay when comparing different datasets.
> 
> Hope that helps

As you said, SCTransform can learn a tailored model of technical noise for a dataset, so Can I rerun SCTransform on integrated Seurat object with `DefaultAssay = 'RNA'` and then I can get a new SCT assay and do DE on that assay?

**Comment by NicolaasVanRenne** [comment]
Hi Satija lab members, 

considering this: 
> The challenge is that these models can be different from one dataset to another. The model SCTransform learns in one dataset may not be directly applicable to the model learned in another. Out of caution, we therefore do not suggest performing DE on the SCT assay when comparing different datasets.

Would this explain the following?
I have used corrected UMI counts from the [["SCT"]] slot and this works brilliantly. Only now, I integrated two datasets (5 healthy phenotypes, 5 sick phenotypes). When I compare the healthy to the sick for DEG, I basically get housekeeping genes that are differentially expressed and I really don't know what happened. SCT should normalize all of this... 

So in more detail what I did: 
integrate 5 healthy and check DEG between clusters using SCT: works fine
integrate 5 sick and check DEG between clusters using SCT: works fine

downsample these 10 to 1500 cells per sample and integrate, check DEG between clusters using SCT: works fine **BUT** when I compare healthy vs sick inside a cluster, the read depth is uneven and I get housekeeping genes.

In any case: Seurat is amazing and thanks for all the support.

Nicolaas

**Comment by Dragonmasterx87** [comment]
But simple question.......why not just use the normalized 'RNA' assay slot? I think biologically, this is most relevant. SCT and Integration slots have negbinom normalized data, which is fine for clustering, but really isn't relevant in terms of gene expression variation across samples......Tx or WT, or Tx vs WT, or Tx vs Tx or WT vs WT. So honestly, I really think one should stick to normalized RNA data for DE. Mostly, because someone performing a wetlab experiment can then re-capitulate your scRNAseq data the best. I think the variation in sequencing depth across scRNAseq experiments is MAXIMUM a log difference of 1 (10k vs 100k reads/cell), which isnt really (or shouldnt be) enough to allow for totally deviant gene expression, to the extent that normalized RNA cant be used to drive DE. Albeit, this discussion is really important I dont think anyone has a really good answer right now. I think a really strong paper needs to be published showing ironclad biologically conserved results for SCT driven DE, recapitulated orthogonally in FISH......im, not a seurat dev, these are just my thoughts though!

**Comment by NicolaasVanRenne** [comment]
Because I assumed the SCT to normalize better. RNA lognormalized counts should have more variance stemming from read depth per cell, a feat that SCT should minimize.   I will try with RNA and see what the results are.  Ah seurat, the gift that keeps on giving :)

**Comment by Dragonmasterx87** [comment]
@NicolaasVanRenne  Just a few ideas....check out your data (you must know Key genes) after when you RNA normalize using 

`normalization.method = "RC", scale.factor = 1e6, # This gives cpm`

vs. the regular log1p normalization ("LogNormalize" does).......RC (relative counts) gives you a true perspective of how genes are ACTUALLY being expressed in your data (RC DOES NOT LOG NORMALIZE).....of course I totally agree with you sequencing depth and batch variation is a pain in the a**, but at the end of the day I think we get too caught up in the integrations and normalizations and we need to ground ourselves on actual gene expression. Having said all this, I'm sure the devs will find a way to make SCT applicable robustly on DE. But for now.....we have #1836 (in favor of SCT) and #1900 #1717 (all hail RNA assay)....also in support of team RNA: (from [here](https://satijalab.org/seurat/faq.html)) 

4. I’ve run an integration analysis and now want to perform a differential expression analysis. Which Assay should I use?
We recommend running your differential expression tests on the “unintegrated” data. By default this is stored in the “RNA” Assay. There are several reasons for this.

i. The integration procedure inherently introduces dependencies between data points. This violates the assumptions of the statistical tests used for differential expression.

**ii. We recommend performing differential expression on the RNA assay, after normalization.**

**ii. If you have used the SCTransform workflow for normalization and integration, we still suggest performing differential expression on the RNA assay.**

THEREFORE till the FAQs don't change....I'm using the RNA slot for normalization, gene expression, and DE...... 😆 🤣

Also, I just want to say here I ❤️ Seurat. The devs should make a T. I'll be the first to buy it.

Cheers,
🐉

**Comment by NicolaasVanRenne** [comment]
Hello dragonmaster,

I quickly tried with RNA (standard, not the way you told me to, will try that later - keep you posted) , seems to give the same results... Maybe its just because I subset a small amount of cells that happen to be low in read depth. I agree that the dev team should make the clarification of this issue a priority, since this question and related ones seem to come back time and again.

**Comment by Dragonmasterx87** [comment]
@NicolaasVanRenne just to clarify, you want to run DE on the log normalized data (like you are doing and what is recommended based on the seurat vignette), I just use RC data usually for plotting raw expression.....and also to see how genes are actually fluctuating across clusters. In the end, the data needs to be scaled anyway for heatmaps.

**Comment by jhb1980** [comment]
I've been following this thread as I've been struggeling with finding the "best" way to go about this also in context of technical and biological (donor) batches. The author of `sctransform` has now implemented a differential expression testing based on the output from the "native" `sctransform`. He put out a really nice walk-through on how to do this in different contexts, including Seurat-based  integration (note this is sctransform, not Seurat::SCTransform):

https://rawgit.com/ChristophH/sctransform/supp_html/supplement/np_diff_mean_test.html
