### ISSUE TITLE
Error in DefaultDimReduc(object = x, assay = assay) :    could not find function "DefaultDimReduc"

### ISSUE THREAD

**Issue by vlcm2019** [satijalab/seurat#2909]
Hello,

I am new user for both R and Single cell analysis. I am trying to use the Seurat object for Monocle analysis. I used your as.CellDataSet.Seurat function. However I am getting the error below. Could you please help? Thank you.

**Error in DefaultDimReduc(object = x, assay = assay) :    could not find function "DefaultDimReduc"**

**Comment by liuxl18-hku** [comment]
That function is not in master branch of SeuratWrapper, but in feat/monocle3 branch, maybe you should try to re-install your SeuratWrapper package:
```r
devtools::install_github("satijalab/seurat-wrappers", ref="feat/monocle3")
```

bless~

**Comment by vlcm2019** [comment]
Hi,

Thanks for your response. I tried re-installing but got the error below.

**>** devtools::install_github("satijalab/seurat-wrappers", ref="feat/monocle3")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.

**Comment by vlcm2019** [comment]
I tried using the **as.cell_data_set.seurat** function available on SeuratWrappers on the feat/monocle3 branch and got the error below.

as.cell_data_set.Seurat(sample)
**Error in AssociatedDimReducs(object = x, assay = assay) : 
  could not find function "AssociatedDimReducs"**

I tried the solution provided by KinSimon96  for the issue **Using Seurat merged object for pseudo time analysis in Monocle 3 #2833** and it worked.

**Comment by mojaveazure** [comment]
@vlcm2019 you should not be calling `as.CellDataSet.Seurat` or `as.cell_data_set.Seurat` directly. These are internal methods that should be dispatched by R to handle other internal functions. Instead, you should be calling `as.CellDataSet` or `as.cell_data_set`; if you are calling these generic functions rather than the `Seurat`-object specific methods, please reopen this issue and provide the code you ran along with a dataset that reproduces the issue (either one of your own or one from [SeuratData](https://github.com/satijalab/seurat-data)), and the output of `sessionInfo()`

**Comment by vlcm2019** [comment]
@mojaveazure thank you for your response. I tried the Seurat as.CellDataSet function and did generate a monocle CDS. However, when I tried running reduceDimension in monocle I got the below error. I am not sure what this means or how to fix it. I posted it in the monocle github issues page and still waiting for a response. Would you be able to provide some input on this error.

**stumor_cds <- reduceDimension(stumor_cds, method = 'DDRTree')

Error in checkSizeFactors(cds) : Error: one or more cells has a size factor of NA.**
