### ISSUE TITLE
plotting cells in "Featureplot" by barcode

### ISSUE THREAD

**Issue by brekk129** [satijalab/seurat#2931]
hello! 

I have a group of cells that I've identified by barcode (i.e. AAACCCACAGTCTGGC-1) that I'd like to highlight in a feature-type plot after I've clustered this sample using umap where all cells would be grey and then just the cells in my barcode list are another color. Is there an easy way to do this? 

thank you.

**Comment by samuel-marsh** [comment]
Hi,

You can do this using `DimPlot()`.  Also adding `order = TRUE` (helpful if number of cells is large so that highlighted cells are not hidden behind non-highlighted ones.
For instance:
`DimPlot(object = object, cells.highlight = cell_names, cols.highlight = "desired_highlight_color", cols = "gray", order = TRUE)`

Best,
Sam

**Comment by brekk129** [comment]
awesome, thanks! looks great!
