### ISSUE TITLE
how to subset cells with cell type marker (expression of one specific gene)

### ISSUE THREAD

**Issue by ivonyao** [satijalab/seurat#294]
I am totally new to the world. We have some 10x sequenced data from different patients, I want to subset out specific cell types based on cell markers, then compare each cell type among patients. Basically, I need split one raw data into several based on surface marker like cd326 for epithelial, cd45 for immune cells, cd31 for endothelial cells. Just wondering if I use seurat to read in 10x raw matrices and create object, then how to use SubsetData to subset them into different projects

**Comment by leonfodoulian** [comment]
Hi,

The way to proceed is to first create a character vector of cell names for each expected cell type in the dataset, and then pass these vectors sequentially to the `cells.use` argument of the `SubsetData()` function from Seurat.  Please check the documentation of the function for more information (simply run `?Seurat::SubsetData` in R). Nevertheless, I think it is much easier to create a column storing the identity of each cell in your `object@meta.data` slot, and proceed with your analysis with a single Seurat object. Seurat has many build in functions that can allow you to limit your analysis to a subset of the cells in your object.

Best,
Leon

**Comment by ivonyao** [comment]
Thanks @leonfodoulian

**Comment by yuyingrong** [comment]
Found this discussion helpful but when I used `SubsetData()`, got "`could not find function "SubsetData`".

Turned out `Seurat::SubsetData` is now defunct, but we can use `subset()` instead: https://github.com/satijalab/seurat/issues/1564.

A usage example here: https://hbctraining.github.io/In-depth-NGS-Data-Analysis-Course/sessionIV/lessons/SC_clustering_analysis.html.

In this example, instead of 
`SubsetData(x=my_object, cells.use=rownames(seurat_raw@meta.data)[which(...)])`,
write `subset(x=my_object, cells=...)` instead.
