### ISSUE TITLE
Error: readMM(): column values 'j' are not in 1:nc

### ISSUE THREAD

**Issue by yimei-li** [satijalab/seurat#2946]
I get this "**Error: readMM(): column values 'j' are not in 1:nc**" when I am trying to use this function of "Read10X":

> mydt.data <- Read10X(data.dir = "../data", gene.column=1)

These are the header of my 3 files:

**matrix.mtx**
%%MatrixMarket matrix coordinate real general
%
20222 157 150812
1 1 5
3 1 0
4 1 7
5 1 3
6 1 5
7 1 8

**genes.tsv**
nduo-6
ndfl-4
nduo-1
atp-6
nduo-2
ctb-1

**barcodes.tsv**
ABalaaaalal.ABalaapaaar
ABalaaaarxp.ABalapppaap.ABplpappaaa
ABalaaapalr.ABalaaapprl
ABpxaapaaap.ABalaaapall.ABalaaapprr.ABalppapapp.ABarapppapp
ABalapxpppp.ABalaapappp.ABalppaappp
ABalaappapa.ABalppaaapa

**Anyone can help me with "Error: readMM(): column values 'j' are not in 1:nc"?**

**Comment by andrewwbutler** [comment]
Hi,

It looks like there is a problem with your `matrix.mtx` file. This kind of error can show up for example if the number of rows as defined in the header is not consistent with the row/column id of the triplet entries. How did you generate these files?

**Comment by breezedu** [comment]
Got the same error this morning, turns out the first two columns in the matrix.mtx were flipped in my case. 
Those three numbers in matrix.mtx (20222, 157, 150812) denote to Genes - Cells - TotalLines;  
So, check the total count of lines in genes.csv, that number should be equal to 20222, then check the total lines of barcodes, it should be equal to 157. Just fyi, I know it's been a few years, just incase someone got similar error again, this might give some heads up.
