### ISSUE TITLE
n1 * n2 : NAs produced by integer overflow

### ISSUE THREAD

**Issue by vlcm2019** [satijalab/seurat#2950]
Hello, I am analyzing a large sample set. I have a total of 18 clusters and after running FindAllMarkers, I got the error message below. With the write.csv file for all markers, I am only able to get the markers for clusters 11-18 and nothing for clusters 1-10. Please let me know how to resolve this issue.

**In n1 * n2 : NAs produced by integer overflow**

**Comment by wtoddfarmer** [comment]
Hi Seurat team. I am having the same issue as vlcm2019. pvals for some clusters are NAs with both FindAllMarkers and FindMarkers. Version 3.1.5. Thanks.

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting! This should be fixed now on the develop branch if you want to try that out.
```R
devtools::install_github(repo = 'satijalab/seurat', ref = 'develop')
```

The issue was caused by a recent switch to using a more efficient function for the wilcox test from the limma package. However, if you don't have the limma package installed, it will still fall back on the standard `wilcox.test` function from `stats` which shouldn't have this overflow issue. So if you don't want to install the development version, you can try uninstalling the limma package.

**Comment by wtoddfarmer** [comment]
Hello,

Thanks for the reply. After I found the issue, I downgraded to 3.1.0. That will do for now.

Best

**Comment by vlcm2019** [comment]
Thank you for the recommendation. I will try that.
