### ISSUE TITLE
Can I compare two subsets of cells across conditions although they are different in numbers of cells?

### ISSUE THREAD

**Issue by ag174891** [satijalab/seurat#2968]
Hi, 
I have a question about integrating two datasets. I'm using Seurat v3 and I followed the guided tutorial on the Satija lab website (THANKS!!!) to perform a comparative analysis of two datasets. I'm interested in a specific cell type that is present in both datasets. However, it turns out that this cell type is more abundant in sample A than in sample B (2,212 vs. 449 cells). 
Now I am afraid that this influences my calculation of variable genes, as the cluster with higher number of cells might be overrepresented. Is there a way to account for differences in cell numbers?

Thanks, 
Anne

**Comment by satijalab** [comment]
Since the identification of variable genes takes mean expression into account, we do take this into account. If you are particularly concerned, you could try downsampling the more abundant cell population to see if the results change substantially. I (strongly) expect that they will not, but if they do please do let us know, and feel free to reopen
