### ISSUE TITLE
VlnPlot:  probability density plots

### ISSUE THREAD

**Issue by AndyR2** [satijalab/seurat#297]
(This is more of a Q than an issue - but, not sure where else to ask and get informed responses)

Trying to understand how VlnPlot 
1) determines when to draw the rotated kernal.   In the attached Acta2 plot, for example, only one cluster shows this, but there are cells shown in other clusters.   What is the "expression threshold" gives the rotated kernal ?
[VlnPlot_Acta2.pdf](https://github.com/satijalab/seurat/files/1692272/VlnPlot_Acta2.pdf)

2) If a gene is expressed broadly, as is Ubc in attached file, the VlnPlot shows a similar looking rotated kernal density plot for all clusters, even though the cell numbers used decrease as the cluster number increases.   Clearly Cl#2, 15, 23 have very different cell numbers, but have nearly identical plots.
[VlnPlot_Ubc.pdf](https://github.com/satijalab/seurat/files/1692263/VlnPlot_Ubc.pdf)

**Comment by leonfodoulian** [comment]
Hello,

> What is the "expression threshold" gives the rotated kernal ?

There is no expression threshold associated with the width of the violin plot. This will depend on the distribution of gene expression levels across all the cells from a given cluster. In your **VlnPlot_Acta2.pdf** plot, you can clearly see that the majority of the cells from all the clusters, except from cluster 17, have 0 gene expression level for _Acta2_, hence the very small width of the violin plots at higher gene expression levels (represented by a line in this case). Indeed, cluster 17 has very few cells with 0 expression level for _Acta2_.

> If a gene is expressed broadly, as is Ubc in attached file, the VlnPlot shows a similar looking rotated kernal density plot for all clusters, even though the cell numbers used decrease as the cluster number increases. Clearly Cl#2, 15, 23 have very different cell numbers, but have nearly identical plots.

Seurat's `VlnPlot()` function uses `width` as input to the `scale` argument of `geom_violin()` (more information on the three input options to `scale` can be found in the documentation of the function - simply run `?ggplot2::geom_violin` in R). You can find the corresponding code at [lines 642 to 647 in plotting_internal.R](https://github.com/satijalab/seurat/blob/23853782a0793540a1db65cd12e95e90bfa86289/R/plotting_internal.R#L642-L647). Defining `scale = "width"` will set the same maximum width for all violin plots across all clusters. You simply don't see that for all clusters (except cluster 17) for _Acta2_ because the maximum width is set at 0, which is exactly the same width as that at gene expression level of ~5 for cluster 17. In other words, the width of the violin plots is independent of cell number, and is not affected by cell number differences across clusters. 

Hope this helps!

Best,
Leon

**Comment by AndyR2** [comment]
thx Leon
