### ISSUE TITLE
Problem reading .h5ad file

### ISSUE THREAD

**Issue by Mohebg1234** [satijalab/seurat#2977]
Dear All,

I am trying to read a .h5ad file using the function>
file.seurat <- ReadH5AD(file = "D:/.../file.h5ad")

I am getting the following error:

Pulling expression matrices and metadata
Error in self$read_low_level(file_space = self_space_id, mem_space = mem_space_id,  : 
  HDF5-API Errors:
    error #000: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5Dio.c in H5Dread(): line 173: can't read data
        class: HDF5
        major: Dataset
        minor: Read failed

    error #001: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5Dio.c in H5D__read(): line 551: can't read data
        class: HDF5
        major: Dataset
        minor: Read failed

    error #002: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5Dchunk.c in H5D__chunk_read(): line 1875: unable to read raw data chunk
        class: HDF5
        major: Low-level I/O
        minor: Read failed

    error #003: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5Dchunk.c in H5D__chunk_lock(): line 2905: data pipeline read failed
        class: HDF5
        major: Data filters
        minor: Filter operation failed

    error #004: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5Z.c in H5Z_pipeline(): line 1347: required filter 'lzf' is not registered
        class: HDF5
        major: Data filters
        minor: Read failed

Can anyone help me figure this out ?

Best,
Moheb

**Comment by kleurless** [comment]
Might be related to this issue #2748, they're working on it.

**Comment by mojaveazure** [comment]
You're missing the LZF HDF5 plugin. The [LZF plugin](https://github.com/h5py/h5py/tree/master/lzf) is developed by h5py and included only in their implementation of HDF5. For the purposes of cross-platform sharing of HDF5 files, I would suggest not using LZF for compression, instead using the default and cross-platform GZIP compression.

However, you can work around this on *NIX systems only (eg. macOS and Linux). To enable LZF in R, you can download the shared library from h5py, change into the lzf directory, and compile it as a plugin for HDF5 (`gcc -O2 -fPIC -shared lzf/*.c lzf_filter.c $(pkg-config --cflags --libs hdf5) -o liblzf_filter.so`). Once done, add the lzf directory to the HDF5_PLUGIN_PATH environment variable (I do it through `Sys.setenv`) and load hdf5r and Seurat (you have to have the HDF5_PLUGIN_PATH variable set **before** loading hdf5r and Seurat, otherwise the HDF5 API won't see the plugins)

**Comment by satijalab** [comment]
Thanks - this is a tough situation as Paul says, LZF compression works well in Python but is difficult to convert across platforms into R.

The easiest option would be just to re-export your LZF-compressed AnnData object as a gzip-compressed AnnData object. This should be easy to do in Scanpy, @falexwolf @flying-sheep - do you guys have a quick example for how to do this?

**Comment by Mohebg1234** [comment]
Thanks alot everyone for the responses.
I ended up coveting the .h5ad to a seurat object in Scanpy, using a python virtual environment in R.

**Comment by janeshen91** [comment]
@Mohebg1234 , would you be able to post an example on what you did? I'm having the same issue
