### ISSUE TITLE
Loading 10x files to Seurat by files and not by directory (Shiny App path directory security issue)

### ISSUE THREAD

**Issue by KinSimon96** [satijalab/seurat#3008]
Hello,

Thank you for fixing most of the issues in your dev version to build a shiny app using Seurat package.
However, shiny server doesn't allow the access to user's hard drive (C:) in order to upload files using a path directory, for security reasons. It only works locally but that's not the final use.
That's why I would like to know if the 3 files from 10xGenomics could be loaded separately, using another form of `Read10x()` that reads `barcodes.tsv`, `genes.tsv` and `matrix.mtx` instead of the directory. 

Thank you very much,
Simon

**Comment by mojaveazure** [comment]
Hi Simon,

Unfortunately, we don't plan on lifting this restriction of `Read10X` as enforcing this structure requires that our users keep their Cell Ranger outputs intact so that they can use their results in other packages. For your app, you could (probably, I haven't actually tried any of these but conceptually they seem sound to me) get around this restriction in one of several ways:

- Have your users use the 10X HDF5 format and use [`Read10X_h5`](https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/Read10X_h5) (will require that you install [hdf5r](https://cran.r-project.org/package=hdf5r) and provide the HDF5 library on your server if you deploy on macOS/Linux installations; hdf5r provides the Windows HDF5 library when installing)
- Roll your own version of `Read10X`. This would mainly mean that you use [`Matrix::readMM`](http://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/externalFormats.html) to read the expression matrix, `readLines` to read the cell barcodes, and `read.table`/`read.delim` to read the features names. It gets a little complicated if you want to support both Cell Ranger v2 and v3 files as the features are formatted slightly differently between the two. It also gets complicated if you want to support multi-modal Cell Ranger v3 datasets
- Make use of temporary directories with [`tempdir`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/tempfile.html). I'm not entirely sure, but I believe that a deployed Shiny app can create temporary directories for itself. You could either have the user upload the three parts individually, copy them to a temp directory, and run `Read10X` on that. You could also have the user upload an archived (zipped or tarballed) Cell Ranger output directory; unarchive it to the temp directory, and run `Read10X` on that.

**Comment by KinSimon96** [comment]
Thank you! I'll try any of these!
