### ISSUE TITLE
Scale.data is used as input source for DoHeatmap()?

### ISSUE THREAD

**Issue by bitttyyyy** [satijalab/seurat#301]
Hi Seurat team,

Thank you so much for developing this amazing tool. I just have a question about the DoHeatmap function. I ran FindAllMarkers and used the top 10 genes of each cluster to plot a heatmap. However, the genes that should be differentially expressed in cluster 0 do not seem to be expressing in great intensity on the heatmap. I was wondering what caused that because the VlnPlot shows high gene expression for those genes in cluster 0, and I think the reason is that DoHeatmap is plotting using the scale.data while VlnPlot is using the normalized data (@data field). I regressed out several confounding variables by doing ScaleData() at the beginning to remove noise caused by cell cycle,  nUMIs, and nGene. Just wondering why does the DoHeatmap function and VlnPlot function use different data source as input and which one is more accurately representing the gene expression? 

Any help is greatly appreciated. Thanks!

**Comment by leonfodoulian** [comment]
Hi,

`DoHeatmap()` uses the scaled data so that all genes are somewhat at the same level. That is, if you have genes expressed at high levels, and other at low levels, using the normalised data will only highlight the highly expressed genes on your plot. In the scaled data, all genes have now a mean of 0 and an sd of 1. Therefore, this will allow you to highlight for each gene, which are the clusters that have the highest mean expression, using the same scale on the plot. `VlnPlot()` plots each gene separately, each plot with its own scale. So in this case using the normalised data will not hinder highlighting which cluster has the highest expression for that gene. 

I don't think that one more accurately represents gene expression level. Heatmaps allow you to visualise the cluster specific genes, whereas violin plots highlight for each cell the normalised (or not) expression level for each gene. 

Hope this was clear!

Best,
Leon

**Comment by ChristinaSteyn** [comment]
Hi there, 

Thank you so much for developing so many amazing tools!

I am still a bit confused about the scaling for DoHeatmap. From what I have read it seems we should use the scale.data slot but this will scale the counts across all nuclei if I am not mistaken not across samples? I am using the average expression counts and would like to visualise the expression between samples (so I would like to scale across samples not nuclei). I have specified group.by = "sample" but I don't think this will automatically scale it across samples? It seems like the DotPlot function has the option to scale the expression and from the outputs it looks like it is scaling it across whatever one specified in group.by (e.g cluster or sample). How can I do the same thing for DoHeatmap?
