### ISSUE TITLE
Seurat and other graph based clustering algorithms

### ISSUE THREAD

**Issue by am-9** [satijalab/seurat#3038]
Hello, 

I'm trying several graph based clustering methods for single cell rna-seq data including seurat, monocle and scanpy. I'm trying to understand how the clustering function works in each of these packages. All 3 methods construct a kNN graph and use either the Louvain or Leiden algorithm to optimize the clusters. 

I was wondering how these 3 methods are different in their clustering functions? Should they produce different clustering results?

**Comment by aubreyghoward** [comment]
Here is a review that I found helpful when first approaching this topic. 
https://www.nature.com/articles/s41576-018-0088-9

**Comment by timoast** [comment]
The clustering methods implemented in these different software packages are similar or the same. In Seurat we construct a neighbor graph and perform community detection on the graph using one of several different algorithms available in the `FindClusters()` function (Louvain, Louvain with multilevel refinement, Leiden, Smart Local Moving). Differences in clustering between the packages are likely due to different upstream data normalization, filtering, neighbor graph construction, random seed initialization, and implementation of the clustering algorithms.
