### ISSUE TITLE
Study heterogeneity of subset after integration

### ISSUE THREAD

**Issue by akramdi** [satijalab/seurat#3039]
Hello, 

I have integrated 9 tumor samples (tumour cells + normal microenvironment cells) using the standard Seurat V3 protocol. Similar to issue #2627,  I noticed that tumors cells are forced to align all together. Because we carefully analysed all tumours separately, we have a feeling on how samples should align but the integration does not reflect any of it, it seems too strong. Here are my questions/thoughts on how to go from here:

1. in  #2627, this comment was made: 

> Please note that just when Seurat aligns cells together that have subtle differences, this is not overfitting. We do this precisely because we want to identify cells that are in a shared biological state. In a secondary step, you can then identify differentially expressed genes between them.

Obviously tumors cells are in a shared biological state so they align well together. If I was to further explore subtle differences between these cells, would it be correct to exact the tumors cells from the integration and rerun a "targeted" analysis only on this subset? What would be the best way to do this? Here's what I am thinking:

- step1: Extract cells
- step2: Recompute most variable genes
- step3: Perform  `RunPCA`, `RunUMAP`, `FindNeighbors`, `FindClusters`
- step4 Switch to RNA assay for expression analysis (`FeaturePlot`, `FindAllMarkers` ) ..

I am not sure which assay to pick for step 2 and step 3 (SCT or integrated?). 

2. In case the first approach is not valid for some reason. In #2627 the idea of performing the integration on a subet of cells (normal cells) was mentioned. How can we perform such integration on a subset of cells? Should we just feed `FindIntegrationAnchors` a list of seurat object containing the subset of normal cells , then use the output `AnchorSet` object to integrate the full data. Does it sound correct?

Many thanks for the helps!
Best,

**Comment by jaisonj708** [comment]
If you feel that CCA results in over-integration of tumor cells, you can consider using RPCA. You can also just do differential expression on the unintegrated data, especially if you think that batch effects are likely to be smaller in magnitude than the differences in your samples (very possible if your data is from different tumors, profiled with the same technology).

Your method of filtering anchors in order to integrate only normal cells is fine. Seurat v4 will include some anchor filtration methods. You can also integrate normal cells, and then merge with the unintegrated tumor cells.
