### ISSUE TITLE
Error in FindIntegrationErrors

### ISSUE THREAD

**Issue by kelly-clark** [satijalab/seurat#3048]
Hi,

We are trying to run FindIntegrationAnchors for a large data set, and we came across this error:

```
Finding anchors
    Found 2934 anchors
Filtering anchors
    Retained anchors
Error in $<-.data.frame(*tmp*, "cell2", value = integer(0)) : 
 replacement has 0 rows, data has 3
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
 Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
```

Is there a way for us to fix this? It did run without issues for a while before getting this error, and we were able to run SCTranform without issues, if that helps.

Thanks,
Kelly

**Comment by timoast** [comment]
In this case it looks like all the anchors were removed during the filtering step, and so later steps fail because there are no anchors. Do you expect common cell states across the datasets that you're trying to integrate? You could try altering the anchor finding and anchor filtering parameters in the `FindIntegrationAnchors()` function.
