### ISSUE TITLE
Why calculate HVG before ScaleData

### ISSUE THREAD

**Issue by dg520** [satijalab/seurat#3057]
Hi,  
    
I have a question regarding the order of preprocessing. Why we should calculate highly variable genes (HVGs) after normalization but before `ScaleData`, especially if we have regressed out variables during `ScaleData`? This process will always give the same set of HVGs, no matter what variable we regress out (the values in "scale.data" will be different for sure).     
        
But the problem is: when regressing out variables of undesired, the variance of gene expression across cells changes. And the HVG estimated from the original "data" slot might not still hold (not only the rank will change, but also the original HVGs might go in and out of the list). Why not apply `ScaleData` with regression on the entire "data" matrix (e.g. all genes), and then calculate HVGs, and finally generate "scale.data" slot based on top HVGs post-scaling? This will give different sets of HVGs according to different `var.to.regress` arguments, and it seems to make more sense.        
      
Do I understand something wrong? Appreciate any help on this.    
        
Best,
Dadi

**Comment by xhbkirby** [comment]
I have the same question here. Also for SCT assay I believe the find HVG function is also applied before regressing out variables, and the same question why not finding HVGs after regression for the SCT method?

**Comment by timoast** [comment]
The idea behind finding highly variable genes is that there is a strong mean-variance relationship in scRNA-seq data, and we want to find genes that are more variable across the cells than expected given the mean expression value for that gene. This assumes that most genes are not variable across cells, and most of the variance we see is due to the sparsity of our measurements. If we scale and center the data, we are subtracting the mean and dividing by SD, so it would then not be possible to recover a set of informative HVGs since we lose the original mean and variance information.

I would recommend looking at the SCTransform paper: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1
and the feature selection chapter of the OSCA book: https://osca.bioconductor.org/feature-selection.html

**Comment by dg520** [comment]
Hi @timoast ,

Thanks for your explanation. It totally makes sense to find HVG without scaling the data as you said. But my question is more regarded to the normalization or regressing out unwanted variables. Why we don't want to regress out background noise first, then find HVGs and finally scale the normalized data? 
Although regressing out noise indeed changes the original mean-variance relationship, I think the new mean-variance relationship (after cleaning) might be more robust and purely related to biology without artifacts. 
Does it sound nonsense or did I make something wrong? 

Best,
Dadi
