### ISSUE TITLE
Question about scaling of y axis for Dotplots

### ISSUE THREAD

**Issue by jeitziner** [satijalab/seurat#3072]
Dear Team, 
Thanks for a great package. I do have several Dotplots for a publication and was wondering how can I make the "y axis" or the rows consistent through several plots ? If I have for instance 3 groups of cells with 10 genes or if I have 10 groups of cells with 10 genes the spacing between the rows is unequal in the two figures. Any suggestions ?

Thank you and best wishes!

**Comment by MoaES** [comment]
I don't understand exactly where your problem lies since I haven't seen the figures, but in general: Seurat outputs ggplot objects, or lists of ggplot objects. If you want to alter i.e. the y axis you can do so using methods from the ggplot package (you can manually set breaks, limits, ticks, etc). 

Below is an example with a violin plot. The last row contains a modifier for the ggplot object; it sets the limits for the y axis. You may want to look into ggplot themes and add something modifying the y.axis.ticks, and consider something like + scale_y_discrete(breaks) to modify your plot object too. 

plot <- VlnPlot(
  seuratObject,
  features =  "gene",
  group.by = "seurat_clusters"
)

betterPlot <- plot + ylim(-1,6)

You can also have a look at ggsave to make sure the figures you output are of identical dimensions -- I don't know if this could be a possible source of your problem. It's a little hard to advice you without seeing the problem. Hope you find a solution, best of luck!

**Comment by jeitziner** [comment]
Thanks for your fast answer. Yes I've tried a few things with breaks and others but it was not really satisfying, I thought you might have another idea. 
here is a picture of how it looks like 
![DotPlot_integrated_only_subepithelial_1_special_4_6_ggsave](https://user-images.githubusercontent.com/32093941/82937880-32d33c00-9f91-11ea-8a90-3a09cc1f17e6.png)


I would have liked 0 1 and 2 to be super close instead of spread so much. 
I will continue to try with the breaks and the ylims. Thank you for your help.

**Comment by MoaES** [comment]
Oh, now I understand (I think). You don’t want it to be square shaped? Then, you just need to change the dimensions of the output. I’d suggest using ggsave and output the dotplot with a lower height than width. I can paste some code example when I’m by my laptop if you’re still having problems with this. :)

**Comment by jeitziner** [comment]
Yes I've tried this and when I change it then the legend gets cutoff. 
![DotPlot_integrated_only_subepithelial_1_special_4_6_ggsave2](https://user-images.githubusercontent.com/32093941/82940248-dbcf6600-9f94-11ea-9f4b-123115b936ec.png)
This for instance looks perfect in terms of 0,1,2 being close, but the legend is cut.

**Comment by MoaES** [comment]
You have to adjust your legend accordingly. You'll do this with ggplot theme options. You may need to play around a little to find the right parts, but this would for instance reduce the text size of your legends:

plot +     
  theme(legend.text = element_text(family = 'Helvetica', size = 10)) +
  theme(legend.title = element_text(family = 'Helvetica', size = 12)) 

You'll also need to adjust the size of the legends themselves, and you can do that with legend.key.height or legend.key.size.

**Comment by jeitziner** [comment]
Thank you for your help, I will try and play some more with parameters ! Best wishes!

**Comment by weiruhan** [comment]
Using coord_fixed(ratio = xx) is better.
