### ISSUE TITLE
FindIntegrationAnchors() with a small amount of cells

### ISSUE THREAD

**Issue by YangShi-PKU** [satijalab/seurat#3166]
Hi, I have about 5000 cells and 30 batches (or samples). I want to integrate them and remove the batch effect using FindIntegrationAnchors() and IntegrateData(). But there are less than 30 cells in some batch, so if I run:
`seu.anchors <- FindIntegrationAnchors(object.list = seu.list, dims = 30)`
It will throw out an error:
`Error in FindIntegrationAnchors(object.list = seu.list, dims = 1:30) : `
`Max dimension too large: objects 1, 2, 3, 4, 9, 10, 11, 12, 13, 14, 16, 18, 19, 21 contain fewer than 30 cells. `
I want to know how to deal with such situation. Do I have to remove those batch with <30 cells? And moreover, if the number of cells in a batch is only a little bit larger than 30, say 35 cells, is it reasonable to include this batch in FindIntegrationAnchors() and IntegrationData?

Thanks !

**Comment by jaisonj708** [comment]
You can either merge your smaller batches together, or get rid of them entirely if you don't think they contain any new information not already present in your larger samples.

**Comment by YangShi-PKU** [comment]
Got it! Thanks!

**Comment by morchalabi** [comment]
@jaisonj708 what you are suggesting is not right:

1) "You can either merge your smaller batches together ..." what you suggest is not right and that's not how MNN-based algorithms (like WNN) work. When you merge two samples each having a cluster of the same cell type, the two clusters will be separate from each other due to batch effect, as if they contained two different cell types like fibroblast and myofibroblast, while they are both fibroblasts. During integration, since both the clusters will follow the direction and length inferred by the resultant vector, still they end up separate in the reference space like two different cell types!

2) "or get rid of them entirely if you don't think they contain any new information" that is not right either. Consider two clusters containing activated stellate cells and inflammatory CAFs. They both have very similar gene expression profiles but the one containing activated stellate cells is most probably much smaller because activated stellate cell is a multipotent stem cell and CAF is a differentiated stellate cell. They both must be present in the integrated data.

3) last but not least, FeaturePlot function uses RNA slot for showing the expression level of genes after integration! that's also very wrong as the count matrix in the RNA slot contains merged data suffering from batch effect. An investigator may be fooled into thinking the expression difference of a gene, like CD45, between two clusters is biologically meaningful. Please be advised I am particularly not talking about differentially expressed genes. Consider a gene that is highly expressed/unexpressed in a small portion of a cluster and therefore not identified during DGEA. However, this expression could be still biologically informative like a cytokine receptor in some portion of a cluster of Tregs.
