### ISSUE TITLE
Assigning cell type identity to clusters

### ISSUE THREAD

**Issue by ikrishnan** [satijalab/seurat#3239]
What is the source of the cell types : "Assigning cell type identity to clusters " in the tutorial? Suggestions (code) to load our own cell types would be most helpful. Thanks.

**Comment by ikrishnan** [comment]
I am referring to this piece of code from the tutorial:
new.cluster.ids <- c("Naive CD4 T", "Memory CD4 T", "CD14+ Mono", "B", "CD8 T", "FCGR3A+ Mono", 
    "NK", "DC", "Platelet")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
DimPlot(pbmc, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but believe you can see issue [#1344](https://github.com/satijalab/seurat/issues/1344) for some additional information on some of the markers but the rest are simply based on canonical markers from the literature for those cell types.

In terms of annotating your own cell types you simply need to replace the values for `new.cluster.ids` with identities of you want to rename your clusters.  The `new.cluster.ids` must have same number of values and be in same order as current cluster identities in order to rename correctly.  If you want to merge clusters simply give them both the same name when providing values to `new.cluster.ids` (see #3202).

Best,
Sam
