### ISSUE TITLE
SCTransform - batch correction

### ISSUE THREAD

**Issue by s849** [satijalab/seurat#3255]
Hi,

Thank you for developing SCTransform. I am using SCTransform on my data set (3 patients - condition + normal for a total of 6 samples) and was wondering the following whether it is recommended to use vars.to.regress to regress out UMI, mito and patient ID (patient 1/2/3) or simply run SCTransform without specifying any vars to regress?

**Comment by jaisonj708** [comment]
By default SCTransform will regress out (log) umi, so you don't need to specify this. It is fairly common to regress out percent mitochondrial reads, so feel free to add this if it cleans up your data (e.g, if cell clusters become more biologically interpretable afterwards). Instead of regressing out patient ID, you can use [our integration tools](https://satijalab.org/seurat/v3.1/integration.html).
