### ISSUE TITLE
R crash during IntegrateData step when merging samples

### ISSUE THREAD

**Issue by jingzhangorg** [satijalab/seurat#3261]
Hello everyone,

I have around 200k cells from 26 samples to be merged. I can run FindIntegrationAnchors with 100G memory (although using > 9 hours). However, it crashed during the IntegrateData step. It seems to be a memory issue. I tried 160G, 200G, and 300G, and none of it works.

Is there an upper limit of cells in the IntegrateData step? 
I searched for previous issues on that, like https://github.com/satijalab/seurat/issues/1355, but still I can not solve this problem.

Thank you.

**Comment by cdarby** [comment]
There is not a set limit on the number of cells that can be integrated, you are limited by your resources. 

If you are certain that the problem is that you are running out of memory, you can try the reference-based integration strategy described in [the integration vignette](https://satijalab.org/seurat/v3.0/integration.html). This would additionally accelerate the FindIntegrationAnchors step. When you have 26 samples, the standard workflow takes a long time as it is making all-pairs comparisons.

If the program is crashing, please provide the list of the commands you used and the traceback/error message you receive.
