### ISSUE TITLE
Error in subset

### ISSUE THREAD

**Issue by swatibiswas86** [satijalab/seurat#3263]
COuld anyone please suggest where I am doing error with the subset  function. I want to retrieve data of celltype having Neutrophil

pbcm1= subset(pbmc, subset= CellType == 'Neutrophil')
 
But this command is giving all result

One more request to developer of Seurat, please don't update every now and then as you please. This is sometime pain in ***
No doubt this tools is very good but very poorly maintained :(

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but maybe I can help.  Can you please provide more detail as to what the error is that you are receiving?  I'm not quite sure from your post what the error you are experiencing is.

Also as note if you prefer not to update more frequently you can simply install the package from CRAN where the releases are more spread out and are only the major versions.  The github "develop" branch is specifically meant to be an in progress branch that is updated as the developers see fit.

Best,
Sam

**Comment by swatibiswas86** [comment]
Thanks sam. It is working fine after updating. I think Seurat team must learn something from you. 
This is one of the worst package in term of maintenance.

**Comment by samuel-marsh** [comment]
Hi,

Glad your issue was resolved.

I would have to say I absolutely disagree and think the entire Seurat team does an incredible job maintaining an extremely high demand software and their constant dedication to fixing bugs and adding new features at the speed that they do is fantastic (i.e. the ENTIRE spatial analysis branch and capabilities are technically in a development branch and not officially released).  I would also note that non-master branches of most if not all packages on github are intended to be just that, an in development branch where bugs may be present but new features are also present before release.  It is entirely up to you the user to chose whether you want to take that chance but that is not something unique to this package or the team behind it.

Also I would kindly say that when trying to get help from a development team insulting them may not be the best choice.

Best,
Sam
