### ISSUE TITLE
Merge 2 technical replicates (same cDNA library, but different sequencers) without renaming of barcodes

### ISSUE THREAD

**Issue by scideas** [satijalab/seurat#3288]
Hi! First off, hats off to your team for such a fantastic, user-friendly package, with excellent vignettes. 

After scouring all of the vignettes I could get my hands on, I've been unable to find a way to merge 2 technical replicates from the same 10x cDNA library, but run on different sequencers, while merging all counts from identical cell barcodes from each run. At the moment, all methods treat identical barcodes from these 2 replicates as separate cells.  Treating identical cell barcodes as distinct cells seems less accurate and reduces the actual depth of the experiment. Just wanted to check whether there are too many caveats with that approach when merging technical replicates from different sequencers. If they were from the same instrument, I'd normally just merge matrices and sum counts from identical barcodes. 

Thanks for the help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can help.  Maybe I'm not understanding your situation but I don't think that summing two count matrices from separate runs of the same library regardless of what instrument they came from is appropriate.  The reason is that the count matrices don't account for UMIs so you could still easily be double counting reads.  That is why it is important to generate count matrices using raw data from all sequencing runs together.  There will be potential additional concerns about doing this as you mentioned when they come from different sequencing platforms and I don't have any personal experience/advice to say one way or the other.  I would recommend posting on more bioinformatics inclined forum though (i.e. Biostars or bioinformatics stack exchange) because this isn't really question about Seurat.

Best,
Sam

**Comment by scideas** [comment]
Thanks, Sam- I will close this issue and re-post on Biostars. 

Also, to clarify, the data sets I'm merging are feature-barcode-count matrices, so I do have the UMI information for each cell (assuming I understood you correctly).

**Comment by scideas** [comment]
For what it's worth, I found a solution on the [10x website,](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/aggregate) which states:

"you should pass a list of FASTQ files from multiple sequencing runs of the same GEM well to the --fastqs argument of cellranger count."  

So It seems like count matrices could probably be combined afterwards without too dissimilar results. i'm going to try both ways and compare.

**Comment by samuel-marsh** [comment]
Hi @scideas,

Hi, yes that is what I was referring too when I said generating the count matrices from all sequencing runs together.  
When you say that your feature-barcode count matrices have the UMI information what do you mean?  What I was referring to is that in order to merge count values you need to know the UMI for every single transcript that is counted for every single gene and make sure that the barcode-UMI combination doesn't duplicate across outputs.  The output from cell ranger count does not have the UMI sequence included for each count as far as I know.  It contains the cell barcodes, gene names, and then numerical counts for each gene.  It doesn't actually contain the UMIs.  You would need the specific UMIs in order to combine the matrices accurately without potentially duplicating counts.

Best,
Sam

**Comment by scideas** [comment]
Thanks for the clarification. Makes perfect sense now.
