### ISSUE TITLE
AddMetaData can manipulate data matrix

### ISSUE THREAD

**Issue by DenizEsen** [satijalab/seurat#3292]
I wanted to find markers for cells that expressed my gene of interest vs the ones that did not, so I tried the following code:
```
idx <- which(object@assays$RNA@counts@Dimnames[[1]] == "geneName"
geneName <- object@assays$RNA@counts[idx, ] > 0
object <- AddMetaData(object, metadata = geneName, col.name = "geneName")
```

This is gives me a logical vector that I can use to differentiate between cells positive or negative for my target gene expression and worked fine with FindMarkers as intended.

However I noticed that setting `col.name = "geneName"` actually led to my target gene expression values to be set to either 0 or 1, which I noticed on violin plots. I changed the col.name to something else to resolve the issue.

So, this is not a huge issue, but I don't think AddMetaData should be able to access the data like this, hence why I'm submitting this issue.

**Comment by timoast** [comment]
You shouldn't be adding a metadata column with the same name as a feature in your dataset, it then becomes ambiguous whether you want to plot the metadata or feature when calling `VlnPlot` (or other functions). You're not correct however that the data is overwritten:

```r
library(Seurat)

a <- GetAssayData(pbmc_small)["MS4A1", ]
pbmc_small$MS4A1 <- 1
b <- GetAssayData(pbmc_small)["MS4A1", ]
all(a == b)
```
```
TRUE
```

(same thing if using `pbmc_small <- AddMetaData(pbmc_small, 1, col.name = "MS4A1")` rather than the dollar assignment operator)

We will discuss whether we should add a check for existing features with the same name before allowing metadata to be added to the object.
