### ISSUE TITLE
What is the "expression " means in the function WhichCells? Does it mean log transformed normalized value or the raw count? 

### ISSUE THREAD

**Issue by 1104964290** [satijalab/seurat#3311]
In the example : WhichCells(object = pbmc_small, expression = MS4A1 > 3), I want to know what is the mean of expression MS4A1 > 3. Does it mean the gene raw count > 3 or the log normalized count > 3?

In addition, how many slot does a seurat object have and their corresponding meaning?
Thanks for developping such a wonderful tool for single cell analysis.

**Comment by cdarby** [comment]
As written, the > 3 refers to the normalized data, because the default for WhichCells slot argument is "data". To filter based on raw counts, do `WhichCells(object = pbmc_small, expression = MS4A1 > 3, slot = "counts"`

To answer the second question, the contents of the Seurat object at any moment depend on what data you used to create the object and what analyses have been performed so far. Not all objects have all possible slots. You should not need to manually manipulate the slots of the object to perform your analysis, just know which ones exist and refer to them by name as I did above with "counts".
