### ISSUE TITLE
error in install seurat V3 using R 3.5.1

### ISSUE THREAD

**Issue by nayaracleite** [satijalab/seurat#3329]
Hi,
I am trying to install Seurat
install.packages('Seurat')
library(Seurat)
but I get the error message:

> install.packages('Seurat') 
Installing package into '/n/home00/nleite/apps/R_3.5.1_core' (as 'lib' is unspecified) 
Warning in install.packages :   dependency 'ROCR' is not available trying URL 'https://cran.rstudio.com/src/contrib/Seurat_3.2.0.tar.gz' 
Content type 'application/x-gzip' length 1482089 bytes (1.4 MB) ================================================== downloaded 1.4 MB  
ERROR: dependency ‘ROCR’ is not available for package ‘Seurat’ *
 removing ‘/n/home00/nleite/apps/R_3.5.1_core/Seurat’ 
Warning in install.packages :   installation of package 'Seurat' had non-zero exit status  The downloaded source packages are in 	'/tmp/RtmpWOueiE/downloaded_packages'
--

**Comment by Dragonmasterx87** [comment]
Nayara, you are doing a cran install of seurat. So you will need the most up to date version of its dependencies for it to function.....for instance in order to run Seurat v3.2 and above you need to have atleast R v3.6.3 installed. Which is why rocr a R package that functions on R v3.6 and above isn't installed and not functioning. This information is evidenced from its cran repo....[Rocr](https://cran.r-project.org/web/packages/ROCR/index.html) 

Also I'm not a dev.....but upgrading R will make 3.2 work.

🐉

**Comment by nayaracleite** [comment]
Thank you! 
I updated to R v3.6.3 and I was able to load the Seurat package.
