### ISSUE TITLE
integrating all cells from a batch or only the ones you are interested?

### ISSUE THREAD

**Issue by Diozao666** [satijalab/seurat#3351]
Hello

I have two batches, one with immune cells (batch 1) and another with immune cells and epithelial cells (batch 2). I want to find a specific cell type (cell A) from batch 1 in batch 2, so I used transfer anchors and transferdata to find them. I also want to integrate batch 1 with batch 2, but I don't care about any other cell type besides cell A in any of the batches. So before integrating, I kept only cell A found in batch 2, and integrated with the whole batch 1, then subsetted cell a from the integrated data and clustered them again with the integrated assay. Is this wrong? Should I have integrated the complete datasets and only then subsetted? Or integrate only cells A?

best,
Diogo

**Comment by jaisonj708** [comment]
On one hand, subsetting cell type A and then integrating will prevent any aberrant anchors from forming (assuming you are confident in your cell type annotation). There is also a small chance that by running integration/clustering/etc on only cell type A instead of the entire dataset, you can pick up on more of the variation within the cell type. On the other hand, by subsetting before integration, you run the risk of missing cells of type A or including a few cells of another type. Feel free to try both methods and check gene expression to see which produces the more reasonable result.
