### ISSUE TITLE
Read10X_Image: Support for SpaceRanger 1.1 aggregate function

### ISSUE THREAD

**Issue by lima1** [satijalab/seurat#3358]
Hi,

Latest SpaceRanger 1.1 comes with a new aggregate function to merge multiple slides. In Read10X_Image, "tissue_positions_list.csv" is currently hardcoded. For aggregate, it's called "aggr_tissue_positions_list.csv", located in the parent directory and includes all samples. The corresponding image files are put in sub-folders.

Best,
Markus

**Comment by andrewwbutler** [comment]
Hi Markus, 

Thanks for bringing this to our attention. We'll look into updating the corresponding Seurat functions to handle the merged slide output and report back here once we have a working solution.

**Comment by johnyaku** [comment]
Any progress on this enhancement?

**Comment by FADHLyemen** [comment]
@andrewwbutler Do you have any updates?
Thank you

**Comment by raman91** [comment]
@andrewwbutler any updates on this ? Thank you

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
