### ISSUE TITLE
RunUMAP: pip install umap-learn

### ISSUE THREAD

**Issue by saniavn** [satijalab/seurat#3361]
Hi-- I have tried to follow up SCTransform tutorial but I got an issue with RunUMAP step. I working on the server. R version 3.6. Would you mind letting me know how I can install it. I have tried following methods:

satijalab/seurat#1020

https://github.com/lmcinnes/umap/tree/4ac190d8c6804b25d6c7861b2aac2971027c5508

**Comment by samuel-marsh** [comment]
Hi,

What version of Seurat are you using?  The current version of Seurat uses the uwot package to run UMAP natively in R instead of relying on python umap-learn.

Best,
Sam

**Comment by saniavn** [comment]
Thank you for the reply. It is version 3. I installed uwot but I still have the same issue.

**Comment by samuel-marsh** [comment]
Hi,

What happens if you run the `RunUMAP` step and explicitly specify `umap.method = 'uwot'`?  Did you install Seurat via CRAN or github?

Thanks,
Sam

**Comment by mojaveazure** [comment]
Hi Saniya,

As Sam mentioned, we switched to using uwot instead of Python/umap-learn as of [Seurat  v3.1.0](https://github.com/satijalab/seurat/blob/master/NEWS.md#310---2019-08-20); we recommend you update your version of Seurat to the latest available [CRAN version](https://cran.r-project.org/package=Seurat) (currently v3.2.0). You can upgrade your version of Seurat with

```R
install.packages("Seurat")
```
in a fresh R session. If you are still having issues with `RunUMAP` after upgrading, please feel free to reopen this issue.
