### ISSUE TITLE
Data integration using SCTransform

### ISSUE THREAD

**Issue by saniavn** [satijalab/seurat#3371]
Hi, 

I used SCTransform to integrate samples but it looks the UMAPs look the same as the unintegrated data in terms of no apparent improvement of the batch effects (comparing experiment 1 and experiment 2).  I was wondering if you know what would be the possible reason.  

Thanks!

**Comment by timoast** [comment]
Do you mean that you ran the integration workflow with sctransform-normalized data, or you ran SCTransform with batch as a latent variable?

**Comment by saniavn** [comment]
Thanks for the reply! As a latent variable.

**Comment by timoast** [comment]
I'd suggest using the data integration methods we have developed in Seurat: https://satijalab.org/seurat/v3.2/integration.html

**Comment by duocang** [comment]
@timoast @saniavn 
I do not really get what is latent variable here.

My question for this post is can we use `SCTransform()` instead of `NoramlizeData()` and `ScaleData()` below?

I hvae tried both. The UMAP is different and I do not which I can trust. 

The screenshots are from [Integration and Label Transfer](https://satijalab.org/seurat/archive/v3.2/integration.html).
![image](https://user-images.githubusercontent.com/14146871/124269871-bf104500-db3b-11eb-90a2-80b808e31689.png)

![image](https://user-images.githubusercontent.com/14146871/124270019-ebc45c80-db3b-11eb-8e8e-210d27d5d693.png)
