### ISSUE TITLE
How does Seurat's AverageExpression() and muscat's aggregateData() differ from each other?

### ISSUE THREAD

**Issue by biobug16** [satijalab/seurat#3374]
Hi @timoast 
Can you please explain how does muscat's aggregateData() with fun = "mean" differ from Seurat's AverageExpression() and which one is better to get average expression of genes for each cluster?

Actually my doubt is Seurat's AverageExpression() should exactly be the same as muscat's aggregateData() with fun="mean". As both are just the average gene expression values from a group of cells from each of the identified cell-type or cluster. But when I checked it in my data, it was not the case.

May be I am getting it completely wrong. Can someone please correct me if I am missing something?

Thanks in advance.

**Comment by yuhanH** [comment]
Right. They have some difference.
If you set slot in `AverageExpression` with counts, these two methods are the same. 
```
pbmc_small

Idents(pbmc_small) <- "RNA_snn_res.1"
seurat.count.ave <- AverageExpression(pbmc_small, slot = "counts")

pbmc.sce <- as.SingleCellExperiment(pbmc_small)
sc.count.ave <- aggregateData(pbmc.sce,  assay = "counts" , by = "RNA_snn_res.1", fun = "mean")
head( seurat.count.ave$RNA)
head(assay(sc.count.ave))
```
If you use default slot which is data, these two methods results will be different.
Seurat will average  data slot in non-log space. https://github.com/satijalab/seurat/blob/72a0c7b61adcf1d6630db9e952bf8b0d4f979295/R/utilities.R#L269-L275

Then, when you set return.seurat = TRUE, output is in log-space , otherwise it's in non-log space.
