### ISSUE TITLE
Normalization on subset of cells vs on the whole dataset

### ISSUE THREAD

**Issue by papanikos** [satijalab/seurat#343]
Hello,

This is probably a more generic data pre-processing question, but with regards to scRNA-seq data.

I have a standard 10x counts matrix that contains cells from pooled samples. I also have a list of barcodes assigned to the original samples.
I would like to produce the tSNE plots for each sample, as a means of validating the assignment of barcodes to samples, reasoning that cells should show more or less similar clustering patterns between samples.

My questions is: Do I first pre-process the data for all cells and then subset on the respective barcodes per sample or do I subset the raw counts and treat each sample individually?

**Comment by satijalab** [comment]
If your goal is to look at samples individually, you should process them individually. However, for some steps (i.e. standard log-normalization), you will get the same answer either way. For other steps (data scaling), joint vs separate analysis may return different results.

**Comment by luluyadummy** [comment]
> If your goal is to look at samples individually, you should process them individually. However, for some steps (i.e. standard log-normalization), you will get the same answer either way. For other steps (data scaling), joint vs separate analysis may return different results.

Thank you for this great package it's been very helpful! I have a question on the same subject but is slightly different from the original question. I understand that the scaling step may give different results, but do you recommend running data scaling on the subset data if the goal is to zoom in to look at just one specific cell type/cluster rather than looking at the subset in the whole picture?
