### ISSUE TITLE
Identity of the RidgePlot

### ISSUE THREAD

**Issue by yueli711** [satijalab/seurat#3432]
Hello,

I used the RidgePlot to make the plot. What is the definition of "Identity", what is the mean of the "identity"? Is that possible I can delete "Identity"?

`RidgePlot(Plasma, features = c("UCP2"), group.by="tech", ncol = 3)`

Thank you in advance for your great help!

Please see attached file

Thank you!

Best,

Yue

![Screenshot from 2020-08-27 03-58-17](https://user-images.githubusercontent.com/40526984/91414892-3342d380-e81b-11ea-9d23-b975b933f0ff.png)

**Comment by samuel-marsh** [comment]
Hi Yue,

This is just generic label for the y axis stating that the y axis is a grouping identity.  As with other plots in Seurat RidgePlot is based in ggplot2 and therefore can be modified as you would any ggplot2 plot.  To remove the y axis the code you are looking for is:
`RidgePlot(Plasma, features = c("UCP2"), group.by="tech", ncol = 3) + theme(axis.title.y= element_blank())`

Best,
Sam

Also as fyi you have `ncol = 3` in your code but you are only plotting one feature so that setting won't actually matter.  In fact `RidgePlot` will actually default to `ncol = 3` until you plot more than 9 features so not necessary if you want 3 columns unless you have list of features greater than 9.
