### ISSUE TITLE
Option ncol not working correctly in VizDimLoadings()

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#3448]
For example, `VizDimLoadings(pbmc_small, dims=1:10, ncol=5)` returns 4 columns, not 5.

**Comment by samuel-marsh** [comment]
Hi Seurat Team,

Issue appears to be that function to automatically set column number depending on number of dims plotted overwrites the ncol provided in the function call https://github.com/satijalab/seurat/blob/72a0c7b61adcf1d6630db9e952bf8b0d4f979295/R/visualization.R#L3683-L3691

Can be fixed by swapping code section with similar code from `FeaturePlot` https://github.com/satijalab/seurat/blob/72a0c7b61adcf1d6630db9e952bf8b0d4f979295/R/visualization.R#L1306-L1317

Happy to submit PR with fix but figured it was probably easier on your end for something simple like this, but can if you prefer.

Best,
Sam

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
