### ISSUE TITLE
Color doesn't match with Dotplot() function

### ISSUE THREAD

**Issue by singletrips** [satijalab/seurat#3457]
![image](https://user-images.githubusercontent.com/31929730/91897341-1cabda80-ec68-11ea-89ab-050c4999e87a.png)
![image](https://user-images.githubusercontent.com/31929730/91897347-1f0e3480-ec68-11ea-9c59-e582576ec566.png)
In figure 1, I include B cells and T cells in my Seurat object and do DotPlot on genes of interest, while in figure 2, I include only T cells.  I found that colors for gene "HDAC4" are dark blue for groups "T.cell_Inflamed" and "T.cell_Healthy". But color for gene "HDAC4" is grey for the group "Tcell_Healthy" in figure 2. I was wondering why the colors don't math in two figures. Can you explain how the colors are mapped?

**Comment by samuel-marsh** [comment]
Hi,

The reason why the colors don't match is because the scales for average expression on the two plots are different.  The scales are going to be based on maximum and minimum values for the identities that you are plotting.  Therefore, only plotting a subset of the identities (as in plot 2) changes the scale.

Best,
Sam
