### ISSUE TITLE
Finding DEGs between genotypes based on data from hashtagged cells

### ISSUE THREAD

**Issue by Zig-E-Stardust** [satijalab/seurat#3481]
Hey there,
I have scRNA-seq data produced from mice from 3 different genotypes, with each genotype group composed of 3 different mice. The cells from each mouse in a group were "hashtagged" so as to allow differentiating between mouse 1, mouse 2 and mouse 3 (the cells from each genotype were pooled and run on a single lane in the 10X chip, but the hashtagging should allow identification of each of cells from specific mice).

Thanks to the vignettes on your website, I've already managed to integrate the data from the different genotypes, find clusters based on that integrated data and then find differentially-expressed genes between the WT and each of the two other genotypes within specific clusters. I've also been able to create tSNE maps etc. for cells labeled by different hashtags within each genotype. What I don't know, however, is how to combine these two so as to allow me to find out differentially-expressed genes (between the WT group and each of the two other genotypes) in specific clusters (cell types) in a manner that would take into account the hashing, i.e. would take into account the fact that each group consists of cells from 3 different individuals (instead of being considered as being from just one individual).

I wonder if you guys can help me with that :)

**Comment by cdarby** [comment]
Thanks for your question @Zig-E-Stardust . If I understand correctly, you are concerned that the differential expression test does not use the fact that the cells from each genotype come from 3 different individuals. I do not believe it is necessary to account for the 3 individuals in this part of your analysis because hopefully the integration procedure already removed any batch effects that may have been caused by having multiple individuals per genotype.  **Could you explain a bit more why you want your differential expression to take into account that cells from each genotype come from 3 individuals?** 

If you wanted to find differentially expressed genes between two individuals of the same genotype, you could of course use `FindMarkers` where one group is cells from one individual and one group is cells from another individual (optionally restricted to one cluster, if you wanted).

**Comment by Zig-E-Stardust** [comment]
Thanks for your detailed response, @cdarby :)
So, I may end up with additional ideas/needs, but in general, I'd like to try and use the fact that I have cells from 3 different individuals per genotype in order to get statistical tests which are more powerful, more reliable/generalizable or both. What I mean by that is that if a rather small change that does not lead to a statistically significant result when looking at the non-individual data turns out to occur consistently when taking into account the individuals comprising each group (e.g. a small increase in expression of gene X among each of the 3 individuals in group A compared with each of the 3 individuals in group B), it may then become statistically significant. On the other hand, if a relatively large difference that does lead to a statistically significant result when looking at the non-individual data turns out to stem from changes seen in only one of the three animal in one of the groups, that would suggest that the difference seen in the non-individual data is probably the result of a random event.

Regardless of that, I do have an additional question that I thought of while reading your reply: you've mentioned that the integration procedure should have taken care of removing batch effects possibly stemming from having multiple mice per genotype. However, in the FAQ section on the website there is a recommendation to use the "RNA" (non-integrated) assay when performing a DEG analysis between the two groups that comprise the integrated object (e.g. "immune.combined"). Would the data in the "RNA" assay (within the integrated object) be susceptible to batch effects that the data in the "integrated" assay (within that same object) would not be susceptible to?

**Comment by jaisonj708** [comment]
You should use the RNA assay for DE, since integration will introduce dependencies between data pts that violate the assumptions of DE tests. While the RNA assay will contain technical batch effects, it will also contain the meaningful differences between your samples, some of which may disappear after integration. Ultimately, the best way to proceed is to use RNA for DE, and then identify the most salient differences. 

For multi-sample, multi-group DE tests, you can refer to [Muscat](https://github.com/HelenaLC/muscat)
