### ISSUE TITLE
object 'pbmc.data' not found

### ISSUE THREAD

**Issue by agirgis16** [satijalab/seurat#3482]
Hi all, 

I'm trying to complete the [Guided Clustering Tutorial](https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html) and I'm running into some trouble. I hardly have any experience with coding; any explanation about this error message would be appreciated. Thanks in advance!
![r script](https://user-images.githubusercontent.com/70825437/92315613-ed190d00-ef9c-11ea-8045-d94d9791e03d.jpg)
![console](https://user-images.githubusercontent.com/70825437/92315614-edb1a380-ef9c-11ea-9db7-2936a2d8931a.jpg)

**Comment by RobertWhitener** [comment]
Hi agirgis,

This isn't an issue with Seurat, but a mistake in your basic R syntax.  I wouldn't worry too much, I was there too not that long ago, and I still consider myself a beginner.  However, I strongly suggest developing a better understanding of the R language before working with Seurat.  There are many available avenues for learning R, both free and paid versions, just a short google away.

I see several potential errors, but the biggest one, in your second picture, take a look at the fifth line.  You have

`pbmc.data <- Read10x(data.dir =`

You don't have a close parenthesis here, so the lines that come after aren't considered a new line of code.  This is indicated by the "+" signs at the beginning of the row, rather than a ">".

So you aren't actually creating the pbmc.data object, and therefore there is nothing to use to make the Seurat Object.

You must be absolutely sure that every open parenthesis '(' has a corresponding close ')' parenthesis.
