### ISSUE TITLE
graphs removed from Seurat object after subsetting features

### ISSUE THREAD

**Issue by NMikolajewicz** [satijalab/seurat#3491]
Hi!

I recently noticed some unexpected behavior with the subset function which I was hoping you could help explain, as I'm unclear whether this is an intended or a bug. 

I would like to subset my seurat object on a few select features: 

``` {r}
so <- subset(so, features = features.of.interest)
```

However, after this runs, I've noticed that the graph slot is NULL, indicating that all entries that were previously present had been removed. Although I know I can simply rerun FindNeighbors() to recompute the graphs, I would like to retain the original and use it in my downstream analysis.

Is there a reason the graphs are removed after subsetting?

Thanks,
NM

**Comment by andrewwbutler** [comment]
Hi,

Yes, this is the expected behavior when subsetting a Seurat object. Typically, subset removes cells from the Seurat object so the graphs were computed on a different set of cells than are currently in the object and therefore are removed to avoid misleading results. In the case where you're only subsetting features, I suppose retaining the graphs is less dangerous and we will consider adding this functionality in the future. 

In the mean time though, you could manually retain the graphs as follows:

```R
so <- subset(object, features = features.of.interest)
so[['graph_of_interest']] <- object[['graph_of_interest']]
```

**Comment by NMikolajewicz** [comment]
Thank you!

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).
