### ISSUE TITLE
Same DE gene independent of cell type

### ISSUE THREAD

**Issue by jcu2347** [satijalab/seurat#3515]
I am using Seurat V3 to identify differentially expressed genes (DEGs) in WT and KO cells. I notice that a handful of genes show up in the DE list, independent of cell type compared. I know this could be a bonafide biological phenomenon but I am also worried that it might have something to do with preprocessing steps (SoupX, integration, etc) prior to DE comparison. Has anyone encountered a similar situation?

**Comment by timoast** [comment]
You didn't provide the code you're running, so it's hard to say specifically whether there are any potential technical causes for this. If you're running DE on the RNA (not integrated assay), then the DE results are not being affected by the integration procedure. If you have replicates for each condition (WT, KO), then you would be able to say with more confidence whether the differences between WT and KO that are shared among cell types are genuine differences due to the condition, or whether they are due to batch effects.
