### ISSUE TITLE
PCA prior to UMAP

### ISSUE THREAD

**Issue by benxiahu** [satijalab/seurat#3527]
Hi,
   I followed this pipeline https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html to analyze scRNA-seq. My question is that PCA must be done before running UMAP, right?
Best,

**Comment by dlmatera** [comment]
correct, the UMAP process takes in PCs as variables, not the gene matrix ..as far as i understand

**Comment by dm8000** [comment]
I hope it is ok to pigbag on your question. I understand that if we used the gene matrix to run the UMAP it would take much longer to process. If I have access to a powerful computer, would it be ok to run the UMAP on the gene matrix? The reason I want to do this is because PCA takes into account linear correlation between genes, so I assume I might lose some data based on non-linear correlations.

**Comment by erzakiev** [comment]
@dm8000 You probably could use the uwot package to compute the UMAP directly, i'm not sure one can calculate umap from the count/data matrix in Seurat without computing PCA first
