### ISSUE TITLE
cell selector only able to draw boxes

### ISSUE THREAD

**Issue by rrkatreddi** [satijalab/seurat#3552]
Hi,

I am using cell selector to manually select cells in my single cell data. However, recently I am not able to select cells in different shapes. Cell selector is only allowing me draw rectangles/squares to select cells.  Did anyone else have same problem or any solution?

Thank you
Raghu

**Comment by samuel-marsh** [comment]
Hi,

Please see #3507.  Unfortunately no solution at this time with most up to date version of the package.

Best,
Sam

**Comment by alikhuseynov** [comment]
I think many users would be interested to draw a convex hull or something like that to be able to select what is needed. Especially for spatial data (totally agree with @RobertKSuter )

For image-based (or in situ-based techs like Xenium) spatial data, the `SeuratObject::Crop` function (non-interactive) only allows to crop a box, here also an irregular shape selection (given custom xy coordinates) is need to crop the part of FOV.
I made a small function using [`sf`](https://r-spatial.github.io/sf/articles/sf1.html) package to crop using xy coords that make a convex hull and all the cells inside there are kept. This is useful also for QC reason, since tissue are sometimes folded or teared/disrupted due to cutting.
I can share the script if people are interested.
Thanks

**Comment by riccardoguidi87** [comment]
Any Update on this? Re: can we use ROIs other than boxes to select cells via CellSelector()?

**Comment by RobertKSuter** [comment]
To get around this, I created a small script using matplotlib...

`import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from matplotlib import colors as mcolors
from matplotlib import path
from matplotlib.collections import RegularPolyCollection
from matplotlib.widgets import Lasso


class LassoManager:
    def __init__(self, ax, data):
        # The information of whether a point has been selected or not is stored in the
        # collection's array (0 = out, 1 = in), which then gets colormapped to blue
        # (out) and red (in).
        
        # added...
        self.data = data
        self.selected_points = [] # list to store selection
        self.collection = RegularPolyCollection(
            6, sizes=(.1,), offset_transform=ax.transData,
            offsets=data, array=np.zeros(len(data)),
            clim=(0, 1), cmap=mcolors.ListedColormap(["tab:blue", "tab:red"]))
        ax.add_collection(self.collection)
        canvas = ax.figure.canvas
        canvas.mpl_connect('button_press_event', self.on_press)
        canvas.mpl_connect('button_release_event', self.on_release)
    
    def callback(self, verts):
        data = self.collection.get_offsets()
        mask = path.Path(verts).contains_points(data) # added rks
        self.collection.set_array(mask)
        # self.collection.set_array(path.Path(verts).contains_points(data))

        # Append selected points to the list
        selected_indices = np.where(mask)[0]
        self.selected_points.extend(self.data[selected_indices].tolist())

        canvas = self.collection.figure.canvas
        canvas.draw_idle()
        del self.lasso

    def on_press(self, event):
        canvas = self.collection.figure.canvas
        if event.inaxes is not self.collection.axes or canvas.widgetlock.locked():
            return
        self.lasso = Lasso(event.inaxes, (event.xdata, event.ydata), self.callback)
        canvas.widgetlock(self.lasso)  # acquire a lock on the widget drawing

    def on_release(self, event):
        canvas = self.collection.figure.canvas
        if hasattr(self, 'lasso') and canvas.widgetlock.isowner(self.lasso):
            canvas.widgetlock.release(self.lasso)
    
    def export_selected_points(self, filename='~/Documents/SuterLab/projects/SCI/selected_points.csv'):
        # Convert the list of selected points to a DataFrame
        selected_df = pd.DataFrame(self.selected_points, columns=['x','y'])
        
        # Export the selected points to a csv file
        selected_df.to_csv(filename, index=False)
        print("Selected points saved to", filename)

embeddings = pd.read_csv(
        'embeddings.csv'
        )

new_column_names = ['cellBarcode', 'Spatial_1', 'Spatial_2']
embeddings.columns = new_column_names

max_1 = embeddings['Spatial_1'].max
print('Max spatial_1')
print(max_1)

min_1 = embeddings['Spatial_1'].min
print('Min spatial_1')
print(min_1)

max_2 = embeddings['Spatial_2'].max
print('Max spatial_2')
print(max_2)

min_2 = embeddings['Spatial_2'].min
print('Min spatial_2')
print(min_2)

spatial_coords = ['Spatial_1', 'Spatial_2']
toPlot = embeddings[spatial_coords].values

if __name__ == '__main__':
    np.random.seed(19680801)
    ax = plt.figure().add_subplot(
        xlim=(-17103, -1000), ylim=(-17000, -1000), title='Lasso points using left mouse button') # adjust your bounds to your data
    manager = LassoManager(ax, toPlot)
    plt.show()

    manager.export_selected_points(filename = "lassoedCellIDs.csv")`

I export the embeddings or spatial coordinates as a csv with cellID, x and y columns, import here, and after using the lasso tool to select cells, a csv file is written with the selected cell IDs. Then you can use that csv to identify WhichCells to put a label on or subset. Hope this helps. We've also modified this script above so that the cells in the popup gui can be colored by a select feature (like %rRNA in a curio seeker tile). Likely you will have to adjust the x and y limits to that of your data.
