### ISSUE TITLE
DoHeatmap clusters

### ISSUE THREAD

**Issue by NDUFB11** [satijalab/seurat#3553]
Hello everyone, 
I created a heatmap based on the top expressed genes in each cluster using the following code:
```
top10 <- pbmc.markers %>% group_by(cluster) %>% slice_max(n = 300, order_by = avg_logFC)
DoHeatmap(seuratobject, features = top10$gene) + NoLegend()

```
the warning message is the following 
```

Warning message:
In DoHeatmap(seuratobject, features = top10$gene) :
  The following features were omitted as they were not found in the scale.data slot for the SCT assay: CLIP1, MIDN, AKIRIN2, LASP1, R3HDM2, LAPTM4A, TMEM9B, ACTB, NCOA4, TAOK1, SKAP2, SNAP23, LACTB, PTGS2, KLF6, PAK1, ZMIZ1, CAPN2, RNF130, RASGEF1B, ADRB2, CRTAP, LIPA, C9orf72, IRS2, GLUD1, PLXNC1, EPB41L3, RGS19, HLA.DMB, DPYSL2, LILRA5, PPT1, DPYD, JAML, [... truncated]
```

I'd like to show the gene of my interest in the list but for some reason is cutted out from DoHeatmap.
I can see it in the top10 list but not in the map, Why is it not present in the scale.data slot? Do you have any suggestion about how can I prevent to loose it in the heatmap? 

I appreciate any help 

thanks

**Comment by samuel-marsh** [comment]
Hi,

When you run `SCTransform` you need to specify an additional parameter otherwise only the variable genes will be included in the scale data slot.  Add `return.only.var.genes = FALSE` to the function call and that should solve the issue.  More information on this and other optional parameters can be found in the manual entry for `SCTransform`.

Best,
Sam
