### ISSUE TITLE
mitochondria in single nuclear RNAseq

### ISSUE THREAD

**Issue by rtyags** [satijalab/seurat#3586]
Hi,

I am working with single nuclear RNAseq from 10X. for snRNAseq, does it make sense to do mitochondrial filtering? I thought it probably doesn't make sense since we are working with data from nuclei rather than whole cells, but I do see some expression of mito genes in my data.

Also, is it preferable to just filter the cells based on percent.mt or to regress it out? I see people using it directly in vars.to.regress, but how does that work? If it uses percent.mt to modify expression value of all genes, then it probably isn't appropriate for most genes that aren't coming from mitochondria. or does that only normalize the value of mtgenes to bring them on the same level as nuclear genes?

**Comment by jaisonj708** [comment]
Sometimes there is minor extranuclear contamination in scRNA-seq data. In this case, you can either remove these features or regress them out. Regressing out will alter the expression levels of other features if they are correlated to mitochondrial expression levels. Since most features in scRNAseq are not correlated to mitochondrial contamination, the regression procedure should not affect a vast majority of features. Simply removing mito features is likely a reasonable option here.
