### ISSUE TITLE
Why split the combined object into a list for analysis

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#3592]
Hi,
I  have a very basic question. Why should one split ( option a) in the combined analysis and do normalization on each of the element instead one does the normalization on the combined whole data set( option b) and then overlay the sample identification. 
 **option a:**
```
pancreas.list <- SplitObject(panc8, split.by = "tech")
pancreas.list <- pancreas.list[c("celseq", "celseq2", "fluidigmc1", "smartseq2")]
for (i in 1:length(pancreas.list)) {
    pancreas.list[[i]] <- SCTransform(pancreas.list[[i]], verbose = FALSE)
}
```

**option b :**
```
panc8<- SCTransform(panc8, verbose = FALSE)
```

What will be the impact on the analysis and its output if we choose option b

**Comment by jaisonj708** [comment]
Since the datasets in `pancreas.list` will be treated separately for downstream processing (e.g, PCA and integration), they should also be scaled/normalized separately. Furthermore, running SCTransform on the merged object rather than each individual dataset will result in the retention of a lot more batch effect.

**Comment by Jayjay601** [comment]
Can you elaborate on how running SCTransform on a merged object will retain more batch effect? My impression is that the gene information sharing will presumably be more accurate as you have more samples in the merged object.
