### ISSUE TITLE
generating a specific matrix

### ISSUE THREAD

**Issue by aelias1** [satijalab/seurat#3599]
I was wondering for a specific cluster if you could output a matrix where it looks like this:

               Sample1.   Sample2.  Sample3
Gene1         4                0                20
Gene2         0               0                  0
Gene3        50              52                 53
ETC

**Comment by cdarby** [comment]
1. To make a new Seurat object with a subset of the cells, say from one cluster, use the `subset` function in Seurat. Check the documentation to see how to use the arguments to select the particular cells you want based on metadata or idents or cell names.

2. To get a matrix from your new subsetted Seurat object, use the `GetAssayData` function. I think you want the counts matrix because you used integers in your example, so make sure to specify `slot=counts` if you want the counts matrix.
