### ISSUE TITLE
Question about CLR normalization of ADT data in WNN - Seurat v4

### ISSUE THREAD

**Issue by rstaupe** [satijalab/seurat#3605]
Hello!

As always, thanks for maintaining the package. It's a tremendous resource for everyone in the single cell community. 

I have a question about the vignette for Weighted Nearest Neighbor Analysis in Seurat v4. Specifically, my question is about the below code:

`bm <- NormalizeData(bm, normalization.method = 'CLR', margin = 2) %>% 
  ScaleData() %>% RunPCA(reduction.name = 'apca')`

I'm wondering why you are using margin = 2 to normalize the data across cells rather than the default of margin = 1 to normalize the data across the features? Any additional insight as to why you are doing this and the advantage to normalizing in this way to the weighted nearest neighbors graph would be much appreciated.

Thanks!

**Comment by satijalab** [comment]
Setting margin=2 normalizes for differences in ADT depth across cells. In some of our earliest CITE_seq experiments we had small antibody panels and sequenced them to saturation, so we saw less variance here. As the panels grow, we typically use margin=2. While there are other published strategies for CITE-seq normalization, finding a single solution that works for a large variety of datasets remains challenging , but please stay tuned for more updates

**Comment by malisas** [comment]
Hi there, I'm sorry if I am asking the obvious, but I am still confused about the `margin` argument for CLR.

I _think_ that the following is the correct interpretation of the margin setting, but I am not sure. Would you be able to clarify?:

- `margin=1` means "perform CLR normalization for each feature independently" 
- `margin=2` means "perform CLR normalization within a cell" 

Here's my visualization of the above:

![image](https://user-images.githubusercontent.com/16787492/106541297-a5989d80-64b6-11eb-8a08-846de1310afb.png)

The above interpretation is consistent with how I interpret the [v3.0 multimodal vignette](https://satijalab.org/seurat/archive/v3.0/multimodal_vignette.html), which seems to imply that the default `margin=1` means "perform CLR normalization for each feature independently"
![image](https://user-images.githubusercontent.com/16787492/106537741-cad5dd80-64af-11eb-9d2b-73f2ea7a49da.png)

I also manually computed the CLR transformation using the [code in your repo](https://github.com/satijalab/seurat/blob/b56d194939379460db23380426d3896b54d91ab6/R/preprocessing.R#L2336) and found that my manual results were consistent with the above interpretatuion.

However, when I read the help page for `?NormalizeData`, I interpret the opposite meaning:
```
margin | If performing CLR normalization, normalize across features (1) or cells (2)
```
When I read "across features" I take that to mean "within a cell, for each cell independently".

Can you please clarify which interpretation is correct? Thanks!

****************************************

Assuming that `margin=1` means "perform CLR normalization for each feature independently", I am trying to follow the logic in your answer above:

It seems that you are saying that when you have small antibody panels you can sequence to saturation, so you get a more accurate “count”. So if you see a feature has a raw count of 10 in cell A but a count of 100 in cell B, it follows that cell B has higher levels of the feature than cell A. You can then use CLR with `margin=1`. A transformed value of 0 then means that a cell expresses the geometric mean of that feature. This helps to put all features on the same-ish scale.

But when you have a lot of different antibodies in one experiment, you can’t sequence to saturation and so that leads to more variation in ADT depth between cells. I think the logic here is that cell A might have a geometric mean of ADT counts of 10, whereas cell B might have a geometric mean of ADT counts of 10,000. If you see a feature has a raw count of 10 in cell A but a value of 100 in cell B, it doesn't necessarily follow that cell B has higher levels of the feature than cell A. It makes sense to me that you would want to first adjust each cell independently (`margin=2`) to control for the cell-specific geometric mean. If you tried to use `margin=1`, you would be ignoring the differences in ADT depth from cell to cell.

I hope I am interpreting correctly. Thank so much for your help.

**Comment by dn-ra** [comment]
I'd like to add my voice to the discussion around normalisation here because I think the language used in the description is misleading. 
When the manual writes 
> margin | If performing CLR normalization, normalize across features (1) or cells (2)

 that to me indicates that setting margin as 1 will normalise one cell at a time by holding a cell constant and use a normalizing factor that is calculated by the vector crossing all features.
 
and likewise for margin =2 (normalising across cells), which to me sounds like you are performing normalising for features independently across all cells present.

But it's actually the opposite. I think it would be much clearer to the user if the manual wrote that margin = 1 normalises _within_ features and margin =2 normalises _within_ cells.

Love the software. Thanks for your efforts in maintaining it.
