### ISSUE TITLE
How to correct batch effects selectively for a few samples in a group

### ISSUE THREAD

**Issue by ksr2018** [satijalab/seurat#3623]
Hi all, 
I need some advice on how to correct batch effects using Seurat v3's integration pipeline.
I have multiple samples from different time-points as noted below:
Day 4 WT-1
Day 4 WT-2
Day 4 mutant
Day 6 WT
Day 6 mutant
Day 10 WT 
Day 10 mutant
Is there a way to correct batch effects only for Day 4 WT-1 and Day 4 WT-2 samples but not the others and still show all of them in the same UMAP?

Thank you.

**Comment by jaisonj708** [comment]
Yes, this is possible but not particularly common, since you could be selectively removing batch effects between some samples and not others. To do this, simply integrate Day WT-1 and -2, and then merge the integrated result with the remaining samples. You will need to rename the assays before merging so that they match.
