### ISSUE TITLE
Merge vs integrate vs merging then integrating (how to work with more than 2 samples is not well described) 

### ISSUE THREAD

**Issue by BrianLohman** [satijalab/seurat#3631]
Hello, 

I've now spent quite a bit of time looking over the vignettes and issues and it seems that in general how to handle multiple samples, multiple treatments, and multiple treatments with multiple samples remains unclear. 

Specifically, one issues is when to use merge and when to use integration ( #3441, #2676) and the response has been: use integration "when you need to account for batch effects". Can you please provide an example of what batch effects look like? The vignette for PBMC stim vs control does not show WHY integration is  necessary. Integration makes intuitive sense when working with data from different sequencing methods but the vast majority of data is all 10X and from the same chemistry and the same flow cell. In such cases, when should we use merge or integration? 

Furthermore, when there are multiple samples within each treatment what is the best practice? The PBMC stim vs control has only one sample in each treatment. If each treatment had 3 samples what would the vignette look like? Merge within treatments then integrate across treatments? Follow some litmus test as determined above? 

The vignette for PBMC stim vs control also contains no QC preprocessing (e.g. filtering cells for percent mitochondria, number of genes detected or total RNAs detected). When should this take place? 

The generation of data gets cheaper all the time so updating the docs to show how to handle multiple samples within multiple treatment would be a welcome addition.

Thank you,

Brian

**Comment by Sergio-ote** [comment]
From my point of view, I would only use merge alone if I am dealing with technical replicates. If you are dealing with multiple samples or experiments, I would definitely expect to have some batch effects due to inter-sample variability (even if they come from the same anatomical location) or inter-experimental variability (i.e. preparation, sequencing technology, and other unpredictable sources of variability). So, in short, integration I something you should practice anytime you are able to.

**Comment by jaisonj708** [comment]
Thanks for your question. In general, we recommend integrating when origin or preparation of your samples is sufficiently different so as to produce inter-sample variation that is "irrelevant" and that you wish to remove. For instance, you may want to remove variation caused by the use of different technologies, different donors, or even different disease states (i.e, to look at cell type distribution in a common subspace, to annotate in a common subspace, or to produce a dimensional reduction with greater signal-to-noise by taking advantage of all the cells in your data). In most cases, it is relatively clear whether an undesired batch effect is present - simply merge your samples and check whether cells of the same known cell type (defined by well-known "relevant" variation) are clustering separately. As for your second question, QC preprocessing should be done prior to integration.

**Comment by BrianLohman** [comment]
Hi @jaisonj708,

Thanks for your reply. To explore this further I have provided some code and plots below using the example PBMC data from the control vs stim integration vignette. Broadly, it still is unclear why integration is necessary and what we gain from this. 

The vignette aims to find differences between two treatments which is contrary to your statement that we would use integration to remove differences between samples/sample types (although the vignette does annotate cells in a common space that is a means to and end: finding differences in expression between clusters/cell types). Why would one look at the below UMAP plot split by treatment and think, "ah, I need to run integration" rather than "okay, that's the effect of simulation, now I can run my DE testing to find out what's going on" (here we are assuming that the samples are run on the same technology, lane, ect., so no technical noise).  

Coloring the UMAP plot sans integration by marker genes provided in the vignette also shows very similar information as coloring them post integration; we get an idea of what clusters are what cell type. This case is more cut and dry than most because of the very sharp, distinct clustering. 

I understand why integration would be very helpful for removing technical noise due to technology but using it as preprocessing in an analysis that aims to find differences between control and stimulated cells that were built with the same technology seems odd. 

Thank you for your continued assistance. 

```
library(Seurat)
library(SeuratData)
library(cowplot)
library(patchwork)

InstallData("ifnb")

data("ifnb")
ifnb.list <- SplitObject(ifnb, split.by = "stim")

# merge stim and ctl into one object
immune.combined = merge(ifnb.list[[1]], ifnb.list[[2]], add.cell.ids = c("CTL", "STIM"))

# Run the standard workflow for visualization and clustering
immune.combined = NormalizeData(immune.combined, normalization.method = "LogNormalize", scale.factor = 10000)
immune.combined = FindVariableFeatures(immune.combined, selection.method = "vst", nfeatures = 2000)
immune.combined <- ScaleData(immune.combined, verbose = FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)

# t-SNE and Clustering
immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:20)
immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:20)
immune.combined <- FindClusters(immune.combined, resolution = 0.5)


# Visualization
p1 <- DimPlot(immune.combined, reduction = "umap", group.by = "stim")
p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE)
plot_grid(p1, p2)

FeaturePlot(immune.combined, features = c("CD3D", "SELL", "CREM", "CD8A", "GNLY", "CD79A", "FCGR3A", 
                                          "CCL2", "PPBP"), min.cutoff = "q9")

```

![image](https://user-images.githubusercontent.com/15367032/98141115-7d7fab00-1e83-11eb-9854-6252de33b2ca.png)

![image](https://user-images.githubusercontent.com/15367032/98141225-a011c400-1e83-11eb-866e-2df73f8b188c.png)

**Comment by qins** [comment]
@BrianLohman I think you are right, "case" and "control" cannot be simply integrated.
Even common cluster/cells should be different in them, biologically.
