### ISSUE TITLE
NULL sample.tree for integration

### ISSUE THREAD

**Issue by stacyhung** [satijalab/seurat#3662]
I'd like to inspect the order of pairwise dataset integration by extracting the sample.tree value using:

```r
my_integrated_dataset@tools$Integration@sample.tree
```

However, I just get NULL, and also noticed that all values associated with `my_integrated_dataset@tools$integration` are NULL as well.  This looks like a bug?  I can only find one other post where sample.tree has been used (#1400), but very little details are given about the command and what the output should look like.

I've tried my workflow on the "pan8" dataset from SeuratData, and obtain the same result.

My sessionInfo:
```r
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.6

[1] panc8.SeuratData_3.0.2  ggplot2_3.3.2           pbmc3k.SeuratData_3.1.4 SeuratData_0.2.1       
[5] future_1.17.0           sctransform_0.3.1.9002  Seurat_3.9.9.9003      
```
Any insight would be greatly appreciated!

**Comment by stacyhung** [comment]
It looks like using a reference in the FindIntegrationAnchors function causes the problem - i.e. running this line of code instead will give a NULL sample.tree

```r
anchors <- FindIntegrationAnchors(obj.list, anchor.features = features, reference = c(3), normalization.method = "SCT")
```

Is there a way around this?

**Comment by timoast** [comment]
If you specify a single reference, the sample tree is not needed since there's only one possible order for the integration (each query dataset mapped onto the reference). If you have multiple reference objects, they will first be integrated into a single object and the query objects mapped onto the integrated reference. In that case, where the number of reference objects is >1, a sample tree is constructed. We currently don't return that sample tree but I've pushed an update to the release/4.0.0 branch that will ensure that the sample tree is stored in the integration output when using reference-based integration.
