### ISSUE TITLE
Changing cell.ids according to orig.ident on a seurat object

### ISSUE THREAD

**Issue by nayaracleite** [satijalab/seurat#3678]
I have a seurat_merged_object with 10 seurat_obejcts, how can I change the cell.ids according to the orig.ident?

> table(merged_seurat@meta.data$orig.ident)
HPAP019_raw_feature_bc_matrix 
5203
HPAP020_raw_feature_bc_matrix 
14276 
HPAP021_raw_feature_bc_matrix 
19268                  
HPAP023_raw_feature_bc_matrix 
7582 
HPAP024_raw_feature_bc_matrix 
3638                  
HPAP026_raw_feature_bc_matrix
1111 
HPAP028_raw_feature_bc_matrix 
5664
HPAP032_raw_feature_bc_matrix 
3208 
HPAP034_raw_feature_bc_matrix 
492
HPAP038_raw_feature_bc_matrix 
3170

> head(merged_seurat@meta.data)
                                                       orig.ident nCount_RNA
ND_ND_ND_ND_ND_AAACCTGAGACTGTAA-1_1 HPAP019_raw_feature_bc_matrix        839
ND_ND_ND_ND_ND_AAACCTGAGGCGCTCT-1_1 HPAP019_raw_feature_bc_matrix      18827
ND_ND_ND_ND_ND_AAACCTGAGTTACCCA-1_1 HPAP019_raw_feature_bc_matrix       9335

**Comment by Dragonmasterx87** [comment]
Hi @nayaracleite, (im not a seurat dev) I think an easier way to do this is to add sample-specific metadata and cell IDs prior to merging. If you have access to the individual 10 Seurat objects or files. You can use `RenameCells` to perform this. RenameCells is only to seperate cells having similar barcodes, for plotting data you need metadata columns that specify how you want your data split or grouped.

Otherwise, you can assign the current active identities to a new or existing metadata column using `merged_seurat$sampletype <- Idents(merged_seurat)` where the new metadata column is called "sampletype". As you want your orig.idents to be mapped and im not sure at this point what your active identities are (looks like orig.idents though), you may want to be sure your current active identities are set to be orig.ident, so just do `Idents(merged_seurat) <- "orig.idents"` prior to running the command above.

**Comment by nayaracleite** [comment]
Hi @Dragonmasterx87, 
Thanks for the suggestion! I added to each seurat_obj a cell.id prior to merging. It worked really well.
