### ISSUE TITLE
data vs scale.data slot

### ISSUE THREAD

**Issue by A-Catarina** [satijalab/seurat#3680]
Hi,

Thank you so much and congratulations for creating such a useful tool, constantly updating it!

In my work, I want to subset a population of cells based on a specific gene expression, splitting the dataset in positive and negative cells. My question is, for this purpose, is it more accurate to use the data or scale.data slot? 
In this context, I would appreciate if you could briefly explain why are heatmap visualizations created with scale.data (and not other visualizations) as I find it to often originate divergent results in comparison to DE results or if data was used.

Thank you in advance.

Kind regards,
Catarina

**Comment by jaisonj708** [comment]
For your purposes, it doesn't matter if you use scaled or unscaled data to split your dataset on 1 feature, since the scaling transformation preserves ordering. For example, splitting data that has been scaled between -1 and 1 with a "splitting threshold" of 0 would be the same as splitting unscaled data that varies between 0 and 1000 with a threshold of 500
