### ISSUE TITLE
Integration for large data set 

### ISSUE THREAD

**Issue by gregszetoAI** [satijalab/seurat#3683]
Hi 

I am looking at trying to integrate and find degs by cell type between disease and healthy conditions for 48 scRNAseq /ATACseq samples with approx 20k cells each. I've implemented SCT per sample in a list, performed rPCA, and specified 4 reference datasets for more efficient integration. I'm still getting crashes or matrix size errors.

My Q- is it better to perform integration independently on  each cell type level, or is it better to iteratively subset a fraction of each cell type and perform integration on them in batches and then integrate the batches? In the latter I imagine an advantage would be preserving global data structure between cell types. But I'm thinking this might not matter if we don't perform degs between cell types, but degs between disease status for each cell type. 

Or will either approach result in the same degs per cell type?

**Comment by jaisonj708** [comment]
It seems like you have over 1 million cells in your data, in which case some memory-related issues arise, perhaps related to RAM limitations or others issues that are independent of Seurat (e.g, if you receiving an error that resembles `long vectors not supported`). 

Either of the proposed options is reasonable, particularly if you are only performing DE analysis on the same cell type, and if you are confident about your cell type calls. Your second option of integrating batches hierarchically is very similar to what our integration method is doing anyways, except for the fact that anchors are found between uncorrected counts rather than integrated counts, and that the hierarchical sample tree is of course constructed automatically instead of manually imposed.
