### ISSUE TITLE
DOHeatmap for FindMarkers result 

### ISSUE THREAD

**Issue by Dahlia90** [satijalab/seurat#3701]
#2907 
I am having trouble generating a heatmap from the result of FindMarkers between two clusters. 

I tried to extract some info from the csv file but I couldn't determine which parameter is important (avglogfc, pct1, pct2, pvalue or adjusted pvalue). Also, I didn't know which parameter to use to use the group_by function. That's one of my attempts:

clus4vs3 <- cluster4_3.markers$p_val %>% group_by(pct.1) %>% top_n(n = 10, wt = avg_logFC) Error in UseMethod("group_by_") : no applicable method for 'group_by_' applied to an object of class "c('double', 'numeric')"

Then, following the referenced issue #2907, I tried to use group.by option, but I didn't know which "ident" should I place in the command line?

**Comment by timoast** [comment]
Here you're extracting one column of the dataframe and piping it into the following functions, which expect a dataframe rather than a vector. There are clear examples of how to create a heatmap on the [Seurat website](https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html), so I suggest you take a look there.
