### ISSUE TITLE
Seurat4  Error: Cannot find 'map' in this Seurat object in PBMC reference

### ISSUE THREAD

**Issue by bassanio** [satijalab/seurat#3707]
Hi,

I have downloaded the PBMC reference dataset and I tried to run the below SCT command as in the Azimuth online script as standalone run. 
```
Data <- SCTransform(
  object = Data,
  assay = "RNA",
  residual.features = rownames(x = reference$map),
  method = 'glmGamPoi',
  ncells = 2000,
  n_genes = 2000,
  do.correct.umi = FALSE,
  do.scale = FALSE,
  do.center = TRUE
)
```
I got the folowing error. 
```
Error: Cannot find 'map' in this Seurat object
Execution halted
```

**Comment by yuhanH** [comment]
reference you downloaded from Azimuth should be a list. The list has an element called map, which is a seurat object.
`rownames(reference$map)` should return 5000 variable genes. Could you check what `reference` is in your case?
It should be a list rather than seurat object

Do you download reference by this way?
`reference <- LoadReference(path = "https://seurat.nygenome.org/references/pbmc/")`

**Comment by bassanio** [comment]
I have made a copy by downloading the following reference "https://atlas.fredhutch.org/data/nygc/multimodal/pbmc_multimodal.h5seurat"

Then I used this function: 
```
reference <- LoadH5Seurat("/project/mv83/Software/Seurat4/PBMC_REF/pbmc_multimodal.h5seurat")
```

**Comment by yuhanH** [comment]
I see...
the reference you loaded is a seurat object, so the script from Azimuth cannot be applied directly. 
You can follow our mapping vignette:  https://satijalab.org/seurat/v4.0/reference_mapping.html
But you can use the above code, you need to replace `rownames(x = reference$map)` to `rownames(reference[["spca"]]@feature.loadings)`
