### ISSUE TITLE
Is Scaledata step unnecessary when using fastMNN to correct batch effect?

### ISSUE THREAD

**Issue by Lukadon77** [satijalab/seurat#3747]
Hi,

I tried to remove the batch effect of multiple single cell RNA-seq datasets using fastMNN in Seurat tutorial (https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/fast_mnn.html), I noticed there is no ScaleData step in the tutorial: 

ifnb <- NormalizeData(ifnb)
ifnb <- FindVariableFeatures(ifnb)
ifnb <- RunFastMNN(object.list = SplitObject(ifnb, split.by = "stim"))
ifnb <- RunUMAP(ifnb, reduction = "mnn", dims = 1:30)
ifnb <- FindNeighbors(ifnb, reduction = "mnn", dims = 1:30)
ifnb <- FindClusters(ifnb)

Does fastMNN cannot regress the variable parameters among all the cells, including mitochodrial percent, UMI counts, etc? 
What will happen if I add the Scaledata step before RunFastMNN step?

**Comment by satijalab** [comment]
FastMNN performs its own internal scaling. I do not believe it is possible to regress out other variables in the process. Running ScaleData in Seurat should not change the. result

**Comment by shahrozeabbas** [comment]
Had a follow up to this....you mentioned that it shouldn't change the result, but would you be able to effectively run `ScaleData` for the purpose of regressing out some variation in the corrected counts? I assume it wouldn't change the result if you just ran `ScaleData` without any additional parameters. 

I ask because I used `FastMNN` to integrate my datasets and subset out a particular cell type of interest. I want to regress out mitochondria percentage, cell cycle, etc. on the subset, but am not sure how to proceed. Any thoughts?
