### ISSUE TITLE
Output out of order in vector of cells.highlight and cols.hightlight of Dimplot

### ISSUE THREAD

**Issue by karenlawwc** [satijalab/seurat#3750]
When I tried to use cells.highlight and cols.highlight, if I pass in a vector with 9 groups, then the respective dimplot graph will show up in correct order with the color and label of the 9 groups. However, if I pass in more than 9 groups (i.e. anything above 10), the order will be messed up as it is showing in sequential order and group 10 will become group 2 and the rest of the group will be shifted by 1.  Please see attached png for reference. May I ask is there a way to fix the order of the output instead of changing the order with hardcode by myself? I used the following command.
DimPlot(project,reduction = "umap",pt.size = 0.5,cells.highlight = list(A,B,C,D,E,F,G,H,I,J),cols.highlight = c("red","yellow","blue","green","darkorchid","orange","grey0","deeppink","gold4","darkgreen"))
As you can see the color "gold4" is automatically assigned to group 10 while group 2 is assigned with "deeppink" and the rest of the groups are shifted by one color. Any insight is welcomed! Thank you very much

![Out_of_order](https://user-images.githubusercontent.com/73906815/99605038-b3f91200-29bb-11eb-995c-b4ec650736c1.png)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but, if you name the groups "Group_01" instead of "Group_1" does that solve the issue? 

Best,
Sam

**Comment by karenlawwc** [comment]
Even if I did the group naming manually, it would still automatically assign the second color I specified in my command to group 10 instead of group 2 so it will not work.

**Comment by samuel-marsh** [comment]
Hi Seurat Team & @karenlawwc,

I can confirm this issue is reproducible using pbmc3k from SeuratData using the following example adapted from vignette (resolution increased to create higher number of clusters).
```
pbmc3k <- LoadData("pbmc3k")

pbmc3k <- pbmc3k %>% 
  NormalizeData() %>%
  FindVariableFeatures() %>%
  ScaleData() %>%
  RunPCA() %>%
  FindNeighbors(dims = 1:10) %>%
  FindClusters(resolution = 1.5) %>%
  RunUMAP(dims = 1:10)

cells_to_highlight <- CellsByIdentities(object = pbmc3k, idents = c(1:12))

DimPlot(pbmc3k, cells.highlight = cells_to_highlight, cols.highlight = DiscretePalette(n=12, palette = "alphabet"))
```

Looking into this more I believe the issue here is actually coming from the `SetHighlight` function.  Specifically, I think it's coming from the end of the function:
[https://github.com/satijalab/seurat/blob/fe93b05745e55ec2f66e3f0b4c4196aad9f4d5a7/R/visualization.R#L6610-L6614](https://github.com/satijalab/seurat/blob/fe93b05745e55ec2f66e3f0b4c4196aad9f4d5a7/R/visualization.R#L6610-L6614)

One remedy I came up with is the following fix.  Changing the `SetHighlight` function appeared to remedy the issue on my machine with the example object code provided above.  If this fix works and looks ok to you I can go ahead and create PR:
```
  highlight[is.na(x = highlight)] <- 'Unselected'
  highlight.length <- length(unique(highlight))-1
  highlight.order <- c(1:high_length, 'Unselected')
  highlight <- factor(x = highlight, levels = highlight.order)
  plot.order <- as.character(sort(x = unique(x = highlight), na.last = TRUE))
  plot.order[is.na(x = plot.order)] <- 'Unselected'
  return(list(
```

Best,
Sam

**Comment by timoast** [comment]
@karenlawwc the recommended way to do this would be to create a metadata field in the Seurat object and group the cells by that field in the `DimPlot` call, rather than passing a long vector of cells and associated colors to `cells.highlight`. Cells that you want to appear grey can be given the value `NA` in the metadata. You can then change the colors used by using the standard ggplot2 functions, eg `scale_color_manual()`

**Comment by karenlawwc** [comment]
@timoast Thanks for the suggestion! But when I tried the scale_color_manual to change the colors, the same issue with more than 10 groups still happen.
@samuel-marsh Thanks for the fix! It looks great to go ahead except for a typo on line 3 of your code? Should it be highlight.length instead of high_length?

**Comment by TeodoraTockovska** [comment]
Hi! Was this issue resolved? I am running into the same problem and I am trying to order my highlighted cells but the ordering is messed up. Thanks!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
