### ISSUE TITLE
How to add ablines on the VlnPlot

### ISSUE THREAD

**Issue by parvathisudha** [satijalab/seurat#3753]
I wonder is there a way to add horizontal alines to the vlnplot to show the feature selection?

![image](https://user-images.githubusercontent.com/13000751/99825341-e83c1200-2b24-11eb-8197-f043262a0fdc.png)

Thanks
Parvathi.

**Comment by samuel-marsh** [comment]
Hi,

Yes, you can modify plots as if you would any ggplot/patchwork plot.  To add horizontal line simply use the `geom_hline(yintercept = X)` extension.  However, it should be noted that in order to apply different lines to the plots independently (which you need to do because the scales are vastly different), you will have to plot and add the lines to each feature individually and then if you want single layout, wrap them back together again.
i.e.
```
p1 <- VlnPlot(pbmc, features = "nFeature_RNA") & geom_hline(yintercept = 7500)
p2 <- VlnPlot(pbmc, features = "nCount_RNA") & geom_hline(yintercept = 50000)
p3 <- VlnPlot(pbmc, features = "percent.mt") & geom_hline(yintercept = 25)
wrap_plots(p1, p2, p3, ncol = 3)
```

Best,
Sam

**Comment by jaisonj708** [comment]
@samuel-marsh's response is correct.

**Comment by parvathisudha** [comment]
Thank you!
