### ISSUE TITLE
Integrating data from different types of data from 10x

### ISSUE THREAD

**Issue by jd10020** [satijalab/seurat#3772]
Dear seurat team,

I am analyzing 3 types of data, 2 of them (my controls) were acquired using 3' v2 from 10x and the other sample (my actual sample) was acquired using 5' v1 from 10x. Can I do the quality check (filtering and normalize them separately) and then integrate it using "FindIntegrationAnchors" and then "integrateData". Once the data is integrated will it be reliable enough to account as significant any DE I find between my conditions for a specific cluster? Also my controls were taken from a repository where they were used in 2 separate studies. When reading the methods section I found for the filtering step they choose percent.mitochondrial <30 for both controls. However, for my data I was using <10. Will I create a problem if I do not have all of them at the same threshold value or can those values be different ?

Thanks in advance!

**Comment by jaisonj708** [comment]
Your objects can be QC'd a bit differently, since samples derived from different experimental methods will tend to have different optimal percent.mito thresholds. Our integration procedure should also be able to correct for minor differences in mitochondrial features. You can always adjust percent.mito to be the same across objects if you'd like.
