### ISSUE TITLE
Merging, scaling and clustering separately integrated two data

### ISSUE THREAD

**Issue by kinali** [satijalab/seurat#3806]
Dear all,

I have 2 different tissues (A and B) from 3 patients. I have integrated them as A_all and B_all and I found clusters for each of them. Now, I want to cluster A and B together to see uncommon clusters between them.
For that, should I integrate them again? or should I merge two integrated objects then cluster them?

For now, I merged two integrated objects but I am not sure if this is the correct approach? Also, I am not sure if I should
scale "integrated" assay or "RNA" before RunPCA.

All_combined <- merge(A_all, B_all)
DefaultAssay(All_combined) <- "integrated"
All_combined <- ScaleData(All_combined, vars.to.regress = c("percent.mt","S.Score","G2M.Score"))

I would really appreciate any help!!
Best,

**Comment by kobeho24** [comment]
I have the very same question as yours. I integrated the data from 2 different tissues, it seems not very biologically meaningful, given that there shouldn't be a lot of cell types in common between the 2 types of tissues. Merging 2 pre-integrated datasets seems a good way to go.

**Comment by Dragonmasterx87** [comment]
What happens when you integrate everything at once? (6 datasets together)? In theory cell-type specific identities should be conserved. Im not a dev, but this is an interesting question.

**Comment by satijalab** [comment]
Its difficult for us to provide a single answer (or a best practice), because it depends entirely on your biological question. But as a general rule, you perform integration or batch correction when you believe there are shared clusters between datasets  and you want to group them together to facilitate downstream annotation. You can also jointly analyze datasets by merging them, but then there is no batch correction performed. The code you have seems reasonable.

**Comment by Dragonmasterx87** [comment]
> Its difficult for us to provide a single answer (or a best practice), because it depends entirely on your biological question. But as a general rule, you perform integration or batch correction when you believe there are shared clusters between datasets and you want to group them together to facilitate downstream annotation. You can also jointly analyze datasets by merging them, but then there is no batch correction performed. The code you have seems reasonable.

@satijalab I agree, it's not really black and white ever, and it depends on the biological model. Nevertheless, this raises an interesting debate, is merging not so bad? .....maybe as long as cell-type-specific identity is not lost. I say this, because in the end DE is run on the RNA assay, and an integrated vs. merged dataset just allows for cell-type-A to distribute evenly in a cluster across samples vs, have numerous subclusters within a cluster for cell-type-A belonging to numerous donors. The point being merging isn't so bad, but novice reviewers, don't understand this and can tear a paper apart purely because someone is performing merging vs. integration.
