### ISSUE TITLE
Create Seurat Object out of Old Spatial Transcriptomics Data

### ISSUE THREAD

**Issue by willmonty14** [satijalab/seurat#3836]
Hi Seurat team, 

I love your new spatial vignette, and I'd love to use it for data generated before 10X came out with their nice space ranger output style, but I can't seem to figure out how. I've seen a couple other posts on this, the main one that comes to mind is the one where y'all recommended using new() to create an image object, but the problem is that without 10X you can't find scale factors for an image (at least as far as I know). I know how to create an object out of the ID column and the .tsv table that the st_pipeline gives me, but for the life of me I cannot figure out how to add an image to the Seurat object. Any ideas?

**Comment by torkencz** [comment]
Hi,

Thank you for you kind words regarding the spatial vignette. Unfortunately, we do not have support for earlier spatial data formats currently. You'll probably have to figure out a scale factors manually. Maybe, if you have hi-def image you could try scale factors of 1, otherwise it becomes a more challenging problem.
