### ISSUE TITLE
Integration and Label Transfer of Iteratively Clustered Reference Data 

### ISSUE THREAD

**Issue by delucalab** [satijalab/seurat#3845]
My apologies if this is a naive question as I am new to the field. I am attempting to use a preexisting dataset from the following paper (https://www.nature.com/articles/s41467-020-19737-2#Sec10) as a reference to predict cluster abundances in other datasets. The reference data was clustered iteratively (twice) and so the variable genes and number of dimensions will differ between these iterations. Since I am only interested in the clusters (1-9) identified as part of the second clustering iteration, should I remove the cells belonging to clusters (10-14) from the first iteration and then use the parameters (ie variable genes and number of dimensions) identified from the second clustering iteration as inputs for the find transfer anchors and transfer data pipeline?

**Comment by jaisonj708** [comment]
The clustering should not impact variable features or number of dimensions in your reduction, since these are both computed before clustering. But it is perfectly fine to subset a reference to use part of it (here, it looks like you only want to use microglial clusters 1-9). You can re-run FindVariableFeatures and RunPCA after you subset.
