### ISSUE TITLE
Rationale behind log normalization

### ISSUE THREAD

**Issue by jasminelmah** [satijalab/seurat#3846]
Hi!

Thanks for writing Seurat. It has been extremely helpful!

From what I understand, Seurat's LogNormalize divides each cell by the total number of molecules in the cell, multiplies it by a scaling factor, +1 then takes the natural log.

What is the biological rationale behind taking the logarithm of counts?

Thanks!

**Comment by saketkc** [comment]
The rationale (computational) for log normalization as you describe is to a) adjust for different sequencing depth and b) stabilize the variance (otherwise genes with higher counts will always have higher variance) and c) reduce stochastic effects of large counts (to some extent).  See [this paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1) for a discussion on the importance of variance stabilization.
