### ISSUE TITLE
Reading .dgecounts.rds.gz file in R

### ISSUE THREAD

**Issue by sumeetpandey** [satijalab/seurat#3863]
Can anyone please help to read .dgecounts.rds.gz file in R? I get error as "unknown input format"

> C_34 <-  readRDS(file = "~/IPF_Data_Athena/34C.dgecounts.rds.gz")
Error in readRDS(file = "~/IPF_Data_Athena/34C.dgecounts.rds.gz") : 
  unknown input format

I have also tried using "unz" then "readRDS" still does not work. 
Thanks in advance.

**Comment by k3yavi** [comment]
Hi @sumeetpandey ,

Can you decompressing the file first and then try `readRDS` ?
Also, if this doesn't work can you provide more details about how was the file generated ?

**Comment by sumeetpandey** [comment]
Hi @k3yavi 
Many thanks. I did try decompressing and then readRDS still it is not working. This file is publicly available "GSM4058900". Thank again for helping.

**Comment by k3yavi** [comment]
I think the issue is unrelated to Seurat, anyway I got the file from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4058900 unzipped it through `gunzip GSM4058900_133C-a.dgecounts.rds.gz` and read it in through `readRDS("GSM4058900_133C-a.dgecounts")` it seems to work. 
Not sure what's wrong on your end.
