### ISSUE TITLE
different # cells per sample

### ISSUE THREAD

**Issue by FADHLyemen** [satijalab/seurat#3911]
What is your advice  if I start with subtle difference of number of cells per sample. for example, # cells for sample 1 is 120 and for sample 2 is 4000.  the cluster is dominated by sample #2 ?

**Comment by NicolaasVanRenne** [comment]
Im not from the Seurat development team, but here is my opinion

Integrating 120 and 4000 cells seems a bit weird. Why such differences? What happened? If integrating both samples you will need to set a low k.filter of 120 or lower, but this will affect the quality. Merging might be better, but I have no experience in this.

Also good clustering depends also on the heterogeneity of your cells. This is hard to judge because of the scant information you provide.  

Put in more information and a picture of the clustering because we have little to go on here.
