### ISSUE TITLE
How to obtain all features in scale.data slot of integrated SCTransformed object

### ISSUE THREAD

**Issue by jgamache014** [satijalab/seurat#3916]
This is similar to issue #3839.

I made an integrated object with SCTransform following [this vignette](https://satijalab.org/seurat/v3.0/integration.html). There are 36,601 features in the 'data' slot of the 'SCT' assay but only 3,000 features in the 'scale.data' slot. Since it is recommended to do DE analysis using the 'scale.data' slot, I need to know how to get data for all features in that slot. Here is my workflow:

```
#Merge multiple Seurat objects
list <- c(sample2, sample3, ... sample24)
combined <- merge(x = sample1, y = list)

#Reference-based integration
combined.list <- SplitObject(combined, split.by = "sampID")
for (i in 1:length(combined.list)) {
  combined.list[[i]] <- SCTransform(combined.list[[i]], method = 'glmGamPoi', verbose = FALSE)
}

combined.features <- SelectIntegrationFeatures(object.list = combined.list, nfeatures = 3000)
combined.list <- PrepSCTIntegration(object.list = combined.list, anchor.features = combined.features)

reference_dataset <- which(names(combined.list) == "sample1")

combined.anchors <- FindIntegrationAnchors(object.list = combined.list, normalization.method = "SCT", 
                                           anchor.features = combined.features, reference = reference_dataset)
combined.integrated <- IntegrateData(anchorset = combined.anchors, normalization.method = "SCT")
```

When I use `return.only.var.genes = FALSE` in SCTransform() and `nfeatures = length(rownames(combined))` in SelectIntegrationFeatures(), the number of features in combined.integrated[["SCT"]]@scale.data after integration was increased only to 6,671.

Next I tried `features.to.integrate = all.genes` in IntegrateData(), but I get an error:

```
all.genes <- rownames(combined)
combined.integrated <- IntegrateData(anchorset = combined.anchors, features.to.integrate = all.genes, normalization.method = "SCT")

##Calculating residuals of type pearson for 14651 genes
##Integrating dataset 1 with reference dataset
##Finding integration vectors
##Finding integration vector weights
##0%   10   20   30   40   50   60   70   80   90   100%
##[----|----|----|----|----|----|----|----|----|----|
##**************************************************|
##Integrating data
##Error in .cbind2Csp(x, y) : 
  ##Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 92
##Calls: IntegrateData ... cbind -> cbind2 -> cbind2 -> cbind2sparse -> .cbind2Csp
##Execution halted
```

Any tips for how I can get data for all 36,601 features in the scale.data slot of my integrated object?

Also, it is recommended to integrate using the 'scale.data' slot - am I doing that correctly? If not, how should that be done?

Thanks a lot!

**Comment by dlmatera** [comment]
As far as I know, it is not currently recommended that you do any differential expression analysis on the scale.data slot for an integrated dataset, integration creates dependencies between cells within the dataset and thus violates the assumptions for most statistical tests.

This makes dataset integration a little less useful than what it otherwise would be, but still allows you to cluster cells appropriately across datasets, and then apply a normal DEG analysis across your clusters (which will have increased statistical power now that they are merged. I believe this still means there may be some batch effects in your DEG analysis, but you can play with the vars.to.regress command to try and correct for this a little bit

**Comment by MrModenait** [comment]
I'll happily hop onto this question since I'm currently working on something similar.
Firstly, to build on what @dlmatera has said: indeed it is recommended to run differential expression analysis on the `RNA` assay, according to the official Seurat [FAQ](https://satijalab.org/seurat/faq.html). The `FindMarkers` command pulls data from the `data` slot by default, and hence that is what I usually do.
Likewise, I understand why @jgamache014 is seeking to integrate all features. For me it helps having all genes integrated e.g. when my supervisor asks me to plot a new gene with `DimPlot` on demand. I struggled to integrate all genes for a recent project while I was using the ancient `ScaleData` command. The bottleneck there was the `ScaleData `command which exhausted my RAM when I tried to scale all genes, but reached a compromise in which I set `features` to a custom vector containing the variable features (as determined by `FindVariableFeatures`) as well as relevant genes in my field of study. The code I used is attached at the bottom of this post. The integration worked despite the number of cells because with the old workflow, genes were scaled _after integration_.
With the `SCTransform `workflow, the steps have been reordered and merged so that the genes are scaled before integrating, which seems to make the files much larger. I'm therefore wondering if anybody knows how to output the vector of genes which Seurat will integrate by default, so that I can add the genes I'm interested in and pass this vector to `features.to.integrate`?

Here's the code I used to make `ScaleData `scale the genes I wanted to scale:
```
all.available.genes <- list(rownames(dataset_1),
                            rownames(dataset_2),
                            rownames(dataset_3)) # and so on
common.genes <- Reduce(f = intersect, x = all.available.genes) #here's my list of available genes
Integrated_Dataset <- IntegrateData(anchorset = anchors, features.to.integrate = common.genes, dims = 1:30) #here I integrated the data using all genes
query.genes <- read.csv("../Directory/Query Cytokines.csv", encoding="UTF-8") #importing list of interesting cytokines
missing.genes <- setdiff(query.genes$X.U.FEFF.Gene.Name,common.genes) #just to check, I exported a list of cytokines which weren't found on the dataset so I could see if the list had any spelling errors. Also note the encoding went a bit weird with that "X.U.FEFF." prefix, but never mind 
write.csv(missing.cytokines,file = "Invalid Query Cytokines.csv") #saved the list of missing genes for examining later
genes.to.scale <- list(VariableFeatures(Neutrophils_SCT_Integrated),
                       query.genes$X.U.FEFF.Gene.Name) #created the list of genes to scale
genes.to.scale <- Reduce(f = union, x = genes.to.scale)
Integrated_Dataset <- ScaleData(Integrated_Dataset, features = genes.to.scale, verbose = TRUE,
                            assay = "Integrated",
                            vars.to.regress = c("nFeature_RNA","percent.mt","S.Score", "G2M.Score"))

```

**Comment by timoast** [comment]
>  Since it is recommended to do DE analysis using the 'scale.data' slot

This is not true

It's also not advised to do DE on integrated data

**Comment by hoondy** [comment]
> It's also not advised to do DE on integrated data

@timoast Can you elaborate? For example, I have multi-sample single-cell data (n=100 10x scRNA from 3 different sources). What is the best practice for doing DE analysis on this type of integrated data?

**Comment by HerpelinckT** [comment]
@hoondy DE is a supposed to be a comparison between samples. By integrating datasets, you are joining samples together into one, so any DE performed on the integrated data is a within-sample comparison instead. For DE analysis on multi-sample single-cell data you can consider for instance [_muscat_](https://www.nature.com/articles/s41467-020-19894-4).

**Comment by hoondy** [comment]
> @hoondy DE is a supposed to be a comparison between samples. By integrating datasets, you are joining samples together into one, so any DE performed on the integrated data is a within-sample comparison instead. For DE analysis on multi-sample single-cell data you can consider for instance [_muscat_](https://www.nature.com/articles/s41467-020-19894-4).

Thanks. Maybe I wasn't clear. I am trying to integrate across sample and remove technical variables. Then, use the integrated dataset to do a clustering and find cluster markers.

**Comment by HerpelinckT** [comment]
@hoondy In that case I belief the [vignette](https://satijalab.org/seurat/articles/integration_introduction.html) for analysis of integrated data is what you are looking for. It demonstrates how to perform clustering on an integrated dataset and identify differential expressed genes across conditions/samples.

**Comment by MrModenait** [comment]
I'm glad to see this thread waking up and might perhaps hop on the train to ask a question. In January @jgamache014 asked the original question in the context of differential expression analysis. However, I'm interested in this to be able to select which genes to integrate for so that I can make feature plots (using `DimPlot`) for relevant genes with a coherent scale. With `ScaleData `it was possible to pick and choose genes, does anybody know how I can do it with `SCTransform`?

**Comment by HerpelinckT** [comment]
I have never tried it, but wouldn't setting `residual.features` to your genes of interest give you that result?

**Comment by MrModenait** [comment]
Hi @HerpelinckT and sorry for re-opening this old thread, I was working on other stuff during the spring and this got put aside.
I see that `SCTransform` does indeed have a setting called `residual.features`, but my challenge has always been choosing features to keep when running `IntegrateData` _after_ `SCTransform`. On the other hand, I later learned that the `Integrated` assay should not be used for violin plots or other forms of visualization, so this issue no longer became pertinent to me. The PhD student who taught me to use Seurat claims that `FeaturePlot` is the exception to the rule, but as I keep getting strange error messages when setting `DefaultAssay(Neutrophils_SCT_Integrated) <- "Integrated"` ahead of `FeaturePlot` (namely "`Found the following features in more than one assay, excluding the default. We will not include these in the final data frame`") I have simply decided to use the `SCT` assay for my UMAP plots of gene expression!
Thanks to everybody in this thread for helping me move on!
