### ISSUE TITLE
Test statistic for FindMarkers

### ISSUE THREAD

**Issue by nsanford0** [satijalab/seurat#3919]
Is it possible to return the test statistic value when running FindMarkers()? For example if I run FinfMarkers with the default wilcox test is there a way to get a column in the table that is returned with the value of the test statistic (U) for that test?

**Comment by torkencz** [comment]
Hi, 
As far as I know outputting test statistic values are not supported in Seurat at the moment.

**Comment by bpyenson** [comment]
Hi, this issue was highlighted by another [paper](https://www.nature.com/articles/s41467-021-25960-2#Sec11), I quote the part of the text where the authors modified Seurat to output a test statistic:
"We observed that some statistical tests returned a large number of p-values below the double precision limit in R (approximately 2 × 10–308), potentially confounding the calculation of the concordance metrics described below. To avoid this pitfall, we modified the Seurat implementation to also return the value of the test statistic from which the p-value was derived. The modified version of Seurat 3.1.5 used to perform all single-cell DE analyses reported in this study is available from http://github.com/jordansquair/Seurat."

My question is: can the test-statistic be added to output of FindMarkers for future versions of Seurat?

**Comment by tfguinan** [comment]
Just to add (and to remind myself in future) the [Squair test_statistic branch](https://github.com/jordansquair/squair_seurat/tree/test_statistic) demonstrates returning test statistics from FindMarkers for t-test, Wilcoxon rank-sum test, logistic regression, negative binomial and Poisson generalized linear models, likelihood ratio test, and MAST
