### ISSUE TITLE
Azimuth on integrated data

### ISSUE THREAD

**Issue by rseurinc** [satijalab/seurat#3920]
I have been trying to run the Azimuth vignette on a large integrated data set of PBMCs, but I keep running in to errors. Does Azimuth support integrated objects? I had no problems running it on the individual data sets.

Ruth

**Comment by yuhanH** [comment]
HI, 
Azimuth doesn't support integrated object, and it only accepts counts data. 
If your samples are just from different donors, you can put them together to Azimuth.

**Comment by levinhein** [comment]
Hello,

I just want to clarify how Azimuth can be used for multple scRNA-seq datasets that are supposedly for integration.

So since integrated data cannot be inputted to Azimuth, and only the non-processed counts data (i.e. seurat object) can be used, I was wondering what do you mean by "you can put them together to Azimuth". 

The input in Azimuth app only accepts one dataset at a time. May I ask what should be the best way to do this?
(1) Merge the Seurat objects so that we can only have one dataset to load in Azimuth
(2) Load the datasets one by one and then (a) simply merge or (b) perform Seurat integration after?
(3) Any other suggestion please?

Thank you!
