### ISSUE TITLE
why DE analysis does not use scaled data

### ISSUE THREAD

**Issue by cankutcubuk** [satijalab/seurat#3933]
Hi @andrewwbutler,

As you mentioned in your previous comment (issue #1874), the scaled data is not used for DE analysis. I do not get this part very clearly. I use ScaleData function with vars.to.regress argument and I consider my scaled data as clean data (ready to use) for downstream steps including DE analysis. Since I am using the residuals (resulting after the counts data regressed against each feature in vars.to.regress) for scaling and centring, I feel like I have to use the scaled data for DE analysis instead of counts data.

Why does Seurat use counts for DE? And when I have to use scaled+centered+batch corrected data?

Best wishes
Cankut

 the (unwanted variablity base on the variables I set removed, then scaled and ) and ready to use data
 resulting residuals are then scaled and centered. 

Hi,

1. Yes, you can do this on the RNA assay after integration for visualizing your markers in the heatmap. 

2. No, scaling does not affect the DE analysis as we used the log normalized data for those tests.

_Originally posted by @andrewwbutler in https://github.com/satijalab/seurat/issues/1874#issuecomment-515502741_

**Comment by jaisonj708** [comment]
By the default method in `FindMarkers` (called wilcox), the normalized data slot is used for DE rather than the counts. Scaling will not affect the order of expression values for a given feature, so there's no clear benefit to a differential expression test like wilcox being based on scaled data rather than normalized data. 

Re: DE after batch correction, as you know we don't recommend running DE on batch corrected values because batch correction procedures introduce a dependency between cells' expression values. This violates the assumptions of DE tests. Furthermore, the purpose of integration is for clustering/annotation, rather than preparing data for DE. After you run your DE test, you can determine (through analyses like GO enrichment) which results are biologically meaningful and which are technical.
