### ISSUE TITLE
When to use vars.to.regress in SCTransform() and that in ScaleData()?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#3935]
Hi everyone, 

The vars.to.regress argument is available in both ScaleData() and SCTransform(). 

If I want to use the SCTransform() instead of the 3 data transformation functions it replaces, #3665 suggests to use SCTransform() to regress out percent.mt, but then use ScaleData() to regress out cell cycle genes. Why cannot we use SCTransform() for both either in 1 step or sequentially? 

Also, these functions do not regress out the actual genes, what do they actually regress out for the mitochondrial genes (vars.to.regress = percent.mt)and the cell cycle genes (vars.to.regress = c("S.Score", "G2M.Score") that are computed from CellCycleScoring()? A threshold of % mt genes and certain threshold for cell cycle gene expression in cells?

Thank you very much for your help!

**Comment by jaisonj708** [comment]
Your cell cycle score will be computed after normalization, whereas percent.mt is based on raw counts, which is why these two are usually regressed out in separate functions. But there's no reason you can't do it simultaneously as long as you have computed both.

I don't completely understand your second question. percent.mt, S.Score, and G2M.Score are the regressor variables. There is no thresholding of these variables

**Comment by denvercal1234GitHub** [comment]
Thank you @jaisonj708 for your response! 

I see. So, when it says to regress out percent.mt and cell cycle scores, it means to control for these variables in the regression model, and it does not mean that we eliminating the mitochondrial or cell cycle genes.

Does it matter if I use SCTransform() again to regress out the cell cycle genes instead of ScaleData() since both have the vars.to.regress argument, if I already used SCTransform() to do so for percent.mt in the preceeding step?
