### ISSUE TITLE
Inefficient garbage cleanup?

### ISSUE THREAD

**Issue by mukundvarma** [satijalab/seurat#396]
I was wondering if anyone else also faces any issues with inefficient garbage cleanup, particularly after computing new dimensionality reduction representations. The size of objects on disk when I do ls() is frequently a lot smaller than the memory occupied by my notebook/script on Activity Monitor, and I wonder if this is because some of the temporary objects being loaded into memory aren't being cleaned up when they're not being used anymore (e.g. for a seurat object of size ~4GB, about 25 GB of total memory seems to be in use). I'm not 100% sure if there's something in my workflow that's inefficient, or if this is an issue anyone else has faced also. Any advice/suggestions would be hugely appreciated.

**Comment by andrewwbutler** [comment]
It's difficult to say why the system is reporting 25GB in your case.  You can read more about memory usage in R [here](http://adv-r.had.co.nz/memory.html), particularly the section on garbage collection. You might be in the second scenario described there:

" 2. Both R and the operating system are lazy: they won’t reclaim memory until it’s actually needed. R might be holding on to memory because the OS hasn’t yet asked for it back."

You can try forcing R to release the memory with `gc()`.
