### ISSUE TITLE
Slot for NMF

### ISSUE THREAD

**Issue by faraz89** [satijalab/seurat#3987]
Hi,

Which slot from SCT would you recommend for NMF analysis.

1. counts - sequencing depth corrected
2. data - log Normalised. We are not supposed to use log for NMF right?
3. Scale.data

Please let me know.

Thanks,
Faraz.

**Comment by torkencz** [comment]
Hi,
I would recommend storing your own dimensional reduction within a dimensional reduction structure. Follow the https://satijalab.org/seurat/v3.0/dim_reduction_vignette.html . Hope this helps.

**Comment by faraz89** [comment]
I'm sorry but can you please elaborate how is that associated with the question I raised? I need to use normalised counts for non-negative matrix factorisation analysis. This is to identify meta-programs? What do you mean by storing dimensional reduction in this case?

**Comment by torkencz** [comment]
I realized I misunderstood the question. I thought the question related to storing the NMF rather than which slot to use. I would run it on the counts matrix. Values in object@scale.data can be negative, while values in object@data are >=0, which is a requirement for NMF. They also discussed this in
https://github.com/satijalab/seurat/issues/3715
