### ISSUE TITLE
Subsetting Seurat object to zero cells gives error

### ISSUE THREAD

**Issue by frederikziebell** [satijalab/seurat#4006]
Subsetting a Seurat object to zero cells gives an error instead of an empty object. Running
```r
pbmc_small[,rep(F,80)]
```
gives `Error in CellsByIdentities(object = object, cells = cells) : Cannot find cells provided`. It would be better to make this operation type-stable by returning a Seurat object with zero cells, since it otherwise prevents automated manipulation (e.g. in a loop or function), when this special case occurs. Seurat Version is 4.0.

**Comment by frederikziebell** [comment]
@yuhanH I don't want to sound nitpicky, but the described behavior is clearly [bug](https://en.wikipedia.org/wiki/Software_bug) and it would be good to also treat it as such. The object is called with a valid subsetting operation and the result is an incorrect, unexpected result.

**Comment by mojaveazure** [comment]
Hi Frederik,

We don't plan to implement support for a zero-cell `Seurat` due to the complexity required for it. We have some alternatives though:

1) In your loops and functions, you can wrap the subset command in either a `try` or `tryCatch`

```R
# Prints error message; returns an object of class `try-error'; check for success with `inherits(x, "Seurat")`
x <- try(pbmc_small[, repr(F, 80)])
# Hides error message; returns an object of class `NULL`; check for success with `is.null(x)` or `inherits(x, "Seurat")`
x <- tryCatch(
  expr = pbmc_small[, repr(F, 80)],
  error = function(...) {
    return(NULL)
  }
)
```

2) We can add an argument to `subset` (not `[`, use `subset(pbmc_small, cells = repr(F, 80))`) to return a `NULL` instead of throw an error if all cells are removed from the object. While not the most type-stable, it would allow you to easily pass through subsets that would remove all cells

**Comment by frederikziebell** [comment]
I think the idea with returning NULL in the subset function is very good because it makes the operation compatible with loops and this special case can easily be dealt with. Thank you!

**Comment by mojaveazure** [comment]
Hi Frederik,

Preliminary support for returning a `NULL` object is available on the `feat/ZeroCellSubset` branch of SeuratObject. Could you give it a try and let us know if this solution works for you? See mojaveazure/seurat-object#9

You can install the `feat/ZeroCellSubset` branch of SeuratObject with
```R
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-object", ref = "feat/ZeroCellSubset")
```

You can test the new functionality with
```R
subset(pbmc_small, cells = rep(F, 80), return.null = TRUE)
```

**Comment by mojaveazure** [comment]
This has been addressed in the development version of SeuratObject; to install the development version of SeuratObject, please run

```R
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("mojaveazure/seurat-object", ref = "develop")
```

**Comment by neha163** [comment]
Hello @mojaveazure, 

Even I am having this subsetting issue with Seurat object. The error message for me says "No cells found". I tried subsetting with some other data just last week and it worked fine. Could you please suggest me how to solve  this so that I can move forward with my analysis. 
Thank you!

Best
Neha
