### ISSUE TITLE
Issue with 10X spatial transcriptomics data upload

### ISSUE THREAD

**Issue by RajneeshSrivastava** [satijalab/seurat#4029]
I am following the Seurat tutorial (https://satijalab.org/seurat/archive/v3.2/spatial_vignette.html) for visium data analysis, which is working fine with the test dataset provided by 10x.
```
#Test_data [Heart data] upload
TestData = Load10X_Spatial(data.dir = "C:/path/scRNA/Visium_Test/TestData_2/", filename =
"V1_Human_Heart_filtered_feature_bc_matrix.h5", assay = "Spatial", slice = "slice2", filter.matrix = TRUE)
```

While using the same code for 10X visium dataset upload (from my lab) which has below files, it gives "no image" error.
```
filtered_feature_bc_matrix/
                    barcodes.tsv.gz
                    features.tsv.gz
                    matrix.mtx.gz
filtered_feature_bc_matrix.h5
Sample1.svs
Sample1.tif
web_summary.html
```
I need help with data upload (for the above files) in seurat. Any snippet of code will be really helpful.

Many thanks,
Rajneesh

**Comment by orrzor** [comment]
hi Rajneesh,

I am pretty sure after running spaceranger count, you should have a subfolder named spatial, which contains your image in it. The image is usually an H&E. So Seurat's function is probably looking for that image, can't find it, and throws this error.
https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/count

hope that helps! -Orr

**Comment by RajneeshSrivastava** [comment]
Thanks Orrzor. You are correct. I think, .svs format file has the spatial folder. Any guess how to make use of it in seurat. Is there any module in seurat to decompress .svs file. 
-Rajneesh

**Comment by samuel-marsh** [comment]
Can you post the full code that you are running for your own analysis?

Thanks,
Sam

**Comment by RajneeshSrivastava** [comment]
> Can you post the full code that you are running for your own analysis?
> 
> Thanks,
> Sam

 PFA.. its just a test documentation following seurat guideline for spatial analysis

[Practice_01_spatial_analysis.pdf](https://github.com/satijalab/seurat/files/5933291/Practice_01_spatial_analysis.pdf)

**Comment by samuel-marsh** [comment]
Hi,

Can you confirm what @orrzor asked.  Do you have the subfolder named "spatial"?  It's not listed in your original post.

Thanks,
Sam

**Comment by RajneeshSrivastava** [comment]
> Hi,
> 
> Can you confirm what @orrzor asked. Do you have the subfolder named "spatial"? It's not listed in your original post.
> 
> Thanks,
> Sam

Hey Sam,
Like i said, i am guessing .svs file might have the spatial folder ( or the required image content), not sure if seurat handle .svs file ( i think its a compressed file). I am following the code/steps in seurat tutorial.
Thanks,
Rajneesh

**Comment by samuel-marsh** [comment]
Hi,

So Seurat is expecting the directory structure to be identical to the output of SpaceRanger pipeline.  The reason you are getting the error is due to a mismatch there.  The Devs might be able to help more here but I suggest trying to get the exact SpaceRanger output and using that as input directory for pipeline.

Best,
Sam

**Comment by RajneeshSrivastava** [comment]
> Hi,
> 
> So Seurat is expecting the directory structure to be identical to the output of SpaceRanger pipeline. The reason you are getting the error is due to a mismatch there. The Devs might be able to help more here but I suggest trying to get the exact SpaceRanger output and using that as input directory for pipeline.
> 
> Best,
> Sam

Thanks Sam. I will reply back, trying to resolve this .svs file decompression. Hope it will be all set soon. Thanks again!

**Comment by mojaveazure** [comment]
`Load10X_Spatial` is built to read data from Space Ranger and does not currently support custom upstream pipelines. It requires a subdirectory of `data.dir` called `spatial` (eg. if `data.dir` is `~/data`, then there must be a directory called `~/data/spatial`). Within the `spatial` directory, there must be the following files
 - `tissue_lowres_image.png`: the slide image in PNG format
 - `scalefactors_json.json`: the scale factors converting between the high-resolution coordinates and the scaled down coordinates in JSON format
 - `tissue_positions_list.csv`: the coordinates for each spot in a CSV file

Please see the documentation for [`Read10X_Image`](https://satijalab.org/seurat/reference/read10x_image) for more details

**Comment by royfrancis** [comment]
Is there some way to use `Load10X_Spatial()` to read in multiple spatial datasets/slides with custom labels (orig.idents and slide labels) and distinct cell names?

**Comment by samuel-marsh** [comment]
@royfrancis `Load10X_Spatial` currently only supports a single data directory (See [https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/R/preprocessing.R#L501](https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/R/preprocessing.R#L501)

You could write function to create list of objects reading files from different directories and specifying different parameters to `Load10X_Spatial()` to automate the process vs. running code individually.

Best,
Sam

**Comment by royfrancis** [comment]
The vignette example shows something like this:

```
InstallData("stxBrain")
brain1 <- LoadData("stxBrain", type = "anterior1")
brain2 <- LoadData("stxBrain", type = "posterior1")
brain.merge <- merge(brain, brain2)
```

And then `SpatialDimPlot(brain.merge)` plots the two slices side by side.

![](https://satijalab.org/seurat/articles/spatial_vignette_files/figure-html/joint.viz2-1.png)

So, `type` is used to somehow define that they are two slices with custom labels. Not sure how this is supposed to worked when manually reading in two spatial datasets using `Load10X()`.

**Comment by royfrancis** [comment]
Just noticed that my issue directly relates to #3732. That is exactly what I was trying to do.

**Comment by samuel-marsh** [comment]
Hi,

So as it states in the vignette the `merge` function is taking the individual objects and merging them together so that they can be plotted together.
In this case the "type" is a parameter of SeuratData that isn't relevant to creating the objects here.  You view the manual entry for `Load10X_Spatial()` more information on the different parameters you can use with that function.

So, you can either read datasets in individually and then supply them to `merge` manually.  Or again if you want a more automated way you can write a function to create a list of objects and then merge the objects in that list together (the merge could even be wrapped inside the same function if you don't want any of the objects individually).

Best,
Sam

**Comment by royfrancis** [comment]
Good point! Just noticed that `Load10X_Spatial()` has an argument `slice` which resolves one of my issues.

**Comment by samuel-marsh** [comment]
Yep!

**Comment by iddryg** [comment]
Hi, spaceranger has another function called aggr: [https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/aggregate](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/using/aggregate)

I am guessing Load10X_Spatial() is not compatible with the aggr output since it has a sub-folder for each sample within the spatial folder? 

Is it recommended to just use Load10X_Spatial() for each sample individually after spaceranger count and not use aggr when analyzing with Seurat then?
