### ISSUE TITLE
Merging Seurat objects 

### ISSUE THREAD

**Issue by rachel662** [satijalab/seurat#4043]
Hi there,

when merging two Seurat objects, are all counts for all genes preserved? 

Cheers
Rachel

**Comment by torkencz** [comment]
Hi,

As far as I know they should be. Also, genes that are unique to one of the objects should be preserved. When merging Seurat objects, the merge procedure will merge the Assay level counts and potentially the data slots (depending on the merge.data parameter). This issue is also discussed in  https://github.com/satijalab/seurat/issues/1771

**Comment by fteufel** [comment]
Hi, 

is there also a way to only retain the subset of genes that all datasets have in common, instead of 0-imputing missing features?
