### ISSUE TITLE
predicted.id missing in the returned value of TransferData

### ISSUE THREAD

**Issue by brianpenghe** [satijalab/seurat#4044]
I was comparing the [Transfer tutorial](https://satijalab.org/seurat/archive/v3.0/integration.html) and the [spatial tutorial](https://satijalab.org/seurat/archive/v3.2/spatial_vignette.html) .
It seems that they both use the transfer function. But the predicted.id variable is missing in the output of the spatial tutorial.
I'm using Seurat_3.2.2
Any ideas?

**Comment by brianpenghe** [comment]
The spatial tutorial requires an additional step of GetTransferPredictions() it seems.

**Comment by andrewwbutler** [comment]
Hi,

In the spatial tutorial we return the predictions as an `Assay` (with the `prediction.assay = TRUE` parameter) in order to easily visualize the prediction scores for each class later on in the tutorial. The `predicted.id` would just be the the class with the max score and can be retrieved using the `GetTransferPredictions()` function you mentioned.

**Comment by brianpenghe** [comment]
I see. I'll pay attention to this parameter. Thanks!
