### ISSUE TITLE
pct values don't match with expression level in feature plot and dot plot

### ISSUE THREAD

**Issue by nikita421** [satijalab/seurat#4045]
Hello,

I have a single cell seq data for 2 different conditions. We have obtained a DEG list using FindAllMarkers fuction, where we have set the idents to condition instead of clusters. So in the DEG output list, we have pct.1 and pct.2 and a "cluster" column which indicates the condition the gene is expressed highly in. My 1st question is, depending on the condition in the "cluster" column, does pct.1 and pct.2 change/flip? As in, if cluster column says Condition 1, does pct.1 indicates the gene expression in that particular condition is higher than the condition 2? Does pct.2 indicate the 2nd condition necessarily if we are using FindAllMarkers function (since we don't specify the ident.1 and ident.2 manually in this function)? 
My 2nd question is, the DEG list we have starts with mentioning all the genes highly expressed in condition 1 with pct.1 values greater than pct.2. However, even when the cluster column changes the condition number from 1 to 2, the DEG list still shows that all our genes are highly expressed in condition 1 and never in condition 2 (so now pct.1 is lower and pct.2 is higher) (if my interpretation of pct.1 and pct.2 flipping based on cluster column is indeed correct). This does not match with our feature plots as we can clearly see our genes being highly expressed in condition 2. Could you please help me understand why this might be happening?
My last question is, although our pct.1 and pct.2 values do not match our feature plots but when we make a dot plot of those genes, the dot size corresponds perfectly to the pct.1 and pct.2 values for each condition. Has this got something to do with normalization method or the values each function uses to plot those genes in different formats? I'm fairly new to coding and Seurat so these might seem like trivial questions but any help would be greatly appreciated.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully this can be helpful.  So pct.1 and pct.2 do not refer to levels of expression but rather to the percentage of cells where gene is detected.  The avg_logFC (Seurat V3) or avg_log2FC (V4+) will tell you the directionality of the expression difference between the groups.  This is why as you state when you perform `DotPlot` the pct.1 and pct.2 values correspond to the size of the dots.

For your first question.  pct.1 is going to represent the number of cells expressing gene in the group list in group 1 (i.e. the "cluster" column which in this case is your condition).  If the same gene is present in the output for the other condition then yes the values will "flip" because now the other condition is considered group 1.  

For your second question I think what you are referring to is due to confusion over what pct.1/pct.2 represents.  You can filter the output of `FindMarkers`/`FindAllMarkers` either prior to running the function using the various parameter options or after using standard functions to subset a dataframe.

I think your third question should be cleared up already in first part of my reply.

Hope this helps.
Best,
Sam

**Comment by nikita421** [comment]
Hi Sam,

Thank you for explaining what pct.1 and pct.2 represents. 

I don't think I get your answer for 2nd question though. We are subsetting each of our clusters one by one, setting out idents to "Condition" and then using FindAllMarkers. The log_FC is always positive in all our DEG lists for all the clusters. But when we make a feature plot of some gene, suppose Gene A, we can clearly see more red on feature plot in condition 2 than condition 1. But if we go back to the DEG list's pct.1 and pct.2 values, they don't match up with the feature plots. If pct refers to the percentage of cells where the gene is detected and if we see more expression in condition 2 from our feature plots (more red, less grey areas), then it should mean pct.1 should be higher than pct.2 (with cluster column showing "Condition2"). But as I mentioned in my original question, in our DEG lists, we always have more percentage of cells expressing all the genes in condition1 and never in condition 2 (so pct.1 higher than pct.2 when cluster is "Condition 1" and pct.1 lower than pct.2 when cluster is "Condition 2". Please let me know if this makes sense. 
-Nikita

**Comment by samuel-marsh** [comment]
Hi Nikita,

Sorry, it's hard to diagnosis exactly with dataset specific things without some specific examples.  What I will say is that again since pct.1 and pct.2 only describe expression above zero and not level of expression it's possible for one condition to have cells which express gene at a higher level (might appear more red) while the other condition has more cells with very low expression (using default color scheme might appear more gray-ish).
To confirm things in very basic fashion you could run the following:
```
# Get total cell number in condition 1
length(WhichCells(object = Obj, idents = "Condition1"))
# Check cells expressing gene above 0 in condition 1
length(WhichCells(object = Obj, idents = "Condition1", expression = Gene_Name > 0))
```

This will just allow you to see the raw numbers of expression vs total cells.  If those numbers don't match the outputs of `FindAllMarkers` pct.1/pct.2 then that's different question.

If that's still unclear might be helpful if you could post pictures with examples of the issue.

Best,
Sam

**Comment by nikita421** [comment]
Thank you so much Sam!! The code really helped to confirm if the pct.1 and pct.2 were actually correct. Also, I now understand relation between pct and feature plot expression. Thanks a lot for all the help!
-Nikita

**Comment by samuel-marsh** [comment]
No problem, happy to help!
