### ISSUE TITLE
Correct procedure for subset analysis on integrated data

### ISSUE THREAD

**Issue by miketerkelsen** [satijalab/seurat#4059]
Hi

I'm in need of some suggestions on how to proceed with subset analysis on integrated data after the update to version 4. When doing an integration following the current vignette I'll have one SCT run/model saved for each sample in the SCT assay and one SCT run/model in the integrated assay. However the one SCT model saved in the integrated assay seems to be a copy of the last SCT model for the individual samples. Is this right? (See attached images)

How would you suggest carrying out a subset analysis? Would it be feasible to do another SCTransform on the subset or should one stick to finding variable features? If so how would you resolve the error I'm presented with when running FindVariableFeatures? `Error: SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<-`

Thanks!

![Erro1](https://user-images.githubusercontent.com/33449808/107528730-70790300-6bba-11eb-8753-973a2501ade6.PNG)
![error2](https://user-images.githubusercontent.com/33449808/107528819-8be40e00-6bba-11eb-9a07-a588be5c1cb1.PNG)

**Comment by yuhanH** [comment]
HI, 
The easiest way is to re-run PCA in the integrated assay for your subset population. This new PCA will capture more structures in your subpopulations in which variable genes from the entire population are used. 

In the subpopulations, `FindVariables` will not work for sct-normalized data, because variable genes from sct method is determined by residual variance within the entire population. If you want to re-define variable genes, you may have to re-run SCTransform on your subset populations and integrations.
