### ISSUE TITLE
RunUMAP() is not working

### ISSUE THREAD

**Issue by sylestiel** [satijalab/seurat#4068]
Hi,

 I'm having issues with RunUMAP function when analyzing my multiomic data. 

> # build a joint UMAP visualization
> P2dual <- RunUMAP(
+   object = P2dual,
+   nn.name = "wknn",
+   assay = "RNA",
+   verbose = TRUE
+ )
Warning: The following arguments are not used: reduction.model, return.model, n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Warning: Running UMAP on Graph objects is only supported using the umap-learn method
Error in RunUMAP.Graph(object = data.use, reduction.model = reduction.model,  : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn).
> 
> DimPlot(P2dual, label = TRUE, repel = TRUE, reduction = "umap") + NoLegend()
Error: Cannot find 'umap' in this Seurat object
>

I'm running Seurat v4.0. I do not know what the problem may be.

Thanks

**Comment by k3yavi** [comment]
Hi @sylestiel ,

How did you create the object `P2dual` ? It seems to be looking for the python version of the UMAP instead of `uwot` the R version. One possible solution is to install the python version of the UMAP. 
I can check with the group when does the python call is triggered in place of the `uwot` r package call.

**Comment by yuhanH** [comment]
HI, 
it seems that your `wknn` is a graph rather than a neighbor object. 
You check the neighbor names in the `object@neighbors` , then use the neighbor names to run UMAP.  The default name is `weighted.nn`

**Comment by honghh2018** [comment]
Hi @sylestiel ,
    I saw the above comment, but i can not understand how to fix this problem.
    At the same time, the RunUMAP just was as same as the tradition Seurat function, i can not determine what time the python
    umap-learn be invoke and what time the uwot be invoke?save for  this issue, i am very confused about the python umap-learn, because of the python umap-learn installed  finishedly by reticulate r package's py_install('umap-learn'). however, when i run RunUMAP it still warning me below string:
  #warning:Running UMAP on Graph objects is only supported using the umap-learn method
![image](https://user-images.githubusercontent.com/41668708/109243681-52e1a580-7818-11eb-9b4f-20ee6b971af1.png)
   Some more information can see the #477 #482
    Any advice would be appreciated
    Best,
    hanhuihong

**Comment by yuhanH** [comment]
Hi, @honghh2018 
Currently, `RunUMAP` supports three types of input: dimensional reduction class (like pca), neighbor class (stored in `object@neighbors`), and graph class (stored in `object@graphs`).  When you want to build UMAP from a graph, it requires the `umap-learn` package.  Otherwise, `uwot` will be used by default. 

In your [Signac issue](https://github.com/timoast/signac/issues/477), you should set `weighted.nn` in nn.name instead of `wknn` which is a graph. 
```
gex <- RunUMAP(
object = gex,
nn.name = "weighted.nn",
assay = "RNA",
verbose = TRUE
)
```

**Comment by honghh2018** [comment]
Thanks @yuhanH so much, i get through this issue with your help.
 Thanks your kindly help again.
