### ISSUE TITLE
RNA Assay vs SCTAssay for visualization?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4082]
Related to #4081 and #4018

RNA Assay contains raw count data which can get normalized and logged, whereas the SCTAssay contains:

- counts = (corrected UMI counts if all cells were sequenced with same depth) counts
- data = log1p(counts)
- scale.data = pearson residuals

Andrew (on https://www.biostars.org/p/395951/) advised to use original log-normalized values in the RNA Assay for any kind of plotting of expression values for a gene and for DE analysis. 

But why in the tutorial of SCTransform() workflow, it says that the counts and data from SCT Assay are useful for visualization?

Thank you very much for your help!

**Comment by satijalab** [comment]
Apologies that this is confusing. The answer requires some nuance, so I'll do my best to explain. It depends on the context.

Let's suppose you have just one dataset, and you SCTransform on it. The data slot of the SCTassay represents the log of the corrected counts. Its fine to use these values for visualization, and we do this routinely in the lab.

However, let's suppose you have two datasets, one sequenced very shallow, and one very deep. You could run SCTransform on these datasets individually, and then merge them (or integrate them) together. In this case, the values in the data slot would be much lower for the shallow sequenced dataset, and higher for the deeply sequenced dataset. This could lead to misleading visualizations.

This is not as much of an issue for the RNA assay, because we divide the counts by 10,000 uniformly across datasets. This number is somewhat arbitrary, but it does impose a uniform standard across datasets, which can be useful when visualizing multiple experiments at different sequencing depths.

We often get questions like yours : Can I use the SCTAssay for visualization. Because it depends on the context (which we don't always know), and we prefer to be conservative and not accidentally encourage users to do something misleading, we tend to answer conservatively with a safe option ('i.e. we recommend using the RNA assay for visualization').

That doesn't mean that it would inappropriate or wrong to use the SCT counts in some cases, and thats why there sometimes appear to be inconsistent responses to questions like this.

Hope that helps-

**Comment by denvercal1234GitHub** [comment]
Thank you so much! This is very useful and clear!
