### ISSUE TITLE
Adding statistical significance to violin plots

### ISSUE THREAD

**Issue by jd10020** [satijalab/seurat#4087]
Dear Seurat team,

Thanks for your great package! I wanted to know if it is possible to add statistical significance when using the function VlnPlot when I am comparing expression level of any gene between clusters? I mean is it possible to get asterisks for significance and n.s or p-val number when it is not significant? If so, can you help me with the code please.

Thanks in advance for your help.

Diego

**Comment by torkencz** [comment]
Hi,

I am not aware of a method to do that within Seurat. However, since Seurat is ggplot based I've used this to modify my plots. http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/76-add-p-values-and-significance-levels-to-ggplots/
Alternatively, you can save a vectorized image and edit with adobe illustrator if you have access.
