### ISSUE TITLE
Nondeterministic output from SCTransform

### ISSUE THREAD

**Issue by Cam-Baker** [satijalab/seurat#4100]
Hello,

I am having a recurring issue when working on datasets with a large number of total cells within a dataset. When running the standard workflow of `CellCycleScoring`, `SCTransform`, `RunPCA`, `FindNeighbors`, and `RunUMAP`, I'm noticing slightly different results each time. 

I've tried setting the seed manually a variety of ways, and I've used `digest` as included within the digest package to pinpoint where the differences are introduced. It appears that the objects are identical before `SCTransform`, but the output of transformation does not appear to be deterministic. I've tried overriding it by manually setting the seed (it is already manually set as an input parameter) and forcing `SCTransform` to use all cells within the merged object, but these do not resolve the issue.

I've included the html to pdf output of the rmarkdown report detailing this. It contains 2 identical passes along a dataset of 32K cells spread across 7 samples. I include an md5sum of the merged object at various phases of analysis and the resulting UMAP plot, showing differences across the 2 tests. I also include the `sessionInfo()` at the end of the report. If requested, I can also provide the readout of the conda environment. This was done in the beta version of 4.0, but I've noticed it pop up on other versions as well.

[Analysis test 1.pdf](https://github.com/satijalab/seurat/files/6004245/Analysis.test.1.pdf)

Best,

Cameron Baker

**Comment by saketkc** [comment]
Thanks for the detailed report @Cam-Baker. There are a few things going on. First, to confirm SCTransform results are deterministic conditional on the same seed. Here's an example:

<details>
  <summary>Set the same seed [1]</summary>
  
```r 
  library(digest)
  library(Seurat)
  dim(pbmc_small)
  pbmc_small_sct1 <- SCTransform(object = pbmc_small, ncells = 50, seed.use = 42, verbose=F)
  pbmc_small_sct1_fa <- SCTResults(object = pbmc_small_sct1, assay="SCT", slot = "feature.attributes")
  
  # change the seed
  set.seed(100)
  # do a random calculation
  x <- rnorm(10)
  
  # use the same seed again
  pbmc_small_sct2 <- SCTransform(object = pbmc_small, ncells = 50, seed.use = 42, verbose=F)
  pbmc_small_sct2_fa <- SCTResults(object = pbmc_small_sct2, assay="SCT", slot = "feature.attributes")
  
  # comare digest of objects
  digest(pbmc_small_sct1) == digest(pbmc_small_sct2)
  # comare digest of scale.data
  digest(GetAssayData(pbmc_small_sct1, assay = "SCT", slot="scale.data")) == digest(GetAssayData(pbmc_small_sct2, assay = "SCT", slot="scale.data"))
  # comare digest of feature attributes
  digest(pbmc_small_sct1_fa) == digest(pbmc_small_sct2_fa)
 ```
 
</details>

<details>
  <summary>Output [1]</summary>
  
  ```r
230 80
FALSE
TRUE
TRUE
  ```
</details>


<details>
  <summary>Set a different seed [2]</summary>
  
```r 
  library(digest)
  library(Seurat)
  dim(pbmc_small)
  
  pbmc_small_sct1 <- SCTransform(object = pbmc_small, ncells = 50, seed.use = 42, verbose=F)
  pbmc_small_sct1_fa <- SCTResults(object = pbmc_small_sct1, assay="SCT", slot = "feature.attributes")
  
  # change the seed
  set.seed(100)
  # do a random calculation
  x <- rnorm(10)
  
  # use a different seed
  pbmc_small_sct2 <- SCTransform(object = pbmc_small, ncells = 50, seed.use = 412, verbose=F)
  pbmc_small_sct2_fa <- SCTResults(object = pbmc_small_sct2, assay="SCT", slot = "feature.attributes")
  digest(pbmc_small_sct1_fa)
  digest(pbmc_small_sct2_fa)
 ```
 
</details>

<details>
  <summary>Output [2]</summary>
  
  ```r
 230 80
 '55e48352677b11e2dc1b7f8bb6534b6b'
 '04ce2e62cee7cb2420740db010f0b38d'
  ```
</details>


In the first example, the features are exactly the same (same hash) but the object singatures are indeed different. You would want to compare the individual features rather than the entire object. Seurat also logs the time of run and hence the object signatures will never be the same (even when using the same seed everywhere). 

P.S . Your clusters look pretty similar within the two runs, but the `RunUMAP` step is indeed stochastic so you would want to set `seed.use=x` inside `RunUMAP` too.

**Comment by Cam-Baker** [comment]
Thank you for the clarification on the differences in the md5sums. Based on the documentation, I don't believe that `RunUMAP` is the issue as it appears to set `seed.use=42` within the [documentation](https://rdrr.io/cran/Seurat/man/RunUMAP.html). While the clusters are very similar, I'm just worried that they aren't identical across each run.
