### ISSUE TITLE
How to merge clusters and what steps needed after merging in SCTransform workflow?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#4128]
Hi there, 

In the tutorial, it states "# note that if you wish to perform additional rounds of clustering after subsetting we recommend re-running FindVariableFeatures() and ScaleData()." #1883 seems to suggest to run everything again on a subsetted cells from a cluster. 

But here I don't subset cells. I just merge cells from clusters or split the cluster: 

1. So if I processed my data using SCTransform, and get my clusters as usual. Then, if I merge some clusters, or split a cluster into smaller clusters, I do **not** need to run SCTransform() with percent.mt regressed (as I did with my original Seurat object), then ScaleData() to regress cell cycle genes, then RunPCA, RunUMAP, FindCluster() all over again on my Seurat object, right? But if I do, do I set the Assay argument to RNA?

2. #3239 and #3202 suggest that giving 2 clusters the same name will merge them, but wouldn't that mean I will need to re-run the FindAllMarkers() again now with the re-named clusters? Because after running RenameIdents(), it only changes the active.ident but the seurat_clusters in meta.data remain the same, and I believe FindAllMarkers() take the active.ident and not seurat_clusters.

3. Would anyone mind confirming that when I run RenameIdent(), it really merges the 2 clusters and not simply change the name of the clusters?

Thank you for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.
1.  If you simply want to change the clusters for visualization or marker detection then no you don't need to re-run anything after merging clusters.  If you haven't changed what cells are present in the object and simply just created a new active.ident then re-running the processing should just result in the same original clustering anyhow.

2. Yes, if you are looking to identify markers that are different between the clusters then you should re-run `FindMarkers` or `FindAllMarkers` after merging clusters because the results will be different.

3.  So merging and changing the name of the active.ident slot are the same thing.  The active.ident slot is a factor, so if two cells have the same value/name for active.ident they are considered the same (hence merged).  As you state the original clustering can be found in meta.data and you can even stash multiple clustering results in meta.data if you like.  What matters for the outputs of things like `FindMarkers` or `FindAllMarkers` as you point out is what the current active.ident is.  So as long as active.ident contains your new cluster names with merged values then yes the clusters are merged as it pertains to downstream analyses but if you switched back to the original clustering from meta.data then they would be unmerged.

Hope that helps!
Best,
Sam

**Comment by denvercal1234GitHub** [comment]
Thank you very much, Sam!

**Comment by denvercal1234GitHub** [comment]
Hi @samuel-marsh - If I subset out certain cells from the Seurat object after running the whole pipeline, should I now rerun SCTransform() to normalize and scale in order to calculate/visualize the expression levels of certain genes of the selected cells in this new object? Thank you again for your response!

**Comment by saketkc** [comment]
Hi @denvercal1234GitHub, SCTransform need not be run twice - the data has already been normalized.

**Comment by samuel-marsh** [comment]
Hi @denvercal1234GitHub if you are just wanting to visualize gene expression then no.  But if you want to analyze that subset further you should run whole pipeline basically again as the variable genes, pca, snn, louvain, UMAP, etc are all based on whole set of cells instead of just the subset of interest.
