### ISSUE TITLE
Error when reading barcode file

### ISSUE THREAD

**Issue by ruohuchengxhe** [satijalab/seurat#4148]
Hi, 
I'm trying to read a 10x barcode file with the following code:
`barcodes <- read.delim('GSE154278_barcodes.tsv.gz', 
                       header = FALSE,
                       stringsAsFactors = FALSE)`

However, I got an error :
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  error reading from the connection
In addition: Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  invalid or incomplete compressed data

I had no problem reading other barcode files. 

Appreciate any help!
Many thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully this can be helpful.  This doesn't appear to be an issue with Seurat as the `read.delim` function in generic R function.  I can confirm that I can replicate the error you are getting when I download and try to read in the same GEO record.  I suggest contacting the authors or GEO support to resolve the issue because it may be problem with the file itself.

Best,
Sam

**Comment by ruohuchengxhe** [comment]
> Hi,
> 
> Not member of Dev team but hopefully this can be helpful. This doesn't appear to be an issue with Seurat as the `read.delim` function in generic R function. I can confirm that I can replicate the error you are getting when I download and try to read in the same GEO record. I suggest contacting the authors or GEO support to resolve the issue because it may be problem with the file itself.
> 
> Best,
> Sam

Thanks! Good to know!!
