### ISSUE TITLE
FindMarkers underestimates fold changes of genes

### ISSUE THREAD

**Issue by HYsxe** [satijalab/seurat#4178]
Related issue: https://github.com/satijalab/seurat/issues/741, https://github.com/satijalab/seurat/issues/1008

Hi! 

I've been working on some differential expression analysis and noticed that FindMarkers consistently identifies much fewer differential genes than some custom scripts we wrote using wilcox test. After some debugging, I realized that when FindMarkers tries to calculate fold changes, it uses the "data" slot to get normalized data x, and then calculate log(mean(expm1(x)) + pseudocount) where the pseudocount is default to be 1. However, for single cell data, the mean(expm1(x)) is usually a pretty small number (very often < 1), so adding a pseudocount of 1 can really significantly shrink the fold change values, leading to very few genes passing the threshold. 

I am wondering if this is the expected behaviour of the function or is FindMarkers not indented for single cell data? For a beginner user this might be confusing and maybe the function should automatically select a pseudocount based on the range of data values. It took me sometime to figure this out and it might be helpful to include this in the documentation?

Hope this is helpful!

Thank you very much 

Yan

**Comment by jaisonj708** [comment]
We add the pseudocount precisely because of how small the mean is. Otherwise the value of the log would be negative, so it is common practice to add a pseudcount whenever using log for variance stabilization of small values.

We are working on fixing our logfc thresholds, which unintentionally filter out genes for which there is 100% positive expression in both groups/clusters. In the mean time, you can set these thresholds to negative values and all genes should be in outputted.
