### ISSUE TITLE
Why AverageExpression() result is different from mean() when I use slot = "data"

### ISSUE THREAD

**Issue by yhli1992** [satijalab/seurat#4181]
I've met a strange problem. Just like as I wrote in the title:
`AverageExpression(test,features = "Mki67",slot = "data")`

> Finished averaging RNA for cluster AnnData
> $RNA
>        AnnData
> Mki67 2.630147

`mean(GetAssayData(test,slot = "data",assay = "RNA")["Mki67",])`

> [1] 0.2922925

But this problem is disappear when change slot from "data" to "counts":
`AverageExpression(test,features = "Mki67",slot = "counts")`

> Finished averaging RNA for cluster AnnData
> $RNA
>        AnnData
> Mki67 64.33095

`mean(GetAssayData(test,slot = "counts",assay = "RNA")["Mki67",])`

> [1] 64.33095

And my seurat package version is 3.9.9.9002

**Comment by JenniferWUSTL** [comment]
Hi @yhli1992 , I am not a part of the Seurat team, but previously had experienced this confusion myself. I believe it is because `AverageExpression` output is in non-log space, and normalized `data` has been log-transformed.

**Comment by torkencz** [comment]
Hi. Just as @JenniferWUSTL said. The Data slot has been log normalized (you need to average on non-log normalized values). If slot is set to 'data', Average expression function assumes that the data has been log normalized and therefore feature values are exponentiated prior to averaging so that averaging is done in non-log space. So when you are doin the mean via GetAssayData you are averaging log normalized values.
