### ISSUE TITLE
Pull transcript id instead of gene id

### ISSUE THREAD

**Issue by aelias1** [satijalab/seurat#4193]
I want to look at alternative splicing.  My gtf has both gene name and transcript names that make this possible.  I was wondering if there's a way to pull this information per cluster using seurat and conduct DE analysis using transcript ids. Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  So this is mainly not a Seurat question unless you already have the differential isoform transcripts counts from your alignment pipeline.  If you do then you may want to consider re-running your analysis using transcript counts instead of gene counts because the results of your clustering may change compared to summing all isoforms together.

If you don't have the isoform count info then it's going to depend on how the sequencing reads were aligned and how the counts for each gene were generated (pre-Seurat).  Different pipelines will give different outputs and those will effect your ability to look at different transcript isoforms.  For instance you can find information from 10X Genomics [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/algorithms/overview) on how counting is performed via CellRanger (select appropriate version in bottom right).  
As another note the ability to detect different transcript isoforms is also going to be dependent on the type of single cell sequencing performed (full length vs. 3' capture vs. 5' capture & traditional short read Illumina vs. long read PacBio/ONT).  This will further effect ability of downstream aligners to detect different isoform transcripts accurately.

Best,
Sam

**Comment by Mangosteen24** [comment]
> Hi,
> 
> Not member of the dev team but hopefully can be helpful. So this is mainly not a Seurat question unless you already have the differential isoform transcripts counts from your alignment pipeline. If you do then you may want to consider re-running your analysis using transcript counts instead of gene counts because the results of your clustering may change compared to summing all isoforms together.
> 
> If you don't have the isoform count info then it's going to depend on how the sequencing reads were aligned and how the counts for each gene were generated (pre-Seurat). Different pipelines will give different outputs and those will effect your ability to look at different transcript isoforms. For instance you can find information from 10X Genomics [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/algorithms/overview) on how counting is performed via CellRanger (select appropriate version in bottom right). As another note the ability to detect different transcript isoforms is also going to be dependent on the type of single cell sequencing performed (full length vs. 3' capture vs. 5' capture & traditional short read Illumina vs. long read PacBio/ONT). This will further effect ability of downstream aligners to detect different isoform transcripts accurately.
> 
> Best, Sam

Hi @samuel-marsh . I have another question. I have a transcripts x cell barcode count matrix generated from single-cell long-read sequencing. May I ask if the regular Seurat workflow supports differential transcript identification between cell types using functions like FindAllMarkers? In this situation, should I use a count or TPM matrix as input? Thanks a lot!
