### ISSUE TITLE
Gene names converted to "NA" when using SplitDotPlotGG

### ISSUE THREAD

**Issue by catsargent** [satijalab/seurat#421]
I am having some problems creating the splitdotplot graph with our data (disease and control). For some reason, the different gene IDs are not shown on the x-axis and only 'NA' is shown. Subsequently all the dots are shown on top of one another as they all have the same gene ID ("NA").

This is the code that I am using to create the split dot plot and I cannot see what I am doing differently from the tutorial:

```R
heart.combined@ident <- factor(heart.combined@ident, levels = (c("Endothelial Cells", "Vessel Endothelial", "Fibroblasts1", "Fibroblasts2", "Proliferating Fibroblasts", "Macrophages1", "Macrophages2", "Smooth Muscle", "Cardiomyocytes", "Lymphocytes", "Epicardial", "Red blood cells")))

markers.to.plot <- c("Cdh5:ENSMUSG00000031871", "Pecam1:ENSMUSG00000020717", "Vwf:ENSMUSG00000001930", "Col1a2:ENSMUSG00000029661", "Col1a1:ENSMUSG00000001506", "Dcn:ENSMUSG00000019929",  "Lum:ENSMUSG00000036446", "Mki67:ENSMUSG00000031004", "Birc5:ENSMUSG00000017716", "Prc1:ENSMUSG00000038943", "Fcgr3:ENSMUSG00000059498", "Kcnj8:ENSMUSG00000030247", "Pdgfrb:ENSMUSG00000024620", "P2ry14:ENSMUSG00000036381", "Mhrt:ENSMUSG00000097652", "Lmod2:ENSMUSG00000029683", "Obscn:ENSMUSG00000061462", "Ttn:ENSMUSG00000051747",  "Lrrn4:ENSMUSG00000043110", "Upk1b:ENSMUSG00000049436", "Krt18:ENSMUSG00000023043", "Mmrn1:ENSMUSG00000054641", "Adgrg3:ENSMUSG00000060470", "Il7:ENSMUSG00000040329")

sdp <- SplitDotPlotGG(object = heart.combined, genes.plot = markers.to.plot, cols.use = c("blue", "red"), x.lab.rot = T, plot.legend = T, dot.scale = 8, do.return = T, grouping.var = "disease")
```

I also tried plotting just one gene using: 

```R
sdp <- SplitDotPlotGG(object = heart.combined, genes.plot = c("Cdh5:ENSMUSG00000031871"), cols.use = c("blue", "red"), x.lab.rot = T, plot.legend = T, dot.scale = 8, do.return = T, grouping.var = "disease")
```

And the gene id is given as "NA" here too. Could it be something to do with the length of the gene IDs?

Many thanks,
Catherine

**Comment by asigore** [comment]
Hi, 
I'm having a similar issue but with gene names that start with numbers rather than letters (e.g. markers.to.plot <- c("2010005H15Rik", "1500015O10Rik"). As Catherine mentioned "all the dots are shown on top of one another as they all have the same gene ID ("NA")" 

I only have gene symbols -not ENSEMBLE gene ids- as gene identifiers. Is there a way around it without having to change the gene name?

Thanks, 

Ana

**Comment by mojaveazure** [comment]
Hi Ana,

This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](http://satijalab.org/seurat/devinstall).

**Comment by asigore** [comment]
Hi Paul,

Thank you for the quick response! 
I'm sorry I forgot to mention that I'm having the same issue with the "DotPlot" function (I imagine is a similar fix, but I wasn't sure if I should open a new issue...). 

For "SplitDotPlotGG",  I just installed the development version (after seeing your post). I re-loaded the same precomputed Seurat object I was working with before. However I still get the same result: genes plotted as NA. (Running R version 3.4.4). From what I see on how the issue was fixed it doesn't seem that I need to change anything on the Seurat object. Is there something I'm missing? Do I need to do anything else for the update to work? Please let me know if you need additional information. Thank you, 

Ana

**Comment by mojaveazure** [comment]
Hi Ana,

If you run `View(SplitDotPlotGG)`, what do you see on lines 18-24?

**Comment by mojaveazure** [comment]
Hi Ana,

So it looks like the development version of Seurat didn't install properly; line 19 should say `colnames(x = data.to.plot) <- genes.plot`. Try installing the development version again:
```R
devtools::install_github(repo = 'satijalab/seurat', ref = 'develop')
```

**Comment by asigore** [comment]
OK, I'm unsure why it didn't install properly... just reinstalled and that worked for both SplitDotPlotGG and DotPlot functions. However now there seems to be an issue with hyphenated gene names (i.e. hemoglobin, mitochondrial MHC genes, etc.). 
markers.to.plot = c("Hba-a2", "Hba-a1", "Hbb-bt"). Now those are being plotted as NAs, which wouldn't happen before... 

Thanks a lot for looking into this!!
Ana

**Comment by mojaveazure** [comment]
Hi Ana

Alright, that should be fixed now. Can you try again?

**Comment by asigore** [comment]
Hi Paul, 

Working beautifully now! Thank you for the upgrade, and the great tool you guys have built! 

Ana

**Comment by catsargent** [comment]
Hi Paul,
Many thanks for getting back to me about this and for fixing the issue!
Catherine
