### ISSUE TITLE
Feature plot- change y-label for multiple features

### ISSUE THREAD

**Issue by Tomer9w** [satijalab/seurat#4223]
Hi there
I'm using FeaturePlot function to project more than 2 features on the t-SNE map, wondering how to change the y-label from the default gene name to my desired text?

Here is my code snippet:
`[FeaturePlot(CD45_data, features = c('Tnfrsf4','Tnfsf4'), split.by = 'Sample', label= T, pt.size = 1.3 ,ncol = 2, order =T)
`
Tried using ylab: `+ ylab("OX40L)` but it doesn't help in this case. 

How can i control both features y-axis name?

Thanks a lot!

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully can be helpful.  There's couple things that you need to do here but it is doable.  First, is that I don't think you want to replace the actual `ylab` as that is the "UMAP_2" axis label.  What you want to replace is the second y axis label.

To do this and maintain the yaxis scale of the original plots when splitting the plots as well just requires one extra step because the split plots may not contain the ful axis range depending on your specific data.
```
# First you should plot a DimPlot and save to environment:
p <- DimPlot(CD45_data)

# Then pull the y-axis dimensions from that plot
y_lim <- ggplot_build(p[[1]])$layout$panel_params[[1]]$y.range

# The run this code to modify second y-axis label but maintain the dimensions of the plot:
FeaturePlot(CD45_data, features = c('Tnfrsf4','Tnfsf4'), split.by = 'Sample', label= T, pt.size = 1.3 ,ncol = 2, order =T) & scale_y_continuous(sec.axis = dup_axis(name = "OX40L"), limits = y_lim)
```

Best,
Sam

**Comment by Tomer9w** [comment]
Thanks Sam!

So how can i change more than 1 feature name?
Tried to change Tnfrsf4 to OX40R and Tnfsf4 to OX40L, couldn't figure out how

Thanks very much!

**Comment by torkencz** [comment]
Hi,
Currently, Seurat does not allow renaming of features after creation of an object. So you would have to go back and change it at an earlier stage. However, the labels in FeaturePlot are simply ggplot2 titles. This means you can change the label on the plot simply by changing the plot title using ggplot2's utilities.
This might help:
https://github.com/satijalab/seurat/issues/1430
