### ISSUE TITLE
Problems with SubsetData() in version 4.0.0

### ISSUE THREAD

**Issue by Friedpollo** [satijalab/seurat#4224]
In seurat version 4.0.0, the command SubsetData() is removed, which command should i use if i want to choose the subclusters cells from the single_cell.rds document? 
PS: I also used command sub_singlecell = subset(single_cell@meta.data, seurat_clusters = 0) , but it seems like this command cant select all the information from the .rds document,only the information in meta.data is selected. :(

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  The command to use for subsetting a Seurat object is `subset` and you can see more details of the parameters that you can provide in the manual entry in the Seurat package.  The code that you ran `sub_singlecell = subset(single_cell@meta.data, seurat_clusters = 0)` specified the meta data as the input for subsetting so that is why only the metadata was returned.
To subset on a cluster identity from full Seurat object you should run the following:
`obj <- subset(x = obj, idents = 0)`

Best,
Sam

**Comment by Friedpollo** [comment]
> Hi,
> 
> Not member of the dev team but hopefully can be helpful. The command to use for subsetting a Seurat object is `subset` and you can see more details of the parameters that you can provide in the manual entry in the Seurat package. The code that you ran `sub_singlecell = subset(single_cell@meta.data, seurat_clusters = 0)` specified the meta data as the input for subsetting so that is why only the metadata was returned.
> To subset on a cluster identity from full Seurat object you should run the following:
> `obj <- subset(x = obj, idents = 0)`
> 
> Best,
> Sam

Thanks bro! I dont know why after typing the command it gives me the message: Warning: The following arguments are not used, but your idea really gives me the spark, i tried code sub_singlecell = subset(single_cell, seurat_clusters=="0") or sub_singlecell = subset(single_cell, seurat_clusters==0), the problem has been solved!

**Comment by lizisiyuanzhang** [comment]
sub_pbmc <- subset(pbmc,
                   subset= seurat_clusters %in% c("0", "1", "2"))
                   )

table(sub_pbmc@meta.data$seurat_cluster)
ry this code and run it as a seurat object.

**Comment by lizisiyuanzhang** [comment]
sub_pbmc <- subset(pbmc,
subset= seurat_clusters %in% c("0", "1", "2"))
)

table([sub_pbmc@meta.data](mailto:sub_pbmc@meta.data)$seurat_cluster)

**Comment by lizisiyuanzhang** [comment]
sub_pbmc <- subset(pbmc,
subset= seurat_clusters %in% c("0", "1", "2"))
)

table([sub_pbmc@meta.data](mailto:sub_pbmc@meta.data)$seurat_cluster)

Please try this code and run it as a seurat object.
