### ISSUE TITLE
How to import a dataset txt with metadata row labels as a Seurat object?

### ISSUE THREAD

**Issue by tshum-05** [satijalab/seurat#4239]
Hi, I'm new to single cell RNA sequencing, and I wanted to reproduce the results in a published dataset (Tirosh, et al, Dissecting the multicellular ecosystem of metastatic melanoma by single-cell RNA-seq, Science, 2016). The only data I currently have access to an integrated dataset file from the GEO repository (http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE72056). There are additional rows of column labels defining their ground truth cell type (tumor, malignant vs non-malignant), which is the metadata component. Can somebody please give me advice for importing this whole dataset into Seurat? Initially I thought about doing

Tirosh.data <- read.table("../GSE72056.txt.gz") 
Tirosh<- CreateSeuratObject(counts = Tirosh.data, min.cells = 3, min.features = 200)

but I wasn't sure how to tell Seurat to identify the metadata component.

I've taken a look at the Seurat guided clustering tutorial and other Seurat tutorials that start with importing the file as a readRDS, read.csv, or read.table for separate pre-made count matrix and and metadata files, but I don't have a good idea for creating a Seurat object from a txt file in which the metadata is already part of the csv or txt file. I would greatly appreciate advice on this.

**Comment by kc-mcp** [comment]
I too would am searching for advice on this!!! I was about to post a similar question! lol

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The way to do this is to create separate inputs for the gene information and the meta data.  I'll provide example code below but couple notes you should know about this data before importing and working with.  
First, it is not raw count values.  You can tell this because there are decimal points in the data.  For full information on how they processed the data you can see the [data processing section of one of the samples](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1850539).
Second, as part of that data processing section they appear to have already done some filtering based on genes expressed in X number of cells and min gene thresholds so may be good to not set those values when creating the object.
Finally, there are duplicate row names in their gene values for couple of genes.  Not sure where these came from and up to you how to deal with them.  For simplicity in code below I just renamed the duplicates using `make.unique` but you may want to figure out why the duplicates exist and either concatenate them if they truly are duplicates or find another solution.

Best,
Sam


```
library(Seurat)
library(dplyr)

# Read in entire file
tirosh <- read.delim("~/Downloads/GSE72056_melanoma_single_cell_revised_v2.txt.gz", header = T, stringsAsFactors = F)

# Pull only gene information
tirosh_genes <- tirosh[-1:-3,]

# Duplicate gene names so make names unique (up to you how you want to deal with this part)
gene_list <- tirosh_genes %>% 
  pull("Cell") %>% 
  make.unique(sep = ".")

# Add back unique rownames
rownames(tirosh_genes) <- gene_list

# Remove Column of gene names
tirosh_genes <- tirosh_genes[, -1]

# Pull meta data columns from original data
tirosh_meta <- tirosh[1:3,]

# Make rownames equal to column 1 values
rownames(tirosh_meta) <- tirosh_meta[, 1]

# Remove column 1
tirosh_meta <- tirosh_meta[, -1]

# Transpose meta data as Seurat expects meta data to have cell names as rows and meta data values as columns
tirosh_meta_transpose <- data.frame(t(tirosh_meta))

# Create Seurat Object
tirosh_seurat <- CreateSeuratObject(counts = tirosh_genes, meta.data = tirosh_meta_transpose)
View(tirosh_seurat@meta.data)
```

**Comment by tshum-05** [comment]
Thanks Sam, works like a charm!
