### ISSUE TITLE
Normalization after filtering steps

### ISSUE THREAD

**Issue by GildasLepennetier** [satijalab/seurat#4249]
I am wondering if one should re-run the first step of the workflow after each filtering step. Here is the workflow:

A) Here is the filtering on the minimum number of features / reads / mitochondrial content. After, one should:
1. NormalizeData
2. FindVariableFeatures
3. ScaleData
4. RunPCA
5. RunUMAP
6. FindNeighbors

B) At this point, I filter a significant amount of cells based on scDblFinder to find some putative doublet that could be missed by the previous filtering. Should I now run again the steps 1 to 6 to obtain a better clustering? 

There are several questions about normalization on integrated data and subsets, but I do not find a clear answer to this specific question, which is probably just a matter of logic. Thank you in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not a member of the dev team but hopefully can be helpful.  For the basic pipeline you mention using the `NormalizeData` function, so as long as you preserve the normalized data slot when removing/subsetting the original object based on doublet filtering you don't need to re-run that particular step.  As defined in the manual entry:
`LogNormalize: Feature counts for each cell are divided by the total counts for that cell and multiplied by the scale.factor. This is then natural-log transformed using log1p.`  
So as long as you only removed cells and not genes too you can see that the normalized expression values for the remaining cells will be the same due to how normalization is performed.

However, the other steps should be re-run.  The identification of variable features, PCA, Neighbors, Louvain clustering, UMAP, etc are all going to be dependent on the cells present in the object.  If the cells present change then each of those results will also change and the end clustering visualization will change.

i.e. Different cells present will change the genes identified during find variable features >
It will change ScaleData because default is to scale only variable features (also the scaling depends on expression of feature in cells across the dataset which will change depending on cells present) >
Again default for PCA is to use variable features which have changed >
etc, etc

Best,
Sam

**Comment by GildasLepennetier** [comment]
Dear Sam, thank you for your answer.
