### ISSUE TITLE
Seurat_4.0.0 and Seurat_3.2.3   have different results

### ISSUE THREAD

**Issue by zznx** [satijalab/seurat#4261]
Different versions of Seurat draw different cluster diagrams

**Comment by samuel-marsh** [comment]
Hi,

Not member of Dev team but hopefully can be helpful.  I would suggest checking out #4217.  The difference why things are not exactly the same is likely due to the change in neighbor finding algorithm.  From V4 ChangeLog:
`Default neighbor finding algorithm changed from "rann" to "annoy"`

Best,
Sam

**Comment by zznx** [comment]
Thank you so much Sam
