### ISSUE TITLE
How to transform Seurat object to csv format 

### ISSUE THREAD

**Issue by kysbbubbu** [satijalab/seurat#427]
I am trying to do some secondary analysis of Seurat object in Granatum
How can i transform Seurat object to csv format?
I want filtered expression data to csv format...

**Comment by milescsmith** [comment]
```
library(data.table)
data_to_write_out <- as.data.frame(as.matrix(seuratObject@data))
fwrite(x = data_to_write_out,` file = "outfile.csv")
```

**Comment by kysbbubbu** [comment]
Thanks, It worked!!! 
In addition, the resulting csv file did not include row names. 
I changed script to 
fwrite(x = data_to_write_out, row.names = TRUE, file = "outfile.csv")

**Comment by mojaveazure** [comment]
The method @milescsmith specified uses the gene names in the Seurat object. We do not provide a database of Ensembl IDs; to convert your gene names to Ensembl IDs, you can either do this in R by matching your gene names to Ensembl IDs and changing the row names, or manually in your favorite CSV editor (eg. Excel). You could also create a Seurat object with Ensembl IDs instead of gene names, rerun your analysis, and write out the CSV from that new Seurat object.

**Comment by YangLilith** [comment]
Hi,

I have the same problem. But when I tried using the code above. I had an error :

> data_to_write_out <- as.data.frame(as.matrix(kidney_object@scale.data))
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

I have no idea why @scale.data is null. Could you help me?

Thanks

**Comment by par21** [comment]
I have a question concerning Seurat 3.
 
How can I create TSNE plot just based on list of genes. I have CSV file which contains around 2000 genes. I would like to extract only these genes from Seurat object and create TSNE base on new Seurat object (which contains all cells but only 2000 of Features).
Thanks for your help in advance

**Comment by whitneyt1** [comment]
Is it possible to export the CSV with metadata as well? 

Thank you!

**Comment by IqRaZaFaR16** [comment]
hi i have metdata.csv file from scRNA-seq data how i can convert it into seurat object and then integrate this dataset with scATAC-seq data
