### ISSUE TITLE
Dotplot shows partially grey dot

### ISSUE THREAD

**Issue by mnakaya5** [satijalab/seurat#4274]
I am integrating 2 data set, one has been already integrated and the other is not integrated. I could make umapa however the Dotplot shows grey partially like here:
![Dotplot](https://user-images.githubusercontent.com/69719544/112282492-835b1900-8cca-11eb-908c-4d54b7f66b78.png)

What happened on this Dotplot?

**Comment by ktrns** [comment]
Hi @mnakaya5, 

Can you post your command for the `DotPlot` as well?

Best
Katrin

**Comment by mnakaya5** [comment]
Hi, @ktrns 
Here is the command for Dotplot.

#GeneExpression
DefaultAssay(integration) <- "RNA"
DotPlot(integration, features = c("tdTomato", "Acta2", "Eng", "Alcam","Cd44", "Nt5e", "Cd34", "Ptprc", "Thy1", "Runx2", "Sox9", "Lgals3", "Sp7", "Alpl", "Ibsp", "Spp1", "Col1a1", "Col1a2", "Bglap", "Bglap2", "Sost", "Bglap3", "Dmp1", "Mepe", "Ctnn1", "Prrx1", "Col2a1", "Acan", "Col9a1", "Col10a1"), cols = "RdYlBu") + RotatedAxis()

**Comment by ktrns** [comment]
Mmh, not sure I get why you have grey dots. I'd advise you to take the code of the `DotPlot` function and run it bit by bit. 

Hope that helps anyhow, 
Katrin

**Comment by torkencz** [comment]
Hi, this is a similar issue to: https://github.com/satijalab/seurat/issues/1715 .This likely due to the features present in the Integrated assay.
When you perform DotPlot , you would better confirm that default assay is RNA, or you can set assay in the DotPlot. DotPlot(obj, assay = "RNA"). For a heatmap or dotplot of markers, the scale.data in the RNA assay should be used.

Here is an issue explaining when to use RNA or integrated assay. It may be helpful.
https://github.com/satijalab/seurat/issues/1717
