### ISSUE TITLE
Some genes fail to be regressed out by SCT

### ISSUE THREAD

**Issue by KGrimstadN** [satijalab/seurat#4338]
Hi, 

I am working with a few datasets of memory B cells from humans, so quite homogeneous samples. I have both the "transcriptome data" as well as the separate V(D)J data for each of the samples separately, and as such, we are appending the V(D)J data as metadata to the Seurat object, to look at distribution of heavy chain isotypes based on the V(D)J data. For this reason, I have tried to regress out any immunoglobulin genes from the transcriptome data when running SCT. In general, I've been going back and forth to include more of these genes as new ones sometimes show up once others have been regressed out. However, there are a few of these genes that do not seem to "disappear" in this step, most notably the heavy chain C genes (IGHG1, IGHM, IGHG2 etc.), as well as some light chain genes. Since the transcriptome data doesn't take into account sterile transcripts or unproductive transcripts, it is our understanding better to exclude them from the transcriptome data and instead explore these genes in the V(D)J data (since, if using the transcriptome data, there seem to be impossible results in terms of combinations of various heavy chain isotypes expressed in cells). Any idea how to solve this? 

I have been using basically the same code for all genes that I want to regress (see below), which works fine for most genes, but some, especially the IGH genes, seem to persist even after regressing in SCT (and show up as marker genes for various cell clusters). 

Thanks in advance!

The code (only including the IGH genes here; there are more genes involved in some cases): 

```
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHM", col.name = "IGHM")
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHA1", col.name = "IGHA1")
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHA2", col.name = "IGHA2")
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHG1", col.name = "IGHG1")
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHG2", col.name = "IGHG2")
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHG3", col.name = "IGHG3")
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHG4", col.name = "IGHG4")
ra2.1 = PercentageFeatureSet(object=ra2.1, features = "IGHE", col.name = "IGHE")

ra2.1=SCTransform(object=ra2.1, variable.features.n = 16102, vars.to.regress = c("IGHE", "IGHA1", "IGHA2", "IGHM", "IGHG1", "IGHG2", "IGHG3", "IGHG4"))
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So first I would recommend never naming the percentage feature sets with the actual gene names because that can cause issues in Seurat identifying which element you are trying to plot.  

Second, (and this may be your intent) but not sure why you are creating percentage feature sets from these genes.  If you want to regress the genes from your analysis you can simply provide the list of genes to the `vars.to.regress` or create a single module score encompassing all of the IG genes you want to regress (similar to what is performed for cell cycle regression in the Seurat tutorial vignettes).

Lastly, regression of these genes will not remove them from the analysis.  They will still be present but the idea is to lessen or remove their impact on downstream dimensionality reduction and therefore clustering.  See description from Seurat Devs from another post:

> `vars.to.regress` in `ScaleData()` and `SCTransform()` specifies variables to regress out of the scaled data or sctransform residuals. These values are typically used for PCA dimension reduction, and so would prevent those variables that are regressed out from contributing much to the PCA.

Best,
Sam

**Comment by KGrimstadN** [comment]
Hi, 

Great point, thank you! I will have a look at this. I realize you do not actually "delete" the genes by regressing them out, but was going for not having them affect the clustering, however I have some instances where the only significant markers for a specific cell cluster would be some of these genes, which to me kind of suggests that, if ignoring the effect of these genes, than these cells should not be in a separate cluster. 

Thank you!

Regards, 
Kristoffer
