### ISSUE TITLE
Cannot download 3.9.9.9024

### ISSUE THREAD

**Issue by NicolaasVanRenne** [satijalab/seurat#4383]
I cannot seem to download version 3.9.9.9024

> remotes::install_github(repo = 'satijalab/seurat', ref =  "release/3.9.9.9024") 

does not work

however, version 4.0.0 does work

> remotes::install_github(repo = 'satijalab/seurat', ref =  "release/4.0.0")

I need this because I cannot reproduce my work (done with 3.9.9.9024) with 4.0.0 or above. The UMAP plot is slightly different. Or is this due to another package for which I made an update? Why oh why is there a UMAP plot difference between 3.9.9.9024 and 4.0.0/4.0.1? Is there a setting I can apply to make the UMAP of 4.0.0 run like it was 3.9.9.9024? 

Thanks so much for helping...

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  As @timoast mentioned in #4370 you need to supply the commit that you want to install.  "release/3.9.9.9024" is not a commit itself.  Going back through commit history here is the commit where the version was bumped to "3.9.9.9024" during development:
```
remotes::install_github(repo = 'satijalab/seurat', ref = 'a20d5fc3ee4a16fcd4b97f92d41d8e4bcdae3da9')
```

As another note I would recommend not updating when you are about to submit a paper unless you truly absolutely need a new functionality.  I'd also recommend using the `renv` package to isolate your analysis environments and avoid unintentional updating of packages that may alter your results and will help reproducibility of your analyses for those following your code.

Best,
Sam

**Comment by NicolaasVanRenne** [comment]
Dear Sam, 

You are my absolute hero. Thank you.

Still any idea why there is a difference? I thought 3.9.9.x were v4beta versions, that's why I wrongly assumed upgrading to v4.0.1 would not be different. I guess I found out the hard way. 

Nicolaas

**Comment by samuel-marsh** [comment]
Nicolaas,

So there are a number of reasons.  First, is that while yes it was a beta version there were 14 more version bumps before the end of that branch (up to version 3.9.9.9038).  That doesn't include any changes to v4 before release from other branches or any changes post release before v4.0.1.  So depending on your pipeline and what changes were made in the interim time that could effect your results.

It could also be completely Seurat independent and be due to changes in another package that you updated that slightly tweaked its parameters.  One potential culprit could be a change in uwot package which provides the R native implementation of UMAP.  

This is again why it's good to be very careful when updating packages mid-analysis and keep track of which versions you were previously using as analysis goes on.  Again suggest you check out [renv package](https://cran.r-project.org/web/packages/renv/vignettes/renv.html) which can be used with RStudio to create project specific package libraries that are independent from each other with minimal setup on user end.

This won't help for github related installs but if you are dealing with CRAN packages and you know the date that you want to mimic versions of, you can use the [versions package](https://cran.r-project.org/web/packages/versions/index.html) which allows to you specify installing the version of package based on what version was available on specific date using the MRAN snapshot repository.  Be careful with this though if not using inside `renv` because setting an older date will downgrade any packages in system library that you install and may break dependencies of newer packages.

Best,
Sam

**Comment by NicolaasVanRenne** [comment]
Hello Sam,

Thanks for the renv suggestion. It seems to work well by calling renv::restore(), closing R and reloading the Seurat package

However: it appears that the Seurat version is now 'stuck' in 3.9.9.9024. Is there a command to 'unload' the renv::restore() command? Or if I want to go back to 4.0.1 I just have to reinstall v4 package? (hope this makes sense)

Also: the settings are store in renv.lock if I understand correctly. Say I want to save a second renv environment, but I want to keep this renv.lock, then I just store this file someplace else until I need it?

**Comment by samuel-marsh** [comment]
Hi,

So this is getting outside realm of Seurat relevance but as basic resource I would recommend RStudio Projects oriented workflow if you aren't using that already.  See these two resources for good intro to the basics from Hadley Wickham and Jenny Bryan/Jim Hester:
[https://r4ds.had.co.nz/workflow-projects.html](https://r4ds.had.co.nz/workflow-projects.html)
[https://rstats.wtf/project-oriented-workflow.html](https://rstats.wtf/project-oriented-workflow.html)

If you are using project oriented workflow then when you call `renv::init` then what you install package wise will remain limited to that project.  So you can have project with the specific package library of Seurat, uwot, other packages etc.  When you start new project it go back to whatever is in the package library at the system level without affecting that other project.  This way you can keep isolated workflows that are easy to restore, pass to others, version control, etc.  I'd recommend checking out other tutorials on renv for more details on how to use package in analysis and project-oriented workflow.

Best,
Sam
