### ISSUE TITLE
Revise comments to indicate that Seurat's MAST implementation does not by default use cellular detection rate as a co-variate.

### ISSUE THREAD

**Issue by tcikezu** [satijalab/seurat#4393]
I wanted to confirm whether [this documentation](https://github.com/satijalab/seurat/blob/4e868fcde49dc0a3df47f94f5fb54a421bfdf7bc/R/differential_expression.R#L1620) for MASTDETest is accurate -- I think the default formula is ' ~ condition', and not '~ condition + nUMI'.

**Comment by timoast** [comment]
The `MASTDETest` function is not actually exported, and so that comment that you referred should not be considered documentation (it does not contribute to any man pages in the Seurat package). However, the comments are outdated and misleading for anyone reading the source code, so I will remove them.

**Comment by tcikezu** [comment]
Hi, thank you for the clarification.

**Comment by timoast** [comment]
This has now been updated on the Seurat develop branch
