### ISSUE TITLE
Split Dot plot is missing Color Key  

### ISSUE THREAD

**Issue by vishnums007** [satijalab/seurat#4406]
![Rplot01](https://user-images.githubusercontent.com/81267539/115966252-4d3fcd80-a4f2-11eb-84b8-fdc80aea77e4.png)

I am trying to make dot plot with my integrated SC data in Seurat . As soon as I use the split function, the color key disappears. Only the percent Expressed remains.  can anyone help me how to get the color key back?
here is the code I used, 

DotPlot(zebra, features = unique(top20$gene)[1:10], dot.scale = 8, split.by = "new-identity", 
        cols = c("Blue", "red"))+
        RotatedAxis()

Also, I would like to use scale_color_gradient2 for each split group ( not just Blue and Red). something like scale_color_gradient2(low = "blue3", mid = "white", high = "red3") for my Vehicle and treated. Any help is appreciated. Thanks.

**Comment by torkencz** [comment]
Hi,

The color key is actually different in the vehicle (red) and the treated (blue) groups, where color scale goes from grey to red and grey to blue. It is not plotted because the number of groups would make it more and more confusing. You can change the end color by changing the cols arguments. If you want a little more control I would split the object by treatment and then do the dot plot on the two objects.
