### ISSUE TITLE
Seurat V4 PBMC Atlas dataset contains no scale.data information, no RNA assay to re-do SCT?

### ISSUE THREAD

**Issue by mr-september** [satijalab/seurat#4441]
As title, [pre-processed PBMC atlas](https://satijalab.org/seurat/) contains SCT and ADT (what is ADT?) Assays, both are missing scale.data. 

Attempting to re-run SCTransform to get scale.data to `runPCA` returns

```
Error in GetAssay.Seurat(object = object, assay = assay) : 
  RNA is not an assay present in the given object. Available assays are: SCT, ADT
```

What should I do? I am trying to re-cluster the data to test some methods I'm working on.

**Comment by messersc** [comment]
Hi,

ADT are the counts for the **A**ntibody **d**erived **t**ags in CITE-seq, see https://en.wikipedia.org/wiki/CITE-Seq. So basically information on which surface markers a cell expresses.
SCT then should be the single cell transcriptome. And the error you get is because the assay is not called "RNA" as usual, but "SCT". So you either have to rename it or give as a parameter so that it is clear which of the two assays should be scaled.

Clemens

**Comment by yuhanH** [comment]
Hi, 
Our atlas reference is mainly used for mapping and visualization. In order to keep the object small, we didn't include RNA assay and all scale.data.  Since all dimensional reduction, weighted KNN and weighted SNN graphs are in the object, you can re-cluster cells. 
Also, you can find all count matrices in [GSE164378](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE164378).
