### ISSUE TITLE
Adding cluster labels to meta.data of a Seurat object when the labels file has fewer rows than the original Seurat object

### ISSUE THREAD

**Issue by l-cli** [satijalab/seurat#4471]
I'm trying to add a .tsv file with cluster labels that looks like this to the meta data of my Seurat object:

```
Cells	0

ATGATCGTCTACCACC	Cluster 6

GAAGCCCAGTTACTCG	Cluster 2

CAAGCTACACGGTGTC	Cluster 7

CACAACACACAGTATC	M8

CATCCACGTTCGGTTA	Cluster 2

ATGCATGGTGTGGTCC	Cluster 3

ACCCTTGTCTCGGGAC	Cluster 6

CTGCATCCAACACGAG	Outliers

TTGAACGGTGCCTAAT	M1

TATGTTCTCCACCTGT	M3

ATCAGGTGTCGAGTTT	Cluster 3

AGGGTGAAGTGGTCAG	M2

GCCTGTTTCGAGCTGC	Cluster 3
```

But this file has fewer cells than the Seurat object I already have. My Seurat object looks like this:
![image](https://user-images.githubusercontent.com/55997222/118216145-8e176c00-b438-11eb-957f-3984724cc525.png)

Because the barcodes are in active.idents, not meta.data, I cannot directly add to the meta.data using dplyr by matching the cell barcodes. Is there a way to merge the labels into meta.data so that extra rows in meta.data are deleted accordingly?
Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So first just by looking at your image the barcodes are not the active.ident your active ident is "fastTopics" (`Factor with 14933 levels: "fastTopics", etc`).  It is simply listing the active.ident by barcode.

The barcodes are present in multiple aspects of the object including as the row names of metadata.

In order to filter the object to only contain the barcodes in the annotation file, you should first pull the barcodes from the annotation file.  Then using `subset` pass these barcodes to the `cells` parameter.
i.e.:
```
filtered_obj <- subset(x = obj, cells = annotation_barcodes)
```

Then to match and add meta data you can do something like following.  Although I would suggest renaming the cluster column in the annotation file to something other that "0" which is what it appears to be in example above before beginning the process as the column name will be the new column name in the object meta data after this.

```
# Extract current meta data and move barcodes to column
obj_meta <- filtered_obj@meta.data %>% 
  rownames_to_column("barcodes")

# Merge with annotation file, move barcodes back to rownames, and remove already included meta data
joined_meta <- inner_join(obj_meta, annotation_tsv, by = c("barcodes" = "Cells")) %>% 
  column_to_rownames("barcodes") %>% 
  select(barcodes, 0)

# Add to Seurat Object
filtered_obj <- AddMetaData(object = filtered_obj, metadata = joined_meta)
```

Best,
Sam

**Comment by l-cli** [comment]
Thank you Sam! Can you explain what the column_to_rownames("barcodes") is doing? When I had it in my codes dplyr does not allow me to select because it says "there is no column named "barcodes"", but when I deleted it there is no error...
Also after the process the Seurat object looks like this:
![image](https://user-images.githubusercontent.com/55997222/118286577-36105200-b498-11eb-8fdc-da881fdd84b0.png)
I can't seem to find where the labels are...Any suggestions?

Thank you again!

**Comment by samuel-marsh** [comment]
Hi,

Whoops that's my bad, typo there.  That final command should be (with the "0" replaced by whatever you renamed the cluster column in the annotation tsv.
```
joined_meta <- inner_join(obj_meta, annotation_tsv, by = c("barcodes" = "Cells")) %>% 
  column_to_rownames("barcodes") %>% 
  select(0)
```

The point of column to rownames is to create a data.frame that contains the same row names in same order as the meta.data slot in your filtered object.  Then you can use the `AddMetaData` command to add the new column containing cluster labels to the existing meta data.

Best,
Sam

**Comment by jaisonj708** [comment]
You should be able to add an unnamed vector as meta data using `object[['desired.name']] <- vec`. Alternatively you can create a data frame with the appropriate row names and add using `AddMetaData` as Sam has suggested

**Comment by samuel-marsh** [comment]
@jaisonj708 Just to confirm though adding the unnamed vector would only work if the annotation file and the seurat object had the row names in the same order correct?

Best,
Sam

**Comment by l-cli** [comment]
Hi Sam, 
The last comment worked, thank you so much!
