### ISSUE TITLE
Physical separation of clusters in Seurat's TSNE Plot

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#459]
Hello All,

I originally posted this question here https://github.com/satijalab/seurat/issues/291

But I'm still a bit confused about the proposed solution there.  If I have clusters in the TSNE plot that are close together and even a bit overlapping, and then I manually try to change the axes limits, I'm not sure how I can get the clusters to become denser and physically more apart from each other to make a better-looking TSNE plot.  If I zoom out, then the clusters that were originally touching each other would only become closer.  If I zoom in, then I will have to lose some of the clusters from the frame.

Any other suggestions to physically separate the clusters on the TSNE plots?  I know there is perplexity to play with, but it doesn't always help in achieving this particular goal without other side-effects.  What do people do to get some of the nice-looking plots in recent papers, for example, the microWellSeq paper, where the clusters are so dense and far apart from each other?  Does that have to do with just the nature and size of their dataset?  Or is there something else we can do?  I would really like to know.

Thanks a bunch!

**Comment by leonfodoulian** [comment]
Hi,

Those "nice-looking plots" simply reflect the dataset (i.e. genes slected to compute PCA, and subsequent embedding on t-SNE). Although t-SNE is used for visualization purposes (especially due to how the plot changes by changing the perplexity parameter), this is not a reason why one would want to change the cell embeddings of the t-SNE post calculation, IMHO. 

Best,
Leon
