### ISSUE TITLE
Mixscape classification global

### ISSUE THREAD

**Issue by lo2811** [satijalab/seurat#4591]
Hi,
First, thank you for the Mixscape package. The documentation is very detailed and easy to follow. 
I have a question related to how Mixscape classifies a cell as NT if that cell has a gRNA assigned to it. In my analsyis, I found that there are 508 cells (~2% of the cell population) being classified as NT in the mixscape_classification.global. If these cells have an assigned gRNA and RunMixscape doesn't detect any transcriptional changes, should they be assigned as NP, rather than NT?
Thank you!

**Comment by epapalexi** [comment]
Hi,

Mixscape only classifies cells as KO or non-perturbed (NP). The NT cells are user defined prior to running mixscape. This is because we assume that cells expressing non-targeting control guides by definition should not have any transcriptomic shifts. When we run mixscape we compare every cell with a gene targeting gRNA to the NT cells and determine if the cell is truly perturbed (KO) or NP. 

So the 508 cells that are NT after mixscape are the same cells as the ones you classified as NT based on gRNA counts prior to mixscape.

I hope this clarifies things.
