### ISSUE TITLE
Dispersion plots

### ISSUE THREAD

**Issue by yjgeno** [satijalab/seurat#4613]
Hi, I was trying to understand alternative ways to select HVGs. I did an experiment:
`pbmc <- NormalizeData(object = pbmc)`
`pbmc2 <- FindVariableFeatures(object = pbmc, selection.method = 'mean.var.plot')`
`pbmc3 <- FindVariableFeatures(object = pbmc, selection.method = 'dispersion')`
`VariableFeaturePlot(object = pbmc2, selection.method = 'mean.var.plot')`
`VariableFeaturePlot(object = pbmc3, selection.method = 'dispersion')`

pbmc2 and pbmc3 plot are:
![2](https://user-images.githubusercontent.com/77600778/121618561-9610fe80-ca2c-11eb-8473-9fc1c0868eb9.png) <br>
![3](https://user-images.githubusercontent.com/77600778/121618589-a32ded80-ca2c-11eb-86e4-e520d028f660.png) <be>

Intuitively, I thought the latter plot would be from the method 'mean.var.plot', as we saw bins, and the former one with the absolute threshold would be from the method 'dispersion'. Should they be reversed?

**Comment by yjgeno** [comment]
Hi any insights here?

**Comment by yuhanH** [comment]
HI @yjgeno 
Sorry for the delayed reply. 
It is an issue in `VariableFeaturePlot `. It plots the scaled dispersion rather than dispersion value. 
When you use dispersion method to find variable genes and plot them by `mvp.mean`and `mvp.dispersion`, you can see the dispersion threshold. Thanks for reporting this. We will fix it soon.
![image](https://user-images.githubusercontent.com/29529544/127696764-cd891a50-db70-4afe-8545-42abf1b0d54f.png)

example code:
```

library(SeuratData)
data('pbmc3k')

pbmc3k <- NormalizeData(object = pbmc3k)
pbmc3k <- FindVariableFeatures(object = pbmc3k, selection.method = 'dispersion')

hvf.info <- pbmc3[['RNA']]@meta.features
 
p1<- SingleCorPlot(
data = hvf.info[,c('mvp.mean', 'mvp.dispersion.scaled')],
col.by = hvf.info$mvp.variable,
 )

p2<- SingleCorPlot(
  data = hvf.info[,c('mvp.mean', 'mvp.dispersion')],
  col.by = hvf.info$mvp.variable,
)

p1+p2
```

**Comment by yjgeno** [comment]
Hi @yuhanH thanks for your reply! now it makes much more sense to me for the dispersion method
Are you planning to update this function?

**Comment by yuhanH** [comment]
Hi, 
Right. We will update this function soon.

**Comment by yjgeno** [comment]
@yuhanH great, glad to know that
