### ISSUE TITLE
Counts Missing from CCA Integrated Object

### ISSUE THREAD

**Issue by oellis1** [satijalab/seurat#4619]
Hi,

I am having issues running CCA twice on an object, which I believe is because some of the objects in 'counts' are missing from the integrated assay.

I am working with a dataset where I have two biological replicates for each condition (i.e. control1, control2, stim1, stim2). I want to first merge the two replicates through CCA, and then do CCA on the integrated objects of each condition. I have followed the instructions from this vignette:
https://satijalab.org/seurat/articles/integration_introduction.html

This works fine for my first integration (control1 + control2). However, when I run CCA the second time (for control_integrated and stim_integrated), I get an error. I am not sure why some of the variables from counts are filled with 0's in the integrated object, but I suspect that is the issue. How can I fix this error?

**Comment by jaisonj708** [comment]
I would suggest trying to integrate all 4 samples at once. `IntegrateData` will construct a sample tree such that more related samples are integrated first (i.e, replicates will likely be integrated before conditions), so it's usually not necessary to run integration on already-integrated samples. It's possible we remove raw counts in the integrated object which is why you are seeing errors.
