### ISSUE TITLE
Waterfall effect in HeatMap?

### ISSUE THREAD

**Issue by YushG** [satijalab/seurat#465]
All,

Does anyone else notice a "waterfall" effect in the heatmap upon doing an integrated analysis? If so, can anyone provide a reason why this may be?

Thanks.

![image](https://user-images.githubusercontent.com/13268822/39790468-3582c492-52eb-11e8-89f2-318710961df8.png)

**Comment by JBreunig** [comment]
I frequently see this in my CCA alignments.  I'd be curious to know if there is any way to attenuate the effect.

**Comment by atakanekiz** [comment]
I'm kind of new to these analyses but I might have an idea about this. Could this be due to the thresholds you set up while calculating differentially expressed genes? There are some arguments that allow you to exclude genes that aren't frequently expressed in the clusters. If 5-10% of the cells are not expressing the "differentiating genes", that might cause the waterfall effect.

**Comment by satijalab** [comment]
This is usually do to the fact that cells within a cluster are ordered as in object@cell.names, which reflects the order that the cells were added to the original object. Therefore, the two parts of the waterfall likely reflect cells from the two different experiments you were integrating.

To put this another way, the waterfall is showing genes that differ between cells in two experiments, though integrated into the same cluster. They could correspond, for example, to the interferon response we observe in Figure 2 of our recent NBT paper.
