### ISSUE TITLE
AverageDetectionRate() function in v3 or how to calculate probability of detection for each gene for each identity class 

### ISSUE THREAD

**Issue by goncik** [satijalab/seurat#4695]
Hi, 

I need to run AverageDetectionRate() function on my object (it's a part in a specific script that I'm using) but this function belongs to Seurat version 2 and I can't find which function does this correspond to in the newer versions?  

Description of this function: For each gene, calculates the probability of detection for each identity class

Thanks in advance.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So if you need the function the source code seems to still be all good but a few spots just need to be updated to work for V3+ objects due to name/object organization changes.
Relevant changes here are:
--`object@ident` is now `object@active.ident`
--`object@data` is now `object@assays$RNA@data` (assuming you are using the RNA assay for this quantification, otherwise just change that part of the code.)

```
AverageDetectionRate_V3 <- function(
  object,
  thresh.min = 0
) {
  ident.use <- object@active.ident
  data.all <- data.frame(row.names = rownames(x = object@assays$RNA@data))
  for (i in sort(x = unique(x = ident.use))) {
    temp.cells <- WhichCells(object = object, ident = i)
    data.temp <- apply(
      X = object@assays$RNA@data[, temp.cells],
      MARGIN = 1,
      FUN = function(x) {
        return(sum(x > thresh.min)/length(x = x))
      }
    )
    data.all <- cbind(data.all, data.temp)
    colnames(x = data.all)[ncol(x = data.all)] <- i
  }
  colnames(x = data.all) <- sort(x = unique(x = ident.use))
  return(data.all)
}
```

Best,
Sam

**Comment by goncik** [comment]
Dear Sam, 

I can't explain how useful this was! Thank you very much.

**Comment by samuel-marsh** [comment]
Happy to help!
