### ISSUE TITLE
running FindMarkers on multiple Seurat objects in the same script

### ISSUE THREAD

**Issue by AvolaAmg** [satijalab/seurat#4702]
Hi All, 

I am currently processing 4 scRNA-seq datasets using Seurat and I am quite new to the whole thing. 
I have imported 4 Seurat objects in my workspace and I am trying to identify markers for all of them and save .csv files for the top 5 markers for each cluster in each dataset. 
Usually I analyse the scRNA-seq datasets one by one and the code is as follow : 

```
library(Seurat)
library(dplyr)

SOBJ <- readRDS("filepath/THESEURATOBJECT.RDS")
    this.markers <- FindAllMarkers(SOBJ, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
    this.markers%>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)
save.csv <- (this.markers, "filepath/this.markers.csv")`

#######################
```

Now I wanted to implement this in a for loop for multiple seurat objects, however I get stuck at the this.markers%>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC) and I am not able to save the csv files. 
Any suggestions ? 

the code I was trying was this : 
```

UMAP.OBJECTS <- c(SOBJ1, SOBJ2, SOBJ3, SOBJ4) 
  for(i in UMAP.OBJECTS)
  {
    
    this.markers <- FindAllMarkers(i, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
    this.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)
    print(this.markers)
    write.csv <- (this.markers[i] "this.markers.csv")
  }
  
```
Thank you very much for your help!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So there are couple issues in both sections of the code.
First, not sure if this is intended or not but your code for filtering the output of `FindAllMarkers` is not actually modifying the dataframe result and you are therefore saving the full dataframe.  If you want to be saving the filtered dataframe you should be using this code instead:
```
this.markers.filtered <- this.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)
```

Second is that neither of your save functions appear to be written correctly.  In both cases you are using the assignment operator to create a variable with the same name as the function instead of supplying parameters to the function.  (Also `save.csv` as written in first example doesn't appear to be a function, or at least one I'm familiar with).  The function in the for loop is also missing a comma in between the object and the file path.
What you want to write to save the dataframe to csv is:
```
write.csv(this.markers, "this.markers.csv")
```

You can easily loop this using `lapply` by doing something like the following:
```
lapply(1:length(UMAP.OBJECTS), function(i) {
  this.markers <- FindAllMarkers(UMAP.OBJECTS[[i]], only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
  this.markers.filtered <- this.markers %>% 
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_logFC)
  write.csv(x = this.markers.filtered, file = paste0("Object_", i, "_this.markers.csv"))
})
```

The other issue in your original loop is that even if it correctly looped all of the dataframes were going to overwrite each other because they all had the same file name.  That is the rationale for the iterative file name I put in the file path in `lapply` function above.  I also removed the `print()` function just because it adds a lot of extra text to the console output that might not be very informative when performing this using large number of objects but could easily be added back in is desired.

Best,
Sam

**Comment by torkencz** [comment]
Hi, I couldn't have answered it better myself, thanks @samuel-marsh.

**Comment by AvolaAmg** [comment]
Thank you very much @samuel-marsh :) your suggestion helped a lot !
