### ISSUE TITLE
FindVariableFeatures returns nothing when assay set to SCT

### ISSUE THREAD

**Issue by duocang** [satijalab/seurat#4703]
```r
a <-  SCTransform(a)
HVG <- FindVariableFeatures(a, nfeatures=6000) %>% VariableFeatures()

DefaultAssay(a) <- "RNA"
HVG_RNA <- FindVariableFeatures(ae, nfeatures=6000) %>% VariableFeatures()

HVG_SCT <- FindVariableFeatures(a, nfeatures=6000, assay = "SCT") %>% VariableFeatures()

length(HVG)
# 6000

length(HVG_RNA)
# 6000

length(HVG_SCT)
# character(0)
```

I do not know why `HVG_SCT` is none.

And  which  6000 is better?
![image](https://user-images.githubusercontent.com/14146871/123865477-8a936200-d95e-11eb-9841-05e79cf4243e.png)

**Comment by timoast** [comment]
This is just because of the way you have called the `VariableFeatures()` function. Here the default assay is RNA, and you have not found variable features for RNA, and so no variable features are returned. If you use the SCT assay (`VariableFeatures(., assay = "SCT")` you will find the variable features have indeed been stored.
