### ISSUE TITLE
Azimuth for Integration?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#4704]
Hello,

I just want to clarify how Azimuth can be used for multple scRNA-seq datasets that are supposedly for integration.

So since integrated data cannot be inputted to Azimuth, and only the non-processed counts data (i.e. seurat object) can be used, I was wondering what do you mean by "you can put them together to Azimuth".

The input in Azimuth app only accepts one dataset at a time. May I ask what should be the best way to do this?
(1) Merge the Seurat objects so that we can only have one dataset to load in Azimuth
(2) Load the datasets one by one and then (a) simply merge or (b) perform Seurat integration after?
(3) Any other suggestion please?

Thank you!

**Comment by rsatija** [comment]
We discuss this in the Azimuth FAQ (relevant section below)
Should I map my batches separately or combined?
We have observed that the results (both for visualization and annotation) are very similar when mapping individual batches separately, or combined together. This is because Azimuth can successfully remove batch effects between query and reference cells, even when there are multiple query batches. However, as discussed further below, the results of QC metrics may change. For example, cells from certain batches sometimes receive high mapping scores when the batches are mapped separately but receive low mapping scores when batches are mapped together, as the batch effect represents a source of heterogeneity in the query that is removed by Azimuth.

https://azimuth.hubmapconsortium.org/
