### ISSUE TITLE
Subset cells by protein expression

### ISSUE THREAD

**Issue by FinleyMcFinley** [satijalab/seurat#4729]
Hi everyone,

I would like to subset cells based on the expression of ADT marker CoV2-S1-TotalSeqC. In other words, I would like to subset cells targeting the SARS-CoV-2 spike protein (S1).

If I try the following: 
DefaultAssay(ALL_CELLS) <- "ADT"
COVID_specific <- subset(x = ALL_CELLS, subset =CoV2-S1-TotalSeqC > .01)

I get the error:
Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found: 

I also tried the same with quotes ("CoV2-S1-TotalSeqC") but unfortunately get the same error.

Is there a way to subset my cells according to ADT markers?

Thanks so much,
Erin

**Comment by samuel-marsh** [comment]
Hi Erin,

Not member of dev team but hopefully can be helpful.  The error seems to be related to not finding the variable in the object.  What is the result if you run the following code:
`grep(pattern = "CoV2-S1-TotalSeqC", x = rownames(ALL_CELLS[["ADT"]]), value = TRUE)`

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi Erin,

Hi,

So as long as running the code I suggested above returns value and confirms presence of the protein name in the object then the issue is actually due to the "-" in the name of protein you are trying to subset on.

The solution is to use backticks and the assay key in order to subset (see https://github.com/satijalab/seurat/issues/2463#issuecomment-570100398).  You don't even need to switch the default assay either.

Here is reproducible validation of the solution using SeuratData bmcite dataset.

```
bmcite_obj <- bmcite.SeuratData::bmcite

Assays(bmcite_obj)
[1] "RNA" "ADT"

bmcite_obj_sub <- subset(x = bmcite_obj, subset = CD127-IL7Ra > 1.5)
Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found: 

# Now for the solution:
bmcite_obj_sub <- subset(x = bmcite_obj, subset = `adt_CD127-IL7Ra` > 1.5)
```

Best,
Sam
