### ISSUE TITLE
R Session Aborted When Integrating 3 Samples

### ISSUE THREAD

**Issue by Jokingpoet** [satijalab/seurat#474]
Hi there,

We are trying to integrate three Seurat object datasets and it runs into a R session abort every time with RunMultiCCA function. This problem is confusing because we did a three datasets integration before on the exact same computer and it was fine.

Any suggestions on why this problem happens?

Thanks,
Ashley

**Comment by andrewwbutler** [comment]
Hi Ashley,

It's hard to say what's happening without more details about what is different between the two times you ran the function and what exactly you mean by "abort". Did you update Seurat/R? What are the resources available on the computer/how many cells are you working with? Most importantly, It would be helpful for debugging purposes if you could provide us with a reproducible example.

**Comment by Jokingpoet** [comment]
There are no difference between the two times I integrate. Both integration have the nearly sample amount of cells numbers. When I hit enter to run the command "RunMultiCCA" there's immediately a window popped up with a drawing of a bomb saying "R session aborted", and I can do nothing but restart RStudio. 

P.S. I am using R 3.4.4 and Seurat 2.3.0 if it helps.

**Comment by orrzor** [comment]
Hi Ashley,

I have had a similar issue and I don't know if it started to occur as I went to Seurat 2.3.0 or 2.3.1. Regardless, I got past this by running Seurat on a machine with more memory than my local computer. Hope that helps - Orr

**Comment by Aja23i6** [comment]
Hi,

I also have same problem. When I run "RunMultiCCA", the session is aborted and when I tried with R console, it said "caught segfault address 0x0, cause 'memory not mapped'. I use R 3.4.4 and install latest seurat from github.

**Comment by qrzhang** [comment]
Hey,

I have the same issuse as well. 

When I run "RunMultiCCA" for three samples on a local computer(R 3.4.4), the R session aborted.  I wonder it may have run out the memory. So, I try it again on a super computer (R 3.5.0) with 1T memory. the session is aborted again and shows error message as below.  

> \>#--- Run multi-set CCA
> \>AGG3.integrated <- RunMultiCCA(ob.list, genes.use = genes.use, num.ccs = 30)
>
> *** caught segfault ***
>address (nil), cause 'memory not mapped'
>
>Traceback:
 >1: Standardize(mat.list[[i]], display_progress = F)
 >2: RunMultiCCA(ob.list, genes.use = genes.use, num.ccs = 30)
>An irrecoverable exception occurred. R is aborting now ...`

I used to run "RunMultiCCA" several times last month and it worked well.  So,  I tried to run the same code on same data that worked well before, the session aborted.  How could it used to work well but got error today?

**Comment by evolvedmicrobe** [comment]
An `address(nil)` segfault is quite unusual as there are no obvious memory leaks in the StandardizeFunction, so one would likely have to run a debugger to figure out what was going on there.

It might be possible that you are running out of memory however and that is somehow causing a segfault somewhere in the Eigen/R internals.  Given that some users above commented on memory issues, I made this pull request https://github.com/satijalab/seurat/pull/610 to see if one could work around that issue.  It might be worth installing that version and checking if it solves your problem.

    library(devtools)
    devtools::install_github("evolvedmicrobe/seurat", ref="less_copy_std")

**Comment by Aja23i6** [comment]
Thank you for your suggestion.
I tried but still have problem.
Is this correct to use evolved microbe/seurat?

install.packages("devtools")
library(devtools)
devtools::install_github("satijalab/seurat", ref = "develop")
devtools::install_github("evolvedmicrobe/seurat", ref="less_copy_std")
library(Seurat)

**Comment by evolvedmicrobe** [comment]
That second `devtools::install_github` command would have installed the alternate version of that function, and it looks like you're still running into the issue.  That is unfortunate, but at least rules out an unlikely error (R should exit with an out of memory error or be killed by the kernel rather than simply segfaulting when too much memory is consumed).

One other thing that might be worth checking out is if you have packages of R that were created with different compilers or versions, as mixing versions or build tools can lead to unexpected behavior and segfaults. I would first try following the instructions here to make sure all your packages are built to the same version of R http://shiny.rstudio.com/articles/upgrade-R.html .  

If that doesn't work, to properly debug the issue one would need a reproducible example one could debug or at least a coredump/symbols to go with it.  If fixing the packages as above doesn't work, and completely reinstalling R and it's packages doesn't work, I would then try to create a core dump or reproducible example to send on.

**Comment by Aja23i6** [comment]
Thank you for your suggestion. R3.5.1 was released recently, I installed it and built all the packages under it. But I still have same problem. If you need any information for this problem, please let me know.

**Comment by evolvedmicrobe** [comment]
Can I ask what the size of your dataset is, and if it would be possible to send on the three datasets?  The easiest way I could help debug this would be for me to run it locally unless good HIPAA or other reasons keep the data private.

If the data can't be shared, the next best thing might be to try to run it in a docker image.  This will help avoid issues due to the environment/installation, and if the issue still occurs we can also use it to create a core-dump/stack-trace for more specific debugging.  I am assuming you are on a Mac or Linux, and if so the following instructions will work, but ping back if otherwise or if questions.

1 - [Install Docker Community Edition](https://www.docker.com/community-edition)
2 - Verify Docker is on the `PATH` by typing `docker -h` in the terminal and making sure text appears (stop otherwise).
3 - Load a docker image with Seurat installed and that contains your data as follows:

    docker run --rm -p 8787:8787 -v [PATH-TO-YOUR-DATA]:/home/rstudio/data    evolvedmicrobe/tme_tutorial:0.0.2

Note that you will need to replace [PATH-TO-YOUR-DATA] with the path to a directory containing you docker files e.g. `~/my_data/`.

4 - Go to this url: http://localhost:8787 in your internet browser. If you're prompted for a username and password, simply use rstudio for both. You will now be in a live RStudio session with your data in the directory `/home/rstudio/data`.  Run an example that leads to the error in this instance, and let us know if the problem still occurs.

Docker may be new to you, in which case this [link](https://ropenscilabs.github.io/r-docker-tutorial/) has more information.  SegFaults are unfortunately notoriously evil to debug remotely, so this process is somewhat painful, but hopefully the above will help.

**Comment by qrzhang** [comment]
I have just solved this problem :)

My suggestion:

1.  Run sample [code](https://www.dropbox.com/s/aji4ielg8gc70vj/multiple_pancreas_workflow.R?dl=1) and [data](
https://www.dropbox.com/s/vdtz4kkodpe8kw3/pancreas_multialignment_expression_matrices.zip?dl=1) provided by Satija Lab for integrating four datasets. If it works well, you may have the same problem with me. 

2. Try to use the same code for your own data. You may have to modify the loading data part according to your own datasets. As for me, I have to use `Read10X()` function. 

3. If it works again, there must be something wrong with your own code. Just find out the differences between your own code and the sample code. For me, after adding this line
`data1<- FindVariableGenes(data1, do.plot = F, display.progress = F)`  
for all three datasets, `RunMultiCCA` works well and no more R Session Aborted happens.

Even though this problem has been solved, I still can not understand why my code worked well before without 'FindVariableGenes' but need to add it now.

Hope this will help.

**Comment by Aja23i6** [comment]
Hi Both,

Thank you very much! My problem is same as qrzhang one. I can solve the problem with FindVariableGenes. I had just modified my code from two dataset analysis, which follow here (https://satijalab.org/seurat/immune_alignment.html).  So, I didn't check that sample code.
Thanks a lot!
