### ISSUE TITLE
How to split Seurat stored Rdata file and it still can be used after glued ? 

### ISSUE THREAD

**Issue by DiracZhu1998** [satijalab/seurat#4746]
Dear Seurat developer, 
thanks you for giving us a wonderful tools!
I am uploading our analysis Rdata (contain more than 1w genes and more than 20w cells) into website, but there is a file size limitation hindered me. I am wondering if any way you know the data still work after I split it and glue it. 
Thank you for your help!

**Comment by timoast** [comment]
Not sure what you mean by "split and glue," can you elaborate and provide code?

**Comment by DiracZhu1998** [comment]
Thank u for your reply. I mean I want to split Rdata into pieces (e.g., by linux command split )and upload it to website. Other people can download these pieces and "glue" (e.g., linux command cat) it and the glued Rdata still intact. 
I tried split and cat command but it failed, I' like to know if there is a way/linux command we can do it.

**Comment by samuel-marsh** [comment]
Hi,

Hi, not member of dev team but just thought that, depending on your file size limit and size of your object you could try saving the object as "qs" object using qs package (https://cran.r-project.org/web/packages/qs/index.html).  Often gets better compression (and faster) than other formats.

Otherwise I think given the needs of end user it might be better to host the data on service without such a size limit as it would minimize end user errors.

Best,
Sam

**Comment by timoast** [comment]
I don't think that will work, as far as I know `split` does not work on binary file formats.

If you need to reduce the size of a Seurat object, you can look at the `DietSeurat()` function https://www.rdocumentation.org/packages/Seurat/versions/4.0.3/topics/DietSeurat

You can also change the compression used when saving the object to disk, see https://rstudio-pubs-static.s3.amazonaws.com/73901_681f75d0c2bd4ba6959fdc7e6b8f72e1.html

Or as Sam pointed out, host the data somewhere with a larger file size limit

**Comment by DiracZhu1998** [comment]
OK, thank you for your advice!
