### ISSUE TITLE
max size seurat object

### ISSUE THREAD

**Issue by meliamne** [satijalab/seurat#4752]
Dear Seurat Devs,

Is there any known maximum to the size of a Seurat object?
I am trying to merge a large amount of Seurat objects in a loop. However, after around a million cells (1080887) every merge fails with the following error message. "Error in RowMergeMatricesList(mat_list = all.mat, mat_rownames = all.rownames,  : 
  vector::reserve"

Kind regards

**Comment by GreenGilad** [comment]
Hi @meliamne,
I am having a similar problem and came up with some workaround to merge the count matrices myself. This does  manages to cope with the large number of cells, but still fails due to sequencing depth (leading to a vector with more than 2^32-1 entries). [This workaround](https://github.com/mojaveazure/seurat-object/issues/19) might still help you.

**Comment by timoast** [comment]
Yes, the size of the Seurat object is currently limited to the maximum size of a `dgCMatrix` sparse matrix in R (2^32-1 non-zero entries)
