### ISSUE TITLE
How to integrate biological replicates across different conditions

### ISSUE THREAD

**Issue by BiostormSilver** [satijalab/seurat#4753]
Hi, I have scRNA-seq data from the 10x pipeline with 2 different conditions that each have 3 biological replicates. I want to analyze the data to find differently expressed genes for a certain cell type between the two conditions but I'm not sure how you should approach it. The tutorials such as https://satijalab.org/seurat/articles/integration_introduction.html , mention both replicates and working with two different conditions but I haven't found an answer for how to deal with both at the same time. 

This has been mentioned in a few previous issues such as https://github.com/satijalab/seurat/issues/2059 ,but I have not yet found a definitive answer on what the correct approach is. Specifically whether to integrate all 6 datasets together or to integrate the biological replicates together and then integrate again, and if that is the correct approach then whether you need to re-normalize and find variable features for the two integrated objects.

**Comment by RajneeshSrivastava** [comment]
#similar question
I have 6 cohorts of roughly 300,000 cells (dummy scheme below) for which I did QC filtering and SCT normalization for all together, as mentioned in seurat tutorials. I want to do pairwise comparison (DE analysis) to obtain important list of differentially expressed genes for all combination initially and then the future goal is to do visualization (feature/Vln plot, split by group) of all those genes across all 6 cohorts. Regarding **data integration**, please suggest if:
(i) I should integrate all 6 cohorts and subset a pair each time for downstream analysis
OR
(ii) I should integrate only a pair each time and do DE analysis. And then visualize the genes in integrated object of 6 cohorts

Do I expect any **feature loss** due to multi cohort integration in (i) compared to (ii) approach?

Cohorts    Replicates
GroupA           8
GroupB           3
GroupC          12
GroupD          11
GroupE            9
GroupF            9

Many thanks in advance!
-Rajneesh

**Comment by Dragonmasterx87** [comment]
Just my two cents, I would integrate everything first then perform DE in a control vs Tx manner. You have hundreds of replicates per gene, and the combined effect should be seen when you take all your replicates as one collective metadata entry. Look at #1091

If you want to look at sample/donor-specific comparisons you can use pseudo-bulk, but that would be a shame since you are underpowering a powered study. 

Reference mapping is cool, but I feel that unless we have multi-million cell atlases spanning over 20 individuals it's difficult to biologically reason that the transcriptional signature of a handful of individuals is representative of a 'reference dataset. So these limitations should be kept in mind when performing a reference-based integration (make sure you have multiple samples - cohorts - spanning multiple experiments).

Otherwise, if you want to perform cluster within-cluster analysis check [this](https://hbctraining.github.io/scRNA-seq/lessons/pseudobulk_DESeq2_scrnaseq.html) out. Look at the heading: **Useful scripts for running analyses on many different cell type clusters using Wald test for pairwise comparisons or Likelihood Ratio Test for multi-group comparisons**

Just my 2x cents.

Cheers,

🐉

**Comment by yuhanH** [comment]
HI, 
In our experience, we usually run integration for all samples together, but set the control replicates as reference.  You can follow our reference-based integration vignettes: https://satijalab.org/seurat/articles/integration_large_datasets.html
Setting your control samples as reference mainly means that you integrate your control samples first, and then integrate samples from the treated group. 
In our [seurat v4 paper](https://www.sciencedirect.com/science/article/pii/S0092867421005833),  we divided samples by individual donors and time points.  When we do integration across all donors and time points, we set the samples from time_0 as reference.

**Comment by shaniAmare** [comment]
Hi, I'm kindly wondering whether this approach you suggested is still valid @yuhanH ? Asking because I see a few things have changed when you moved from v3 to 4 to 5 - and also the link you have provided does not exist anymore. But want to try a similar method out for our data.

Many thanks,
Shani.
