### ISSUE TITLE
DoHeatmap(v3.1.5) generates additional cells with expression levels = NA

### ISSUE THREAD

**Issue by atgustin** [satijalab/seurat#4799]
Hi there, I've been pulling the $data from a DoHeatmap object, and the cell column contains more cells than are in the original seurat object.  I attempted to specifically run the command on the cells in my seurat object using "cells=seurat_object@meta.data$cells", but the problem persisted.  

My starting cell number is ~11700, and after running DoHeatmap the number of unique cells jumps to ~12400.  These cells have unique labels (e.g. "dzlfstcgjaepihmvyxnw") but these labels are quite unlike the labels of my true cells.  

The Expression values for these new cells are NA, but they _are_ assigned to different clusters.

Can you help identify where these cells come from?  I'm assuming some sort of artifact of the DoHeatmap code, but I'm not savvy enough to figure it out.

Thanks!

Andrew
UW

**Comment by andrewwbutler** [comment]
Hi Andrew,

Yes, those are an artifact of the `DoHeatmap` code. In order to insert the vertical lines between groups, we insert dummy cells with NAs for expression values. If you really want to work with this data frame rather than pulling from the Seurat object (with `GetAssayData`), you can either just exclude these rows or set the `draw.lines` parameter in `DoHeatmap` to `FALSE` to prevent these `NA`s from being added to `$data` in the ggplot object.
