### ISSUE TITLE
multimodal reference mapping: PCA calculation error and data integration question

### ISSUE THREAD

**Issue by AndyZ395** [satijalab/seurat#4817]
Hi,

I serially mapped immune cell scRNAseq data from 8 tumor patients to the PBMC CITE-seq data reference (SCT transformed), similar to example 2 of the Seurat Vignette for multimodal reference mapping (https://satijalab.org/seurat/articles/multimodal_reference_mapping.html), with the purpose to label cell types. Like in the tutorial, I merged the 8 donors after mapping cell types.

**Question 1:**
For serial multimodal reference mapping, each of the 8 tumor samples get SCT-transformed separately. After multimodal reference mapping, the data is  merged using merge(). Is the result simply the merged SCT-transformed data of each sample, or do the different samples get properly integrated during the multimodal reference workflow? Or should I perform scRNAseq data integration of SCT transformed samples before or after multimodal reference mapping for further analysis?

**Question 2:**
After multimodal reference mapping would like to compute new standard PCA and UMAP reduction:
`data<- RunPCA(data)`
But an error is coming up:
`Error in PrepDR(object = object, features = features, verbose = verbose) : Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.`

To solve this issue, I tried to calculate the most variable features:
`data <- FindVariableFeatures(data, selection.method = "vst", nfeatures = 2000)`
Another error is showing up:
`Error: SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<-`

Can you please advice how to solve this?
I checked data@assays[["SCT"]]@SCTModel.list:
![image](https://user-images.githubusercontent.com/87702329/126389995-2566b3c8-f385-4f0b-b1c4-f3b99a947c3a.png)

It seems like there is a separate SCT model for each donor, but as far as I can tell, there is no SCT model for the merged data set? How can I make this work to perform a normal PCA with the merged, SCT transformed data?

**Comment by yuhanH** [comment]
Hi, 
Question1: the result is simply the merged SCT-transformed data of each sample. That's why you see many SCT models in your merged objects.  If you use the `ref.umap` obtained in the mapping process, you don't need to do any integration. But if you want to identify some novel cell types in the dataset, you need to run integration again. 

Question2: After you merge the objects, the variable features are not set in the merged object. 
You can get the variable features from your object.list by the following command:
`VariableFeatures(object.inte) <- SelectIntegrationFeatures(object.list =object.list, nfeatures = 3000)`

`FindVariableFeatures(data, selection.method = "vst", nfeatures = 2000)` is used for the log-normalized data.
