### ISSUE TITLE
Comparing scRNA analysis with different mt-cutoffs

### ISSUE THREAD

**Issue by SleepySomething** [satijalab/seurat#4887]
Hello everybody, newby here.

In this semester I chose to learn some bioinformatics and came across single cell RNA sequencing, RStudio and the package Seurat. I am currently working on a project and one question popped into my mind, which I could not find an answer. 

Can I somehow (qualitative-ly) compare 2 scRNA-seq analyses, where the only difference is the mitochondrial read cutoff,
 and if yes, what would be the criterias?
I have done the steps as described in the vignettes [Guided turotial](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html) and [SCTransform](https://satijalab.org/seurat/articles/sctransform_vignette.html).
When it came to the  code `pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)`, I entered one time 30 and the other time 20 after percent.mt for my analyses.

I get UMAPs - where the general structure is similar-, some different marker genes for a few clusters and the annotation was more or less difficult. I do not know how to see, if the 20% or the 30% cutoff was better and why. 

Thanks in advance.

**Comment by saketkc** [comment]
A higher mitochondrial content is reflective of cells dying cells, but could also sometimes be reflective of the biology (for example tumors might have higher mitochondrial content due to the perturbed metabolic pathway) .The exact cutoffs are dependent on your dataset, but a general rule of thumb is to exclude outlier cells with mitochondrial content that is not representative of the sampled population (extreme high your percent.mt violin plot for example).
