### ISSUE TITLE
Use of hires image instead of lowres in SpatialDimPlot

### ISSUE THREAD

**Issue by Lisa-Salhi** [satijalab/seurat#4894]
### Discussed in https://github.com/satijalab/seurat/discussions/4833

<div type='discussions-op-text'>

<sup>Originally posted by **Lisa-Salhi** July 23, 2021</sup>
Hello,

How can I overlap ​the spots on the hires (high resolution) image instead of the lowres one?
When I do `SpatialDimPlot(allsamples.merged, label.size = 3, alpha = 0.1, group.by = "seurat_clusters", images = "slice1")`, the image shown is the lowres one.

The Seurat version I use is 4.0.1

Best,
Lisa</div>

**Comment by andrewwbutler** [comment]
Hi, 

You will need to read in the high resolution image initially instead of the lowres one. This can be done now if you install the `develop` branch (instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)). You would need to specify it to `Read10X_Image()` via the `image.name` parameter.
