### ISSUE TITLE
Very small % of variance explained with PCA

### ISSUE THREAD

**Issue by jyoh1248** [satijalab/seurat#4920]
Hello. I am a statistician recently working as a bioinfomatician dealing with pbmc data and with the dimension of 4200*3000. After running PCA, the proportion of variance explained is 21% with 50 PCs and 18% for 30 PCs. Increasing the PCs to 100 returns 26% and 200 PCs give 36%. It does not seem high enough to me at all. Is this acceptable values in the field? 

As we're running clutsering by using these PCs, could we still say that the result is valid even though the PCs does not represent the data well?

I think it is due to nonlinearity of the genes and as PCA uses linear method. Maybe it would be better to use other dimension reduction method? 

Thank you in advance for your help and opinions!

**Comment by liuxl18-hku** [comment]
Also interested in this topic.

To my understanding, scRNA-seq data is sparse and noisy. It is common that there is higher portion of un-structured technical variation in the system, that's why top PCs captured lower variance comparing to more homogenous data, like bulk RNA-seq data.

Directly applying PCA to count matrix or log-transformed count matrix, e.g., log(count + 1) of __all expressed genes__ is not recommended:

1. Skewed expression distribution of scRNA-seq data with a zeros or drop-outs spike breaks the symmetry assumption of PCA.
2. Variance of genes in scRNA-seq data relates to their abundance, highly expressed genes tend to have higher variance, which will be overweighted in PCA.

Therefore, a feature selection step for highly variable genes is required before PCA. HIghly variable genes tend to capture major variability of the system (e.g, difference of major cell types) and exclude the majority variability (e.g., sub-populations difference and technical noisy). For example, like [what Seurat did](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html).

Other RD approaches, like using more general factorization analysis method with underlying statistical structure modified to accommodate scRNA-seq unique expression distribution is also possible. For more details, you can refer to [Kharchenko recent review paper](https://doi.org/10.1038/s41592-021-01171-x) and [a paper discussing statistical structure of scRNA-seq from Satija lab](https://doi.org/10.1101/2021.07.07.451498).

bless~

**Comment by jyoh1248** [comment]
Thank you for your kind answer and clear explanation. 

I misunderstood the dimension. The data after filtering has 14300 genes with 4200 cells. (14300*4200). It is normalised by using sctransform function. PCA is applied in this normalised data while I realize that Seurat PCA uses 3000 selected features to build PCs as a default. As far as I understand, Seurat is automatically doing its feature selection with higly expressed 3000 genes. 20% of proportion of variance explained with 50 PCs is already based on selected features. It seems way too low to me.

I will check other RD approches and read papers thank you so much.

**Comment by liuxl18-hku** [comment]
Welcome. Yes, people also like other DR methods, like NMF.

Actually, was wondering whether 4200 PBMCs need 3000 HVGs (highly variable genes) and 50 PCs. And what variance were included in the 20%, are they all biologically relevant, means contribute to what you are interested in the system. Different number of HVGs (e.g., 1k - 3k) with more parsimonious reduced dimensions (`ElbowPlot()` may help) may change the percent of variance captured.

You may find (this paper)[https://doi.org/10.1186/s13059-019-1898-6] useful if you want try other DR methods.

bless~

**Comment by rsatija** [comment]
Thanks for this question. The answers in this thread give a good overview of responses. The reason that only a small proportion of noise is explained by PCA (or any dimensional reduction technique) is the extensive technical noise that is present in scRNA-seq data that - by definition - does not exhibit correlation structure and therefore cannot be explained in a low-dimensional space. There is also (especially in deeply sequenced datasets) observable biological 'noise' that does not correlate with cell type identity (see for example the discussion in https://www.biorxiv.org/content/10.1101/2021.07.07.451498v1

**Comment by davisidarta** [comment]
Hi @jyoh1248. In fact, you're absolutely correct, but the field lacks rigor.

> After running PCA, the proportion of variance explained is 21% with 50 PCs and 18% for 30 PCs. Increasing the PCs to 100 returns 26% and 200 PCs give 36%. It does not seem high enough to me at all.
Indeed, you're right. Most single-cell data have very low explained variance even using hundreds of PCs, and the features are not linearly correlated. 

> Is this acceptable values in the field?
If by 'acceptable' you mean 'correct', then no. If you mean 'purposefully ignored', then yes.

> As we're running clutsering by using these PCs, could we still say that the result is valid even though the PCs does not represent the data well?
No. Hence the will to ignore it. Most analyses to this day were performed using PCA for constructing neighborhood graphs and clustering, and accepting it is wrong would mean the field would have to correct it. I'm sure you can imagine how willing people are to retract dozens of papers.

> I think it is due to nonlinearity of the genes and as PCA uses linear method. Maybe it would be better to use other dimension reduction method?
Again, yes, and yes. Sadly, in single-cell analysis, the obvious is willfully ignored. Even when using non-linear methods, folks will use PCA preprocessing to avoid higher computational costs. The only exception I know of is scvis.

Came across this while searching for examples of material for a paper I'm writing precisely on this topic. Nice to know at least somebody else allowed the thought of doubt to cross their minds upon evidence, it's an attribute that seems to be increasingly rare these days.
