### ISSUE TITLE
Error generated while generating RMarkdown html report

### ISSUE THREAD

**Issue by hchetia** [satijalab/seurat#4935]
Hi,
I am using  the Seurat tutorial using PBMC data. 

The R script runs fine from console.

But when I try converting it to an Rmarkdown report, I get the foll. error-
![image](https://user-images.githubusercontent.com/64626735/129396627-f1637cea-f6b7-4416-a78b-7d12008ca531.png)

I believe that the error is caused by this chunk of code-
`scaled.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC)`

 I tried using `cluster` and {{cluster}}  but Rmarkdown generated the same error.

Then I tried using `group_by(!!enquo(cluster))` provided by Tidyverse which led to different error.
![image](https://user-images.githubusercontent.com/64626735/129392381-6de827c5-d30a-4f38-8efc-e45643cf7156.png)

Seurat is not able to read cluster when using enquo.
How shall I modify my code so that both Seurat and Rmarkdown can process it seamlessly?

Best,
Hasna

**Comment by timoast** [comment]
It looks like the dataframe that you're using might not have a column called "cluster".

Since this issue does not involve any Seurat functions (`group_by()`, etc are part of the dplyr package), I will close this and suggest that you check the dataframe contains the columns you expect, or you could seek help in a more generic forum like stackoverflow.
