### ISSUE TITLE
FeaturePlot split.by gives different background color

### ISSUE THREAD

**Issue by YingzhengXu** [satijalab/seurat#4956]
Hi,

Thank you for developing this great tool! I notice FeaturePlot gives me 2 different background colors when I use split.by. Looks like the red color is bleaching into all of the cells, and it's very distracting. Is there a way to unify the background color between conditions(CTRL & STRESS in my case)?

[
<img width="1359" alt="Screen Shot 2021-08-18 at 16 26 40" src="https://user-images.githubusercontent.com/78630660/129974790-5b4a9a31-a57f-48e5-b679-a3fe444ffeaf.png">
](url)

**Comment by mhkowalski** [comment]
Could you please provide the code you used to generate this plot? Also, if you subset just the CTRL condition into a separate Seurat object and run FeaturePlot, does it look the same?

**Comment by YingzhengXu** [comment]
> Could you please provide the code you used to generate this plot? Also, if you subset just the CTRL condition into a separate Seurat object and run FeaturePlot, does it look the same?

I changed the defaultassay to "RNA" and the pink color is no longer there. My guess is the "baseline" expression is changed through integration(normalization etc.)? 
Also, is there a way to reserve the color scale bar when split.by is used? I guess some gig-lots function can make it happen?

<img width="1359" alt="Screen Shot 2021-08-20 at 14 04 28" src="https://user-images.githubusercontent.com/78630660/130281799-ea93ffe2-54fa-4289-9a17-6030a2a8ede1.png">

**Comment by samuel-marsh** [comment]
Hi,

Yes you can simply use ggplot2 theming to return the scale bar.  Assuming you leave the `keep.scale` parameter on it's default then you can just get a single scale bar using:
`FeaturePlot(object = obj_name, features = "Gene", split.by = "Factor") + theme(legend.position = "right")`

If you change it such that it scales each split individually then you'll want to make sure to use patchwork `&` instead of ggplot2 `+` so that each plot has it's own scale bar otherwise it will confuse interpretation:
`FeaturePlot(object = obj_name, features = "Gene", split.by = "Factor", keep.scale = NULL) & theme(legend.position = "right")`

Best,
Sam

**Comment by mhkowalski** [comment]
I agree with the above except with the slight modification that you want to use `keep.scale = "feature" ` in order to scale each plot individually rather than `keep.scale = NULL`. Thanks for your question.
