### ISSUE TITLE
Directory Not Found

### ISSUE THREAD

**Issue by scalderon190909** [satijalab/seurat#4990]
Hi,

I installed Seurat along with the associated packages from following the tutorial. However, whenever I get to the step of inputting the data, I get an error.

> pbmc.data <- Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/")
Error in Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/") : 
  Directory provided does not exist 

If I try to put in the file directory directly I also get a similar error:

> pbmc.data <- Read10X(data.dir = "Macintosh HD/Users/calderons3/Desktop/filtered_gene_bc_matrices/hg19/")
Error in Read10X(data.dir = "Macintosh HD/Users/calderons3/Desktop/filtered_gene_bc_matrices/hg19/") : 
  Directory provided does not exist

Any help would be greatly appreciated!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So I think there are probably two issues with the path you are writing.  First is that you need initial slash in the path otherwise it is looking within the current working directory where it will not find the full path.  Second is that the full path for most Macs will not include the Mactinosh HD (and if it does spaces need to be treated differently when supplying file paths like this).

I would guess the path you need to supply is: 
```
pbmc.data <- Read10X(data.dir = "/Users/calderons3/Desktop/filtered_gene_bc_matrices/hg19/")
```

Finally, if you are working within RStudio you can also use tab completion once you are inside the quotation marks to create file paths which will help ensure they are valid when supplying them to a function.

Best,
Sam

**Comment by scalderon190909** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. So I think there are probably two issues with the path you are writing. First is that you need initial slash in the path otherwise it is looking within the current working directory where it will not find the full path. Second is that the full path for most Macs will not include the Mactinosh HD (and if it does spaces need to be treated differently when supplying file paths like this).
> 
> I would guess the path you need to supply is:
> 
> ```
> pbmc.data <- Read10X(data.dir = "/Users/calderons3/Desktop/filtered_gene_bc_matrices/hg19/")
> ```
> 
> Finally, if you are working within RStudio you can also use tab completion once you are inside the quotation marks to create file paths which will help ensure they are valid when supplying them to a function.
> 
> Best,
> Sam

I tried your methods, but its still giving me the same error :(. Also, when I try to use tab completion it says "(No Matches)".

**Comment by samuel-marsh** [comment]
When you type:

`"/"`

and then try tab completing what happens?

**Comment by scalderon190909** [comment]
> When you type:
> 
> `"/"`
> 
> and then try tab completing what happens?

Figured it out and it worked! Thank you so much !!

**Comment by prachi-sao** [comment]
please tell how did you solve it. i am facing the same issue
