### ISSUE TITLE
error running jackStraw

### ISSUE THREAD

**Issue by roryk** [satijalab/seurat#5]
Hi,

I have an issue running the `jackStraw` method:

```
> seurat.data = jackStraw(seurat.data, num.replicate=200, do.print=FALSE)
Error in matrix(x2[ind], nrow = nrow(x), ncol = ncol(x), byrow = TRUE) : 
  non-numeric matrix extent
```

I saved the `seurat.data` object and stuck it up here: https://dl.dropboxusercontent.com/u/2822886/seurat-error.RData

Any ideas about why this is failing? It has worked on other datasets, I'm not sure what is different about this one.

**Comment by Puriney** [comment]
Could you please share these 3 components from your huge Rdata? 

```r
pca.x <- seurat.error@pca.x
save(pca.x, file = <path>)
pca.rot <- seurat.error@pca.rot
save(pca.rot, file = <path>)
sca.dt <- seurat.error@scale.data
save(sca.dt, file = <path>)
```

**Comment by roryk** [comment]
Hi Yun,

Thanks for responding. Here is an RData object with just those three objects saved. It is still large (170 MB). https://dl.dropboxusercontent.com/u/2822886/seurat-small.RData

**Comment by Puriney** [comment]
Thanks for sharing the file. 

**Solution**
If `prop.freq = 0.016` (or any other number greater than 0.015), your call runs. 

**Why error**
The error is because you have not set the `prop.freq` parameter.It is used to determine the number of permuted 'synthetic' null original variables denoted as `s` in original jackstraw paper. In Seurat implementation, s = (number of variable genes) * `prop.freq`.  

**Going deep**
Your specific data yields extreme case for Seurat which is helpful for the package grow-up. Thanks again for reporting issue. 

By default, `prop.freq` will be 0.01. If your data has less than 200 variable genes, the `prop.freq` will be forced to be up a little bit, to 0.015, so that helps user has enough tests to get robust results. Your data is the latter case which has 131 variable genes, therefore 131 * 0.015 = 1.965 ~ 1 gene is ready to be permuted. In this extreme case the accuracy of p-value is going to be maximized while the algorithm is least efficient, referring to original jackstraw paper. Currently public Seurat implementation does not allow this happen but without warning, thus the error happens. 

---

Hope it helps. Excuse me for replying late as I was busy making :snowman: these days.

**Comment by fanli-gcb** [comment]
Does anyone also get this error running jackStrawPlot?
```
> jackStrawPlot(srt, PCs = 1:12)
Error: Unknown parameters: dist
```

Seems my error comes from line 2706 of seurat.R:
`stat_qq(dist=qunif)` should be `stat_qq(distribution=qunif)`

**Comment by mukundvarma** [comment]
I get this error as well. I believe this is because the latest version of ggplot2 does not allow for the dist parameter. If you want a quick fix, rolling back to ggplot 2.0.0 fixes this, but it would be nice to update the seurat code as well.

**Comment by roryk** [comment]
Opened up a pull request for the fix.

**Comment by roryk** [comment]
```
library(devtools)
install_github("roryk/seurat")
```

will install the fixed version so you don't have to roll back ggplot.
