### ISSUE TITLE
Select variable Features in dgCMatrix /Cholmod error 'problem too large' at file

### ISSUE THREAD

**Issue by eroesti** [satijalab/seurat#5027]
Hi, I have a question regarding the creation of a Seurat object.

I am creating a Seurat object from a very large sparse matrix of a SingleCellExperiment with the following code:

`pbmc <- CreateSeuratObject(counts = as.matrix(assay(sce,"counts")), meta.data = as.data.frame(colData(sce)))`

Using a small subset of the dataset works fine, however when using the entire data set, the following error appear:

`Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102`

This should be due to the function `counts(sce) <- as.matrix(counts(sce)`, as the same error appears.

Is there any function in Seurat that help to clean the sparse matrix removing the uninformative genes while creating the Seurat object? Or a separate function?

Thank you in advance,
Elisa

**Comment by saketkc** [comment]
The problem likely occurs because you are creating a dense matrix by doing `as.matrix(assay(sce,"counts")`. You would want to do: `as(object=counts(sce), Class="dgCMatrix")`. You could also simply pass in `counts(sce`). For gene filtering, you could use `min.cells` parameter. Most downstream analysis relies on using only the most variable genes (which are determined post normalization [log/SCTransform])
