### ISSUE TITLE
Striking the right balance between tSNE dims.use and resolution

### ISSUE THREAD

**Issue by atakanekiz** [satijalab/seurat#504]
Hello,

Thanks for this amazing software!

I realize the answer to this question may be experiment-specific but I think it is a valid question across various types of experiments. In general, I'm analyzing my data by using different parameters to see how clusters change.  My experimental setup involves 4 separate samples aggregated with `multiCCA`.

For tSNE clustering, I tried values of `20` and `50` for `dims.use` parameter at `resolution=0.5` . Not suprisingly, I got  different numbers of clusters (13 clusters for `20`, 18 clusters for `50`). 

Then I tried keeping the `dims.use` parameter constant at `20`, and compared `resolution = 0.5` and `resolution = 1.0`. Again, not surprisingly, I ended up having different clustering morphology and number of clusters (13 clusters for `0.5`, 19 clusters for `1.0`). 

My question is about determining the right balance between `dims.use` and `resolution` parameters to define clusters. I appreciate if you have any thoughts on this.

**Comment by mukundvarma** [comment]
The clustering is not based on the tSNE dimensionality reduction. [Hyperparameter optimization](https://en.wikipedia.org/wiki/Hyperparameter_optimization) is almost a field of its own and there's no single right answer to your question. But you could identify some sort of a validation or accuracy metric that you want to optimize, and choose the set of parameters that does that best. In the seurat package, the AssessSplit/ValidateClusters methods are two you can use to see how well your clusters hold up for different configurations of the hyperparameters you use

**Comment by atakanekiz** [comment]
Thanks for your answer. Is there a good vignette out there for AssessSplit/ValidateClusters to help me understand how I can use in my case?

Also, are there any special considerations using these functions with aggregated data (two time-points, two genotypes)?

**Comment by mukundvarma** [comment]
Maybe the seurat devs can chip in with whether or not a good vignette already exists? I'd be happy to write one using the pbmc dataset if it doesn't. 

You can see a description of these functions by looking at `?AssessSplit`.

The way I use them is to set my resolution parameter to be really high (say 2.2 or 2.3), and decide on an accuracy cut off before I start the analysis (let's say 80%). Then, after I have the clustering results, and I've built the cluster tree using `BuildClusterTree`, I assess the split at each of the terminal nodes. If the classifier used in AssessSplit is able to perform at an accuracy >=80%, I consider the clusters to be real. If not, then I merge the clusters using `SetIdent`. You can use your own classifiers that use other algorithms (SVM/logistic regression/XGB) instead of the Random Forests that AssessSplit uses by default.

This is just one workflow, and I'm sure there are multiple other ways to do it. I don't think having aggregated data changes anything at this stage, although you might want to look at the CCA vignette and other methods like contrastive PCA etc. to see how you could better integrate diverse datasets.

**Comment by satijalab** [comment]
We don't have a specific vignette for this. Assessing whether cluster splits are biologically valid should also involve examination of the gene expression markers driving the split.
