### ISSUE TITLE
Why are the variable features removed from the RNA assay after integration?

### ISSUE THREAD

**Issue by aminerva** [satijalab/seurat#5061]
Hi,

I am running some analysis in which I integrate two datasets (control and stress). I followed the [instructions for integration ](https://satijalab.org/seurat/articles/integration_introduction.html) on the website and used 2000 features for the FindVariableFeatures function. Integration seems to have worked, but I'm wondering why 2000 features are now no longer in the RNA assay but they are in the total integrated object. It does not seem to be the same 2000 features that are in the integrated assay. 

These are the metrics of my two datasets pre-integration:
```
An object of class Seurat 
23639 features across 4195 samples within 1 assay 
Active assay: RNA (23639 features, 0 variable features)
An object of class Seurat 
22834 features across 3108 samples within 1 assay 
Active assay: RNA (22834 features, 0 variable features)
```

This is post integration:

```
An object of class Seurat 
26502 features across 6133 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
```

This is the integrated assay:

```
Assay data with 2000 features for 6133 cells
Top 10 variable features:
 Sst, Vip, Il1rapl2, Adarb2, Ly6c1, Gm32647, Flt1, Npy, AC121788.1, Vtn 
```

And this is RNA assay:

```
Assay data with 24502 features for 6133 cells
First 10 features:
 Xkr4, Gm1992, Gm37381, Rp1, Sox17, Mrpl15, Lypla1, Gm37988, Tcea1,
Rgs20 
```

Thanks for your help!

**Comment by timoast** [comment]
When you merge assays the variable feature information is removed, since the set of cells changes. Those genes are still present in the RNA assay, it's just the list of variable features for the assay that is removed. If you want to set the variable features for the RNA assay to those used for integration, you can do that using the `VariableFeatures(object) <- <features>` assignment function. Note that the main use for variable features is in selecting features to be used for PCA, which is typically run on the integrated assay following integration.
