### ISSUE TITLE
mixscape for treated sc data

### ISSUE THREAD

**Issue by maxybck** [satijalab/seurat#5100]
Hello, 

I was interested in using your newer mixscape analysis to compare a set of sc data of treated-with-drug vs control cells. Your vignette is focussed on a CRISPR knockdown experiment, so I just want to confirm that mixscape could potentially work to distinguish those cells that the drug is having an effect on in my experiment. I am primarily concerned that the drug may be having a small(ish) effect that might be too subtle and that mixscape will be unable to distinguish those cells affected by the the drug (or get confused). Given those concerns do you have suggestions for how best to use mixscape in this instance or parameters that I should pay attention to in the processing? What kind of output would tell you it is struggling to distinguish the differences? Thank you for your time!

**Comment by rsatija** [comment]
Mixscape is designed for cases where you expect to observe a heterogeneous response to a perturbation, and wish to remove cells where a response is not detected. You can certainly run the method on your dataset, but should some care in interpreting the results. For genetic screens, cells may be non-perturbed due to an in-frame mutation or a nonfunctional gRNA. In this case, a nonresponding cell may not be a technical artifact, but as you say - reflect a drug which only induces a detectable response in some fraction of cells. I don't think it affects how you run the method, but it should affect your conclusions and interpretations.
