### ISSUE TITLE
tutorial section on loading the pbmc data "Read10X(data.dir = .... " doesn't work

### ISSUE THREAD

**Issue by cebriggs7135** [satijalab/seurat#5130]
From: https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

The tutorial starts with this:

"Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/") "

but
I had to download the raw data separately and put it in the working directory. It's not in the seurat package, as I think it used to be.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  You need to replace the file path from the tutorial with the file path to the tutorial data on your system.

Best,
Sam

**Comment by cebriggs7135** [comment]
@samuel-marsh Yes, I figured all that out but I don't think that wasn't necessary the last time I installed Seurat. One could copy & paste the commands from the tutorial.  Just aheads up in case it warrants attention.
Thanks for your quick response

**Comment by samuel-marsh** [comment]
Hi @cebriggs7135 
I don’t think that’s possible with this particular command due to how R package installations work and how `Read10X` function works, but glad you figured it out!

Also as fyi data doesn’t necessarily need to be in working directory but when it’s not you need to provide full path instead of relative path to data files.

best,
Sam

**Comment by mojaveazure** [comment]
Hi Chris,

We do not include, and have not ever included, the PBMC 3k dataset in Seurat. If it's worked for you in the past, it would have been because you happened to have the dataset downloaded and in the same path as the one listed in our vignette. We do have a link in the vignette to the website where you can download the raw data, but we can probably do better in communicating that the user must download the dataset and adjust the path to the dataset for their system.
