### ISSUE TITLE
Mixscape classification looks wrong in identifying NP population

### ISSUE THREAD

**Issue by RuiyuRayWang** [satijalab/seurat#5134]
Hi, Seurat team

I'm trying to analyze a Perturb-seq dataset following the mixscape vignette.

I encountered two issues:
1. After `RunMixscape()`, R console show several messages "WARNING! NOT CONVERGENT! ". I know this warning message shows up when `normalmixEM()` failed at finding optimal parameters. But what I'm curious is that when I do the plots, a large amount of cells were predicted as NP (see plots below).
![Rplot1](https://user-images.githubusercontent.com/12589928/134897232-e3c72e24-2cc9-4649-aa33-8df410d85b45.png)
![Rplot2](https://user-images.githubusercontent.com/12589928/134897380-201465d3-2197-4d95-b702-857151b383a1.png)
My first question: is this normal?

2. To check that mixscape is assigning the correct perturbation status to cells, I used `PlotPerturbScore()` function as suggested by the mixscape vignette to visualize the results from `RunMixscape()`.
It seems this visualization does not work for genes with 0 KO. i.e. for Adnp, 
`PlotPerturbScore(cells,
                  target.gene.ident = "Adnp",
                  mixscape.class = "mixscape_class",
                  col = "coral2") + labs(fill = "mixscape class")`
returned
`Error in do.call(rbind, prtb_score_list) : second argument must be a list`

Additionally, when I visualize one of the genes that do have KOs, i.e. Cul3
`PlotPerturbScore(mg,
                 target.gene.ident = "Cul3",
                 mixscape.class = "mixscape_class",
                 col = "coral2") + labs(fill = "mixscape class")`
![image](https://user-images.githubusercontent.com/12589928/134898408-4aed82d9-be06-4215-b253-81507e0a0d5b.png)
It seems that a small percentage of cells on the right tail of the population were also assigned as NP. Why this behavior? Is there a way to adjust the parameters so that I could get better results?

Thanks!
Ray

**Comment by epapalexi** [comment]
Hi Ray,

Regarding your first question:  I happen to be familiar with this particular dataset you are trying to analyze. May I ask if you are taking into consideration that there are different cell types in the dataset before running mixscape? If not I would suggest running mixscape and specifying `split.by = "cell.type"` where cell.type is a metadata column with your cell type classifications. This helps a lot in cases where a perturbation has a cell-type specific effect that can be missed if you run mixscape pooling all cell types together. In the past, when I analyzed this dataset using `split.by` I was able to get a much higher % of perturbed cells. 
Regarding the error on `PlotPerturbScore`: we do not calculate a perturbation score if mixscape finds that there are no differentially expressed genes between a target gene class and NTs. This is because the score is calculated based on the differentially expressed genes. That's why it throws an error. I will modify the code a bit so that in the feature instead of an error users get a message explaining this to them to avoid confusion. 
Finally, about the Cul3 NP cells that fall into the KO cell distribution, I am not sure why this happens. If you can share your code with me I can take a look and figure out what it going on.

I hope this helps. 

Best,
Efi

**Comment by RuiyuRayWang** [comment]
Hi Efi, Thanks for your response!

Yes, I'm aware that there are different cell types in the dataset, but since I'm only interested in one particular cell type (microglia), I extracted them into a single object and ran mixscape on the subsetted cells. This gave me the low perturbed cell counts above.

Regarding `PlotPerturbScore`, here's the code to reproduce the mixscape vignette:
`
# Data, metadata and tSNE coordinates are downloaded from broad institute single cell portal
cells <- CreateSeuratObject(counts = data, project = "JIN", names.field = 2, names.delim = "_", meta.data = meta)
cells[["tsne"]] <- CreateDimReducObject(embeddings = as.matrix(tsne_coord), key = "TSNE_", assay = "RNA")

# Subset high quality microglia and calculate Cell Cycle Score
mg <- subset(cells, subset = CellType == "Microglia" & isKey == TRUE)  # isKey: high-quality cells
s.genes <- stringr::str_to_title(tolower(cc.genes$s.genes))
g2m.genes <- stringr::str_to_title(tolower(cc.genes$g2m.genes))
mg <- CellCycleScoring(mg, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

# Reassign perturbation status: Perturbed vs NT
Idents(mg) <- "Perturbation"
mg <- SetIdent(mg, cells = Cells(mg)[!is.na(Idents(mg))], value = "Perturbed")
mg <- SetIdent(mg, cells = Cells(mg)[is.na(Idents(mg))], value = "NT")
mg[["crispr"]] <- Idents(mg)

Idents(mg) <- "Perturbation"
mg <- SetIdent(mg, cells = Cells(mg)[is.na(Idents(mg))], value = "NT")
mg <- SetIdent(mg, cells = WhichCells(mg, expression = Perturbation == "GFP"), value = "NT")
mg[["gene"]] <- Idents(mg)

# Calculating local perturbation signatures to mitigate confounding effects
mg <- CalcPerturbSig(object = mg, 
                     assay = "RNA", 
                     slot = "data", 
                     gd.class ="gene", 
                     nt.cell.class = "NT", 
                     reduction = "pca", 
                     ndims = 40, 
                     num.neighbors = 20, 
                     split.by = "Batch",
                     new.assay.name = "PRTB")

# Identifying perturbations with no detectable effect
mg <- RunMixscape(object = mg, 
                  assay = "PRTB", 
                  slot = "scale.data", 
                  labels = "gene", 
                  nt.class.name = "NT", 
                  min.de.genes = 5, 
                  iter.num = 20, 
                  de.assay = "RNA", 
                  verbose = F,
                  prtb.type = "KO")

# Plotting Cul3 mixscape class identified by normalmixEM
PlotPerturbScore(mg,
                 target.gene.ident = "Cul3",
                 mixscape.class = "mixscape_class",
                 col = "coral2") + labs(fill = "mixscape class")
`

Best,
Ray

**Comment by kaanokay** [comment]
Hi @epapalexi,

I have an issue with PlotPerturbScore function. I got this error: "Error in "[.data.frame`(prtb_score, , target.gene.class) : undefined columns selected" when I run PlotPerturbScore function with my CRISPR seurat object. Almost everything in my Seurat object is the same with yours (i.e., eccite Seurat object in Mixscape pipeline). Only difference is that my Seurat object have mouse gene names. I'm attaching my Seurat data with rds format (https://drive.google.com/drive/folders/1DJhqlk5hxLffDhGtZ9Gu3XIiGfTowvbN).

Could you help me with this?
Bw.

**Comment by kaanokay** [comment]
Hi Efi,

I ran `RunMixscape` function to obtain perturbation scores with following manner. 

`Mixscape_seurat <- RunMixscape(
  object = Mixscape_seurat, 
  assay = "PRTB", 
  slot = "scale.data", 
  labels = "gene", 
  nt.class.name = "NT", 
  min.de.genes = 5, 
  iter.num = 10, 
  de.assay = "RNA", 
  verbose = F,
  prtb.type = "KO",
  split.by = "replicate")`

I used split.by because I have two replicates. If I do not use split.by parameter for my replicates, I'm getting a warning :"WARNING! NOT CONVERGENT!".

and then I ran `PlotPerturbScore` function but I got an error: "Error: Must request at least one colour from a hue palette". This error is different than previous one but I did not understand why I'm getting this error.

Code was like:

`PlotPerturbScore(object = Mixscape_seurat, 
                 target.gene.ident = "Gata3", 
                 mixscape.class = "mixscape_class", 
                 col = "coral2") + labs(fill = "mixscape class")`

I updated my Seurat object in the same link. I used this Seurat object in `PlotPerturbScore` function.

Thank you for quick reply and developing such good tool for Perturb-seq.

Bw.

**Comment by epapalexi** [comment]
Hi Kaan,

I was able to figure out what was giving you the above error. I have merged a fix in the develop branch of Seurat. Here are instructions on how to use the new version to be able to plot the perturbation score:

install.packages('remotes')
remotes::install_github(repo = 'satijalab/seurat', ref = 'develop')
library(Seurat)

Once you do this, you should be able to use `PlotPerturbScore`.
Efi

**Comment by kaanokay** [comment]
Hi Efi,

Thank you so much for your help! I'll try it.

~Kaan

**Comment by littleju777** [comment]
> Hi Kaan,
> 
> I was able to figure out what was giving you the above error. I have merged a fix in the develop branch of Seurat. Here are instructions on how to use the new version to be able to plot the perturbation score:
> 
> install.packages('remotes') remotes::install_github(repo = 'satijalab/seurat', ref = 'develop') library(Seurat)
> 
> Once you do this, you should be able to use `PlotPerturbScore`. Efi

Hi @epapalexi ,

I got the same error in plotperturbsocre, Error in do.call(rbind, prtb_score_list) : second argument must be a list. 

I try your solution, but it doesn't work. Could you help me with that?
