### ISSUE TITLE
Question about reduction methods

### ISSUE THREAD

**Issue by HelloWorldLTY** [satijalab/seurat#5178]
reduction = c("cca", "rpca", "rlsi"),

I wonder will the results be significantly different among these three reduction parameters. In some datasets, cca will generate a too large matrix to run. But if I use rpca, then the memory usage is very low.

**Comment by mhkowalski** [comment]
As explained here (https://satijalab.org/seurat/articles/integration_rpca.html), reciprocal PCA is more conservative and is less likely to align cell across datasets, whereas CCA can lead to overcorrection if you have cell types that are present in one dataset but not the others. Because reciprocal PCA is faster and requires less memory, it is recommended if you have many cells.
