### ISSUE TITLE
Minor: Write out that `nGene` == number of genes and ditto for nUMI

### ISSUE THREAD

**Issue by HenrikBengtsson** [satijalab/seurat#52]
In http://satijalab.org/seurat/pbmc-tutorial.html, it may not be obvious what `n` in `nGene` and `nUMI` stands for.  Instead of
```r
#nGene and nUMI are automatically calculated for every object by Seurat.
# For non-UMI data, nUMI represents the sum of the non-normalized values within a cell
```
writing
```r
# The number of genes and UMIs (nGene and nUMI) are automatically calculated for every object by Seurat. 
# For non-UMI data, nUMI represents the sum of the non-normalized values within a cell
```
would clarify this.

**Comment by andrewwbutler** [comment]
Thanks for the suggestion! The tutorial has been updated.

**Comment by vondoRishi** [comment]
Hi ,
The tutorial is great but however it would be better with an actual UMI data. At present the very first figure is labelled with "nUMI" where it is actually total count of reads. Otherwise it could be mention that pbmc data is non UMI. 
Adding an example with UMI data will help the readers a lot.

**Comment by leonfodoulian** [comment]
Hello,

PBMC data is composed of UMI. It is data acquired using the 10X Genomics platform. 

Best,
Leon
