### ISSUE TITLE
spatial Inferring tutorial obsolete

### ISSUE THREAD

**Issue by ccshao** [satijalab/seurat#525]
Hello, 

Could you kindly update the tutorial on spatial analyis with Seurat? The current one on the website uses seurat 1.2, and many functions changed/deprecated. Thanks!

**Comment by satijalab** [comment]
At the moment we do not have the bandwidth to redo this set of tutorials. This is because we are developing new methods for this task, that we hope will be substantially improved, and also overcome some of the fixed limitations of the previous method (for example, the grid structure requirement that you cite in another issue). We will make sure that all new methods and vignettes use the most recent version of Seurat

**Comment by ccshao** [comment]
Thanks! Actually all functions are there with names changed.
