### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by alessandriLuca** [satijalab/seurat#5269]
Good morning, i was trying to reach the dockerfile, in order to build the docker with seurat, but the only thing i can find is  https://hub.docker.com/r/satijalab/seurat the link to pull the docker. Can you please provide the dockerfile?

Thank you 

Best

Luca

**Comment by timoast** [comment]
Hi @alessandriLuca, the dockerfile for Seurat can be found in this repository: https://github.com/satijalab/seurat-docker

**Comment by alessandriLuca** [comment]
Good morning,

from what i see from the repository
https://github.com/satijalab/seurat-docker , the only dockerfile that does
not start from a preexisted seurat docker image is in
seurat-docker/archive/v4/latest.  Is this dockerfile,
seurat-docker/archive/v4/latest/ the dockerfile used to create the
preexisted docker satijalab/seurat:version?
What i mean is that, besides for the dockerfile in
seurat-docker/archive/v4/latest/ , all the other docker start from FROM
satijalab/seurat:4.0.0-beta or similar. What I'm interested in is the
dockerfile to generate satijalab/seurat:4.0.0-bet.

Thank you for your availability

Best

Luca

Il giorno ven 5 nov 2021 alle ore 21:34 Tim Stuart ***@***.***>
ha scritto:

**Comment by timoast** [comment]
I believe this is the file you want: https://github.com/satijalab/seurat-docker/blob/master/latest/Dockerfile

**Comment by alessandriLuca** [comment]
Yes that's it! Thank you again!

Best

Luca

Il giorno lun 8 nov 2021 alle ore 14:02 Tim Stuart ***@***.***>
ha scritto:

**Comment by RegnerM2015** [comment]
Hi @timoast and @alessandriLuca, 

I am ultimately trying to repurpose this Docker container for my own use. First, I rebuilt the Docker image using https://github.com/satijalab/seurat-docker/blob/master/latest/Dockerfile and pushed it to a test repo in DockerHub (https://hub.docker.com/repository/docker/regnerm/scbreast). 

I next put the following R script into a Snakemake workflow where I called Singularity to run the test Docker container. 

`Plot_SeuratData.R`: 

```
library(dplyr)
library(Seurat)
library(patchwork)

# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "./filtered_gene_bc_matrices/hg19/")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)

pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))

pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)

pbmc <- RunUMAP(pbmc, dims = 1:10)

pdf("./Tutorial_PBMC_UMAP.pdf")
DimPlot(pbmc, reduction = "umap")
dev.off()
```

`Snakefile` invoked with `snakemake --use-singularity --cores 8`:

```
container: "docker://regnerm/scbreast"

rule all:
    input:
        "Tutorial_PBMC_UMAP.pdf"

rule a:
    input:
        "filtered_gene_bc_matrices/hg19/"
    output:
        "Tutorial_PBMC_UMAP.pdf"
    script:
        "./Plot_SeuratData.R"
```

However, I receive the following error:

```
Activating singularity image /home/regnerm/snakemake_test/.snakemake/singularity/b6dd844f20be4c2f82061a3cc391494e.simg
/bin/bash: Rscript: command not found
[Tue Jan  4 16:00:32 2022]
Error in rule a:
    jobid: 1
    output: Tutorial_PBMC_UMAP.pdf
```

Note that everything runs correctly when I swap out the test container with the original Seurat image at https://hub.docker.com/r/satijalab/seurat. The container line in the `Snakefile` would say satijalab/seurat instead of regnerm/scbreast. 

Therefore, it seems like the provided Dockerfile (https://github.com/satijalab/seurat-docker/blob/master/latest/Dockerfile) is different that the Dockerfile used to produce the Docker image on DockerHub (https://hub.docker.com/r/satijalab/seurat) since I am missing some underlying path to the `Rscript` command. 

Would you be able to suggest any ideas/advice for debugging the "Rscript: command not found" error? Should I append something to my $PATH in the Dockerfile? 

Thanks in advance!
