### ISSUE TITLE
subsetting Seurat object after Harmony integration

### ISSUE THREAD

**Issue by lironyoffe** [satijalab/seurat#5289]
Hi, 

I used Harmony to integrate 60 samples from multiple subjects. After identifying the major cell types, I would like to subset the integrated object and recluster the sub-objects.

I tried using the same pipeline as for the integrated object with the new objects (using the same harmony values), but the results don't look good.

cur.obj <- FindNeighbors(cur.obj, reduction = "harmony", dims = 1:n.dims)
cur.obj <- FindClusters(cur.obj, resolution = 0.5)
cur.obj <- RunUMAP(cur.obj, reduction = "harmony", dims = 1:n.dims) 

I also tried to re-integrate the samples in the new objects using Harmony and then continue with the same pipeline (subsetting and then running PCA, RunHarmony, FindNeighbors, FindClusters, etc.), but again, the results don't look good (specifically, the clusters are not separated and are blending together). 

I'm not sure how to subset a Harmony-integrated Seurat object and recluster the sub-objects. 

Using Seurat integration did not work even when using RPCA and a reference (I got a "subscript out of bounds" error). 

What is the right way to do this?

Thank you!

**Comment by torkencz** [comment]
This issue relates to https://github.com/satijalab/seurat/issues/2087#issuecomment-691250903 . I can reopen if the recommended workflow of that does not work here.

**Comment by lironyoffe** [comment]
@torkencz This solution doe not apply in this case, since there is no integrated assay

**Comment by JJBio** [comment]
Hi, we have the same issue, since there is no integrated assay and hence no corrected expression matrix. 
If I understand correctly we only have two options: 
(1) re-integration
(2) re-clustering 

The recommended workflow as suggested here (https://github.com/satijalab/seurat/issues/2087#issuecomment-691250903) is not possible, right? 
> 1. Subset the cells
> 2. Find variable features in the subset using the RNA assay
> 3. Run ScaleData on the integrate assay on the new set of variable features
> Run PCA on the integrated assay using the new set of variable features
> Run FindNeighbors and FindClusters using the new PC dimensions

So we can either (1) re-do the complete workflow after subsetting including the re-integration with harmony or (2) we can only re-run FindNeighbors and FindClusters. Is this correct? In our case, (2) worked better.
What is your recommendation here? Are both approaches acceptable?

**Comment by torkencz** [comment]
Hi, I reopened. While I would ask this question primarily from the developers of Harmony, I think both approaches you suggested should work. All in all, I am leaning more towards (1) of correcting the PCAs on a subset of your data.
