### ISSUE TITLE
To integrate or not?

### ISSUE THREAD

**Issue by SimoniMD** [satijalab/seurat#5294]
Hi all,

I know this topic has been approached many times, but I feel like each situation is different.

I have 8 human samples from 2 conditions (4+4) - same tissue source (uterus). the condition is pregnancy & not pregnant. The samples were flowed to get a certain class of cells only, and then were library prepped/sequenced together, so I don't expect batch effect.

I merge the datasets, split them, SCTransform on the split, but then did NOT integrate because i'm looking to see if new cell types get recruited to the uterus during pregnancy. Would this make sense? But i also do want to see differences between the cell types that are already there (which is what i think integration would be better for).

Now i'm reading everything else posted here and everywhere it says to integrate if you can.  But what if I don't know whether to expect new cell types? Would people just do both options, annotate the clusters, and see if they match? (the integrated and non-integrated actually do match ALMOST, but not exactly)

Just wondering what the approach would be if you're not sure what to expect.

**Comment by mhkowalski** [comment]
It is never a bad idea to compare the non-integrated and integrated datasets, although, as you mentioned, it is hard to recommend which is better without having explored your data. The primary purpose of integration is to align like cell types between the two datasets. When doing differential expression, we recommend that you do not use the integrated assay and use the original SCT or RNA assay. Therefore, if you see that most cell types seem to be aligning  relatively well without integration, it is probably ok to proceed with differential expression analysis. 

Also, a benefit of your data is that you have multiple samples from the pregnancy condition. For instance, if you have a celltype that appears in all of your pregnancy samples but none of your non-pregnancy samples, this would be indicative of true biology rather than a batch effect.
