### ISSUE TITLE
FetchData Reference Page has a 404 error

### ISSUE THREAD

**Issue by KalenBerry** [satijalab/seurat#5296]
Hello, 

Just wanted to report that the following page returns a 404 error. 
https://satijalab.org/seurat/articles/reference/FetchData.html

and is linked to from https://satijalab.org/seurat/articles/essential_commands.html

**Comment by timoast** [comment]
Hi @KalenBerry 

Thanks for pointing this out, it looks like all the functions re-exported from the SeuratObject package are incorrectly linked in the Seurat website documentation. I think this is due to the package website for the SeuratObject package incorrectly pointing to the Seurat website. I have opened a PR in the SeuratObject package to fix this (https://github.com/mojaveazure/seurat-object/pull/30).

In the meantime, you can find documentation for all functions by running `?<function_name>` in R, or you can go to the SeuratObject website to find online documentation for functions in SeuratObject: https://mojaveazure.github.io/seurat-object/reference/index.html

**Comment by timoast** [comment]
This should be fixed now
