### ISSUE TITLE
creating peak assay on a cluster with UCSC without internet 

### ISSUE THREAD

**Issue by kirakoko** [satijalab/seurat#5397]
Hey, 
I am quiet new in the analysis and couldn't find anything.. I am working with multiome data and want to create a Seurat object with a peak assay. As i am working on a cluster with no internet partition other than a build one I don't have access to this file: 
> seqlevelsStyle(annotation) <- "UCSC"
Error in download.file(url, destfile, quiet = TRUE) : 
  cannot open URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/chromInfo.txt.gz'
I managed to upload it to the cluster but wonder now I can read it in to get my peak assay. 
I am working with R4.1.0
thank you so much!

**Comment by torkencz** [comment]
Hi, this is because in the GenomInfoDb  package the function will try to fetch the chromosome sizes from UCSC with fetch_chrom_sizes_from_UCSC(). This will fail if 'genome' is an unknown UCSC genome or if the internet is not accessible. I would either take it up with the package developers or just create your annotation on another computer and transfer to the server.
