### ISSUE TITLE
normalized counts with batch correction

### ISSUE THREAD

**Issue by mvis1231** [satijalab/seurat#5454]
Hi team,

My understanding is that by using integration method, we can remove some batch effects between datasets.

If I want to get batch corrected counts from the integrated object, should I look at "data" under "integrated" assay?

Thank you!

**Comment by saketkc** [comment]
Batch corrected counts are not calculated during the integration process. You can run using counts and associated batch information (needs to be known apriori) [sctransform](http://htmlpreview.github.io/?https://github.com/satijalab/sctransform/blob/supp_html/supplement/batch_correction.html) to get corrected counts.

**Comment by cutleraging** [comment]
Hello @saketkc, sorry to reopen this issue but I was seeking some clarification on how to obtain batch corrected counts (to use for co-expression analysis) after performing integration.

Here is the original data, which has batch effects between samples even though these cells should all be the same
![image](https://user-images.githubusercontent.com/84161843/202314629-eb61c63a-550c-4f4f-bb22-996a6b0d9deb.png)

Then I perform integration using a tip to integrate all genes: https://github.com/satijalab/seurat/issues/2590
```

# integration
# split the dataset
obj.list <- SplitObject(obj, split.by = group)

# normalize and identify variable features for each dataset independently
obj.list <- lapply(X = obj.list, FUN = function(x) {
    x <- SCTransform(x, vst.flavor = "v2", verbose = FALSE)
})

# select features that are repeatedly variable across datasets for integration
var_features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 3000)
obj.list <- PrepSCTIntegration(object.list = obj.list, anchor.features = var_features)

# get anchors using repeatedly variable features
anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = var_features, normalization.method = "SCT")

# select all features to integrate
all_features <- lapply(obj.list, row.names) %>% Reduce(intersect, .)
    
# integrate using anchors from variable features but integrate ALL features
obj.integrate <- IntegrateData(anchorset = anchors, features.to.integrate = all_features, normalization.method = "SCT")

# scale and dim reduc
obj.integrate <- RunPCA(obj.integrate, npcs = 50, verbose = FALSE)
obj.integrate <- RunUMAP(obj.integrate, reduction = "pca", dims = 1:30)
```
And the integrated data looks good on a UMAP
![image](https://user-images.githubusercontent.com/84161843/202315140-056294b3-6204-4f0f-b582-5a937999d4d2.png)

However looking at the distribution of the integrated data, I can see it's no longer just positive counts and appears to be centered around 0. Because of this I don't this it is suitable for downstream analyses. The optimal input would be positive normalized counts.
![image](https://user-images.githubusercontent.com/84161843/202316630-23083cea-4786-4b6f-a109-6363e673b8ba.png)

Now are you proposing that instead of the integration I regress out the batch effect?

```
# regression on batch variables
obj <- SCTransform(obj, vst.flavor = "v2", verbose = FALSE, vars.to.regress = "sample")

obj<- RunPCA(obj, npcs = 20, verbose = FALSE)
obj <- RunUMAP(obj, reduction = "pca", dims = 1:20)
```

It does seem to remove the batch effect, but I have read somewhere that integration is preferred. Why?
![image](https://user-images.githubusercontent.com/84161843/202316744-584716a4-f697-4a6a-89f6-b2fe24a418bf.png)
