### ISSUE TITLE
How did the 'Bridge' form in single-cell transcriptome UMAP plot?

### ISSUE THREAD

**Issue by jiangpuxuan** [satijalab/seurat#5465]
Here is the identification for 'Bridge' in  _Scrublet: Computational Identification of Cell Doublets in Single-Cell Transcriptomic Data_
> multiplets of dissimilar cells (‘‘neotypic’’) generate qualitatively new features, such as distinct clusters (left) or bridges (right).

Here is the example for 'Bridge':
<img width="253" alt="fecf63d23115a233dd6ad55be286fd1" src="https://user-images.githubusercontent.com/81287604/148712570-23cc35ad-663c-457c-aea3-0c62e747a0f9.png">

I tried many softwares for trimming doublets, but my bridge had not been removed. So, are there other causes for bridge in single-cell transcriptome UMAP plot rather than doublets?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Yes it is totally possible for real cells to appear in this fashion but totally depends on inidivual experiments.  It is also possible that automated software for doublet removal are not 100% accurate and these cells are still doublets but just not detected as such by the software.  I would examine what these cells are more deeply and decide whether you think they are doublets or real cells so that you can decide whether to leave in or remove from your analysis.

Best,
Sam

**Comment by jiangpuxuan** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. Yes it is totally possible for real cells to appear in this fashion but totally depends on inidivual experiments. It is also possible that automated software for doublet removal are not 100% accurate and these cells are still doublets but just not detected as such by the software. I would examine what these cells are more deeply and decide whether you think they are doublets or real cells so that you can decide whether to leave in or remove from your analysis.
> 
> Best, Sam

Thank you for your help！
