### ISSUE TITLE
load already processed/published scRNAseq data with cell clusters and use Seurat for visualisation

### ISSUE THREAD

**Issue by harshini-c** [satijalab/seurat#5478]
Hi, I am working with a published scRNAseq dataset that has been processed and clustered, along with a lot other meta data. This is how the data looks like currently as a dataframe where relevant columns would be --

sample_index  = cell_id
count = counts data
broad.cell.type = cell type cluster
projid = patient ID

![image](https://user-images.githubusercontent.com/78223419/149023141-aac4feb7-c52d-46e6-abdf-ca0f8dadee34.png)

I would like to use Seurat to visualise the expression profiles of gene across the clusters (like RidgePlot / Feature Plot) and also based on different paramters such as the "projid" which represents patient ID.  It would be extremely helpful to me if anyone could let me know the best way to do this instead of re-analysing from the raw matrix files.

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So in terms of creating `FeaturePlots` in addition to the meta data you have shown you will also need to know the X and Y coordinates for whatever dimensionality reduction technique was used by the original authors.  Otherwise you will not be able to create identical plots (unless there methods contain enough detail to repeat their analysis exactly).

In terms of creating Seurat object you will be to split the data.frame you have shown into two parts: meta data part and a gene expression.
`CreateSeuratObject` can take any gene-by-cell matrix as input to create the starting object.

You will then need to filter the meta data so that each row is single cell.  Then you can add this to the object meta data using `AddMetaData`.

Finally if you have the dim reduc coordinates in data.frame you will need to convert them to a matrix and then create a DimReducObject that can be added to the Seurat object.  See this post for more explanation of that part with a different dataset (https://github.com/satijalab/seurat/issues/4515#issuecomment-846322426).

Then simply change the active identity to desired meta data column before plotting.

Best,
Sam

**Comment by harshini-c** [comment]
Thank you very much for your quick and detailed response! very helpful. Will update here if I have any further questions.

Best,
Harshini

**Comment by yuhanH** [comment]
Thanks @samuel-marsh for your nice explanation. It seems that this issue is resolved.
@harshini-c If you meet any other questions, we can reopen this issue.
