### ISSUE TITLE
QC when using ensembl ids

### ISSUE THREAD

**Issue by YuliaInn** [satijalab/seurat#5496]
I have 10x scRNA-seq data for a dog. The genes are in ensembl id format. I converted them to gene symbols using biomaRt and added to the Seurat features metadata like this:
`HCC1@assays$RNA@meta.features <- merge(HCC1@assays$RNA@meta.features, gfile, by=0, all.x=TRUE)`

So my **HCC1@assays$RNA@meta.features** looks like this
![Screen Shot 2022-01-13 at 12 00 29 PM](https://user-images.githubusercontent.com/54861076/149384230-37326ca7-0421-4915-b405-3425268b016e.png)

The reason why I do not want to convert features into gene symbols right away is that there are many duplicate gene symbols after conversion. That is why I want to use gene symbols in the end for annotation only.

However, for quality control purposes I need gene names (to find percentages of mitochondrial and ribosomal genes).

How to refer to the gene names when using `PercentageFeatureSet`? For example in this line:

`HCC1[["percent.rb"]]<-PercentageFeatureSet(HCC1, pattern="RP[SL]")`

**Comment by mhkowalski** [comment]
Hi, to use the `PercentageFeatureSet` function, the pattern needs to match the rownames of an assay.  

One possible way to do this is to make a unique version of the gene_names variable with the `make.unique(names, unique=TRUE)` function, which will append a number after each duplicate value of a character vector.  You could then set up your count matrix with the unique gene symbols as rownames in order to calculate percent feature sets. 

Hope this is helpful!
