### ISSUE TITLE
How to create a overlapping image

### ISSUE THREAD

**Issue by Plundgren1** [satijalab/seurat#5507]
Not sure if anyone can help with this?

### Discussed in https://github.com/satijalab/seurat/discussions/5024

<div type='discussions-op-text'>

<sup>Originally posted by **ssgwshota** September  1, 2021</sup>
Hi
FeaturePlots have the Blend function, but SpatialFeaturePlots do not.
For example, how can I superimpose the two genes of 
SpatialFeaturePlot(brain, features = c("Penk","Pde10a"))
 with different colors?</div>

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
