### ISSUE TITLE
mito genes

### ISSUE THREAD

**Issue by camilliano** [satijalab/seurat#551]
Hi everyone,

I have a question about the mitochondrial gene. 
In the **Seurat - Guided Clustering Tutorial** we can calculate  the percentage of mitochondrial genes here and store it in percent.mito.
In order to do that, we are looking for the "^MT" genes.

But why there is only 13  -MT genes? and not 37?

I know that only 13 gene code for protein but why I cannot find the other MT gene with the grep function?
Is that because of the reference genome (GrCh38)? 

Thank you for your answer.

Camille

**Comment by leonfodoulian** [comment]
Hi Camille,

Most probably these genes are not present in the matrix you are analysing (either not expressed and filtered out during the creation of the Seurat object, or not returned when counting gene counts with what ever tool you are using). 

Best,
Leon

**Comment by wyattmcdonnell** [comment]
Hi @camilliano 

Thought I would chip in to add on to @leonfodoulian's answer

The 13/14 genes you should find on the 10X platform are the polyadenylated electron transport chain genes. The remainder, which you likely aren't finding in your gene matrix, are the tRNAs and the rRNAs.   In our group's experience, we have yet to see tRNA or rRNA genes that are mitochondrially encoded turn up in the raw or filtered gene matrices coming out of CellRanger. This is probably because the tRNAs and rRNAs aren't being captured during the RT step (for instance, polyadenylation of tRNAs leads to their degradation, and occurs in the nucleus, so the Chromium probably wouldn't capture them). Curious if anybody else has had a different experience, but I hope this helps.

Cheers
Wyatt
