### ISSUE TITLE
How to save variable features from another tool in a Seurat object?

### ISSUE THREAD

**Issue by jessicafehlhaber** [satijalab/seurat#5512]
Hey,
I have created a Seurat Object (scRNA-seq data), which does not include any variable features. 

```
Seu<- CreateSeuratObject(counts = RNA_subset_S1D1_T,assay="RNA")
Seu
```
```
Warning message in storage.mode(from) <- "double":
“NAs introduced by coercion”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
An object of class Seurat 
10 features across 5616 samples within 1 assay 
Active assay: RNA (10 features, 0 variable features)
```

I want to save variable features from another tool (it is in a matrix format) into this Seurat object. Is there a way to accomplish this?

Thank you in advance!

**Comment by samuel-marsh** [comment]
Hi,

Yes, all you need is a list of genes that you want to use as the variable features and then run:
```
FEARURE_LIST <- c("Gene1", "Gene2", "Gene3")

VariableFeatures(OBJECT_NAME) <- FEATURE_LIST
```

I would say though for the example that you posted it seems like you might want to double check the data you are using to create the object because there are NAs being introduced and it says that you only have 10 genes total in the object.

Best,
Sam

**Comment by jessicafehlhaber** [comment]
Thank you very much for your answer, it helped me a lot.
