### ISSUE TITLE
levels on split.by and group.by DotPlot

### ISSUE THREAD

**Issue by anto-ucsf** [satijalab/seurat#5599]
Hi. 
I have two main identities ("ID") group in my object: "CD11b-hi" and "CD11b-lo". 
I have two types of population CD301b: "Mgl2-pos" and "Mgl2-neg". 
I would like to represent my populations grouped by identity and split by CD301b:

`  DotPlot(AW75_skin_paper2022_DC2,features=c("Cd274", "Pdcd1lg2","Socs1", "Fas","Cd80","Cd86","Cd40"), group.by="ID",split.by="CD301b", cols=c("red", "blue"))+theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))`
![FeaturePlot_AW75_skin_paper2022_CD301bposvsneg_mreg](https://user-images.githubusercontent.com/88804801/152869331-d193ad49-7818-43f2-a5d5-0c38624134b1.png)

However in my paper we compare Mgl2-pos vs Mgl2-neg, and for esthetic purposes I'd like my plots to start with Mgl2-pos. 
I tried the solution suggested in #2571:

`AW75_skin_paper2022_DC2@meta.data$CD301b <- factor(AW75_skin_paper2022_DC2@meta.data$CD301b, levels = c("Mgl2-pos", "Mgl2-neg"))`

The change in level did not modify the order within the "split identity" in my DotPlot.

Any idea why and how to make this happens? Thanks a lot.

**Comment by torkencz** [comment]
I think this is likely due to the split identity becoming a new variable with different factor levels (that doesn't retain the individual variable's factor order going into it). By the looks of it your y axis is in alphabetical order. Honestly, in this case the easiest would be to write out the data you have (FetchData) and the metadata and then create your own data frame that you can relevel.  Or edit the figure manually with illustrator.
