### ISSUE TITLE
Differential expression within a cluster

### ISSUE THREAD

**Issue by mbartl13** [satijalab/seurat#5620]
Hi, I am trying to use FindMarkers to get DEGs within a cluster based on expression of a specific gene (expression listed in metadata under cells_of_interest as detected or undetected). What am I missing?

`Detected_B<-subset(x = seurat_object, subset = cells_of_interest == "detected", idents = "IGHM+ B")
Idents(Detected_B) <- "Detected_B"
Undetected_B<-subset(x = seurat_object, subset = cells_of_interest == "undetected", idents = "IGHM+ B")
Idents(Undetected_B) <- "Undetected_B"

DEG <- FindMarkers(seurat_object, ident.1 = "Detected_B", ident.2 = "Detected_B", verbose = FALSE)
`
_Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: Detected_B_

Thanks!

**Comment by mhkowalski** [comment]
Hi, 

The problem is that if you view the Idents of the object you are trying to perform DE on with ```table( Idents(seurat_object))``` you will see that this does not contain "Detected_B", so the function is looking for cells it cannot find. Instead, you could first subset out the  "IGHM+ B" cells and then perform differential expression using the ` cells_of_interest` variable. 

For example, 
```
b <- subset(x = seurat_object,  idents = "IGHM+ B")
Idents(b) <- b$cells_of_interest
DEG <- FindMarkers(b, ident.1 = "detected", ident.2 = "undetected", verbose = FALSE)
```

**Comment by mbartl13** [comment]
Thanks, that worked!
