### ISSUE TITLE
Renaming Cluster IDs

### ISSUE THREAD

**Issue by Tyler-tech-png** [satijalab/seurat#5624]
I followed the well-established workflow for renaming cluster IDs from "0", "1", etc. to "Cell_type_1", "Cell_type_2", etc. as detailed below.
```
cluster.ids <- c("Muscle Fast", "Muscle Slow") 

names(cluster.ids) <- levels(object)

object <- RenameIdents(object, cluster.ids)
```
This successfully renamed my clusters. However, after returning and trying to rename the clusters using the same process, or 

`object <- RenameIdents(object, 'Muscle Fast' = "new.name")`

I get the error: Warning: Cannot find identity NA. Upon checking GitHub, someone else had the same problem, issue #3139. I have re-run this in a new R session with the same result.

Any help would be great. Thanks!

```r
# insert reproducible example here
```

**Comment by Tyler-tech-png** [comment]
Hi Sam, thanks for the reply.

I figured out the error more specifically. It comes from trying to rename clusters that have been assigned the same name. For example, if I name two clusters "a"
```
cluster.ids.new <- c("a", "a", "c", "d")
names(cluster.ids.new) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, cluster.ids.new)
```
and then try to rename the clusters "a", "b", "c", "d" using the same process, I get "Warning: Cannot find identity NA"

I cannot find a way to rename the clusters once they have been assigned the same identity.

**Comment by samuel-marsh** [comment]
Hi,

So I'm not sure I understand the issue because again things aren't causing me an issue when I try to rename using a name that's already in use.

```
DimPlot(pbmc, label = TRUE) + NoLegend()

new_names <- c("level 1", "level 2", "level 1", "level 4", "level 5")
names(new_names) <- levels(pbmc)

pbmc <- RenameIdents(object = pbmc, new_names)
DimPlot(pbmc, label = TRUE) + NoLegend()


pbmc <- RenameIdents(object = pbmc, "level 2" = "level 1")
DimPlot(pbmc, label = TRUE) + NoLegend()
```

In your example in your response it makes sense that doesn't work though.  If you renamed clusters 0, 1, 2, 3 to become a, a, c, d.  Then you can't rename them as a, b, c, d because once you renamed them there are only 3 (a, c, d) levels and not 4.  If you want to rename off of the original structure you can always stash that ident in the meta data, rename clusters, then set ident back to original names and rename again off of that original structure.

Best,
Sam

**Comment by Tyler-tech-png** [comment]
Great, I was able to stash the old.ident in metadata and reset the identities to the original seurat_clusters column from the metadata.

Thanks for your help!
