### ISSUE TITLE
Using WNN approach to analyse ADT + GEX

### ISSUE THREAD

**Issue by qoiopipq** [satijalab/seurat#5627]
I've ADT and GEX libraries. ~8K cells in GEX and 4 antibodies in ADT. Then I followed the WNN workflow to analyse ADT and GEX libraries (i.e. pre-processing them independently). After calculating weights from both modalities based on the clusters, I found most of the clusters have high ADT weights (from cluster 0 to cluster 23, ADT weight = 1): 

I plotted median modality weight based on clusters: 
![image](https://user-images.githubusercontent.com/16911467/154198037-35346399-5c30-4bd9-8433-676bac65b40b.png)

I noticed that in here #3759 has discussed that WNN approach doesn't work if analysing a small number of antibodies. The questions I have are:

1.  In this case, I have 4 antibodies, is it still OK to perform WNN? Or if it's better to do clustering on RNA/GEX then overlay protein enrichment info on top of the RNA clusters? 
2.  I also noticed that there are methods like using dsb (https://cran.r-project.org/web/packages/dsb/vignettes/dsb_normalizing_CITEseq_data.html#wnn) to normalise protein values then put the normalised protein values to WNN. Would this method worth a try?

Thanks!

**Comment by k3yavi** [comment]
Hi @qoiopipq ,

As mentioned in the thread you linked, it doesn't make much sense to use WNN approach with only a few ADT features. You can definitely try overlaying protein enrichment over RNA-seq cluster or using the dsb tool but imho the problem is not the normalization, it's having only 4 antibodies; using which you can create only 2-3 low dimensional embeddings.
