### ISSUE TITLE
SCT Vignette doesnt scale pearson residuals before PCA

### ISSUE THREAD

**Issue by danielcgingerich** [satijalab/seurat#5649]
The sct vignette leaves out setting `do.scale = T` in the `SCTransform` function.   Why is this?   

Here are my thoughts.  Let me know if I am misunderstanding something: 

In theory, the variance of the pearson residuals should be approximately equal across genes, but in practice this may not be true.  The variance of the Pearson residuals will not be equal across genes, leading to uneven weighting when running PCA.  

I looked at two SCTransformed datasets of mine.  I calculated variance of the pearson residuals: 
```
mtx1 <- obj1@assays$SCT@scale.data ; var1 <- apply(mtx1, MARGIN = 1, var)
mtx2 <- obj2@assays$SCT@scale.data ; var2 <- apply(mtx2, MARGIN = 1, var)

quantile(var1, probs = seq(0,1,0.1)) ; quantile(var2, probs = seq(0,1,0.1))
        0%        10%        20%        30%        40%        50%        60%        70%        80%        90%       100% 
 0.1184756  0.3333104  0.5396053  0.7032464  0.8084059  0.8959035  0.9832648  1.0901368  1.2814459  1.8054586 32.5996674 
        0%        10%        20%        30%        40%        50%        60%        70%        80%        90%       100% 
 0.1170762  0.3798686  0.5774389  0.6938045  0.7764559  0.8477527  0.9230154  1.0247237  1.2106634  1.7642437 48.4945970 

```

There are a few genes in both datasets with super high variance.  I can imagine these outweighing other important genes in PCA... 

I think `do.scale` should be set to TRUE if you plan to run PCA on SCT normalized data.  Scaling the data will not strongly affect the genes that have variance around 1 (majority of the data), but it will reduce the effect of outliers with very high variance.

**Comment by saketkc** [comment]
> In theory, the variance of the pearson residuals should be approximately equal across genes, but in practice this may not be true. 

In practice, this is almost never true (unless the dataset is 'truly' homogeneous). This is a feature, that we actually use to identify variable genes (higher residual variance => highly variable even after accounting for sequencing depth). 

> There are a few genes in both datasets with super high variance. I can imagine these outweighing other important genes in PCA...

The residuals for most genes are all on the same "scale", which is not true when you use log normalization (as described in the SCtransform [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1)). While we recommend `do.scale=F`,  setting it otherwise could be helpful in scenarios where a very small set of genes are defining a cluster (due to super high pearson residuals).

**Comment by danielcgingerich** [comment]
@saketkc Thank you for the explanation.  Yes, when I said "a few genes in both datsets with super high variance" I meant the variance of the pearson residuals, not the log normed genes.  Most pearson residuals are between 0.8 and 1.2, as expected, but as you can see the highest variance is ~48.  A few genes reach into the 20s, 30s and 40s.  I think it might be good in my case to scale these before further analysis
