### ISSUE TITLE
FeaturePlot(split.by = "foobar") is not compatible with ggplot scale_color_* function

### ISSUE THREAD

**Issue by JackieMium** [satijalab/seurat#5664]
I want to plot out split plots of the expression of a feature in two samples with `FeaturePlot(split.by = "stim")`. I changed color scheme with 

```
FeaturePlot(seurat_object, 
            split.by = "stim",
            features = myFt) + 
scale_color_viridis_c(direction = -1))
``` 

The `scale_color_viridis_c(direction = -1))` function worked as expected as long as I didn't add the `split.by = "stim"` arg. Seems `scale_color_viridis_c(direction = -1))` only took effect in one of the plots (or should I say the last plot):

![image](https://user-images.githubusercontent.com/12944832/155724772-28783155-48a3-457e-af5d-3812c9daf802.png)

The plot one the left (first) still uses the defafult grey and blue pallete, the one on the right (the last plot), however, picked up the viridis colors.

**Comment by samuel-marsh** [comment]
Hi,

So the reason is because split plots are patchwork objects and you need to use patchwork to add elements across all plots by using `&` instead of `+`.

However, be aware that doing so will change the plots so that the scales are no longer the same/comparable across all plots (see example below).

```
pbmc$sample_id <- sample(c("sample1", "sample2", "sample3", "sample4"), size = ncol(pbmc),
                         replace = TRUE)

FeaturePlot(object = pbmc, "FOS", split.by = "sample_id") & theme(legend.position = "right")
FeaturePlot(object = pbmc, "FOS", split.by = "sample_id") & scale_color_viridis_c(direction = -1) & theme(legend.position = "right")
```
![image](https://user-images.githubusercontent.com/38284410/155731712-42ed1239-49a8-414d-92c7-6d374aedfdc5.png)

![image](https://user-images.githubusercontent.com/38284410/155731623-24552256-1305-4c96-8046-6ea2440f715b.png)


As alternative you can use `FeaturePlot_scCustom` from my package scCustomize to supply custom gradient and easily maintain color scale across plots (non-expressing cells are also colored using different color and are not part of color scale).

```
FeaturePlot_scCustom(seurat_object = pbmc, features = "FOS", split.by = "sample_id", colors_use = viridis(10, direction = -1))
```

![image](https://user-images.githubusercontent.com/38284410/155732625-ff0b9b45-e671-4df3-9501-01064f5b1aaa.png)


Best,
Sam

**Comment by JackieMium** [comment]
@samuel-marsh thanks for your clarification and solutions. 
In the meantime, I am thinking that it's still a bug in FeaturePlot, or a flaw with the function. Color scale should apply to all plots simultaneously because it makes no sense to use different colour scales in a split plot which is used for comparison. Also, it seems to work for `DimPlot()` and `DotPlot()`.

**Comment by samuel-marsh** [comment]
Hi,

I'm not a dev but I don't believe this is bug.  This is simply how the patchwork package functions for arranging multiple plots (see https://patchwork.data-imaginist.com/).  There are many other instances of this type of issue being brought up if you search the issues.  Depending on how the plots are assembled in the Seurat function depends on whether a patchwork or ggplot object is returned (see function documentation).

This thing can be seen if you are trying to plot the legends for plots.
```
FeaturePlot(object = pbmc, "FOS", split.by = "sample_id") + theme(legend.position = "right")
FeaturePlot(object = pbmc, "FOS", split.by = "sample_id") & theme(legend.position = "right")

```

![image](https://user-images.githubusercontent.com/38284410/155743235-81e2c1e9-5707-436b-a306-d227c24c350d.png)
![image](https://user-images.githubusercontent.com/38284410/155743294-ea69574f-fe2c-4e00-b273-d24aaaf3fdd8.png)

Best,
Sam
