### ISSUE TITLE
How to change the scale bar to same range for multiple cryosections in SpatialFeaturePlot ? 

### ISSUE THREAD

**Issue by LinAU** [satijalab/seurat#5677]
Hi I am using [SpatialFeaturePlot](https://satijalab.org/seurat/reference/SpatialPlot.html) to plot multiple cryosections. However, the ranger of the scale bar is different in different cryosections. LIke in the democase in the Vignette, L2/3 IT is 0.0-0.6, and L4 is 0-0.3

May I ask how to generate the same scale bar for multiple cryosections, when plot them at the same time ?

Thanks in advance for your help. 
KR
Lin

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
