### ISSUE TITLE
difference between highly variable genes and marker genes

### ISSUE THREAD

**Issue by FionaMoon** [satijalab/seurat#5743]
Dear all,
As a new user of Seurat , I have two questions below.

1. I wonder what' the difference between `highly variable genes` and `marker genes`. Most of the time in my analysis they are overlap.

2. Which of them should be considered as different expression genes? 

Thank you for your help!

Fiona

**Comment by samuel-marsh** [comment]
Hi,

Hi, not member of dev team but hopefully can be helpful.  This is due to the nature of how analysis is performed and relates to the issue of p values from cluster vs cluster comparisons being artificially inflated (and why setting p value cutoffs using these DEG p values is often not recommended.  See comment here for some more details:
https://github.com/satijalab/seurat/discussions/5528#discussioncomment-2016188.

There have been a couple of newer approaches attempting to address this issue with pvalues in cluster vs cluster DE but to my knowledge there isn’t yet consensus as to which is best.

Best,
Sam

**Comment by yuhanH** [comment]
Thanks @samuel-marsh for your reply. As always, your reply is very helpful.
Just add a few comments. 
`highly variable genes` usually means that genes have variation across all cells.  Here is a description of one FindVariableFeature method. 
```
vst: First, fits a line to the relationship of log(variance) and log(mean) using local polynomial regression (loess). 
Then standardizes the feature values using the observed mean and expected variance (given by the fitted line). 
Feature variance is then calculated on the standardized values after clipping to a maximum (see clip.max parameter).
```

`marker genes` usually means the genes highly or lowly expression in some clusters. They are usually obtained by some differential analysis.

**Comment by FionaMoon** [comment]
Thank you for your answer.



---- 回复的原邮件 ----
| 发件人 | Yuhan ***@***.***> |
| 日期 | 2022年03月19日 02:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [satijalab/seurat] difference between highly variable genes and marker genes (Issue #5743) |

Thanks @samuel-marsh for your reply. As always, your reply is very helpful.
Just add a few comments.
highly variable genes usually means that genes have variation across all cells. Here is a description of one FindVariableFeature method.

vst: First, fits a line to the relationship of log(variance) and log(mean) using local polynomial regression (loess). 
Then standardizes the feature values using the observed mean and expected variance (given by the fitted line). 
Feature variance is then calculated on the standardized values after clipping to a maximum (see clip.max parameter).


marker genes usually means the genes highly or lowly expression in some clusters. They are usually obtained by some differential analysis.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
