### ISSUE TITLE
The impact of variable features on PC variance explained

### ISSUE THREAD

**Issue by yeastce11** [satijalab/seurat#5770]
Hi, I was working with fetal tissue cells and I initially run the following:

```
# Normalize data
data <- NormalizeData(data)

# Find variable features
data <- FindVariableFeatures(data, selection.method = "vst", nfeatures = 2000)

# Scale data
data <- ScaleData(data)

# PCA
data <- RunPCA(data)
```

I was then interested to see the variance explained by the calculated PCs (50 by default) and I've got ~30%.
Then I decreased the `nfeatures` parameter to 1000 and I've got ~40% for the variance explained.
The code snippet I used to calculate percentage is from zeehio's answer in https://github.com/satijalab/seurat/issues/982.

Now I'm wondering how lowering the number of HVGs (highly variable genes) increases the variance explained? Or maybe there's something I'm missing or simply don't understand enough the underlying logic?

Many thanks!

**Comment by longmanz** [comment]
Hi @yeastce11 , 
It is generally better to include a larger number of HVGs to run RunPCA(), because the variance-covariance matrix of the data/cells is more accurately estimated (i.e., the variability of the data/cells are better represented). Accordingly, the variance explained by top 50PCs will be lower.
