### ISSUE TITLE
Forcing FindMarkers() to report near-0 p-values

### ISSUE THREAD

**Issue by indraroy** [satijalab/seurat#5784]
Dear Seurat developers,

I am using FindMarkers to identify marker genes for disease vs. control. The test I am using is MAST from Bioconductor.

The issue is as follows: for both my top 50 up or downregulated marker genes, there are many with p-values of 0. I assume that this is because the they are so significant as to consider the p-value 0, because it is so small. However, this presents an issue when attempting to visualize these markers using (for example) a volcano plot. The genes with p-val of 0 are converted to the closest non-zero p. Which leaves a weird diagram where all the most-significant genes are clumped in a line on top.

Is there a way to get FindMarkers to report the actual p-values instead of 0, no matter how small the p?

**Comment by jsim91** [comment]
Computers can only confidently do math on floating point numbers within a certain range because of how numbers are stored in memory. If those bounds are exceeded, computers can either (1) compromise on precision (bad) or (2) round to the nearest limit (less bad). There will always be a restraint on what can confidently be reported with current computing methods.

For more: https://stackoverflow.com/questions/38165221/r-largest-smallest-representable-numbers

**Comment by saketkc** [comment]
It is also perfectly fine in such scenarios to set a a lower limit for p-values to your machine's [lower limit](https://stats.stackexchange.com/questions/78839/how-should-tiny-p-values-be-reported-and-why-does-r-put-a-minimum-on-2-22e-1). Alternativel, if you use ggplot to plot such genes, they will show up as "Inf" points on the top like the figure in [this](https://stackoverflow.com/q/45271442) question, which is also fine imo.
