### ISSUE TITLE
Multiple comparison testing with single-cell data

### ISSUE THREAD

**Issue by shikhanayar** [satijalab/seurat#5790]
Hi, I am trying to test for comparisons of means for one protein's ADT expression within a multimodal seurat object, between different cell types or different conditions. Is there a way to currently do this? I only seem to find pairwise testing available for this. 

Similar to the following issue: https://github.com/satijalab/seurat/issues/1911

I see that you suggested to use FindAllMarkers for multiple testing but I don't see an option under test.use for e.g. ANOVA or something that would test for multiple comparisons. 

Thank you.

**Comment by saketkc** [comment]
For accounting for a specific condition as a latent variable, you can use the LR or MAST based DE test. For example,

```r
library(Seurat)
library(SeuratData)
data("pbmc3k.final")
pbmc3k.final$condition <- sample(c("c1", "c2"), ncol(pbmc3k.final), replace = TRUE)
markers <- FindMarkers(pbmc3k.final, ident.1 = "B", latent.vars = "condition", test.use = "MAST")
```

Feel free to reopen with any followup questions.

**Comment by brookeabrown** [comment]
Hello, I have the same question as the original post. I have 6 groups and want to compare the differential expression across all conditions, using an ANOVA or something similar. I ran the code that was posted here and only get one p-value. Is it possible to compare all conditions at once, or will I need to do individual "FindMarkers" with Wiloxcon test for each comparison? Although I don't know if the latter is ideal because each individual comparison is going to ignore the values of the other groups.

Here is the plot I am looking to add statistics too.
<img width="431" alt="Screen Shot 2022-09-26 at 10 07 12 PM" src="https://user-images.githubusercontent.com/105321750/192415609-966d60a2-c771-435f-8f8b-8c81c7b0f7cb.png">

Thanks in advance for any help!

**Comment by EzequielD-86** [comment]
I was wondering how you solved this, I am in a similar situation. Thanks a lot!

**Comment by feanaros** [comment]
Same, please
