### ISSUE TITLE
seurat-disk not compatible with newer versions of python AnnData

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#5794]
Hello,

I dont know if the ancillary seurat repos are watched very well, so i want to make you aware of this issue and fix:

https://github.com/mojaveazure/seurat-disk/pull/106

The gist is that python's anndata >0.8.0 is more strict on reading AnnData attributes. This PR should fix a problem where gene names in an AnnData created by seurat-disk are not read correctly in the latest anndata.

**Comment by bbimber** [comment]
Hello - sorry to bug but is there a chance someone would be willing to look at this PR? It's a bugfix designed to make seurat-disk compatible with the latest python AnnData package.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
