### ISSUE TITLE
Integration using SCT and lognorm gives Different DEGs

### ISSUE THREAD

**Issue by Rohit-Satyam** [satijalab/seurat#5812]
Hi developers!! 

I am analyzing a malaria dataset obtained where cells were highly synchronized at the ring stage. I have two samples, control, and knockout and I have to perform differential expression analysis. I started a discussion thread [here](https://www.biostars.org/p/9516696/) to understand which approach is best to deal with my data. I have a few queries for the same:

1. I see more clusters when using SCT (23 clusters) and 7 clusters when using lognormal. There is no prior information regarding how many cell types must be observed at this stage in the Malaria Cell Atlas. How do I choose which approach is better?
2. I get a lot of DE genes when using lognorm rather than when using SCT upon integration. Why so? How much overlap should I expect between the two DEG lists? I see a considerable amount of gene overlaps from the SCT side rather than the lognormal side (36% of lognormal overlaps with SCT and 60% of SCT overlaps with lognormal ). Do you recommend using the DEGs obtained from the intersection of the two approaches?
3. Also, in the vignette, why do you use `log2FC threshold=0.25` which is roughly 1.2 FC, and not `1` which represents 2 FC. Is it usual to get lower foldchange for many genes as compared to bulkRNASeq? 
4. As you analyze a lot of RNASeq data, how much overlap do you usually observe between Bulk RNASeq and scRNASeq results in terms of Differential Expression. Has there been a systematic study to show that?
5. My single cells contain on average 100-250 genes expressed (ring stage show low expression of genes) should I reduce the `nfeatures` parameter from `2000` to `200` ?

PS: Can I share the UMAPs over the email for help?

**Update 1:** I performed integration and I could see good integration using `SCTv2` and less cluster switching/splitting as the resolution increases (using `clustree`; however I used the default of 0.5). I then carried out cluster wise DE analysis (something like `cluster_0_knockout` vs `cluster_0_control`) using `FindMarkers` and `min.pct=0.25` and then merged DE list and filtered currently based on `p-values` only to check rough overlap. 
![image](https://user-images.githubusercontent.com/55479480/161340277-d19a107f-5c94-4cfd-95a9-7febcb45e4f1.png)

**Comment by saketkc** [comment]
Hi @Rohit-Satyam,

>I see more clusters when using SCT (23 clusters) and 7 clusters when using lognormal. There is no prior information regarding how many cell types must be observed at this stage in the Malaria Cell Atlas. How do I choose which approach is better?

This can happen for a number of reasons, but primiarily because the pearson residuals and the log normalized data are on different scales leading to a different underlying structure (eve when using the same resolution parameter).

> I get a lot of DE genes when using lognorm rather than when using SCT upon integration. Why so? How much overlap should I expect between the two DEG lists? I see a considerable amount of gene overlaps from the SCT side rather than the lognormal side (36% of lognormal overlaps with SCT and 60% of SCT overlaps with lognormal ). Do you recommend using the DEGs obtained from the intersection of the two approaches?

You should ideally stick to one normalization and DEG workflow. DE should never be performed on the integrated assay (I am not sure if that explains the difference in numbers here though). But generally, for shallow sequenced datasets we see very similar marker genes using either the [LogNormalization](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html) or [SCT (v2)](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) workflow. 

> Also, in the vignette, why do you use log2FC threshold=0.25 which is roughly 1.2 FC, and not 1 which represents 2 FC. Is it usual to get lower foldchange for many genes as compared to bulkRNASeq?

It is hard to set a universal threshold that applies in all the contexts, but for a lot of use cases 0.25 is a reasonable cutoff to call something DE (particularly so when the sequencing depth is shallow). The DE results can always be filtered for more stringency (and biologically relevance)


> As you analyze a lot of RNASeq data, how much overlap do you usually observe between Bulk RNASeq and scRNASeq results in terms of Differential Expression. 

Comparing scRNA-seq DE results  with bulk data is only possible if you have "pure" bulk samples (Say a FACS sorted population of monocytes sequenced as bulk) .
 
> My single cells contain on average 100-250 genes expressed (ring stage show low expression of genes) should I reduce the nfeatures parameter from 2000 to 200 ?

Again, these parameters will vary from dataset to dataset and the idea behind these parameters is to exclude low quality cells (and doublets) from affecting your downstream analysis. I would adjust the cutoffs based on an exploratory QC of your data (just like what you suggested).
