### ISSUE TITLE
Adding MAGIC to Seurat

### ISSUE THREAD

**Issue by scottgigante** [satijalab/seurat#585]
Hi,

We spoke a while ago about adding [PHATE](https://github.com/KrishnaswamyLab/PHATE) and eventually [MAGIC](https://github.com/KrishnaswamyLab/MAGIC) to Seurat. MAGIC has just been submitted to CRAN and is in a stable state. 

How should a tool such as MAGIC interact with Seurat? Do you currently have any imputation methods included in the package that I can use to model the API?

Thanks,
Scott

**Comment by mschilli87** [comment]
Another case that ~would~could benefit from https://github.com/satijalab/seurat/issues/586.

**Comment by satijalab** [comment]
Agreed! We don't have an API that works well with this yet, but will in the future- and will keep you updated as things progress.

**Comment by huqingtao2018** [comment]
Hi, scott,

After running MAGIC, I want to use the result dataframe as input for RunMultiCCA in Seurat package.  I don't know which slot should the MAGIC dataframe be put (raw.data, data or scaled.data?), I put the MAGIC result at @data slot and got error message when running RunMultiCCA(something like subscription out of bound). Is this caused by those negtive value in the MAGIC dataframe? Woud you please give any suggestion on it?

Thank you.
Best wishes!

**Comment by scottgigante** [comment]
@huqingtao2018 , how one would insert external data into an existing object is not my expertise - you're better off opening a separate issue to discuss this. MAGIC returns a `data.frame` with one column for every row, in which missing values are imputed; you might be best off creating a new Seurat object for this, but as I said, the Seurat help manual or authors are better positioned to answer your question.

**Comment by mschilli87** [comment]
@scottgigante: @huqingtao2018  opened https://github.com/satijalab/seurat/issues/612 for this.
