### ISSUE TITLE
Atomic sketch integration for scRNA-scATAC integration

### ISSUE THREAD

**Issue by jindalk** [satijalab/seurat#5850]
Hi, thanks for developing this highly scalable version of Seurat integration. I am curious to know if the atomic sketch workflow can be applied to cross modality integration of 2 two large datasets, eg ATAC and RNA. The only way i could think of is to identify atoms in each dataset (1/dataset so total 2), perform CCA integration on atoms and then use IntegrateSketchEmbeddings to integrate the full RNA and ATAC datasets with the merged atom.

Would be great to know if you have tried this/have any thoughts on it.

Thanks!

**Comment by yuhanH** [comment]
Hi @jindalk 
Due to the sparsity of scATAC data, current leverage score implementation is not applicable for scATAC data. 
For the cross modality integration, if you have a multiomic data from the same sample, you can try our [bridge integration](https://satijalab.org/seurat/articles/bridge_integration_vignette.html).
