### ISSUE TITLE
Dots on the Stacked Violins

### ISSUE THREAD

**Issue by vkavaka** [satijalab/seurat#5852]
Dear Seurat team,

is there any possibility to plot the dots on the stacked violin plot? As I understand, the VlnPlot function removes them as soon the "stack" parameter is TRUE.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So if you want the points you can add them back in manually using ggplot2 themeing with Seurat:

```
VlnPlot(pbmc, c("PTPRC", "CD14"), raster = FALSE, stack = T) + geom_jitter()
```

![image](https://user-images.githubusercontent.com/38284410/163203976-c7c81762-e4b1-401e-a108-032667f6795f.png)

However, you should be aware that depending on the number of cells in your object and the number of features in the stack the resulting plots may take longer to render (both in and out of R) due to the number of points in vector form.


As alternative you can see the function `Stacked_VlnPlot` from my package scCustomize (https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#stacked-violin-plots).  Just like in Seurat by default points are excluded but you can add them back in by manually specifying the `pt.size` parameter and you can rasterize the points if you have lot of cells using `raster` parameter (https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#point-size-and-rasterization)

Best,
Sam
