### ISSUE TITLE
Convert an already clustered Seurat Object to Monocle

### ISSUE THREAD

**Issue by blusoldier001** [satijalab/seurat#5857]
Hi,

I'm trying to convert a Seurat Object that's already been clustered with cluster labels identified into a Monocle CellDataSet object, so I won't have to recluster the cells.

I've proided some screenshots of what the dataframe for my Seurat Object looks like at the moment:
![image](https://user-images.githubusercontent.com/35697422/163489793-a3b38439-84fb-4e1d-a117-98d359d91983.png)
![image](https://user-images.githubusercontent.com/35697422/163489832-92c150f8-455c-41dc-a4e1-23b306fd7f5e.png)

I'm trying to convert this to a Monocle CellDataSet and then maintain the clusters detailed in the "seurat_clusters" column and labeled in the "labels" column. However, I've been having trouble converting it without losing data. Is there any way this can be accomplished?

**Comment by saketkc** [comment]
It is not clear what the error is (since there is no code), but you can use the [`as.cell_data_set`](https://rdrr.io/github/satijalab/seurat-wrappers/man/as.cell_data_set.html) function from [SeuratWrappers](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/monocle3.html) to retain the metadata (see the documentation for notes on how the labels are transferred).

**Comment by dpwlek1997** [comment]
Did you figure out how to transfer the annotated cell-type data?
