### ISSUE TITLE
Strange behaviour with FeatureScatter when one feature is all 0s.

### ISSUE THREAD

**Issue by davidsanin** [satijalab/seurat#5875]
Hi Seurat team!

I found that when one of the features plotted with `FeatureScatter` is just a vector of 0s, the function will instead create a random (?) distribution between -0.4 and 0.4. I am not sure if this is intended behaviour or if its a quirk of the data I am working with.

I downloaded a dataset deposited online:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126068
I took their raw count matrices, and imported them into R. The authors describe these as "csv files represent raw un-normalized counts. One csv file per patient with each column representing an individual cell."

I ran:
```
zz <- gzfile(description = "PATH_TO_FILE")
  data <- read.table(zz, header = T, row.names = 1, sep = ",")
  data <- CreateSeuratObject(
    counts = data, min.cells = 3,
    min.features = 200)
  
  #Get mitochondrial percentage
  data[['percent.mito']] <- PercentageFeatureSet(data, 
                                                      pattern = '^MT-')
  p1 <- FeatureScatter(object = data,
                       feature1 = "nCount_RNA",
                       feature2 = "percent.mito",
                       pt.size = 0.2)
````

The resulting plot is bizarre.
![Rplot](https://user-images.githubusercontent.com/57994984/164517116-09978968-ab7a-49fd-adb1-3ba51630df30.png)

I was worried there was an error in the upstream processing of these files (maybe some negative values in the deposited data?). so I checked this on the imported matrix (prior to converting it to a Seurat object):
```
sum(colSums(data<0))
[1] 0
```
So that does not seem to be the issue.
Then I simply looked at `data$percent.mito` and this was just a vector of 0s.
```
sum(data$percent.mito)
[1] 0
```
I guess the authors of the data scrubbed all mitochondrial genes. What I don't get is how/why FeatureScatter is creating that random distribution. Is this intended behaviour?

Thanks for a wonderful package!

```
sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 12.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RColorBrewer_1.1-2     goseq_1.44.0           geneLenDataBase_1.28.0 BiasedUrn_1.07         reshape2_1.4.4        
 [6] gam_1.20               foreach_1.5.1          SeuratWrappers_0.3.0   future_1.23.0          patchwork_1.1.1       
[11] forcats_0.5.1          stringr_1.4.0          purrr_0.3.4            readr_2.1.1            tidyr_1.1.4           
[16] tibble_3.1.6           tidyverse_1.3.1        biomaRt_2.48.3         ggrepel_0.9.1          scales_1.1.1          
[21] plyr_1.8.6             clustree_0.4.4         ggraph_2.0.5           ggplot2_3.3.5          dplyr_1.0.7           
[26] SeuratObject_4.0.4     Seurat_4.1.0   
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I thought this was curious too so took a look.  The reason is because there is parameter in `FeatureScatter` called `jitter`.  This adds some random noise to spread out crowded points but as you point out when parameter is 0 that creates false impression.  You can visualize example with pbmc3k dataset if you set percent mito to mouse pattern:

```
pbmc <- pbmc3k.SeuratData::pbmc3k.final
pbmc[['percent.mito']] <- PercentageFeatureSet(pbmc, pattern = '^mt-')

p1 <- FeatureScatter(object = pbmc, feature1 = "nCount_RNA", feature2 = "percent.mito", pt.size = 0.2, jitter = T) + NoLegend()

p2 <- FeatureScatter(object = pbmc, feature1 = "nCount_RNA", feature2 = "percent.mito", pt.size = 0.2, jitter = F) + NoLegend()
```

![image](https://user-images.githubusercontent.com/38284410/164529558-6318932b-85d9-42d1-a590-a1e64492e962.png)


As for the authors removing the mitochondrial genes it could be that they simply aligned their data using a reference annotation that didn't contain the mito genes.  I would check the paper methods to have better idea of how they performed that step.  If those and potentially other excluded genes are important to you then you could download the raw data from that GEO reference and reprocess using different annotation.

Best,
Sam

**Comment by samuel-marsh** [comment]
@davidsanin This behavior is now updated in the develop branch.  `jitter` is set to false by default.

Best,
Sam

**Comment by davidsanin** [comment]
Thanks @samuel-marsh!
Jitter here could be quite misleading!
