### ISSUE TITLE
unable to load shared object '/usr/local/lib/R/site-library/hdf5r/libs/hdf5r.so'

### ISSUE THREAD

**Issue by DadongZ** [satijalab/seurat#588]
I got some issue to load the library:
```R
> library(Seurat)
Loading required package: ggplot2
Loading required package: cowplot

Attaching package: ‘cowplot’

The following object is masked from ‘package:ggplot2’:

    ggsave

Loading required package: Matrix
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/hdf5r/libs/hdf5r.so':
  libhdf5_serial_hl.so.10: cannot open shared object file: No such file or directory
```

Any suggestions?

**Comment by mschilli87** [comment]
Looks like hdf5 was (re)moved since Seurat was installed. Which system are you on?

**Comment by DadongZ** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

**Comment by leonfodoulian** [comment]
Hi @DadongZ,

I often had this error with other packages. Try re-loading R and re-installing the Seurat package. This solution very often fixed my issues.

Best,
Leon

**Comment by DadongZ** [comment]
Thanks Leon, I will try it!

**Comment by mschilli87** [comment]
Otherwise, try `R CMD ldd /usr/local/lib/R/site-library/hdf5r/libs/hdf5r.so` to see where R looks for the library to and `locate libhdf5_serial_hl.so.10` to check where (if at all) is is now. If it's missing entirely, try (re-)installing the package that provides it (`apt-file search libhdf5_serial_hl.so.10` should tell you which one). Once you are sure it exists, I woudl re-install the hdf5r package, not Seurat as Seurat seems to just trigger this issue indirectly via its dependency of hdf5r.

**Comment by leonfodoulian** [comment]
@mschilli87: indeed, you are right. I meant writing **hdf5r** instead of **Seurat**.

**Comment by mthjwu** [comment]
https://github.com/hhoeflin/hdf5r/issues/94
