### ISSUE TITLE
can I use FindMarkers in an integrated data

### ISSUE THREAD

**Issue by ElyasMo** [satijalab/seurat#5881]
Dear Seurat developers,

I have two datasets from two different studies. Hence, I need to integrate them to remove the unknown batch effects. Then I want to do the differential gene expression between two clusters of these two datasets. To do so:

```r
all_objects <- c(Normal.Epithelial, Malignant)
all_objects <- lapply(X = all_objects, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst")
})

features <- SelectIntegrationFeatures(object.list = all_objects)

anchors <- FindIntegrationAnchors(object.list = all_objects, anchor.features = features)
all.int <- IntegrateData(anchorset = anchors)

sc.MalvsNorm <- FindMarkers(all.int, ident.1 = "Malignant", ident.2 = "Normal" ,l
ogfc.threshold = FALSE, min.pct = 0.2, assay = "integrated",densify = TRUE)
```

The volcano plot that is being produced after this analysis is wierd and seems not to be correct. I change the test.use but did not work. Here is the Volcano plot:
![Rplot](https://user-images.githubusercontent.com/58432307/164910035-3f619628-f7be-44e2-8f97-efedc391be49.jpeg)

I read before (https://github.com/satijalab/seurat/issues/1168) that we are not allowed to do the differential gene expression using the integrated data. So, If I change the assay to "RNA", how we can trust that the DEGs are not due to the batch effects originated from the differences between two datasets, as the aim of integration is to make these two datasets comparable. 

To make it more clear, would it make any differences if I just merge the datasets and compute the differential gene expression analysis or doing the data integration and computing the DEGs using RNA assay? Because to my understanding, all information from data integration would be saved in integrated assay. 

Thank you very much in advance.

**Comment by f6v** [comment]
> So, If I change the assay to "RNA", how we can trust that the DEGs are not due to the batch effects originated from the differences between two datasets, as the aim of integration is to make these two datasets comparable.

It has indeed been confusing. Nevertheless, many people used this approach in their publications. I think a systematic evaluation of this approach is yet to be done.

On the other hand, the authors have published an updated method recently. I'm in the middle of a [vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html) myself now. Hope it helps.

**Comment by rsatija** [comment]
It is not valid to perform DE on integrated values. The goal of integration is to align shared cell populations across datasets. The resulting DE genes from the RNA assay will indeed be driven by multiple factors, but performing DE on the integrated assay is not statistically valid.

**Comment by martuskaR** [comment]
@rsatija @Gesmira 

Thanks for all the work on Seurat!

In this vignette, https://satijalab.org/seurat/articles/integration_introduction.html#perform-integration-with-sctransform-normalized-datasets is PrepSCTFindMarkers(ifnb) done on SCT or integrated assay? 

In my data, I integrated SCT assay, so that now I have RNA, SCT and integrated assay. Just like in the vignette I have stimulated vs control cells that I want to perform DGE on. I used old (Seurat 4.3) integration of the SCT of the stimulated and unstimulated cells. Now that I successfully aligned them, how do perform DGE? if I do it on SCT, then its the same as if I didn't do integration since this has uncorrected data (cells cluster based on stim or unsitm state).  A the same time, I cannot do it on the integrated data (its not recommended, but also PrepSCTFindMarkers() doesn't work as now it is called 'integrated' and not 'SCT'). 

 I tried to assign clusters as stim and unstim and FindMarkers(), but doing this on SCT, led to markers being expressed evenly across heatmap. 
What would be the correct way of doing DGE in this case?

Any help will be much appreciated. 🙏🏻
