### ISSUE TITLE
Looking for suitable integration method

### ISSUE THREAD

**Issue by monaye745** [satijalab/seurat#5894]
Hi,

I am dealing a 10X data including totally 30 samples for six groups, I am wondering if there is any integration method that can keep the differences between different groups and eliminate the differences between different samples in the same group?

Thanks!

**Comment by WesDe** [comment]
Hi,
Not a developer from Seurat but there is not a clear answer even among the scientific community. If I summarize your need is to integrate all your data by removing batch effect but keeping biological state of each group. 

There is different kind of batch effect correction tools, you can use integration method from Seurat and check the clustering [Vignette](https://satijalab.org/seurat/articles/integration_introduction.html). If the batch effect remains, you can use a stronger batch effect correction tools or change the integration method. If the correction is too strong and you lose biological state information, you need to reduce the batch correction (i.e: using Harmony instead of Seurat method). It may be worth for you to check benchmark publication about batch effect correction to identify which tool may fit your needs or check other post related to integration on this github.

Nevertheless, (Seurat developers correct me if I am wrong) even if the biological state is removed during the clustering part, you may be able to identify potential marker genes by comparing gene expression between groups associated with the same cluster using FindMarker. 

Best,

**Comment by torkencz** [comment]
Thank you @WesDe, couldn't have answered it better myself.
