### ISSUE TITLE
Order of vinPlot

### ISSUE THREAD

**Issue by TM9013** [satijalab/seurat#5930]
Hi！ Thanks for providing this useful tool.

I want to display multiple gene expression by cell type in VinPlot.
How can I swap the celltype to be sorted? I am using the code below, but only the last "Cxcr4" is displayed in the order I want.
Thanks in advance.

VlnPlot(All, features=c("Bcl11a","Bcl11b","Ccr9","Cd34","Cd3e","Cd3g","Cd44","Cd82","Cebpa","Cxcr4"), pt.size=0,ncol=3,group.by="type")+
scale_x_discrete(limit=c("day0","day1","day2","day3","day4","day5","day7","day10"))

![image](https://user-images.githubusercontent.com/94793688/167298255-e9dd1e60-3340-4e33-b235-468c83c86d13.png)

**Comment by WesDe** [comment]
Hi, 

Not a developer from Seurat but your issue is more associated with ggplot2 display than Seurat.  There is a lot of ways to reorder discrete value, you can for example manually reorder the level by using All$celltype<-factor(All$celltype=c("day0","day1","day2","day3","day4","day5","day7","day10")) before performing your violing plot. You can find more solution on stakoverflow.

Best,

**Comment by samuel-marsh** [comment]
Hi,

So the issue you described is due to differences ggplot and patchwork packages.  Combined plots return patchwork objects.  So you just need to use `&` instead of `+`

```
VlnPlot(All, features=c("Bcl11a","Bcl11b","Ccr9","Cd34","Cd3e","Cd3g","Cd44","Cd82","Cebpa","Cxcr4"), pt.size=0,ncol=3,group.by="type") & 
scale_x_discrete(limit=c("day0","day1","day2","day3","day4","day5","day7","day10"))
```

I also agree with @WesDe it will make things easier to change the factor level directly prior to plotting so you don't have to repeatedly add the extra code.

```
# Create factor level order:
day_order <- c("day0","day1","day2","day3","day4","day5","day7","day10")

# If what you are changing is the current Ident of the object you can run:
Idents(OBJ) <- factor(x = Idents(OBJ), levels = day_order)

# If you are changing something in meta data slot then you can run
OBJ[["cell_type"]] <- factor(x = OBJ@meta.data$cell_type, levels = day_order)
```

Best,
Sam

**Comment by TM9013** [comment]
Thank you all！
It worked!!!

**Comment by samuel-marsh** [comment]
No problem!
