### ISSUE TITLE
slice comparision in spatial datasets

### ISSUE THREAD

**Issue by dzhaobio** [satijalab/seurat#5953]
I am analyzing the 10X spatial transcriptome data using Seurat. According to the [Seurat tutorial](https://satijalab.org/seurat/articles/spatial_vignette.html#working-with-multiple-slices-in-seurat-1), the SCTtransform should be applied to each dataset (slice) separately before merging them together. My question is whether the gene expression levels are comparable between slices. For example, we can draw a SpatialFeaturePlot of a particular gene to show its expression levels in different slices, but are they comparable across the slices?

It seems to me they are not comparable across slices because there is no between-slice normalization. However, I  notice that SCTransform is also used for [integrating different datasets](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html#perform-integration-using-pearson-residuals-1) and the datasets are SCTransform-ed before integration. After integration, the gene expression is comparable across datasets. Not sure if the datasets are re-normalized during the integration (IntegrateData).

I have no strong mathematical background to figure it out. Could you clarify whether the gene expression levels are comparable between slices in spatial data? Thanks!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
