### ISSUE TITLE
10x CellPlex Subsetting Issue

### ISSUE THREAD

**Issue by jglassbrook** [satijalab/seurat#5978]
Hi there, 

I'm having trouble subsetting a Seurat object with multiple assays attached. 

After I normalize the data, the Default assay is RNA.

I change the default assay to subset out the unused CMO tags used in the experiment, and something about that removes the RNA assay. Below I show that I can change the DefaultAssay between RNA and CMO, but after I subset things, I can't go back to RNA. 

Using a combination of the HTODemux vignette, the attached 10x document, and the standard workflow. My cobbled together script is also attached.

> DefaultAssay(S22_23_24_cells_filtered_CMO_norm)
[1] "RNA"
> DefaultAssay(S22_23_24_cells_filtered_CMO_norm)<-"CMO"
> DefaultAssay(S22_23_24_cells_filtered_CMO_norm)<-"RNA"
> DefaultAssay(S22_23_24_cells_filtered_CMO_norm)<-"CMO"
> S22_23_24_cells_filtered_CMO_norm_tags <- subset(S22_23_24_cells_filtered_CMO_norm, features = c("CMO310","CMO311", "CMO312"))
> S22_23_24_cells_filtered_CMO_norm_tags_nozeros = subset(x = S22_23_24_cells_filtered_CMO_norm_tags, subset = nCount_CMO > 0)
> DefaultAssay(S22_23_24_cells_filtered_CMO_norm_tags_nozeros)
[1] "CMO"
> DefaultAssay(S22_23_24_cells_filtered_CMO_norm_tags_nozeros)<-"RNA"
Error in `DefaultAssay<-.Seurat`(`*tmp*`, value = "RNA") :
  Cannot find assay RNA

[Tag assignment of CellPlex data using Seurat’s HTODemux function.pdf](https://github.com/satijalab/seurat/files/8735287/Tag.assignment.of.CellPlex.data.using.Seurat.s.HTODemux.function.pdf)

[debugging_script1.txt](https://github.com/satijalab/seurat/files/8735294/debugging_script1.txt)

**Comment by rsatija** [comment]
The issue here is that you are subsetting to only include features that are not present in the RNA assay. This removes the RNA assay entirely so you cannot switch back.

One solution that I believe should work would be to say

```
object_filtered = subset(object, features = c(rownames(object[["RNA"]]), c("CMO310","CMO311", "CMO312"))
```

Alternately, you can subset the specific features from the MultiPlex assay before creating the CMO assay. Hope that helps!

**Comment by shwetajohari** [comment]
Hello,
I am facing a similar error also tried the command but it didn't help. 
May I please know if this command helped? or did you do something else? 
Also, when did you put this command, before creating the CMO assay or after? 
Would it be possible to please see the script?

Thank you. 

Kind Regards,
Shweta Johari

**Comment by shwetajohari** [comment]
Hey 
Please do forgive me for the late response. Thank you so much. This ran successfully :) Thank you 
If you don't mind, got another question.
After this, is it possible to get the pattern like integrated data? 
Like how over here they have Ctrl vs STIM plotted as a  UMAP https://satijalab.org/seurat/articles/sctransform_v2_vignette.html 

Is there a way of getting a plot like that with CMOs?

Thank you so much.

Yours sincerely,
Shweta Johari

**Comment by apal6** [comment]
Hi, 

I demultiplxed my data and was looking at the expression of genes from two HTOs, HTO1 and HTO2. Both are expressing the genes at the same level and I am wondering if this is due to issue in demultiplexing? 
<img width="617" alt="Screenshot 2024-03-26 at 5 40 09 PM" src="https://github.com/satijalab/seurat/assets/127814354/7506d98a-ea91-4e79-a63c-9ddd166fd030">
<img width="590" alt="Screenshot 2024-03-26 at 5 42 46 PM" src="https://github.com/satijalab/seurat/assets/127814354/1ce29823-6ed3-482f-8f98-ac3be2473f5e">

Thank you so much!
Aastha
