### ISSUE TITLE
Making Seurat object from GEO dataset.

### ISSUE THREAD

**Issue by polespin** [satijalab/seurat#5979]
Hello 

I have a question about data export from GEO to seurat object.
I want to make GSE121861 dataset to seurat object file. (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE121861)

Usually I make seurat object using 3 files (barcodes, features, matrix) 
by Read10X(data.dir = "E:/Mouse_Singlecell_Public/eee")

But GSE121861 have only (coulmn, expression, row data) form.

How can I transform those files to seurat object? 

I really appreciate any answers.
Thank you.

**Comment by FernandaScar** [comment]
I'm not the best to answer this question, but I'm working with an only file from public data as well.
So, if the data is already in 10x you can just CreateSeuratObject from this file (the information about the barcodes and features has to be in this data).
Did you try to create a seurat object from the file directly?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So there are couple things to be aware of here.  As I mentioned on your other post you can create Seurat object from any data.frame/matrix as long as features are rows and cells are columns.

When you read in the expression file:
```
data <- data.table::fread("~/Downloads/GSE121861_syngeneic_expression.csv.gz", data.table = F)
```
you find that there are no column or row names.

The rownames can be found in this other provided file:
```
rows <- data.table::fread("~/Downloads/GSE121861_syngeneic_row_data.csv.gz")
```

However, the authors apparently did the analysis using the ensembl IDs as there are duplicate gene symbols so you will need to use those when creating object.

Next you'll realize with the number of features provided that the expression matrix needs to be transposed:
```
data_transposed <- data.frame(t(x = data))
```

Then you can add feature names and create object:
```
rownames(data_transposed) <- rows$ENSMUSG_ID

seurat <- CreateSeuratObject(data_transposed)
```

One final note though is that the authors appear to have provided some sort of normalized data and not raw counts as there are decimals in the expression matrix.  Hopefully they have provided this information on GEO or in manuscript so that you know what was performed and so that you know not to run normalization again since data is already normalized.

Best,
Sam

**Comment by FernandaScar** [comment]
Hi Sam!

I'm having an similar issue trying to create an analysis from a public data. Could you look it up for me? It would be very helpful!

https://github.com/satijalab/seurat/discussions/5982

Thank you anyway!!

**Comment by samuel-marsh** [comment]
@FernandaScar will take look at yours and respond there.

**Comment by hannhat1998** [comment]
Hi, I faced the same problem. I'm not sure if you were able to get it run. If you were, could you show me please?

**Comment by carlottamp** [comment]
Hi, I also want to make a Seurat Object from the CITE-Seq data (GSE185381) (link: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE185381). Would you be able to help?
