### ISSUE TITLE
Command log overwritten for RunTSNE and FindClusters

### ISSUE THREAD

**Issue by kverstae** [satijalab/seurat#5983]
Hi,

We would like to use the `commands` slot of the Seurat object to keep track of all the parameters used for the different steps during the analysis.
Since we have multi-modal data (cDNA + antibody data), we run (parts of) the Seurat pipeline for both modalities.
One of these steps is `FindClusters`, which we use to both cluster the data on the gene expression data and the antibody data separately. On the second run of `FindClusters`, the first entry in the command log is overwritten:
```
FindClusters(seuratObj, graph.name = "RNA_snn", resolution = 0.6)
FindClusters(seuratObj, graph.name = "ADT_snn", resolution = 0.8)
names(seuratObj@commands) # Only includes FindClusters once with the parameters of the last run
```
Would it be possible to add the graph.name parameter in the command log so we can keep track of all the different `FindCluster` runs?

A similar story for `RunTSNE`. This also overwrites and only keeps the results of the last run. I expect this to behave the same as `RunUMAP` which creates command logs with following key format: `RunUMAP.<ASSAY>.<REDUCTION>`

**Comment by wuyinbuquan97** [comment]
I wanted to ask if you solved this problem because I was also looping this command but it was overwritten
seq <- seq(0.1, 1, by = 0.1)
for(res in seq){
  PBMC1 <- FindClusters(PBMC1, modularity.fxn = 2,resolution = res)
}

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
