### ISSUE TITLE
Doheatmap plot is obscure

### ISSUE THREAD

**Issue by qjcatherine** [satijalab/seurat#5996]
Hi,
I have processed the SCT-integration-cluster-subset and get the subset of stromal cells. I used SCT_CCA reintegration and resubcluster stromal cells. When I want to FindAllMarkers() in different subclusters, and do heatmap, there comes two problems:
1)the heatmap could not show in the preview window.
2)when using ggsave to save the heatmap plot and open to view it, it seems obscure like the picture below. 

When I used the same code for pbmc, nothing went wrong. 

So where is the problems?

Thanks alot!
![b6e2c0ef21156d543b9402c4276dcb6](https://user-images.githubusercontent.com/79858784/170061664-5317e92a-b865-4068-a5b6-26d2b9542b80.png)

**Comment by coffeeCowLu** [comment]
It happened to me, too. How did you solve it? Thank you

**Comment by coffeeCowLu** [comment]
When saved as PDF, I also encountered, how do you solve? Thank you

**Comment by qjcatherine** [comment]
I think it might be caused by the data we used is not very good. You can check whether batch effect is exist in ur data.

Or I can reopen the issue and wait for the developing group to address.

**Comment by coffeeCowLu** [comment]
It's not easy to explain why, but the color bars are clear when saved in PNG format, just as they are blurred when saved in PDF format. If it is a data problem, both PNG and PDF images should be blurred. You can reopen the issue and wait for a solution from the developer.

**Comment by samuel-marsh** [comment]
Hi,

Not member of the dev team but hopefully can be helpful.  What application are you using to open the PDF after saving it?  There is known issue (documented in the manual entry for DoHeatmap) where certain PDF viewers may display the plots like this due to how the plot raster is interpolated.  For instance here is the same plot opened side-by-side in Adobe vs. Preview:

![image](https://user-images.githubusercontent.com/38284410/170500891-68661b96-e3f8-462f-870c-ed7b5faa2cc5.png)

By default `DoHeatmap` sets raster = TRUE to speed up plotting and reduce file sizes.  You can always set `raster = FALSE` but depending on the number of genes and number of cells you are plotting the plot can take long time to make/render.

Best,
Sam

**Comment by coffeeCowLu** [comment]
> 
Thank you very much for your reply.

**Comment by coffeeCowLu** [comment]
> 

raster
If true, plot with geom_raster, else use geom_tile. geom_raster may look blurry on some viewing applications such as Preview due to how the raster is interpolated. Set this to FALSE if you are encountering that issue.

**Comment by samuel-marsh** [comment]
Yep!  Either set to false or you can use different application to open the files if that solves the issue.  If later works that's probably easier solution because that will still allow for faster plotting and smaller file sizes.

Best,
Sam
