### ISSUE TITLE
Merge function for 500,000+ cells says "problem too large"

### ISSUE THREAD

**Issue by claudiafeng123** [satijalab/seurat#6019]
Hi! I'm trying to merge 144 Seurat Objects (each from a single 10X inlet) using the merge() function. I have expression counts for 720,000 cells across about 6,000 genes.

I get the following error: 

Error in .cbind2Csp(x, y) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: merge ... cbind -> cbind2 -> cbind2 -> cbind2sparse -> .cbind2Csp
Execution halted

The code seems to work for a subset of the data. Do you know what might be going wrong? I seem to have requested enough memory.

    Max Memory :                                 325447 MB
    Average Memory :                             197939.80 MB
    Total Requested Memory :                     500000.00 MB
    Delta Memory :                               174553.00 MB

**Comment by yuhanH** [comment]
Hi, @claudiafeng123 
How many non-zero elements in all your objects?
Because the R sparse matrix and RCPP limits the non-zero elements to (2**31 - 1), if the number of non-zero elements in your object is above this, you cannot generate the merged object now.  We are working on a new data infrastructure to support this. 
Also,  you can have a look at our [atomic sketching vignette](https://satijalab.org/seurat/articles/atomic_integration.html). We sampled the representative cells from the  each object respectively and those representative cells can be used to explore the data or integrate all cells.
