### ISSUE TITLE
Multiple Spatial data analysis

### ISSUE THREAD

**Issue by mimisikai** [satijalab/seurat#6020]
I have several spatial data, one for each sample. In order to analyze them together, I wonder by which order I handle them is appropriate.

1. Load10X_Spatial for for each
2. SCTransform for each
3. merge all
4. Sample integration by SelectIntegrationFeatures + PrepSCTIntegration + FindIntegrationAnchors + IntegrateData
5. RunNMF/RunPCA

Or swap 2 and 3? 

And would you please little bit explain the difference of running NMF and PCA for reduction? Some clusters in my data seem reasonable after running NMF rather than run PCA. 

Thanks.

**Comment by longmanz** [comment]
Hi, 
A standard procedure would be run SCTransform (2) first and then merge them together. This is because SCT is mainly used to remove technical variation specific to each dataset. 
As for NMF v.s. PCA, these 2 methods aim to solve different questions. In your case, you mentioned that your NMF clusters seem more reasonable than those from PCA. Due to the non-negativity constraint, NMF components are often easier to interpret than PCA components, as they appear to be "module" more often than PCA. Thus, it really depend on the question you have and what you want to solve.
