### ISSUE TITLE
NormalizeData not giving values between 0 and 1

### ISSUE THREAD

**Issue by aminerva** [satijalab/seurat#6071]
I have normalized my raw counts using the NormalizeData() function with the defaults normalization.method = "LogNormalize" and scale.factor = 10000. When I look at raw counts, I have continuous values >=0. However, after normalization, expression is bimodal (see below for one example gene). I expect to see a large number of nuclei with expression levels at 0 and then some with higher expression levels, but why are there no values between 0 and 1? 

Thanks!

![Unknown-2](https://user-images.githubusercontent.com/55995342/173383724-2792b28e-2898-49cd-93dc-b8ab8b5ce622.png)

**Comment by longmanz** [comment]
Hi @aminerva,
Since you are using LogNormalize in ScaleData(), we might see this if the total count of all the cells is not big enough. By definition, LogNormalize means "Feature counts for each cell (x) are divided by the total counts (y) for that cell and multiplied by the scale factor, then gets natural-log transformed with log1p()". 
So if the total counts of all your cells are small and the gene counts are big (e.g., x/y*10000 + 1 < exp(1) ), you might end up with no value between 0 and 1. You can easily confirm this by using a smaller scale.factor (e.g., 1000 or 100), which will lead to values between 0 and 1. 

Longda
