### ISSUE TITLE
Benchmarking regression of cell cycle effect

### ISSUE THREAD

**Issue by Spidrre** [satijalab/seurat#6073]
Hi! I have been looking through your vignette for Removing Cell Cycle Effect (https://satijalab.org/seurat/articles/cell_cycle_vignette.html)
Need to note that I am still a newcomer in area of bioinformatics.
As far as I understand, features could be regressed out by applying SclaData() function for our dataset. We can use linear, poisson or negative binomial regression models in this function.
I have a question - is there any way to benchmark (or evaluate, sorry, not sure how to translate this word in English) regression?
How to get MSE, RMSE, MAE or R-squared values for our results?

**Comment by longmanz** [comment]
Hi @Spidrre,
Unfortunately, we cannot get the MSE/r^2 from ScaleDate(, vars.to.regress = ...) itself, because the r^2s are not saved during the process. For each gene, only the residual is extracted and saved. 
If you really want to obtain this, you will need to explicitly run lm/poisson/nb for each gene. The built-in functions for lm/poisson/nb in ScaleDate() are exactly the standard R functions (i.e., lm(), glm(family = 'poisson'), and glm.nb() ), so you may just run lm/glm for all the genes of interest and extract the r^2/MSE from the standard lm/glm output.  
Best,
Longda
