### ISSUE TITLE
Looping through the markers

### ISSUE THREAD

**Issue by stacygenovese** [satijalab/seurat#6086]
I have successfully integrated my data and have cycled through each cluster finding the top gene in each. I saved these in a list.  I now want to cycle through the list renaming the Idents but the code I have isn't working:
```
for (i in 1:length(top_genes[[1]])){
  gene.conditions <- RenameIdents(gene.conditions, 
                                      as.character(i-1) = top_genes[[i]]
}
```

The problem has to do with as.character(i-1).  Any idea how to cycle through the clusters and apply the genes stored in top_genes to each Ident?

This group is great - I can't thank everyone for all the help,
Stacy

**Comment by longmanz** [comment]
Hi @stacygenovese ,
It seems that you want to rename each cluster ID to its corresponding top gene. You might need to use 
`for (i in 1:length(top_genes)){...}` 
on your first line. 

Best,
Longda

**Comment by stacygenovese** [comment]
Longda,

Thanks but that's not the issue.  The error I'm getting says ' unexpected = ' in RenameIdents.  But when I put in '0' it works.  I'm not using the correct syntax to convert the i to the character that the function is looking for.  Any ideas on how to fix that?
Stacy

**Comment by longmanz** [comment]
Hi @stacygenovese,
Thanks, I see what the problem is now. You cannot use a variable in the (...) to assign new Ident IDs. 
There is a workaround, however, by using named vector (without for loop). You might do something like this:
`new.cluster.ids = unlist(top_genes)`
`names(new.cluster.ids) = levels(gene.conditions)`
`gene.conditions = RenameIdents(gene.conditions, new.cluster.ids)`
You can refer to this similar thread https://github.com/satijalab/seurat/issues/2580 for more information. 
Longda

**Comment by stacygenovese** [comment]
I think I got it working with:
```
names(new_cluster_ids) = as.character(sort(as.numeric(levels(gene.conditions))))
```
