### ISSUE TITLE
Re-normalizing/Scaling Subset

### ISSUE THREAD

**Issue by smallkamal** [satijalab/seurat#6115]
My dataset contains different cell types. After I subset out a cell type, do I need to re-normalize and re-scale the data, or do I just need to run PCA/UMAP and plot the cells on a new graph?

**Comment by giorgiatosoni** [comment]
Hi, 

In this vignette (https://satijalab.org/seurat/archive/v3.0/interaction_vignette.html) they recommend:

# note that if you wish to perform additional rounds of clustering after subsetting we recommend
# re-running FindVariableFeatures() and ScaleData()

Best,

Giorgia

**Comment by xjin15** [comment]
If i used the _SCTransform()_ procedure before subset out a cell type, what should i do to rescale the subsetted data?

**Comment by mhkowalski** [comment]
Hi, 

You don't necessarily need to re-normalize and re-scale the data, but you can try re-running ```SCTransform()``` on the subsetted data again to focus on features that are variable in your cell type.

**Comment by denvercal1234GitHub** [comment]
Hi @mhkowalski -- When you say "don't neccessarily", does that imply that if you want to cluster the subsetted cells, you should not redo SCTransform(do.scale=**T**, do.center=**T**)? Instead, you should redo SCTransform(do.scale=FALSE, do.center=TRUE) to identify the variable features of the subsetted cells?

**Comment by hartmannmark** [comment]
> In this vignette (https://satijalab.org/seurat/archive/v3.0/interaction_vignette.html) they recommend:
> 
> _note that if you wish to perform additional rounds of clustering after subsetting we recommend re-running FindVariableFeatures() and ScaleData()_

Hi All,
I did this but it does not make any change, which feels weird to me...
In detail, I subsetted my dataset `B` and re-called the variable genes:
`FindVariableFeatures(
  B, selection.method = "vst", 
  nfeatures = 2000)`

When I compare the result, it is identical:
`B.top100.01 <- head(x=VariableFeatures(object=B),100) 
B.top100.02 <- head(x=VariableFeatures(object=B),100) 
identical(B.top100.01, B.top100.02)
[1] TRUE
`

Since I subsetted the B-cell lineage from an entire hematopoiesis dataset, I can not imagine that the variable features should remain the same.

Would be happy to read any thoughts on this?
