### ISSUE TITLE
Displaying multiple Prodection of cell types on a Visium slide

### ISSUE THREAD

**Issue by moutazhelal** [satijalab/seurat#6148]
Dear Authors,
Thank you for considering my request.

I was working on a spatial transcriptomics data generated using Visium. I performed cell type predictions using a scRNA data. I was wondering if it possible to show multiple cell types prediction scores on the same spatial plot each with a different color. Cell2location offer such visualization method.

Thanks a lot,
Best,
Moutaz

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
