### ISSUE TITLE
C stack usage ... is too close to the limit when running RunTSNE

### ISSUE THREAD

**Issue by eridona** [satijalab/seurat#6158]
I am getting an error when trying to run RunTSNE on a dataset of ~400k cells.

R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit) - allocated memory: 600Gb
Running under: Scientific Linux 7.8 (Nitrogen)
Seurat_4.0.5

The error says:
C stack usage 992245842996 is too close to the limit 

When running the same command againand again I get the same error, but with different numbers. I have checked the ulimit of my system and it is set to unlimited. 
The same command works with smaller datasets (eg. 300k cells).

Do you have any suggestions?

Thank you,
Erika

**Comment by scachero** [comment]
Hello, I am having the same issue.

Please let me know if there is a fix!

Thanks

Sebastian

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
