### ISSUE TITLE
AddModuleScore meaning?

### ISSUE THREAD

**Issue by giorgiatosoni** [satijalab/seurat#6174]
Hi,

I am using the `AddModuleScore()` function on different published datasets to look for the presence of cells of interest, by entering as "features" a list of genes of interest. 

As far as I understood, I shouldn't be comparing the module score values obtained from different datasets because this score is relative to the datasets. For some datasets, I get module scores up to 100, while for others up to 1, using the same list of genes, when using `FeaturePlot` to visualize the results.
See the example in the picture: 2 different datasets (ncells = 150K and 200K), same features used for module score.

I was wondering if these differences among datasets mean that some datasets contain less of my cells of interest (eg module score up to 1 vs module score up to 100) or can be something technical eg relative to the number of total cells in the datasets, the numbers of clusters...

Hope this is clear and thanks in advance!

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/94447264/178439617-6aa3c7c7-cdad-46e6-bb26-858a0f624471.png"> 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/94447264/178439727-f2cf8f08-2836-48c2-99a7-ef1d9bd64ef4.png">

**Comment by mhkowalski** [comment]
Hi, 

Comparing module scores calculated on different data sets may be difficult to do, because AddModuleScore uses a randomly selected set of control features based on the expression levels of your input features. Therefore, module scores might differ based on what control features are used, the technology, or the composition of cell types within that sample. 

If you'd like to compare the module score directly, I would recommend running them in a merged seurat object, which will guarantee a consistent set of background features is used (but again, if there are substantial differences between datasets, this might not be accurate).

**Comment by denvercal1234GitHub** [comment]
Hi @mhkowalski - Would integrating the datasets instead of merging them, then compare the Module Score calculated from cells of dataset A within the integrated object vs Score calculated from cells of dataset B work? Thank you.
