### ISSUE TITLE
Bug(s) in SpatialDimPlot

### ISSUE THREAD

**Issue by mvhunter1** [satijalab/seurat#6179]
Hi Seurat team,
Thank you so much for your service to the community. 
Similar to previous issue #5975 I am unable to use SpatialDimPlot or SpatialPlot with group.by after upgrading to Seurat 4.1.1. The plots appear as unlabeled points no matter which metadata column is used to group the data. 
![Screen Shot 2022-07-12 at 5 30 18 PM](https://user-images.githubusercontent.com/57913498/178598852-d8f1c318-c2fa-461d-b438-200cadbdf055.png)
These are critical functions for plotting any type of spatial data so a bug fix would really be appreciated :) Thank you!

**Comment by lengjing0519** [comment]
me too! If there is any solution, please let me know

**Comment by yoda-vid** [comment]
I've encountered this as well in v4.1.1, while it worked in v4.1.0. It appears to bisect to commit 4024b0c38a8a4009d4889de145385e5b10e7adba, where the addition of `cols <- cols[names(x = cols) %in% data$ident]` appears to filter out the colors when grouping by something other than `ident`.

The workaround for me was just to comment out this line. I also tried replacing `data$ident` with `data[[col.by]]`, but `col.by` gets surrounded by backticks and doesn't appear to work here.

**Comment by sciencepeak** [comment]
Hi, I have updated my Seurat to 4.3.0, however, the `SpatialDimPlot(..., col = colors)` still produce **the error** of `Insufficient values in manual scale. 12 needed but only 0 provided`, which is similar to the previous [issue](https://github.com/satijalab/seurat/issues/5975
).

Luckily, I found a suggestion [here](https://github.com/satijalab/seurat/discussions/6083#discussioncomment-2962200). The suggestion fixes **the error**.  My version of the solution is like this:

```r
numCluster <- my_seurat_object@meta.data$seurat_clusters %>% unique %>% length
colors = Seurat::DiscretePalette(n = numCluster, palette = "alphabet2")
Idents(my_seurat_object) # should be seurat clusters.
# The colors, which is a character vector of different color codes, need the names for the vector.
names(colors) <- Idents(my_seurat_object) %>% unique

the_ggplot_list <- SpatialDimPlot(
    my_seurat_object,
    images = "my_image_name",
    group.by = c("seurat_clusters"),
    pt.size.factor = 1.15,
    label = TRUE,
    label.size = 6,
    repel = TRUE,
    combine = FALSE,
    cols = colors
)
print(the_ggplot_list)
```

If **the error** could be further investigated by the devolopers, that would be terrific. Otherwise, it would be helpful that the document of `SpatialDimPlot(..., col = colors)`  have more explanation, which should not be hard.

Thank you very much for your contribution to the science community.

**Comment by chengwenxuan1997** [comment]
I have an alternative trick here, it seems that the SpatialDimPlot still works on the Idents of the Seurat object.
```r
Idents(ST.seu) <- ST.seu$group
SpatialDimPlot(ST.seu)
```

**Comment by sciencepeak** [comment]
> 
It's glad to know that SpatialDimPlot works on the Idents of the Seurat object again.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
