### ISSUE TITLE
Doheatmap to max color at 95th percentile? 

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6200]
Hello. Do you have any recommendations how to plot DoHeatmap() while setting max color at 95th percentile? This is to avoid "overvisualizing" outlier/s. Thank you.

**Comment by levinhein** [comment]
I calculated AverageExpression(). As you can see here, TYROBP is high on second to the last group but it is only represented by few cells. And, the first and second group have high expression too. 

![image](https://user-images.githubusercontent.com/68268222/179353528-fc10e56c-2535-440e-90f7-c07866387532.png)

BUT, on a DoHeatmap, TYROBP visualization on blue group is kind of outlier, making the other groups virtually non-expressing. The colors in the first and second group, which we definitely expect to be high, are dark, suggesting non-expression/low average expression.    

I wonder if there is any way to solve this like by having a max cutoff (like in FeaturePlot)?

![image](https://user-images.githubusercontent.com/68268222/179353467-239b8e11-d31f-4f49-a34d-c2a938eb5cf8.png)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I think issue you are seeing has to do more with what heatmap visualization is.  You are viewing the average expression per cluster and then you have to remember that heatmap is scaled data.  You also have to remember that with default settings you can think of the color scale as relative and not high expression vs no expression.  The purple color doesn’t mean no expression but that the average expression relative to other groups is lower.  This is due to the considerable number of cells that have no expression of gene in first two groups vs all cells expression the gene in the last two groups.  I would suggest that either plotting heatmap per cell or using another visualization technique may be more optimal here as I’m not sure a 95th cutoff would actually solve the issue you are describing.

Best,
Sam

**Comment by torkencz** [comment]
I agree with @samuel-marsh.
