### ISSUE TITLE
Problem with loading in Vizgen data

### ISSUE THREAD

**Issue by PoolLab** [satijalab/seurat#6226]
I am following the spatial transcriptomics vignette to analyze sample Vizgen data: https://satijalab.org/seurat/articles/spatial_vignette_2.html . Although I've downloaded the same dataset and am following the tutorial verbatim, I am getting issues with loading in the spatial dataset. Namely, I am getting two distinct warning messages upon running LoadVizgen: vizgen.obj <- LoadVizgen(data.dir = "<path_to_folder>/s2r1/", fov = "s2r1")

* Warning in ReadVizgen(data.dir = data.dir, filter = "^Blank-", type = c("centroids",  :  80223 cells missing polygon information
* In ...future.FUN(...future.X_jj, ...) : Cannot find HDF5 file for field of view 22 (multiples of this warning with different view #)

I do have all the hdf5 files in the "cell_boundaries" subfolder and it appears that a small subset of those does get read in. 
I have reproduced this on two different workstations but unfortunately have not been able to resolve it. Thank you in advance!

**Comment by AustinHartman** [comment]
Hi, thanks for raising this. Could you post your sessionInfo()? Normally, there are a couple 100 cells for which there is no polygon information available likely because polygon information is read from a single Z-stack and those cells segmentations could be hiding somewhere else in the Z-stack. 80,000 cells however is nearly the whole dataset which makes me wonder if cells could have been named incorrectly leading to minimal barcode/cell name overlap.

For the second issue, I am not certain how Vizgen's processing works but I think certain files are missing from the cell_boundaries directory because there were no cells segmented in that FOV. In the screenshot below you can see it's lots of the first FOVs (0-21) and final FOVs  (1300s) which probably tile the edge of the slide lacking any tissue with cells to segment
<img width="1437" alt="Screen Shot 2022-08-01 at 12 28 13 PM" src="https://user-images.githubusercontent.com/8409657/182198003-6e9b96e4-9f03-414a-921e-27309ccfff41.png">

**Comment by PoolLab** [comment]
Thank you for the quick and helpful reply! As you suggested, the relevant cell boundaries data was missing due to an entertaining mistake. As gsutil function issue prevented me from downloading the entire folder, I resorted to manually downloading the hdf5 files and did not realize that there are multiple pages of these files on google cloud. After troubleshooting gsutil folder download, everything worked as intended. Thank you again - this issue can be closed.
