### ISSUE TITLE
labeling on spatial plot

### ISSUE THREAD

**Issue by andynkili** [satijalab/seurat#6245]
Dear developers,

Thank you so much for keeping this great tool up to new technology!
I followed your [vignette](https://satijalab.org/seurat/articles/spatial_vignette_2.html) regarding the imaged-based spatial data analysis with the vizgen dataset.
Sometime it can be difficult to tell apart clusters as there is no labeling (on ImageFeaturePlot or ImageDimPlot). Of course, we can  still plot specific cells but it would be nice to have something the label on the spatial plots (like the 10x Visium vignette):
![dim plots-1](https://user-images.githubusercontent.com/49782275/181511364-8af1f05f-da35-40ce-917f-d0d261143f13.png)

Also:
`ImageDimPlot(vizgen.obj, fov = "test", axes = TRUE, border.color = "white",size = 2, border.size = 0.1, molecules = c("Chrm1", "Slc17a7", "Htr4"), mols.cols = c('blue','green', 'red'),mols.size = 1,cols = "polychrome", coord.fixed = FALSE, overlap = F)`
![Rplot01](https://user-images.githubusercontent.com/49782275/181512351-676cc5df-d2bb-4e61-b4a0-f4825a1d0eb5.png)
As it can be challenging to distinguish clusters when highlighting molecules, coloring borders by clusters may help.

Best,
Andy

**Comment by AustinHartman** [comment]
thanks for the suggestion - I agree this would be useful and I will update the issue once it's added. For the second point, it might be useful to plot the segmentations instead of points. Also, maybe you could make the cell points a bit larger and set the border.size as NULL or 0 to get the desired viz

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
