### ISSUE TITLE
DEenrichRPlot returning "missing value where TRUE/FALSE needed" error

### ISSUE THREAD

**Issue by jtoker** [satijalab/seurat#6283]
Hello,

I've been trying to run the DEenrichRPlot function on my Seurat object using the following lines of code:

```r
Idents(pbmc_small) <- "groups"
DEenrichRPlot(pbmc_small, ident.1 = "g1", ident.2 = "g2", enrich.database = "MSigDB_Hallmark_2020", max.genes = 100, return.gene.list = T)
```

This returns the following:

  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  
Uploading data to Enrichr... Done.
  Querying MSigDB_Hallmark_2020... Done.
Parsing results... Done.
Uploading data to Enrichr... Error in if (is.vector(genes) & !all(genes == "") & length(genes) != 0) { : 
  missing value where TRUE/FALSE needed

My sessionInfo() information: 
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.5.2

Please advise. Thanks so much

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
