### ISSUE TITLE
Read10X() not able to read genes.tsv.gz file

### ISSUE THREAD

**Issue by mariamnawaz1** [satijalab/seurat#6289]
I am reading a sample (directory) containing the following files:
**barcodes.tsv.gz  genes.tsv.gz  matrix.mtx.gz**

using **Read10X(data.dir = directoryPath)**, but following is the error I am getting:

**Error in Read10X(data.dir = directoryPath) : 
  Gene name or features file missing. Expecting features.tsv.gz**

Do I need to change the name of genes.tsv.gz to features.tsv.gz? The [documentation ](https://satijalab.org/seurat/reference/read10x) says it should be able to read both.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So I believe the issue is that in earlier versions of Cell Ranger that output the “genes.tsv” file the outputs weren’t zipped so `Read10X` is looking for file name that doesn’t contain the .gz.  You should be able to solve it by unzipping the files before reading them in.

Best,
Sam
