### ISSUE TITLE
How to interpret DEGs found by FindMarkers() with vs without setting latent.vars="donor_ID"?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6302]
Hi there, 

I performed `(A) FindAllMarkers(test.use = "wilcox")`. 

I then ran using the same Seurat object `(B) FindAllMarkers(now setting assay = "SCT", only.pos = F, recorrect_umi = FALSE, test.use="MAST", latent.vars="donor_ID")`. 

(B) gave me genes that were not identified by (A). Does it mean these genes are consistently differentially expressed for this cluster across all donors? 

I am unclear how I should interpret the difference in the list of returned DEGs using these 2 approaches (paying attention to the confounding effect of donor variability.

Thank you for your help!

**Comment by longmanz** [comment]
Hi @denvercal1234GitHub,
I will share some of my naive understanding about A and B.

In (A), the Wilcox rank test does not incorporate any donor information. It is technically similar to a T.test by comparing the mean expression values of a gene between two groups and see if there is a significant mean difference. It is an efficient, and conserved (well controlled false positive rate) test. However, it does have some downfalls. For example, if there are multiple samples in your data as a case/control design, and the number of cells contributed by diff samples are disproportional, bias could arise. Imagine a sample in your dataset contributes ~80% of the cells in your case group, and for some unknown artifacts, it has elevated expression levels for some genes, and these genes are not elevated in other samples in your case group, then Wilcos will still falsely identify these genes as DEGs, because the cells in your case group is dominated by this single sample.

In (B), since MAST DE test can model donor_ID, it will be able to mitigate such issue. The MAST test will identify the DEGs that are consistently elevated/down-regulated across all the samples in your case group. As for sample-specific "DEGs", they will be captured by the Donor_ID term in the MAST model. So personally, MAST model might provide a more stringent list of DEGs than Wilcox test.
