### ISSUE TITLE
Memory allocation estimation for FindIntegrationAnchors() and FindTransferAnchors()

### ISSUE THREAD

**Issue by mhugaboom** [satijalab/seurat#6315]
Hello,

Is there a way to estimate the memory required to identify anchors between reference objects and/or between an integrated reference and query object based on the size of the input objects? For example, I am currently trying to run FindTransferAnchors() using a reference object of 22GB and a query object of 5.8GB and would like to be able to approximate how much memory I'll need to do so. 

Thank you!

**Comment by timoast** [comment]
It's difficult to provide an estimate since the amount of memory needed will be influenced by several things, including number of cells, number of features used, dimension reduction method use, number of dimensions used, etc.

All I can suggest is trying the integration with a high amount of allocated memory and record what the peak memory usage was, then use that as a guide for allocating memory for other similar jobs
