### ISSUE TITLE
Average expression color gradient legend missing from DotPlot when using split.by argument

### ISSUE THREAD

**Issue by JE001** [satijalab/seurat#6320]
Hello. I know this has been asked before, but I am trying to create a dot plot showing gene expression of selected genes in the various seurat_clusters of my seurat object. The idents is set to "seurat_clusters", and I want to split each cluster by another variable, "subset." I can successfully create a dot plot with the dots colored in two separate colors depending on what "subset" they belong to, but their are no "Average Expression" legends, which usually appear when the split.by argument is not being used. Is there a way to add the legends back? Alternatively, I thought I could also create two separate dot plots for each subset just to generate the legends, which I can then cut and past onto the original plot. However, when I tried this the colors did not seem to match exactly. What is the default color used for the minimum color in the dot plot when split.by is used? Thank you for your help.

[DP_SP_Dotplot.pdf](https://github.com/satijalab/seurat/files/9376976/DP_SP_Dotplot.pdf)

**Comment by longmanz** [comment]
Hi,
Sorry for not responding earlier. This is indeed an issue with DotPlot(), because once the "split.by = " is being set, the DotPlot will actually use discrete colors to generate the plot, and a continuous color scale is not applicable. 
While this can be fixed from our end, it might take some time. As a workaround (for DotPlot specifically), you can generate a new Ident for your seurat object based on your original Ident + the "split.by = " column, so that you will have the same DotPlot as with "split.by = ", but with color scale legend. 
Here is an example:
```
### this one generates the DotPlot without color scale.
DotPlot(object = pbmc_small, features = cd_genes, split.by = "groups")

### this one generates a new Ident column you can use based on the original Ident + the split.by above
pbmc_small$new_split_group = paste0(Idents(pbmc_small), "_", pbmc_small$groups)
# this Dotplot should now have color scale. 
DotPlot(object = pbmc_small, features = cd_genes, group.by = "new_split_group")
```
