### ISSUE TITLE
Percentage of cells expressing a gene and Pct.1 in FindMarkers

### ISSUE THREAD

**Issue by Dexiao211** [satijalab/seurat#6322]
Hi Seurat team,
Thanks for developing this useful package.
I use a a small script ( wrote by Dr. Zhu) to count percentage of cells expressing a gene:

**_PrctCellExpringGene <- function(object, genes, group.by = "all"){
  if(group.by == "all"){
    prct = unlist(lapply(genes,calc_helper, object=object))
    result = data.frame(Markers = genes, Cell_proportion = prct)
    return(result)
  }
  
  else{        
    list = SplitObject(object, group.by)
    factors = names(list)
    
    results = lapply(list, PrctCellExpringGene, genes=genes)
    for(i in 1:length(factors)){
      results[[i]]$Feature = factors[i]
    }
    combined = do.call("rbind", results)
    return(combined)
  }
}

calc_helper <- function(object,genes){
  counts = object[['RNA']]@counts
  ncells = ncol(counts)
  if(genes %in% row.names(counts)){
    sum(counts[genes,]>0)/ncells
  }else{return(NA)}
}**_

I use this script to count percentage of cells expressing a gene in three groups (group 1, group 2 and group 3), and these groups are used as ident.1 in FindMarkers. However, the average value doesn't equal Pct.1 value. Can you tell me the possible reason? And which assay should I use to count number or percentage? RNA assay? Thanks.

**Comment by longmanz** [comment]
Hi, 
When Seurat is calculating the pct, by default it uses the 'data' slot in your selected assay 'RNA' (e.g., obj[['RNA']]@data). Please make sure you set your DefaultAssay() to 'RNA'. 
In addition, you mentioned that the average of you self-calculated pct of (group 1, group 2 and group 3) is not equal to Seurat's Pct.1 value. Since the number of cells in each of (group 1, group 2 and group 3) is different, the 2 numbers are not expected to be equal. You might need to directly calculate  the pct of all cells from (group 1, group 2 and group 3) together, and then check if it is equal to Seurat's pct.
