### ISSUE TITLE
There is a bug in using harmony. I can't solve it after spending a lot of time.

### ISSUE THREAD

**Issue by MaJiakang** [satijalab/seurat#6343]
system.time({sce_Macrophage <- RunHarmony(sce_Macrophage, group.by.vars = "orig.ident")})
![image](https://user-images.githubusercontent.com/110780219/186570733-acdd5a52-d734-412c-9c4f-f49c13aaaf8d.png)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The `RunHarmony` function isn't actually part of Seurat but the Harmony package (https://github.com/immunogenomics/harmony).  I would suggest posting your issue their so the devs of that package can assist you.  

As suggestion so that they can best help you I would post your full code and not a screenshot so they can understand what code you ran and where the error might be coming from.

Good luck!

Best,
Sam

**Comment by MaJiakang** [comment]
Thank you for your valuable comments.
