### ISSUE TITLE
Error in asMethod(object) :    dense_to_Csparse(<LARGE>): cholmod_l_dense_to_sparse failure status=-4

### ISSUE THREAD

**Issue by zqw1103** [satijalab/seurat#6353]
HI, 

I imputed Seurat object with MAGIC and using assay = 'MAGIC_RNA' as the input into FindVariableFeatures() function and got such error. If you could help cipher that this error means and possible causes? Here is the code you could help refer to:

#Normalize data
sce.all.filt <- NormalizeData(sce.all.filt)
sce.all.filt.imputed <- magic(sce.all.filt, n.jobs = 24)

sce.all.filt.imputed <- FindVariableFeatures(sce.all.filt.imputed, assay = 'MAGIC_RNA')

Thank you!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
