### ISSUE TITLE
How to change legend point size in DoHeatmap?

### ISSUE THREAD

**Issue by tomerweiss9** [satijalab/seurat#6356]
Hi there,
How can I adjust the legend point size?
I tried to access legend aesthetic via 'guides', but was not successfull. 

Hope you can help with this one
Thanks!

**Comment by zqw1103** [comment]
Somehow I think needs customized functions based on average expression to control size of point

**Comment by tomerweiss9** [comment]
I do not see any relation between average expression and legend point size..

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.

**Comment by 14zac2** [comment]
Hi - I am also encountering this problem. I am trying to use `guides(color = guide_legend(override.aes = list(size=5)))` to increase the legend point size but it's not working. I would love some advice!
