### ISSUE TITLE
Error in function "MULTIseqDemux"

### ISSUE THREAD

**Issue by skylarsiwu0113** [satijalab/seurat#6366]
Hi,

I met the following errors when I was running the "MULTIseqDemux" function when I am analyzing the CITE-seq data to remove doublets.

Error in if (n_bc_calls[i] == 0) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

The data matrix do not have NA. It only shows errors for some samples, while not for others. In addition, when I set "maxiter = 2" to avoid the iteration that met errors, then it would not report the error as expected. So I wonder whether some of you have met the same problems, and how to solve it? Thank you!

**Comment by longmanz** [comment]
Hi,
This happened to me when the number of cells of some barcodes was very small. In that case, the autoThresh process will fail as the convergence will fail due to the small number of cells. I usually do not do autoThresh (autoThresh = FALSE) when running MULTIseqDemux(). 
Alternatively, you may use HTODemux() to do demultiplex for your CITE-seq.
