### ISSUE TITLE
FeaturePlot not setting correct axis limits with custom reduction

### ISSUE THREAD

**Issue by f6v** [satijalab/seurat#6375]
I've added custom dimensionality reduction to my Seurat object, as well as pseudotime values. The DimPlot look alright:
<img width="353" alt="Screenshot 2022-09-01 at 09 09 08" src="https://user-images.githubusercontent.com/13019221/187853543-f6950186-e906-4d50-9f02-ef310ad6dcd2.png">
FeaturePlot is way off:
<img width="353" alt="Screenshot 2022-09-01 at 09 09 17" src="https://user-images.githubusercontent.com/13019221/187853609-368517e2-9506-447a-b588-d8ce2a36c969.png">
In this case, I have to set the appropriate limits manually.

**Comment by jeffdemartino** [comment]
Was actually about to add this myself... For the developers: I think the issue has to do with the way the limits are calculated in the `FeaturePlot` function on lines 1208, 1209 of visualization.R:

` xlims <- c(floor(x = min(data[, dims[1]])), ceiling(x = max(data[, dims[1]])))`
` ylims <- c(floor(min(data[, dims[2]])), ceiling(x = max(data[, dims[2]])))`

Invoking `floor` and `ceiling` on small numbers between -1 and 1 rounds them to -1 and 1, which as shown is problematic if the range is something like -0.02 to -0.02 (for example). I think it isn't a problem for `DimPlot` since it seems the coordinate ranges are calculated automatically by ggplot2.

@f6v  for now you can get around this by adding `+ xlim()` and/or `+ ylim()` (set to appropriate values) after your `FeaturePlot` call.

**Comment by gabrielnegreira** [comment]
Hi,

I had exactly the same problem with phate dimension reduction. I think the simplest workaround is to just multiply the phate values by 100. This solved the issue for me.

**Comment by yuhanH** [comment]
hi @f6v 
I totally agree with @gabrielnegreira . 
The value in your DC dimension reduction is too small and you can just multiply those value by100 for visualization.

**Comment by lucygarner** [comment]
Is this still the best solution or is there a way to change the axis limits for `FeaturePlot`?
