### ISSUE TITLE
File analyzing from GEO (GSE136831)

### ISSUE THREAD

**Issue by DukKi88** [satijalab/seurat#6399]
Hello, 

I have a question about how to generate a seurat object from GEO dataset (GSE136831).
In GSE136831_RAW.tar, there are RDS files for each sample. 
When I load RDS file to R, I cannot make seurat object from it. 
The type of the loaded RDS file is confirmed 'list'.
How can I make Seurat object with each dataset of the RAW.tar? Should I convert the 'list' type of the file to the 'dgcMatrix' file first?

Thank you for the generous help, in advance...

Best Regards, 
DKK

**Comment by f6v** [comment]
You should figure out what the list elements are. There's probably a matrix in that list, or maybe several matrices for different assays.

**Comment by DukKi88** [comment]
> You should figure out what the list elements are. There's probably a matrix in that list, or maybe several matrices for different assays.

Thank you for your answering

GSE link : https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE136831

In GSE136831, you can see GSE136831_RAW.tar part, there were many dgecounts.rds.gz files for each sample. 
When you extract dgecounts.rds.gz, there is rds file and
head(rds) showed below, 


![RDS](https://user-images.githubusercontent.com/113331490/189692436-97a04407-ba63-4deb-b0c3-aba3d0c8fee5.JPG)

How can I make Seurat object with each dataset of RDS files? 

Thank you for the generous help, in advance...
Best Regards,

**Comment by f6v** [comment]
If you click on one of the samples in the series, there's a description:

> Sample-Associated .rds files: R object files specific to each sequenced library, representing gene expression count data per cell, formatted with ensembl gene IDs. These are the primary data outputs by the processing program zUMIs 2.0. Each one is a nested list of intron spanning, exon spanning and combined intron and exon spanning UMI and read counts for the top 8,000-10,000 cell barcodes in each library ranked by total number of reads

I guess each list contains a matrix for exon-mapped reads, intron-mapped reads, and a combined one for both intronic and exonic reads. You have to decide which ones you want first(CellRanger used to include exonic reads only, it includes exonic + intronic by default now). I'm not a zUMIs user myself, so can't help with that.

Since it's a zUMIs output, you can find an answer on their page: https://github.com/sdparekh/zUMIs/issues/208
