### ISSUE TITLE
SampleUMI does not perform traditional random sampling

### ISSUE THREAD

**Issue by bnprks** [satijalab/seurat#6404]
`SampleUMI` unexpectedly does not perform a traditional *random* sampling of UMIs.
This seems unexpected given the name of the function, so I suggest either the algorithm is 
changed, or the documentation is updated to specify that the current algorithm does not perform
random sampling.

The current algorithm is just dividing counts by a factor, then randomly rounding to the nearest integer.
```r
library(Seurat)
library(Matrix)
x <- sparseMatrix(i=c(1,2,2), j=c(1,1,2), x=c(5,5,10))
x
# 2 x 2 sparse Matrix of class "dgCMatrix"
# [1,] 5  .
# [2,] 5 10
SampleUMI(x, 5)
# 2 x 2 sparse Matrix of class "dgCMatrix"
# [1,] 2 .
# [2,] 3 5
```
Notably, this means that the entry 2,2 of this example matrix will *always* be 5, with no randomness. 
And in the first column, the values can either be 2 or 3, but will never be 0,1, or 4. 

For good random sampling approaches, I believe downsampling with a binomial distribution, or uniform sampling with/without replacement of UMIs within each cell are three good options. I'd be happy to give some implementation tips to efficiently implement these sampling methods if desired.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
