### ISSUE TITLE
Issue with NormalizeData() and other functions from CZI cellxgene

### ISSUE THREAD

**Issue by zdebruine** [satijalab/seurat#6408]
A number of datasets from CZI's cellxgene are throwing the following error when running Seurat `NormalizeData`:

```
Error in vapply(X = keyed.objects, FUN = function(x) { : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
```

For example, see `Visium-GT_IZ_P13-Spatial multi-omic map of human myocardial infarction` from https://cellxgene.cziscience.com/datasets.

This issue can be avoided for `NormalizeData` by calling the S3 method for the `dgCMatrix` directly:

```{R}
data@assays$RNA@data <- LogNormalize(data@assays$RNA@counts)
```

But cannot be avoided for `RunUMAP()`, for example.

How do we address this issue?

**Comment by AustinHartman** [comment]
I believe this is happening because the `key` slot is `NULL` but is expected to be set in order to look up features from a specific `Assay`. Could you try running `data@assays$RNA@key <- "rna_"` to set the key and then see if you are able to run `NormalizeData()` and `RunUMAP()` on the Seurat object?

**Comment by zdebruine** [comment]
@AustinHartman That worked.  Seems like a trivial bug.  Is there any way you could work in a check for the absence of a key, and if absent assign a value to the key corresponding to the assay name?
