### ISSUE TITLE
Error in `Read10x` with R `Matrix` package v. 1.5-0

### ISSUE THREAD

**Issue by ms-gx** [satijalab/seurat#6438]
When using function `Read10x` I got the following error:
`Error: as(<dgTMatrix>, "dgCMatrix") is deprecated since Matrix 1.5-0; do as(., "CsparseMatrix") instead`

In function `Read10x` I changed
`list_of_data[[j]] <- as(object = list_of_data[[j]], Class = "dgCMatrix")`
to
`list_of_data[[j]] <- as(object = list_of_data[[j]], Class = "CsparseMatrix")`

Now it works, but I guess this has to be adjusted globally.

See here:
https://github.com/ms-gx/seurat/commit/63185aa868deac5c55705610d92873d600ee37d8

**Comment by AustinHartman** [comment]
Thanks for raising this - Seurat 4.2.0 was just released on CRAN which addresses coercions which were deprecated in Matrix 1.5.0. Alternatively, you can try modifying the `Matrix.warnDeprecatedCoerce` option in order to toggle warnings/errors as described [here](https://cran.r-project.org/web/packages/Matrix/news.html) under 1.5.0
