### ISSUE TITLE
Tuning seurat integration strength

### ISSUE THREAD

**Issue by nickhir** [satijalab/seurat#6450]
Hello,

I am currently working with multiple replicates for 2 different conditions (stimulated and unstimulated cells) that I want to integrate to adjust to correct for batch effects. I was wondering, if there is a way (or parameter), which can be adjusted to control the integration strength or stringency. I am afraid that cell types that are unique to the stimulated condition, are projected onto the "wrong" cells, because the integration is to stringent, so I want to try out different settings.

Any help is much appreciated. 
Cheers!

**Comment by massisnascimento** [comment]
This is something that I also have trouble with. In my experience, the default parameters are pretty strong, and I've been using it only to integrate technical replicates with no biological differences between samples. Using the integration tool on datasets with samples at different maturation stages introduces lots of artificial similarities between them, completely erasing meaningful biological processes I am interested in investigating, such as differentiation. 

Would be nice to be able to tune the strength -- I wonder if this can be done by selecting fewer features or fewer anchors when integrating.

**Comment by f6v** [comment]
You've got to look at the plots without any integration. How different are your replicates on the UMAP? Maybe you don't even need to bother.

**Comment by timoast** [comment]
You can adjust the `k.anchor` parameter in `FindIntegrationAnchors()` to make the anchor-finding more or less stringent.

>  Using the integration tool on datasets with samples at different maturation stages introduces lots of artificial similarities between them, completely erasing meaningful biological processes I am interested in investigating, such as differentiation.

Remember that the goal of integration is to identify equivalent cell states across datasets, and we always go back to the original (un-integrated) data for doing cross-dataset comparisons. Therefore, integration is only guiding the choice of cell comparisons you want to perform, and will not erase anything since you use the uncorrected data for differential expression.
