### ISSUE TITLE
RunCCA doesn't check for compatible input and has incomplete documentation

### ISSUE THREAD

**Issue by TomKellyGenetics** [satijalab/seurat#647]
I tried to use `RunCCA` to combine 2 datasets and perform canonical correlation analysis to evaluate batch effects. However, I received the following error message:

```
> RunCCA(object1, object2, group.by = "group")
0 valid genes in genes.use
```

This error was not helpful. Giving `genes.use = union(object1@var.genes, object1@var.genes)` did not resolve this issue nor did re-running `FindVariableGenes` on each object.

This issue arose because I had neglected to run `ScaleData` on an object. This also produces this error message. I was able to identify and troubleshoot this from viewing the source code, since the default `genes.use` is compared to `possible.genes` derived from `rownames(object@scale.data)` (which does not exist when the data has not yet been scaled) rather than `rownames(object@data)` . 

This error message is therefore terse and is unhelpful considering that many less inexperienced R users perform Seurat analysis since the package is so popular. I would suggest to include more checks for compatible data inputs and warning or error messages if these data inputs are missing. While the vignette includes the appropriate data scaling, it may be helpful to mention that this requires a scaled object by default in the R documentation. I would also suggest to mention in the `RunMultiCCA` documentation that `RunCCA` is recommended if only 2 datasets are being compared. 

It would also be helpful to make "group" be the default for `group.by` (for `RunCCA`) and `grouping.var` (for `AlignSubspace`). It is not clear why there is no default for these, why the group arguments differ between them, or why `RunCCA` suggests to "add.cell.ids"  (an argument in `RunMultiCCA` and `MergeSeurat` but not this command) when a grouping variable would resolve this problem and is already supported by the Seurat object Metadata.

Overall these are minor issues but addressing them would make performing CCA easier.

**Comment by satijalab** [comment]
Thanks for the feedback - it would be wonderful if you would consider submitting a PR with modified documentation, and/or compatibility checks. 

Hopefully, when you were able to run the alignment procedure, it worked well for you.

**Comment by TomKellyGenetics** [comment]
I'm still experiencing some difficulties but I think that may be due to the experiments that we are still optimising. My colleague has performed this analysis on another project and recommends this package enthusiastically. Overall, I think it is very good but I encountered some minor issues running this analysis and have suggested changes with consideration for the popularity of the package and that this would cause more difficulties for inexperienced R users.

**Comment by yueqiw** [comment]
@satijalab I had experienced similar issue to this one. 

I took previously analyzed datasets as input to RunCCA. Although I did run ScaleData on both datasets previously, it was run only on `@var.genes` rather than all genes to save time and reduce file size. I run through the CCA pipeline without any error but got weird results. It took me a while to realize that RunCCA only considered the genes present in `@scale.data` as `possible.genes`. Since most of the genes (non-HVGs) were not scaled, they were ignored and CCA was run only with a very small set of genes (`intersect(object1@var.genes, object1@var.genes)`). This was a silent error and hard to catch. 

I'd suggest filtering `genes.use = union(object1@var.genes, object1@var.genes)` based on the row names of `@data` slot and then check if all these genes are also present in `@scale.data`. If not, a warning message can be printed telling the user that they need to run ScaleData on more genes. 

This would help when people are working with larger datasets, especially since the [Mouse Cell Atlas Vignette](https://satijalab.org/seurat/mca.html) suggests running ScaleData on only HVGs for larger datasets.

**Comment by TomKellyGenetics** [comment]
@yueqiw I think this is tangentially-related but I'm not sure whether the solution I've suggested by [Pull Request](https://github.com/satijalab/seurat/pull/649) would resolve your problems.

Are you aware that `genes.use` defaults to `union(object1@var.genes, object1@var.genes)`? Currently, `data` or `scale.data` is used depending on whether the scaling parameter is TRUE (which it is by default). I don't take issue with this, although I have tried to make it clearer in the documentation and warning messages in Pull Request #649. I was not aware that `ScaleData` only returns a subset of the data but I suspect that there may be other issues if `genes.use` differs between these commands.
