### ISSUE TITLE
How to convert/transform/normalize the expression such that the scale bar in DoHeatmap() becomes 0 to 1?

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#6506]
Hi! 

Is it possible for the expression scale in DoHeatmap to be converted/transformed/normalized to **0 to 1 scale** like below figure? In this paper they mentioned "all gene expression values are unity normalized from 0 to 1" only in figure captions so there were no clues from their method. I was wondering if the same can be done from DoHeatmap. 

![image](https://user-images.githubusercontent.com/68268222/194277932-d3999b1c-9fef-43c6-930b-8f8a2c0eafef.png)

Meanwhile, the arguments **disp.min** and **disp.min** from **DoHeatmap()** only clips all data below and above these thresholds respectively, so I need the scaling to 0 to 1 expression. Thank you.

**Comment by longmanz** [comment]
Hi, 
Not necessarily with DoHeatmap since the ScaleData() in Seurat only do standard scaling. But a workaround would be to extract the count matrix and do the unity scaling by yourself and use functions like heatmap.2 in package gplots (https://cran.r-project.org/web/packages/gplots/index.html) to generate customized heatmaps. 

As for unity scaling, I am not sure what exactly was done in your paper. You may extract the normalized expression matrix by `mat = seurat.obj[['RNA']]@data`, and then do unity scaling for each row (gene). You may refer to this post for a possible unity-normalization method: https://stats.stackexchange.com/questions/70801/how-to-normalize-data-to-0-1-range .
