### ISSUE TITLE
Latest Seurat version differs on GitHub and CRAN

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#6523]
Hi,

Why is the version of Seurat on CRAN 4.2.0, while the latest version on GitHub is 4.1.1? I would like to install Seurat in a Conda environment on a high performance cluster, but I am using 4.2.0 locally so I would also like that in my Conda environment. Should I just download the current GitHub state?

What are the main changes between 4.1.1 and 4.2.0?

Best wishes,
Lucy

**Comment by samuel-marsh** [comment]
Hi,

The current master branch on GitHub is also 4.2.0 just like CRAN:
https://github.com/satijalab/seurat/blob/master/DESCRIPTION

So you can install from either source.

Changes between versions can be found in the changelog News.md file (https://github.com/satijalab/seurat/blob/master/NEWS.md)

Best,
Sam

**Comment by lucygarner** [comment]
Thank you. How would you go about installing from GitHub within a Conda environment?

**Comment by samuel-marsh** [comment]
Hi,

Here is Biostars post with couple helpful replies as to what to do: https://www.biostars.org/p/450316/.  I’m sure there are other blogs/forum posts too.

In short, create conda env, install R in env, activate env, open R in terminal, install packages like you normally would.  

```
install.packages(“devtools”)
devtools::install_github(“satijalab/seurat”)
```

again though that’s not necessary because it’s equivalent to CRAN version so you can just run:
```
install.packages(“Seurat”)
```

Best,
Sam

**Comment by lucygarner** [comment]
Great, thank you.

**Comment by samuel-marsh** [comment]
No problem!
