### ISSUE TITLE
Setting custom color palettes in FeaturePlot

### ISSUE THREAD

**Issue by zqyhyunbin** [satijalab/seurat#653]
Hi,guys,
i do need help. i just want to know how to set the color parameter that plot the marker gene figure which gene expression from blue to yellow to red. 
thank you so much for your help

**Comment by mojaveazure** [comment]
You can set colors with the [`cols.use` argument](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/FeaturePlot), and we provide a [CustomPalette](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/CustomPalette) function to help generate color palettes for our plots.

**Comment by yueqiw** [comment]
@mojaveazure I tried the CustomPalette function. The plot looks good but the legend does not work well. 
It's plotting color values as discrete legends rather than a continuous one:

![image](https://user-images.githubusercontent.com/5046690/44065789-fcbb425c-9f29-11e8-993d-fee4042e4518.png)

**Comment by zqyhyunbin** [comment]
yes, i did, set the code in tsns_plot(do.return=true), and use the ggplot2 do more work which including change the color via RColorbrewer package

**Comment by CodeInTheSkies** [comment]
Hi @yueqiw and @zqyhyunbin,

Could you please elaborate more on how you modified the ggplot object obtained from the TSNEPlot function to add custom color palettes?  That will be awesome!

I am facing the same problem, i.e., I wish to have more control to choose the color gradient in FeaturePlot.  The FeaturePlot function doesn't have a lot of options for this, and so I think it's best to get the ggplot object and then modify outside.  If you have already figured this out, then any help will be appreciated.   Many thanks.

**Comment by zqyhyunbin** [comment]
library(RColorBrewer)
fp <- FeaturePlot(object , features.plot = c("CD68"), 
			   reduction.use = "tsne",	
			   cols.use = c("gray","red"),
                           pt.size = 1.5,			
			   no.legend = FALSE,
			   do.return=TRUE)
lapply(fp, function(x){x + scale_colour_gradientn(colours=brewer.pal(11,"RdYlBu")[11:1])+
                                       ...+
                                       ...+

**Comment by CodeInTheSkies** [comment]
Thank you very much!  That works.

The only other thing I would like to add as a comment is that it will be
nice to be able to do this using the ggplot object obtained from the
TSNEPlot function, but then I see that we'll have to change the aes mapping
with respect to color using something like ggplot_build.

Of course, one may say that this is why the FeaturePlot function exists.
Agreed.  But at least in my case, I think the above would be useful since
the biologist wants the exact look of the TSNEPlot output but just with the
cells colored by a gene's expression.  The output of the Featureplot
function looks a bit different and so I'll have to find other ways to
adjust the plot's look.  Anyway, this is not a big problem.
