### ISSUE TITLE
order of merging objects impacts cluster result?

### ISSUE THREAD

**Issue by goubegou** [satijalab/seurat#656]
Hi all,i merged 3 seurat object stepwise as recommanded in #207 , like:
```R
object12=mergeseurat(object1,object2)
objectfinal=mergeseurat(object12,object3)
```
and performed cluster analysis on the objectfinal .I found that cells from objects that i merge first(object1&object2) clustered together tightly,while cells from object3 formed seperate clusters.

For objectfinal,i tried to deal with batch effect by `ScaleData(...vars.to.regress=c(..."orig.ident"))`,and i've proved that this orig.ident indeed referred to three original object correctly. I wonder whether this result truly reflects the fact,or it's just a special kind of "batch effect"? I dont really familiar with theory behind seurat normalization and scaling method,so i wish to learn from you about this "weird" result.Thanks all!

**Comment by leonfodoulian** [comment]
Hi @goubegou,

You might want to have a look at Seurat's [CCA tutorial](https://satijalab.org/seurat/immune_alignment.html), and try to implement that for your data. The corresponding paper is published and can be found [here](https://www.nature.com/articles/nbt.4096).

Best,
Leon

**Comment by leonfodoulian** [comment]
Also, I should mention that the order by which you merge the objects has nothing to do with adding batch effects to your data, as `Seurat::MergeSeurat()` simply concatenates objects without altering gene expression values. If there are batch effects in your data, these most probably are due to the experiments being performed at different days, samples sequenced on different sequencing lanes, etc.

Best,
Leon
