### ISSUE TITLE
"cols" in DEenrichRPlot() does not work 

### ISSUE THREAD

**Issue by naziafrin** [satijalab/seurat#6562]
Whenever I try to change the color of the barplot generated from DEenrichPlot(), it does not work for me. It is always giving me the blue and red color for 'positive marker' & 'negative marker' respectively. 
Could you please help me with this? 

 
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

```r
# insert reproducible example here
```
DEenrichRPlot(
  CD8.EMRA,
  ident.1 =  "CD8 EMRA_HR",
  ident.2 =  "CD8 EMRA_SR",
  balanced = TRUE,
  logfc.threshold = 0.25,
  assay = "RNA",
  max.genes = 100,
  test.use = "wilcox",
  p.val.cutoff = 0.05,
  enrich.database = "GO_Biological_Process_2018",
  num.pathway = 20,
  cols = c("lightgrey", "blue"),
  return.gene.list = FALSE)

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
