### ISSUE TITLE
How to create a seurat object from multiple .dgecounts.rds objects?

### ISSUE THREAD

**Issue by cogen859** [satijalab/seurat#6571]
I am working on a dataset whose count matrix is 9Gb. When I follow regular workflow to create Seurat object using barcodes.tsv, genes.tsv and matrix.mtx file I get following error:

```
Error in dimnamesGets(x, value) : 
  length of Dimnames[[1]] (45948) is not equal to Dim[1] (45947)
  ```
Since I could not find any resolution on this error, I decided to download Raw.tar file which contains .dgecounts.rds for each sample. I am not able to find a way to create seurat object with .dgecounts.rds objects.

**Comment by samuel-marsh** [comment]
Hi,

Is this a dataset from NCBI GEO?  Could you provide accession number?

If the dgecounts.rds files are individual matrices then you should be able to read them in using `readRDS`.  You can then provide that variable to `CreateSeuratObject` (just being aware that if you set parameters for min.cells and min.features this will be done on per sample basis as opposed to across the entire dataset.).  Then you can use `merge` to make single Seurat object.

That said if there's lot of files then figuring out what the issue is with the original matrix may be easier.  

Best,
Sam

**Comment by cogen859** [comment]
Thanks Sam for your suggestion. Yes its a public dataset- gse136831.
There are 78 samples each having its own .dgecounts.rds file. It would be great if you share how to resolve the error around the original matrix.

**Comment by samuel-marsh** [comment]
Hi,

Not sure how you were reading the data in but things worked for me doing this:

```
library(tidyverse)
library(Matrix)
library(Seurat)

mat <- readMM(file = "~/Downloads/GSE136831_RawCounts_Sparse.mtx.gz")
barcodes <- read.delim("~/Downloads/GSE136831_AllCells.cellBarcodes.txt.gz", header = F)
genes <- data.table::fread("~/Downloads/GSE136831_AllCells.GeneIDs.txt.gz", data.table = F)

rownames(mat) <- genes$HGNC_EnsemblAlt_GeneID
colnames(mat) <- barcodes$V1

obj <- CreateSeuratObject(counts = mat)
```

Best,
Sam

**Comment by cogen859** [comment]
Thank you!

**Comment by samuel-marsh** [comment]
At this time no it's just the way it is and Seurat/R stores things so you need compute environment that has enough RAM to handle it.  I know Seurat team are working on support for other formats to enable easier working with large datasets though: https://github.com/mojaveazure/seurat-object/issues/49

Best,
Sam
