### ISSUE TITLE
PCASigGenes error Error in pvals.use[, pcs.use] : subscript out of bounds

### ISSUE THREAD

**Issue by kaizen89** [satijalab/seurat#658]
I am using Seurat 2.3.4 and contrary to v1.4 Im having an annoying error, I can run PCASigGenes on variable genes;
```R
PCASigGenes(x_seurat, pcs.use = 1:6, max.per.pc = 200, use.full = F) 
```
However when running on all genes;
```R
PCASigGenes(x_seurat, pcs.use = 1:6, max.per.pc = 200, use.full = T) 
```
I get;
```R
Error in pvals.use[, pcs.use] : subscript out of bounds
```
I found that in 
```
GetDimReduction(x_seurat, reduction.type = "pca", 
                slot = "jackstraw")@emperical.p.value.full
```
I get;
```R
      [,1]
[1,]   NA
```
Any help?
thanks

**Comment by stillhere89** [comment]
Still looking for an answer :)
Also if you are able to  use this function in Seurat v2 please let me know.
thanks

**Comment by stillhere89** [comment]
no one is using this function?

**Comment by ChengTao2017** [comment]
Have you solved this problem?

**Comment by kaizen89** [comment]
No, but I used another approach
After ruinning PCA on variale genes, jackstraw function and/or elbowplot, I choose the number of PCs to keep
df<- as.data.frame(GetDimReduction(x_seurat))
#I want the top200 genes for each of the 6 first PCs
top_genes = c()
for( i in 1:6){ 
  top_genes = c(top_genes, rownames(df)[order(df[,i], decreasing = FALSE)][1:100]) 
  top_genes = unique(c(top_genes, rownames(df)[order(df[,i], decreasing = TRUE)][1:100])) 
}
#I run a new PCA on "top_genes"

**Comment by mojaveazure** [comment]
As per the [documentation for PCASigGenes](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/PCASigGenes):

> **use.full** Use the full list of genes (from the projected PCA). Assumes that [`ProjectPCA`](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/ProjectPCA) has been run. Currently, must be set to `FALSE`.

The `use.full` argument pulls the genes from the projected PCA matrix. It also tries to pull from a JackStraw that has been projected back to all genes, but that doesn't work in Seurat v2.X; as such, the `use.full` argument needs to be `FALSE` in Seurat v2. In Seurat v3, this has been fixed so that pulling the full gene/feature loading matrix doesn't depend on JackStraw having been projected back to the full gene/feature list.

**Comment by vertesy** [comment]
[ProjectPCA](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/ProjectPCA) is not used any more. 
Based on  #2421, `ProjectDim` should be the correct function.

I, however got 
```r
Error in data.use %*% cell.embeddings : non-conformable arguments

```
