### ISSUE TITLE
how to Exports a seurat object as CSV files

### ISSUE THREAD

**Issue by mianmianyin** [satijalab/seurat#6585]
how to Exports a seurat object as CSV files

**Comment by jjo12** [comment]
Hi Seurat Team,

I had the same question on this. I would like to export the gene expression in CSV matrix organized into each cluster. Is this possible? I tried going over the [](https://github.com/satijalab/seurat/issues/1802) and [](https://satijalab.org/seurat/archive/v3.0/de_vignette.html).

I could not find an appropriate way to obtain the CSV file. This is just so that my team can go over genes manually in a list.

Thank you.

J

**Comment by f6v** [comment]
I think this has already been asked before https://github.com/satijalab/seurat/issues/427

**Comment by samuel-marsh** [comment]
Hi,

Yes, @f6v is correct.  You can simply extract which set of data you want from the object (raw, normalized, scaled) and then saving as csv.  Though you don't need to convert to data.frame in R before saving.  Beware though that depending on size of your object/dataset these files could be quite large/unwieldy as they will be in dense format.

Here's example exporting normalized expression data for whole object
```
mat <- GetAssayData(object = pbmc, assay = "RNA", slot = "data")

write.csv(mat, "mat.csv")
```

@jjo12 If you want to do by cluster then you can simply subset the matrix extracted from Seurat object by cell names from that cluster before saving the file.

Here's example exporting normalized expression data one file per cluster.
```
mat <- GetAssayData(object = pbmc, assay = "RNA", slot = "data")

cells <- CellsByIdentities(object = pbmc)

for (x in names(cells)) {
  temp_mat <- test[colnames(test) %in% cells[[x]], ]
  write.csv(temp_mat, file = paste0(x, "_matrix.csv"))
}
```

Best,
Sam

**Comment by mianmianyin** [comment]
thanks
