### ISSUE TITLE
AddModuleScore - Comparing Scores For Different Gene Lists

### ISSUE THREAD

**Issue by chenv3** [satijalab/seurat#6589]
I'm trying to determine how valid it is to compare the calculated module scores when providing different gene lists against each other. I understand that these are relative scores for how much the gene list is expressed across the population. By my understanding this would mean that the only conclusion I can draw when looking at the scores for two different modules in a particular cluster is how much these two modules are expressed when compared to the average expression. I can not necessarily say how much one module is expressed compared to the second module.

I'm actually working with gene lists of very different lengths and I was trying to determine how valid it is to compare the results in that situation. However, if a direct comparison of scores isn't a valid way of saying module one is expressed more highly in that cluster than module two is, then this question would be a moot point.

I hope my question makes sense. Thank you

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Others may have some more thoughts but I can give some of mine. 
 So I think you pretty much hit on it in terms of comparing the module scores.  The scores are going to be created vs. different background gene sets and gene sets of different sizes, and also the fact that dataset composition can significantly alter module score.

There is also a matter of what the cutoff of module score is as "enriched".  I think there is potentially situation where you could aim to compare the % of enriched cells between two module scores but again depending on what they are scores for and what the composition of the dataset is even that may not be quite valid.

In terms of whether a score is enriched this is what I did in recent paper (https://doi.org/10.1038/s41593-022-01022-8; See Figure 3f-k)
_We then created 1,000 random gene lists of equivalent length to the microglial LIGER factor (38 genes) and the astrocyte LIGER factor (27 genes). We then downsampled each dataset so that all of the major cell classes had the same number of cells, so that cell number/proportion did not influence outlier detection. We then performed gene module scoring using the random lists. To determine a cutoff for microglia we calculated an outlier threshold for each of the random scores. The outlier threshold was calculated as median score (across all cell types) + 3 × median absolute deviation of score (across all cell types). We then plotted all of the outlier thresholds for each of the 1,000 random scores. A cutoff was selected at the top 2.5% of outlier thresholds. We then determined the proportion of microglia per sample that exhibited a postmortem LIGER microglia factor score above that cutoff._

Best,
Sam

**Comment by yuhanH** [comment]
hi @samuel-marsh 
Thank you very much for your great explanations. I totally agree with you.

**Comment by chenv3** [comment]
@samuel-marsh Thank you so much for your response, that was very helpful.
