### ISSUE TITLE
Possible BUG in PCA, that might affect other functions?

### ISSUE THREAD

**Issue by CodeInTheSkies** [satijalab/seurat#66]
Hello Seurat Team,

I just noticed a potential error in the SetMethod section for the PCA function with regards to rev.pca.

Particularly, here are the lines I am referring to:

```
if (!rev.pca) {
              pc.genes.use=pc.genes[pc.genes.var>0]; pc.genes.use=pc.genes.use[!is.na(pc.genes.use)]
              pc.data = data.use[pc.genes.use,]
              pca.obj = prcomp(t(pc.data),...)
              object@pca.obj=list(pca.obj)
  
              pcs.store=min(pcs.store, ncol(pca.obj$rotation))
              pcs.print=min(pcs.print, ncol(pca.obj$rotation))
              object@pca.x=data.frame(pca.obj$rotation[,1:pcs.store])
              object@pca.rot=data.frame(pca.obj$x[,1:pcs.store])
}
```

From my understanding, the last two lines should be

```
              object@pca.x=data.frame(pca.obj$x[,1:pcs.store])
              object@pca.rot=data.frame(pca.obj$rotation[,1:pcs.store])
```

In effect, the current code seems to wrongly assign rotation to x and x to rotation.  

Now, I am not sure how much of the rest of the functions, like tSNE, etc. get affected by this.  Anyway, I thought I should bring this point out.

Thanks.

**Comment by satijalab** [comment]
We apologize, as this is indeed quite confusing due to a poor naming convention, though the calculations are handled correctly by downstream functions (tSNE, FindClusters, etc.). 

In our next release we are replacing these variable names to clearly denote cell embeddings (representing rotated data in low dimensional PCA space), and gene loadings (based on the eigenvectors). The results will be unchanged, but this will be significantly clearer, with accurate naming.

**Comment by friedue** [comment]
I can confirm that it's not a bug, but poor naming convention. If the authors had clearly stated what `pca.x` and `pca.rot` are supposed to represent (i.e., the loadings for cells and genes), this would be clearer. But most of the code that relies on the PCA output that I've looked at (SNN, clustering) seems to handle the awkward naming convention correctly.
