### ISSUE TITLE
Any way to include ERCCs to remove technical noise?

### ISSUE THREAD

**Issue by mvalenzuelav** [satijalab/seurat#660]
Hi all,
I just wonder if ERCCs counts could be included in any step of data cleaning, because I read they are used to remove technical noise but I can not see any tutorial from you where you include ERCCs during filtering cells. The step you use to remove possible sources of variation is function ScaleData, should then be ERCCs (percent.ERCC) included here, like percent.mito? Would it make any difference?
I thought ERCC data should be use for filtering, if not, which is their function?
Thanks a lot!

**Comment by leonfodoulian** [comment]
Hi @mvalenzuelav,

You can compute the ERCC count abundance (as `percent.ERCC`) and add that info to your `object@meta.data`, the same as you would do with mitochondrial count abundance calculation (see **QC and selecting cells for further analysis** in the [Seurat Guided Clustering Tutorial](https://satijalab.org/seurat/pbmc3k_tutorial.html)). However, I would be interested in hearing the opinion of @satijalab and others on using ERCC data as confounder variables when scaling the data. 

Best,
Leon

**Comment by satijalab** [comment]
Thanks Leon. We personally do not use ERCCs in our experiments - as in my own lab we found cases where the ERCCs looked great - but the cell data looked quite poor (for example, due to incomplete cellular lysis). However, this is an active area of discussion from the community.

If you do have ERCC data in your experiment, and apply the suggestions Leon mentioned above, we would be happy/curious to hear how it affects your downstream analysis.
