### ISSUE TITLE
Can't CreateSeuratObject with two txt files

### ISSUE THREAD

**Issue by toniseq** [satijalab/seurat#6617]
Hi :)

I downloaded a scRNAseq dataset from [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE156444).
The provided files are two txt files, one with the expression data and the other with annotations.

I seem to fail to bring those two together into a Seurat Object. Do you have tips on how I can master this?

I tried to simply create a matrix from the expression file with

```
b16 <- as.matrix(read.table("GSE156444_scRNA-seq_UMI_raw_counts.txt",
                             row.names = 1, sep = "\t", header = TRUE))
```

and loaded the annotation file as a data frame with

```
annotation <- read.table("GSE156444_cell_annotation.txt", 
                          sep = "\t", header = TRUE)
```

But the final Seurat object can't be created with

`seurat_object <- CreateSeuratObject("b16", meta.data = "annotation", min.cells = 3, min.features = 200)`

I tried several variations or additions that I found online, but nothing worked.

Common error messages I got were...

- Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features,  : 
  No cell names (colnames) names present in the input matrix
- In CreateSeuratObject.default("b16", meta.data = annotation, min.cells = 3,  :
  Some cells in meta.data not present in provided counts matrix

Please someone help me, I've been stuck with this for far too long 🤕

**Comment by samuel-marsh** [comment]
Hi,

The issue seems to be with the format of both files.  You just need to be sure that column and row names are set correctly.  This works when I tried it:

```
mat <- data.table::fread("~/Downloads/GSE156444_scRNA-seq_UMI_raw_counts.txt.gz", data.table = F) %>% 
  column_to_rownames("V1")
annot <- data.table::fread("~/Downloads/GSE156444_cell_annotation.txt.gz", data.table = F) %>% 
  column_to_rownames("V1")

test_seu <- CreateSeuratObject(counts = mat, meta.data = annot)
```

Best,
Sam

**Comment by toniseq** [comment]
Dear Sam,

Wow. This worked perfectly!
Thank you so much. I still don't really understand what you did there though.

Could you explain a little more detailed? :)

Kindly,
Antonia

**Comment by samuel-marsh** [comment]
Hi Antonia,

Sure!  So basically I use fread for basically any delimited file type (tsv, csv, txt) because it detects delimiter and is much faster for large files than read.csv etc.  I set data.table = F so that the imported object is a data.frame and not data.table (some quirks to modifying/working with data.table formatted objects in some use cases).

If you just read in the files using first line of code what you’ll notice is in the matrix file that the gene names are stored in column 1 and in annotation file the cell names are stored in column 1.  Seurat needs the gene names to be stored as rownames in counts file and cell names to be stored as rownames in meta data file.

So all that we are doing here is piping `column_to_rownames` to move those columns to rownames after reading in the files.  Then they are all ready for creation of Seurat object.

Glad it worked!
Best,
Sam
