### ISSUE TITLE
Read10X(data.dir = "~") error:    Barcode file missing. Expecting barcodes.tsv.gz 

### ISSUE THREAD

**Issue by mvslmdOjbi** [satijalab/seurat#6632]
I am new to Seurat analysis, so please excuse my very basic question.

I'm trying to analysis scRNA-seq data deposited in GSE132771 (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE132771).
I downloaded the genes.tsv.gz, barcodes.tsv.gz, and matrix.mtx.gz data for each sample, and unzipped files were renamed to features.tsv, barcodes.tsv and matrix.mtx ( e.g. renamed from GSM3891619_UT2_GFPn_genes.tsv to features.tsv), respectively.

Unfortunately, when I tried to read these data by Read10× function in R, I got the following error message;
**Read10X(data.dir = "~") error:    Barcode file missing. Expecting barcodes.tsv.gz**

Where do you see the problems?
 list.files("~") shows the following , so I suppose matirx data is actually set as working directory.
[1] "barcodes.tsv" "features.tsv" "matrix.mtx"  

I also conducted the same procedure for the analysis of the Seurat tutorial data (2700 PBMCs), but it worked well.
Unzipped form of this tutorial PBMC data and above mentioned GSE132771 data looks quite similar.
One difference was that the matrix data of GSE132771 could not be simply unzipped, so I used an app (The Unarchiver) to decompress  it.

I would be grateful for your support.

**Comment by jarchana09** [comment]
Hello. Perhaps, this may be helpful. 
In the uncompressed file, instead of renaming "genes.tsv" to "features.tsv", retain the filename as "genes.tsv" 

My understanding is that these are the file names (barcodes.tsv, genes.tsv, matrix.mtx) that the Read10X function expects for scRNA seq processed through earlier versions 10X Genomics Cell Ranger software (<3.0).

For scRNA seq data processed through Cell Ranger v3 and higher, Read10X can directly read the .tsv.gz files (barcode.tsv.gz, features.tsv.gz, matrix.mtx.gz), and the file names for the newer data include features instead of genes as per 10X conventions.

Further information is available at Seurat's R code page at: [https://github.com/satijalab/seurat/blob/master/R/preprocessing.R](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R) (lines 781-904)

Hope this helps.
Thanks.

**Comment by saketkc** [comment]
For experiments where the filenames do not follow the usual 10X convention you can use the `Readmtx` [function](https://satijalab.org/seurat/reference/readmtx)

**Comment by mvslmdOjbi** [comment]
Dear jarchana09,

Thank you very much for the valuable information！
It really helps me.
When I loaded these data as unzipped gz file, it worked well.

I would really appreciate it if you would help me if I should encounter any problems.

**Comment by mvslmdOjbi** [comment]
Dear [saketkc](https://github.com/saketkc),

Thank you for your information, it is very educational for me.
I will try this method next time I encounter a similar problem.

I would really appreciate it if you would help me if I should encounter any problems.
