### ISSUE TITLE
Questions about "PrepSCTFindMarkers"

### ISSUE THREAD

**Issue by LeeWang21** [satijalab/seurat#6675]
hi, Seurat team.

I have  some questions about  the function of "PrepSCTFindMarkers". 

 Given a merged object with multiple SCT models, before running PrepSCTFindMarkers, each SCT model sets the median UMI as the sequence depth for corresponding dataset . according to the documents, if I want to find DEGs, i need run the  PrepSCTFindMarkers, which uses minimum of the median UMI (calculated using the raw UMI counts) of individual objects to reverse the individual SCT regression model using minimum of median UMI as the sequencing depth covariate. 

However, each SCT model is established based on its corresponding dataset. Is it reasonable to set the same sequence depth ( i.e.  the minimum of the median UMI of individual dataset) for all SCT models which are "trained" and established  on different individual dataset?  does it indeed make all the datasets in the merged object at "the same sequence depth"?
    

Another question is that if i want to check the expreesions of genes in the  "SCT" assay of merged object, and the genes exist in multiple datasets of merged object, should I also run the "PrepSCTFindMarkers" to make  all the datasets in the merged object at "the same sequence depth"? 

these questions puzzle me a lot ~   looking forward to the communicaion with you 
  
best wishes

**Comment by saketkc** [comment]
> However, each SCT model is established based on its corresponding dataset. Is it reasonable to set the same sequence depth ( i.e. the minimum of the median UMI of individual dataset) for all SCT models which are "trained" and established on different individual dataset? does it indeed make all the datasets in the merged object at "the same sequence depth"?

The correction step is based on the premise that if all datasets were to be sequenced to a given depth (the default being minimum of the median UMI as a reasonable middle ground) what would the observed gene counts be if there are is minimal technical noise arising from sequencing depth. 

> Another question is that if i want to check the expreesions of genes in the "SCT" assay of merged object, and the genes exist in multiple datasets of merged object, should I also run the "PrepSCTFindMarkers" to make all the datasets in the merged object at "the same sequence depth"?

Yes, I would recommend running `PrepSCTFindMarkers()` before visualization if you are trying to visualize expression on a dataset with multiple SCT models.

**Comment by realzehuali** [comment]
For the second question here, I am wondering if visualization without PrepSCTFindMarkers() is more reasonable.  Since each SCT model sets the median UMI as the sequence depth for corresponding dataset, the individual sctransform step has corrected the this dataset with its own median UMI. In this way, PrepSCTFindMarkers()'s correction with the same median UMI would result in UMI variance induced bt batch on the contrary.

**Comment by realzehuali** [comment]
In the abstract of SCTransform paper: We propose that the Pearson residuals from “regularized negative binomial regression,” where cellular sequencing depth is utilized as a covariate in a generalized linear model, successfully remove the influence of technical characteristics from downstream analyses while preserving biological heterogeneity.

**Comment by saketkc** [comment]
The correction step by default fixes the covariate to the median UMI for that dataset. If you have a dataset with 10k median UMI and 1k median UMI, it is necessary to bring them to same sequencing depth. The reason to choose a monomum of these two during PrepSCTFindMarkers is to reduce the false-positives you would otherwise get.

**Comment by realzehuali** [comment]
My confusion is that I think before running PrepSCTFindMarkers(), each SCT model or each correction step fixes the covariate to the median UMI for not only that dataset, but also to an absolute level that is comparable to other datasets fixed. So after running PrepSCTFindMarkers() with the same UMI, they are back to their original level.  So can each SCT model do this?

**Comment by saketkc** [comment]
Not sure if I understand the question. But I will try to elaborate what happens with the correction step. If you have two datasets, you learn two noise models using sctransform. In the correction step you then use these individual models and reverse  the regression step to estimate the counts (the 'y' in a linear model is what is being estimated where y ~ x.) At this step you also need to tell the model how deep each dataset is being sequenced to - this is where we substitute the minimum of the median UMIs. This ensures the models take into account thr noise model for each dataset while estimating the corrected counts. Hope this helps.

**Comment by realzehuali** [comment]
I have an example. My apologies for my bad understanding of Sctransform().
Dataset A: 3 cells with UMI 90,100,110 and gene A counts: 4.5, 10, 55. (so absolute expression: 0.05, 0.1, 0.5)
Dataset B: 3 cells with UMI 900,1000,1100 and gene A counts: 45, 100, 550.  (so absolute expression: 0.05, 0.1, 0.5)
So gene A expression in dataset A is the same with itself in dataset B.

I agree with correction of each dataset to make sure they have the same sequencing depth.
Here is our divergence: Sctransform step before PrepSCTFindMarkers() 
I think Sctransform will result in dataset A: 0.05, 0.1, 0.5 and dataset B: 0.05, 0.1, 0.5. After PrepSCTFindMarkers(), you will get dataset A: 0.05, 0.1, 0.5 and dataset B: 0.5, 1, 5. Gene A level are back to their original level, since 0.05, 0.1, 0.5 and 0.5, 1, 5 are the same as 5, 10, 50 and 50, 100, 500. 
You think Sctransform will result in dataset A: 5, 10, 50 and dataset B: 50, 100, 500. So you need PrepSCTFindMarkers() to get dataset A: 0.05, 0.1, 0.5 and dataset B: 0.05, 0.1, 0.5. 

So sorry for my bad understanding of Sctransform(), and thank you very much for being patient with my question.

**Comment by saketkc** [comment]
You need PrepSCTFindMarkers to bring both datasets at a comparable sequencing depth - otherwise you will have a ~10x difference in the corrected counts of gene A across the two datasets.

**Comment by realzehuali** [comment]
Now I understand. Thank you for the quick reponse very much!

**Comment by realzehuali** [comment]
So this should be a routine step.
