### ISSUE TITLE
Converting SingleCellExperiment objects into Seurat objects

### ISSUE THREAD

**Issue by mass-a** [satijalab/seurat#6692]
Hello,

I am having trouble converting SingleCellExperiment objects from the [scRNAseq bioconductor collection](https://bioconductor.org/packages/release/data/experiment/vignettes/scRNAseq/inst/doc/scRNAseq.html) using `as.Seurat`. Here's a reproducible example:
```r
BiocManager::install('scRNAseq')
library(scRNAseq)

sce <- ZilionisLungData('mouse')
seurat <- as.Seurat(sce, counts = "counts", data=NULL)
```
```r
Error in embeddings[i, j, drop = drop, ...] : subscript out of bounds
```

Several other datasets in the collection give similar errors. Any idea what's going on here? can I e.g. ask `as.Seurat` to only convert counts and metadata?

Thanks in advance,
-massimo

**Comment by timoast** [comment]
The problem with this dataset is many of the cell names are duplicated:

```r
library(scRNAseq)
sce <- ZilionisLungData('mouse')
length(unique(colnames(sce)))
[1] 2711
length(colnames(sce))
[1] 17549
```

This is unusual, and we require that within a Seurat object a cell name is unique to one cell. The issue here is that we are automatically renaming cells with conflicting names, but that renaming is not being performed on the dimension reduction object
