### ISSUE TITLE
Cannot join HTO libraries with different oligo sets

### ISSUE THREAD

**Issue by RoganGrant** [satijalab/seurat#6698]
I am trying to read multiple 10X libraries using the `read10X()` function. The libraries were run in two batches. Batch 1 was multiplexed with 4 samples per library (B0301 - B0304), whereas batch 2 was multiplexed with 5 samples per library (B0301 - B0305). I get the following error when I run the function:

` Error: Matrices must have same number of rows in cbind2(argl[[i]], r)`

I can easily re-run cellranger on batch 1 and just add B0305 and assume it will yield zero counts, however I can picture many cases where oligos will differ (and even overlap, but with different antibodies) between different batches for the same dataset. Alternatively, would it be possible to use a merge function instead of `cbind2` which can generate NAs or zeros for non-overlapping rows.

Sorry, normally I would have a reprex but I don't know how to reasonably generate one here.

**Comment by mhkowalski** [comment]
Hello,

Thanks for your question. I would suggest that you use the `read10X()` function separately for each library. You should especially do this because I would run HTO demultiplexing separately for each library, and then merge the remaining singlets after demultiplexing.  You can merge the two objects using the `merge`  function (see [here](https://satijalab.org/seurat/articles/merge_vignette.html)). 

We'll work on creating a more informative error message here.

**Comment by RoganGrant** [comment]
This makes sense, thank you!
