### ISSUE TITLE
Integration of Integrated objects

### ISSUE THREAD

**Issue by ejc043** [satijalab/seurat#6704]
Hello!! Thank you for the wonderful package! It is really helping my project move along. 
I am currently trying to integrate multiple sc atlases i.e. tabula sapiens, fetal development, etc. 
There are cases where the individual atlases have technical batch effects. For some atlases, I conducted `sctransform --> integration `to remove those batch effects. The atlases without observable batch effects just had `sctransform` normalization. 

How would the seurat team recommend integrating these integrated objects into one?

**Comment by mhkowalski** [comment]
Hello, 

Thanks for your question. 

I would split each atlas by batch and then integrate using SCTransform. For atlases without batch effects, you might also use the entire atlas rather than splitting by batch, which might be slightly more time efficient. I would not recommend trying to integrate the integrated assays, however.
