### ISSUE TITLE
merge and integrate 2 datasets, one with cell-cycle regress-out, one is not

### ISSUE THREAD

**Issue by trnguyenuka** [satijalab/seurat#6705]
Hello, 

thanks for developing this great tool!

I have a question regarding the `merge` function and the integration of datasets. At the moment, I have 2 datasets: one needs cell-cycle regress-out since the cell-cycle PCA/UMAP shows clearly distinct clusters based on cell-cycle. The other does not need that. So that I performed cell-cycle regress-out in only the first dataset. 

When I merge these two dataset using the function `merge` with the option `merge.data = TRUE`, the new merged Seurat object only has data slots `counts` and `data`, which means that I have lost the cell-cycle regress-out `scale.data` slot in the first dataset. 

I would like to ask: Is there any possible way to merge 2 Seurat objects and keep the `scale.data` slot? Or what would be the best practices for merging (and after that, integrating) 2 Seurat objects that have different scaling/normalizing strategies? 

Thank you and I'm looking forward to your response. 

Best regards,
H.N

**Comment by longmanz** [comment]
Hi @trnguyenuka ,
When using merge() to merge 2 seurat object, their individual scale.data slots are no longer valid. Because scale.data is the normalized data based on the variance and mean of each gene, and once you merge 2 obj into 1, the variance / mean for each gene will change. So you will need to redo the scaleData() step to obtain the new scale.data slot. 

Regarding your analysis, you can re-generate your scale.data slot for your merged dataset, by fitting the batch information (data 1 and data 2) and your cell-cycle score as 2 covariates. For example, run `ScaleData(..., vars.to.regress = c("cell_cycle_score", "Batch"))` . I will still recommend fitting cell-cycle score for your 2nd dataset to keep things consistent. However, if you do not want to, you can use 0 as the cell-cycle score for all the cells in your 2nd dataset.
