### ISSUE TITLE
PseudobulkExpression marked @export but not in NAMESPACE?

### ISSUE THREAD

**Issue by bbimber** [satijalab/seurat#6731]
PseudobulkExpression is marked with @export:

https://github.com/satijalab/seurat/blob/c4638730d0639d770ad12c35f50d19108e0491db/R/utilities.R#L1196

but it's not in NAMESPACE and therefore not exported. Is this on purpose?

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team so don’t know whether it’s intentional or not but the function documentation lacks the roxygen comment `#’` hence why it doesn’t appear in NAMESPACE.

If this is unintentional I’m happy to push PR to fix.

Beat,
Sam

**Comment by mojaveazure** [comment]
This is intentional, as none of the other documentation for `Pseudobulk` uses Roxygen-style comments (`#'`). While we may export it in the future, it's not in our pipeline at this time. You can use it in your scripts with `Seurat:::Psuedobulk` (note the triple-colon `:::`), but not in any downstream packages that are on CRAN or Bioconductor

**Comment by bbimber** [comment]
ok, thanks,
