### ISSUE TITLE
How to find out G0 phase cell in cellcyclescoring?

### ISSUE THREAD

**Issue by goubegou** [satijalab/seurat#676]
Hi seurat developer,in seurat CellCycleScoring function there seems only phase G1,G2M and S are avalible.Every cells are predicted to be one of these three phases. However, in our study, we want to focus on stable G0 cells. But these cells seem to be mixed in G1 cell in seurat.Can we find out G0 cell?  Thanks!

**Comment by satijalab** [comment]
As you say - we don't currently subdivide between G0/G1. This is because the two phases are quite similar transcriptionally, and its challenging to develop a clear gene set to distinguish. If you do have a gene set of G0 vs G1 markers, you can use AddModuleScore to score cells and distinguish. If you have success with this, let us know - and we'll consider adding this to the package.
