### ISSUE TITLE
FindConservedMarkers(): Error in marker.test[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by Jiayi-Zheng** [satijalab/seurat#6768]
Hi, I want to find the conserved markers between two clusters of two datasets in a integrated seurat dataset. 

I did: `markers = FindConservedMarkers(seu.combined, ident.1 = 'C6', ident.2 = 'Low_nCount', only.pos = TRUE, grouping.var = 'cell.ident', logfc.threshold = 0.25, min.pct = 0.25)`

My `cell.ident` is a column in the `seu.combined@meta.data` with multiple cluster labels including 'Low_nCount' and 'C6'. 

I got error message:
<img width="560" alt="Screen Shot 2022-12-07 at 5 34 54 PM" src="https://user-images.githubusercontent.com/90501211/206142328-7ffc409f-545a-48f8-81c8-853067d4c964.png">

Not sure what's happening here and why is it requiring my one cluster to be present in another cluster?

Thanks!

**Comment by Gesmira** [comment]
Hi, 
The issue is because your ident and `grouping.var` are the same. `FindConservedMarkers()` should be used to find markers that are conserved in your cell idents (for example cell types) across a grouping variable (for example datasets). Thus, the fix depends on what you are trying to accomplish with FindConservedMarkers. If you are looking for conserved markers for each of your clusters across datasets:
```
Idents(seu.combined) <- "cell.ident"
markers = FindConservedMarkers(seu.combined, ident.1 = 'C6', ident.2 = 'Low_nCount', only.pos = TRUE, grouping.var = 'dataset', logfc.threshold = 0.25, min.pct = 0.25)
```
