### ISSUE TITLE
Removing genes with Rpl from markers

### ISSUE THREAD

**Issue by jjo12** [satijalab/seurat#6777]
Hi All,

I am performing clustering using the SingleR package and manually. I tried to identify the cluster with SingleR, but it's all called bulk of T cells while Seurat recognizes them as different clusters.

To determine manually, I was wondering if I can calculate (or display) markers without 'Rpl-' or 'Rps-' identification to see if there are any other genes that pop up with more significance to a population based on ImmGen. I previously tried to correct ribosomal transcripts like mitochondria, but it did not yield a good amount of cells.

My code for one cluster looks like this:
`obj.5.markers <- FindMarkers(obj, ident.1 = 5, min.pct = 0.25)`
`head(obj.5.markers, n = 30)`

The resulting markers look like this:
> head(obj.5.markers, n = 30)
Rps24 
Tpt1   
Rps16
Rpl19 
Fau    
Rpl23
Rps27a 
Tmsb4x
Rpl27a
Rps9   
Rps12 
Rpl13  
Rpl32  
Rpl41  
Rpl18a
Rps4x  
Rps23  
Rps10  
Rplp1  
Rpl34  
Rps11 
Rps8   
Rps3a1 
Rps14 
Rpl17  
Rps5   
Rps20 
Eef1a1
Rps15a
Rps3

There are just too many Rpl- and Rps- genes and I was wondering if I can add a line to prevent markers from showing genes without ribosomal transcripts.

Thank you.

J

**Comment by alikhuseynov** [comment]
I think you can either exclude those genes from the test

```
genes2use <- rownames(obj)[-grep("^Rp[sl]", rownames(obj))]
obj.5.markers <- FindMarkers(obj, ident.1 = 5, min.pct = 0.25, features = genes2use)
```

or do test on all genes and filter them out using `dplyr` and `tidyverse` packages
```
obj.5.markers <- FindMarkers(obj, ident.1 = 5, min.pct = 0.25)
# filter out Ribo genes
obj.5.markers %>% dplyr::filter(stringr::str_detect(genes, "^Rp[sl]", negate = TRUE)) %>% head
# or keep only Ribo genes
obj.5.markers %>% dplyr::filter(stringr::str_detect(genes, "^Rp[sl]", negate = FALSE)) %>% head
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  I would add couple of notes.

What @alikhuseynov has said is correct.  Though personally I would caution against removing genes prior to testing and be careful about removing them post testing too.  Data is data and removing genes should (in my opinion) be thought of more as last resort vs other factors.

First, while excess ribosomal transcripts can be technical in nature you should be careful about equating ribosomal percentage to mitochondrial percentage (used as proxy for cell health/damage).  Increased ribosomal content can be due to biological change or normal differences between cell types.

Second, if you really don’t want them driving clustering (again it may be totally valid for them to do so) you could try removing them from variable features before PCA.

Finally, this could also simply mean that you need to adjust your PC selection/clustering.  It’s possible that data is over clustered and cluster defined by only these markers is result of suboptimal processing and requires different analysis before marker testing.

I will leave this issue open for now in case devs have any additional comments to add.

Best,
Sam

**Comment by jjo12** [comment]
Hi @alikhuseynov and @samuel-marsh,

I read both of your comments and they make sense. I've used SingleR implemented with ImmGen or TabulaMurisData. The cluster of concern with a lot of Rp[sl]- proteins identified as T cells and after combing through (I gave up after looking at first 100) and had some signature genes. I will probably use the removal of Rp[sl]- proteins just to summarize the signature genes because a lot of Rp[sl]- genes on ImmGen highlight all of the immune populations they got.

Thanks both of you 👍
