### ISSUE TITLE
FindMarkers automatically subsetting genes

### ISSUE THREAD

**Issue by carversh** [satijalab/seurat#6784]
Hi, I am finding that the FindMarkers functionality is automatically subsetting genes although I set it to consider all genes in the gene matrix (~20k genes). Any way you could let me know why this is happening?

```
all.genes <- rownames(Seuratobject)
Seuratobject.de.markers <- FindMarkers(Seuratobject, ident.1 = celltype, features = all.genes, test.use = 't')
```
Depending on what cell type I use as ident.1, different numbers of genes are returned on the same dataset, which doesn't make a lot of sense to me since I'm setting features to all.genes. 

Thanks in advance

**Comment by carversh** [comment]
It seems that this is the results:
```
Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
"No features pass logfc.threshold threshold; returning empty data.frame"
```

Therefore, this implies that this gene is not a differentially expressed gene because it doesn't pass the logfc threshold, meaning that there is a zero log fold change

**Comment by samuel-marsh** [comment]
Hi,

As I think you have discovered there are several thresholds in FindMarkers that subset the analysis/results.  You can see all parameters in documentation (https://satijalab.org/seurat/reference/findmarkers).  If you want to return all of the data you can modify those thresholds so that values for all genes are returned.

Best,
Sam
