### ISSUE TITLE
Suggestions in annotating cluster using FindTransferAnchors() and TransferData()

### ISSUE THREAD

**Issue by jeji0209** [satijalab/seurat#6790]
Hello.
I was trying to annotate my clusters using a reference matrix (specifically the Allen Brain Atlas Mouse 10x genomics data) by following https://satijalab.org/seurat/articles/integration_mapping.html this vignette of using the FindTransferAnchors() and TransferData() function.
The process has been fairly successful, as when I draw the proportion of cell type assigned for each of all cells assigned to my clusters, most clusters show a clear cell type.

`cell_type_count <- data.frame(table(seu.integrated$Cell_Type, seu.integrated$seurat_clusters))
colnames(cell_type_count) <- c("Cell_Type", "Cluster", "Freq")
data.frame(cell_type_count) %>% ggplot(aes(Cluster, Freq)) + 
  geom_bar(aes(fill = Cell_Type), stat = "identity") +
  theme_bw()`

This is the code I have used to draw the figure. 
<img width="626" alt="스크린샷 2022-12-16 오후 9 40 55" src="https://user-images.githubusercontent.com/90094328/208103058-6ad2dca5-5180-413e-b304-a7dc39e3fa15.png">

However, some of my clusters, (mainly cluster 6) has very mixed proportion of assigned cell types, and I am not sure about how to deal with this cluster. Any suggestions on methods to affirm the cell type for this cluster? or should the cluster just be stated as "ambiguous"?
Thanks in advance :)

**Comment by Gesmira** [comment]
Hi, 
For clusters that have been annotated as multiple cell types using the TransferData() method, if you are confident in your clustering, I would recommend a few possible steps to validate cell types: 

- running differential expression analysis with FindMarkers() and seeing which markers cluster 6 expresses. If it expresses multiple markers from different cell types, you would have to investigate if you should subcluster cluster 6 further or look at the quality of your cells. Otherwise, if it expresses the canonical markers of a specific cell type, you can call it that cell type with more confidence.
- visualizing the "Cell_Type" annotations on a umap plot using DimPlot() to see whether the cells of the same label cluster together 

For more tips, I would recommend looking at the vignettes on the seurat website such as https://satijalab.org/seurat/articles/pbmc3k_tutorial.html for info on annotating cells using gene expression data.
