### ISSUE TITLE
How to return test statistic and not just adjusted p value for FindMarkers test

### ISSUE THREAD

**Issue by carversh** [satijalab/seurat#6791]
Hi, for the FindMarkers function, how do I also return the test statistics?

Here is an example of the function call:
`morab.atac.de.markers <- FindMarkers(morab.atac, ident.1 = celltype, features = all.genes, test.use = 't')`

**Comment by longmanz** [comment]
Hi, 
Do you mean the test Z-scores (or T-scores since you are using t.test)? There is no explicit way to obtain test statistics directly from the function. But you may calculate that by converting the p-values (unadjusted) + sign information from fold-change into test statistics. An example command will look like this:
`z_score = qnorm(p_val/2, lower.tail=F) * sign(avg_log2FC)`
You may notice here we have Z-score instead of T-score (since you are using test.use = 't'). This is because we lack the information of the number of cells (observations) in the test, so we have to use Z-scores to approximate the T-scores.
