### ISSUE TITLE
Excluding TCR and BCR genes for 5' scRNA-seq analyses?

### ISSUE THREAD

**Issue by learning-MD** [satijalab/seurat#6798]
Has anyone been excluding TCR and BCR genes prior to normalization/scaling/clustering and downstream analyses when using **10x 5' chemistry** on human PBMCs? This paper and some that it references suggests so:

https://academic.oup.com/bfg/advance-article/doi/10.1093/bfgp/elac044/6874511

Asking, in part, because the majority of highly variable genes in my samples are TCR/BCR genes whether I select highly variable genes for each sample individually before merging or merge first and Normalize after. Using both the original NormalizeData, SCTransform, and SCTransform v2, there tends to be a cluster of cells that is largely defined by TCR/BCR genes and no other markers of typical immune cells. So, I'm leaning toward testing the exclusion of these genes from each individual sample prior to normalization, feature selection, clustering, etc. Wanted to get the thoughts of others. Thanks!

**Comment by trynkaLab-admin** [comment]
Hi,
the usual answer in scRNAseq: it depends. For my samples consisting of CD4 T cells I remove TRB and TRA genes, with exception of the MAIT/NKT cell ones - in this way all variable receptors won't  influence clustering and MAIT cells will be better separated.  For highly heterogenous samples with very variable T cells it should not be an issue.
NB. you do not have to exclude them at the normalisation step - just exclude them from the variable features:

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
