### ISSUE TITLE
Return list of genes tested in `FindMarkers`

### ISSUE THREAD

**Issue by lucygarner** [satijalab/seurat#6821]
Hi,

It would be really helpful if there was an option to return the list of genes tested in `FindMarkers`. I would like to use this as a background gene list for pathway (over-representation) analysis. Otherwise I need to calculate this manually for each analysis by filtering for genes expressed in a minimum percentage of cells in either of the two populations etc.

Best wishes,
Lucy

**Comment by samuel-marsh** [comment]
Hi Lucy,

Not member of dev team but hopefully can be helpful.  So in terms of the the adj. p-value (which I believe is what you are referring too) the answer is it is simply against all genes/features in the dataset (See https://github.com/satijalab/seurat/issues/905#issuecomment-434537989).

You can also see this by running something like this which shows the results for GZMB is identical between the conditions.  
```
markers <- FindMarkers(object = pbmc, ident.1 = "B", ident.2 = "NK")

markers_one <- FindMarkers(object = pbmc, ident.1 = "B", ident.2 = "NK", features = "GZMB")
```

As mentioned in that comment above `FindMarkers` does subset the dataset depending on the threshold parameters used and whether or not the `features` parameter is used.  This speeds up the testing depending on those values but does not change that the multiple comparison significance testing is done against all features in the dataset.

If you want to return a dataframe containing all features and their associated values you can simply modify the threshold parameters so that everything will be returned.

Hope that answers your question but if not let me know!

Best,
Sam

**Comment by lucygarner** [comment]
Hi Sam,

Thank you for the detailed answer. I am actually looking for the list of tested genes rather than the calculation for the adjusted p-value.

Best wishes,
Lucy

**Comment by lucygarner** [comment]
Looking at the code, maybe the current `FindMarkers` function already returns all tested genes?

**Comment by samuel-marsh** [comment]
Yes the specifically tested features as determined by thresholds set will be tested and returned but their padj is corrected vs all features in dataset.

However, in my opinion (note I don’t do ton of pathway analysis because I don’t really like it lot of the time) you may want to liberal with those thresholds in terms of background for pathway analysis (in particular would set  no lfc threshold). Then use post-test padj and lfc thresholds to call background vs sig genes.  Just thinking about it you might not want to restrict your background genes too much (even if it slows down the actual DE function).  

Best,
Sam

**Comment by lucygarner** [comment]
Yes, agreed. Thank you.

**Comment by lucygarner** [comment]
Hi @samuel-marsh,

I changed the `logfc.threshold` to 0 and compared the results with those obtained using `logfc.threshold` = 0.25. I got a much longer list of genes with p_val_adj < 0.05 with the former, and the adjusted p-values for a given gene were not identical across the two approaches. I am using `MAST`.

Best wishes,
Lucy
