### ISSUE TITLE
Calculating Perturbation Signature on Integrated Data

### ISSUE THREAD

**Issue by shahrozeabbas** [satijalab/seurat#6881]
Hi,

I had a question about a dataset that is integrated using rpca. I have corrected for batch effect but would like to follow up with `Mixscape`. However, I am currently unsure about the input parameters for `CalcPerturbSig` and if I should use the `integrated` assay or `RNA` assay. Would it be valid to use the `RNA` assay but use the integration features along with a `pca` reduction calculated from the `integrated` assay? It could also be possible to run `Mixscape` on each individual batch to obtain KO labels, then integrate. 

I think there could be multiple approaches, but I would appreciate any insight that could be given for this type of analysis. Perturbation signature is calculated by comparing the mRNA expression profiles from control cells and targeted cells using the nearest neighbors algorithm. I wonder if batch effect would confound this calculation. Appreciate any thoughts you might have, thanks!

Shahroze

**Comment by longmanz** [comment]
Hi,
I personally would recommend running Mixscape individually for each batch. There is a "split.by =" flag in CalPerturbSig() and RunMixscape() function, where you can specify the column for batch information in your meta.data so that the Mixscape will run for each batch individually. Please use RNA assay and PRTB assay, but not the Integrated assay.

Best,
Longda
