### ISSUE TITLE
Integration approch

### ISSUE THREAD

**Issue by AvitalPo** [satijalab/seurat#6913]
Hi,

I have a dataset of B cells from three patients. For the dataset analysis, I've integrated the data using the regular integration approach.

Now I would like to compare my dataset with a publically available dataset of B cells, also from different donors (7) but with a different condition. The available dataset is also integrated. 

How should I integrate integrated objects? I saw some questions but couldn't find something that really answered my question.
I think that if I just integrate the two integrated objects, I will remove the patient integration of each dataset. If I treat each sample as an object (so overall, 7+3=10 samples) and integrate everything, I will not consider the different conditions (at least, this is my filing).

The aim is to see whether the B cells are the same between the conditions. I can use the data from the paper as a reference, but what will happen if in my dataset there is a unique subpopulation that doesn't exist in the reference dataset? Will those cells will be forced on the reference UMAP? Or with a specific "label" (cell type from the reference).

Thanks!

**Comment by f6v** [comment]
I think you can try to integrate all objects from your three patients as one batch, and all seven from other patients as a second batch. Thus, you'll have two batches. 

There're other tools like scVI that allow more complex strategies with nested batches. But keep in mind that comparing conditions that are all in different batches is not very sound since you can't distinguish technical and biological differences.

**Comment by mhkowalski** [comment]
Hello, 

We don't recommend that you run integration on the integrated assay data. Rather, I would separate each donor from both the publicly available data and your data and try integration. If you want to control the order of integration (to integrate all of the donors from one condition first, please see details in the `IntegrateData` documentation.

As you mention, you could also try reference mapping rather than integration. Reference mapping will force a unique subpopulation from the query data onto the reference UMAP, but you can address this by computing a new UMAP based on both the reference and the query after mapping, as demonstrated [here](https://satijalab.org/seurat/articles/multimodal_reference_mapping.html)
