### ISSUE TITLE
Batch integration in the reference before bridge mapping

### ISSUE THREAD

**Issue by alitinet** [satijalab/seurat#6929]
Hi @yuhanH,

I want to map ADT data onto a RNA reference using bridge. I have 6 samples in the reference, so I first normalize data with SCTransform and then perform integration following this [vignette](https://satijalab.org/seurat/articles/integration_introduction.html#performing-integration-on-datasets-normalized-with-sctransform-1). Then when I try to run
```
obj.rna.ext <- PrepareBridgeReference(
    reference = ref.combined.sct,
    bridge = cite,
    bridge.query.assay = "ADT",
    reference.reduction = "pca",
    reference.dims = dims.rna,
    normalization.method = "SCT",
    verbose=FALSE
)
```

I get the following error
`Error: Given reference assay (SCT) has 6 reference sct models. Please provide a reference assay with a  single reference sct model`.

How do I need to perform the integration of the batches in the reference, so I can use it later with bridge?

**Comment by yuhanH** [comment]
Hi, 
This issue is related with the RNA reference default assay. This can be resolved by changing your reference's default assay to 'integrated' (any name for your integrated assay).
There are also some other parameters that need to be modified. You can have a look at this issue https://github.com/satijalab/seurat/issues/5697.
