### ISSUE TITLE
FindClusters error: java.lang.OutOfMemoryError (Same as closed issue #242)

### ISSUE THREAD

**Issue by lmurrow** [satijalab/seurat#693]
I am having the same problem as closed issue #242, but I am using the latest version of Seurat (2.3.1). When running FindClusters on a ~48,000 cell dataset (object size ~11 Gb) I get the following error message:

```
> Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
> 	at ModularityOptimizer.readInputFile(ModularityOptimizer.java:211)
> 	at ModularityOptimizer.main(ModularityOptimizer.java:74)
> Error in file(file, "rt") : cannot open the connection
> In addition: Warning message:
> In file(file, "rt") :
>   cannot open file '/var/folders/cw/v18jq9l16p13ngn35h9vxlmw0000gn/T//RtmpSHYd21/file3a5b75d22951_output_79803.txt': No such file or directory
```

I am running R version 3.4.4 in R Studio (10.0.143) on a Mac OS 10.13.3.

```
> packageVersion("Seurat")
[1] ‘2.3.1’

> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.4                         
year           2018                        
month          03                          
day            15                          
svn rev        74408                       
language       R                           
version.string R version 3.4.4 (2018-03-15)
nickname       Someone to Lean On          
```

**Comment by evolvedmicrobe** [comment]
It's quite possible your machine doesn't have enough RAM for you to run this analysis, in which case you will need to find a different machine.

However, it's also possible Java is running with a memory restriction.  It varies by which version of Java is being run, but in general Java programs are not allowed to use all of the system memory unless they are explicitly given this option at the command line.

Recently, this java clustering was added directly to Seurat to use C++ instead of Java, and this may allow you to work around the Java imposed (but not hardware imposed) memory constraints.  You can install this version for testing with:

    install.packages("devtools")
    library(devtools)
    install_github("satijalab/seurat", ref="develop")

**Comment by satijalab** [comment]
Our most recent CRAN release should also include Nigel's C++ version (thanks again!), which should fix your problem. Just make sure to re-install Seurat to ensure you have the latest version.
