### ISSUE TITLE
Unbalanced number of cells between samples

### ISSUE THREAD

**Issue by albertop210** [satijalab/seurat#6946]
Hi Seurat team,
we are analyzing some scRNA-seq data of patients samples. In detail we have 6 samples, of which 1 (call it sample A) is ~7000 cells and the other 5 are ~3500 cells.
Is there a bias on analyzing data, as the number of cells between samples is "unbalanced"? 
Would the UMAP and its communities be affected/biased by the unbalanced number of cells of sample A, or can we assume that cells are representative of all communities?
If this is not the case, should we downsample the object keeping also for sample A the same number of cells that the other patients have (i.e. using `subset(object, cells = sample(Cells(object), 3000))`? 

Thanks in advance for your kind response,

Alberto

**Comment by nathan-nakatsuka** [comment]
Hi Alberto, yes there will be some bias in the UMAP, because the more highly represented sample (sample A in this case) will be more emphasized in the UMAP (see for example: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6853336/). That said, you do not need to downsample sample A, because for most analyses it should not affect the results. There perhaps might be some minor biases in some differential expression analyses if you are pseudobulking on an individual level, because you will have less drop-out in sample A than in the other samples so there might be a minor bias against lowly expressed genes in the other samples. You can try to downsample sample A and see if the results are affected for differential expression analyses, but there likely won't be much difference between them.

**Comment by albertop210** [comment]
Thanks a lot for your kind reply Nathan, I will go on with the whole sample and eventually try also a downsample to see the effects in a differential expression analysis.

**Comment by ankita86** [comment]
@albertop210 : I was searching for a thread that discussed the impact of downsampling on the analysis and found this one. I have a same issue where one group has more cells (substantially higher) than the other. Just wandering, did you find any biases if you use the whole dataset vs downsampled?
