### ISSUE TITLE
the error of FindIntegrationAnchors

### ISSUE THREAD

**Issue by crystal0721** [satijalab/seurat#6954]
hello terms；
Thanks for this great R packages for scATAC-seq. we had one question about scATC subcluster analyis. We had 28 samples and when we subset lymphoid cells for subclustering analyis，while there were less than 50 cells in some samples，and got an error at "FindIntegrationAnchors" function. The error is as follows:

Error in rbind(Embeddings(object = object.1[[reduction]]), Embeddings(object = object.2[[reduction]])) :
number of columns of matrices must match (see arg 2)
Calls: FindIntegrationAnchors ... resolve.list -> signalConditionsASAP -> signalConditions
In addition: Warning message:
No filtering performed if passing to data rather than counts
Execution halted

```r
# insert reproducible example here
```

**Comment by Gesmira** [comment]
Hi, 
I would recommend combining the clusters that have less than 50 cells or removing them from the integration workflow. Based on the error, I am assuming you ran dimensional reduction outputting 50 dimensions, but since you have less cells than dimensions you are running into the error. Running integration with samples with very small numbers of cells can lead to some downstream problems.
