### ISSUE TITLE
Usage of DietSeurat() says 'The default assay is slated to be removed, please change the default assay'

### ISSUE THREAD

**Issue by Jiayi-Zheng** [satijalab/seurat#6956]
Hi, I'm trying to slim down a seurat object by:
`seu = DietSeurat(
    seu,
    counts = TRUE,
    data = TRUE,
    scale.data = TRUE,
    features = TRUE,
    assays = 'RNA',
    dimreducs = 'umap',
    graphs = NULL,
    misc = TRUE
)`

`> seu@active.assay
[1] "RNA"`

However, it keeps telling me:
`Error in DietSeurat(seu, counts = TRUE, data = TRUE, scale.data = TRUE,  : 
  The default assay is slated to be removed, please change the default assay`

I tried changing `assays = 'RNA'` to `assays = NULL` or `assays = FALSE`

I'm not sure what's the origin of this error message (like what is it actually saying)?

Meanwhile... If I would like to remove the PCA reduction data manually, what should I do? I tried `seu@images$pca = NULL` and doesn't seem to be the right answer.

Thank you!

**Comment by yuhanH** [comment]
hi @Jiayi-Zheng 
You would better not use `@` for operations in Seurat object, because `@` will pass all our designed checking functions. 
When you need to change the default assay, you can use `DefaultAssay` function such as `DefaultAssay(obj) <- 'RNA'`.
In your case, you can set PCA reduction to NULL. `obj[['pca']] <- NULL`
