### ISSUE TITLE
How to obtain the same clusters as when performing clustering on RNA GEX vs on loom's "spliced" in RNA Velocity analysis?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6959]
In the tutorial for RNA velocity analysis (http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/scvelo.html), which was what @mojaveazure in issue #3423 advised to do, it performs clustering on "spliced" counts of the loom objects. 

Thus, I tried to subset the same cells and genes from the loom objects matching with the cells and genes from my GEX Seurat object and perform the same clustering workflow. **My aim is to have the same clusters by performing clustering workflow on the "spliced" counts from loom objects; however, instead I obtained different clusters compared to those I got from performing the same clustering workflow on GEX "RNA".** 

**QUESTION 1.** How should I process loom objects so that we can directly connect the trajectories onto the original clusters of the GEX object? 

**QUESTION 2.** Do we expect the clusters generated by GEX (i.e., `cellranger count` outputs) and the clusters generated by setting `bm[["RNA"]] <- bm[["spliced"]]` (i.e., performing clustering on "spliced" counts) to be the same/similar? 

Thank you for your help!

Related to #6863, #6869 and #5318

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
