### ISSUE TITLE
Which slot is the default and preferred slot to subset cells based on protein/RNA expression in CITE-seq data?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#6990]
Hi, 

I perform `subset()` on my Seurat CITE-seq object after doing `DefaultAssay() <- 'ADT'`. 

I aim to have cells that expressed a marker either at a protein or RNA level. 

Q1. Would you mind advising to subset cells based on protein/RNA expression level, should I pull the expression from `counts`, `data` or `scale.data`? 

Q2. Is it correct that:

if I just want to subset cells with yes or no expression, I can subset based on counts (unnormalized)?

If I want to subset cells that are the top 10% expressors of a marker, then I should subset cells based on data (normalized)? 

Q3. Is there a situation when we will subset based on `scale.data`?

Thank you!

**Comment by yuhanH** [comment]
hi 
I would suggest you subset based on data slot. For ADT assay, the count matrix is not sparse due to the antibody unspecific binding. Yes or no expression for ADT is not a good metric. 
In most cases you could not subset by scale.data for ADT, because it is just the centered and standardized data slot.
