### ISSUE TITLE
How to incorporate FDR into Differential expression testing?

### ISSUE THREAD

**Issue by donaldn1995** [satijalab/seurat#6994]
Hello, I have done differential gene expression testing on my dataset using the default on Seurat (wilcoxon) which from my understanding uses bonferroni method to correct and produce P Val Adj. I would like to use MAST on my dataset and have followed the vignette but do not see anywhere where I can add FDR correction. Is there a way to do this within Seurat? I saw a protocol (https://star-protocols.cell.com/protocols/695) that implied FDR is already added for MAST PValAdj. Is that correct? Thank you, I really appreciate the work that has gone into making Seurat so user friendly!

**Comment by longmanz** [comment]
Hi, 
It is not recommended to use FDR-based correction methods (as stated in the manual of FindMarkers()). This is because Seurat pre-filters genes using the arguments like `logfc.threshold = 0.25` or `min.pct = 0.1`, reducing the number of tests performed. The reduced number of tests should still be accounted for, but FDR-based methods cannot do that. 
That being said, if you still want to apply FDR-based methods, you can certainly do it on your own. Just input the raw P-values you get from your MAST test, e.g., `p.adjust(p = MAST_results$p_val, method = "BH")` .
