### ISSUE TITLE
Unable to get same p value as reported in FindMarker function result 

### ISSUE THREAD

**Issue by me37uday** [satijalab/seurat#7006]
Hi all,

Let's say I want to make a boxplot for the following highlighted gene in the figure with the same reported p-value: 

![image](https://user-images.githubusercontent.com/32290365/222541517-0c5e5599-bb1b-422a-8b99-e91e8543b196.png)

The column format is as follows : gene symbol, pct.1, pct.2, avg_log2FC, p-value, adj_p_val, gene name

How can I achieve this? 

So far, I have tried the following : 

```
#The table above was obtained by running the following chunk of code 

DefaultAssay(seurat_obj) <- "RNA"
x <- FindMarkers(seurat_obj, min.pct = 0.1, logfc.threshold = 0, ident.1 = "KO", ident.2 = "WT")

library(ggpubr)
library(ggplot2)

expression_df <- data.frame(
     gene = rownames(seurat_obj@assays$RNA[c("dlx6a"), ]),
     condition = seurat_obj$orig.ident,
     celltype = seurat_obj$celltype,
     expression = as.numeric(seurat_obj@assays$RNA@counts[c("dlx6a"), ])
 ) 

ggplot(expression_df, aes(x = celltype, y = expression, fill = condition)) +
     geom_boxplot() +
     scale_fill_manual(values = c("WT" = "#00BFC4", "KO" = "#F8766D"), name = "Condition") +
     xlab("Cell Type") +    ylab("Expression") +
     stat_compare_means(method = "wilcox.test") + ylim(0, 5)

```
I get the following plot : 

![image](https://user-images.githubusercontent.com/32290365/222543369-66162c46-d673-4575-8194-b4da765df525.png)

And when I run the following : 

`VlnPlot(seurat_onj, features = c("dlx6a"), split.by = "orig.ident", assay = "RNA") + stat_compare_means(method = "wilcox.test")
`
I get : 

![image](https://user-images.githubusercontent.com/32290365/222545688-a55428dd-e64e-4cbb-8aee-d35c39a833e5.png)

Three different p-values on all three different occasions. Very curious to know what I'm doing wrong. Any help/suggestions would be much appreciated!

**Comment by longmanz** [comment]
Hi,
For the first P-value (listed in your Excel table), I cannot tell what is the problem. How did you get the P-values in that table? Is it also from the Wilcoxon rank sum test in Seurat?
For the 2nd P-value, since you are using data from the 'count' slot (seurat_obj@assays$RNA@counts), this is inappropriate. You should use data from your 'data' slot (seurat_obj@assays$RNA@data) after you run NormalizeData(). But I do notice that the data you extracted from your 'count' slot is not 'count' (i.e., integers). You might need to check what is going on with your count slot. 
For the 3rd P-value, it looks okay. The VlnPlot() by default uses the 'data' slot. The discrepancy between your 1st and 3rd P-values might be driven by the issue in your count slot I described above.

**Comment by jhjiang2020** [comment]
Hi, I came across the same issue recently when trying to add `ggpubr::stat_compare_means()` on top of the violin plot. After a closer inspection of my ggplot object, I realized that by default Vlnplot add a small noise for better visualization, which will affect the wilcox.test result especially when a large number of cells have the same value. It also affects the shape of violins (see #5756).  

A quick solution would be to set `add.noise=FALSE`, and then feed the unmodified data to `stat_compare_means`

**Comment by longmanz** [comment]
Thanks @jhjiang2020! That is a good catch. Yes, the discrepancy between the 1st and 3rd P-values could come from the "add.noise" in VlnPlot. Setting add.noise = F should fix the issue. 
The 2nd P-value is driven by using the wrong slot ('count'). Switching to 'data' slot should fix it.
