### ISSUE TITLE
SCTransformed data to scale or not?!

### ISSUE THREAD

**Issue by asilvestris84** [satijalab/seurat#7018]
Hi,
I have a problem with the analysis of my 10x dataset on a sorted population of T-cells: when the data is not scaled, a lot of very strange subpopulations are generated with the only marker being one of the TRBV genes; I'm using to assign the cell type a reference of multimodal PBMC (Azimuth) which is normalized with SCTransform and therefore I'm "forced" to normalize my data in the same way; the default setting of SCTransform is scale.data FALSE and therefore I obtain the subpopulations that do not appear with scale.data TRUE or with the normal normalization procedure, scaleData and findVariable features; so my question is why the default setting of SCTransform is scale.data FALSE (and you recommend not to change this parameter) if the normal practice of Seurat analysis before SCTransform was introduced was always to scale data? What do you advise me to do to analyze my data in the best way?
Thanks
Alessandro

**Comment by saketkc** [comment]
I am not entirely sure what you are asking, but if the question is why is `do.scale=FALSE` by default in SCTransform  - this is because we want to retain the variance of the residuals (instead of forcing them to be 1) - this makes sense because the perason residuals already achieve variance stabilization (i.e. get rid of the usual mean-variance relationship you notice in raw counts).

Azimuth mapping uses the reference model to calculate the residuals. If you can provide more details about what you are trying to achieve and paste the code here, it would be helpful.

**Comment by saketkc** [comment]
Closing as I haven't heard back.
