### ISSUE TITLE
A question about loading PCA matrix into SeuratObject

### ISSUE THREAD

**Issue by Kevinckyy** [satijalab/seurat#7042]
Hello, I encountere some problems with importing PCA reduction data into a SeuratObject. Hope that you could help me dealing with it, thanks !
Now I have a matrix including the PCA coordinates, which is named as `correct_pcas`. Then I want to take this as the PCA reduction component of a SeuratObject named as `atlas`, this is my code:

```R
> correct_pcas$all[1:5,1:5]
             PC1         PC2        PC3       PC4      PC5
cell_1  4.939742  -1.5143608 -0.9350627 -4.063321 4.582803
cell_2  4.610650  -0.4930892 -0.2712987 -5.043434 4.310679
cell_5 -8.328844 -11.7581931 -1.0229377 15.876421 6.425218
cell_6  4.265451  -1.3810930 -1.4368237 -5.567990 5.709955
cell_8  4.363276  -1.9405133 -1.7313952 -5.472438 4.632083

> atlas@reductions$pca <- correct_pcas$all %>% as.matrix %>% 
            CreateDimReducObject(embedding = .,assay = DefaultAssay(atlas),key = "PC_")
```
But after running the code, `atlas@reduction$pca@feature.loadings` is still an <0 x 0 matrix> 
```R
> atlas@reductions$pca@feature.loadings
<0 x 0 matrix>
```
The absent of feature.loadings will prevent me from making a label transfer like this :
```R
TrAnchors = FindTransferAnchors(
                                    reference = atlas,
                                    query = obj,
                                    normalization.method = "SCT",
                                    reference.reduction = "umap",
                                    dims = 1:50)
```
Running this code will just get an error:
```R
Normalizing query using reference SCT model
Projecting cell embeddings
Error in Loadings(object = reference[[reduction]])[features, dims] :
  subscript out of bounds
```

So I wonder if there is any way to calculate the feature.loadings matrix from cell.embeddins matrix.

**Comment by saketkc** [comment]
`CreateDimReducObject(embeddings=embeddings, loadings=loadings)`

**Comment by longmanz** [comment]
Hi, 
Since you ran this command:
`atlas@reductions$pca <- correct_pcas$all %>% as.matrix %>% 
            CreateDimReducObject(embedding = .,assay = DefaultAssay(atlas),key = "PC_")`
You only imported the cell embeddings, but not the feature loadings. 

I am not sure how you obtained your PCAs, but usually you should have both the loadings and embeddings. If so, you must simply specify them both in the CreateDimReducObject() as followed:
`CreateDimReducObject(embeddings = as.matrix(correct_pcas$all), loadings = as.matrix(correct_pcas$loadings), key = "PC_")`

Or if you do not have the loadings and only the embeddings, you will need to first figure out how the PCA was actually done (what genes/features were used, any scaling, your eigenvalues, etc.), and then you might be able to calculate the loadings. For example:
X = U %*% S %*% V    =>       t(US) %*% X = V
X is the original gene expression matrix (rows are the selected features);
U is the embeddings;
S is a diagonal matrix with each diagonal element being sqrt(eigenvalues);
and V is the feature loadings matrix you want. 

I will not suggest you calculate the loadings by yourself. It'd be better to retrieve it from your PCA algorithm.
