### ISSUE TITLE
Choosing  Normalization method

### ISSUE THREAD

**Issue by Sahu-Mousumi** [satijalab/seurat#7050]
HI! I have a question related to Seurat. Will it be correct to go with "RC" normalization method and use the normalized values to identify differentially expressed genes using NormalizeData()? I know usually log normalized method is used. But, using log normalize values I am getting only couple of down-regulated genes for my comparison . 
Thanks! 
Mousumi

**Comment by longmanz** [comment]
Hi, 
Usually we recommend using log-normalization because it has the advantages as followed:
1. Variance stabilization: scRNA-seq data is inherently noisy, and the counts can have high variability due to technical factors and biological heterogeneity. Log-normalization helps stabilize the variance across different expression levels. It reduces the influence of highly expressed genes and amplifies the signal from lowly expressed genes, allowing for better identification of differentially expressed genes and improved downstream analysis.
2. Interpretability: Log-normalization makes the data more interpretable by transforming the count data into a log scale, which is more in line with how researchers usually think about fold-changes in gene expression. This is especially useful when comparing gene expression across different cell types or conditions, as fold-changes are more meaningful than absolute differences in counts.
3. Handling zero counts: A significant proportion of scRNA-seq data may contain zero counts for some genes in certain cells due to dropout events (i.e., failure to detect lowly expressed genes). Log-normalization typically adds a small pseudocount to the raw counts before taking the log transformation, which helps handle zero counts and reduces the impact of dropout events on downstream analysis.

Using "RC"only divide the count with a cell's total count, but without the log1p step as in log-normalization. It is definitely okay to use RC, but you should do it based on the fact that it is appropriate for your data. You should Not do it because it gives you more DEGs.
