### ISSUE TITLE
Hybrid approach of integrating and merging

### ISSUE THREAD

**Issue by me-orlov** [satijalab/seurat#7066]
Hello and thank you for your very detailed support for the Seurat package! I have learned a lot from browsing here. Unfortunately, I am very new to scrnaseq and can’t find exactly the answers I’m looking for. 

My experimental set-up is such that I have a number of control samples (9) and treatment samples (11), each one coming from a different patient. The samples have different sequencing depth and have not been run through cellranger aggr. The treatment samples are strongly suspected to contain some cell types not found in the control groups. To control for technical variation and patient-related effects, I originally intended to use RPCA and integrate across all the samples, using all the control samples together as a reference. I opted for using a reference due to computational constraints. Unfortunately, having done the analysis as planned, I am concerned that this approach is not finding clusters associated with the cell types present only in the diseased state and am worried about the loss of biological variation. I am wondering whether such an approach was appropriate.

As a result, I thought to perform a hybrid approach, as indicated here (https://github.com/satijalab/seurat/issues/2468) and integrate the control and treatment samples separately, followed by merging. I would love more guidance on how to do so. My questions are:
1) Are there problems with merging integrated data? (see https://github.com/satijalab/seurat/issues/5890). I have simply used the default merge command to do so. 
2) After applying merge, can I use the "integrated" assay for the UMAP? When I attempt to do so, I get an error about missing variable features. Is there an optimal way to address this and re-obtain them? I'd like to use the final merged object for clustering.
3) Would calling PrepSCTFindMarkers on the final object make it acceptable to run DE using its "SCT" assay?

Thank you in advance for your help!

**Comment by longmanz** [comment]
Hi, 
To integrate multiple samples from different conditions could be challenging and there is probably no gold-standard answer. 
Re 1). Merging after integration is reasonable. But one problem is that have you observed any bizarre clusters in your final UMAP? If there is substantial batch effect between your two conditions, simply merging your treatment and control groups might not be optimal. 
Re 2). You are right. Since the integration for your treatment and control groups are done separately, their "integrated" assays are not consistent (different genes are used), as well as their VariableFeatures. 
Re 3). It is not recommended to do DE test using the integrated assay. We only recommend doing DE test with the RNA assay or the SCT assay that derived from RNA assay. 

What I would recommend you to do is to Integrate your treatment groups to your control groups, rather than merging. With Seurat v5 you may do it with just one line of command: https://satijalab.org/seurat/articles/seurat5_integration.html . You can try the default "CCAIntegration" or the "HarmonyIntegration" for such integration.

**Comment by me-orlov** [comment]
Thank you very much for your help!

**Comment by apal6** [comment]
Hi @longmanz 

I have a similar experimental design. (9 samples in three conditions). Following up on your statement "have you observed any bizarre clusters in your final UMAP?", yes I do see a cluster that is dominated by one sample in one condition. 
I performed integration using CCA and the UMAP seems to look well integrated at sample level as well as condition level.

How to account for this one cluster that is dominated by one patient?

Thank you,
Aastha
