### ISSUE TITLE
Counts to FPKM

### ISSUE THREAD

**Issue by Boehmin** [satijalab/seurat#7075]
I was wondering if there is an integrated feature to transform counts to FPKM. I require counts from our snRNA-seq data so I can compare this with available FPKM data. Also the MERSCOPE probe design tool requires FPKM values.

Many thanks for your help!

**Comment by longmanz** [comment]
Hi, 
In Seurat package we do not have such function to convert raw counts to FPKM. Since sc-data are generally UMI-based data, the assumption of FPKM is not satisfied. 
But since FPKM data can be viewed as normalized counts, a log-normalized count data (from Seurat) and your FPKM data are still comparable.
