### ISSUE TITLE
differential gene expression analysis 

### ISSUE THREAD

**Issue by merveyrc** [satijalab/seurat#7076]
Hello,

Specifically, I have an integrated Seurat object and I used the "FindMarkers" function to generate a list of differentially expressed genes between two conditions (diseased and control) of one cluster (NK.degs <- FindMarkers(PBMC.integrated, ident.1 = "NK_ctrl", ident.2 = "NK_stim"). I also saved the gene expression data for the two conditions separately as CSV files.

However, when I manually applied a t-test to expression data for a gene that was not included in the DEG list, I found a p-value of 3.30E-10. I also noticed that one of the genes in the DEG list had a p-value of 5.11E-07, and I am wondering why my gene of interest was not included in the DEG list. Additionally, I noticed that some genes have an adjusted p-value of 1, but I am unsure why they were included when the default threshold is 0.05.

Could you please help me understand why these discrepancies might be occurring? I would greatly appreciate any insight you can provide.

**Comment by longmanz** [comment]
Hi, 
1. When you run FindMarkers(), you will need to set your Idents to "RNA" assay (e.g., `Idents(seurat_obj) = "RNA"`). Or, you can specify this in FindMarkers(..., assay = "RNA"). Using "integrated" assay is not appropriate. 
2. In addition, please make sure you are using the appropriate data slot. Usually "data" slot is recommended for FindMarkers(). 
3. The default method.use in FindMarkers() is Wilcoxon rank sum test, which is a non-parametric 2-sample 't-test'. It is more preferred than a standard t-test, because sc-RNA data usually does not meet the normality assumption for standard t-test. You are likely to observe inflated p-value from a standard t-test as the variance of the test statistics is usually underestimated.

**Comment by merveyrc** [comment]
Thank you so much for your quick response. I did not mentioned but I already was set to my Idents RNA assay and I used data slot as you explained. Also, except for ttest, which I applied manually, when I added test.use="t" to the function, there was no change in the DEG list. Also, apart from this question, I wonder how genes with adj p value of 1 can be found in the DEG list?

**Comment by longmanz** [comment]
Hi @merveyrc ,
I see. Thanks for your information. 
1. In that case, your genes of interest might have got filtered out by FindMarkers(), because by default FindMarkers() will remove genes with log-fold-change <= 0.2 or with minimum proportion <= 0.1 (in either of the 2 groups of cells). You can manually set them to a different value in FindMarkers() to include more genes into your DE test.
2. The adjusted p-values are calculated based on Bonferroni correction (i.e., adj_pval = raw_pval * total_number_of_genes). If the adj p-value exceeds 1 the after this correction, it will be set to 1.  *However*, this does not lead to missing genes. Your missing genes are usually removed because of step 1, not the adjustment of p-value.

**Comment by longmanz** [comment]
Hi, 
Please use logfc.threshold = 0 instead of "NULL". This should fix the issue. 
Other filtering in FindMarkers() include min.pct, min.cells.feature, and min.cells.group. Usually you do not need to alter these filtering criteria, but feel free to do so if you are still missing your gene of interest.
