### ISSUE TITLE
QC check for single-cell data (scRNA-seq) integration

### ISSUE THREAD

**Issue by inayat45shaikh** [satijalab/seurat#7120]
Hi all,
I am trying to integrate single-cell data from independent studies and from differential treatment outcomes such as drug resistant & sensitive. I have done the integration and this is how integrated data looks.
 
![integrated_data](https://user-images.githubusercontent.com/39797483/229755701-1e231273-36a0-42bb-9f66-bdbb887ca6c4.png)

As per my understanding the integrated clusters is expected to be a mix of independent samples (After integration umap in above fig) and not as separate cluster for each sample  (Before integration umap in above fig). Additionally, the integrated cluster also expected to be annotated as one cell type  (bottom cell type annotated umap in above fig) and not same cell types spread across different clusters.

I would appreciate your response on my integrated data, and whether this looks fine or need further optimization.

Many Thanks
Inayat

**Comment by Gesmira** [comment]
Hi Inayat, 
Sorry for the delay in responding here. It is difficult for us to give a concrete answer without having a thorough understanding of your data, but based on what you have shared, yes - Before integration the samples look to be clustering by sample, and after integration the samples are more thoroughly combined. Since the same cell types are mostly clustering together, it seems integration worked well to combine the same cells.  

You can reference our `FindIntegrationAnchors` function to look into changing parameters to see how they might affect the strength or quality of integration. It is hard to determine if an integration is "good" or "bad" as it's dataset dependent.

**Comment by inayat45shaikh** [comment]
Thanks @Gesmira for sharing your view on this.
Yes, i have used FindIntegrationAnchors function for integration and you rightly said, i could look further with changing its parameters to see if this improve integration.

Thanks
Inayat
