### ISSUE TITLE
Fail to install SeuratV5 on LINUX

### ISSUE THREAD

**Issue by YYYYYWWWYYYYYY** [satijalab/seurat#7127]
Hi,I was trying to download seurat v5 using 'remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("satijalab/seurat", "seurat5", quiet = TRUE)'; and I met the error below: 
~~~
installing to /tmp/Rtmps1Y5EW/Rinst10f75b43549f/00LOCK-SeuratObject/00new/SeuratObject/libs
** R
Error in parse(outFile) : 
  /tmp/Rtmps1Y5EW/Rbuild10f77f3bac47/SeuratObject/R/assay.R:233:13: unexpected input
232:     expr = Layers(object = object, search = layer),
233:     error = \
                 ^
ERROR: unable to collate and parse R files for package ‘SeuratObject’
* removing ‘/tmp/Rtmps1Y5EW/Rinst10f75b43549f/SeuratObject’
      -----------------------------------
ERROR: package installation failed
STDERR:

Error: Failed to install 'Seurat' from GitHub:
  Failed to install 'SeuratObject' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.
~~~
My R version is 4.0.5 and rlang is 1.1.0. May I ask how to solve this problem?
Thank you very much!

**Comment by saketkc** [comment]
Can you update your R to 4.2 or higher and retry?

**Comment by zhoujoeyyi** [comment]
Hi @saketkc 

I'm using R4.3, though running into a similar error. Please see below.

`
> remotes::install_github("satijalab/seurat", "seurat5")
Downloading GitHub repo satijalab/seurat@seurat5
Downloading GitHub repo mojaveazure/seurat-object@seurat5
Running `R CMD build`...
* checking for file 'C:\Users\zhouj\AppData\Local\Temp\RtmpuMUWDD\remotes67039b553f9\mojaveazure-seurat-object-185884a/DESCRIPTION' ... OK
* preparing 'SeuratObject':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
      -----------------------------------
* installing *source* package 'SeuratObject' ...
** using staged installation
** libs
g++ -std=gnu++17  -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG  -I'C:/Users/zhouj/AppData/Local/R/win-library/4.3/Rcpp/include' -I'C:/Users/zhouj/AppData/Local/R/win-library/4.3/RcppEigen/include'   -I"c:/rtools43/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
sh: g++: command not found
make: *** [C:/PROGRA~1/R/R-43~1.0/etc/x64/Makeconf:272: RcppExports.o] Error 127
ERROR: compilation failed for package 'SeuratObject'
* removing 'C:/Users/zhouj/AppData/Local/Temp/RtmpYX30tZ/Rinst245c479d3d2c/SeuratObject'
      -----------------------------------
ERROR: package installation failed
STDOUT:
* checking for file 'C:\Users\zhouj\AppData\Local\Temp\RtmpuMUWDD\remotes67039b553f9\mojaveazure-seurat-object-185884a/DESCRIPTION' ... OK
* preparing 'SeuratObject':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
      -----------------------------------
* installing *source* package 'SeuratObject' ...
** using staged installation
** libs
g++ -std=gnu++17  -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG  -I'C:/Users/zhouj/AppData/Local/R/win-library/4.3/Rcpp/include' -I'C:/Users/zhouj/AppData/Local/R/win-library/4.3/RcppEigen/include'   -I"c:/rtools43/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
sh: g++: command not found
make: *** [C:/PROGRA~1/R/R-43~1.0/etc/x64/Makeconf:272: RcppExports.o] Error 127
ERROR: compilation failed for package 'SeuratObject'
* removing 'C:/Users/zhouj/AppData/Local/Temp/RtmpYX30tZ/Rinst245c479d3d2c/SeuratObject'
      -----------------------------------
ERROR: package installation failed
STDERR:

Error: Failed to install 'Seurat' from GitHub:
  Failed to install 'SeuratObject' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.
In addition: Warning messages:
1: In missing_devel_warning(pkgdir) :
  Package Seurat has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
2: In missing_devel_warning(pkgdir) :
  Package SeuratObject has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
`

**Comment by AustinHartman** [comment]
Hi @YYYYYWWWYYYYYY, I just pushed a fix for this error to SeuratObject which should make installation possible on R versions <4.1.0.

**Comment by guisantagui** [comment]
Hi, I am having this exact issue. I am on R 4.0.5 and cannot update it since it is the version in my institution's HPC. I am tried both to install Seurat v5 from GitHub, and CRAN's Seurat version with install.packages(). Both gave the same error: 
`Error in parse(outFile) : 
  /tmp/RtmpOWEyqu/R.INSTALL281dd94d24511b/SeuratObject/R/assay5.R:174:13: unexpected input
173:     expr = Layers(object = object, search = layer),
174:     error = \
                 ^
ERROR: unable to collate and parse R files for package ‘SeuratObject’
* removing ‘/mnt/irisgpfs/users/gsantamaria/R/x86_64-pc-linux-gnu-library/4.0/SeuratObject’

The downloaded source packages are in
        ‘/tmp/RtmpLSa6BA/downloaded_packages’
✔  checking for file ‘/tmp/RtmpLSa6BA/remotes28157f3e49c72e/satijalab-seurat-a4075e7/DESCRIPTION’ (462ms)
─  preparing ‘Seurat’:
✔  checking DESCRIPTION meta-information ... OK
─  cleaning src
─  installing the package to process help pages
         -----------------------------------
   ERROR: dependency ‘SeuratObject’ is not available for package ‘Seurat’
─  removing ‘/tmp/RtmpEr8o44/Rinst281e2c284fd862/Seurat’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'Seurat' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/tmp/RtmpLSa6BA/remotes28157f3e49c72e/satijalab-seurat-a4075e7/DESCRIPTION’ ... OK
E> * preparing ‘Seurat’:
E> * checking DESCRIPTION meta-information ... OK
E> * cleaning src
E> * installing the package to process help pages
E>       -----------------------------------
E> ERROR: dependency ‘SeuratObject’ is not available for package ‘Seurat’
E> * removing ‘/tmp/RtmpEr8o44/Rinst281e2c284fd862/Seurat’
E>       -----------------------------------
E> ERROR: package 
In addition: Warning message:
In i.p(...) :
  installation of package ‘SeuratObject’ had non-zero exit status`

I have tried to install SeuratObject both from GitHub (mojaveazure/seurat-object) and from CRAN (with install.packages()), and the error persists. Does any of you know how to solve this issue?

**Comment by Wenjuan-ZHU** [comment]
@guisantagui I had the same issue here and cannot install SeuratObject.

**Comment by alexanderchang1** [comment]
I have the same issue here.

**Comment by helenzhangyc** [comment]
@guisantagui I have the same issue here and cannot install SeuratObject.

**Comment by kevinhwong1** [comment]
@guisantagui I am also having the same issue (R version 4.0.3 and rlang version 1.1.2). Please let me know if there are any solutions to this without updating R. 

Error message:

Error in parse(outFile) : 
     /private/var/folders/cg/539pdzbj11g5mqx9hyc31qr80000gn/T/RtmpGovcBw/Rbuild892e234dc9e7/SeuratObject/R/assay5.R:174:13: unexpected input
   173:     expr = Layers(object = object, search = layer),
   174:     error = \
                    ^
   ERROR: unable to collate and parse R files for package ‘SeuratObject’
─  removing ‘/private/var/folders/cg/539pdzbj11g5mqx9hyc31qr80000gn/T/RtmpGovcBw/Rinst892e48026ecc/SeuratObject’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'SeuratObject' from GitHub:
  ! System command 'R' failed

**Comment by Andelyu** [comment]
I got the same issue here. Can anyone give a hand?

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘SeuratObject’ is not available for package ‘SeuratData’
* removing ‘/usr/local/lib/R/site-library/SeuratData’
Warning messages:
1: In i.p(...):
  installation of package ‘SeuratObject’ had non-zero exit status.
2: In i.p(...):
  installation of package ‘/tmp/Rtmp38GKrW/filed5a616079f66/SeuratData_0.2.2.9001.tar.gz’ had non-zero exit status.
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets methods   base

loaded via a namespace (and not attached):
 [1] processx_3.8.1    compiler_4.0.3    R6_2.5.1          rprojroot_2.0.4
 [5] cli_3.6.1         prettyunits_1.1.1 tools_4.0.3       withr_2.5.2
 [9] curl_5.1.0        crayon_1.5.2      remotes_2.4.2     callr_3.7.3
[13] ps_1.6.0          pkgbuild_1.2.0

**Comment by jingquanlim** [comment]
[seurat-object-5.0.1_fixedForR4.1_and_below.tar.gz](https://github.com/satijalab/seurat/files/14882952/seurat-object-5.0.1_fixedForR4.1_and_below.tar.gz)
Credits to @AustinHartman for pointing out the 'shorthands used' with the "error = \(" code. I have manually replaced numerous to "error = function(" and have the files uploaded here for everyone to try it out.
