### ISSUE TITLE
Error while reading a .h5 file using Read10X_h5 function

### ISSUE THREAD

**Issue by Priyadarshini-Rai** [satijalab/seurat#7130]
I am getting the following error while reading a .h5 file.

Error in sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x = counts[]),  : 
  'p' must be a nondecreasing vector c(0, ...)
In addition: Warning message:
In sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x = counts[]),  :
  NAs introduced by coercion to integer range

**Comment by saketkc** [comment]
Can you point to the h5 file if it is publically available? Also, how big is the dataset?

**Comment by Priyadarshini-Rai** [comment]
Dear Saket

Thank you for your reply.

The data is generated by our lab and is not available online and it
consists of around 1M cells.

*With Regards,*
*Priyadarshini Rai*
*Research Scholar, IIIT Delhi*
*Mobile: +919560039273*

**Comment by saketkc** [comment]
I would then recommend switching to Seurat V5 and using the on-disk capability for this dataset. https://satijalab.org/seurat/articles/get_started_v5.html

**Comment by Priyadarshini-Rai** [comment]
Dear Saket

Thank you for suggesting a solution. But, we are not able to load the .h5
file using Seurat.

*With Regards,*
*Priyadarshini Rai*
*Research Scholar, IIIT Delhi*
*Mobile: +919560039273*

**Comment by saketkc** [comment]
The V5 architecture allows loading 1M+ cells. You can see this vignette for an example: https://satijalab.org/seurat/articles/seurat5_sketch_analysis.html

You will need to install the `seurat5` branch using the instructions here: https://satijalab.org/seurat/articles/install.html

**Comment by Priyadarshini-Rai** [comment]
Dear Saket

After uninstalling Seurat v5 and then again installing Seurat v4.3, we are
getting the following error while using SCTransform:

Error in is_scalar_character(x = key) : could not find function
"is_scalar_character"

Can you please help with the same?

*With Regards,*
*Priyadarshini Rai*
*Research Scholar, IIIT Delhi*
*Mobile: +919560039273*

**Comment by katimbach** [comment]
Hi, 

I am currently having the same error, but I am analyzing a public dataset. Briefly, I downloaded the h5 file from this GEO data repository: GSE180661 (https://0-www-ncbi-nlm-nih-gov.brum.beds.ac.uk/geo/query/acc.cgi). I was having trouble reading it in with Seurat, which upon further inspection seemed to be due to the format of the h5 file. Namely, I experienced the following error:
```
 Error in `[[.H5File`(infile, paste0(genome, "/shape")) : 
  An object with name X/shape does not exist in this group
```

Using rhdf5 package, I ran the following to view the file architecture: 
```
h5ls("./Reference_Data/Vazquez_2022/GSE180661_matrix.h5")
  group                     name       otype   dclass        dim
0     /                        X   H5I_GROUP                    
1    /X                     data H5I_DATASET    FLOAT 2700985203
2    /X                  indices H5I_DATASET  INTEGER 2700985203
3    /X                   indptr H5I_DATASET  INTEGER    1376122
4     /                      obs H5I_DATASET COMPOUND    1376121
5     /                      uns   H5I_GROUP                    
6  /uns feature_types_categories H5I_DATASET   STRING          1
7     /                      var H5I_DATASET COMPOUND      32223
```
To try to mitigate this, I copied a version as an h5ad file, as I read worked in this case https://www.reddit.com/r/bioinformatics/comments/146b1ev/trouble_converting_h5_file_to_seurat_object/. Then using SeuratDisk and SeuratData I converted it to a h5seurat, but now I am experiencing the same error as @Priyadarshini-Rai :
```
Vazquez<- LoadH5Seurat("./Reference_Data/Vazquez_2022/GSE180661_matrix.h5seurat")
Validating h5Seurat file
Initializing RNA with data
Error in sparseMatrix(i = x[["indices"]][] + 1, p = x[["indptr"]][], x = x[["data"]][],  : 
  'p' must be a nondecreasing vector c(0, ...)

```
I think this is all likely due to the lack of the /shape in the X group, but I'm not quite sure how to mitigate this. From the paper, it is stated that this file was made using CellRanger version 3.1.0.

**Comment by Ilarius** [comment]
@katimbach have you solved this? I am trying to download the same dataset as yours!

**Comment by s-juross** [comment]
Hey, I'm also working with this dataset and have the same problem. Did you find a solution? :)

**Comment by nfancy** [comment]
Following! Having the same error with a different dataset.
