### ISSUE TITLE
seurat v5 saveRDS seurat when use h5 as input

### ISSUE THREAD

**Issue by Liripo** [satijalab/seurat#7165]
When I use open_matrix_10x_hdf5 to build a seurat object, the following warning appears when saving rds.
```R
brain_data <- open_matrix_10x_hdf5(h5_file)
brain <- CreateSeuratObject(counts = brain_data)
dir.create("./seurat",showWarnings = FALSE)
saveRDS(
  object = brain,
  file = "obj.Rds",
  destdir = "./seurat",
  relative = FALSE,
  remove_old = FALSE
)
```
```R
## Warning messages:
## 1: The matrix provided does not exist on-disk 
## 2: The matrix provided does not exist on-disk 
```
 The warning is caused by the following code.
https://github.com/mojaveazure/seurat-object/blob/87ea3960c33926dc5bcc8cdc107e0041e9f3afa9/R/seurat.R#L731

Is there any reason to do this, would analysis be faster using open_matrix_dir?

**Comment by Gesmira** [comment]
Hi, 
Thanks for bringing this up. Currently `saveRDS` will move any saved BPCells directories on disk, created using `write_matrix_dir`, to the destination directory. This warning can be ignored for your purposes as when you load in the object, it will still refer to the path of your hdf5 file. As long as you do not move the file, reading in the seurat object and running operations should work as normal. Otherwise, you can follow the steps in the [BPCells vignette](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html) to avoid the warning for now. 


However, it's a good point and we'll look into either making the warning more informative when an hdf5 file is provided instead of a BPCells directory or adding functionality to move the hdf5 file.
