### ISSUE TITLE
Parallelization "multiprocess" deprecated

### ISSUE THREAD

**Issue by wht10** [satijalab/seurat#7185]
Hi Seurat Team, 

I was using [this documentation](https://satijalab.org/seurat/articles/future_vignette.html) to run parallelized FindMarkers on a large dataset, and found that `multiprocess` has been deprecated, and [the new argument](https://future.futureverse.org/reference/plan.html) is `multicore`.

Thank you!

**Comment by BenjaminDEMAILLE** [comment]
'multisession' replaced 'multiprocess'

**Comment by HenrikBengtsson** [comment]
Hi, author of **future** here. Please update your documentation to use `multisession` instead of `multiprocess`.  The `multiprocess` backend has been deprecated since 2020 and is now (July 2023) fully removed from the **future** package.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
