### ISSUE TITLE
muticca error 

### ISSUE THREAD

**Issue by songeric1107** [satijalab/seurat#719]
I am trying to run the multicca with 4 sets of data, but always get this error
```R
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

g.1 <- head(rownames(c2f@hvg.info), 2000)
g.2 <- head(rownames(c7f@hvg.info), 2000)
g.3 <- head(rownames(u2f@hvg.info), 2000)
g.4 <- head(rownames(u7f@hvg.info), 2000)

genes.use <- unique(c(g.1, g.2))
genes.use1 <- unique(c(g.3, g.4))

genes.use2<-unique(c(genes.use,genes.use1))

genes.use2 <- intersect(genes.use2, rownames(u2f@scale.data))
genes.use2 <- intersect(genes.use2, rownames(u7f@scale.data))

genes.use2 <- intersect(genes.use2, rownames(c2f@scale.data))
genes.use2 <- intersect(genes.use2, rownames(c7f@scale.data))

c2f@cell.names= paste("c2",c2f@cell.names, sep="_")
 c7f@cell.names= paste("c7",c7f@cell.names, sep="_")
 u7f@cell.names= paste("u7",u7f@cell.names, sep="_")
 u2f@cell.names= paste("u2",u2f@cell.names, sep="_")

cca <- RunMultiCCA(object.list = list, genes.use = genes.use2, num.ccs = 3)


Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing
```

**Comment by songeric1107** [comment]
list <- list(c2f, c7f,u2f,u7f)

**Comment by ekernf01** [comment]
The cell names are not only present in the `cell.names` slot. They also appear as rownames in the `meta.data` slot, as colnames in the `data`, `scale.data`, and `raw.data`, as names in the `ident` slot, and other places besides. This problem is probably due to modifying the `cell.names` slot without modifying anything else. Does your code work when you don't modify the cell names? To avoid duplicates, can you rename the cells in a simple way prior to CreateSeuratObject? If you absolutely have to modify the cell names, I would recommend modifying them everywhere, or at least in all the places mentioned above.

**Comment by songeric1107** [comment]
If I did not modify cell.names, it will fail and ask me to add.cell.id 

I read the raw files directly from 10X output. How to rename before createObject?

thank you

**Comment by ekernf01** [comment]
Have you tried using `Seurat::RenameCells()`? 

I should have looked for that earlier.

**Comment by mojaveazure** [comment]
@songeric1107 You can modify the column names of the matrix that gets passed to `CreateSeuratObject` to modify cell names before making a Seurat object using the `colnames` function.
