### ISSUE TITLE
Question about SNN

### ISSUE THREAD

**Issue by gturco** [satijalab/seurat#721]
When I select save SNN I get a matrix with data frames: i,p and x. I can not find in the docs what data these data frames contain?

**Comment by satijalab** [comment]
The saved SNN represents an edge matrix- with the weight of each element representing the jaccard similarity between two cells. Since the matrix is sparse, we use a sparseMatrix representation to store it - you can read more about that here

https://www.rdocumentation.org/packages/Matrix/versions/1.2-14/topics/sparseMatrix
