### ISSUE TITLE
Increasing resolution in 1 cluster without the others

### ISSUE THREAD

**Issue by EDYAC** [satijalab/seurat#726]
Hello everyone,
Is there a way to increase tSNE resolution of a specific cluster without affecting the others?
Thank you

**Comment by orrzor** [comment]
hi, that is not a good approach and is not how the resolution parameter in clustering works. 

However you can extract just the cells for yourcluster of interest (SubsetData) and then cluster those cells on their own with a different clustering resolution parameter.

**Comment by ericvon11** [comment]
As orrzor said, the tSNE has nothing to do with the resolution set in FindClusters, the tSNE is only using information from PCs (or CCs) or genes, depending on what you specified. If you feel a certain cluster is not resolved enough, it may be likely that your variable genes used to cluster weren't particularly enriched in this cluster. Try subestting and collecting more variable genes specific to this cluster, then add those in to your all cells clustering (or just keep it separate). Your issue is that you likely haven't included enough information to resolve this cluster more

**Comment by EDYAC** [comment]
Thank you so much for the clarification
