### ISSUE TITLE
Spatial Transcriptomics - only lowres image

### ISSUE THREAD

**Issue by onahman** [satijalab/seurat#7289]
Hi,
It would be a rather small fix, and a nice addition if you could allow to choose between lowres/hires images.
It seems almost everything needed for that is already in the code, but the parameter can't be passed to the Load10X_Spatial function and the SpatialFeaturePlot function.
Thanks in advanced!
Ornit

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
