### ISSUE TITLE
Difference between power and myAUC in Seurat R package for analyzing Single Cell RNA-seq data?

### ISSUE THREAD

**Issue by timj6599** [satijalab/seurat#7341]
I am attempting to use the Seurat FindAllMarkers function to validate markers for rice taken from the plantsSCRNA-db. I want to use the ROC test in order to get a good idea of how effective any of the markers are. While doing a bit of research, different stats forums say: "If we must label certain scores as good or bad, we can reference the following rule of thumb from Hosmer and Lemeshow in Applied Logistic Regression (p. 177):
0.5 = No discrimination 0.5-0.7 = Poor discrimination 0.7-0.8 = Acceptable discrimination 0.8-0.9= Excellent discrimination0.9 = Outstanding discrimination "
[https://www.statology.org/what-is-a-good-auc-score/#:~:text=0.5%2D0.7%20%3D%20Poor%20discrimination,%3E0.9%20%3D%20Outstanding%20discrimination](https://www.researchgate.net/deref/https%3A%2F%2Fwww.statology.org%2Fwhat-is-a-good-auc-score%2F%23%3A~%3Atext%3D0.5%252D0.7%2520%253D%2520Poor%2520discrimination%2C%253E0.9%2520%253D%2520Outstanding%2520discrimination)
For more background, the output of the function returns a dataframe with a row for each gene, showing myAUC: area under the Receiver Operating Characteristic, and Power: the absolute value of myAUC - 0.5 multiplied by 2. Some other statistics are included as well such as average log2FC and the percent of cells expressing the gene in one cluster vs all other clusters.
With this being said, I would assume a myAUC score of 0.7 or above would imply the marker is effective. However given the formula used to calculate power, a myAUC score of 0.7 would correlate to a power of 0.4. So with this being said, would it be fair to assume that myAUC should be ignored for the purposes of validating markers? Or should both values be taken into account somehow?

**Comment by longmanz** [comment]
Hi, 
ROC test is to find out how good each gene helps differentiate your ident.1 (control group) from ident.2 (treatment group). So it is ranked purely based on the AUC. However, please note that myAUC in ROC test is not exactly the same as the standard AUC. 

The thread you posted assumes the AUC is always on the right-hand side of 0.5 (which is the standard AUC). But in the ROC test implemented in Seurat, myAUC can also go below 0.5 (meaning this gene is a negative marker). That is why people tend to use the 'Power' to rank genes in ROC test, because the deviation of myAUC from 0.5 is really what matters here (and such deviation is represented by 'Power'). 

Thus, you only need to look at the Power. The myAUC and the Power are fundamentally reflecting the same things.
