### ISSUE TITLE
Terminology: slot vs. layer

### ISSUE THREAD

**Issue by petervangalen** [satijalab/seurat#7351]
I am confused about the following since updating to Seurat_4.9.9.9041 (using RStudio with R version 4.2.1).

I am now using `LayerData()` instead of `GetAssayData()` as advised in the Lifecycle note.
When I use `LayerData(..., slot = "count")`, it returns the "data". I found that I need to use `layer` instead of `slot`, so I figure you have updated the terminology: `LayerData(..., layer = "count")` returns the expected matrix.

However, in other functions, such as `AverageExpression`, `slot` is still the argument that provides the expected matrix.

Are `slot` and `layer` synonymous? Do I need to memorize which function goes with which?

**Comment by Gesmira** [comment]
Hi, thanks for pointing this out. We will be deprecating the `slot` argument in Seurat v5 so that the first example you gave will return an error. Seurat v5 will primarily use the `layer` terminology and the `slot` argument will be phased out from functions like AverageExpression from Seurat v4 over time as well.

**Comment by petervangalen** [comment]
Good to know. Thanks!
