### ISSUE TITLE
two question about FindConservedMarkers/FindAllMarkers

### ISSUE THREAD

**Issue by xiexiaowei** [satijalab/seurat#736]
Dear authors,
Recently, we used your powerful(vey powerful) Seurat software and I met two questions.

Question1.
1). FindConservedMarkers(ABC, ident.1=0, ident.2=1, grouping.var="group")----is ok
2). FindMarkers(ABC, ident.1=1, min.pct=0.25)----is ok
3). FindConservedMarkers(ABC, ident.1=0, grouping.var="group")----had warnings as follows:
Warning messages:
1: In if (!ident.use.2 %in% object@ident) { :
   the condition has length > 1 and only the first element will be used
2: In if (!ident.use.2 %in% object@ident) { :
     the condition has length > 1 and only the first element will be used
How can I solve the question or just ignore it? Would it affect the marker list?

Question2.
about "avg_logFC" in the output of FindAllMarkers
The log is log(number,e) or log(number,10)?

I need your help urgently and show my great appreciation to you!
xiaowei，

**Comment by leonfodoulian** [comment]
Hi @xiexiaowei,

> Question1.
> 1). FindConservedMarkers(ABC, ident.1=0, ident.2=1, grouping.var="group")----is ok
> 2). FindMarkers(ABC, ident.1=1, min.pct=0.25)----is ok
> 3). FindConservedMarkers(ABC, ident.1=0, grouping.var="group")----had warnings as follows:
> Warning messages:
> 1: In if (!ident.use.2 %in% object@ident) { :
> the condition has length > 1 and only the first element will be used
> 2: In if (!ident.use.2 %in% object@ident) { :
> the condition has length > 1 and only the first element will be used
> How can I solve the question or just ignore it? Would it affect the marker list?

Regarding your first question, this is a simple warning message. The fact is that `ident.use.2` in this case is formed of multiple identities (since `ident.2` is not specified in the function call, cells from all other identities are compared to cells pertaining to the cluster 0). For more details, please see [lines 709 to 715 in differential_expression.R](https://github.com/satijalab/seurat/blob/7618ac8798e2aefc509529f07af9d2836b96a1be/R/differential_expression.R#L709-L715 ). The code line (i.e. `if (!ident.use.2 %in% object@ident) {`), as it is written, only allows the first element of `ident.use.2` to be tested in the `if` statement. I have encountered this warning message also previously, and I agree that the code should be slightly modified to avoid getting this warning message, and will consider submitting PRs sometime in the near future to fix that.

> Question2.
> about "avg_logFC" in the output of FindAllMarkers
> The log is log(number,e) or log(number,10)?

`avg_logFC` is in natural log. For more details, please check [lines 176 to 178 in differential_expression.R](https://github.com/satijalab/seurat/blob/7618ac8798e2aefc509529f07af9d2836b96a1be/R/differential_expression.R#L176-L178).

Best,
Leon
