### ISSUE TITLE
Number of cells per cluster per identity

### ISSUE THREAD

**Issue by PaulineMarangoni** [satijalab/seurat#738]
I'm running analysis on a merged dataset comprising 2 samples (1 control, 1 treatment condition), and I am trying to get the distribution of cells per clusters based on their sample of origin.

`table(... = combined.res1p0@ident)`
gives me how many cells I have per cluster, not whether they come from control vs treated.

I've then tried the following, which gives me an answer `< table of extent 0 >`:
`> table(...=combined.res1p0@meta.data$ident)`

Did anyone run into the similar issue? Do you happen to know what to call for in that case? Thanks in advance for your help!

**Comment by leonfodoulian** [comment]
Hi,

Cluster identities in Seurat are stored in `object@meta.data`, in a column named after the resolution of the clustering you used. With default parameters, the resolution is set at 0.8. Therefore, the following code should give you how many cells you have per cluster and per sample of origin:

```R
# Get number of cells per cluster and per sample of origin
table(object@meta.data$res.0.8, object@meta.data$orig.ident)
```

An alternative would be to store the cluster identities of your cells (which are also located in `object@ident`) in a new column in `object@meta.data`, and then get the number of cells per cluster and sample of origin using the following code:

```R
# Store cluster identities in object@meta.data$my.clusters
object <- Seurat::StashIdent(object = object, save.name = "my.clusters")

# Get number of cells per cluster and per sample of origin
table(object@meta.data$my.clusters, object@meta.data$orig.ident)
```

 You can also use the following code:

```R
# Get number of cells per cluster and per sample of origin
table(object@ident, object@meta.data$orig.ident)
```

But I prefer to input to the `table` `R` function data coming from the same source (in this case, `object@meta.data`), so that the order of cells is maintained and consistent across the two vectors.
 
Hope these help!

Best,
Leon

**Comment by PaulineMarangoni** [comment]
Thanks a lot Leon!

I tried the 1st one
`table(object@meta.data$res.0.8, object@meta.data$orig.ident)`
but it gave me an error because "all arguments must have the same length". I am assuming this might have to do with the fact that I purposely changed the resolution to 1.0 in my analysis.

`table(object@ident, object@meta.data$orig.ident)`
however gives me exactly the information I was looking for!

**Comment by leonfodoulian** [comment]
Hi @PaulineMarangoni,

I'm glad it works!

Among other ways of doing this, the following code will give you all column names that start with `res.` in `object@meta.data`:

```R
grep(pattern = "^res.", x = colnames(x = object@meta.data), value = TRUE)
```

In your case, this should give the correct results:

```R
table(object@meta.data$res.1, object@meta.data$orig.ident)
```

As I mentioned it previously, I would be really cautious of 
```R
table(object@ident, object@meta.data$orig.ident)
```
since changing the order of the cells in one of the slots (i.e. `@ident` or `@meta.data`) for what ever reason will not change the order of the cells in the other slots of the Seurat object. And since the table function will not take the cell names into consideration, doing it this way might give you false results. This example demonstrates my point:

```R
> table(object@meta.data$res.1, object@meta.data$orig.ident) == table(object@ident, object@meta.data$orig.ident)
   
       a    b
  0 TRUE TRUE
  1 TRUE TRUE
  2 TRUE TRUE
  3 TRUE TRUE
  4 TRUE TRUE
  5 TRUE TRUE
  6 TRUE TRUE
> object@meta.data <- object@meta.data[order(object@meta.data$nGene, decreasing = TRUE), ] # change order of cells in object@meta.data (order by nGene instead of cell name)
> table(object@meta.data$res.1, object@meta.data$orig.ident) == table(object@ident, object@meta.data$orig.ident)
   
        a     b
  0 FALSE FALSE
  1  TRUE  TRUE
  2 FALSE FALSE
  3 FALSE FALSE
  4 FALSE FALSE
  5 FALSE FALSE
  6 FALSE FALSE
```

Best,
Leon

**Comment by SaraAlidadiani** [comment]
Hi, 
I want to show the the cell type frequency between two different conditions, I followed your comments here, and I created the table as the code below:

table(harmonized_seurat@meta.data$cell_type, harmonized_seurat@meta.data$condition)

and my table looks like below (example of how my data looks like):
                                patient   Control
  Astrocytes                 157       111
  Endothelial cells       19        16
  Excitatory neurons     34      61
  Inhibitory neurons   75      60
  Microglia                   40      50
  Neurons                     35     39
  
  Is it the right way to get the number of cells per different conditions? Which statistical test must I use to see if the difference in each fraction is significant between two groups (e.g., if the difference in the fraction of astrocytes is significant between patient and control)?
  I feel like with this code, I am getting the number of cells per group. How do I calculate the fraction of cells between two groups?

Thank you in advance
