### ISSUE TITLE
Merge seurat objects before or after SCtransform

### ISSUE THREAD

**Issue by joachimsiaw** [satijalab/seurat#7407]
It is still not clear to me, what the actual guidline is regarding merging of seurat objects. Should one merge the objects before or after running SCtransform? This question was asked in #3046 but no clear answer was provided.  I tried the two approaches on my SPATIAL TRANSCRIPTOMICS dataset and here are the results:

1. Run SCtransform > mege
![image](https://github.com/satijalab/seurat/assets/38905650/04fcbe23-d6ec-4b01-8ff1-b05f639583ad)

2. merge > SCtransform
![image](https://github.com/satijalab/seurat/assets/38905650/9b305a99-83df-41dd-84eb-e6699521da6b)

The seurat tutorial suggest using the first approach but in  my case this doesn't seem to look right as clearly the counts between the two samples are different, due to difference in sequencing depth. Won't this affect downstream analysis if not corrected?
The second (2) approach seemed to have corrected for difference in sequencing depth  with some scaling. 
could you please help clarify this and suggest a clear guideline in this scenario.

Thank you

**Comment by saketkc** [comment]
I would recommend running SCTransform separately and then using PrepSCTFindMarkers() to adjust for difference in sequencing depth across samples as shown in the [v2 vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette.html)

**Comment by iddryg** [comment]
@saketkc your link to the v2 vignette doesn't work anymore. Any updated references?

**Comment by Pancreas-Pratik** [comment]
> https://satijalab.org/seurat/archive/v4.3/sctransform_v2_vignette

@saketkc I was wondering if you have updated recommendations, based on the sketch-based clustering from this section of the new VisiumHD vignette (https://satijalab.org/seurat/articles/visiumhd_analysis_vignette#unsupervised-clustering-mouse-intestine). I _would use_ this vignette, but because I have two samples (a treatment and a control), I am questioning on how to proceed appropriately. Intuitively, I think integration would need to be implemented for this two sample study.

Therefore, I am left with two paths:

1. **v2_vignette you linked** - I am asking in this issue, because this issue and v2 vignette you linked is a perfect match with my study design (treatment vs. control) and what I intend to do, except the issue being that the data I am using is... VisiumHD data. Would using VisiumHD data with the vignette you linked be an issue?

2. **combination of current visiumHD sketch-based clustering vignette and integration** - I would use the v2 vignette you linked, but I am unsure, if somehow implementing the sketch-based clustering together with integration would be more appropriate.

Could you please help by recommending which path (1 or 2) should be taken with this treatment vs. control VisiumHD data? Or if there is a better suggestion could you advise, please?

Thank you very much

**Comment by saketkc** [comment]
Thanks for the question @Pancreas-Pratik. `SketchData` currently does not support SCT workflow.

> v2_vignette you linked - I am asking in this issue, because this issue and v2 vignette you linked is a perfect match with my study design (treatment vs. control) and what I intend to do, except the issue being that the data I am using is... VisiumHD data. Would using VisiumHD data with the vignette you linked be an issue?

You can use SCT v2 workflow on spatial datasets.

**Comment by xiavincent** [comment]
Hi @saketkc and @yuhanH , 
Following up on this question regarding Sketch and SCTransform, I am wondering if you can explain why SketchData does not support SCT workflow.

I understand that you cannot run SketchData on an SCTransformed dataset, but what about the following workflow? @yuhanH had made a comment here (https://github.com/satijalab/seurat/issues/7336), but for me, SCTransform has no problem running **after sketching**.

Load Xenium data and merge -> NormalizeData + FindVariableFeatures + SketchData -> SCTransform on sketch assay

<img width="758" height="481" alt="Image" src="https://github.com/user-attachments/assets/b5bb0ca5-7a84-49c8-9c20-7adb172a32bf" />

Will this work? Will there be an issue during "ProjectData" if I try to project the full dataset onto SCT assay?
