### ISSUE TITLE
TPM or raw count matrix

### ISSUE THREAD

**Issue by seongguheo** [satijalab/seurat#7414]
Dear Authors,

I am analyzing Smart-seq2 single cell RNA-seq data, which is a full length RNA-seq data.
TPM removes transcript length difference effects from the data.

I wonder if I can use the TPM count matrix for Seurat or I have to use the raw count matrix data since Seurat performs normalization by itself.

And I wonder If there is a way around of Seurat's normalization to avoid duplicating normalizations in the case I use TPM.  

Thank you so much for your help.
Luke

**Comment by longmanz** [comment]
Hi, 
It is definitely okay to only load the normalized count matrix instead of raw count matrix into a seurat obj. For example:
`assay_TPM = CreateAssayObject(data = TPM_count_matrix)` allows you to load the TPM matrix directly into the "data" slot, which is the normalized slot. And you do not need to perform Seurat Normalization if you use TPM counts.
