### ISSUE TITLE
link in vignette doesn't provide the expected data (h5ad)

### ISSUE THREAD

**Issue by sopenaml** [satijalab/seurat#7437]
I'm trying to follow the [ following vignette] (https://satijalab.org/seurat/articles/parsebio_sketch_integration) to carry out sketch integration.  In the vignette you say that the data was downloaded  from [here](https://resources.parsebiosciences.com/dataset-wt-mega-one-million-pbmc-type-1-diabetes)   but  all I can get is a bunch of html documents.  At the bottom  there's a link to an example, to run the analysis using scanpy, but then link in there only downloads the matrices ... I appreciate that Parse Biosciences may have changed the location of the data, but it would be great to get the correct link for the location of the h5ad file, thank you.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
