### ISSUE TITLE
Can`t remove the effect of certain genes even after regressing them

### ISSUE THREAD

**Issue by raunakkar** [satijalab/seurat#7468]
Hi,
The particular problem was raised in a previous issue (issue #4338). But the resolution of the issue did not work for me.
I have regressed out a variety of genes from my data set while performing SCTransform followed by integrating data.
But still I have gotten clusters entirely dictated by genes in question. In a case, it happened to be the only differentially expressed genes for the given cluster.
This does not happen when i follow the regular workflow without using SCTransform.
Looking forward to some guidance as to what could be the solution.

Regards

**Comment by longmanz** [comment]
Hi,
It is a tricky question to try to remove the effect of certain genes when doing clustering. Following the method from https://github.com/satijalab/seurat/issues/4338 to regress out the overall module score of these genes might not work that well, because using one score to remove the effect of many genes does not guarantee a complete removal. 
You can potentially treat each gene as an individual covariate and regress them out using "vars.to.regress". You just need to extract them from your RNA matrix (seurat_obj@assays$RNA@data[c("gene1", "gene2",...), ]) and add them to your metadata, so that you can use vars.to.regress to regress them out.
