### ISSUE TITLE
cell cycle scoring very different in Seurat v5 

### ISSUE THREAD

**Issue by CellSignaling** [satijalab/seurat#7486]
Hi Seurat team, 

I cannot reproduce the same cell cycle scoring in Seurat v5 as the previous versions. I have tried to assign an object using Seurat_4.3.0 which yields 50% of cells in G1 which is what we expected based on experimental data. However using the same object in Seurat v5 and the same custom gene list for each S, G2M across Seurat versions, in v5 I get a frequency of 90% cells in G1. 

The cell cycle scoring function that I'm using is the one from your vignettes:
seu_big<- CellCycleScoring(seu_big, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

Actually, plotting the S.Score and G2M.Score reveals a strange positive correlation.

![image](https://github.com/satijalab/seurat/assets/41546416/92e690b2-d3df-4bea-9890-69c51b5400c3)

In the past, I had the same problem with Scanpy with the same gene list and Seurat object. I have seen previous issues related to cell cycle scoring #6625, #5329, #5518 but did not seem to report the same problem. The data is increasing in cell number and I'll need to use Seurat v5 to handle the large dataset ideally within the same Seurat version. Any ideas as to how I could get around this?

Thank you!
Mariona

**Comment by longmanz** [comment]
Hi,
So you observed that using the same object but with different versions of Seurat, you obtained different cell-cycle scores?
1. Is there any change of the object itself? If so, the scores will be different because the CellCycleScoring() is based on AddModuleScore(), and AddModuleScore() will be different if the cells or features in the object are different. 
2. Have you checked if you are using the same assay? You can specify it in CellCycleScoring() just as in AddModuleScore(). A different assay will lead to different results. 

Let us know if the above checks cannot fix the issue. And we will look into this

**Comment by rsatija** [comment]
Thanks for catching this. It is related to the AddModuleScore bug that was reported today. We found the source of the bug and will fix ASAP

**Comment by lselfors** [comment]
Thank you so much. You do great work.
Laura

On Jul 6, 2023, at 5:55 PM, rsatija ***@***.******@***.***>> wrote:



Thanks for catching this. It is related to the AddModuleScore bug that was reported today. We found the source of the bug and will fix ASAP
