### ISSUE TITLE
different DEG fold change values between RNA assay of integrated seurat object and original seurat object

### ISSUE THREAD

**Issue by mervedede** [satijalab/seurat#7499]
Hello team,

I have been using Seurat for the past two years and am grateful for this toolkit. I have noticed an issue recently that I could not make sense of, so I need your advice.

I have a seurat object that has been preprocessed using all preprocessing steps and I have created another version of this object by performing integration as described in : https://satijalab.org/seurat/articles/integration_introduction.html.

For the integrated object, I switched to the RNA assay which should contain the raw values and I subsetted it to a certain cell type (both seurat objects have exactly the same cell type annotation) and then I performed DEG analysis using the default settings in the FindMarkers function. Then, I did the same process in the original unintegrated seurat object. While I was able to confirm that the gene expression values for both of these objects are identical, although I am still getting identical differentially expressed genes and adjusted p values in both ways, the fold avg_log2FCs are inflated in the integrated object (by 2x). After subsetting, I have confirmed that both objects have the same number of cells and same number of features. Can you explain why I could be getting different fold change values although the RNA assay of the integrated object should have the same information as the unintegrated seurat object, is this a bug?

Thanks

<img width="425" alt="Screenshot 2023-06-26 at 10 35 29 AM" src="https://github.com/satijalab/seurat/assets/31451832/4f9422c2-72c2-456d-a74b-045810bc1d81">

**Comment by saketkc** [comment]
Hi @mervedede,

This was because of a bug in how FindMarkers/FoldChange were handing different normalization approaches.

I have just pushed https://github.com/satijalab/seurat/commit/992c1a96693b1467160969625edc8a5c80ab0867 to develop branch which should fix this and related issues. Can you pull from the develop branch and re-open this issue if you are still facing issues?

```r
devtools::install_github("satijalab/seurat", branch="develop")
```

You should make sure the unintegrated object has also been normalized (i.e, you have run `NormalizeData()`)

This should also be in the next Seuratv4 release.
