### ISSUE TITLE
Unclear about default partitioning algorithm

### ISSUE THREAD

**Issue by lazappi** [satijalab/seurat#75]
In the PBMC tutorial you discuss how Seurat now uses the SLM algorithm to partition the KNN graph. Looking at the help for the `FindClusters` function the default algorithm is 1, corresponding to the original Louvain algorithm. The call in the example does not set the algorithm parameter so I assume SLM is not being used.

Is it true that this is the default and do you recommend setting `algorithm = 3` to use SLM?

Thanks

**Comment by andrewwbutler** [comment]
Sorry for the confusion. The documentation for the function is correct. If you want to use the SLM procedure, you will need to set `algorithm = 3`. In many cases (particularly with smaller data sets), they produce very similar results but I would recommend trying both to see how results change. In general, I'd recommend SLM and we'll likely make that the default for future releases since datasets are growing rapidly.
