### ISSUE TITLE
DEenrichRPlot positive and negative results are the same

### ISSUE THREAD

**Issue by abspangler13** [satijalab/seurat#7500]
Hello,

I'm running Seurat 4.2.0 and using the DEenrichRPlot() function. I'd like to see the enriched pathways for both negative and positive DE genes. For some reason, the function returns the exact same pathways and and p-values for both the negative and positive DE genes for all of my clusters. I'm running the function like this: 

`    lapply(clusters, FUN = function(x) {
        DEenrichRPlot(tonsil_in, ident.1 = x,logfc.threshold = 0.4,enrich.database = "GO_Biological_Process_2023",max.genes = 200, balanced = FALSE)
        })`

And my plots look like this:
<img width="749" alt="image" src="https://github.com/satijalab/seurat/assets/18468963/1194de53-785f-483d-9a3f-0458ba96247e">

<img width="746" alt="image" src="https://github.com/satijalab/seurat/assets/18468963/f678365e-07e2-48ff-b073-482d987dae6e">

Thanks for your help,

Abby

**Comment by longmanz** [comment]
Hi,
If you want to get enrichR results for both of your positive and negative DEGs, you will need to set the `balance =` to "TRUE" instead of "FALSE". 
```
Option to display pathway enrichments for both negative and positive DE genes.If false, only positive DE gene will be displayed.
```
Let me know if the problem persists even after setting `balance = TRUE`. I will reopen the issue.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
