### ISSUE TITLE
Conversion factor from the coordinates to actual size after "GetTissueCoordinates" for spatial transcriptomics

### ISSUE THREAD

**Issue by chiwwong** [satijalab/seurat#7510]
I wonder if that is possible to get a scale bar on the spatial transcriptomics data(sequence-base). More specifically, I am plotting each spot manually, by extracting the coordinates and scaled expression data using `GetTissueCoordinates`. I found that the distance between the spots is around 8 (I am not sure of the unit here as they are coordinates and can be plotted by ggplot). I wonder if that is possible to know how to convert the coordinate back to the actual length. Thanks!

**Comment by alikhuseynov** [comment]
Not sure for the scale bar.. 
But Seurat scales the spot coords of Visium data. Take a look at this #6980 
Also this info from 10X [output_spatial](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/spatial) is very useful.
The original units from SpaceRanger output for tissue coords are in pixels, you can convert them: 
`px.size <- 65 / spot_diameter_fullres` then multiply `x` and `y` coord from `GetTissueCoordinates` by `px.size`
the `spot_diameter_fullres` comes from `"^tissue_positions_list"` file.
Hope this helps

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
