### ISSUE TITLE
AddModuleScore 

### ISSUE THREAD

**Issue by JLi-github** [satijalab/seurat#7512]
As I used the **AddModuleScore** function and I found that when I printed the Featureplot I got a bug:

F1_signature_gene_list <- list(c("IL6", "IL6R", "STAT3"))

object <- AddModuleScore(object = object, features = F1_signature_gene_list, name = "ID1")

FeaturePlot(object = object, features = "ID2", order=T)

---------------------------------------------

FeaturePlot(object = object, features = "ID2", order=T) works but in the meta.data of object, there is no "ID2"

How to explain this?

Thanks!

```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The reason for this is because there is a human gene with the symbol ID2 (https://www.ncbi.nlm.nih.gov/gene/3398).  It is important to ensure any names you give for meta data are different than gene list to avoid any potential name collisions.

Best,
Sam
