### ISSUE TITLE
FindMarkers assay: RNA, SCT or integrated

### ISSUE THREAD

**Issue by dy-lin** [satijalab/seurat#7532]
Which assay should be used for using the `FindMarkers` function after integration (normalized with SCT), and which data slot?

In the RNA assay, I have normalized using `NormalizeData()`, `ScaleData()`, `FindVariableFeatures()` workflow.
In the SCT assay, I have normalized using `SCTransform(.., vst.flavor = 'v2')`
In the integrated assay, I have used `IntegrateData(..., normalization.method = "SCT") 

The reason I run both NormalizeData and SCTransform is that I have observed differences in `FeaturePlot` depending on the normalization method. Often using the SCT assay the FeaturePlot will warn that all values are the same but that is not the case when using the RNA assay.

According to the SCTransform (v1 and v2) vignette, the SCT assay with the `data` slot should be used for differential expression testing. What kind of downstream analysis is the integrated assay (default only contains 2000 features)? Is the created integrated assay only used for clustering and dimensional reductions?

**Comment by saketkc** [comment]
This question is covered in the [FAQs](https://github.com/satijalab/seurat/discussions/4000) but to summarize you should run FindMarkers on the RNA or SCT assay.

The difference in the SCTransform vs LogNormalization for visualization is because of differences in how they work. While LogNomralization uses a default scaling factor of 10000, SCTransform produces "corrected counts" using median of sequencing depth. I would recommend sticking to one workflow for visualization and DE (whichever you decide to choose).

**Comment by dy-lin** [comment]
Should SCT be used over RNA due to the corrected counts of sequencing depth? I notice for some of my genes of interest, the p_val_adj is significant when using the RNA assay but is not significant when using SCT for FindMarkers.

**Comment by saketkc** [comment]
I would recommend using the SCT workflow for the arguments given in this [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1874-1), but you are welcome to choose one that makes most sense in your setting.

**Comment by dy-lin** [comment]
Is the integration process used for only clustering?

**Comment by saketkc** [comment]
Yes. Please see this [FAQ](https://github.com/satijalab/seurat/discussions/4000)
