### ISSUE TITLE
Generating Count Matrix for Deseq Analysis in Seurat

### ISSUE THREAD

**Issue by sallyseullee-0821** [satijalab/seurat#7554]
Hi experts! 

Using Seurat, I have clustered the cells and subsetted a specific cell cluster to do downstream analysis. 
Using this subset, I am trying to run Deseq to find differentially expressed genes between more than 10 patients (patient_id stored in metadata). 

As one of the inputs, I need a count matrix where each row represents a gene, and each column represents a patient_id, with the count value indicating the total number of counts for that particular gene (row n) in the corresponding patient's data (column n). 

I am curious if there is a convenient method within Seurat to accomplish this. If not, I would greatly appreciate any suggestions or alternative approaches you might have. 

Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Yes there is easy function in Seurat to do this `AggregateExpression`.  Simply provide the meta.data column name to the `group.by` parameter.  You can all multiple parameters too (i.e. if you want to get the aggregated expression per sample per cluster) which you can then manually filter.

```
deseq_df <- data.frame(AggregateExpression(object = OBJ_NAME, group.by = "patient_id"))

deseq_df_cluster <- data.frame(AggregateExpression(object = OBJ_NAME, group.by = c("sample_id", "ident")))
```

Best,
Sam

**Comment by longmanz** [comment]
Thank you @samuel-marsh! Really appreciate you always being there to help with the issues. 

Just a quick additional suggestion to @sallyseullee-0821, if you are looking for aggregation for raw counts instead of normalized data, please remember to set the `slot = "counts"` when running `AggregateExpression()`. The aggregated raw counts is often easier to work with if you want to apply DEseq/DEseq2 method, as it requires counts instead of norm.data.

**Comment by samuel-marsh** [comment]
Hi @longmanz happy to help!!  And yes @sallyseullee-0821 sorry I omitted that but I agree as suggested should definitely use raw counts for summing for DESeq2
