### ISSUE TITLE
dotplot vs heatmap interpretation

### ISSUE THREAD

**Issue by thamsepia** [satijalab/seurat#7571]
I am interested in comparing gene expression of 2 genes (CACNA1D and CACNA1S) in my sc data. By looking at the dotplot, it seems that CACNA1D is highly expressed in a larger pct of cells (eg cluster 4) compared to CACNA1S.  Looking at the heatmap,  this doesn't seem to be the case. 

Don't both dotplot and heatmap use scaled.data by default? Could someone please explain this discrepancy?
![hc_cav_dotplot_col](https://github.com/satijalab/seurat/assets/93143535/238e27a7-323f-4aa7-9260-f54ad6b938c7)
![hc_cav_scaled_heatmap_col](https://github.com/satijalab/seurat/assets/93143535/e7579774-229a-43f0-94e0-550d60082e8e)

Thank you

**Comment by longmanz** [comment]
Hi,
1. In the dotplot, the size of the dot only indicates the percentage of cells in that cluster the express that gene ( expression > 0), while the gradient of color indicate the average expression level of that gene.
2. The scaling of the dotplot is done for the average expression levels of each cluster, rather than on a single-cell level. It means that for each gene in your dotplot, the number of datapoints being scaled is 8. 
3. In that case, the scaling in your dotplot will not always match the scaling in your single-cell heatmap. Because in your single-cell heatmap, the scaling is done for each individual cell. 

To make sure the dotplot is showing the correct values, you can manually calculate AverageExpression() for each of your clusters for gene CACNA1D and CACNA1S. They should match what you have in the dotplot.

**Comment by thamsepia** [comment]
Thank you for the clarification. Does that mean the dotplot and heatmap can only be used to compare expression of one gene between different clusters and cannot be used to compare expression of two or more genes in a particular cluster?

**Comment by longmanz** [comment]
Hi, 
Not really. They can still be used to compare different genes. What I meant was that DoHeatmap's scaling does not always match DotPlot's scaling, since they are done in a very different way.
