### ISSUE TITLE
AverageExpression() Formula

### ISSUE THREAD

**Issue by akshatkarambe** [satijalab/seurat#758]
I was trying go to through the data frame which is created after using the function AverageExpression().
This is the same data frame which is used in plotting the heat maps. I am unsure of how we are getting the negative values. 
Can I know what formula we are using to find the average expression?
Also, what is being considered while finding the average expression of each gene per cluster?

**Comment by leonfodoulian** [comment]
Hi @akshatkarambe,

The formula used in `Seurat::AverageExpression()` if `use.scale = FALSE` and `use.raw = FALSE` is:

```R
mean(x = expm1(x = x))
```

`x` being a vector of expression values across cells of a given gene. See [line 569 in utilities.R](https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/utilities.R#L569).

Best,
Leon

**Comment by akshatkarambe** [comment]
Thank you Leon,

But as i was going through the data frame i found out that we save some negative values as well.
So how are we getting the negative values? Are we subtracting anything from our value?

**Comment by leonfodoulian** [comment]
Hi @akshatkarambe,

Could you please share the code you used? And maybe specify which data frame you are referring too? Negative values could arise if you are using the scaled data (from `object@scale.data`) to compute average expression. 

Best,
Leon

**Comment by akshatkarambe** [comment]
Ohh got it.

Thanks alot!

**Comment by whitleyo** [comment]
Looking through the source code to AverageExpression, it appears that when use.scale is true, the mean of the scaled data (which should be in a normally distributed space) is taken. In the documentation, it is stated:

"Output is in log-space when return.seurat = TRUE, otherwise it's in non-log space. Averaging is done in non-log space"

Did I miss something or is there a discrepancy between the source code and the documentation?

Thanks,
Owen
