### ISSUE TITLE
Is there a way to regress out ribosomal genes from the dimensional reduction? 

### ISSUE THREAD

**Issue by bwang258** [satijalab/seurat#759]
Hi,

I read from the Seurat webpage about a vignette to remove the cell cycle-related genes from dimensional reduction. It was really helpful and then it showed some promising result on my data. However, I dug around to see if there is a way to regress out the ribosomal genes from the dimensional reduction and haven't seen an approach to do this. Is there a way or function that support similar processing as the cell cycle genes for ribosomal genes? Given that I have extracted some of the ribosomal genes already. 

Again the goal is to exclude both cell-cycle genes and ribosomal genes in the dimensional reduction. 

Thank you so much in advance!

**Comment by satijalab** [comment]
You can replace the mitochondrial reduction with ribosomal reduction (just change the gene set). However we don't recommend this, as biological differences can be easily blended with technical ones

**Comment by cesco-lemon** [comment]
Hi everyone,

I've tried to regress out ribosomal genes from my datasets (I've tried without regressing them out first but it was too confounding and decided to try get rid of them).
I've used similar lines as for mitochondrial genes:

**#mitochondrial genes**
mito.genes <- grep(pattern = "^MT-", x = rownames(x = Mgcoculture@data), value = TRUE)
percent.mito <- Matrix::colSums(Mgcoculture@raw.data[mito.genes, ])/Matrix::colSums(Mgcoculture@raw.data)
Mgcoculture <- AddMetaData(object = Mgcoculture, metadata = percent.mito, col.name = "percent.mito")
**#look at ribosomal genes**
RPS.genes <- grep(pattern = "^RPS", x = rownames(x = Mgcoculture@data), value = TRUE)
percent.RPS <- Matrix::colSums(Mgcoculture@raw.data[RPS.genes, ])/Matrix::colSums(Mgcoculture@raw.data)
Mgcoculture <- AddMetaData(object = Mgcoculture, metadata = percent.RPS, col.name = "percent.RPS")
RPL.genes <- grep(pattern = "^RPL", x = rownames(x = Mgcoculture@data), value = TRUE)
percent.RPL <- Matrix::colSums(Mgcoculture@raw.data[RPL.genes, ])/Matrix::colSums(Mgcoculture@raw.data)
Mgcoculture <- AddMetaData(object = Mgcoculture, metadata = percent.RPL, col.name = "percent.RPL")
**#filter cells**
Mgcoculture <- FilterCells(object = Mgcoculture, subset.names = c("nGene", "percent.mito"), 
                           low.thresholds = c(200, -Inf), high.thresholds = c(3000, 0.2))
Mgcoculture <- NormalizeData(object = Mgcoculture, normalization.method = "LogNormalize", 
                             scale.factor = 10000)
Mgcoculture <- FindVariableGenes(object = Mgcoculture, mean.function = ExpMean, dispersion.function = LogVMR, 
                                 x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
Mgcoculture <- ScaleData(object = Mgcoculture, vars.to.regress = c("nUMI", "percent.mito", "percent.RPS", "percent.RPL"))
**Then I run my PCA:**
Mgcoculture <- RunPCA(object = Mgcoculture, pc.genes = Mgcoculture@var.genes, do.print = TRUE, pcs.print = 1:12, genes.print = 10)

However, ribosomal genes are still part of the main PCs. I've double-checked and the genes that come up in the PCs are part of the "RPL.genes" and "RPS.genes" list.
I'm wondering whether I am not regressing them out or if maybe I should change the "pc.genes" in the RunPCA function so that PCA is run on the scaled data.
Any ideas?

Thanks for the help!

Cesco

**Comment by bwang258** [comment]
Hi @cesco-lemon ,

I am not sure if I can help you because I ended up keeping ribosomal genes in dimensional reduction as they turned out to be biologically relevant to one of my samples. However, I did had the same issue as yours initially. The code was roughly the same as yours as well. I ended up seeing ribosomal genes in PC and even in the cluster markers, in which ribosomal genes actually contributed to PC1 and PC2. 

My way out was to manually remove these genes out of the **var.genes** list before PCA. I am not sure if your suggestion would work since **pc.genes** parameter is reading a gene list and the rownames of **scale.data** contains all the genes. 

Not sure if that helps, we could keep the discussion going though.

**Comment by cesco-lemon** [comment]
Hey @bwang258,

Yeah I' getting them everywhere, in PCs and in cluster markers, it is really annoying. I think it has mostly to do with technical issues and the samples make-up itself and I'd like to get rid of them because they're not really giving me real biological differences. I can see the biological relevance of my PCs but ribosomal genes are giving me so much noise that I am sure I am losing more important biological differences. I ended up filtering out cells that have too high of a percentage of ribosomal genes to at list get a go at the data and see what it looks like but I need those cells as part of the dataset too.

I thought that by scaling the data I was automatically removing these genes in **vars.to.regress** right? That's why I was so confused, isn't **RunPCA** using the scaled data to run the analysis? Otherwise it make no sense running the **RegressOut** function in **ScaleData** if nothing gets regressed out...

@bwang258 could you provide the code you used to manually remove the genes from **var.genes**? That would definitely save my life for now!

@satijalab any idea of why my code isn't working? Because theoretically I am regressing out ribosomal genes by using the same workflow as for mitochondrial genes, right? Does it mean that I am not regressing out mitochondrial genes either? Maybe I am not fully understanding what "regress out" entails but based on your cell cycle gene vignette my code should get rid of the variability coming from the gene lists I've provided.

Thank you so much for the help!

**Comment by ZeqiNiu** [comment]
@cesco-lemon Hey, Did you end up removing them? I am getting the exact same problem, interested in what happened next. THANK YOU

**Comment by PierreGCD** [comment]
@cesco-lemon Hello , 
Same here, 
I would like to remove the Rpl/Rps genes but I am getting the same problem as you guys so I am also interested to find a way which work fine.

**Comment by laijen000** [comment]
Hi all! One of my clusters has RPL genes as its top 20 markers. I have read in many threads about removing RPL genes etc, but was wondering if anyone could explain or share relevant papers regarding what a high RPL/RPS expression could indicate (ie, cellular stress/dying cells?) and how you've decided whether to keep or remove them. Thank you!

**Comment by josegarciamanteiga** [comment]
In my experience/opinion, if you high a cluster whose marker genes are mainly (almost all) RPS/RPL and/or mitochondrial then it is technical, that is, for those cells you just picked the most abundant transcripts. In this case, you should remove the cells in those clusters from the analysis and go back to square one. But I would not remove the genes. Still, if the variance in the population of mito/rps/rpl is high, you could regress them out as for cell cycle. 
On the other hand, if the RPS/RPL genes arise from a DGE comparing clusters from one sample to the other, then it could be biologically relevant or it could be that the cells are too similar and the statistics picks up only the most abundant just because they are easier to detect. In this case, I would first check whether the % of total RPL/RPS is not completely different (say 80% vs 20%) because then the DGE is statistically flawed. But if this is not the case I would report a biologically relevant difference between cell types of ribosomal proteins expression

**Comment by Drosophilist** [comment]
@laijen000 Hello! Have you found any papers which link high ribosomal subunit gene expression and cellular stress? Would really appreciate if you could give me a pointer ;) 
Cheers

**Comment by GBeattie** [comment]
I've been playing around with removing ribosomal genes myself, no definitive answer to whether it's advised in some cases, but I did make a regex that selects all human ribosomal genes, can easily be used in PercentageFeatureSet for example, or to remove downstream in DE tests. If anyone sees something wrong with it that would be great to know!

"^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA"

**Comment by levinhein** [comment]
@GBeattie Hello! Thanks for this, I'll try this one. How many recommended %ribosomal genes did you set to remove cells?

**Comment by GBeattie** [comment]
@levinhein I chose not to remove cells, I either remove the ribosomal genes at the start (i.e. remove them from the counts matrix), or remove them after the differential expression analysis, so they don't show up in visualisations.

**Comment by Pentayouth** [comment]
@GBeattie That sounds ... cool.
Actually I saw some [paper](https://www.biorxiv.org/content/10.1101/2020.05.12.091132v1.full) did the same thing:
> We performed Seurat-based filtering of cells based on the number of detected genes per cell (500 to 7000) and the percentage of mitochondrial genes expressed (<10%). The mitochondrial genes and ribosomal genes were also removed from the gene expression matrix.
Is there any paper explain this strategy or it's just an experience-based approach?

Wang.

**Comment by levinhein** [comment]
> I've been playing around with removing ribosomal genes myself, no definitive answer to whether it's advised in some cases, but I did make a regex that selects all human ribosomal genes, can easily be used in PercentageFeatureSet for example, or to remove downstream in DE tests. If anyone sees something wrong with it that would be great to know!
> 
> `"^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA"`

HI @GBeattie This one was helpful to select the ribosomal genes using PercentageFeatureSet. Could you also share the code you used to remove them from the data?

**Comment by denvercal1234GitHub** [comment]
@josegarciamanteiga - Thanks very much for the explanation! Do you know how to identify the cells that express certain genes and then remove those cells from the data before PCA and clustering?

**Comment by GBeattie** [comment]
@levinhein sure, something like this will do (here I'm doing it after CreateSeuratObject, but you can do it before if you like)

seu <- seu[grep("^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA", rownames(seu), value = T, invert = T), ]

**Comment by NicolaasVanRenne** [comment]
@GBeattie that works very well thanks. Been digging into the ribo conundrum myself

**Comment by baymin721** [comment]
> @GBeattie that works very well thanks. Been digging into the ribo conundrum myself. I use the following code
> 
> MySeuratObject<- PercentageFeatureSet(MySeuratObject, pattern = "^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA", col.name = "percent.ribo")
> 
> You can now visualise with FeaturePlot, or exclude cells with high expression of the ribo genes using subset
> 
> HOWEVER!! I had a quick look on ribosomal expression in the pbmc3k dataset and it is HUGE. So it makes no sense removing high ribo content cells because then you will just remove all cells (at least in that dataset). But it argues -to me- that removing such cells is a bad strategy.
> 
> ![image](https://user-images.githubusercontent.com/48249789/105688003-65a34a80-5ef9-11eb-95ba-e6a5023cef8a.png)

Hi, I am super new to data analysis. I tried your code and I kept getting 0 using the code to get percent.ribo, any ideas why?

**Comment by fauxrest** [comment]
> I've been playing around with removing ribosomal genes myself, no definitive answer to whether it's advised in some cases, but I did make a regex that selects all human ribosomal genes, can easily be used in PercentageFeatureSet for example, or to remove downstream in DE tests. If anyone sees something wrong with it that would be great to know!
> 
> `"^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA"`

This regex pattern also captures ribosomal protein kinases, antisense genes, and RP-like genes that have not been confirmed as genuine ribosomal proteins. In a dataset based on the current reference file (CellRanger 2024), 25 of the 107 genes selected by the above pattern should not be present in a list of ribosomal proteins. This can be corrected by assigning the output of the above grep as a vector and running a second grep with `invert=T` and the following pattern: `"[BK-]|AP|[[:digit:]](.+)L"`

This pattern eliminates any ribosomal protein binding protein (B), any kinase (K), any antisense gene (-), any Associated Protein (AP), and any RP-like gene, [[:digit:]](.+)L
