### ISSUE TITLE
accelerate the execution of FindCluster()

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [satijalab/seurat#7591]
Is there any method to accelerate the execution of FindCluster()? I am dealing with more than one million cells. Prior to clustering, I have normalized and batch corrected the data

`Atac <- FindClusters(object = Atac, algorithm=4, resolution = 1.5, method = "igraph") `

Any suggestions would be greatly appreciated! 

Thanks,
Parul

**Comment by longmanz** [comment]
Hi, 
We do have 'future' to allow parallelization in Seurat (see details at https://satijalab.org/seurat/articles/future_vignette.html), but for FindClusters(), this only happens when you input multiple resolution. 
To accelerate the execution, you may try an even lower resolution (e.g., 1.2, 1.0, 0.8).

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
