### ISSUE TITLE
AddModuleScore for specific clusters

### ISSUE THREAD

**Issue by Ryuichi30** [satijalab/seurat#7594]
Hi,

I would like to calculate module scores in certain clusters (for example, calculating module scores among cluster 0 - 5 if all cluster are 0 - 10).
Is it possible in Seurat? If so, please let me know how to do it.

Thank you,
Ryuichi

**Comment by samuel-marsh** [comment]
Hi Ryuichi,

Not member of dev team but hopefully can be helpful.  So there is currently not a way to do this on whole object.  The easiest way to do is probably to subset/split the object by ident and then run `AddModuleScore` on each sub-object and then if you wanted combine them all back together.  However, in that case the module scores of different clusters would not be comparable to each other because of being run separately.  In fact comparing module scores across clusters is difficult even if run on whole object.

You may want to check out UCell which can provide help with the issue of scores being shifted by dataset composition.
https://doi.org/10.1016/j.csbj.2021.06.043
https://bioconductor.org/packages/release/bioc/html/UCell.html

Best,
Sam

**Comment by yuhanH** [comment]
Thank you @samuel-marsh  for your nice reply. I fully agree with you.

**Comment by Ryuichi30** [comment]
> Hi Ryuichi,
> 
> Not member of dev team but hopefully can be helpful. So there is currently not a way to do this on whole object. The easiest way to do is probably to subset/split the object by ident and then run `AddModuleScore` on each sub-object and then if you wanted combine them all back together. However, in that case the module scores of different clusters would not be comparable to each other because of being run separately. In fact comparing module scores across clusters is difficult even if run on whole object.
> 
> You may want to check out UCell which can provide help with the issue of scores being shifted by dataset composition. https://doi.org/10.1016/j.csbj.2021.06.043 https://bioconductor.org/packages/release/bioc/html/UCell.html
> 
> Best, Sam,

Dear Sam, yuhanH

Thank you very much for your information !

Best 
Ryuichi
