### ISSUE TITLE
unwanted genes even adding limited gene list in FindAllMarkers()

### ISSUE THREAD

**Issue by SherylShaw** [satijalab/seurat#7595]
Hello! 
I intend to find differential expressed genes from a specific gene list after the standard flow, so I add *features = gene_list* in **FindAllmarkers()**. Then I get all_markers including 357 genes, but when I check if they are all in my specific gene list, it turns out that there are 118 genes not there. 
I really cannot figure out why... And I wonder if there's any difference between intersecting all_markers in the gene list after running FindAllMarkers() and adding the gene list directly in FindAllMarkers(). Actually the result of the former one has the same amount genes.
Thanks!
```
library(Seurat)
LVCM <- readRDS("tmp/LVCM/LVCM_subcluster.rds")
DefaultAssay(LVCM) <- 'RNA'

library(openxlsx)
gene_list <- read.xlsx("gene_list.xlsx", startRow = 1, sheet = 1)
LVCM_genes <- rownames(LVCM@assays$RNA) 
LVCM_gene_list <- intersect(gene_list$gene_name, LVCM_genes)   # make sure all the genes analysed are involved the LVCM

all_markers <- FindAllMarkers(LVCM, features = LVCM_gene_list, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)


table(rownames(all_markers) %in% gene_list$gene_name)
FALSE  TRUE 
  118   239
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So what is likely happening is that the same gene is a marker of multiple identities.  When that happens Seurat appends a `.1` `.2` etc to the end of the rownames since the rownames of data.frame need to be unique.  However, the gene symbols in the "gene" column will be identical.

I would check:
```
table(all_markers$gene %in% gene_list$gene_name)
```

Best,
Sam
