### ISSUE TITLE
Besides the RunCCA function, are there any other methods or functions available to calculate the Proportion of Variance Explained?

### ISSUE THREAD

**Issue by ZhenyaoYe** [satijalab/seurat#7598]
Hi, 

After obtaining results by using RunCCA function, are there any other methods or functions available to calculate the proportion of variance explained? Thank you! 

Best regards,
Zhenyao

**Comment by longmanz** [comment]
Hi,
Are you referring to RunPCA or RunCCA?

**Comment by ZhenyaoYe** [comment]
> Hi, Are you referring to RunPCA or RunCCA?

RunCCA. Thanks.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
