### ISSUE TITLE
RunUMAP default metric

### ISSUE THREAD

**Issue by jsim91** [satijalab/seurat#7610]
Hello Seurat team. I have a question regarding the choice of the cosine metric as default with umap.method uwot. It looks like the default metric for uwot::umap is euclidean. Does the cosine metric tend to perform better than the other supported metrics on single cell data sets or was the choice to use 'cosine' instead of 'euclidean' simply a matter of personal preference? Thanks.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
