### ISSUE TITLE
Spot coord problem

### ISSUE THREAD

**Issue by oghzzang** [satijalab/seurat#7619]
Dear seurat team. 

My web_summary by spaceranger showed tissue image (left).
But, when I show it using seurat, I have this tissue image (right). 

I think it is flipped (up <➞ down).
Can you explain why they are flipped??
And, How can I flip the image using Seurat object?

Thank you. 

<img width="1193" alt="image" src="https://github.com/satijalab/seurat/assets/33537478/0c089f56-5c3c-4099-a6b5-2b051188ebf1">

**Comment by longmanz** [comment]
Hi, 
Have you tried to use +coord_flip() to flip the coordinates of your plot (https://github.com/satijalab/seurat/issues/6110)?

**Comment by oghzzang** [comment]
Yes, I had tried.
But, it looks wrong. 
I think they couldn't change the image slot. 

```shell
SpatialPlot(obj, features = "nCount_Spatial")  | SpatialPlot(obj, features = "nCount_Spatial") + coord_flip()
``` 

![image](https://github.com/satijalab/seurat/assets/33537478/dc39f47a-5f41-4fb2-85f1-1a59f82b4283)

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.

**Comment by Puriney** [comment]
<img width="1193" alt="256680295-0c089f56-5c3c-4099-a6b5-2b051188ebf1" src="https://github.com/user-attachments/assets/a02bf928-4453-48ae-ad9d-19a824f29dd2">

This is because of the spatial (or image) y-axis is opposite to the ggplot y-axis. Flip the y-axis would give you what you want.
