### ISSUE TITLE
pct.1 is lower than pct.2 for every positive averagelog2FC in DE analysis

### ISSUE THREAD

**Issue by hbussan** [satijalab/seurat#7629]
Hello,

I am running scRNAseq on cells from WT and from KO mice. Each was a separate scRNAseq run, so I merged the datasets together and ran dimension reduction and clustering.

I am now trying to determine the differentially expressed genes between WT and KO within the same cluster. I run FindMarkers which runs completely without error. Code below

`b.interferon.response <- FindMarkers(immune.combined2, ident.1 = "4_Rey05", ident.2 = "4_Rey06", logfc.threshold = log(1.5), min.pct = 0.25, verbose = FALSE)`

When the AverageLog2FC is negative, the pct.2 is generally higher than pct.1 (example shown below) 

<img width="1332" alt="Screenshot 2023-08-01 at 12 32 44 PM" src="https://github.com/satijalab/seurat/assets/16260611/97b296de-3b22-4b62-8e6f-a665953cb6bb">

However, whenever the AverageLog2FC is positive, the pct.1 is always smaller than pct.2. I have an example below - all my identified DEGs look like this.   I would figure there are a couple of genes in which the pct.1 < pct.2 generates a positive AvLog2FC if a small number of cells are expressing a gene particularly highly. But I wouldn't expect that each Positive AverageLogFC is associated with a pct.1 population that is much smaller than pct.2. 

<img width="1347" alt="Screenshot 2023-08-01 at 12 29 40 PM" src="https://github.com/satijalab/seurat/assets/16260611/d80ff794-42ab-49d9-b774-6f6878c535bd">

Is this an issue with cluster identification? Or is a merge issue? Any tips would be appreciated. Thanks!

**Comment by Jiayi-Zheng** [comment]
Do a violin plot of these genes and see if it's the case that these few cells have significantly much higher expression?

**Comment by longmanz** [comment]
Hi,
It is hard to tell the reason from our end as we do not have access to the dataset. But there are a few things you can check:
1. Check if the assay and slot is set correctly. You should only use "RNA" assay (or "SCT" assay in some cases) to perform DE test. 
2. A positive avg_log2FC value means that this gene is down-regulated in group 1 (4_Rey05). So theoretically you should see lower pct for that gene in group 1 because it is "turned-down" (not always the case of course). Since you are using a logfc.threshold to select the top DEGs, it is possible that for these top DEGs, such relationship is more profound and thus it leads to your extreme observation. You can lower the logfc.threshold to 0.1 or 0.01 to include more small-effect DEGs, and re-check the pct v.s. avg_log2FC relationship.
