### ISSUE TITLE
wnn analysisfor spatial transcript and spatial  metabolic   

### ISSUE THREAD

**Issue by lvmt** [satijalab/seurat#7643]
hi, thanks for your wanderful tools.   
nowadays, i'm studying the releationship between spatial transcript and spatial metabolic. i want to know if seurat can be used to integrate sptail data with wnn analysis.  

need your help and thanks.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
