### ISSUE TITLE
Spatial feature plot of only cells within a given cluster

### ISSUE THREAD

**Issue by ivingan01** [satijalab/seurat#7646]
I think the title sorta explains the whole issue. I would like to make a spatial feature plot for my samples (the kind where you have a color scale for the expression of a given gene across the sample) but limit the highlighted spots only to those within specific clusters. i know you can do `cell.highlight = WhichCells(., expression = FEATURE >0) ` to monochromatically highlight all colors expressing that gene. but how do you get the function to return a color gradient of its expression?

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.

**Comment by iddryg** [comment]
I was looking for the same functionality. The only thing I can think of is FetchData the genes you want to plot, merge those into the metadata, then set all cells to zero expression in your metadata in clusters you don't want to plot. Then use that metadata column to plot the feature plot. Definitely not straightforward as a nice function to do the same
