### ISSUE TITLE
effect of nFeature_count difference on AverageExpression

### ISSUE THREAD

**Issue by caochch** [satijalab/seurat#7649]
Dear authors,

I have two groups of cells (marked as group A and groupB). Each group was sequenced separately. After integration, I used AverageExpression to get expression values of some genes. The results indicated that the vast majority genes (~80%) showed decrease in the group B by visually checking the heatmap. I did not know whether it is real or just raised by batch effect.

After tracing back, I found that the nFeature_count for groupA is much larger than that for groupB (4000 vs 2000). I am wondering whether this scenario lead to the observed heatmap. Specifically, the counts for a gene not detceted in groupB cells were recorded as zero, this lead a higher percentage of zero counts in groupB and thus lower value by AverageExpression. Am I correct? and how to fix this issue?

My command is :
AverageExpression(object, features =geneList, assays = 'RNA')$RNA -> geneExp
pheatmap(geneExp, scale='row')

Looking forward to your valuable answers.

**Comment by longmanz** [comment]
Hi,
It seems that the seq depth of your group A and B are very different, which led to the systematic difference between them (as you observed for nFeature_count). It is not recommended to combine them to perform AverageExpression() or DE test directly. You may calculate the AverageExpression() separately for them. You will likely observe that the AverageExpression() in group A is systematically higher than group B. However, this is hard to tell if this is just due to sequencing depth (batch effect) or due to real biological difference.

**Comment by caochch** [comment]
This is why I feel confused, as group B cells showed even **higher** sequencing depth (i.e., higher nCount_RNA) but lower nFeature_count values.

**Comment by longmanz** [comment]
Hi, 
That is very strange. With a high(er) nCount_RNA we usually expect the nFeature to be high(er) as well. 
Was group B sequenced with a different pipeline/assay? Or was group B a different cell lines / species from group A?

**Comment by caochch** [comment]
They are different cells collected at distinct developmental stages. Group
B cells (from 28-days old mice) are more mature than Group A (1-day old
mice), but they are both from the same tissue.

Longda ***@***.***> 于2023年8月17日周四 22:31写道：

**Comment by caochch** [comment]
I can not tell whether it has biological significance or just be raised by some batch effects that I did not know.
