### ISSUE TITLE
Showing the expression of a set of genes as binary

### ISSUE THREAD

**Issue by fereshtehizadi** [satijalab/seurat#765]
Sorry, this is not a issue rather my problem that I could not figure out myself, I need your kindly help please. 

Usually, when we are trying to plot the marker intensities in a heat map or feature plot, they have strongly skewed distributions with varying ranges of expression, thus making it difficult to distinguish between the negative and positive cell populations. It is common practice to transform marker intensities with a cofactor. For example like below but this gets quantile (between 0 and 1) while I need binary

```R
library(matrixStats)
rng <- colQuantiles(expr, probs = c(0.01, 0.99))
expr01 <- t((t(expr) - rng[, 1]) / (rng[, 2] - rng[, 1]))
expr01[expr01 < 0] <- 0
expr01[expr01 > 1] <- 1
```

**Comment by mojaveazure** [comment]
What are the values of the genes you have? If they're not 0/1, `TRUE`/`FALSE`, yes/no, or something like that, then they're not binary. If you have values of expression that are binary, you can add those values to object meta data, then use the `group.by` argument to view in with `DimPlot`

```R
> vals # Some vector where the length is the number of cells in your dataset and each value is one of two values, one for TRUE and one for FALSE
> cc <- AddMetaData(object = seurat, metadata = vals, col.name = 'binary')
> DimPlot(object = cc, reduction.use = 'tsne', group.by = 'binary')
```

Note that if you do this, you will not have a gradient of colors. Gradients show a range of data (continuous data) while binary is one or the other (discrete data). `DimPlot` and any of it's helper functions (eg. `PCAPlot`, `TSNEPlot`, etc) will only show discrete colorings since it's designed to show groups, not ranges. Cell identities are discrete since they're one of a set group of possible values, some point in an infinite range of values.

If you'd like a gradient showing continuous ranges of expression, use `FeaturePlot` instead. `FeaturePlot` can pull values from object meta data and show them continuously.

```R
# This won't be meaningful, since 'binary' is one of two values, but it'll work and color values on a gradient
# You can use FeaturePlot to plot anything that FetchData can pull
> FeaturePlot(object = cc, features.plot = 'binary', no.legend = FALSE)
```

**Comment by fereshtehizadi** [comment]
Really thanks a lot for replying me, honestly this is my long time problem that I can't solve

Actually the problem is setting a threshold to transform an expression data matrix to a binary matrix 

for example we have cells 1 to 3 and genes A to E

```
      CELL1 CELL2 CELL3
A       0.0   1.0   1.0
B       0.0   1.0   0.0
C       0.0   1.0   0.0
D       1.0   0.0   1.0
E       1.0   1.0   1.0
Ratio   0.4   0.8   0.6
```

For creating this matrix I I used quantile 0.01 and 0.90 % by which the ratio of the expression of genes A,B,C,D,E in CELL1 is 0.4 (2/5), 0.8 in CELL2 (4/5) and 0.6 in CELL3 (3/5). So I obtained the vector you mentioned 

For example such a vector for a list of marker genes in cluster 0

```
 cell1       cell2       cell3       cell5       cell6       cell7      cell8       cell9       cell10      cell11      cell12      cell13      cell13      cell14      cell15      cell16 
     0.06410152 0.07752379 0.06369479 0.07459530 0.06719271 0.05856992 0.06727406 0.07044660 0.04799479 0.07052794 0.05279427 0.07736110 0.07166680 0.06938908 0.07239893 0.06637924 
```

 I added this vector of values to my metadata and I coloured my cells like picture but it is not binary rather very sporadic (I expect cluster zero has a distinct colour but it does not as the threshold will cover cell in another clusters). My question is how I can set a threshold in creating my binary matrix from an expression matrix where only a set of cells being coloured. Let's say I am going to plot marker genes of cluster 0 so I expect this cluster being coloured as in a heat map we see

```
cc <- AddMetaData(object = seurat, metadata = vector of values of each cell) 
cc <- SetAllIdent(object = cc, id = "value")
TSNEPlot(object = cc)
```
