### ISSUE TITLE
Dim error while plotting spatial expression data with new assay 

### ISSUE THREAD

**Issue by OdmaaBayar** [satijalab/seurat#7667]
Hi! I'm currently analyzing 10x Visium spatial transcriptomics data and added a new assay to my Seurat object
1. Can the new assay I'm loading have different dimensions, specifically fewer spots than my spatial assay?
2. When I try to plot the SpatialFeaturePlot of this new assay's nCount using `SpatialFeaturePlot(spatial_obj, features = "nCount_NewAssay")` I get the following error:
```
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```
I want to be able to plot the new assay, even with fewer spots, so any help would be greatly appreciated. 
Thank you!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
