### ISSUE TITLE
TSNE plot dots that are close together assigned to different clusters

### ISSUE THREAD

**Issue by Leran10** [satijalab/seurat#7668]
Hi,

I have been having trouble to understand why some dots are so closed together in tsne plot but they are assigned to different clusters in FindNeighbors() and FindClusters()?

For example below plot:
<img width="329" alt="image" src="https://github.com/satijalab/seurat/assets/17597071/67af7226-1e09-465f-9693-4cf34f871fb7">

The most of the cluster 0 (red dots) are in bottom right but there are some are scattered in upper left and seem closer to cluster 3 (purple) and cluster 2 (blue) than to cluster 0. 

Then why those dots were still grouped as cluster0?

Thank you!
Leran

**Comment by samuel-marsh** [comment]
Hi,

Not member of devteam but hopefully can be helpful.  This may be better question to ask in general bioinformatics forum (i.e. Biostars) than here which is primary for issues specifically with Seurat package.

That being said there are couple of things I can hopefully give some insight into.

First, is that interpretation of distance between cells/clusters in UMAP/tSNE is not necessarily meaningful.  So I'd be careful before ascribing issues based on how close/far cells are from each other.

Second, is that UMAP/tSNE are dimensionality reduction techniques and showing their plots mainly comes down to displaying a visualization of the data.  So how you assign/label clusters is going to depend on the goal of the visualization among other things.  The choice of how to cluster the data should be made based on examination of the clustering, cells, markers, etc and will also depend on the goals of analysis and planned next steps downstream.

Third, there are several factors that will eventually contribute to assignment to clusters but I think in example you are showing the most likely issue is the resolution parameter in `FindClusters`.  Adjusting this parameter will have significant effects on the number of clusters output and requires some (and in some cases a lot) of iterative analysis and examination to determine optimal parameter for resolution parameter.  If resolution is too high clusters are unlikely to be very distinct from each other but if it is too low then real differences between groups of cells might be lost.  Again the choice here is partially down to the goal of both the visualization and analysis that you intend to perform downstream.  It is up to end user to examine the cluster markers (though again also be careful with DE between clusters because of inherent statistical issues with double dipping) to decide "appropriateness" of clustering.  

Finally, there are some techniques which aim to provide statistical analysis of clustering.  Here is one recent example from Rafael A. Irizarry's group (https://doi.org/10.1038/s41592-023-01933-9; https://github.com/igrabski/sc-SHC)

Best,
Sam
