### ISSUE TITLE
Error with load10x_Spatial

### ISSUE THREAD

**Issue by vravik** [satijalab/seurat#7677]
Hello, I keep getting this error message when I try to load a 10x spatial object in Seurat. 

Error in Load10X_Spatial(file.path(inpath2, sid[[1]])) :   Image must be an object of class 'VisiumV1'.

Could you please tell me how to work around this?

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
