### ISSUE TITLE
spaceranger aggr and Load10X_Spatial function

### ISSUE THREAD

**Issue by stefanerb89** [satijalab/seurat#7682]
I want to load aggregated (processed with spaceranger aggr) spatial transcriptomics samples into R. But this does not work with aggregated samples. This error occurs:

`unable to open /Volumes/all_samples01/outs/spatial/tissue_lowres_image.png`
- because there are sub directories with all samples generated by aggr function."

Is there a strategy to load my spaceranger aggr matrix with different slides into R (with Seurat). Or is there a workaround/code to accomplish this? 

best regards

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
