### ISSUE TITLE
AddModuleScore function and Number of bins

### ISSUE THREAD

**Issue by ShreenaNishaKalaria** [satijalab/seurat#7694]
I am using seurat's addmodulescore function to calculate a module score for my spatial transcriptomics dataset. However, I am getting the following error: "Error in `cut_number()`:! Insufficient data values to produce 24 bins." 

Question 1: What specifically do the bins refer to? It seems to be a bin of genes for comparison to the genes in the module- but does anyone have a link to a complete and accurate description of how calculation of this score works? 

Question 2 (related): When I decrease the number of bins, I am able to avoid this error, and the module score is calculated without issue. However, I don't understand what effects reducing the bin size might have on my analysis. How might the calculation be affected? Will the outputted score be noisier with different/'smaller' controls?

**Comment by longmanz** [comment]
Hi,
Re 1). There is a nice explanation post on how the AddModuleScore() works at [here](https://www.waltermuskovic.com/2021/04/15/seurat-s-addmodulescore-function/). The "bin" is used to divide the genes into different bin given the average expression levels, so that genes have similar expression level will be grouped together. They will be used as background genes during the score calculation.

Re 2). When the number of total genes is not large, reducing the number of bins will avoid insufficient number of genes in some of the bins (and avoid the error you encountered). And you are right that the final results will be noisier, since genes with relatively different expression levels are now grouped together. 

3. If you think such strategy is not very appropriate for your dataset, you may consider using a "binning-free" scoring method called UCell (https://github.com/carmonalab/UCell). This method only relies on the ranking of the genes, without the need of binning of background genes. it is also compatible with Seurat object, with a similar syntax of AddModuleScore (see https://carmonalab.github.io/UCell_demo/UCell_Seurat_vignette.html).

**Comment by ShreenaNishaKalaria** [comment]
Thanks so much for your help @longmanz ! :) Much appreciated.
