### ISSUE TITLE
is avg_diff values in FindMarkers log2 based?

### ISSUE THREAD

**Issue by kathirij** [satijalab/seurat#77]
Just curious whether the avg_diff values in FindAllMarkers or FindMarkers are log2 transformed or a simple average?

**Comment by andrewwbutler** [comment]
The avg_diff value is the difference in average expression (in natural log space) between the two clusters.

**Comment by Hrishi27** [comment]
I was going through the FindMarkers function and I have a question regarding the log(mean) calculations. I am pasting the code below as a reference:  What is the significance of using "expm1" in the log mean calculation? 
apply(X = data.use[genes.use, cells.1, drop = F], MARGIN = 1, FUN = function(x) log(x = mean(x = expm1(x = x)) + pseudocount.use))

**Comment by leonfodoulian** [comment]
Hello Hrishikesh,

`expm1(x)` is equivalent to `exp(x) - 1`. In this code, it allows to compute the mean on non-log transformed data (given the fact that in the `object@data` slot, the data is log normalized). Then the mean is transformed to log space. Computing `log(mean(x))` is not equivalent to `mean(log(x))`. 

Best,
Leon

**Comment by Hrishi27** [comment]
Thank you!

**Comment by yueqiw** [comment]
Hi, I'm confused by the default value of `pseudocount.use = 1`. 

I often set `logfc.threshold = log(2)` to find genes that are differentially expressed at least 2-fold. However, I constantly run into situations where the calculated `avg_logFC` is much smaller than what I expected. I think this is because the default value of `pseudocount.use = 1`. 

From the documentation, the `logfc.threshold` parameter is explained as follows: 

> Limit testing to genes which show, on average, at least X-fold difference (log-scale) between the two groups of cells.

My understanding is that, for a given gene and two groups of cells, if the average count of the cells are `count.1 / count.2 = 2`, then the log fold change should be `log(2) = 0.693`, regardless of the exact value of count.1 and count.2.
```
logfc = log(count.1) - log(count.2)= log(count.1/count.2)  = log(2) = 0.693. 
```

However, with `pseudocount.use = 1` in the code, the formula becomes:

```
logfc = log(count.1 + 1) - log(count.2 + 1)= log[(count.1+1)/(count.2+1)]
```
This makes `logfc` much smaller than log(2) even though `count.1 / count.2 = 2`. This effect is strong especially when count.1 and count.2 are small (e.g. when pct.1 and pct.2 are small).

For example, if the average counts are `count.1 = 0.4, count.2 = 0.2`, `pseudocount.use = 1` gives `logfc = 0.154`, much smaller than log(2) = 0.693. If we set `pseudocount.use = 0.001`, the result `logfc = 0.691` is a much better approximation of the actual log fold change of log(2). 

Even if we set `count.1 = 1.2`, which is a 6 fold change compare to `count.2`, `pseudocount.use = 1` gives `logfc = 0.606`, still smaller than log(2) = 0.693. Setting `pseudocount.use = 0.001` gives `logfc = 1.787`, similar to `log(6) = 1.792`.

So I would suggest changing the default value of `pseudocount.use` to a much smaller value like 0.001 (to avoid zero-division error). I don't quite understand the purpose of adding a large pseudocount when calculating log fold change. 

Thanks!

**Comment by QiangShiPKU** [comment]
@andrewwbutler Why not log2 in line with traditional DE analysis. A doubling (or the reduction to 50%) is often considered as a biologically relevant change. On the log2 scale this translates to one unit (+1 or -1). That's a simple value, easy to recall, and it is more "fine grained" than using higher bases (like log or log10).
https://www.researchgate.net/post/Why_do_we_usually_use_Log2_when_normalizing_the_expression_of_genes
