### ISSUE TITLE
Plotting cluster by sample ids 

### ISSUE THREAD

**Issue by fred166** [satijalab/seurat#7710]
I have a combined matrix file of 7 samples from cellranger_aggr. I have been able to produce cell clusters and plots following the guided tutorial from Seurat. However, I want to plot the cell clusters by their sample id, for example patient number that I have used in the aggregation.csv. I was trying the following code, which might be obsolete now and does not work. If anybody could help me with the correct code to produce such a plot will be highly appreciated. The column containing the sample names in my aggregation.csv file is labelled as ''library_id''. 
I am relatively new to this and kinda getting lost. 

(https://bioinformatics.stackexchange.com/questions/779/handling-sample-identity-in-aggregated-10x-libraries) 
sampleidentity <- cellcodes["samples"]
cells <- Setup(cells,
               meta.data=sampleidentity,
               min.cells=3,
               min.genes=200,
               do.logNormalize=T, total.expr=1e4, project="projectname")

**Comment by longmanz** [comment]
Hi, 
Which version of Seurat are you using? It seems to be a strange way to create a Seurat object using your code.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
