### ISSUE TITLE
FindClusters cannot handle random.seed = NULL

### ISSUE THREAD

**Issue by velten-lab** [satijalab/seurat#7711]
Running FindClusters with random.seed = NULL causes an error
```
Error in RunModularityClusteringCpp(SNN, modularity, resolution, algorithm,  :
Expecting a single value: [extent=0].
```

If random.seed is set to a value (e.g. default), this causes ugly behavior in sampling experiments:

```r
replicate(3, lapply(1:3, function(i,s) { 
s <- FindClusters(s, resolution=res, graph.name = "clone_nn", verbose = F)
return(rnorm(1))
}, s = some_object))
```

Outputs for example:

```
     [,1]       [,2]       [,3]      
[1,] -0.3262334 -0.3262334 -0.3262334
[2,] -0.3262334 -0.3262334 -0.3262334
[3,] -0.3262334 -0.3262334 -0.3262334
```

Workaround can be to set seed to a pre-specified number after the FindClusters statement in the sampling function, but it would be nicer if FindClusters permitted NULL as a seed, same as RunPCA. Thanks for providing this great software!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
