### ISSUE TITLE
performing DGE to compare gene profiles based on a specific marker gene

### ISSUE THREAD

**Issue by JoBeh** [satijalab/seurat#7717]
Hi guys,

I have a snRNA Seq dataset, my task is to find out if the expression of a certain genes in the cells leads to differences in the gene expression profile in the same cells. Important to mention is, the expression of the gene of interest is not a column in the metadata, so in order for me to find the cells that expressed the gene I subsetted my data like this:

#subsetting the data based on gene expression
positive_cells <- subset(seuratObj, subset = `Td-tomato` > 0) 
negative_cells <- subset(seuratObj, subset = `Td-tomato` == 0)
 

Now, I have 2 Seurat objects and I don't know how or if it is possible to compare gene profiles between them. 

Can you help to perform DGE analysis between cells that are Td-tomato positive and cells that are Td-tomato negative?

if you need more information to understand the matter please let me know.4

Thanks a lot in advance and looking forward to your help.

**Comment by longmanz** [comment]
Hi, 
I am not 100% sure if this is what you want, but here is my strategy given your dataset:
1. Since you have 2 datasets, you may first [merge](https://satijalab.org/seurat/articles/merge_vignette.html)() or [integrate](https://satijalab.org/seurat/articles/integration_introduction) them first. Integration is not necessary if you only care about the DE analysis. However, if you want to harmonize the cell type/cluster information between your 2 datasets, you may need to do integration first. 

2. After you merge() / integrate your datasets, then you can run 
```
DefaultAssay(seuratObj) = "RNA"
positive_cells <- colnames(seuratObj)[seuratObj@assays$RNA$data["Td-tomato", ] > 0]
negative_cells <- colnames(seuratObj)[seuratObj@assays$RNA$data["Td-tomato", ] == 0]
```
to get the cell IDs for the 2 groups.

3. Now you can run DE test:  
```
res = FindMarkers(seuratObj, slot = "data", cells.1 = positive_cells, cells.2 = negative_cells)
```

**Comment by JoBeh** [comment]
Hi longmanz,

Thanks a lot for you response. I encountered this error now. 

> res = FindMarkers(seuratObj, slot = "data", cells.1 = positive_cells, cells.2 = negative_cells)
Error in FindMarkers.Seurat(seuratObj, slot = "data", cells.1 = positive_cells,  : 
  At least 1 ident must be specified in `ident.1`

any ideas?

Thanks in advance.

**Comment by wjyzidane** [comment]
I got the same error. any solution?

**Comment by longmanz** [comment]
Hi,
Sorry this is the right command:
`res = FindMarkers(seuratObj, slot = "data", ident.1 = positive_cells, ident.2 = negative_cells)`

**Comment by wjyzidane** [comment]
Thank you!
