### ISSUE TITLE
feature.loadings after runCCA

### ISSUE THREAD

**Issue by RawanSO** [satijalab/seurat#7718]
Hi,
How to get the feature.loadings for each of the two objects used to run CCA (I.e, features loadings for x and features loadings for y )? Also, to double check my understanding .. Does the feature.loadings holds the maximum correlation between the two objects?
Thanks

**Comment by zskylarli** [comment]
Hi, do you mean PCA?

**Comment by RawanSO** [comment]
Hi,
runCCA will produce @cell.embeddings and @feature.loadings. Why there is only one @feature.loadings, not @feature.loadingsX and @feature.loadingsY for example?
Shall I calculate the loadings for each dataset by

 cca_res = RunCCA(obj1, obj2, num.cc =30   ,renormalize = FALSE,rescale = FALSE,verbose = TRUE) 
cca_call= cca_res[['cca']]
varF = rownames(cca_call@feature.loadings)
x.aux.calc = obj1@assays$RNA@scale.data[varF,] 
y.aux.calc = obj2@assays$RNA@scale.data[varF,]
u = cca_call@cell.embeddings[colnames(x.aux.calc),] #colnames(x = obj1)
  v = cca_call@cell.embeddings[colnames(y.aux.calc),] #colnames(y = obj2)
  xscores <- x.aux.calc %*% u
  yscores <- y.aux.calc %*% v
where scores and scores the features loadings calculated for each dataset object, respectively.
Thank you for your advice in advance

**Comment by zskylarli** [comment]
Hi - in CCA, the objective is to find linear combinations of features in each dataset (here, obj1 and obj2) that are maximally correlated. The @feature.loadings in Seurat's CCA output represent these linear combinations and are shared across both datasets because they are derived from a joint analysis. Essentially, CCA seeks to find a common subspace where the datasets are most similar, hence the single set of loadings. Your method seems like it's effectively projecting the data from each object onto the CCA space defined by @cell.embeddings, but these scores are not the same as having separate @feature.loadings for each dataset, but are projections of each dataset onto the common CCA space. If you have any further questions, please feel free to reopen the issue!
