### ISSUE TITLE
grey background image with SpatialPlot

### ISSUE THREAD

**Issue by cathalgking** [satijalab/seurat#7721]
The ability to grey out the background image of a spatial transcriptomics experiment using the function `SpatialPlot()`. This is possible when using the scanpy spatial plot and the bw parameter such as
`sc.pl.spatial(A1, img_key="hires", color="clusters", size=1.1, bw=True, palette="Paired")`
It would be nice to be able to do the same with Seurats `SpatialPlot`

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
