### ISSUE TITLE
DE analysis after Running Harmony

### ISSUE THREAD

**Issue by JS0715** [satijalab/seurat#7724]
Hi Team,

I used harmony to integrate multiple datasets and have removed the batch effect. Wondering what is the best way to run DE analysis of disease vs control in this case on my seurat object? I am pretty new to data integration, and this is my first-time using harmony.  Appreciate your suggestions and thoughts on the same.

Thanks!

**Comment by alikhuseynov** [comment]
this [workflow](http://htmlpreview.github.io/?https://github.com/immunogenomics/harmony/blob/master/docs/SeuratV3.html) is with Seurat v3 but the principle is the same. For data normalization you can use `SCTransform()` workflow.

**Comment by longmanz** [comment]
Hi,
After you are done with the Harmony and integration, you will have different cell types/clusters for your integrated data. For each cell type/cluster, you can run FindMarkers() to identify DE genes. 
However, please note that the DE tests should be done with your "RNA" assay, instead of "integrated" assay. The "batch effect" among the different datasets are "removed" just for the purpose of integration. You should NOT use "integrated" assay to perform DE tests. 
For your DE tests after integration, you can follow example in this vignette ("Identify differential expressed genes across conditions" section of this [vignette](https://satijalab.org/seurat/articles/integration_introduction) ). 
Alternatively, as alikhuseynov has suggested, you can use SCTransform() to normalize your datasets and perform DE tests with the "SCT" assay.

**Comment by JS0715** [comment]
Thank you for the response @longmanz @alikhuseynov!
