### ISSUE TITLE
Whether Integration remove true biological difference and steps prior to integration?

### ISSUE THREAD

**Issue by JiahuaQu** [satijalab/seurat#7731]
Hi, here all my questions are about the `Integration` methods provided by Seurat.
1. I found three `Integration` manuals: 
(1) default CCA: https://satijalab.org/seurat/articles/integration_introduction.html; 
(2) RPCA: https://satijalab.org/seurat/articles/integration_rpca.html; and 
(3) IntegrateLayers: https://satijalab.org/seurat/articles/seurat5_integration.
2. In (1) and (2), you showed the examples to first split data according to `stim`, which represents two different treatments, and then integrate them. **I wonder whether this way will remove the true biological difference because it looks like you regarded the treatment as the batch effect** that should be removed whereas the true biological difference derived from the treatment should remain because we usually want to know the difference between two treatments, such as DEGs or clusters. For example, my previous colleagues followed these manuals to obtain negative results in all differential gene expression analyses between two stim/treatments. It's unexpected that there's no difference between treatment vs. control in all our projects. Given this, the (3) manual makes more sense to use different technical methods as an example to integrate data.
3. It's also confusing among your different manuals about the steps prior to Integration. Specifically, in the manual 
(1) the sequences were: 1) NormalizeData, 2) FindVariableFeatures, 3) SelectIntegrationFeatures, 4) FindIntegrationAnchors, 5) IntegrateData, 6) ScaleData, 7) RunPCA; 
but in 
(2) they were: 1) NormalizeData, 2) FindVariableFeatures, 3) SelectIntegrationFeatures, 4) ScaleData, 5) RunPCA , 6)FindIntegrationAnchors, 7) IntegrateData, 8) ScaleData, 9) RunPCA; 
but in 
(3) they were quite unclear what steps were required before running `IntegrateLayers`. 
**Can method (3) replace (1) and (2) in the future use?**
4. After we used the different versions, (1), (2) and (3), of `Integration`, `which slot/assay` should we use for (1) Vlnplot, (2) featureplot, (3) DoHeatmap, (4) DotPlot, (5) differential gene expression (DEGs), (6) pseudotime trajectory analysis, respectively?
5. Is there any difference if I use the `SCTransform` normalization method? Should I run one more `ScaleData` and `RunPCA` for `rpca`?
Thank you very much for answering so many questions in advance.

**Comment by longmanz** [comment]
Hi,
The purpose of integration: when different samples were sequenced differently, in many cases we cannot know if the difference between them (like stim and ctrl in our dataset) was truly driven by biological difference or batch effect (usually a mix of both). Since we know that stim and ctrl groups should have (almost) the same cell type composition (since they are both PBMCs), at least the majority of cells from the 2 groups should form well-mixed PBMC clusters together.

However, if you simply merge them (without integration) and run UMAP, you will see that the cells form very distinct clusters from the 2 groups (which is not likely). That is why integration is important. 

The integration should NOT impact your DE test. This is because integration only removes the batch effect and use the "integrated" assay (which is kind of the batch-corrected count matrix) for integration. When we run DE test, we should only use the "RNA" assay (uncorrected one) to perform the DE test. Integration only gives us a better cell type clustering/annotation, but it will not affect the DE test results. 

method (3) can replace (1) and (2) if you are using Seurat v5. All the standard processing in (1) and (2) is now wrapped up by (3). 

The analyses you listed should only happen to RNA assay, not the integrated assay. 

If you are using SCTransform, you do NOT need to run ScaleData. You can directly run RunPCA.
