### ISSUE TITLE
Integration of visium datasets

### ISSUE THREAD

**Issue by oghzzang** [satijalab/seurat#7750]
Dear Seurat team, 
Hi, I have 6 visium data derived from the different liver tissues. 
Before integration (harmony or integrateData), they look so different. 
So I thought I need to integrate them. 

When I integrate them, I'm going to use the variable features calculated from `FindSpatiallyVariableFeatures` like this. 

For individual sample,
1. NormalizeData 
2. FindVariableFeatures
3. ScaleData
4. FindSpatiallyVariableFeatures

For integration 
1. Merge them 
2. NormalizeData
3. ScaleData on the `SpatiallyVariableFeatures of 6 samples`
     - I will find some method similar with `SelectIntegrationFeature`
4. PCA
5. Harmony

How about this flow? do you think it's reasonable?

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
