### ISSUE TITLE
SCTransform gives fewer DE genes

### ISSUE THREAD

**Issue by JS0715** [satijalab/seurat#7765]
Hi Team,

I used harmony to integrate multiple datasets and have removed the batch effect. Tried log normalization and SCTransform approaches to compare both methods along with harmony. Upon running DE analysis, I see drastic differences in the number of DE genes obtained in SCtransform (~60 DE genes) DE analysis vs log normalization (~450 DE genes) DE analysis. Below is the code I ran for each. Can you please help me understand why there is a big difference between the two?

DefaultAssay of SeuratObj_SCT is SCT

DefaultAssay of SeuratObj is RNA

DE<-FindMarkers(SeuratObj,ident.1 = "Disease",ident.2 = "Control",only.pos = T) #~450 DE genes

SeuratObj_SCT<-PrepSCTFindMarkers(SeuratObj_SCT)
DE_SCT<-FindMarkers(SeuratObj_SCT,int,ident.1 = "Disease",ident.2 = "Control",only.pos = T,assay=SCT) #~60 Genes

Thanks!

**Comment by saketkc** [comment]
Hi @JS0715,

These differences are expected because of the underlying differences between the two normalization approaches. In particular, NormalizeData uses a scale factor of 10000 while SCtransform uses a default scale factor of median sequencing depth (besides being a different approach statistically).
