### ISSUE TITLE
Regressing out nuisance parameters with millions of cells

### ISSUE THREAD

**Issue by roryk** [satijalab/seurat#777]
Hey all,

Do you all have any suggestions for how we can cut down on the memory usage when running `ScaleData` and regressing out parameters? This step blows up the memory for me to 200 GB+ when operating on 20k genes with around a million cells. If I subset down to around the most variable 4k genes then I can fit it in, but it would be nice not to do that.

**Comment by andrewwbutler** [comment]
Hi,

Unfortunately, `ScaleData` transforms the data matrix in such a way that it becomes non-sparse and that's why you're seeing the memory blow up with a 20k genes x 1M cell dataset. Just as a quick estimate, if we assume every entry in that matrix costs 8 bytes to store, you're looking at a 160GB matrix. That's one of the main reasons we recommend scaling only the genes that are going to be used in downstream functions (i.e. variable genes). Other than subsetting down the number of genes or cells, you could consider trying out our hdf5/loom based implementation of some of the Seurat functions that make use of on disk computation. Here's a [brief intro to loomR](https://satijalab.org/loomR/loomR_tutorial.html) and an example [analysis vignette](https://satijalab.org/seurat/mca_loom.html) to get started.

**Comment by roryk** [comment]
Thanks! That makes good sense. Thanks so much for the links to loom, I'll take a look at that for sure.

**Comment by roryk** [comment]
Is this something that can be done in chunks? Does the whole matrix need to get desparsed, or could we operate on chunks of it? The genewise regressions should be independent, right?

**Comment by andrewwbutler** [comment]
Yep, gene-wise regressions are independent and can be chunked. This is why it's able to run on a smaller subset of genes.

**Comment by zhiiiyang** [comment]
@andrewwbutler, the analysis vignette link seems not to be working anymore (https://satijalab.org/seurat/articles/mca_loom.html). Do you have an updated link? Thank you!

**Comment by andrewwbutler** [comment]
Hi,

I've restored that webpage available [here](https://satijalab.org/loomr/mca_loom) now.  Just a note, this vignette is built for Seurat v2; current support for loom files is handled by the new [SeuratDisk](https://github.com/mojaveazure/seurat-disk) package.
