### ISSUE TITLE
FindConservedMarkers no longer returning "mixed" attributes

### ISSUE THREAD

**Issue by paraish** [satijalab/seurat#7773]
Hello,

In the past, when I've run FindConservedMarkers, it would return a few columns with mixed p values, Log2FC, etc. Now, it no longer returns these aggregated attributes. I'm running Seurat 4.3.0, and my call to the function is:
`IFN_markers = FindConservedMarkers(IFN5,"No IFNg", "With IFNg", grouping.var = "Annot2")`

Those "mixed" outputs were really helpful, and advice on how I can get them back would be really appreciated!

**Comment by saketkc** [comment]
Can you post what your output of `FindConservedMarkers`, look like? For an example, see [this vignette](https://satijalab.org/seurat/articles/sctransform_v2_vignette)

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
