### ISSUE TITLE
In the process of single-cell clustering, there are always some independent small subgroups, and I feel very helpless in dealing with them.

### ISSUE THREAD

**Issue by M-jk22** [satijalab/seurat#7778]
In the process of single-cell clustering, there are always some independent small subgroups that I feel helpless to deal with. These three or four very small subgroups cannot be well-annotated and are not useful for my own research. Are there any proper methods to handle them, or relevant research references to help me deal with these small subgroups? Thank you.
![db34bba741797de41d976dd305c54a4](https://github.com/satijalab/seurat/assets/110780219/8c7f6c41-5d1e-460b-9d9d-e297433a235d)

**Comment by Pentayouth** [comment]
just delete those clusters. little information could be inferred from such a small number of cells.

**Comment by igrabski** [comment]
Thanks for your question. In general, I would not recommend deleting clusters or otherwise removing data unless you are confident they represent low-quality cells, etc. Here, how large are the subgroups you are finding? If they come up consistently across different attempts to cluster, it could be possible they represent some real signal. If you use `FindMarkers`, are there any genes highly expressed in those groups that seem biologically plausible? If not, is there any other commonality among those cells? For example, any batch differences, or differences in data quality (e.g. on the basis of total RNA, number of unique genes, mitochondrial percentage, or other QC metrics?)
