### ISSUE TITLE
Overlapping cluster annotation caused by doublet?

### ISSUE THREAD

**Issue by synatkeamsk** [satijalab/seurat#7784]
Dear Senior developers/instructor,

I used Seurat to cluster my single cells and use singleR for annotation, but there seems to be an overlapping cluster / annotation. Are they doublets? or just error with annotation (circle in red). if they are doublets, is there any standard workflow in seurat I could remove them from seurat object! thank you before hand.

Kind Regards,

![Seurate](https://github.com/satijalab/seurat/assets/121846660/017c8e43-04a4-42ed-8198-2e918a199854)

Synat,

**Comment by rsatija** [comment]
What is likely happening here is that just a single cell is being aberrantly labeled as a Chondrocyte, but since that cell is located in the middle of the T cell cluster, it looks like there is overlap.

you can demonstrate this by adding cells.highlight to DimPlot, and highlight only the cells that are labeled as Chondrocytes.
