### ISSUE TITLE
RunMultiCCA

### ISSUE THREAD

**Issue by MiaoCui** [satijalab/seurat#779]
Dear Seurat team,

Thank you so much for getting this amazing package setup and maintained!

I have some questions regarding the RunMultiCCA function. I understand that it merges objects, so I assume that it will automatically do the normalization and scaling? I have eight objects that have variable numbers of genes/UMI as well as mito percentage detected. So I wonder if it's necessary for me to do NomalizeData and ScaleData to the merged object ( I have done that to the eight individual objects)?

Lastly, given that my mito percentage is highly different, do you recommend regression on mito percentage for the merged object?

Thank you!

Miao Cui, PhD

**Comment by rjtower** [comment]
I have 2 questions regarding the RunMultiCCA trying to combine 4 scRNA-seq runs.

i) First, I create a list of variable genes for each data set, then combined into a unique list. But I get script out of bounds when I run the RunMultiCCA. I found that this is because, while some genes are highly variable within 2-3 runs, that gene is not expressed in one of the runs. Can I sort my "genes.use" list by only expressed genes for each of my 4 data sets?

ii) If I manually remove non-expressed genes from my genelist, the CCA list runs fine. But when I try to check the analysis with eg. DimPlot(object = object, reduction.use = "cca", group.by = "group", pt.size = 0.5, do.return = TRUE), I get the following error:

Error in reduction.type %in% names(object@dr) :
trying to get slot "dr" from an object of a basic class ("list") with no slots

This was not a problem when I was doing pairwise CCA comparisons.

**Comment by satijalab** [comment]
We have an updated v3 workflow for multi-sample comparisons that addresses these questions and errors, which you can explore at https://satijalab.org/seurat/
