### ISSUE TITLE
LIGER factors: "iNMF" vs "iNMF_raw" ?

### ISSUE THREAD

**Issue by mabbasi6** [satijalab/seurat#7798]
Hi,

I am using LIGER to integrate batches of my scRNA-seq dataset by using the SeuratWrappers package following [this tutorial](https://github.com/satijalab/seurat.wrappers/blob/master/docs/liger.html). After integration, my Seurat object has two reductions "iNMF" and "iNMF_raw". I wanted to ask what the difference between the two is, and which one I should look at to get the loadings matrix.

Thanks!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
