### ISSUE TITLE
Failed installing on R 3.3.3

### ISSUE THREAD

**Issue by MonkeySylvia** [satijalab/seurat#780]
Hi,
My R version is 3.3.3 (I can't update to 3.4 due to my MAC OS version), and I can't find a way to install Seurat. I tried both the official and development version, and they both gave me this result

```
"Downloading GitHub repo satijalab/seurat@develop
from URL https://api.github.com/repos/satijalab/seurat/zipball/develop
Installing Seurat
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/qn/rzqqg7291393d6h137sldg5w0000gn/T/RtmpL6T89u/devtools263972093695/satijalab-seurat-3cd9be0'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

ERROR: this R is version 3.3.3, package 'Seurat' requires R >= 3.4.0
Installation failed: Command failed (1)"
```
Should I install an old version of Seurat or is there another way to solve this issue? Thank you!
Sylvia

**Comment by mojaveazure** [comment]
Hi Sylvia,

We recommend that you upgrade your versions of macOS and R so that you can use the latest version of Seurat. If you absolutely cannot do these things, then you can download old releases of Seurat from our [releases page](https://github.com/satijalab/seurat/releases) or [CRAN archive](https://cran.r-project.org/src/contrib/Archive/Seurat/). Version 2.3.0 is the latest version that works on Seurat 3.3.3
