### ISSUE TITLE
create spatial seurat object manually

### ISSUE THREAD

**Issue by VenomEvoDevo** [satijalab/seurat#7801]
Hi! It would be great if you can create a command to load Visium data which are not from the SpaceRanger output folder. This means, creating a spatial seurat object using as input:
1. count matrix (features x spots)
2. tissue_hires_image.png
3. tissue_positions.csv (i.e. coordinates)
4. scalefactors_json.json (perhaps optional?)

I tried to create a spatial object with Read10X_Image and then merge it with the Seurat object which contain the count matrix, but I don't know how to do it. I've seen lots of posts of people asking for a canonical way to create spatial seurat object without being forced of using the SpaceRanger spatial output directory.

Thank you,

\Giulia

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
