### ISSUE TITLE
Seurat v5 function to combine FOVs

### ISSUE THREAD

**Issue by dpcook** [satijalab/seurat#7803]
Hi there,

I'm working with some Nanostring CosMx data and have a single object that was made from merging ~50 smaller objects (each 1 FOV from the same slide). _Aside: decided to build the object this way instead of starting with the entire dataset because there didn't seem to be convenient functionality for filtering out poor quality FOVs or conveniently making crops based on Nanostring's "fov" category in the metadata_ 

I can use Crop() to subset a region within an individual FOV, but is there an approach to create a new FOV that combines existing FOVs with global/tissue coordinates?

Thanks!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.

**Comment by Mmaycon** [comment]
Are there any updates on that?
