### ISSUE TITLE
The necessity of running RunPCA before FindIntegrationAnchors in SCTransform

### ISSUE THREAD

**Issue by okamo9chi** [satijalab/seurat#7808]
Hello,

I have a question about the SCTransform workflow. I noticed that some users run the RunPCA function before performing FindIntegrationAnchors (https://satijalab.org/seurat/articles/integration_introduction.html), while others skip this step (https://satijalab.org/seurat/articles/integration_rpca.html). I would like to understand why there is this difference and whether it is necessary to run RunPCA before FindIntegrationAnchors in the SCTransform workflow.

Could you please explain the reasons and benefits of running RunPCA before proceeding with FindIntegrationAnchors in SCTransform? I want to better understand the rationale behind this practice.

Thank you for your assistance and clarification.

Best regards,
Takanari

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
