### ISSUE TITLE
N=1 or how many? for sc RNA experiment

### ISSUE THREAD

**Issue by zara03** [satijalab/seurat#7819]
I am writing to ask for a comment we receive from one of reviewer as she mentioned that n=1 for single cell is not reliable and we need to run more samples.
As you know it’s not a normal everyday experiment so how to address this comment? Or are there any standards which can be referred or followed?

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
