### ISSUE TITLE
HELP, Integrating doublet finder with Seurat v5

### ISSUE THREAD

**Issue by anemartinezlarrinaga2898** [satijalab/seurat#7821]
Hello! 

Is there anyone who is using Seurat V5 and DoubletFinder with a huge amount of cells ( around 1M) that will be willing to have a chat? Im having issues to find people using Seurat V5 in my work environment!

Main questions are: 

- Can the subset function from the Seurat V5 function be used to do DoubletFinder? I know that some of the functions should be change, but I was wondering as I have more than 1M cells it would be interesting to run the DoubletFinder with the sketch assay as the computational cost would be less. 
- Which is the column that should be used to group the cluster in the UMAP? The one with RNA or the one with sketch assay?
- When should be the assay be split in patients or samples? 
- Which is a good number for subsetting? 
- When you changed assays?

Thanks in advanced!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
