### ISSUE TITLE
harmony not working with seurat 3.2.3

### ISSUE THREAD

**Issue by stefanonard85** [satijalab/seurat#7822]
Hello, Seurat  team, 

We are trying to reproduce results generated in 2021 using Seurat 3.2.3 and Harmony 0.1.0 on R v. 3.6.3.
Now, we have R v. 4.2.3. Both installations went well, but when we use Harmony 0.1.0 or 0.1.1 with Seurat 3.2.3, it does not work and gives some error messages, whereas with Seurat 4 works very well. 
Here is the error and the session info, plus lines of code. 
Thx in advance for any suggestions. 

<img width="897" alt="Screenshot 2023-09-18 at 7 49 10 PM" src="https://github.com/satijalab/seurat/assets/16965990/2cc09d99-f948-4c15-acf4-1cdac751f148">
<img width="983" alt="Screenshot 2023-09-18 at 7 56 33 PM" src="https://github.com/satijalab/seurat/assets/16965990/c6cf1da0-8857-46cb-9ff1-0a9c1c0d7426">

_Originally posted by @stefanonard85 in https://github.com/satijalab/seurat/issues/1849#issuecomment-1724102984_

**Comment by longmanz** [comment]
Hi,
This is a bit tricky to debug from our end because we stop supporting v3 a long time ago. According to the error message, it seems that the "U" object you pass to RunHarmony is of class "character"?  Can you check the class(U) to make sure it is of the correct class? 
Alternatively, can you try to convert the 'U' into a SingleCellExperiment object and then run RunHarmony to see if you can avoid the issue?

**Comment by mhkowalski** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen, providing more details about the code you're trying to run.
