### ISSUE TITLE
Reference Mapping - possible to retain reference UMAP shape while extracting novel cell types in query?

### ISSUE THREAD

**Issue by bts76-pitt** [satijalab/seurat#7828]
Hello Seurat team!

We are generating a reference atlas using multiple time points, conditions, treatments to which we are going to map subsequent studies using the refmap pipeline from Seurat. We used the 'de novo' approach to generate the UMAP between the reference and the query, but we noticed that the UMAP shape/structure of the generated reference changes every time we use a new query.

Is there a way to extract novel cell types in the query data set while implementing the refmap to the reference atlas and maintain the shape of the reference UMAP (except for the extra cell types that might be present)? It is important for us to maintain the shape of the reference atlas UMAP as we make our comparisons, to avoid confusion and clearly show differences between the atlas and the query without having too many different UMAP representations.

Ideally, the goal is that our query UMAPs have the same cluster shape as the reference, like the standard reference mapping pipeline, except for the novel cell types. Would this be possible? Please see below for an example.

![refmapping](https://github.com/satijalab/seurat/assets/117182944/5c427a2d-26dd-4e0e-b742-bc7c8ae55739)

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any activity since the release of v4.4.0.

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
