### ISSUE TITLE
Addmodule score different expression range on UMAP v. Spatialfeatureplot? 

### ISSUE THREAD

**Issue by chrkuo** [satijalab/seurat#7854]
I am using addmodule score to look at a composite of genes but when plot onto UMAP the scale reflected is different compared to when I plot the same exact module score onto a spatial feature plot. This should be the same scale since it's pulling from the same data column correct? is there an explanation for this

For example:
![image](https://github.com/satijalab/seurat/assets/119452428/a71c0cd9-dfcb-4d64-bc3d-106541983808)

compared to the UMAP the scale bar is completely different. 

![image](https://github.com/satijalab/seurat/assets/119452428/2460107f-e9d4-4b85-b30e-7bae086ee895)

**Comment by longmanz** [comment]
Hi, 
That is strange since you are inputting the the same "TGFB_features1" for plotting. I cannot reproduce your issues by using our own data (see reproducible codes below). But it seems that the 
```
InstallData("stxBrain")
brain <- LoadData("stxBrain", type = "anterior1")

brain = NormalizeData(brain)
brain = FindVariableFeatures(brain)
brain = ScaleData(brain)
brain = RunPCA(brain)
brain = RunUMAP(brain, dims = 1:20)

brain = AddModuleScore(brain, features = list(test = VariableFeatures(brain)[1:100]))

FeaturePlot(brain, features = "Cluster1")
SpatialFeaturePlot(brain, features = "Cluster1")

```
If you are generating the FeaturePlot or SpatialFeaturePlot using `split.by = `, you should set `keep.scale = NULL` to avoid scaling across groups.  Also, if would be helpful if you can provide reproducible codes for us to test.

**Comment by mhkowalski** [comment]
Hello,

I'm closing this issue as we haven't heard back from you. Please open a new issue if you have additional questions, thanks.
