### ISSUE TITLE
Does the Wilcoxon test meet its assumptions when comparing sub-clusters?

### ISSUE THREAD

**Issue by chanmur** [satijalab/seurat#7869]
Hi, 

My question concerns one of the assumptions of Wilcoxon Rank Sum Test - independence of samples. I am sorry if this is redundant, but I could not really find the answer anywhere else.

When performing differential gene expression analysis using the FindMarkers function on two sub-clusters, there is a good chance that the cells being compared originate from the same samples. Since the test considers individual cells as samples, is it valid to use Wilcoxon test between sub-clusters, as it violates the assumption of independence of samples? I am addressing this specific case, since, when we compare between conditions within clusters, the cells usually originate from different samples belonging to the respective conditions. However, sub-clusters represent cells of different states or subtypes from within the same samples across conditions.

I believe, a similar problem may also exist when finding markers for clusters, since one cluster would be compared against all the others, and the cells being compared, again, may originate from the same samples.

**Comment by longmanz** [comment]
Hi,
You are definitely right about the possibility of violation of independency. If you are concerned about this, you may use mixed-model based method (generalized linear mixed model, GLMM) to account for the within-sample correlation (either to find cluster markers or for DE analyses). Alternatively, you can also pseudo-bulk your cells based on sample information within each cluster, and then run a paired wilcox signed-rank test to account for the within-sample correlation. 
That being said, due to computational burden of GLMM, people still use Wilcoxon rank sum test to find cluster markers. Because we usually only care about the top few markers between 2 clusters, instead of all the DE genes. These top markers are mostly consistent across different methods. Therefore, even if there is a violation of independency, it does not really affect the results/markers we are getting.
