### ISSUE TITLE
The difference between IntegrateLayers() and IntegrateData()

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#7880]
Thank you for the development of Seurat v5. I have been a long-time user of Seurat v2-4.
 
Due to limited computational memory, I recently updated to Seurat v5 in order to integrate my data. I noticed that the [tutorial](https://satijalab.org/seurat/articles/seurat5_integration) has been updated as well.
 
In the previous versions, we utilized `FindIntegrationAnchors()` and  `IntegrateData()`  to obtain a corrected expression matrix, also known as the ‘integrated’ assay.
 
I would like to inquire whether it is possible to obtain the corrected expression matrix by performing `IntegrateLayers()` or if it only results in an integrated reduction of layers for the `RunUMAP()` step. Additionally, I am curious if we can obtain the corrected expression matrix by performing both  `IntegrateLayers()` and  `JoinLayers()` .

Look forward to your reply. Thanks.

**Comment by zskylarli** [comment]
Hi - both IntegrateData() and IntegrateLayers() should return the integrated embeddings, and not the expression matrix. This is due to our method of integration, which performs CCA, anchor identification, and correction in the low-dimensional space. For more information, you can see our paper [here](https://www.sciencedirect.com/science/article/pii/S0092867419305598).
