### ISSUE TITLE
using createseuratobject to convert a SCE object to seurat

### ISSUE THREAD

**Issue by timj6599** [satijalab/seurat#7890]
I have been trying to utilize dropletutils in order to carry out preprocessing and QC steps prior to analysis in seurat. As far as I can tell the SCE is formatted properly, and the counts matrix and metadata I extract in order to supply to createseuratobject seem to be formatted correctly too. However when I run createseuratobject I receive this error message: Error in rep_len(x = value, length.out = length(x = i)) : 
  attempt to replicate non-vector
I couldn't seem to find an example of this happening else where in relation to this function, I apologize if this error message has already been explained previously. I will provide all the code I used up to this point for added context. I checked to make sure the barcodes between the metadata variable and the expression_data variable match, I've checked the dimensions of the variables (number of cells and genes) and they match.

library(dplyr)
library(Seurat)
library(SeuratObject)
library(openxlsx)
library(patchwork)
library(DropletUtils)
library(SingleCellExperiment)
library(Matrix)

dir.name <- "~/Downloads/SC-RNA/SC-RNA/A_Expected_rice_ref_counts15/raw_feature_bc_matrix"
sample_names <- "A_rice_ref_counts"
sce <- read10xCounts(dir.name, sample.names = sample_names, col.names = TRUE, type = "sparse" ) 

set.seed(100)
limit <- 100   
all.out <- emptyDrops(counts(sce), lower=limit)
sce <- sce[,which(all.out$FDR <= 0.001)]

expression_data <- assays(sce)$counts
metadata <- colData(sce)
seurat_obj_A6 <- CreateSeuratObject(counts = expression_data, meta.data = metadata, project = "A_rice_ref_counts")

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So I’m not sure on the error but have you tried just running `as.Seurat` (https://satijalab.org/seurat/articles/conversion_vignette) which should convert SCE to Seurat without need for extracting individual components manually?

The other note is that since you are using data from 10X pipeline the emptyDrops algorithm is already part of that pipeline for cell calling (since Cell Ranger v3).  So unless you want to alter defaults (appears you are calling default parameters here) then running dropletUtils as shown above is probably not necessary (or very different result-wise) from the filtered outputs from 10X pipeline.

Best,
Sam

**Comment by saketkc** [comment]
Hi @timj6599 You should be able to use `as.Seurat()` on SCE objects to convert them to Seurat. Alternatively, you could check if the returned metadata has same rownames as the columns of your count matrix. I will close this for now, but if you are still facing issues feel free to open a new issue.
