### ISSUE TITLE
Umatch between dotplot output and featureplot.

### ISSUE THREAD

**Issue by Kenneth-new-user** [satijalab/seurat#7895]
I am trying to evaluate marker genes for a data set annotated by MapQuery(). I have manually circled a target region using CellSelector() and assigned the cells as "target" and "others" in a metadata column $cluster_dummy. That way we can be sure that no "target" cells are hidden behind the "others" cells.

DotPlot() suggests that "Epha3" is an excellent marker that is highly expressed in a large percentage of target cells but is almost absent from the other cells, but when I look at it in the feature plot, this does not seem to be the case.

Am I doing anything wrong?

```
p1<- DotPlot(adult.v4, features = "Epha3", scale = F) + coord_flip()
p2<-FeaturePlot(adult.v4, "Epha3", reduction = "ref.umap")
p3<-DimPlot(adult.v4, group.by = "cluster_dummy", reduction = "ref.umap")
p1+p2+p3
 ```
![image](https://github.com/satijalab/seurat/assets/140436875/1a81d1ab-2904-4ecb-af45-965d0d856e1e)

**Comment by mhkowalski** [comment]
Hi, 

Thanks for your question. From your UMAP it seems that Epha3 is expressed in additional celltypes besides the cells you have labeled as "target". The average expression in the `DotPlot` function might be low because you are averaging a lot of cells that _don't_ express Epha3 with some that do (it's a bit hard to visualize the density of the underlying points in a UMAP). Visualizing Epha3 expression with `VlnPlot` might be more informative here (so you can visualize the expression for each cell in each group).
