### ISSUE TITLE
RunMixscape Error: NA/NaN/Inf in foreign function call (arg 4)

### ISSUE THREAD

**Issue by rebeccayw** [satijalab/seurat#7899]
Hi! I was running mixscape with no errors, but was having almost all of my cells labeled as "NP". I tried to lower the threshold in the RunMixscape function by lowering the _logfc.threshold_ as well as the _min.de.genes_:

```
RunMixscape(object = seuratToUse_combined, assay = "PRTB", slot = "scale.data",
labels = "Gene_Targeted", nt.class.name = "NT", min.de.genes = 1,
logfc.threshold = 0.1, iter.num = 10, de.assay = "RNA",
verbose = F, prtb.type = "KO")
```

It runs through some of the genes, but will then stop and give me this error:

```
Error in mixtools::normalmixEM(x = pvec, mu = c(nt.norm$mu, guide.norm$mu),  : 
  NA/NaN/Inf in foreign function call (arg 4)
```

However, I have checked and there are no NaNs or Infs in my original seurat object. Would you please be able to advise?

**Comment by longmanz** [comment]
hi, 
RunMixscape performs EM binary classification based on the PRTB scores, which is calculated from the de.genes between the NT cells and the test cells (cells with the same gRNA/target_gene identity). When there is not enough de.genes (less than the min.de.genes we set), it will not do the EM classification, but directly label all the test cells as "NP". 
When you see almost all cells are "NP", this means that there is not enough perturbation response in your test cells. There is not much RunMixscape can do in such scenario. Setting min.de.genes or logfc.threshold to smaller values might force RunMixscape() to work, but it is not ideal. Do not set min.de.genes = 1, because calculating PRTB scores using only 1 gene is not doable (it will create NaN because some of the denominator will be 0 during the process. See SuppNote from the Mixscape paper for details of the PRTB score calculation https://www.nature.com/articles/s41588-021-00778-2). You might try a smaller logfc.threshold value (e.g., 0.05) but keep min.de.genes to 3 or larger, to see if RunMixscape() works.

**Comment by rebeccayw** [comment]
I understand, thanks so much for your response!
