### ISSUE TITLE
Petty request for better code clarity in differential_expression

### ISSUE THREAD

**Issue by jonasfreimuth** [satijalab/seurat#7924]
I would like to request an improvement of code clarity for the [differential_expression](https://github.com/satijalab/seurat/blob/master/R/differential_expression.R) code, ideally in general, but mainly with regards to the computation of the p-Values for the `WilcoxonDETest` via the `limma::rankSumTestWithCorrelation` function (see [here](https://github.com/satijalab/seurat/blob/57564e282a1ba54c655192d907d83df21164dc78/R/differential_expression.R#L2421)). When I read that line I wonder why do you need to multiply the minimum of a function that is supposed to give you a p_value? And why is there a possibility that that result may ever be greater than one? Such non-trivial operations require either deconstruction with descriptive variable naming, or some explanatory comments.

I know this would be very low on any priority list, but I still wanted to ask that this be considered when that function receives changes in the future.

My issue with the rest of the file is a general lack of separation of distinct operational blocks by whitespaces, making it difficult to understand what happens in these individual blocks, and how that ties into what any given function is supposed to achieve. The easiest way to start would be to just add line breaks before introductiory comments like [here](https://github.com/satijalab/seurat/blob/57564e282a1ba54c655192d907d83df21164dc78/R/differential_expression.R#L548), [here](https://github.com/satijalab/seurat/blob/57564e282a1ba54c655192d907d83df21164dc78/R/differential_expression.R#L854-L855), and [here](https://github.com/satijalab/seurat/blob/57564e282a1ba54c655192d907d83df21164dc78/R/differential_expression.R#L1304-L1305).
This code is used by a huge amount of projects and can only benefit by being more accessible to more people.

**Comment by longmanz** [comment]
Hi,
Thank you for pointing this out. We will definitely work harder to do better documentation for our codes. It is generally difficult to do it for every module/function because these are codes from many different colleagues/contributors through many years. But we will certainly improve it.
As for the wilcox command, the codes are indeed not documented and I apologize. To answer your question, the reason for that is because we are doing a 2-sided test `return(min(2 * min(limma::rankSumTestWithCorrelation(index = j, statistics = data.use[x, ])), `1)).`` Therefore, we need to extract the "1-sided test" P-value from the 'smaller side' and then multiply it by 2 to get the 2-sided P-value. 
This is consistent with the default [wilcox.test(), line 258-269](https://github.com/SurajGupta/r-source/blob/master/src/library/stats/R/wilcox.test.R) in R-stats:
```
switch(alternative,
                       "two.sided" = {
                           p <- if(STATISTIC > (n.x * n.y / 2))
                               pwilcox(STATISTIC - 1, n.x, n.y, lower.tail = FALSE)
                           else
                               pwilcox(STATISTIC, n.x, n.y)
                           min(2 * p, 1)
                       },
                       "greater" = {
                           pwilcox(STATISTIC - 1, n.x, n.y, lower.tail = FALSE)
                       },
                       "less" = pwilcox(STATISTIC, n.x, n.y))
```
When using the limma package, we are doing this explicitly.

**Comment by jonasfreimuth** [comment]
Thank you very much for taking the time to reply and explain!
