### ISSUE TITLE
Sctransform - which layer does it use?

### ISSUE THREAD

**Issue by TdzBAS** [satijalab/seurat#7934]
Hi,

I would like to know which layer is sctransform using? the raw counts of the seuratobject, the lognormalized data layer or the scale.data?

And I would also like to know, if it uses the raw counts, what to do if I download a count matrix from GEO, which is already preprocessed and normalized (scale.factor 10000). How to get the raw data from it for the counts layer?

Best,
Tolga

**Comment by igrabski** [comment]
Sctransform operates on the counts, and accounts for technical variability due to factors like sequencing depth. If available, you should instead download the raw counts in order to apply this normalization method. Unfortunately, it is not always possible to backtrack from the normalized data to the original raw counts, e.g. if the original sequencing depths are not known for each cell.
