### ISSUE TITLE
I have some questions about findmarkers and findallmakrer

### ISSUE THREAD

**Issue by dd123456000** [satijalab/seurat#7945]
this is my code   
① levels（pbmc）
 [1] "Sertoli cell_IT"     "Leydig cell_IT"      "Stromal cell_IT"     "Macrophage_IT"       "Endothelial cell_IT"
 [6] "Germ cell_IT"        "Blood_IT"            "Myoid cell_IT"       "T cell_IT"           "Plasma cell_IT"     
[11] "Sertoli cell_NT"     "Stromal cell_NT"     "Leydig cell_NT"      "Myoid cell_NT"       "Germ cell_NT"       
[16] "Endothelial cell_NT" "T cell_NT"           "Macrophage_NT"       "Blood_NT"            "Plasma cell_NT" 
 DEGs <- FindMarkers(pbmc,ident.1 = 'Myoid cell_NT',ident.2 = Myoid cell_IT', verbose = FALSE, test.use = 'wilcox',min.pct = 0.1)
 DEGs <- FindMarkers(pbmc,ident.1 = 'Myoid cell_IT',ident.2 = Myoid cell_NT', verbose = FALSE, test.use = 'wilcox',min.pct = 0.1)
Why is it that the results are different after I swapped the IDs？
②levels（pbmc）
"IT' "NT"
DEGs <- FindMarkers(pbmc,ident.1 = 'NT',ident.2 = ‘IT', verbose = FALSE, test.use = 'wilcox',min.pct = 0.1)
pbmc.markers <- FindAllMarkers(pbmc, only.pos = FALSE,min.pct = 0.25, logfc.threshold = 0)
I want to know if these two sets of results will be the same. Also, this is my first attempt at setting 'idents' as groups. I'm wondering if this result is reliable?

**Comment by igrabski** [comment]
For your first question, swapping the IDs should yield the same markers in the same order and with the same p-values. However, the values in the `pct.1` and `pct.2` columns will be swapped, because which group corresponds to `ident.1` versus `ident.2` is swapped between the two calls. Similarly, the log fold-change values in one output will be the negatives of the other, since the log fold-change compares how much more expression is in the cells corresponding to `ident.1` than the cells corresponding to `ident.2`. 

For your second question, the two calls as you have written them will yield different results because the thresholds are different; for example, in your first call, you have set `min.pct` to 0.1, whereas in the second, `min.pct` is 0.25. Similarly, you set the threshold for log fold-change to 0 in the second call, but the default value used in the first call is either 0.25 or 0.1, depending on the version of Seurat you are using. In general, however, `FindAllMarkers` will essentially be equivalent to collating the results of calling `FindMarkers` with `ident.1` set to each identity and `ident.2` set to `NULL` (i.e. comparing each identity to all other cells).
