### ISSUE TITLE
Importing Visium data without spatial coordinate

### ISSUE THREAD

**Issue by SuhanC** [satijalab/seurat#7953]
Hi, 

Thanks for the accessible software for single cell and spatial transcriptomics.

As I'm trying to import visium data with only with these 4 files:
barcodes.tsv.gz
features.tsv.gz
matrix.mtx.gz
tissue_image.tiff

I realized that it needs spatial coordinate and scale factor json file.
The data is from GEO and I have only those 4 files, so would it be possible to read Visium data out of these files?
I've tried Read10_Spatial and Reading count matrix and Image data separately.

Thank you!

**Comment by rsatija** [comment]
Unfortunately you will need these files in order to know which spatial location each visium spot corresponds to on the image. You can use Read_10X to read the count matrix information in, but there will be no spatial information. The original study authors should have these files and may have accidentally omitted uploading them to GEO.
