### ISSUE TITLE
Adding metadata to large number of H5 files using BPCells

### ISSUE THREAD

**Issue by jcorn427** [satijalab/seurat#7960]
Hello! I'm working with a dataset of 160 samples and having difficulties integrating my metadata with the H5 files. I'm following the "Using BPCells with Seurat objects" vignette and I'm getting stuck when running the `CreateSeuratObject(counts = data.list, meta.data = metadata)` command. Since I have so many samples, the cell barcodes get reused and I run into an error about non-unique barcodes. I've been trying to figure out how to get around this issue and any help would be much appreciated. Thanks.

**Comment by InternetExplorerBoy** [comment]
Hi @jcorn427,
I'm not part of the dev team, but I'm also currently struggling to get BPCells to work with a large SeuratObject (v5), consisting of multiple samples (layers).

I came across the exact same problem you are mentioning here. I solved it by extending each cell name with the sample ID (in order to make the cell names unique), then using these unique cell names to construct a cell-level meta data frame.
From the help page of `CreateSeuratObject()`:

> Additional cell-level metadata to add to the Seurat object. Should be a data.frame
> where the rows are cell names and the columns are additional metadata fields. Row names in the metadata need to
> match the column names of the counts matrix. 

```
# From the "Using BPCells with Seurat objects" vignette
# In the code from section "Load data from multiple h5ad files"
# Inside the for-loop, where you loop over the set of .h5 files, at the end I added

for (i in 1:length(files.set)) {
  # Follow steps in vignette

  # Before writing matrix to disk
  # Rename cells (column names) to unique names, in order to facilitate later addition of sample meta data
  colnames(data) <- sapply(colnames(data), function(x) {
    x <- paste0(x, "-", sample_id)
    return(x)
  })

  # Follow steps in vignette

  # Construct cell-level meta data for current sample
  sample_meta <- data.frame()
  for (i in 1:length(colnames(data))) {
    sample_meta <- rbind(sample_meta, meta_data[sample_row, c("title", "series_id", "tissue", "diagnosis", "treatment")])
  }
  # Unique cell names as meta data rows
  rownames(sample_meta) <- colnames(data)
  
  # Append cell-level meta data to list
  meta_data_list[[sample]] <- sample_meta
}

# Then outside the for-loop
# Reduce meta_data_list
metadata <- Reduce(rbind, meta_data_list)
```

I don't know how your original meta data looks like, but mine was sample-level (1 row = 1 sample). But the meta data needs to be cell-level (1 row = 1 cell).

However, now I'm stuck with the function SaveSeuratRds(), which throws me the warning:
> Warning: No layers found matching search pattern provided

...which I interpret as that the layers I created are not recognized by the function. 

Hope this was helpful to you. If you encounter a similar warning like me further down-stream, I would appreciate it if you could let me know, as I am not sure whether it's a bug in SaveSeuratRds() or a mistake of my own.

**Comment by jcorn427** [comment]
Thanks for your help! I went with a similar solution. Regarding your problem with SaveSeuratRds(), I've just been using saveRDS() to save my seurat objects without issue. Is there a reason to use SaveSeuratRDS() over the regular one?

**Comment by igrabski** [comment]
Thanks, at this time we don't recommend using `SaveSeuratRds()` so using `saveRDS()` is fine -- however, updates will be coming soon in the future to rectify `SaveSeuratRds()`.
