### ISSUE TITLE
Default setting for anchor filtering

### ISSUE THREAD

**Issue by cbligaard** [satijalab/seurat#8007]
Hi Seurat team,

First, thanks for a great set of tools and R package. I have a question regarding the parameter `k.filter` which is used in `FindTransferAnchors`. In Seurat v. 4.3.0, the default value for this parameter is set to 200, but in some cases (e.g. when using SCTransformed data), this is overwritten and the value is changed to NA - resulting in no filtering of the anchors and also a dramatic drop in runtime (as was also noted in #5206).

In Seurat v. 5, the default for `k.filter` has been adjusted to NA (https://github.com/satijalab/seurat/releases). I would like to understand why this change was implemented and particularly, how using/not using anchor filtering affects mapping results? For `FindIntegrationAnchors` I noticed that the default value for `k.filter` remains 200.

I hope you can clarify this,
Christina

**Comment by zskylarli** [comment]
Hi - thanks for the question! With k.filter set to a specific number, the algorithm filters and retains only the top k anchors based on their scores. This can ensure that mappings are valid, as it prioritizes stronger connections between anchors in the high-dimensional space. We describe the exact methods in our Stuart et al. Cell 2019 paper. When k.filter is set to NA, this means that all potential anchors are used, which can be beneficial when dealing with very heterogeneous datasets, but could introduce noise or less relevant connections into the analysis. As for the parameter being overwritten at times, we use internal parameter validation functions that can turn k.filter off depending on the assay structure or normalization method. 

We turned anchor filtration off for FindTransferAnchors by default in v5 since 1) it is not fully supported for multi-layer objects as of now and 2) it can be slow to run and in most cases not necessary in a label-transferring context. If you are using a v5 object with layers and/or used SCTransform, you will not be able to use anchor filtration as of now as they are incompatible methods. Hope this makes sense and please let me know if you have more questions.
