### ISSUE TITLE
Version 5 installation

### ISSUE THREAD

**Issue by cathalgking** [satijalab/seurat#8025]
Tried to install Seurat version 5 with:
`install.packages('Seurat')`
However, version 4.3.0.1 is installed instead. The same thing happened on a different computer. Also tried removing package and installing again.
I tried with the older method to install version 5 and an 'Install Build Tools' prompt pops up which returns the same error whether I say yes or no, presumably because it is no longer accessible from GitHub that way.
`devtools::install_github("satijalab/seurat", "seurat5")`
Error:
```{r}
Downloading GitHub repo satijalab/seurat@seurat5
Error: Failed to install 'Seurat' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```
How can I install version 5?

**Comment by cathalgking** [comment]
@Gesmira 
Can someone look into this?
Thanks

**Comment by Gesmira** [comment]
Hi, 
The `seurat5` branch is no longer updated, if you do want to install the latest Seurat version from github you can just install from the master branch. However, the fact that you're getting both CRAN install as well as github install issues is unusual and does not seem to be related to Seurat. Did either of you attempt to solve the devtools error? Some details [here](https://stackoverflow.com/questions/66359031/install-with-devtoolsinstall-github-fails-to-detect-build-tools). 

The CRAN install should install the latest version of Seurat as well. What version of R are you running? The following command can also be used to check where you are getting packages from. 
```
options()$repo
```
Another thing to try is installing SeuratObject first, in case your install is erroring out due to older SeuratObject version and is not being automatically installed. 
```
install.packages('SeuratObject')
install.packages('Seurat')
```

**Comment by cathalgking** [comment]
Yeah, maybe the issue is related to other packages"
```{r}
library(Seurat)
Warning messages:
1: package ‘SeuratObject’ was built under R version 4.2.3 
2: package ‘sp’ was built under R version 4.2.3 
3: package ‘Seurat’ was built under R version 4.2.3
```

**Comment by cathalgking** [comment]
installed it by removing seurat object and seurat wrapper first.
