### ISSUE TITLE
Using SCTransform with sketch based analysis

### ISSUE THREAD

**Issue by jcorn427** [satijalab/seurat#8046]
I have a large (1.36 million cells post filtering) single cell dataset that I would like to use sketch based analysis with but I would like to use SCTransform on the cells as well. What would be the correct order to run these two commands? I'm guessing that it would be SCTransform first then do the sketch based analysis on the SCT assay. If anyone could let me know, that would be great. Thanks.

**Comment by longmanz** [comment]
Hi, 
You can definitely use SCTransform to perform sketch based analysis. You can do the SCTransform (instead of the normalizeData) first, can then do sketch based analysis as in this vignette (https://satijalab.org/seurat/articles/seurat5_sketch_analysis). Please do not forget to include `normalization.method = "SCT"` when running `IntegrateLayer()`.

**Comment by leqi0001** [comment]
Hi,
Sorry to reopen this thread. I'm also trying to integrate data using Seurat v5 and SCTransform following this code:
https://satijalab.org/seurat/articles/seurat5_integration

options(future.globals.maxSize = 3e+09)
obj <- SCTransform(obj)
obj <- RunPCA(obj, npcs = 30, verbose = F)
obj <- IntegrateLayers(
  object = obj,
  method = RPCAIntegration,
  normalization.method = "SCT",
  verbose = F
)

However, I wasn't able to specify reference samples in IntegrateLayers. Is this specific to the SCT method? 

Thanks!
