### ISSUE TITLE
Error when looping with `DimPlot `- empty plot 

### ISSUE THREAD

**Issue by wjzwjz5** [satijalab/seurat#8066]
When I want to plot in a loop using `DimPlot ` and save to pdf using `pdf() dev.off()`, all the saved images are empty.

This problem can be easily repeated and solved.Since I found that someone in 2021 had already proposed this bug, which can be fixed in loops with a simple `p1<-DimPlot() print(p1)`, I wonder if there is a better way to solve this problem now

This is an example that can reproduce this error.
```
for (i in 10:30) {
  merge_data <- RunUMAP(merge_data,reduction = "harmony",dims = 1:i)
  pdf(paste0("./dimplots/All_merge_Umap_dim_", i, ".pdf"))
  DimPlot(merge_data,group.by = "cluster_zero",reduction = "umap",label = TRUE, repel = TRUE, label.size = 2.5,raster=FALSE)
  dev.off()
}
```

**Comment by zandigohar** [comment]
Not on the Seurat developer team but I think this is not a Seurat bug but rather an enhancement request. You would like `DimPlot()` to return `print(ggplot.object)` instead of `ggplot.object`.

When you save a plot to a file using functions like ggsave(), it often automatically prints the plot to the device before saving it. However, when you're manually using pdf() and dev.off(), you need to use print() to ensure that the plot is properly displayed on the device before saving.

If you omit the `print()` function when creating `ggplots` in a loop, plots are **not** explicitly printed to the graphics device. The `print()` function forces the plotting functions to actually draw the plot and display it on the screen or save it to a file.

Alternatively, you may modify your code just a bit (put `DimPlot()` in `print()`, that's it!) as below:
```
for (i in 10:30) {
  merge_data <- RunUMAP(merge_data,reduction = "harmony",dims = 1:i)
  pdf(paste0("./dimplots/All_merge_Umap_dim_", i, ".pdf"))
  print(DimPlot(merge_data,group.by = "cluster_zero",reduction = "umap",label = TRUE, repel = TRUE, label.size = 2.5,raster=FALSE))
  dev.off()
}
```

**Comment by wjzwjz5** [comment]
Thanks for your answer！
