### ISSUE TITLE
Cluster-wise Violin plot for integrated data with P-value

### ISSUE THREAD

**Issue by shamimaTU** [satijalab/seurat#8080]
Hi all,

I am in the process of generating a violin plot illustrating the expression of a specific gene in scRNAseq data, which includes two groups (B6-2dpi and Ctrl) and 11 clusters. I want to create a plot like this (Please ignore the p-value here. I just randomly used these to make an example)-
<img width="788" alt="Screen Shot 2023-11-22 at 11 49 27 AM" src="https://github.com/satijalab/seurat/assets/92605695/44839cd8-bb09-4d65-8787-f749e47d2ce1">

But I am getting like this (The clusters do not exhibit a specific order, and the groups B-2dpi and Ctrl are not placed together)-
<img width="803" alt="Screen Shot 2023-11-22 at 11 50 19 AM" src="https://github.com/satijalab/seurat/assets/92605695/35d4cb94-dc20-44cb-bdde-adae435278b3">
Please see the code below -
```ruby
library(tidyverse)
library(Seurat)
library(SeuratObject)
library(ggsignif)
library(ggpubr)
DefaultAssay(immune.combined) <- "RNA"
immune.combined$celltype.covid <- paste(Idents(immune.combined), immune.combined$covid, sep = "_")
immune.combined$celltype <- Idents(immune.combined)
Idents(immune.combined) <- "celltype.covid"
my_comparisons <- list( c("T cells_B6_2dpi", "T cells_B6_Ctrl"), c("B cells_B6_2dpi", "B cells_B6_Ctrl"), c("Myeloid cells_B6_2dpi", "Myeloid cells_B6_Ctrl"), c("NK cells_B6_2dpi", "NK cells_B6_Ctrl"), c("Myeloid cells_B6_2dpi", "Myeloid cells_B6_Ctrl"), c("Myeloid cells_B6_2dpi", "Myeloid cells_B6_Ctrl"), c("Fibroblast_B6_2dpi", "Fibroblast_B6_Ctrl"), c("Endothelial_B6_2dpi", "Endothelial_B6_Ctrl"), c("Erythroid_B6_2dpi", "Erythroid_B6_Ctrl"), c("Non-specific_B6_2dpi", "Non-specific_B6_Ctrl"),c("B & T cells_B6_2dpi", "B & T cells_B6_Ctrl"),c("Epithelial_B6_2dpi", "Epithelial_B6_Ctrl"))
VlnPlot(immune.combined, features = "C3", split.by = "covid", pt.size = 0.0, log = TRUE) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + stat_compare_means(comparisons = my_comparisons) + ylim(0, 12)
```
I would greatly appreciate any help.
Thanks in advance!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So this doesn't seem to so much be an issue with Seurat as it is the interaction of ggpubr with the plot generated by Seurat.  

That said I would strongly recommend against using ggpubr in this fashion period (to calculate DEG and pvalues on plotted data).  You should be calculating those values using appropriate DE expression method meant for either scRNA-seq (if at cell level) or bulk/pseudobulk (often most appropriate at group level, likely the case here where you are comparing groups and it is important to take replicates and other factors into account).  ggpubr will not perform appropriate multiple correction testing because the plot data is subset of full dataset and cannot take into account other covariates that proper DE methods do.

Best,
Sam

**Comment by shamimaTU** [comment]
Hi Sam,
Thank you so much for your reply. 
Could you kindly explain the application of the DE method in this context? I encountered difficulty obtaining any p-value until I incorporated gbpubr. Your guidance in providing the corresponding code would be immensely appreciated.
Thanks again!
