### ISSUE TITLE
FindVariableGenes comes out with error

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#809]
I found i if data without filtered accrording to https://satijalab.org/seurat/pbmc3k_tutorial.html came out with an error, and when I tried to save the pdf, always autosaved a pdf named Rplots.pdf and I can not open it, I do not know the use of the Rplots.pdf

what is more, my pdf looks very abnormal, not like the https://satijalab.org/seurat/pbmc3k_tutorial.html even I reset the param x.high.cutoff bigger.
![image](https://user-images.githubusercontent.com/25199946/46196768-8283df00-c33a-11e8-859c-1d4ee8fc1da6.png)

**Comment by 2236529177** [comment]
the purpose of  FindVariableGenesis to  Identifies genes that are outliers on a ’mean variability plot’  means find unwanted gene?  I still can not understand the meaning of the pdf

**Comment by andrewwbutler** [comment]
The first error that you're encountering may be because you didn't normalize the data (via `NormalizeData`), though it's hard to say without more context. The purpose of this function is to identify genes that are highly variable. We provide a brief description in the tutorial you linked to. For a detailed description, you can checkout the [Macosko et al, 2015](https://www.cell.com/abstract/S0092-8674(15)00549-8) paper.
