### ISSUE TITLE
Integration and differential gene expression

### ISSUE THREAD

**Issue by Victor-K27** [satijalab/seurat#8108]
Dear all, 

Thank you for this wonderful package. 

I am here to ask a mainstream question: can the "integrated" assay slot be used for differential gene expression across conditions, marker identification between clusters in the same condition etc. I know this has repeatedly been asked #1717 and #3014 , and in other forums (https://www.biostars.org/p/456603/).

I however want to gain a bit more insight into how NOT recommended this approach is. Is it completely wrong to do it or not? Is there a predictable way in which it will affect results? (e.g. will it give rise to more false positives?). In my case, using the integrated slot reveals a lot more differentially expressed genes between conditions, and in some cases I have no DEGs when using the RNA slot and hundreds with the integrated slot. 

Also, some the results of the DE on the integrated slot are in accordance with other techniques (i.e. flow cytometic analysis has confirmed some of the results). The reason I am asking is because I do not understand the extend to which this is not recommended to do.

Thank you in advance for your time and consideration

**Comment by rsatija** [comment]
It is not appropriate to use the integrated assay for DE. The reason for this is that the integration procedure aligns cell types, matching cells in shared biological states across conditions. However, as a result of this, in order to identify differences in transcriptional profiles of the same cell type across conditions (the reason we perform integration in the first place), you do need to use the un-integrated, or RNA, assay.

**Comment by martuskaR** [comment]
@rsatija Thank you so much for explaining!
How about in this vignette, https://satijalab.org/seurat/articles/integration_introduction.html#perform-integration-with-sctransform-normalized-datasets. 

After running PrepSCT, doesn't FindMarkers() find markers on SCT, which is the integrated assay? 

Thanks a lot!
