### ISSUE TITLE
LOGFC threshold values and their effects on logFC of top DEGs

### ISSUE THREAD

**Issue by nygr** [satijalab/seurat#8120]
Hi, I am using FindMarkers to test DEG's between two groups of cells. In order to calculate fdr using benjamini-hochberg instead of default, I changed my FindMarker parameters from logfc.threshold = 0.1 to 0 and min.pct from 0.01 to 0 and compared the results. With the lower thresholds of 0, some of my DEG genes have now FoldChanges of -10 when before with 0.1 and 0.01 they were around -3. Does descreasing the thresholds and thus increasing number of tested genes increase the power of the results - so is it more accurate to say that my foldchange of gene x is more likely to really be -10 than -3? Or am I doing something completely wrong?

My code: de_perturbation <- function(IDENT1, IDENT2, GENELIST=NULL, RETURNTHRESH=0.05, LOGFC=0, MIN.PCT=0){
  
  result <- FindMarkers(k562,
                        test.use = "t",
                        #return.thresh = RETURNTHRESH, 
                        logfc.threshold = LOGFC,
                        ident.1 = IDENT1,
                        ident.2 = IDENT2,
                        features = GENELIST,
                        min.pct = MIN.PCT)
  
  if(length(result) == 3) {
    result <- data.frame(p_val = NA, avg_logFC = NA, pct.1 = NA, pct.2 = NA, p_val_adj = NA)
  }

**Comment by igrabski** [comment]
Sometimes very lowly expressed genes can have high fold-changes, somewhat as an artifact of low expression -- if you imagine a scenario where a gene has near-zero expression in one group but some expression in the other, that will inflate the fold-change by nature of comparing to a near-zero value. Because your second `FindMarkers` call is no longer restricting the set of genes by `min.pct`, you are now getting more lowly expressed genes, which explains why you are seeing so many more extreme fold-changes.
