### ISSUE TITLE
Log fc discrepancies between Seurat version 3.2.0 and Seurat V5

### ISSUE THREAD

**Issue by Tushar-87** [satijalab/seurat#8168]
First of all, my apologies if this issue appears to be a repeat. I searched in already posted questions. The solutions to those questions did not help me. 

There is a huge difference in log fc between version 3.2.0 and version 5.
Unfortunately, I cannot reinstall version 3.2.0 to reproduce the earlier data.
I tried using docker but no success there. 
I checked all other parameters (slot, assay, normalization, log base etc).

With version 3, I got log fold change 0.77
With version 5 (I am using this currently) the log fold change is around 5.5

here are the results with version 5 using various layers and assays (just to check if I get a value of 0.77 as with version 3):
> FoldChange(ec.all, features = "Ttr", ident.1 = "a5cx", ident.2 = "wt1cx", base = exp(1), assay = "RNA", slot = "data")
    avg_logFC pct.1 pct.2
Ttr  5.576341 0.224 0.001
> FoldChange(ec.all, features = "Ttr", ident.1 = "a5cx", ident.2 = "wt1cx", base = exp(1), assay = "RNA", slot = "counts")
    avg_logFC pct.1 pct.2
Ttr  5.295536 0.224 0.001
> FoldChange(ec.all, features = "Ttr", ident.1 = "a5cx", ident.2 = "wt1cx", base = exp(1), assay = "SCT", slot = "data")
    avg_logFC pct.1 pct.2
Ttr  5.117611 0.207 0.001
> FoldChange(ec.all, features = "Ttr", ident.1 = "a5cx", ident.2 = "wt1cx", base = exp(1), assay = "SCT", slot = "counts")
    avg_logFC pct.1 pct.2
Ttr  5.338301 0.207 0.001

Is there anything else that I can check to find out reasons behind these discrepancies? I am sure that I used correct assay and slot after normalization. I also tried normalizing data again.

I checked another data. There also I found difference between version 3 and 5 for log fold change. Other results are exactly same. The p values and pct do not change between version 3 and 5. There is no apparent correlation between version 3 and 5 fold changes.
![fold change version 3 and 5](https://github.com/satijalab/seurat/assets/27356193/7403cce8-303c-4fe3-9f87-71f73c2879af)

**Comment by RobJackson28** [comment]
@Tushar-87 I noticed this as well. Reasons are stated in [News -> Changes in Seurat v5](https://satijalab.org/seurat/articles/announcements#:~:text=As%20a%20result%2C%20users%20will%20observe%20higher%20logFC%20estimates%20in%20v5)

> Differential expression:
Seurat v5 now uses the [presto package](https://github.com/immunogenomics/presto) (from the Korunsky and Raychaudhari labs), when available, to perform differential expression analysis. Using presto can dramatically speed up DE testing, and we encourage users to install it.
In addition, in Seurat v5 we implement a pseudocount (when calculating log-FC) at the group level instead of the cell level. As a result, users will observe higher logFC estimates in v5 - but should note that these estimates may be more unstable - particularly for genes that are very lowly expressed in one of the two groups. We gratefully acknowledge feedback from the McCarthy and Pachter labs on this topic.

**Comment by Tushar-87** [comment]
Thank you @RobJackson28. 

Indeed, the manner in which pseudocount is implemented makes the difference in logfold change estimation. The question now is which method gives more realistic fold change estimates (Version 3 with cell level pseudocount or version 5 with group level pseudocount)? 

For highly expressed genes, does version 5 method  give realistic fold change? and for lowly expressed genes does version 3 give accurate fold change? Will the fold change estimation be more accurate if we turn off the pseudocount?

One can compare the vln plots with  fold change estimates and get an impression whether the fold changes aptly describe what we see in the graph. Does this approach make sense? 

It would be helpful to know different experiences on this issue.

**Comment by rsatija** [comment]
The documentation that Rob shared does address this - for lowly expressed genes, Seurat v5 may return much higher log fold-changes, but these are more unstable (i.e. small changes to the data could strongly affect results).

We encourage users not to simply use logFC as a metric to identify or rank DE genes, but to consider the other metrics as well (p-value, and the difference in percentage detection) - all of which we return in `FindMarkers`
