### ISSUE TITLE
FindTransferAnchors ERROR: cannot add different number of cell than already present

### ISSUE THREAD

**Issue by JessicaKLL** [satijalab/seurat#8175]
I'm trying to calculate the transfer anchors with FindTransferAnchors with the following code (the input features are present in both data):

`transfer.anchors<-FindTransferAnchors(reference = rna,query = atac,
                                      features = markers, 
                                      reference.assay = "RNA",query.assay = "gene_activity")`

The following error occurred:

`Warning: Keys should be one or more alphanumeric characters followed by an underscore, setting key from gene_activity_ to geneactivity_
Performing PCA on the provided reference using 3277 features as input.
Projecting cell embeddings
Finding neighborhoods
Finding anchors
	Found 1994 anchors
Filtering anchors
	Retained 111 anchors
Error: Cannot add a different number of cells than already present`

But I have the same number of cells in both data:

`dim(rna@assays$RNA)
[1] 38224 37717`
`dim(atac@assays$gene_activity)
[1] 16787 37717`

Version of Seurat: 4.4.0
Version of R: 4.3.0

**Comment by nathan-nakatsuka** [comment]
Hi @JessicaKLL , it seems likely that the reason you have this error is due to having too few anchors. You can try to remove the filtering features by changing the k.filter or max.features. It is unclear to us why your data is having so many anchors filtered out, though. The other thing is that we are unsure why you are doing the findtransferanchors with datasets that have exactly the same number of cells. If this is multiome data from say ATAC and RNA, you can integrate within the object via WNN (https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis), which would not require finding transfer anchors.
