### ISSUE TITLE
SCTransform error

### ISSUE THREAD

**Issue by jessicaliu09** [satijalab/seurat#8185]
Hi,
I ran the following code
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$batch)
obj <- SCTransform(obj, variable.features.n = 3000, vars.to.regress = c('percent.mt','nCount_RNA'))

It worked for some batches, but then stopped at this batch with error: 
Getting residuals for block 1(of 2) for Batch12 dataset
Getting residuals for block 2(of 2) for Batch12 dataset
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': incorrect number of dimensions
Calls: SCTransform ... get_residuals -> as.matrix -> .handleSimpleError -> h
Execution halted

This batch seems to have enough cells as other batches
 table(obj$batch)
Batch          Number of Cells
B4             3905
B5             4734
B6             1864
B7             4727
B8             3900
B9             3478
B10            5131
B11            4342
B12            5001
B13            4656
B14            4871
B15            4863
B16            5213
B17            2254
B18            5052
B19            6357
B20            4391
B21            5425
B22            5849

 packageVersion('SeuratObject')
[1] ‘5.0.1’
packageVersion('Seurat')
[1] ‘5.0.1’
> packageVersion('SeuratWrappers')
[1] ‘0.3.2’
> packageVersion("sctransform")
[1] ‘0.4.1’

Do you know the causes?

Thanks.

**Comment by saketkc** [comment]
Hi @jessicaliu09 I cannot replicate this with our test datasets, but if you can email me your object on schoudhary@nygenome.org, I can take a look.

**Comment by jessicaliu70** [comment]
Hi, 

I have sent the email.

I have another question for SCTransform.
What's the minimum number of cells for running SCTransform? 
Here, each batch is an experiment. 
When I ran SCTransform for each batch, it gives me many small clusters, while log normalization doesn't. And I don't see this for cell types with more cells in each batch. It seems it is because the number of cells in each batch is too small? 


SCT normalized for celltype1:
![OPCs_dimplot_sct umap unintegrated_3_2](https://github.com/satijalab/seurat/assets/85238061/791d5c6b-af30-4422-ba09-d8ce5c838067)

SCT +  integration by harmony for celltype1:
![OPCs_dimplot_sct umap integrated dr_3_2](https://github.com/satijalab/seurat/assets/85238061/78eb8d0a-5c4f-45fa-bfb1-205e405c1757)

SCT +  integration by harmony for celltype2:
![Microglia_dimplot_sct umap integrated dr_3_2](https://github.com/satijalab/seurat/assets/85238061/ad74f603-64f4-4447-9361-15c9fc433bb5)
Here, you can see there are many small clusters even after integration.

log normalized for celltype1:
![OPCs_dimplot_umap unintegrated_3_2](https://github.com/satijalab/seurat/assets/85238061/3ed4cbc3-88bd-44f8-82da-5cf3b76b86e5)


My code for sctransform: 
for each main cell type I run the following: 
obj[["RNA"]] <- split(obj[["RNA"]], f = obj$batch)
obj <- SCTransform(obj, variable.features.n = 3000, vars.to.regress = c('percent.mt'))
obj <- RunPCA(obj, npcs = 50, verbose = F)
obj <- FindNeighbors(obj, dims = 1:50, reduction = "pca")
obj <- FindClusters(obj, resolution = 0.5, cluster.name = "sct_unintegrated_clusters", method = "igraph",algorithm=4)
obj <- RunUMAP(obj, dims = 1:50, reduction = "pca", reduction.name = "sct.umap.unintegrated")

obj <- IntegrateLayers(
  object = obj,
  method = HarmonyIntegration,
  normalization.method = "SCT",
  verbose = F,
  k.weight=30,
  new.reduction = "integrated.dr",
)
obj <- FindNeighbors(obj, dims = 1:50, reduction = "integrated.dr")
obj <- FindClusters(obj, resolution = 0.5, cluster.name = "dr_clusters", method = "igraph",algorithm=4)
obj <- RunUMAP(obj, dims = 1:50, reduction = "integrated.dr", reduction.name = "sct.umap.integrated.dr")

**Comment by saketkc** [comment]
Thanks for sharing the object. I have pushed a fix here https://github.com/satijalab/seurat/commit/64a6495ec17759d2a7513c706871b9167dece01c
You can install the `develop` branch to test:

```r
remotes::install_github("sataijalab/seurat", ref="develop")
```

For your question about small clusters, you could try restricting the residual range to something smaller`SCTransform(clip.range = c(-5,5))`. SCT uses 2000 cells for parameter estimation which is a reasonable assumption for most single-cell datasets but in case your batch size is small, restricting the clip range might be useful to prevent cells from generating high residuals. Hope this helps!
