### ISSUE TITLE
Seurat RenameIdents not working

### ISSUE THREAD

**Issue by DublinLeigh** [satijalab/seurat#8247]
Hi all,
I am at my wit's end with this.  I have an object and am simply trying to rename the idents that are stored in metadata.  The problem is that while the new idents come up in the active.ident slot, nothing happens within the metadata column at all. 

Code snipet
Idents(Obj) <- "celltype"
Obj<- RenameIdents(Obj, "1"= "B cells",
                                           "2" = "NKT,
                                           "3"= "T cells")

When I run this, active.ident changes correctly, but "celltype" in metadata still says, "1" and "3"

I have also tried directly rewriting the metadata with
Obj$celltype <- c("B cells", "NKT", "T cells") only to get _Error: No cell overlap between new meta data and Seurat object_

I tried putting the new ids into a vector as well only to get the same issue where active.ident changes and nothing else-
names(new.IDs) <- levels(Obj)
Obj <- RenameIdents(Obj, new.IDs)

I cannot figure out why this isn't working.  If anyone can shed some light, I'd be very grateful.

**Comment by samuel-marsh** [comment]
Hi @DublinLeigh,

Not member of dev team but hopefully can be helpful.  So the functions appear to be working as expected but it seems you may be misunderstanding what they do.  

How you are running `RenameIdents` is 100% correct.  What that function does is rename the active.idents of the object.  But it does not change the meta.data.  The meta.data column you are referring to is result of `FindClusters` function and therefore will not be changed.

The reason that this fails: `Obj$celltype <- c("B cells", "NKT", "T cells") ` is because you are trying to replace an entire column of 100s to 1000s of rows (one for each cell) with a vector of length 3, none of which contain matched barcodes.

After renaming idents you can easily add new column to meta.data like so:
```
obj[["NAME_OF_NEW_COLUMN"]] <- Idents(obj)
```

Best,
Sam

**Comment by DublinLeigh** [comment]
@samuel-marsh Thank you for the information, but that doesn't tell me how to fix the problem.  Adding a new metadata column has the same problem as mentioned--that it doesn't match to the cluster IDs but to the cell IDs and is therefore not useful.  I still don't know how to get my cluster IDs saved "permanently" so that I can switch between idents for further processing.

**Comment by DublinLeigh** [comment]
@samuel-marsh Many thanks!
