### ISSUE TITLE
hard coded min.pct in TopDEGenesMixscape

### ISSUE THREAD

**Issue by zia1138** [satijalab/seurat#8253]
Thanks for all your hard work on seurat. We've been working with a perturb-seq data set and noticed a potential issue within `RunMixscape` 

It appears min.pct is hard coded to 0.1 in TopDEGenesMixscape. Can this parameter be exposed or changed to use the default for FindMarkers? 
https://github.com/satijalab/seurat/blob/41d19a8a55350bff444340d6ae7d7e03417d4173/R/mixscape.R#L1328

Happy to also submit a pull request with the parameter exposed, but wanted to get some feedback first. 
Thanks!

**Comment by longmanz** [comment]
Hi,
That is a good catch. We do it on purpose because we want to make sure the genes we selected to calculate Mixscape are highly expressed genes. The default min.pct in FindMarkers() is 0.01 so it means a lot of lowly expressed genes might be selected and they are not useful to distinguish perturbed and non-target cells. We would not recommend using a lower min.pct threshold than 0.1.  

That being said, it is a good suggestion of exposing the parameters in Mixscape (including min.pct and log-fold-change). We will be happy to work on it but it might take some time for it to make it to the public repo. Would it be easier for you to submit a PR (in which case you will have an "Exposed" version to work with from your end much sooner)? Any suggestion is appreciated.

**Comment by Gesmira** [comment]
Hi @zia1138,

Thanks for the suggestion!

Unfortunately, our bandwidth is limited so we won’t be able to include this in our roadmap at this time. We’ll circle back to this once our resources allow. In the meantime, please feel free to open a PR or continue the conversation in this thread. We cannot overstate how much we appreciate your input and we encourage you to keep sharing your ideas.
