### ISSUE TITLE
Error in Vlnplot of Seurat V5

### ISSUE THREAD

**Issue by ZivTQ** [satijalab/seurat#8259]
Hi
someone met this problems in seurat V5?
VlnPlot(WT, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
#error
Error: (converted from warning) Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.

It's so weird.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So there are two separate issues here.  First is that the reason it is throwing error instead of intended warning is due to your R settings (see here for solution: https://github.com/satijalab/seurat/issues/8140#issuecomment-1847821230).

The second is that it appears you have not yet normalized your data before plotting.  Running `NormalizeData` should solve this issue.

Best,
Sam

**Comment by ZivTQ** [comment]
> Hi,
> 
> Not member of dev team but hopefully can be helpful. So there are two separate issues here. First is that the reason it is throwing error instead of intended warning is due to your R settings (see here for solution: [#8140 (comment)](https://github.com/satijalab/seurat/issues/8140#issuecomment-1847821230)).
> 
> The second is that it appears you have not yet normalized your data before plotting. Running `NormalizeData` should solve this issue.
> 
> Best, Sam

Thank you very much!
It worked!!
And also I find that set layers in Vlnplot could also solve this problems!

Best
Tan

**Comment by 0russ4** [comment]
> 嗨，有人在修拉 V5 中遇到了这个问题？ VlnPlot（WT， 特征 = c（“nFeature_RNA”， “nCount_RNA”， “percent.mt”）， ncol = 3） #error 错误：（从警告转换而来）在“RNA”检测中默认搜索“数据”层没有结果;改用“计数”层。
> 
> 这太奇怪了。



> > Hi,
> > Not member of dev team but hopefully can be helpful. So there are two separate issues here. First is that the reason it is throwing error instead of intended warning is due to your R settings (see here for solution: [#8140 (comment)](https://github.com/satijalab/seurat/issues/8140#issuecomment-1847821230)).
> > The second is that it appears you have not yet normalized your data before plotting. Running `NormalizeData` should solve this issue.
> > Best, Sam
> 
> Thank you very much! It worked!! And also I find that set layers in Vlnplot could also solve this problems!
> 
> Best Tan

Could you please provide the code of the final solution? I also got an error when running the following code: 
preQC_P < -VlnPlot (P, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
ncol = 3,
group.by = "orig.ident",
pt.size = 0)
#error
Error: (converted from warning) Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.

**Comment by lrc6688** [comment]
May I ask how it was solved? I also encountered this problem when I tried to run with the same code and data as others

<img width="863" alt="56b3b130f2948f07dd7217209ae7080" src="https://github.com/user-attachments/assets/7d70ff00-cae3-4e68-ae08-c9891a24f2e2">

**Comment by cccclary** [comment]
I have the same problem, can you tell me the code? Thank you so much

**Comment by chiarasdn** [comment]
I am trying to analyse the scRNA seq data and I have a problem with the new version of Seurat.  It is giving the data a layer (counts) to the seurat object and is not “letting me” plot the data (error message) even if I see that they are stored as metadata in the Seurat object.
I thought might be due to the new version of Seurat but when I am trying to use version 3 it still gives me an error.
 
The error is with the part in red here, error being
 
Warning: Default search for "data" layer in "RNA" assay yielded no results; utilizing "counts" layer instead.
Error in Ops.data.frame(guide_loc, panel_loc) :
  ‘==’ only defined for equally-sized data frames
 
 
Here the code
 
# make Seurat object
so.NVAD28.data <- Read10X(data.dir =                          "/data/gpfs/projects/punim2346/chiara/projects/andrew_joseph_assembloid_singlecell_Oct_2024/output/cell_ranger/run_count_NVAD28/outs/raw_feature_bc_matrix")
# Initialize the Seurat object with the raw (non-normalized data)
so.NVAD28 <- CreateSeuratObject(counts =so.NVAD28.data, project = "so_NVA_2024", min.cells = 3, min.features = 200)
# Percentage of reads that map to the mitochondrial genome
so.NVAD28[["percent.mt"]] <- PercentageFeatureSet(so.NVAD28, pattern = "^MT-")
# Visualize QC metrics as a violin plot
VlnPlot(so.NVAD28, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
 
I noticed for the first time there was a layer in the Seurat object that I have never had before, when I explored the object:
An object of class Seurat
28912 features across 9578 samples within 1 assay
Active assay: RNA (28912 features, 0 variable features)
1 layer present: counts
 
The “strange” thing to me is that it works if I run ggplot separately it works but I need it in order to proceed with the next steps.

**Comment by Elizabeth-Zott** [comment]
can set the layer to fix the error:

`VlnPlot(WT, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, layer = "the name of your RNA assay layer")`

take an example, the following picture shows the data structure, and the code should be following then:

![Image](https://github.com/user-attachments/assets/dbd5b92d-78c3-4b60-b6cb-a8ab9cc21a28)

`VlnPlot(data_seurat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, layer = "counts.Gene Expression")`
