### ISSUE TITLE
How to perform reclustering subset of an integrating seurat object using seurat v5? 

### ISSUE THREAD

**Issue by xz289** [satijalab/seurat#8260]

**Comment by mhkowalski** [comment]
Hello, 

There are a couple of approaches you can take. You can use the `FindSubCluster` function (which would use the same snn graph you built on the integrated data), or you could re-run the entire integration workflow on your subsetted object. I often find the former works well for me and is the simplest approach, but both would be valid.

**Comment by sgolomb** [comment]
Hi @mhkowalski , I am trying to recluster cells that I have subsetted from an object that was previously integrated. I performed integration following the "Integrative Analysis Seuratv5" tutorial. I generated a UMAP using the CCA integration reduction and then applied SCTransform for downstream gene expression analyses.

I am now subsetting out groups of cells from this main object and want to recluster. I have done this in the past with older versions of Seurat where I had applied the integration workflow that creates an assay slot called "integrated". When I reclustered a subset of cells I set DefaultAssay(object) <- "integrated" and then proceeded with remaining clustering functions (RunPCA, FindNeighbors, FindClusters, RunUMAP).

With the integration workflow I followed for v5 there is no "integrated" assay slot so I am running: 
DefaultAssay(object) <- "SCT"
Then running the following code:
object <- RunPCA(object)
object <- FindNeighbors(object, reduction = "integrated.cca", dims = 1:10)
object <- FindClusters(object, resolution = 0.5, cluster.name = "reclus_cca_clusters", graph.name = "RNA_snn")
object <- RunUMAP(object, reduction = "integrated.cca", dims = 1:10, reduction.name = "reclus_umap.cca")
DimPlot(object, reduction = "reclus_umap.cca")

I do not feel completely confident if this is correct for a number of reasons:
1. I did not use either of your suggestions above to use FindSubCluster function (using original unsubsetted object?) or re-run integration workflow on subsetted cells... since I didn't do either of those, I'm wondering if the way I tried this is not correct.
2. My reclustered UMAP looks very similar to the patterning of cells as they are in the main unsubsetted UMAP - but maybe because they are already relatively similar/clustered even in the main UMAP with the parameters I used before?
3. I was prompted to indicate the graph.name in FindClusters, which I haven't seen before. I am concerned if it is using the same graph.name as the original main object, which is maybe why the cluster pattern looks so similar? I ran FindClusters after rerunning FindNeighbors, so I think it should use a re-generated graph based on the subsetted object?
4. Not sure if this is the appropriate way to visualize clusters with integration since I set the DefaultAssay to SCT (since "integrated" is not an option).

Thank you for any help, suggestions and advice! Appreciate it very much.
-Sam
