### ISSUE TITLE
scPred Error 

### ISSUE THREAD

**Issue by nitinmahajan20** [satijalab/seurat#8262]
I am having trouble running the scPred at one particular step. 

I posted the Query in the Biostar initially which you you can see here https://www.biostars.org/p/9583817/

I am still not able to run the code. I use Posit IDE R Studio on AWS pagemaker, but also when I tried to run the scPred on my local machine I did not run and give me the same error. 

Any help would be appreciated. 

Thank you.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So this doesn't seem to be an error with Seurat but rather with scPred.  My best guess is that it is because scPred has not been updated to navigate the new object structure of V5 objects (and they appear to have coded some functions with `:::` which isn't great).

One solution is to convert your V5 object to V3 style object (see here for info https://github.com/satijalab/seurat/issues/8220#issuecomment-1871874649).

The other option would be to post to scPred repo specifically.  However, I see that several others have already reported this issue, thus far with no response from those devs.  In fact the none of the code for scPred has been updated in 2.5 years and there does not appear to have been response from devs to any issues over that time too.  So it may be better to try another cell classification method.

Best,
Sam
