### ISSUE TITLE
GSEA not able to format with Seurat

### ISSUE THREAD

**Issue by lichenlady94** [satijalab/seurat#8300]
Hi everyone!

I'm trying to download GSE155698 and convert it into Seurat objects. I keep on getting that the barcode file is missing despite it being in the folders. I was wondering if there's a code that would help this or is it something with Seurat.

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  The issue is because `Read10X` does not work if the files have prefixes (as all GEO files do).  This comment on previous post explains issue and two potential solutions (`ReadMtx` in Seurat and `Read10X_GEO` in scCustomize) in 2nd half of the comment (https://github.com/satijalab/seurat/issues/5693#issuecomment-1060786186)
