### ISSUE TITLE
GetAssayData doesn't work for multiple layers in v5 assay

### ISSUE THREAD

**Issue by denvercal1234GitHub** [satijalab/seurat#8304]
Hi there, 

I have a Seurat object. When I set `DefaultAssay(seuratObj) <- "SCT"`, everything is fine. But, when I set `DefaultAssay(seuratObj) <- "RNA"`, I kept getting error below even if just viewing the seuratObj. 

```
> seuratObj
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay.
Backtrace:
  1. methods (local) `<stndrdGn>`(`<Seurat[,22723]>`)
 13. SeuratObject:::GetAssayData.Seurat(x)
 15. SeuratObject:::GetAssayData.StdAssay(object = object[[assay]], layer = layer)
```

```
> seuratObj
# A Seurat-tibble abstraction: 22,723 × 56
# Features=16661 | Cells=22723 | Active assay=SCT | Assays=RNA, SCT
```

Because I `SCTransform` each sample individually, then merge, then use `SelectIntegrationFeatures` to set Variable Features for the merged object before clustering. My object has: 

<img width="192" alt="Screenshot 2024-01-11 at 09 35 29" src="https://github.com/satijalab/seurat/assets/62179082/e1e27b3d-5c47-45eb-8e4c-35edbd1cc44f">

<img width="212" alt="Screenshot 2024-01-11 at 09 36 40" src="https://github.com/satijalab/seurat/assets/62179082/c242b95d-0f75-43cc-9e42-c1f9ed7ba96c">

```
> DietSeurat(object = seuratObj, layers = "counts", assays="RNA")
Error in `DietSeurat()`:
! The default assay is slated to be removed, please change the default assay
Backtrace:
 1. Seurat::DietSeurat(...)
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
```

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So this is expected performance of the function(s).  First, `GetAssayData` has been superseded by `LayerData` so suggest moving to that when using V5 structure moving forward.

Second, as pointed out here by dev team in order to pull data from all applicable layers (e.g. raw counts, normalized data, etc) you first need to run `JoinLayers` (https://github.com/satijalab/seurat/issues/7985#issuecomment-1806483174).  Alternatively, you could extract all relevant layer names from object and then use `lapply` to pull one matrix for each layer into a list.

Best,
Sam

**Comment by HappinessEricst** [comment]
Hi please i encountered this error:  "Error in GetAssay.Seurat(object = object, assay = assay) :
RNA is not an assay present in the given object. Available assays are:"



Here is the code:

# SCTransform  
for (i in 1:length(p3.moe.seu.list)) {
  p3.moe.seu.list[[i]] <- SCTransform(p3.moe.seu.list[[i]], method = "glmGamPoi", 
                                   vars.to.regress = "percent.mt")
}


please can anyone help out

**Comment by SaleenaYounus** [comment]
@denvercal1234GitHub 
##First integrate the object, then set the assay, then join the layers then apply function, it work for me
DefaultAssay(Objectname <- "integrated"
DefaultAssay(Objectnamet) <- "RNA"
##Join layers
New<- JoinLayers(Objectnamet, overwrite = TRUE)
data.input <- GetAssayData(New, assay = "RNA", slot = "data")

**Comment by aircondition426** [comment]
Hi!

**Comment by aircondition426** [comment]
Hi! With the update of V5 assay, using the code below, the results of two alternative methods(testdata and data.input) seemingly different. How and why does it occurs? Thanks!                                                                                                                                                                 
>testdata <- LayerData(objectname, layer ="data")   

> New<- JoinLayers(Objectnamet, overwrite = TRUE)
data.input <- GetAssayData(New, assay = "RNA", slot =  #"data")

**Comment by DrSawal** [comment]
Warning message:
Layer ‘data’ is empty 

How should I remove this error?

**Comment by DrSawal** [comment]
how? can you please suggest the commands for these?
________________________________
From: Samuel Marsh ***@***.***>
Sent: Thursday, January 2, 2025 12:26 PM
To: satijalab/seurat ***@***.***>
Cc: Humaira Sawal ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [satijalab/seurat] GetAssayData doesn't work for multiple layers in v5 assay (Issue #8304)

@ DrSawal You need to run NormalizeData or SCTransform. Best, Sam — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <satijalab/seurat/issues/8304/2568118756@ github. com>


@DrSawal<https://urldefense.com/v3/__https://github.com/DrSawal__;!!GobTDDpD7A!JSbxMfK-yP97aze96VvsgUK3X9EmX4LtQ8eMI771rKTl74I7MBJGdBWr0JnIPKU2cDMEzRSpKzhNSeSteohdHDuy6A$>
You need to run NormalizeData or SCTransform.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi @DrSawal,

Those are the commands.  You can view them in package manual by typing `?` before command name and running that in RStudio.  Or by searching for them in package pdf manual on CRAN.  Or Satija lab Seurat website.

Best,
Sam

**Comment by DrSawal** [comment]
If I send you my R History, will you be able to help me out? because I am getting few errors after putting commands.

Best Regards,
Humaira
________________________________
From: Samuel Marsh ***@***.***>
Sent: Thursday, January 2, 2025 3:59 PM
To: satijalab/seurat ***@***.***>
Cc: Humaira Sawal ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [satijalab/seurat] GetAssayData doesn't work for multiple layers in v5 assay (Issue #8304)

Hi @DrSawal, Those are the commands. You can view them in package manual by typing ? before command name and running that in RStudio. Or by searching for them in package pdf manual on CRAN. Or Satija lab Seurat website. Best, Sam — Reply


Hi @DrSawal<https://urldefense.com/v3/__https://github.com/DrSawal__;!!GobTDDpD7A!LsPVV03RpeH4h2UCgqln_0vmuvuKm22Hxubnnq1olyF26tQPQbV-a4PRuZAPXaZ_1keUomWkbBXWHN-3bMPaRWXM8w$>,

Those are the commands. You can view them in package manual by typing ? before command name and running that in RStudio. Or by searching for them in package pdf manual on CRAN. Or Satija lab Seurat website.

Best,
Sam

**Comment by samuel-marsh** [comment]
Sure but I suggest starting a new issue rather than continuing on this thread.

Best,
Sam

**Comment by DrSawal** [comment]
can you please give me ur email address
________________________________
From: Samuel Marsh ***@***.***>
Sent: Friday, January 3, 2025 10:57 AM
To: satijalab/seurat ***@***.***>
Cc: Humaira Sawal ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [satijalab/seurat] GetAssayData doesn't work for multiple layers in v5 assay (Issue #8304)

Sure but I suggest starting a new issue rather than continuing on this thread. Best, Sam — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <satijalab/seurat/issues/8304/2569456522@ github. com>


Sure but I suggest starting a new issue rather than continuing on this thread.

Best,
Sam
