### ISSUE TITLE
calculating adjusted p-values from FindMarkers output

### ISSUE THREAD

**Issue by tanonymush** [satijalab/seurat#8358]
Thank you for developing an amazing package. 

I'm conducting a differential gene expression analysis within a cluster of interest across different treatment conditions and Id like to assess whether a list of genes are differentially expressed or not. Initially, I utilized Seurat's FindMarkers function which provides bonferroni corrected p values but I'm interested in exploring alternative  p-value correction methods.

To this end, I extracted the expression levels of my target genes from two treatment groups using FetchData() and then calculated the p-values using the wilcox.test() function in base R. For comparison purposes I initially applied the Bonferroni correction the output p-values, expecting them to align with the results from FindMarkers. Surprisingly, I observed discrepancies in the adjusted p-values between my manual method and those obtained from FindMarkers.

Firstly, I would like to ask if it is valid to conduct p-value analysis by manually extracting gene expression data with FetchData() function and then applying statistical tests like wilcox.test() in base R? Regarding the discrepancies in adjusted p values, could there be specific aspects of the FindMarkers() in calculating adjusted p-values that I might be overlooking in my manual analysis?

**Comment by longmanz** [comment]
Hi,
In Seurat FindMarkers(), the Bonferroni correction is conducted based on the total number of genes in the dataset (the row number of the RNA count matrix), instead of the number of genes that go into the testing. We do the multiple testing in a more conserved way because in FindMarkers() there are some pre-filtering steps (log-fold-change, min.pct) that will reduce the number of genes go into the final testing. However, such pre-filtering steps should also be taken into account when doing multiple testing. 

If you want to do multiple testing correction using other methods (e.g., BH), you can do it directly for your `p_val` column after FindMarkers(). Of course this is not recommended compared to the built-in Bonferroni correction, since you will have a higher false positive rate potentially.

**Comment by apal6** [comment]
Hi,

I wonder why my p_val_adj is 1 for all the genes? What do you think could be going wrong in my analysis?

Thank you
