### ISSUE TITLE
no scale.data slot in seuratobject

### ISSUE THREAD

**Issue by sghoshuc** [satijalab/seurat#8378]
I was trying to create seuratobject by using ReadMtx function followed by CreateSeuratObject. 
Seuratobjects were created successfully however, when I am using Seurat_5.0.1 it is missing scale.data slot under assay.

It's retaining when I am using Seurat_4.0.3
Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Can you please post the full code that you are running that results in the error?

Best,
Sam

**Comment by sghoshuc** [comment]
Hi Sam, thanks for your reply.  I read multiple files  and converted  to seuratobjects using the following codes.  
for(x in dirs){
  name <- gsub('_filtered_feature_bc_matrix','', x)
  
  cts <- ReadMtx(mtx = paste0('sct.files/',x,"/matrix.mtx.gz"),
                 features = paste0('sct.files/',x,"/features.tsv.gz"),
                 cells = paste0('sct.files/',x,"/barcodes.tsv.gz"))
  
  # create seurat objects
  assign(name, CreateSeuratObject(counts = cts))
  
  
}

With Seurat V4 seuratobject showing a slot named scale.data under assay. However, when I switched to Seurat V5 that slot was missing. I am attaching the picture from Rstudio for your convenience.   
   
![image](https://github.com/satijalab/seurat/assets/39599004/6a6d2a7a-fafa-4145-bcb5-2df6ab5c7d8b)
[seurat.pptx](https://github.com/satijalab/seurat/files/14060709/seurat.pptx)


![image](https://github.com/satijalab/seurat/assets/39599004/ce40bc8a-eb27-489e-85ae-149ec218ae71)

**Comment by longmanz** [comment]
Hi, 
After you generate a Seurat object, you will need to run NormalizeDate(), FindVariableFeatures() , and ScaleData() for the object to get the actual scale.data. 

Or if you are asking why "scale.data" no longer exists in `IUGR_R1@assays$RNA@`, it is because in V5 we no longer store data in 'slot' but in 'layer'. So for each layer, you can have counts, data, and scale.data. You can check it using `IUGR_R1@assays$RNA@layers$` to see if you have a 'scale.data' or not. Make sure you run `ScaleData()` before that.
