### ISSUE TITLE
Switching between two versions

### ISSUE THREAD

**Issue by sghoshuc** [satijalab/seurat#8379]
Hi Satija lab,
I am currently running into issues when I switch to Seurat V5. Is their a way to install botha Seurat V4.3/5 and switch between them?
Thanks

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  There is not a way to have two versions simultaneously installed in the same R session.  You can always switched back and forth after restarting an R session.

Is your issue with the V4 vs. V5 package or with Assay vs Assay5 structure?  Because you can switch between assay and assay5 structure while just having V5+ installed?

Best,
Sam

**Comment by longmanz** [comment]
Hi,
Thanks @samuel-marsh for helping out! 
As Samuel has suggested, unfortunately it is not possible to install both v4 and v5 at the same time. If you want to keep using v4 object in V5, you can use `options(Seurat.object.assay.version = 'v3') ` before running any Seurat codes, so that all Seurat objects in your environment is in v4 (v3 technically, since Seurat v4 is using v3 assay).
