### ISSUE TITLE
Load10X_Spatial with multimodal data

### ISSUE THREAD

**Issue by jchariker** [satijalab/seurat#8454]
Hi, 
I have Visium slides with gene expression and antibody capture. When using Load10X_Spatial, I get the following error. 

**Genome matrix has multiple modalities, returning a list of matrices for this genome
Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features,  : 
  No cell names (colnames) names present in the input matrix**

Is this function designed to take multimodal data?  I'm using Seurat_4.0.2 with R version 4.0.3. 
The function works beautifully on SpaceRanger output with only gene expression.

Thanks for your help.

**Comment by zskylarli** [comment]
Hi - not super sure since I can't view your data, but since Load10X_Spatial reads the counts matrices for the paths of all h5 files provided and loads them as an assay, I would imagine Load10X_Spatial should work as long as your antibody counts matrix has the proper colnames/cell names. Can you extract and recreate the matrix to have the right structure based on your gene expression data?

**Comment by jchariker** [comment]
Hi Zhuoyan,


After I upgraded to Seurat_5.0.1, Load10X_Spatial worked beautifully. I see the gene expression and protein assays in the Seurat object.

Thanks for your help!



Julia
