### ISSUE TITLE
Error during Seurat installation in RStudio Server docker container 

### ISSUE THREAD

**Issue by will-gt** [satijalab/seurat#8496]
**Platform: Ubuntu 20.04 (already installed "libglpk-dev libgmp-dev libxml2-dev")**

**RStudio Server: rocker/rstudio docker container**

**Problems:** 
**I have been using RStudio Server installed from rocker/rstudio docker image.** 

**Recently, I tried to install the Seurat package on my RStudio Server docker container. I got the following error messages when I installed Seurat package and library it.**

> 
>
> Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
>   libglpk.so.40: cannot open shared object file: No such file or directory
> 
> 

**For this error, I have installed "libglpk-dev libgmp-dev libxml2-dev" package on my Ubuntu, but the error still occurs when I library Seurat.**

**I reinstalled RStudio Server container many times after I installed "libglpk-dev libgmp-dev libxml2-dev" packages, but the error still occurs.**

**Could you please tell me how to fix it?**

**Comment by szhorvat** [comment]
> libglpk.so.40: cannot open shared object file: No such file or directory

This error indicates that a library that was present and accessible when you compiled igraph is no longer present or no longer accessible. There can be several reasons:

 - You compiled igraph with the system version of GLPK but then later uninstalled this.
 - You compiled igraph with a different installation of GLPK, and this installation was removed or became inaccessible in the meantime. This commonly happens when people have a conda environment active while compiling igraph. Always deactivate conda environments first.

I suggest you re-install igraph, making sure to use the system version of GLPK, and making sure that conda doesn't interfere.

Troubleshooting instructions are at https://r.igraph.org/articles/installation-troubleshooting.html
