### ISSUE TITLE
Inflated p-value for 'LR' test using latent.vars in FindMarkers.

### ISSUE THREAD

**Issue by jeji0209** [satijalab/seurat#8498]
Hello! 
I am currently trying to find DEGs between two conditions. My data is an integration of multiple publicly available datasets, so I thought it would be appropriate to use the 'LR' test, with 'data' as latent.vars.

This is the code that I used:
`lr_degs = FindMarkers(seu.integrated.ident,
              ident.1 = 'Cond1',
              ident.2 = 'Cond2,
              test.use = "LR",
              #latent.vars = "data",
              logfc.threshold = -Inf, 
              min.pct = -Inf, 
              min.diff.pct = -Inf)`

When I checked the distribution of log2FC and -log10(adjusted_p), there was a group of genes that had very high -log10(adjusted_p), despite a very low absolute log2FC. Also, the overall pattern of the distribution between log2FC and -log10(adjusted_p) did not seem linear. 

This is the volcano plot:
![volcanoplot_pvallr_colorlr_20240219](https://github.com/satijalab/seurat/assets/90094328/ea3763b0-ca18-42ac-ba53-d578fb8ed6b4)

However, when I did the same comparison using Wilcoxon test (therefore, not regressing out 'data' as a covariate), the distribution came out more ideally. 
Code:
`wilcos_degs = FindMarkers(seu.integrated.ident,
              ident.1 = 'Cond1',
              ident.2 = 'Cond2',
              test.use = "wilcox",
              logfc.threshold = -Inf, 
              min.pct = -Inf, 
              min.diff.pct = -Inf)`

Volcano plot:
![volcanoplot_pvalwilcox_colorwilcox_20240219](https://github.com/satijalab/seurat/assets/90094328/81617407-2e96-4262-8abb-5609b3c9c63f)

What is confusing me is that the number of significant genes using Wilcoxon test is much higher than LR method, and therefore most of the genes that is significant for LR method is also significant using Wilcoxon test. Is there any way to explain this difference in significance distribution?

Thank you in advance.

**Comment by igrabski** [comment]
Hi Jungeun, thanks for your question. First, the log-fold change computations are not dependent on the test type, and do not necessarily reflect internal computations of the DE test. For example, in your first DE approach, you used data as a latent variable to the LR test, but this does not get accounted for in log fold-change. Instead, log fold-change is a simple comparison of expression between two conditions. So, the lack of direct correlation between the log fold-change and the p-value is not necessarily unreasonable. 

Similarly, the Wilcoxon test and the LR test are also fairly different statistical tests, especially because you are also using data as a latent variable for the LR test, but this information is not used for Wilcoxon. So, it is again not unexpected to have different results between the two. It's possible that the Wilcoxon test is giving a lot more false positives, or conversely it's possible that the LR test with data as a latent variable is being conservative -- that decision will depend on your specific experimental design and which set of results seems more reasonable to you.
