### ISSUE TITLE
AverageExpression and expm1 

### ISSUE THREAD

**Issue by rrotkopf** [satijalab/seurat#8532]
Hello,

I have noticed that when calculating average values per cluster (on SCT data), I get values that are much higher than the values in the violin plot. I realize that this is because the expm1 function (within AverageExpression) un-logs the values before calculating the average.
What is the advantage of presenting the un-logged means? Is it wrong to present a mean of the logged values, calculated by fetching the relevant genes from the object and calculating a regular arithmetic mean?

Thanks!

Similar issue here:
(#2381)

**Comment by mhkowalski** [comment]
Hi, 

Thanks for your question. The values will be different from those on the violin plot because the data plotted in the ```VlnPlot``` is logged, and AverageExpression returns the average exponentiated data, as you mention. You could use ```return.seurat=TRUE``` and extract ```data``` to get the log of the average exponentiated data.

You can think of averaging the exponentiated data as averaging the counts for that gene but adjusting for sequencing depth within each cell. We think this value is more representative of the value you would obtain from bulk RNA-seq. The arithmetic mean of the logged data is equivalent to the geometric mean of the counts, which would reduce the effect of outlier cells. This is also a valid metric but is not currently our default.
