### ISSUE TITLE
RunUMAP: return nearest neighbor indexes 

### ISSUE THREAD

**Issue by tirk999** [satijalab/seurat#8533]
Hi everyone,

I have a question about the RunUMAP function. Is there a way to obtain the computed nearest neighbor index?
Basically, I am interested in having a "measure of distance" of my cells in the high dimensional space, so I think this is equivalent to obtain an intermediate output of the RunUMAP function. Do you know how I could achieve this?

Thank you a lot.

**Comment by Gesmira** [comment]
Hi @tirk999, there are two decision points that will impact the answer to this question: 

- First, to the `RunUMAP` function, you can directly provide a pre-computed graph (built using `FindNeighbors` and provided to the `graph` parameter of `RunUMAP`). Otherwise, the neighbor graph will be computed as the function runs. In the first way, that output graph from `FindNeighbors` would be what you are looking for, but in the second way - we don't store this graph. 
- Second, there are two supported implementations of UMAP in Seurat: the default is the R-native implementation "uwot" and the python implementation "umap-learn". If you were providing a Seurat object and having the function compute the neighbor graph for you, I would recommend exploring these internal functions depending on your implementation to try to extract the neighbor graph, but we don't provide a way to do that.
