### ISSUE TITLE
DEGs are dominated by one sample from a group

### ISSUE THREAD

**Issue by ilcink** [satijalab/seurat#8556]
Hello!
There is a dataset consisting of 4 conditions, where each condition is represented by multiple samples. The dataset was integrated using the Reciprocal PCA approach.

DEG search

`Idents(obj)<-"condition"
obj.markers <- FindAllMarkers(obj, logfc.threshold = 0.25, assay="RNA")`

results in a set of genes characteristic for each of these 4 conditions.
The dot plot between conditions looks fine
`DotPlot(object = obj, features = c("XXX", "YYY", etc.))`
but when plotting the same genes by samples

`Idents(obj)<-"sample"
DotPlot(object = obj, features = c("XXX", "YYY", etc.))`

it turns out that these differences are rather dominated by one-two samples from a condition group (please see example attached).
<img width="925" alt="img" src="https://github.com/satijalab/seurat/assets/67465927/dda9602d-bce0-4bf2-ad6e-58c6714e1b65">

Is there a way to find genes which distinguish one condition from the others, when these markers would be consistently upregulated in all/most samples within that condition group vs samples from all other conditions?
Thanks

**Comment by igrabski** [comment]
Hi, if you have multiple samples per condition, we recommend using `DESeq2` for finding differentially expressed genes in order to account for variability across samples and mitigate the possibility of one sample dominating the DE results. You can find a tutorial on this [here](https://satijalab.org/seurat/articles/de_vignette).
