### ISSUE TITLE
Integration with SCTransform(v2) in Seurat v5--IntegrateLayers and PrepSCTFindMarkers

### ISSUE THREAD

**Issue by rln0005** [satijalab/seurat#8582]
I am integrating 4 melanoma cell lines and using SCTransform (vst=v2) in Seurat v5.0.1. 

1. Does `IntegrateLayers` replace the following: `SelectIntegegrationFeatures`, `PrepSCTIntegration`, `FindIntegrationAnchors`, AND `IntegrateData`? 
2. When identifying cluster markers (after integration) using `FindAllMarkers`, should I run `PrepSCTFindMarkers` first? 

I have read through all the vignettes, but this part is unclear with the new updates. Thank you in advance.

**Comment by igrabski** [comment]
Hi Rebecca, 

1. You are correct, you can just use `IntegrateLayers` (with specifying `normalization.method = "SCT"`) instead of the previous set of commands. You can see an example of this in the last section of this [vignette](https://satijalab.org/seurat/articles/integration_introduction.html#perform-integration-with-sctransform-normalized-datasets). 

2. Yes, you should run `PrepSCTFindMarkers` prior to `FindAllMarkers`.
