### ISSUE TITLE
How to set nfeatures in IntegrateLayers?

### ISSUE THREAD

**Issue by 809825706** [satijalab/seurat#8590]
**before v5, we use:**

```R
integ_features <- SelectIntegrationFeatures(object.list = split_seurat, nfeatures = 5000) 
split_seurat <- PrepSCTIntegration(object.list = split_seurat, anchor.features = integ_features)
integ_anchors <- FindIntegrationAnchors(object.list = split_seurat, normalization.method = "SCT", anchor.features = integ_features)
seurat_integrated <- IntegrateData(anchorset = integ_anchors, normalization.method = "SCT")
```

we can adjust in `SelectIntegrationFeatures`, while merged_seurat is split to layers in v5. is the function `SelectIntegrationFeatures` work for split_seurat which is split to layers？

**Comment by igrabski** [comment]
Hi, in v5, we now use `IntegrateLayers` as a single step for running integration, which includes these previous steps under the hood. You can see an example of this [here](https://satijalab.org/seurat/articles/integration_introduction.html#perform-integration-with-sctransform-normalized-datasets). You can pass any list of features you want into `IntegrateLayers` using the `features` argument if you don't want the default feature selection process. This includes the output of `SelectIntegrationFeatures` with `nfeatures` set however you like, but you will need a list of separate objects rather than a typical v5 object split into layers.
