### ISSUE TITLE
Getting residual variance after regression

### ISSUE THREAD

**Issue by hwangjw26** [satijalab/seurat#8613]
Hello, I appreciate your efforts with this library. I'm seeking a clear understanding of how the residual variance and scale.data slots are used after SCT. This question is related to [issue #5916](https://github.com/satijalab/seurat/issues/5916), which is now closed.

From what I understand, within the SCT slot, SCTModel.list$counts@feature.attributes displays the values obtained after the initial negative binomial (NB) regression. If vars.to.regress is set, a second linear regression is conducted, and the results are stored in the scale.data slot.

If this is correct, setting additional covariates in vars.to.regress would not alter the SCT slot's residual mean and residual variance. Furthermore, since the scale.data slot only contains the residual mean value (post-second regression), I presume there is no direct method to extract the residual variance after accounting for extra covariates.

Therefore, I would like to know how to obtain the residual variance values after performing regression with additional covariates. Additionally, does the highly variable gene (HVG) function only utilize the residual variance from the first NB regression? If so, is this due to centering, and does it mean that HVG does not take into account the extra covariate?

Thank you once again.

**Comment by longmanz** [comment]
Hi,
Re 1). It is difficult to obtain the residual variance based on the current function structure. But you can obtain that by yourself if you run linear regression between your `obj@assays$SCT@scale.data` and your covariates directly. 
Re 2). Yes, HVG is determined by resVar in the first NB regression.
Re 3). While SCTransform does not take into account for the extra covariates, you can use the variance you obtain from step 1) to generate your own HVG list. Note that you will need to set `return.only.var.genes = F` when running SCTransform(), otherwise the function will only return the top 3000 HVG in the scale.data slot.
