### ISSUE TITLE
FindMarkers directly without PCA reduction, Find clusters and UMAP reduction

### ISSUE THREAD

**Issue by Dkaaaaa** [satijalab/seurat#8617]
Dear Fellows,

I recently ran into a question about FindMarkers : I was given a single-cell data along with the corresponding cell type annotation file, and then I wanted to find out the marker genes between the different cell types, and I wondered if I could just do QC, Normalizing the data, Identification of highly variable features, and Scaling the data of my data, then directly run the FindMarkers(). Does this have any effect on the result? 

What'more, when I run FindAllMarkers , I find that the number of genes obtained by FindAllMarkers is less than that of FindMarkers , after consulting the source code, I find that FindAllMarkers is calling FindMarkers in a loop, and then filtering out the genes with a p_val greater than 0.7 in the final result, but the number of genes obtained by the two functions is still not the same even after filtering out these genes from my data, may I ask what is the reason for this difference?

Very much looking forward to hearing back from you, it will help me immensely in my studies, best wishes!

Dka

**Comment by samuel-marsh** [comment]
Hi Dka,

Yes you as long as you have meta.data that confers the identities you want to compare then you can run DE.  However, be warned that pvalues for DE between cell clusters are not entirely valid due to methods used to arrive at those clusters (double dipping).  Also you don't need to run ScaleData in order to run DE as those values are not used for DE.

In terms of the genes returned it all depends on the values you set for parameters.  If you set `return.thresh` in FindAllMarkers you can replicate results exactly.

```
test1 <- FindAllMarkers(object = pbmc, logfc.threshold = 0.1, return.thresh = Inf)
test1_sub <- test1 %>% 
     filter(cluster == 0)
nrow(test1_sub)
[1] 8546

test2 <- FindMarkers(pbmc, ident.1 = 0, logfc.threshold = 0.1)
nrow(test2)
[1] 8546 
```

Best,
Sam

**Comment by Dkaaaaa** [comment]
Hi Sam,

Thank you very much for your reply, but I have some questions in response to your reply.

Data used in the DE analysis is data after normalization, is that right?

In my understanding, either after running Findclusters() or without running Findclusters() and clustering the cells based on the metadata, since DE is performed in findmarkers based on the already clustered cells , the` double dipping` you mentioned in the DE analysis occurs. I am not sure if my understanding is correct. If my understanding is correct, I would like to ask if there is any other way to improve this, I noticed that [#4256 ](https://github.com/satijalab/seurat/issues/4256) was also mentioned the `double dipping` but you did not respond further. 

Very much looking forward to hearing back from you, it will help me immensely in my studies, best wishes!

Dka

**Comment by samuel-marsh** [comment]
Hi Dka,

Yes any cluster vs. cluster DE based on identifying features, pca on those features, SNN, clustering etc will suffer from double dipping (in addition to general cell level DE inflating p values that does not take into account sample to sample variability).

In terms of improving there are some approaches out there to try and avoid this in DE.  However, if you are just looking to identify marker genes the approach is fine because between the log2FC and pct.1 vs. pct.2 you can identify genes that are either selectively enriched or selectively expressed (or mix) between clusters.  It is just that the p-values from that analysis should not be used as threshold or cutoff for downstream analyses because they suffer from issue.

As detailed in `FindAllMarkers` documentation `Slot to pull data from; note that if test.use is "negbinom", "poisson", or "DESeq2", slot will be set to "counts"`.  So yes you are correct which data is used depends on the DE test in question.

Best,
Sam

**Comment by Dkaaaaa** [comment]
> Hi Dka,
> 
> Yes any cluster vs. cluster DE based on identifying features, pca on those features, SNN, clustering etc will suffer from double dipping (in addition to general cell level DE inflating p values that does not take into account sample to sample variability).
> 
> In terms of improving there are some approaches out there to try and avoid this in DE. However, if you are just looking to identify marker genes the approach is fine because between the log2FC and pct.1 vs. pct.2 you can identify genes that are either selectively enriched or selectively expressed (or mix) between clusters. It is just that the p-values from that analysis should not be used as threshold or cutoff for downstream analyses because they suffer from issue.
> 
> As detailed in `FindAllMarkers` documentation `Slot to pull data from; note that if test.use is "negbinom", "poisson", or "DESeq2", slot will be set to "counts"`. So yes you are correct which data is used depends on the DE test in question.
> 
> Best, Sam

Hi Sam,

Your reply helped me a lot, have a happy and healthy day!

Dka
