### ISSUE TITLE
Inquiry about Integration

### ISSUE THREAD

**Issue by xieaq** [satijalab/seurat#8644]
Hi, Seurat is really helpful! But when doing the batch correct, I do meet some problems.

I notice that,  [IntegrateLayers](https://satijalab.org/seurat/reference/integratelayers) can only get embedding results saved in ``` "integrated.dr" ```, and [RunUMAP](https://satijalab.org/seurat/reference/runumap) also works on that embedding data to see if batch correction works well.

The results in ```SCT@counts``` from [PrepSCTFindMarkers](https://satijalab.org/seurat/reference/prepsctfindmarkers) is no difference whether we do integration before.

If we don't implement [IntegrateLayers](https://satijalab.org/seurat/reference/integratelayers), just perform [RunPCA](https://satijalab.org/seurat/reference/runpca) and [RunUMAP](https://satijalab.org/seurat/reference/runumap) directly on the ``` Seurat Object ``` after [PrepSCTFindMarkers](https://satijalab.org/seurat/reference/prepsctfindmarkers), the Dimplot shows that it can't make different methods mixed well. 

I'm wondering how to get batch corrected integer counts when integrating data rather than embedding data in Seurat?

Thanks a lot!

**Comment by rsatija** [comment]
Thanks for your question - we do not return batch-corrected integer counts. Our goal in performing integration is to identify shared patterns of variation across datasets, so that cells in a matched biological state can be grouped together - and the latent space which achieves this is stored in integrated.dr as you pointed out.
