### ISSUE TITLE
Error in Read10X

### ISSUE THREAD

**Issue by ShashTrip1** [satijalab/seurat#8661]
I am rerunning some code from a couple months ago (and did not get an error then) however now when I run read10X it is throwing the following error: 

Warning: Stopped early on line 6. Expected 2 fields but found 1. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<O<b2>-D<b7>O<d3>8H<85><ec><af>N<df>r>>Error in fixupDN.if.valid(value, x@Dim) : 
  length of Dimnames[[2]] (2) is not equal to Dim[2] (9069)

and for the second sample: 

Error in fixupDN.if.valid(value, x@Dim) : 
  length of Dimnames[[2]] (2) is not equal to Dim[2] (8110)
In addition: Warning message:
In data.table::fread(barcode.loc, header = FALSE) : Stopped early on line 4. Expected 2 fields but found 3. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<�,(��*T��d,a���Q�Όh��X��r	/1��cC�;|�Vّ���B�O�z���"<E�H�ؽ��렊�b��.ѬW���>>

**Comment by Gesmira** [comment]
Hi, 
I have not previously seen this error. Do you have a file that works normally and do you know if there is any difference between how these were made? Otherwise, can you provide a small reproducible example file?

**Comment by Gesmira** [comment]
Closing now due to lack of response. Feel free to reopen if the issue persists.

**Comment by Gesmira** [comment]
Just wanted to share I ran into this issue myself and it turned out that the dataset I was using which was generated by the newest version of cellranger-arc had a strangely formatted features.tsv.gz file where there was a blank line in between every feature line. Removing the blank lines allowed Read10X to work. (Note that `read.delim` handles the blank lines fine, but `fread` which is used by default within `Read10X` if you have `data.table` installed leaves them in). 

This is slightly different than the error the original commenter was getting because I got a warning that looked like: 

`Expected 6 fields but found 0` due to the blank lines.

But, I wanted to share in case anyone else comes here with the same issue.
