### ISSUE TITLE
how to interprete the result of RunCCA 

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#868]
CCA is a multivariate constrained ordination technique that extracts major gradients among combinations of explanatory variables in a dataset. but I can not get that from the picture

![image](https://user-images.githubusercontent.com/25199946/47091228-03a60600-d257-11e8-86da-8531c830af81.png)
also as PCA, the hetamap is how to depict, thanks a lot
![image](https://user-images.githubusercontent.com/25199946/47091276-2506f200-d257-11e8-9839-ccb035bfd243.png)

**Comment by satijalab** [comment]
Dear 2236529177,

Thanks so much for your feedback and interest in the software package! We are an academic lab as opposed to a commercial software company, but we are happy to spend time helping users with issues as they arise on this forum. We are also particularly grateful for community members not affiliated with the lab, who assist with user queries as well.

We recognize that you are getting started with the software and have many questions. Myself, those in my lab, and others in the community have been doing our best to answer them, but I think you are asking questions at a faster rate that we can process them! :). I worry that this is not the best mechanism for us to support you. In addition, this GitHub forum has become dominated by issues from a single user, and I believe that this could have a negative impact for other users.

Going forward, I would like to ask you to consider these challenges for us when posting GitHub issues. In particular, it is sometimes difficult for us to answer queries asking about interpretation of individual functions or outputs. We also cannot provide personalized recommendations for individual parameter choices. Lastly, we encourage you to please read the documentation in our website carefully, many of your questions have been addressed clearly in existing resources. I will go through your existing issues and point you to places in the documentation that can address them.

We are always happy to see bug reports and errors that arise. For example, you recently pointed out that our documentation contained an $dr instead of an @dr, which we appreciate, and will fix in a later release.

I do hope you will consider this going forward. 

best,
Rahul

**Comment by leonfodoulian** [comment]
Hi @2236529177,

To briefly answer some of your questions.

> You can see that in you function TSNEPlot, there is no parameter of group.by, though I can guess that

Although `Seurat::TSNEPlot()` does not explicitly state that it can process a `group.by` argument, the [function documentation](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/TSNEPlot) clearly states that additional parameters to `Seurat::DimPlot()` can be passed to the function. This is indeed the case because `Seurat::TSNEPlot()` actually calls `Seurat::DimPlot()`, and both functions have the `...` (i.e. ellipsis) argument, meaning that additional parameters to the internal function (i.e. `Seurat::DimPlot()`) can be inputted to the external function (i.e. `Seurat::TSNEPlot()`). More info about ellipsis [here](https://stackoverflow.com/questions/5890576/usage-of-three-dots-or-dot-dot-dot-in-functions) and [here](https://www.r-bloggers.com/r-three-dots-ellipsis/).

https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/plotting.R#L2776-L2795

I see that you are struggling with this parameter, but again, as mentioned in the [`Seurat::DimPlot()` documentation](https://www.rdocumentation.org/packages/Seurat/versions/2.3.4/topics/DimPlot), it's simply a convenient way to colour your cells according to any variable of interest stored in your Seurat object. 

> also, there is really not clear description about the PCA CCA of heatmap. It just tells it can do, but not tell the meaning of that, for example, you said In particular PCHeatmap allows for easy exploration of the primary sources of heterogeneity in a dataset(https://satijalab.org/seurat/pbmc3k_tutorial.html),nut there is really no clear as JackStrawPlot and PCElbowPlot to tell you how many pcs to select, if you just see the PCHeatmap, I guess most people can not decide how many to choose.

As you mention, Seurat has multiple functions that allow you to explore the results of it's `Seurat::RunPCA()` output, each being informative in its own way. Even if `Seurat::PCElbowPlot()` can help you choose which PCs account for the highest variability, and how that variability changes with increasing PCs, it won't actually tell you anything about what is driving these PCs. And if you'd like to remove technical variability from the dataset when clustering, you would be interest in exploring that using `Seurat::PCHeatmap()` for instance.

I hope I answered some of your questions. 

Best,
Leon

**Comment by 2236529177** [comment]
> And if you'd like to remove technical variability from the dataset when clustering, you would be interest in exploring that using `Seurat::PCHeatmap()` for instance.

Dear Leon, 
I am always grateful that there are so many people in the world who help others like you and make the world better.
I am not clear about the heatmap of pca,cca, can you take an example to exlpain that, thanks a lot. I am here give you two links. especially you know there is one colorbar there(count 0-1500, I guess it means cell numbers). but still do not know how to interprete that.
{

![image](https://user-images.githubusercontent.com/25199946/47145373-2d653880-d2fc-11e8-8d83-1b8780adcf7e.png)



![image](https://user-images.githubusercontent.com/25199946/47145279-eb3bf700-d2fb-11e8-8e0e-fc351e04a731.png)


}

for why I am intersted in parmeters, you know to wirte a  workflow, you need to make the script run with just like   xx.sh  param_1  param_2  param_3 ........
so I need to select the important ones and need to know the range of that.
Thanks a lot, Leon.

**Comment by leonfodoulian** [comment]
Hi @2236529177,

The plot has cell names on the x axis, and gene names on the y axis. Cells and genes are ordered based on their loadings (both positive and negative) for the given PC. Plotted colour correspond to the scaled gene expressions.

As suggested by @satijalab, it would be very helpful to read the documentation of the function. And in case of doubts, to check the source code and try to run the code line by line for a better understanding of the function. Seurat has a lot of functions, and many with various processing steps. And the easiest way to get familiarised with them is to read the code and the documentation.

Best,
Leon

**Comment by 2236529177** [comment]
Dear Leon,
I use less cell and calculate the z-score, yes, it is what you told me ,thanks a lot.
