### ISSUE TITLE
How to access an image (slice) of interest in spatial analysis

### ISSUE THREAD

**Issue by Pedramto89** [satijalab/seurat#8681]
Hello

I am doing an analysis via fgsea package and when I want to visualize the results, although I have three images (slices) stored in seurat object, I cannot access other slices and the result is just based on the first slice. I am wondering how can I make the slice of interest as default?
> summary(data@images)
         Length Class    Mode
slice1   1      VisiumV1 S4  
slice1.1 1      VisiumV1 S4  
slice1.2 1      VisiumV1 S4

**Comment by zskylarli** [comment]
Hi - for most relevant functions, there should either be a `images` or `fov` parameter that will allow you to specify the name of the image. Additionally, you can access the Image information by using data[['name_of_image"]], so for example, specifying `data[['slice1']]`. Please let me know if this helps!

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any recent activity.

If this issue is still relevant we strongly encourage you to reopen or repost it.
