### ISSUE TITLE
Inconsistent behavior of 'merge' for RNA and SCT assays

### ISSUE THREAD

**Issue by viktorfeketa** [satijalab/seurat#8687]
I noticed the inconsistent behavior of the "merge" function between "RNA" and "SCT" assays.

The context: I would like to integrate several Seurat objects (different samples) contained in the list 'seurats'.
Unfortunately, all the vignettes about integration start from a combined object containing different samples, which is then "split" into layers (by the way, it would be great if you had an official workflow for starting with individual samples in individual Seurat objects, or in a list of Seurat objects, as this seems to be a more common situations for many users). But by searching around, I found a solution in using 'merge' on the list of Seurat objects.

However, such 'merging' when the Active assay is "RNA" results in the new merged object with layers for every sample (i.e. counts, data, and scale.data for every original individual Seurat object in the original list).
'Merging' when the Active assay is "SCT" results in the new merge object with only 3 layers (counts, data, and scale.data) regardless of the number of original Seurat objects in the original list. This behavior is inconsistent.
I then "IntegrateLayers" on the resulting merged object, which seems to correctly integrate in case of "RNA" assay, and also mirrors the Integration vignettes.
However, I am worried that in case of "SCT", "IntegrateLayers" is not working properly, because there are no layers per sample, there are only 3 total layers. This also now seems to not agree with the "SCT" section of the Integration vignettes, which start with the 'split" object with multiple layers per each sample.

Please advise if this is the expected behavior of the 'merge', and what would be the workflow for integrating multiple samples using SCT and starting from a list of individual Seurat objects.

UPDATE:
Actually I just noticed that running SCTransform on the 'split' ifnb object even in the "integration_introduction" vignette still results in "collapsing" all individual sample layers into one layer. So it seems this is the expected behavior/workflow for SCT assays - could you please confirm? (namely, that it is not necessary to have individual samples in separate layers before integration in case of SCT assays).

**Comment by mhkowalski** [comment]
Hi, 

Thank you for your question and detailed explanation. Yes, you are correct, the ```merge``` behavior is different for the SCT assay, because SCT assays are still v3 assays at this point. Also, as you say, after splitting your object according to condition and running SCT, the layers will no longer be split anymore.

```IntegrateLayers``` is set up to handle this. As shown in the vignette, you'll have to pass the ```normalization.method = "SCT"``` argument to ```RPCAIntegration``` or ```CCAIntegration```, and it will handle this appropriately (i.e. will integrate cells according to how your layers were split when SCT was run).  

We will think about how we can make this more clear to the user, thanks for your feedback.
