### ISSUE TITLE
 resolution in FindClusters is Weird

### ISSUE THREAD

**Issue by 2236529177** [satijalab/seurat#869]
resolution Value of the resolution parameter, use a value above (below) 1.0 if you want to
obtain a larger (smaller) number of communities.

you used  different resultion value in tutorial, and you emphasized thta resultion may caused subdivisions  in website https://satijalab.org/seurat/pbmc3k_tutorial.html

{
 
If you perturb some of our parameter choices above (for example, setting resolution=0.8 or changing the number of PCs), you might see the CD4 T cells subdivide into two groups. You can explore this subdivision to find markers separating the two T cell subsets. However, before reclustering (which will overwrite object@ident), we can stash our renamed identities to be easily recovered later.
}

so do you have some good suggestions for this param, this param can make a world of difference.

Thanks a lot

**Comment by satijalab** [comment]
Indeed, all clustering algorithms have some parameter to govern the granularity of the clustering result. We cannot recommend a global parameter that will work for all analyses. Instead of fixing this at resolution=1 we wanted to provide our users with flexibility to identify a level of granularity that appropriately describes their dataset
