### ISSUE TITLE
Different margin in genesCLR normalization?

### ISSUE THREAD

**Issue by ccasar** [satijalab/seurat#871]
Hi,

in the method section of the Stoeckius et. al. CITE-Seq paper, the ADT CLR normalization
is performed cell-wise, while the Seurat genesCLR normalization is performed gene-wise. Is this the 'slight improvement' you mention in the multimodal vignette?

When creating *.fcs files (to identify cells by their classical cell surface markers) from the normalized ADT data I received feedback from our wet-lab scientists that the cell-wise normalization consistently looks much closer to Cytometry data you would expect from identically stained cells while the gene-wise normalized data makes it harder to gate by standard definitions of positive/negative marker expression, e.g. see plots below.

Did the cell-wise/gene-wise switch show better results for downstream analysis?

![cite_nom_cell](https://user-images.githubusercontent.com/2711108/47164777-f3466780-d2f8-11e8-9f26-aa3d51059d9b.png)
![cite_norm_genes](https://user-images.githubusercontent.com/2711108/47164776-f2add100-d2f8-11e8-9dff-ff482c935384.png)

**Comment by satijalab** [comment]
Thanks for the question!

Unfortunately there is not a single answer. In some cases, cell-based normalization fails. This is because cell-normalization makes an assumption that the total ADT counts should be constant across cells. That can become a significant issue if you have cell populations in your data, but did not add protein markers for them (this is also an issue for scRNA-seq, but is significantly mitigated because at least you measure many genes).

However, gene-based normalization can fail when there is significant heterogeneity in sequencing depth, or cell size. The optimal strategy depends on the AB panel, and heterogeneity of your sample. 

So I think you are correct to try both on your system, but this highlights the need for new normalization approaches for antibody seq data (stay tuned)
