### ISSUE TITLE
Error in match.arg(arg = value, choices = Assays(object = object)) : 'arg' should be one of "SCT", "ADT"

### ISSUE THREAD

**Issue by nicolasnunez83** [satijalab/seurat#8718]
Dear Seurat team,

I'm working on integrating CyTOF and CITE-seq data using the bridge integration functionality in the Seurat package. I'm running into an issue with the PrepareBridgeReference function and was hoping you could provide some guidance. (Sorry I only see the example for ATAC and scRNAseq and the closed issue #5697)

The error I'm encountering is:

Error in match.arg(arg = value, choices = Assays(object = object)) :
'arg' should be one of "SCT", "ADT"

I've tried the following steps to resolve the issue:

Set the default assay of the  obj.multi Seurat object to "ADT" ( bridge = obj.multi) as discussed issue #5697. (Using "pbmc_multimodal_2023.rds”).
Create a new Seurat object that combines the reference = obj.rna (“SCT data from pbmc_multimodal_2023.rds and with a new dataset).

Here some information:
ref.extend <- PrepareBridgeReference(reference = obj.rna,
normalization.method = 'LogNormalize',
bridge =  obj.multi,
reference.reduction = 'integrated_dr',
reference.dims = dims.rna,
bridge.query.assay = 'ADT',
supervised.reduction = 'spca',
bridge.query.features = adt.feature)

obj.rna
An object of class Seurat
14875 features across 7355 samples within 1 assay
Active assay: RNA (14875 features, 2000 variable features)
3 layers present: counts, data, scale.data
2 dimensional reductions calculated: pca, umap

obj.multi
An object of class Seurat
20957 features across 161764 samples within 2 assays
Active assay: ADT (228 features, 28 variable features)
3 layers present: counts, data, scale.data
1 other assay present: SCT
6 dimensional reductions calculated: apca, aumap, pca, spca, umap, wnn.umap

adt.feature
[1] "CD39" "TIGIT" "CD4-1" "CD3-1" "CD27" "CD25" "CD45RA" "CD56-1" "CD45RO" "CD11b-1" "CD38-1" "CD152" "CD206"
[14] "IgD" "CD127" "CD279" "CD278" "CD274" "CD95" "CD16" "CD14" "CD19" "CD8" "HLA-DR" "CD103" "CD57"
[27] "CD244" "CD21"

However, I'm still encountering the same error. I'm using the latest version of the Seurat package, but I wanted to check if there are any updates or fixes in that branch that could help resolve my problem.

Thank you in advance for your help. I'm looking forward to hearing from you.

Best regards,
Nicolás

**Comment by igrabski** [comment]
Hi Nicolás, it looks like your bridge object (`obj.multi`) has `ADT` and `SCT` assays, but your reference object `obj.rna` only has an `RNA` assay. For bridge integration, the bridge object needs to have one assay in common with the reference, and another assay in common with the query. In this case, you would need an assay named `SCT` in `obj.rna` (for example, by running `SCTransform`). In addition, you should make sure to set the `bridge.ref.assay` parameter in `PrepareBridgeReference` (which otherwise defaults to `RNA`). Finally, it looks like you set `reference.reduction` to `integrated_dr`, but I only see `pca` and `umap` as reductions in the output of your `obj.rna`.
