### ISSUE TITLE
FindVariableFeatures Error: 'VST.default' is not implemented yet 

### ISSUE THREAD

**Issue by myanna1416** [satijalab/seurat#8770]
Hi developers, 
I am running into the error "FindVariableFeatures Error: 'VST.default' is not implemented yet" 
This is my traceback for my error : 

<img width="615" alt="Screenshot 2024-04-13 at 1 01 17 AM" src="https://github.com/satijalab/seurat/assets/12978106/456db532-647b-4735-9850-c6b4d6c33b72">

The function that is is throwing errors from uses "vst" like this : 
```r
preprocess <- function(adata) {
  
  # Find highly variable genes similar to Seurat's approach which aligns closely with "seurat_v3"
  adata <- FindVariableFeatures(adata, selection.method = "vst", nfeatures = 3000)
  
  # Normalize data to a total expression of 10,000 per cell
  adata <- NormalizeData(adata, normalization.method = "LogNormalize", scale.factor = 10000)
  
  # Log-transform the data
  adata <- ScaleData(adata, features = rownames(adata), scale.max = 10, verbose = FALSE)
  
  # Print statement to indicate completion of preprocessing
  cat("Preprocessing completed!\n")
  
  return(adata)
}
``` 

Is there an issue with my function or maybe my data?

**Comment by mhkowalski** [comment]
Hello, 

What version of Seurat are you running? It's possible this may be an old version.

**Comment by dcollins15** [comment]
Thanks for using Seurat!

It appears that this issue has gone stale. In an effort to keep our Issues board from getting more unruly than it already is, we’re going to begin closing out issues that haven’t had any recent activity. 

If this issue is still relevant we strongly encourage you to reopen or repost it, especially if you didn’t initially receive a response from us.
