### ISSUE TITLE
Add min.pct threshold to FoldChange

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [satijalab/seurat#8785]
Hello,
I noticed while calculating log2FC values using FoldChange() that I sometimes get quite high values for the avg_log2FC, while pct.1 and pct.2 are both 0. I checked my data and found that in these instances, usually my gene was only detected once (compared to 16,000 other cells). I know in the FindAllMarkers() it is possible to set the parameter min.pct to avoid these issues in the result data where the gene was almost never detected. It would be great if you could implement something similar for FoldChange() so that I don't have to do additional manual filtering afterwards. I actually wanted to extract genes above a specific avg_log2FC value, but now I have to carefully check each gene individually to be sure that the gene was even detected in enough cells to be able to draw any conclusions from that.

**Comment by Gesmira** [comment]
Hi, 
For now, we would recommend just getting this information from the `FindMarkers()`/`FindAllMarkers()` functions and using the min.pct threshold there. Now that we have updated the differential expression method, it runs much faster so we don't see a real reason to run FoldChange only instead of FindMarkers.
