### ISSUE TITLE
AddModuleScore or PercentageFeatureSet for regression

### ISSUE THREAD

**Issue by davide-angeletti** [satijalab/seurat#8846]
Hello,

in your tutorials you use PercentageFeatureSet to identify the % of counts belonging to mitochondrial genes for each cell while the CellCycleScoring function (similarly to AddModuleScore) calculates average expression levels of the selected genes minus control feature set.

If I have a set of genes, which I want to regress our during ScaleData should I pass their percent or their score to the vars.to.regress. Results are slightly different depending on which function I use.

**Comment by longmanz** [comment]
Hi, 

You should regress out their scores instead of just percentage in general. 

In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.

We look forward to seeing your post there - thanks for using Seurat!
