### ISSUE TITLE
Skipping Normalization Step

### ISSUE THREAD

**Issue by veredyosko** [satijalab/seurat#887]
Hi
I am running Seurat on a dataset which is already normalized (log-normalized). So I think I should skip the NormalizeData step. But then I encounter problems in the downstream analysis (for example, in"FindVariableGenes").
Is there a way I can skip the normalization step and proceed with analysis?

Thank you
Vered

**Comment by satijalab** [comment]
You should be able to place log-normalized data in the @data slot and proceed with your analysis. We have received reports that FindVariableGenes can throw errors when run on log-normalized data, since outlier values can cause problems for the dispersion and density estimates. However, we have not seen this occur on data that is log-normalized

**Comment by 2236529177** [comment]
> You should be able to place log-normalized data in the `@data` slot and proceed with your analysis. We have received reports that FindVariableGenes can throw errors when run on log-normalized data, since outlier values can cause problems for the dispersion and density estimates. However, we have not seen this occur on data that is log-normalized

@satijalab,help me ,please,thanks a lot.

**Comment by veredyosko** [comment]
Thank you!
You mean - you did get reports about errors when running non-log-normalized data, but didn't when running log-normalized data?
Thanks

**Comment by satijalab** [comment]
Yes - that is correct
