### ISSUE TITLE
Issue with memory handling in Seurat v5

### ISSUE THREAD

**Issue by wudustan** [satijalab/seurat#8899]
I am currently working on a Seurat v5 object that is arround 19GB when I run `object.size()`

After various steps in preprocessing & clustering the dataset memory utilisation goes up to 80GB+ 

If I save the object, clear environment and restart the R session then read the object back in, memory utilisation is closer to 20GB and then after carrying out various function calls climbs again. 

`gc()` and manually clearing memory in in WSL2 doesn't reduce the utilisation.

I didn't experience this kind of issue with earlier versions of Seurat, I'm wondering if something has inherently changed to the way certain functions are ran? 

I've only experienced this kind of issue before when I ran lots of `lapply()` functions on large matrices in unrelated analyses.

**Comment by zskylarli** [comment]
Hi @wudustan ,

Thanks for your question! This could be due to the way that the v5 object is now structured, especially if you have multiple layers in your object, since many functions are ran by layer. In an effort to more promptly address user issues, we’ve started asking users to direct questions like this to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance based on experience with similar issues. 

We’re going to close this issue for now but strongly encourage you to repost your question in the other forum. 

We look forward to seeing your post there - thanks for using Seurat!
