### ISSUE TITLE
Problem about "split.by" when drawing Dotplot

### ISSUE THREAD

**Issue by bWl4wTkrnLEeSMJwdWZ9** [satijalab/seurat#8953]
<img width="557" alt="444242cb-5695-48ac-8666-4e4c35e321fe2" src="https://github.com/satijalab/seurat/assets/171160362/3b67312e-ad3b-47ab-907e-5d0f020de213">
<img width="557" alt="d2eee7b5-1880-4241-a6e7-06b7ceb886912" src="https://github.com/satijalab/seurat/assets/171160362/eacee01b-f7e4-4b5a-8341-c6ece9419271">

When I drawing a Dotplot using "split.by = "orig.ident"", the legend of "Average Expression" got disappeared.

**Comment by ilovegreentea** [comment]
I have a same issue...

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  That is the default behavior of Seurat's DotPlot as it only shows percent expression when using `split.by`.  For a `DotPlot` alternative that maintains expression information when splitting see `Clustered_DotPlot` function from my package scCustomize (vignette [here](https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html#clustered-dotplots).

However, it should be noted that because expression is scaled expression this can cause issues in the interpretation of the plot between groups and users should be mindful of that in their interpretation.

Best,
Sam
