### ISSUE TITLE
Where is integrated assay in Seurat v5

### ISSUE THREAD

**Issue by tewengtong** [satijalab/seurat#8967]
Dear authors:

I followed this vignette to perform the integration (https://satijalab.org/seurat/articles/seurat5_integration). Then I want to calculate kBET to evaluate the integration result, however, I do not know which assay should I use. I couldn't find any integrated assay. Would you please give me some suggestions?

Thank you so much!

**Comment by zskylarli** [comment]
Hi - `IntegrateLayers` does not return an integrated assay and only an integrated reduction, so you will not be able to run kBET on the integrated output; see more discussion on this topic here: https://github.com/satijalab/seurat/issues/5881 and https://github.com/satijalab/seurat/issues/1717. If you need to return a batch-corrected matrix, you can try other methods (not supported directly by Seurat) such as Scanorama. Otherwise, you can try to assess the integration results via methods mentioned in #5185. Thanks and feel free to redirect the issue to our Discussions board if you have further analysis questions!
