### ISSUE TITLE
AddMetaData not in the Function Reference docs

### ISSUE THREAD

**Issue by nick-youngblut** [satijalab/seurat#8992]
`Seurat::AddMetaData` is not in the [Seurat v5.1.0 function reference docs](https://satijalab.org/seurat/reference/).

Moreover, `?Seurat::AddMetaData` just prints:

```
Objects exported from other packages

Description

These objects are imported from other packages. Follow the links below to see their documentation.

SeuratObject
AddMetaData, as.Graph, as.Neighbor, as.Seurat, as.sparse, Assays, Cells, CellsByIdentities, Command, CreateAssayObject, CreateDimReducObject, CreateSeuratObject, DefaultAssay, DefaultAssay<-, Distances, Embeddings, FetchData, GetAssayData, GetImage, GetTissueCoordinates, HVFInfo, Idents, Idents<-, Images, Index, Index<-, Indices, IsGlobal, JS, JS<-, Key, Key<-, Loadings, Loadings<-, LogSeuratCommand, Misc, Misc<-, Neighbors, Project, Project<-, Radius, Reductions, RenameCells, RenameIdents, ReorderIdent, RowMergeSparseMatrices, SetAssayData, SetIdent, SpatiallyVariableFeatures, StashIdent, Stdev, SVFInfo, Tool, Tool<-, UpdateSeuratObject, VariableFeatures, VariableFeatures<-, WhichCells

Usage
components(object, ...)

x %||% y

x %iff% y
```

Lastly, it would be helpful to have a section on feature metadata (and not just cell metadata) in the [essential commands vignette](https://satijalab.org/seurat/articles/essential_commands.html).

**Comment by samuel-marsh** [comment]
Hi @nick-youngblut,

So the fact that it is not in the function reference and the result of `?Seurat::AddMetaData` are as to be expected as the function is not part of Seurat but SeuratObject and Seurat only reexports them.  The function is part of SeuratObject function reference (see [here](https://satijalab.github.io/seurat-object/reference/index.html) and if you run ?SeuratObject::AddMetaData` you will get the full manual page.

The details on adding feature level meta data can be found in manual page where it states that you need to use assay level specification when using the function (because features are stored at assay level).
```
If adding feature-level metadata, add to the Assay object (e.g. object[["RNA"]])
```

I previously posted some additional info in SeuratObject github on differences between adding feature level meta data for Assay vs. Assay5 objects (see [here](https://github.com/satijalab/seurat-object/issues/125#issuecomment-2077154225)).  I also agree would be helpful if Seurat team added this to vignette but the issues as specified in your original post are normal behavior for website and function manual.

Not member of dev team so can't speak to their priorities but I would suggest potentially making vignette update and submitting as PR for that kind of enhancement to get things going and get on their radar for changes where they can comment further and update as needed.

Best,
Sam

**Comment by nick-youngblut** [comment]
Thanks @samuel-marsh for all of the information!

> if you run ?SeuratObject::AddMetaData` you will get the full manual page

It could be helpful to include that in the function docs instead of just:

> These objects are imported from other packages. Follow the links below to see their documentation.

...given that no links are provided when running `?SeuratObject::AddMetaData` from the command line or in a Jupyter Notebook. Another approach would be to list the package names for each re-exported function (e.g., `SeuratObject::AddMetaData` instead of just `AddMetaData`).

> feature level meta data can be found in manual page

I'm curious why cell metadata is address in [essential commands vignette(https://satijalab.org/seurat/articles/essential_commands.html), but not feature metadata. This seems like an imbalance/bias in the docs. 

> I would suggest potentially making vignette update and submitting as PR

It's probably obvious that I'm new to using Seurat, so asking a naive user to write the docs is likely going to lead to inaccuracies.

Lastly, just an anecdote: I asked some members of my instititue about feature-level metadata in Seurat objects, and none seem to use it because they don't know how; so, they just keep feature-level metadata separate from the Seurat object.
