### ISSUE TITLE
RCTD celltype result to full: wrong weights matrix input

### ISSUE THREAD

**Issue by sunkunkun** [satijalab/seurat#8995]
In clusters, from sketch to full , have <NA> is ok; but RCTD result have <NA> is not ok.  if as <NA> with "unknow", the full result also have "unknow"
![image](https://github.com/satijalab/seurat/assets/44913738/9e7b05f6-0c46-4a2a-ba69-4d652bd0aade)

![image](https://github.com/satijalab/seurat/assets/44913738/0be63ab4-682f-484d-acce-20f2988c5397)

Could you please help me solve this problem?

**Comment by zskylarli** [comment]
Hi - I suspect that this is due to the RCTD having been run on a sketch of the full assay that is different from the sketched assay in the current object, or some other mismatch that will unfortunately require rerunning the entire pipeline from scratch. I understand that it may take some time but could you try to rerun RCTD on the sketched assay of the object you have now and then try to project labels again?

**Comment by Wl-Shaw** [comment]
我遇到了相同问题并成功解决。关键在于，将RCTD结果返回至Seurat对象之前，要设置默认Assay为"sketch"。
DefaultAssay(seurat_obj) <- "sketch"#注意
seurat_obj <- AddMetaData(seurat_obj, metadata = RCTD@results$results_df)
seurat_obj <- ProjectData(
  object = seurat_obj,
  assay = "Spatial.008um",
  full.reduction = "full.pca.RCTD",
  sketched.assay = "sketch",
  sketched.reduction = "pca.sketch",
  umap.model = "umap.sketch",
  dims = 1:50,
  refdata = list(full_first_type = "first_type")
)
