### ISSUE TITLE
SpatialPlots are taking ages to calculate

### ISSUE THREAD

**Issue by TdzBAS** [satijalab/seurat#9042]
HI,

I am working with stereo-seq data, for which I created a spatial object to read in the input data. However, plotting the spatial plots takes ages. I use SpatialDimPlot and SpatialFeaturePlot with default parameters, but the image is huge. Is there a way to rasterize the plot or do something else to generate the plot instantly? Currently, I am waiting almost 5 minutes for one plot.

Best,
T

**Comment by zskylarli** [comment]
Hi - in general, these plots do take a longer time to show in the RStudio viewer, and is due to the inherently denser nature of the spatial data; however, I've personally found that it could be marginally faster to immediately save them using `ggsave()` from ggplot and viewing it within your saved files instead. Please feel free to reopen if you experience any further issues, or if you suspect there is a bug in working with your object.
