### ISSUE TITLE
Is it possible to generate multi genes plot using Featurecounts

### ISSUE THREAD

**Issue by diyabasu97** [satijalab/seurat#9058]
Hi all,
I was trying to plot FeaturePlot() for multiple genes using Seurat. So, here for each gene subplot gets generated.

<img width="348" alt="featureplot" src="https://github.com/satijalab/seurat/assets/116066133/de0ef891-1229-4486-b22a-8d563e14977f">

However, is it possible to plot the multiple genes in the same plot having different colors using Seurat package? Below is the plot which I would like to generate.

<img width="451" alt="multi-gene_umap" src="https://github.com/satijalab/seurat/assets/116066133/a82273f4-f83f-440f-98c8-f2fe4a540f95">

I just want to know if its possible to generate something like this . Apologies for giving the label as bug instead of question , I am unable to edit now.

It would be great if you could help me with this. Thanks in advance.

Regards,
Diya

**Comment by longmanz** [comment]
Hi @diyabasu97,
We allow FeaturePlot() to plot two genes in a single plot by using the `blend = ` parameter. However, it does not support bleeding 3 or more genes, since it is impossible to generate a color platte for so many different colors. 

There are probably other software/packages that can do this. If you want, please feel free to post it to our [Discussions board](https://github.com/satijalab/seurat/discussions), where community members and developers can provide more targeted assistance.
