### ISSUE TITLE
Erreur on Perform DE analysis after pseudobulking

### ISSUE THREAD

**Issue by eligerges** [satijalab/seurat#9084]
Hello,

I am encountering a problem that I cannot resolve. After applying the AggregateExpression function as follows: 
pseudo_GSE195 <- AggregateExpression(GSE195_runmap, assays = "RNA", slot = "data", return.seurat = TRUE, group.by = c("Groupe", "cluster_names_GSE195")), and the following function for differential comparison: bulk.GSE1952 <- FindMarkers(object = pseudo_combined, ident.1 = "Keratenocytes_Healthy", ident.2 = "Keratenocytes_Patient", test.use = "DESeq2"), I receive the following error message: Error in ValidateCellGroups(object = object, cells.1 = cells.1, cells.2 = cells.2, : Cell group 1 has fewer than 3 cells. 
When checking the number of cells in each cluster, I find there is only 1 cell per cluster: > table(Idents(pseudo_GSE195))
example : Keratenocytes_Healthy       1
                Keratenocytes_Patient         1

I think the problem lies with the AggregateExpression function. Has anyone encountered this problem or knows the exact cause?

Thank you in advance for your help!

**Comment by mhkowalski** [comment]
Hello!

In order to perform pseduobulk analysis, you will need multiple samples within each condition (in this framework, each sample is considered to be 1 observation, rather than each cell). Do you have more than 1 "patient" or "healthy" sample? Make sure your pseudobulk analysis is split by sample if so. If not, then pseudobulk analysis is not appropriate for your data.
