### ISSUE TITLE
Error in `IntegrateLayers()`: ! None of the features provided are found in this assay

### ISSUE THREAD

**Issue by IrohaShiro** [satijalab/seurat#9098]
I'm trying to follow the vignette here https://satijalab.org/seurat/articles/integration_introduction. However, I got the following error:
```
warning: No layers found matching search pattern provided
Error in `IntegrateLayers()`:
! None of the features provided are found in this assay
```
Here is my code:
```
library(Seurat)
library(SeuratData)
library(patchwork)
ifnb <- InstallData("ifnb")
ifnb <- LoadData("ifnb")
ifnb[["RNA"]] <- split(ifnb[["RNA"]], f = ifnb$stim)
ifnb <- IntegrateLayers(object = ifnb, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca", verbose = FALSE)
```
My Seurat version is 5.1.0, SeuratObject version is 5.0.2, and SeuratData version is 0.2.2.9001.

**Comment by mhkowalski** [comment]
Hi, 

Thanks for posting! You're encountering this error because you're trying to use the `pca` reduction, but this isn't present in the object. 

If you run PCA on this object, you should be able to run `IntegrateLayers` using the code you've written.

```
ifnb <- LoadData("ifnb")
ifnb[["RNA"]] <- split(ifnb[["RNA"]], f = ifnb$stim)
ifnb <- FindVariableFeatures(ifnb)
ifnb <- ScaleData(ifnb)
ifnb <- RunPCA(ifnb)
ifnb <- IntegrateLayers(object = ifnb, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca", verbose = FALSE)
``` 

I think that this isn't the most informative error, so we will consider updating this message in the future, thanks.
