### ISSUE TITLE
Why not make order=TRUE default for FeaturePlot, OR note explicitly in documentation that the default is order=FALSE?

### ISSUE THREAD

**Issue by beazors** [satijalab/seurat#9147]
Straightforward question - I've seen the question about cells with non-zero expression values being buried by cells with zero values, since at least two Seurat versions ago. I was surprised to see that this behavior is still default. I am concerned that highlighting non-zero values is an _option that needs to be opted into_ rather than being default behavior, especially given the zero-inflation issue that is widespread in single-cell analysis.

**Comment by sup27606** [comment]
As user, I see the peril also in preferentially highlighting the highest expression cells at the top, as that also gives a false impression of abundance of the gene expression in a cluster or UMAP region. An alternative solution could be to push all the zeros to the bottom, then scramble the order of non zero expression cells and plot them on the top of the zero expression ones.

**Comment by beazors** [comment]
I take your point, and I recall shuffling being discussed [elsewhere here](https://github.com/satijalab/seurat/issues/5762). However, single-cell RNA sequencing has the issue of the majority of cells not expressing a given gene (zero inflation), meaning zeros could obscure the signal on a visualization. Perhaps choosing a dot size that allows for most of the cells to be seen (and not covered) is the ideal case.

**Comment by samuel-marsh** [comment]
Hi @beazors,

Not member of dev team but hopefully can be helpful.  I think the reason that @sup27606 points ouyt is likely the reason why order is not on by default.  Because it can give false impression.  Generally unshuffled data does give good impression (although the visualization may not be what you are looking for).  Also I would like to just point out that single cell data is not zero-inflated (see excellent paper from Valentine Svensson here: https://www.nature.com/articles/s41587-019-0379-5).

Personally, I think that overall unordered gives users best idea of potential variability in the data while optionally setting `order = TRUE` may be the better visualization for presentation (depending on the intent of visualization).

In my package scCustomize I have `order = TRUE` turned on by default because I think it is better visualization which is part of aim of package.  But in practice I often shift even that when doing initial analysis to see the data better (or use different visualization e.g. Violin or Dot plots which contain easier to visualize elements showing the distribution of expression and percent of cells expressing).

Best,
Sam

**Comment by longmanz** [comment]
Dear @beazors,
Thank you for your feedback. As @sup27606 and @samuel-marsh have pointed out (thank them for their contributions), setting `order=TRUE` can potentially bias the interpretation of gene expression levels in UMAP plots or cluster visualizations. This issue is particularly pronounced in areas with a high density of cells within a cluster or specific region.

While setting `order=FALSE` may not be ideal in all scenarios, it prevents users drawing false conclusions from the data visualization:
1. It prevents unintended misinterpretation of the data, especially for users who may not be aware of the implications of cell ordering in dense regions.
2. Users who manually set `order=TRUE` typically do so with an understanding of its effects and implications for their analysis. 
We believe this approach is more appropriate for general users. However, we're always open to further discussion on this so please feel free to re-open the issue if necessary.
