### ISSUE TITLE
What happened to FindAllMarkers() ?

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [satijalab/seurat#9148]
Hey everyone,

I am working on an object since a very long time. A few days ago I had to update R and reinstall all my packages due to a bug that I was consistently facing. After installing the latest seurat version I encountered the following issue: For the same exact object, the results I obtained after running the FindAllMarkers() were different, both in quantity and quality. The number has increased from 3132 to 46444 genes and the log2FC values have also increased (see screenshots). Importantly, the genes that were highly differentially expressed before would make also biological sense based on the dataset. Now the genes with the highest avg_log2FC values do not make sense anymore.
Does anyone face a similar issue? Any help would be more than appreciated. Thanks a lot in advance :)

edit: I noticed that the log2FC threshold has decreased, changed it back to 0.25 but still way too different results compared to the initial analysis. More parameters have been changed but I cant find the initial original definition of these parameters. 

<img width="373" alt="image" src="https://github.com/user-attachments/assets/1635b67b-6647-4a54-88a2-a6d0f1624162">

old results sorted by avg_log2FC:

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/5486f346-39b0-4f9c-9310-494becc7649b">

new results sorted by avg_log2FC:
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/d1e63f75-3c5d-4558-89fc-afd66ca4f57f">

comparison of avg_log2FC of genes before and after the update:

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/a2968395-2ede-40d2-8109-20abea82ef0d">
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/b86c721c-d718-4853-9d35-daa8a93ed18d">

**Comment by christoforos-dimitropoulos** [comment]
edit: I noticed that the log2FC threshold has decreased, changed it back to 0.25 but still way too different results compared to the initial analysis

**Comment by Alexis-Varin** [comment]
Hi,
These kind of log2fc and results typically happen when `FindMarkers()` is run on the `counts` layer (with the exception of DESeq2 method run on pseudobulk, I always run FindMarkers on 'data' layer).
 Since it seems you have updated every packages recently, I would try to check if the Seurat object you have been using for a while is still correctly loaded with Seurat v5. We can see that the percentage of expression have not moved before and after update (for example, Sell pct.1 and pct.2 are identical) so it is likely that the problem is indeed an incorrect layer.

I would try to update your Seurat object to an Assay5 class object, or try to use `NormalizeData()` again. If you are using `SCTransform`, check also if your default assay is set to `SCT`.

**Comment by longmanz** [comment]
Hi @christoforos-dimitropoulos ,
As @Alexis-Varin (thank you for the help) suggested, please go through some of the checks he mentioned to make sure the FindMarkers() is run based on the correct slot. After re-creating the Seurat object with Seurat V5, please remember to normalize your data. 

As for the logFG difference, we have updated the following things in FindMarkers() in Seurat V5:
1. some the default parameters are changed (`logfc.threshold=` changes from 0.25 to 0.1, `min.pct=` changes from 0.1 to 0.01). If you want, you can use the old default values to re-run FindMarkers(). 
2. the way we calculate avg_log2FC is changed (now we use this formula `(log(x = (rowSums(x = x) + pseudocount.use)/NCOL(x), base = base))` to calculate the log2FC, which will increase the log2FC compared to the previous Seurat v3 version. We believe the new log2FC is more accurate, since it is less affected/underestimated by the pseudo-count value). 
3. The ranking of your DE genes should be done first based on P-values and then based on logFC. Ranking it solely based on logFC will tend to capture some lowly-expressed genes (those with low pct.1 and pct.2).

**Comment by Flu09** [comment]
@longmanz how to filter downregulated genes? 
Hello, I would appreciate it if you can help

 I have used for ident.1 disease cells and for ident.2 control cells so I understand that I can later on filter by pvalue then by  log2FC for example  > 0.25

Then for the downregulated I still used for ident.1 disease cells and for ident.2 control cells how to filter by log2FC ?
