### ISSUE TITLE
Running Seurat offline

### ISSUE THREAD

**Issue by Guliariel** [satijalab/seurat#9168]
Hello, 
Since my environment does not let me run commands with big files/ lots of memory I am using interactive mode to perform different analysis. 
Unfortunately when I am working on this mode (it is like an offline mode) I am not able to run this command: 
chrom.assay <- CreateChromatinAssay(counts = counts.ls[[experim]],
                                      fragments = fragment.ls[[experim]],
                                      genome = genome,
                                      min.cells = min_cell,
                                      min.features = min_feat)
I received the error  that Seurat cannot call the genome. When I am tryin to run it not on the interactive mode it works perfectly. 
I also tried to create the SeqInfo table and set is a variable but it failed too. 
Does somebody have ay idea about this situation?
Thank you very much,

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.

I would suggest posting this to the Signac GitHub as `CreateChromatinAssay` is part of that package.  I would also suggest when posting to post full code using Seqinfo object so that devs can help figure out where the issue is when running without internet connection.

Best,
Sam
