### ISSUE TITLE
Analysis of KO vs WT cells

### ISSUE THREAD

**Issue by GabeFalcao** [satijalab/seurat#920]
Hello,

I'm working with some scRNA-seq comparing KO vs WT of a transcription factor in a specific cell type. We know from the literature that this will alter subpopulations of this cell type during de-differentiation and disease. I saw in previous questions that this is an issue running integrated analysis.  
  
I ran the analysis in both methods, the CCA and the regular merged. As expected, the CCA "blended" the cells that we expected to be "lost" due to KO. However, the regular merge, show very good clustering of all the populations, except the one that we expected to be lost, and that one was only present in the WT.

My question is, are you planning to release a new approach to potentially fix the CCA issue? Is it wrong to simply merge the WT and KO and perform the analysis in that manner? All experiments were performed in the same day/machine/protocol. The only variable is the presence or absence of that gene.

Thanks for your help!

Gabriel

**Comment by orrzor** [comment]
Hi Gabriel,

Just two quick points, the Seurat team has a new batch correction / data integration method now on bioRxiv,
https://www.biorxiv.org/content/early/2018/11/02/460147

And I would not use CCA unless you have evidence that there is a batch effect. I personally only apply batch correction methods if I have some evidence / strong suspicion that there is a batch effect. It sounds like your combined analysis makes biological sense to you, so that may already be good enough. I'd be sure to check that cells of similar type/state that you expect in both KO and WT cluster together in the simply merged data. best, Orr
