### ISSUE TITLE
how to quantify the expression of one gene in more conditions?

### ISSUE THREAD

**Issue by feanaros** [satijalab/seurat#9201]
Hi,

I have 4 experimental conditions:
**WT (2 reps)**
**KO1 (2 reps)**
**KO2 (2 reps)**
**KO3 (2 reps)**

I would like to compare the expression of WT against the 3 mutants. I want to use something similar to FindMarkers(seurat, features = "mygene"), but I want to set ident.1 = WT and ident.2 = KO1, KO2, KO3 (analyzing them together while still being able to distinguish between them). Is this possible? Additionally, is there a way to visualize the results in a heatmap with Z-scores?

Thank you!

**Comment by mhkowalski** [comment]
Hi, 

You can run `FindMarkers(obj, ident.1 = "WT", ident.2 = c("KO1", "KO2", "KO3"))`. This would calculate one test statistic for the test, but would combine all cells from the KO conditions. Because you have multiple replicates, you might look into a pseudobulk approach, where you consider each replicate as a unit of observation, rather than each cell. 

You could see our vignette [here](https://satijalab.org/seurat/articles/de_vignette) for more details. 

We don't have anything with z-scores currently implemented and I'm not exactly sure what you mean but you can plot the scaled data of differentially expressed genes using the function `DoHeatmap`, I would consult this [vignette](https://satijalab.org/seurat/articles/pbmc3k_tutorial) for details.
