### ISSUE TITLE
Can't set SCT as Default assay with FindNeighbors in Seurat v5

### ISSUE THREAD

**Issue by m85976668z** [satijalab/seurat#9207]
My workplace updated R and all the packages on the HPCC, so I have to replicate some of my Single cell analysis with Seurat V5 (was V3 before). I struggled a little bit at the beginning, but it all went well. I failed to produce the same results as before with the updated V5, and after troubleshooting and comparison of Seurat objects. I found that after I did the SCTransform, the 'FindNeighbor' function didn't really use SCTAssay, instead it used original RNA assay. It can be verified by typing 'names(obj@graphs)'. In my previous analysis, I can see two graphs with name 'SCT_nn' and 'SCT_ann'. But in the new one, it becomes 'RNA_nn' and 'RNA_ann'. I think this is the main reason that I get different UMAP plot results.
Could anyone test it and give me some feedbacks? I would love a solution

**Comment by longmanz** [comment]
Hi, 
In Seurat v5 we no longer have "assay" but instead use "layers" to store the data. If you want to use Seurat V5 with Harmony and SCTransform(), you may following this vignette:  https://satijalab.org/seurat/articles/seurat5_integration 

If you want to keep using RunHarmony() from the harmony package, then they also provided a nice tutorial to work with Seurat V5 at: https://cran.r-project.org/web/packages/harmony/vignettes/Seurat.html . However, setting "assay.use" to "SCT" might not work with Seurat v5 object since we do not have "assay". 

That being said, the best way to reproduce the exact same results as what you had previously, is to re-install Seurat v3 instead of using v5. You can following this vignette to try to re-install the older versions: https://satijalab.org/seurat/articles/install_v5
