### ISSUE TITLE
Sparse to dense conversion warning when computing PCA on BPcells backed data

### ISSUE THREAD

**Issue by abs51295** [satijalab/seurat#9271]
```r
library(Seurat)
library(BPCells)

ad = BPCells::open_matrix_anndata_hdf5(path = 'file.h5ad')
metadata = read.csv('./metadata.csv', row.names = 1)

obj = Seurat::CreateSeuratObject(counts = ad, meta.data = metadata)
obj = SetAssayData(object = obj, assay = 'RNA', layer = 'scale.data', new.data = obj@assays$RNA@layers$counts)

obj = RunPCA(obj, features = rownames(obj))

Warning: Converting to a dense matrix may use excessive memory
This message is displayed once every 8 hours.
Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 44.1 GiB”
```

Is there any way to compute PCA on sparse matrix when using BPcells in Seurat?

**Comment by JeffreyMaurer** [comment]
@abs51295 It looks like BPCells recommends to use their own function rather than Seurat's:

**Comment by mhkowalski** [comment]
Hi, 

The BPCells workflow above also runs PCA on a dense matrix, as their vignette explains. 

I don't think it makes sense to run PCA on the raw counts, as you are doing above, as PCA is sensitive to different features with different scales. We typically run PCA on a scaled and centered matrix of variable features instead, which will no longer be sparse because of centering. Using just variable features (rather than every feature) reduces the size of this matrix and is helpful for reducing noise and getting more biological signal. I hope this is helpful!
