### ISSUE TITLE
pheatmap plot of differential expression expression generated by FindMarkers

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#9278]
Hi,

I got differential expression genes generated by FindMarkers, and used them to do gsekegg enrichment.

Now I want to do pheatmap to these genes with the genes ordered by pathways.
The process is that I first extract the scaled expression matrix of these genes from seurat object, right?
When I do this by (here "cg" means genes from the pathways):
`expression_matrix <- GetAssayData(Obj_Integrate, slot = "scale.data")[cg, ]`
I got an error:
Error in GetAssayData(Obj_Integrate, slot = "scale.data")[cg, ] : 
  subscript out of bounds

Does that mean some genes not existing in the assay?

Thank you for your patience.

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  Unless you told `ScaleData` to scale all of the genes in RNA assay then it only scales the genes from variable gene list.  If you re-run `ScaleData` using all genes that should solve the issue.

Finally, I would just suggest moving to using `LayerData` instead of `GetAssayData`.  `GetAssayData` has been superseded and I suspect will eventually be deprecated.  `LayerData` should function identically.

Best,
Sam

**Comment by yulchen810** [comment]
@samuel-marsh Hi, thank you. I have scaled all genes and re-run that.
LayerData can only be used in Seurat v5. I have already almost finished data analysis in v4.
