### ISSUE TITLE
Accessor Function for Classes

### ISSUE THREAD

**Issue by DarioS** [satijalab/seurat#928]
A function such as `GetIdent` is an accessor function. I would expect to find it on the seurat class documentation page in a section titled Accessors, such as many other R packages do (e.g. [GRanges](https://github.com/Bioconductor/GenomicRanges/blob/master/man/GRanges-class.Rd)) so I can see what accessors are available for a particular class. Also, it's unusual that a function name starts with a capital letter, but the class name is lowercase. This is opposite to the convention used in popular programming languages.

**Comment by mojaveazure** [comment]
Hi Dario,

While we don't have much integrated documentation for Seurat v2.X, the next release (v3) will have much clearer documentation. For now, you can view Seurat v3.X object structure and associated methods on our [wiki](https://github.com/satijalab/seurat/wiki). Also, since R has no predefined style (like [PEP 8](https://www.python.org/dev/peps/pep-0008/) for Python), we've chosen to adopt [Google's R style guide](https://google.github.io/styleguide/Rguide.xml) for Seurat. We are currently formalizing a Seurat-specific style guide (based on Google's with expanded criteria for documentation) and will publish it on our wiki as well once completed.
