### ISSUE TITLE
Differences in SCTransform between versions 

### ISSUE THREAD

**Issue by katkatrach** [satijalab/seurat#9338]
Hello!

I wanted to reference issue #9222 where the user was seeing different results between Seurat versions but did not provide examples. I am seeing something similar so I wanted to share and make sure this doesn't have a large effect on downstream analysis. 

I usually perform clustering in Pagoda2, where I take the SCTransformed matrix to cluster and add the embeddings back into the Seurat object. 

At the same resolution for clustering (Pagoda2 k200), this is how the number of clusters changed between versions with no changes in code:
5.1.0: 79
5.0.3: 75
5.0.2: 77
5.0.1: 78

UMAP shaped changed between versions 5.0.2 and 5.0.3
5.0.1 & 5.0.2:
![image](https://github.com/user-attachments/assets/8303701b-740d-4d24-9353-697e5bd3bfc0)
5.0.3 & 5.1.0
![image](https://github.com/user-attachments/assets/1da34d7f-48b3-4667-b4ed-b9795e013a76)

I know this difference is due to clip.range changes, but I was curious if I should be worried at all about this change for my data?

I am also seeing slight label transfer differences where some cell labels are predicted differently (usually 1-50 per cell type depending on the number of cells attributed).

Any thoughts are appreciated. Thanks!

**Comment by mccormickceci** [comment]
Hello! To me this change in UMAP is not alarmingly different, but in the case that you are worried about consistency I would keep with the same older version of the package. In order to test if this is in fact a difference because of clip.range() I might set the clip range explicitly to be the same in both versions of the package and confirm that you get the same UMAP. If you still have different UMAPs it might be an indication of something else going on.
