### ISSUE TITLE
SCTransform produces NA's

### ISSUE THREAD

**Issue by weishwu** [satijalab/seurat#9355]
SCTransform produces NA's if all the cells (after QC filtering) from a sample have zero counts. This makes it impossible to draw any comparison plots against a sample where this gene has counts. Is it legitimate to change NA's to zeros in this case, or should I switch to logNormalize?

**Comment by wangbenwang123** [comment]
Hi, I'd like to get your code along with the error output.

**Comment by mhkowalski** [comment]
You could use `log-normalize` rather than `SCTransform`, but I would be cautious about making this comparison.  Not sure what you mean exactly by "sample",  but I would be hesitant to compare an experiment where you don't capture any counts for a gene to one where you do capture that gene as I imagine that could be driven by sequencing depth or other technical factors. I also might not recommend comparing the output of two different SCTransform models directly.
