### ISSUE TITLE
FeaturePlot split.by color only change in last one

### ISSUE THREAD

**Issue by yulchen810** [satijalab/seurat#9367]
Hi, seurat team:
Thank you for your work. 
I have a brief question here.
when I use `FeaturePlot(Obj, features = c("Mbp"),order = T, 
            keep.scale = "feature",split.by = "region") + 
  scale_color_gradientn(colors = plasma(n = 10, direction = -1), limits = c(0, 10))
` to plot, the plasma color only works in last group, is there any other parameter to set for this? 
Thank you a lot.

![image](https://github.com/user-attachments/assets/f2794904-27e5-4821-a209-8c88569d852f)

**Comment by samuel-marsh** [comment]
Hi,

Not member of dev team but hopefully can be helpful.  So the issue you are describing is issue with patchwork vs ggplot2 and using `+` vs `&`.

However, I would also like to point out two other issues with your code just for your information.  First, when adding `scale_color_gradientn` after the plot you are eliminating the `keep.scale` and plots will be scaled independently.  Furthermore, when specifying `limits = c(0,10)` all of the plots will be scaled 0-10 instead of true values.  This will return all of the plots being scaled the same but will be hard to interpret because the values in the plots don't go to 10 so they will only use small portion of the actual scale.

Using `theme(legend.position = "right")` to add legend pack to plots

limits 0-10
![image](https://github.com/user-attachments/assets/b7a6125e-a6b0-4093-b888-e376aefe9430)


without limits 0-10 but keep scale now gone
![image](https://github.com/user-attachments/assets/e80f4e93-7395-43b4-965e-e1adc3892be8)

Best,
Sam

**Comment by yulchen810** [comment]
@samuel-marsh Thank you. Sam
