### ISSUE TITLE
RAW DATA FOR PBMCs in Seurat V5

### ISSUE THREAD

**Issue by singhd6** [satijalab/seurat#9407]
I am utilizing the Seurat Object for analyzing the single cell data analysis in R, I am following the steps in Seurat to have a thorough understanding, however I see the analysis starts with creating the seurat object with barcodes.tsv, genes.tsv, matrix.mtx fiels from teh step #####Loading and reading the PBMC data#####
pbmc.data<-Read10X(data.dir="---/-----/----/hg19/"), i was thinking do teh single cell data analysis with  barcode, genes and matrix files or the single cell RNA seq data is processed through the fastq files, if so, could you please add the .fastq files and the preprocessing steps in the data preprocessing also, could you please provide the information of raw data .fastq files.
Happy Coding
Thank you
Divya

**Comment by mccormickceci** [comment]
Hello,
In the PBMC vignette we are working with data from the 10x experimental output (a common commercial sequencing method) which comes in the format of barcodes.tsv, genes.tsv, matrix.mtx. In order to work with this dataset, we read in the 10x data specifically using the Read10x function in Seurat. Once the data is read in we can then create a Seurat object using this data as the input to the “counts” argument. If you were working from fastq files you will first need to generate a counts matrix from your fastq files (in the format of genes as rows and cells as columns). This counts matrix can then be used to generate a Seurat object.
 Hope this helps! 
Seurat Team :)
