### ISSUE TITLE
How to analysis the DEGs between smartseq2 data and 10x data

### ISSUE THREAD

**Issue by Linxiaobuskiy** [satijalab/seurat#9451]
Hi Seurat community!

I've been contemplating this issue for a while. I'm comparing the same cell type across two datasets that used different sequencing technologies: Smart-seq2 for the control condition and 10x for the disease condition. This introduces a significant batch effect due to the technological differences. I assume that a corrected matrix should be used for DEG analysis. However, I noticed in discussions such as issue #5881 that it is often recommended to use the RNA assay for DEGs analysis, which has left me confused. How can I ensure that the DEGs reflect the biological condition (control vs. disease) rather than the sequencing technology differences?

**Comment by igrabski** [comment]
Hi, you are correct -- we don't recommend using corrected matrices for DEG analysis because it is hard to understand if those comparisons will be meaningful. It is always challenging when you have a batch effect (in this case, the technology) that is confounded with the biological condition of interest -- this is definitely somewhat of an open, analysis-based question, which we would recommend posting to the Discussions board for more community input!
