### ISSUE TITLE
Consistency for cell/gene filter thresholds in CreateSeruratObject()

### ISSUE THREAD

**Issue by ddiez** [satijalab/seurat#947]
When calling `CreateSeuratObject()` cells are kept following `num.genes > min.genes` criteria:

https://github.com/satijalab/seurat/blob/e5bace41d77b221f4f222a61a74d2efad0de49a0/R/preprocessing.R#L84

However for genes the criteria is `num.cells >= min.cells`. Although it does not typically make a lot of difference, I am wondering if this distinction is intentional or if the criteria for cells should be as well `num.genes >= min.genes`

**Comment by andrewwbutler** [comment]
Thanks for bringing this up! I think it makes sense for these to be consistent. Mostly, these were kept different in order to be consistent with older Seurat versions but seeing as 3.0 will be a major release containing breaking changes anyways, I think this is a good time to change this (and as you say, it shouldn't practically affect things much).
