### ISSUE TITLE
No package called 'mclust'; could not find function "Read10X"

### ISSUE THREAD

**Issue by mahadevanv** [satijalab/seurat#952]
Hi everyone, 

Trying to get Seurat started for 10X data analyses on my macOS Sierra 10.12.6; R version 3.5.

I have the following error:
```R
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘mclust’

Accompanied by another error:

Error in Read10X(data.dir = matDirs[i]) : 
  could not find function "Read10X"
```
Any help on this is much appreciated !

Thanks

**Comment by timoast** [comment]
Hi, it sounds like you need to install mclust (and perhaps other Seurat dependencies). See [here](https://satijalab.org/seurat/install.html) for more information about how to install Seurat.

Since loading the Seurat package failed due to missing dependencies (your first error), you can't call any of the Seurat functions (your second error).
