### ISSUE TITLE
Is it possible to attach different Seurat libraries according to RDS files made by different version of Seurat?

### ISSUE THREAD

**Issue by QuinceyLv** [satijalab/seurat#9527]
Hi, 
I have some RDS files containing Seurat objects, and they were made by different Seurat versions (4 and 5). I know the version of the object could be accessed by object@version but it needs SeuratObject, which would cause conflicts when importing another version of Seurat. I also tried .libPaths(), however conflicts of some packages such as Matirx still exists. Is there any solution?

Best, 
quincey

**Comment by rharao** [comment]
Did any error occur when you tried to load the old Seurat objects from RDS? If so, could you show the error message?

**Comment by samuel-marsh** [comment]
Hi @QuinceyLv,

Not member of dev team but hopefully can be helpful.  As @rharao mentioned if you could explain any errors better and provide full code you are running that would be greatly appreciated.  Is the need to run multiple versions of Seurat due to need to replicate analysis environments or due to errors in loading the objects?  If you are trying to maintain analysis environments with different versions of Seurat I would suggest checking out the renv package (https://rstudio.github.io/renv/) to maintain separate environments which can have different package versions.

In terms of loading and using objects there should be no issue using Seurat 5 when dealing with objects created with Seurat 4.  However, if this is case please provide more details as described above.

Best,
Sam

**Comment by QuinceyLv** [comment]
Thanks @rharao @samuel-marsh ! I would try your suggestions, and I would report errors if encountered.
