### ISSUE TITLE
`setOldClass` issue seen while getting code ready for v3 release

### ISSUE THREAD

**Issue by mjsteinbaugh** [satijalab/seurat#990]
Hi guys, I'm seeing this S4 class issue pop up in my package that defines S4 methods on the `seurat` class, when attempting to import the v3 alpha release:

```
Warning: class "seurat" is not exported by 'namespace:Seurat'
```

Is the `seurat` S4 class no longer defined in the package?

**Comment by mjsteinbaugh** [comment]
Ah okay figured this out. The S4 class has been renamed from `seurat` to `Seurat`, so code that attempts to define methods for the old `seurat` class name will break in v3. Is it possible to provide legacy support for the old `seurat` class so we can still load up old objects and update them?

For reference, this has changed in NAMESPACE:
`exportClasses(seurat)` --> `exportClasses(Seurat)`

**Comment by mojaveazure** [comment]
Hi Michael,

Just some clarification as to what's happening for reference purposes:

Seurat v3 defines two "seurat" classes, one called `seurat` for old (v2.X) versions of Seurat and one called `Seurat` for new (v3.X) versions. While it is unfortunate that the two classes differ only in capital/lowercase, we chose this implementation to allow users with old `seurat` objects the ability to upgrade their object to a new `Seurat` object with `UpdateSeuratObject`. As such, attaching Seurat v3 to your R session (`library(Seurat)`) will enable users to load both v2 and v3 objects.

If you load a v2 object while using Seurat v3, you'll get the "old seurat" description when you call the object. We haven't defined any methods for the v2 object in Seurat v3, since we will no longer support v2 objects once v3 is released to CRAN (we will provide access to an archived version of Seurat v2.3.4 for users who still need and old version of Seurat). We also don't export the class; what this means is that other packages cannot import the `seurat` class definition to extend it through S4 methods (`setMethod`) or by subclassing it (`setClass(contains = 'seurat', ...)`). People can still load objects of class `seurat` and it can be extended through S3 methods (not recommended due to deprecation of the old `seurat` object), but other packages cannot extend it through S4 techniques.

For building off of Seurat v3, we recommend using the Seurat v3 `Seurat` object. Not only can users create and interact with these objects, other packages can extend it through S3 **and** S4 techniques since we export this class. All methods in Seurat v3 are designed for the `Seurat` object, not the `seurat` object, and we provide more support for it through proper setters/accessors and taken great lengths to make our object more "R-like" through the addition of `dimnames`, `subset`, `merge`, etc.

More information about the objects presented in Seurat v3 and how to best extend them can be found in our [Developer's Guide](https://github.com/satijalab/seurat/wiki) (WIP). While we would like to ensure that all people building off of Seurat objects have a seamless update, it's very difficult to track all packages that use our objects. For the most part, we can only track packages that have been submitted to CRAN and list Seurat in "Depends", "Imports", "Suggests", or "Enhances", as only CRAN packages are tracked in this manner and we don't have another way of finding packages that utilize Seurat.

Hopefully this helps clarify what's going on behind-the-scenes and how to best prepare yourself and your tools for Seurat v3.
