### ISSUE TITLE
I met a issue when i run RunCCA using two species.

### ISSUE THREAD

**Issue by newcounts** [satijalab/seurat#992]
I have tried using seurat to compare two single-cell RNA-seq data from monky and mouse,  both are come fron one cell type, but with two different sequence method, I met no problem when i  deal with monky. But i mouse data, when i set min.cells = 1 parameter in CreateSeuratObject, there was a problem as: 
![default](https://user-images.githubusercontent.com/45653892/49572286-67ef6700-f976-11e8-9e37-fc9dbdc3f528.png), then i used a default parameter value,  error in ScaleData(). 
Can you help me see where the error is? thank you

**Comment by satijalab** [comment]
This is unrelated to CCA, but seems to be an issue with identifying variable features.

DId you first run NormalizeData? In v2, FindVariableGenes requires the @data slot to be populated with log-normalized data.

In cases where I forget to normalize first I have received an identical error, so that is likely the issue here.
